Added a way to identify HBW node using hwloc
memkind/memkind pull request #401
Opened 2020-10-30 02:27 UTC by keiya-nobuta

This patch adds the ability to identify HBW nodes using information
obtained from ACPI HMAT table via hwloc if available.

### Description

### Types of changes

- [ ] Bugfix (non-breaking change which fixes issue linked in Description above)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation (correction or otherwise)
- [ ] Cosmetics (whitespace, appearance)
- [ ] Other

### Checklist

- [x] Code compiles without errors
- [ ] All tests pass locally with my changes (see TESTING section in CONTRIBUTING file)
- [ ] Created tests which will fail without the change (if possible)
- [x] Extended the README/documentation (if necessary)
- [ ] All newly added files have proprietary license (if necessary)
- [ ] All newly added files are referenced in MANIFEST files (if necessary)

## Further comments

I tested in the same environment as issue #383

2020-10-30 08:55 UTC, michalbiesek requested changes
> Reviewed 2 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/401)* status: 2 of 3 files reviewed, 8 unresolved discussions (waiting on @keiya-nobuta)

___
*[src/memkind_hbw.c, line 345 at r1](https://reviewable.io/reviews/memkind/memkind/401#-MKsZknL26J8dp1Qp2uL:-MKsZknL26J8dp1Qp2uM:bb76xpq) ([raw file](https://github.com/memkind/memkind/blob/6cfa91374db257cd8bd1bf0501bb2a726daeb09d/src/memkind_hbw.c#L345)):*
> ```
> return MEMKIND_ERROR_UNAVAILABLE;
> ```
I would prefer to have logic from get_high_bandwidth_nodes_by_hwloc put in here.
Something like:

if(!is_hbm_legacy_supported(cpu))
  int ret = bandwidth_fill(bandwidth, get_high_bandwidth_nodes);
else
  //your logic
  int ret = bandwidth_fill(bandwidth, get_high_bandwidth_nodes_hmat);

Therefore we still support legacy CPU even if the library is built with the support of hwloc.

get_high_bandwidth_nodes_hmat:
* provides your logic if  MEMKIND_HWLOC is defined
* return MEMKIND_ERROR_UNAVAILABLE with prior some log_err message if  MEMKIND_HWLOC is not defined.

Therefore we could have MEMKIND_HWLOC used in one place.
___
*[src/memkind_hbw.c, line 353 at r1](https://reviewable.io/reviews/memkind/memkind/401#-MKsNam522Zdn42Risi3:-MKsNam522Zdn42Risi4:b-837ua) ([raw file](https://github.com/memkind/memkind/blob/6cfa91374db257cd8bd1bf0501bb2a726daeb09d/src/memkind_hbw.c#L353)):*
> ```C
> {
>     char *env = "MEMKIND_HBW_THRESHOLD";
>     char *hbw_threshold_env = secure_getenv(env);
> ```

I am aware that this is not related to your change but could you please add a comment to replace secure_getenv with memkind_get_env - this is related to fa3818f and when the change will be ported I would like not to forget about it.
___
*[src/memkind_hbw.c, line 353 at r1](https://reviewable.io/reviews/memkind/memkind/401#-MKsOC2wAwafmUYjtJYi:-MKsOC2wAwafmUYjtJYj:b-5xx2f4) ([raw file](https://github.com/memkind/memkind/blob/6cfa91374db257cd8bd1bf0501bb2a726daeb09d/src/memkind_hbw.c#L353)):*
> ```
> char
> ```
const char 
___
*[src/memkind_hbw.c, line 361 at r1](https://reviewable.io/reviews/memkind/memkind/401#-MKsNKngED_gg5KkcIlW:-MKsNKngED_gg5KkcIlX:bdmgovx) ([raw file](https://github.com/memkind/memkind/blob/6cfa91374db257cd8bd1bf0501bb2a726daeb09d/src/memkind_hbw.c#L361)):*
> ```
> valiable
> ```
variable
___
*[src/memkind_hbw.c, line 364 at r1](https://reviewable.io/reviews/memkind/memkind/401#-MKsNMOi8fA4519DqTyQ:-MKsNMOi8fA4519DqTyR:bdi7g19) ([raw file](https://github.com/memkind/memkind/blob/6cfa91374db257cd8bd1bf0501bb2a726daeb09d/src/memkind_hbw.c#L364)):*
> ```
> valiable
> ```
variable
___
*[src/memkind_hbw.c, line 368 at r1](https://reviewable.io/reviews/memkind/memkind/401#-MKsOcM71b_JzhY3qVIB:-MKsOcM71b_JzhY3qVIC:b-lccefh) ([raw file](https://github.com/memkind/memkind/blob/6cfa91374db257cd8bd1bf0501bb2a726daeb09d/src/memkind_hbw.c#L368)):*
> ```
> 200 * 1024; // Default threshold is 200 GB/s
> ```
Make this a macro please, something like
MEMKIND_HBW_THRESHOLD_DEFAULT
___
*[src/memkind_hbw.c, line 371 at r1](https://reviewable.io/reviews/memkind/memkind/401#-MKsMqqf8L3btcW8tAmo:-MKsMqqf8L3btcW8tAmp:b-by07fu) ([raw file](https://github.com/memkind/memkind/blob/6cfa91374db257cd8bd1bf0501bb2a726daeb09d/src/memkind_hbw.c#L371)):*
> ```
> hwloc_topology_init
> ```
Before return of get_high_bandwidth_nodes_by_hwloc, you should call hwloc_topology_destroy.
___
*[src/memkind_hbw.c, line 392 at r1](https://reviewable.io/reviews/memkind/memkind/401#-MKsN9yT0Po8HmLaS0fQ:-MKsN9yT0Po8HmLaS0fR:b-il9yav) ([raw file](https://github.com/memkind/memkind/blob/6cfa91374db257cd8bd1bf0501bb2a726daeb09d/src/memkind_hbw.c#L392)):*
> ```C
>             log_err("hwloc_memattr_get_best_initiator failed");
>             return MEMKIND_ERROR_UNAVAILABLE;
> 	}
> ```

spaces instead of tabs - please run ./astyle.sh script to confirm style issue


<!-- Sent from Reviewable.io -->

2020-11-02 05:21 UTC, keiya-nobuta reviewed
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/401)* status: 2 of 3 files reviewed, 8 unresolved discussions (waiting on @michalbiesek)

___
*[src/memkind_hbw.c, line 345 at r1](https://reviewable.io/reviews/memkind/memkind/401#-MKsZknL26J8dp1Qp2uL:-ML6Md2D2mHcqchFeBbN:b-k9a9ki) ([raw file](https://github.com/memkind/memkind/blob/6cfa91374db257cd8bd1bf0501bb2a726daeb09d/src/memkind_hbw.c#L345)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> return MEMKIND_ERROR_UNAVAILABLE;
> ```
I would prefer to have logic from get_high_bandwidth_nodes_by_hwloc put in here.
Something like:

if(!is_hbm_legacy_supported(cpu))
  int ret = bandwidth_fill(bandwidth, get_high_bandwidth_nodes);
else
  //your logic
  int ret = bandwidth_fill(bandwidth, get_high_bandwidth_nodes_hmat);

Therefore we still support legacy CPU even if the library is built with the support of hwloc.

get_high_bandwidth_nodes_hmat:
* provides your logic if  MEMKIND_HWLOC is defined
* return MEMKIND_ERROR_UNAVAILABLE with prior some log_err message if  MEMKIND_HWLOC is not defined.

Therefore we could have MEMKIND_HWLOC used in one place.

</blockquote></details>

OK, I remade my patch.
___
*[src/memkind_hbw.c, line 353 at r1](https://reviewable.io/reviews/memkind/memkind/401#-MKsOC2wAwafmUYjtJYi:-ML6LDBC0qUb6N6XOmvd:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/6cfa91374db257cd8bd1bf0501bb2a726daeb09d/src/memkind_hbw.c#L353)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> char
> ```
const char 
</blockquote></details>

Done.
___
*[src/memkind_hbw.c, line 353 at r1](https://reviewable.io/reviews/memkind/memkind/401#-MKsNam522Zdn42Risi3:-ML6MWcp5TbByHXqrBJV:b2nhktp) ([raw file](https://github.com/memkind/memkind/blob/6cfa91374db257cd8bd1bf0501bb2a726daeb09d/src/memkind_hbw.c#L353)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

I am aware that this is not related to your change but could you please add a comment to replace secure_getenv with memkind_get_env - this is related to fa3818f and when the change will be ported I would like not to forget about it.
</blockquote></details>

OK.
___
*[src/memkind_hbw.c, line 361 at r1](https://reviewable.io/reviews/memkind/memkind/401#-MKsNKngED_gg5KkcIlW:-ML6LE-h7OXH82xDbo4z:b-euu55f) ([raw file](https://github.com/memkind/memkind/blob/6cfa91374db257cd8bd1bf0501bb2a726daeb09d/src/memkind_hbw.c#L361)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> valiable
> ```
variable
</blockquote></details>

Oh...sorry
___
*[src/memkind_hbw.c, line 364 at r1](https://reviewable.io/reviews/memkind/memkind/401#-MKsNMOi8fA4519DqTyQ:-ML6LMdCBujnJWwCma2W:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/6cfa91374db257cd8bd1bf0501bb2a726daeb09d/src/memkind_hbw.c#L364)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> valiable
> ```
varaible
</blockquote></details>

Done.
___
*[src/memkind_hbw.c, line 368 at r1](https://reviewable.io/reviews/memkind/memkind/401#-MKsOcM71b_JzhY3qVIB:-ML6LUK5-ZFnP4k33f1e:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/6cfa91374db257cd8bd1bf0501bb2a726daeb09d/src/memkind_hbw.c#L368)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> 200 * 1024; // Default threshold is 200 GB/s
> ```
Make this a macro please, something like
MEMKIND_HBW_THRESHOLD_DEFAULT
</blockquote></details>

Done.
___
*[src/memkind_hbw.c, line 371 at r1](https://reviewable.io/reviews/memkind/memkind/401#-MKsMqqf8L3btcW8tAmo:-ML6LUcqA1ae3K07Cl9D:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/6cfa91374db257cd8bd1bf0501bb2a726daeb09d/src/memkind_hbw.c#L371)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> hwloc_topology_init
> ```
Before return of get_high_bandwidth_nodes_by_hwloc, you should call hwloc_topology_destroy.
</blockquote></details>

Done.
___
*[src/memkind_hbw.c, line 392 at r1](https://reviewable.io/reviews/memkind/memkind/401#-MKsN9yT0Po8HmLaS0fQ:-ML6LVaX4Vyf53LQ5a3K:b-opcpqz) ([raw file](https://github.com/memkind/memkind/blob/6cfa91374db257cd8bd1bf0501bb2a726daeb09d/src/memkind_hbw.c#L392)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

spaces instead of tabs - please run ./astyle.sh script to confirm style issue
</blockquote></details>

Sorry, I’ve forgotten


<!-- Sent from Reviewable.io -->

2020-11-03 11:03 UTC, michalbiesek requested changes
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/401)* status: 2 of 3 files reviewed, 5 unresolved discussions (waiting on @keiya-nobuta)

___
*[src/memkind_hbw.c, line 328 at r2](https://reviewable.io/reviews/memkind/memkind/401#-ML87yz-ChTLZvtptkUr:-ML87yz-ChTLZvtptkUs:b-4ygiwd) ([raw file](https://github.com/memkind/memkind/blob/51140aa0ea44046f757ab596ba6b6174332bcedb/src/memkind_hbw.c#L328)):*
> ```
> env
> ```
just put "MEMKIND_HBW_THRESHOLD" and remove the occurrence of env variable
___
*[src/memkind_hbw.c, line 340 at r2](https://reviewable.io/reviews/memkind/memkind/401#-ML8fDZo-kY-s6EDMeAh:-ML8fDZo-kY-s6EDMeAi:bcogole) ([raw file](https://github.com/memkind/memkind/blob/51140aa0ea44046f757ab596ba6b6174332bcedb/src/memkind_hbw.c#L340)):*
> ```
> MEMKIND_ERROR_UNAVAILABLE
> ```
MEMKIND_ERROR_ENVIRON
___
*[src/memkind_hbw.c, line 363 at r2](https://reviewable.io/reviews/memkind/memkind/401#-ML8G-D-7JV5KhAAAMuG:-ML8G-D-7JV5KhAAAMuH:b-xmdwl9) ([raw file](https://github.com/memkind/memkind/blob/51140aa0ea44046f757ab596ba6b6174332bcedb/src/memkind_hbw.c#L363)):*
> ```
> hwloc_memattr_get_best_initiator
> ```
I could be wrong with my previous review; sincerely apologize for that. Let me explain: basically, get_high_bandwidth_nodes_hmat is now responsible for pointing which NUMA Nodes are considered as High Bandwidth. Unfortunately, we did not consider the initiator and target Node - which could be worth addressing.
I mean, it is possible that target NUMA Node which is considered to be High Bandwith for one initiator, could not be High Bandwith for another initiator.

We should take a step back to the previous approach with set_closest_numanode, but as the custom implementation in hwloc support. Which should be called: only if hwloc is supported and excluding legacy architecture. set_closest_numanode is designated to fulfill : the struct vec_cpu_node **closest_numanode with correct values. The structure is responsible for mapping: CPU -> memory destination (NUMA id(s))
With hwloc, we could:
Iterate over all CPU NUMA Nodes
For each CPU NUMA Node perform operation like:
Get all Memory NUMA nodes which memory bandwidth fulfill the condition specified by "MEMKIND_HBW_THRESHOLD" - ( we could use hwloc_memattr_get_value to find all Nodes, see https://github.com/open-mpi/hwloc/blob/c978f9a74ed3d84a18d5dbb70594e85ff787d8a1/include/hwloc/memattrs.h#L225-L230 )
From the NUMA Node(s) set from the previous point, we should pick up the "closest" NUMA Node(s) in terms of the locality. ( we could use hwloc_get_local_numanode_objs and set specific CPU Node as initiator)
Last we return fulfilled the struct vec_cpu_node

I am aware that this could be a challenging task so let me know what you think, again sorry for the confusion.
___
*[src/memkind_hbw.c, line 368 at r2](https://reviewable.io/reviews/memkind/memkind/401#-ML85usa3k-Aqig-Vc4k:-ML85usa3k-Aqig-Vc4l:b-wkncc9) ([raw file](https://github.com/memkind/memkind/blob/51140aa0ea44046f757ab596ba6b6174332bcedb/src/memkind_hbw.c#L368)):*
<details><summary><i alt="summary">Quoted 7 lines of code…</i></summary>

> ```
>         err = hwloc_memattr_get_best_initiator(topology, HWLOC_MEMATTR_ID_BANDWIDTH,
>                                                target, 0, &initiator, &bandwidth);
>         if (err) {
>             log_err("hwloc_memattr_get_best_initiator failed");
>             hwloc_topology_destroy(topology);
>             return MEMKIND_ERROR_UNAVAILABLE;
>         }
> ```
</details>

There is one thing which should be included in this solution:
Imagine you have the following NUMA node configuration:
node   0   1   3
  0:  10  20  28
  1:  20  10  17
  3:  28  17  10
Which is a valid configuration and in your loop for node=2 -> target equals NULL and you return from function with  MEMKIND_ERROR_UNAVAILABLE status but basically you should just skip the missing node,
see https://github.com/memkind/memkind/commit/d25b04166acc1c61ae7de9b73459f98aaf480fce for a similar situation.
___
*[src/memkind_hbw.c, line 383 at r2](https://reviewable.io/reviews/memkind/memkind/401#-ML85V3S-Jwi7y_rx_xn:-ML85V3S-Jwi7y_rx_xo:bja3f3g) ([raw file](https://github.com/memkind/memkind/blob/51140aa0ea44046f757ab596ba6b6174332bcedb/src/memkind_hbw.c#L383)):*
> ```
> return MEMKIND_ERROR_UNAVAILABLE;
> ```
 log_err("High Bandwith NUMA nodes cannot be automatically detected.");
 return MEMKIND_ERROR_OPERATION_FAILED;


<!-- Sent from Reviewable.io -->

2020-11-05 12:37 UTC, keiya-nobuta reviewed
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/401)* status: 2 of 3 files reviewed, 5 unresolved discussions (waiting on @michalbiesek)

___
*[src/memkind_hbw.c, line 328 at r2](https://reviewable.io/reviews/memkind/memkind/401#-ML87yz-ChTLZvtptkUr:-MLN4zY3A4Ev9zSVppeD:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/51140aa0ea44046f757ab596ba6b6174332bcedb/src/memkind_hbw.c#L328)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> env
> ```
just put "MEMKIND_HBW_THRESHOLD" and remove the occurrence of env variable
</blockquote></details>

Done.
___
*[src/memkind_hbw.c, line 340 at r2](https://reviewable.io/reviews/memkind/memkind/401#-ML8fDZo-kY-s6EDMeAh:-MLN4yfwD6MNNtr8w2K-:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/51140aa0ea44046f757ab596ba6b6174332bcedb/src/memkind_hbw.c#L340)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> MEMKIND_ERROR_UNAVAILABLE
> ```
MEMKIND_ERROR_ENVIRON
</blockquote></details>

Done.
___
*[src/memkind_hbw.c, line 363 at r2](https://reviewable.io/reviews/memkind/memkind/401#-ML8G-D-7JV5KhAAAMuG:-MLN5Ni4-SiwkZIeNLdG:b-uo6uoa) ([raw file](https://github.com/memkind/memkind/blob/51140aa0ea44046f757ab596ba6b6174332bcedb/src/memkind_hbw.c#L363)):*
Sorry for the late reply (because I spent some time understanding how to use hwloc). OK, I remade my patch to using logic which iterate over all CPU NUMA Nodes, please re-review it.

> From the NUMA Node(s) set from the previous point, we should pick up the "closest" NUMA Node(s) in terms of the locality. ( we could use hwloc_get_local_numanode_objs and set specific CPU Node as initiator)
Last we return fulfilled the struct vec_cpu_node

Sorry I don't understand the above meaning, does that mean I need to modify set_closest_numanode or some functions it calls?
___
*[src/memkind_hbw.c, line 368 at r2](https://reviewable.io/reviews/memkind/memkind/401#-ML85usa3k-Aqig-Vc4k:-MLNA5gkDLbrGmTC8YLV:b5vdf04) ([raw file](https://github.com/memkind/memkind/blob/51140aa0ea44046f757ab596ba6b6174332bcedb/src/memkind_hbw.c#L368)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
>         err = hwloc_memattr_get_best_initiator(topology, HWLOC_MEMATTR_ID_BANDWIDTH,
>                                                target, 0, &initiator, &bandwidth);
>         if (err) {
>             log_err("hwloc_memattr_get_best_initiator failed");
>             hwloc_topology_destroy(topology);
>             return MEMKIND_ERROR_UNAVAILABLE;
>         }
> ```
There is one thing which should be included in this solution:
Imagine you have the following NUMA node configuration:
node   0   1   3
  0:  10  20  28
  1:  20  10  17
  3:  28  17  10
Which is a valid configuration and in your loop for node=2 -> target equals NULL and you return from function with  MEMKIND_ERROR_UNAVAILABLE status but basically you should just skip the missing node,
see https://github.com/memkind/memkind/commit/d25b04166acc1c61ae7de9b73459f98aaf480fce for a similar situation.

</blockquote></details>

Thank you for pointing out, I didn't have that perspective. I've changed the iterative logic to using hwloc, so I think it has been resolved.
___
*[src/memkind_hbw.c, line 383 at r2](https://reviewable.io/reviews/memkind/memkind/401#-ML85V3S-Jwi7y_rx_xn:-MLN2XQA71ttTozQ7gkn:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/51140aa0ea44046f757ab596ba6b6174332bcedb/src/memkind_hbw.c#L383)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> return MEMKIND_ERROR_UNAVAILABLE;
> ```
 log_err("High Bandwith NUMA nodes cannot be automatically detected.");
 return MEMKIND_ERROR_OPERATION_FAILED;
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-11-10 19:54 UTC, michalbiesek requested changes
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/401)* status: 2 of 3 files reviewed, 6 unresolved discussions (waiting on @keiya-nobuta)

___
*[src/memkind_hbw.c, line 363 at r2](https://reviewable.io/reviews/memkind/memkind/401#-ML8G-D-7JV5KhAAAMuG:-MLm_clIBmcaNjquDWD7:b-7rh2ew) ([raw file](https://github.com/memkind/memkind/blob/51140aa0ea44046f757ab596ba6b6174332bcedb/src/memkind_hbw.c#L363)):*
<details><summary><i>Previously, keiya-nobuta wrote…</i></summary><blockquote>

Sorry for the late reply (because I spent some time understanding how to use hwloc). OK, I remade my patch to using logic which iterate over all CPU NUMA Nodes, please re-review it.

> From the NUMA Node(s) set from the previous point, we should pick up the "closest" NUMA Node(s) in terms of the locality. ( we could use hwloc_get_local_numanode_objs and set specific CPU Node as initiator)
Last we return fulfilled the struct vec_cpu_node

Sorry I don't understand the above meaning, does that mean I need to modify set_closest_numanode or some functions it calls?
</blockquote></details>

Nevermind(regarding my previous comment) -  I think this could be addressed in a separate commit - FYI this needs some extensive testing like what happened if we have architecture:

```

+-------+    +-------+    +-------+    +-------+
| node3 |    | node1 |    | node2 |    | node4 |
| no-cpu|----| CPU   |----| CPU   |----| no-cpu|
| HBW   |    | DRAM  |    | DRAM  |    | HBW   |
+-------+    +-------+    +-------+    +-------+  
                              |
                              |
                          +-------+
                          | node5 |
                          | no-cpu|
                          | HBW   |
                          +-------+

```

And assuming that:

Node 3 provides expected High Bandwidth only for Node 1. 
Node 4 and Node 5 provide expected High Bandwidth only for Node 2. 
Node 4 and Node 5 cannot be considered as High Bandwidth Memory for Node1.
How MEMKIND_HBW_ALL should for example behave. 

For now, your solution looks OK.
___
*[src/memkind_hbw.c, line 332 at r3](https://reviewable.io/reviews/memkind/memkind/401#-MLmrol18-sbVbpQnjx4:-MLmrol18-sbVbpQnjx5:bi4pe06) ([raw file](https://github.com/memkind/memkind/blob/1eca078172c1a886e49f47df8e96c68f66598808/src/memkind_hbw.c#L332)):*
> ```
> pu_node
> ```
init_node -  rename it, please
I prefer to keep convention like in https://www.kernel.org/doc/html/latest/admin-guide/mm/numaperf.html
___
*[src/memkind_hbw.c, line 371 at r3](https://reviewable.io/reviews/memkind/memkind/401#-MLmswPlE7yKp5GCi3uE:-MLmswPlE7yKp5GCi3uF:b-uccqxg) ([raw file](https://github.com/memkind/memkind/blob/1eca078172c1a886e49f47df8e96c68f66598808/src/memkind_hbw.c#L371)):*
> ```
> if (hwloc_bitmap_isincluded(pu_node->cpuset, visited)) {
> ```
The whole point of the visited structure is to check if the CPU was already included right? I am not sure if this correct way...
I believe we could iterate through all NUMA Nodes and check here if this NODE is able to perform allocation

```
    struct bitmask *node_cpus = numa_allocate_cpumask();
	while ((intit_node = hwloc_get_next_obj_by_type(topology, HWLOC_OBJ_NUMANODE, intit_node)) != NULL) {
        numa_node_to_cpus(intit_node->os_index, node_cpus);
        if(numa_bitmask_weight(node_cpus) == 0) {
            printf("Node skipped %d - no CPU detected in intiator Node.", intit_node->os_index);;
        }
```
___
*[src/memkind_hbw.c, line 374 at r3](https://reviewable.io/reviews/memkind/memkind/401#-MLncEtAEVdpnv1B4B9y:-MLncEtAEVdpnv1B4B9z:b7etelc) ([raw file](https://github.com/memkind/memkind/blob/1eca078172c1a886e49f47df8e96c68f66598808/src/memkind_hbw.c#L374)):*
> ```C
>             continue;
>         }
>         hwloc_bitmap_or(visited, visited, pu_node->cpuset);
> ```

Feel free to add yourself to https://github.com/memkind/memkind/blob/master/AUTHORS
___
*[src/memkind_hbw.c, line 377 at r3](https://reviewable.io/reviews/memkind/memkind/401#-MLmsDfV5pdOWBcOPp0g:-MLmsDfW4MdjkSaWRP3_:bs26l0v) ([raw file](https://github.com/memkind/memkind/blob/1eca078172c1a886e49f47df8e96c68f66598808/src/memkind_hbw.c#L377)):*
> ```
>         initiator.type = HWLOC_LOCATION_TYPE_CPUSET;
>         initiator.location.cpuset = pu_node->cpuset;
> ```
You could use something like:

        initiator.type = HWLOC_LOCATION_TYPE_OBJECT;
        initiator.location.object = intit_node;

And get rid of "visited" structure
___
*[src/memkind_hbw.c, line 385 at r3](https://reviewable.io/reviews/memkind/memkind/401#-MLmsVHe2lor4eilDGjQ:-MLmsVHe2lor4eilDGjR:bnxt7i8) ([raw file](https://github.com/memkind/memkind/blob/1eca078172c1a886e49f47df8e96c68f66598808/src/memkind_hbw.c#L385)):*
> ```
> continue;
> ```
    log_info("Node skipped - cannot read intiator Node %d and target Node %d." , init->os_index);
    continue;
___
*[src/memkind_hbw.c, line 402 at r3](https://reviewable.io/reviews/memkind/memkind/401#-MLmscNv0ZLBusJDSwNf:-MLmscNv0ZLBusJDSwNg:berfv9l) ([raw file](https://github.com/memkind/memkind/blob/1eca078172c1a886e49f47df8e96c68f66598808/src/memkind_hbw.c#L402)):*
> ```
> Bandwith
> ```
Bandwidth


<!-- Sent from Reviewable.io -->

2020-11-11 10:52 UTC, keiya-nobuta reviewed
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/401)* status: 2 of 4 files reviewed, 6 unresolved discussions (waiting on @michalbiesek)

___
*[src/memkind_hbw.c, line 363 at r2](https://reviewable.io/reviews/memkind/memkind/401#-ML8G-D-7JV5KhAAAMuG:-MLqtEx8-gSdLnJCc8AK:belskm3) ([raw file](https://github.com/memkind/memkind/blob/51140aa0ea44046f757ab596ba6b6174332bcedb/src/memkind_hbw.c#L363)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

Nevermind(regarding my previous comment) -  I think this could be addressed in a separate commit - FYI this needs some extensive testing like what happened if we have architecture:

```

+-------+    +-------+    +-------+    +-------+
| node3 |    | node1 |    | node2 |    | node4 |
| no-cpu|----| CPU   |----| CPU   |----| no-cpu|
| HBW   |    | DRAM  |    | DRAM  |    | HBW   |
+-------+    +-------+    +-------+    +-------+  
                              |
                              |
                          +-------+
                          | node5 |
                          | no-cpu|
                          | HBW   |
                          +-------+

```

And assuming that:

Node 3 provides expected High Bandwidth only for Node 1. 
Node 4 and Node 5 provide expected High Bandwidth only for Node 2. 
Node 4 and Node 5 cannot be considered as High Bandwidth Memory for Node1.
How MEMKIND_HBW_ALL should for example behave. 

For now, your solution looks OK.

</blockquote></details>

Thanks for letting me know.
___
*[src/memkind_hbw.c, line 332 at r3](https://reviewable.io/reviews/memkind/memkind/401#-MLmrol18-sbVbpQnjx4:-MLqfc7HDoKgNyXLFxwM:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/1eca078172c1a886e49f47df8e96c68f66598808/src/memkind_hbw.c#L332)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> pu_node
> ```
init_node -  rename it, please
I prefer to keep convention like in https://www.kernel.org/doc/html/latest/admin-guide/mm/numaperf.html
</blockquote></details>

Done.
___
*[src/memkind_hbw.c, line 371 at r3](https://reviewable.io/reviews/memkind/memkind/401#-MLmswPlE7yKp5GCi3uE:-MLqhaXE0wMBc4OtavVq:b-vs60eu) ([raw file](https://github.com/memkind/memkind/blob/1eca078172c1a886e49f47df8e96c68f66598808/src/memkind_hbw.c#L371)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> if (hwloc_bitmap_isincluded(pu_node->cpuset, visited)) {
> ```
The whole point of the visited structure is to check if the CPU was already included right? I am not sure if this correct way...
I believe we could iterate through all NUMA Nodes and check here if this NODE is able to perform allocation

```
    struct bitmask *node_cpus = numa_allocate_cpumask();
	while ((intit_node = hwloc_get_next_obj_by_type(topology, HWLOC_OBJ_NUMANODE, intit_node)) != NULL) {
        numa_node_to_cpus(intit_node->os_index, node_cpus);
        if(numa_bitmask_weight(node_cpus) == 0) {
            printf("Node skipped %d - no CPU detected in intiator Node.", intit_node->os_index);;
        }
```

</blockquote></details>

I was too particular about using the functions of hwloc, but I understand your point.
___
*[src/memkind_hbw.c, line 374 at r3](https://reviewable.io/reviews/memkind/memkind/401#-MLncEtAEVdpnv1B4B9y:-MLqhq6fCFqq1044ZtZN:b23zas4) ([raw file](https://github.com/memkind/memkind/blob/1eca078172c1a886e49f47df8e96c68f66598808/src/memkind_hbw.c#L374)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

Feel free to add yourself to https://github.com/memkind/memkind/blob/master/AUTHORS
</blockquote></details>

Thank you, I added it.
___
*[src/memkind_hbw.c, line 377 at r3](https://reviewable.io/reviews/memkind/memkind/401#-MLmsDfV5pdOWBcOPp0g:-MLqiWcP8hasySrzBWBa:byqdili) ([raw file](https://github.com/memkind/memkind/blob/1eca078172c1a886e49f47df8e96c68f66598808/src/memkind_hbw.c#L377)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
>         initiator.type = HWLOC_LOCATION_TYPE_CPUSET;
>         initiator.location.cpuset = pu_node->cpuset;
> ```
You could use something like:

        initiator.type = HWLOC_LOCATION_TYPE_OBJECT;
        initiator.location.object = intit_node;

And get rid of "visited" structure
</blockquote></details>

I agree with your point, but the above is not working in my environment. I think HWLOC_LOCATION_TYPE_OBJECT is probably not supported because initiator type is set  to HWLOC_LOCATION_TYPE_CPUSET on setting the HWLOC_MEMATTR_ID_BANDWIDTH attribute.

https://github.com/open-mpi/hwloc/blob/a10b9e7b3afc2de3487354b6a86f49492538e1c3/hwloc/topology-linux.c#L3266-L3269
https://github.com/open-mpi/hwloc/blob/a10b9e7b3afc2de3487354b6a86f49492538e1c3/hwloc/topology-linux.c#L3559-L3567

Should I contact the hwloc community first?
___
*[src/memkind_hbw.c, line 385 at r3](https://reviewable.io/reviews/memkind/memkind/401#-MLmsVHe2lor4eilDGjQ:-MLqrN2y3owZhi61sAUa:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/1eca078172c1a886e49f47df8e96c68f66598808/src/memkind_hbw.c#L385)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> continue;
> ```
    log_info("Node skipped - cannot read intiator Node %d and target Node %d." , init->os_index);
    continue;
</blockquote></details>

Done.
___
*[src/memkind_hbw.c, line 402 at r3](https://reviewable.io/reviews/memkind/memkind/401#-MLmscNv0ZLBusJDSwNf:-MLqrR-dC3EkrukBniXC:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/1eca078172c1a886e49f47df8e96c68f66598808/src/memkind_hbw.c#L402)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> Bandwith
> ```
Bandwidth
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-11-16 07:44 UTC, michalbiesek approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/401#-:-MMF-rheAShV3OMO2vWA:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @keiya-nobuta)

___
*[src/memkind_hbw.c, line 377 at r3](https://reviewable.io/reviews/memkind/memkind/401#-MLmsDfV5pdOWBcOPp0g:-MMEzlA9-Jfhi-R5dg_C:b-ke9yax) ([raw file](https://github.com/memkind/memkind/blob/1eca078172c1a886e49f47df8e96c68f66598808/src/memkind_hbw.c#L377)):*
<details><summary><i>Previously, keiya-nobuta wrote…</i></summary><blockquote>

I agree with your point, but the above is not working in my environment. I think HWLOC_LOCATION_TYPE_OBJECT is probably not supported because initiator type is set  to HWLOC_LOCATION_TYPE_CPUSET on setting the HWLOC_MEMATTR_ID_BANDWIDTH attribute.

https://github.com/open-mpi/hwloc/blob/a10b9e7b3afc2de3487354b6a86f49492538e1c3/hwloc/topology-linux.c#L3266-L3269
https://github.com/open-mpi/hwloc/blob/a10b9e7b3afc2de3487354b6a86f49492538e1c3/hwloc/topology-linux.c#L3559-L3567

Should I contact the hwloc community first?
</blockquote></details>

Yes, please - I was not aware of this kind of limitation in hwloc and I thought that HWLOC_LOCATION_TYPE_CPUSET and HWLOC_LOCATION_TYPE_OBJECT may be used interchangeably in our context of usage.


<!-- Sent from Reviewable.io -->

2020-11-16 08:37 UTC, merged

2020-11-16 11:33 UTC, keiya-nobuta commented
___
*[src/memkind_hbw.c, line 377 at r3](https://reviewable.io/reviews/memkind/memkind/401#-MLmsDfV5pdOWBcOPp0g:-MMFn5ms-lTBIzU84duR:b-dm2sei) ([raw file](https://github.com/memkind/memkind/blob/1eca078172c1a886e49f47df8e96c68f66598808/src/memkind_hbw.c#L377)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

Yes, please - I was not aware of this kind of limitation in hwloc and I thought that HWLOC_LOCATION_TYPE_CPUSET and HWLOC_LOCATION_TYPE_OBJECT may be used interchangeably in our context of usage.
</blockquote></details>

FYI: I got a reply right away https://github.com/open-mpi/hwloc/issues/433


<!-- Sent from Reviewable.io -->

2020-11-16 14:30 UTC, bgoglin commented
On KNL, the HBM bandwidth of a single MCDRAM NUMA node in SNC4 mode is ~90GB/s. Not sure it matters here but it wouldn't match your test bw>200.

By the way, hwloc exposes "hardwired" HMAT bandwidth for KNL (90GB/s for DDR, divided by number of SNCs ; 360 for HBM, divided by number of SNCs). I didn't check whether this could be an issue in your code with respect to the existing KNL-specific code.

2020-11-17 08:15 UTC, keiya-nobuta commented
@bgoglin Thank you for the information. The current memkind code uses the existing code if identified the KNL from cpuid. In that case, the threshold logic in my patch is not used.