add new MEMKIND_HIGHEST_CAPACITY kind
memkind/memkind pull request #415
Opened 2020-12-07 12:04 UTC by bratpiorka

### Description

### Types of changes

- [ ] Bugfix (non-breaking change which fixes issue linked in Description above)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Documentation (correction or otherwise)
- [ ] Cosmetics (whitespace, appearance)
- [ ] Other

### Checklist

- [x] Code compiles without errors
- [x] All tests pass locally with my changes (see TESTING section in CONTRIBUTING file)
- [x] Created tests which will fail without the change (if possible)
- [x] Extended the README/documentation (if necessary)
- [x] All newly added files have proprietary license (if necessary)
- [x] All newly added files are referenced in MANIFEST files (if necessary)

## Further comments

2020-12-07 12:47 UTC, michalbiesek requested changes
> Reviewed 12 of 17 files at r1.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/415)* status: 12 of 17 files reviewed, 17 unresolved discussions (waiting on @bratpiorka)

___
*[AUTHORS, line 27 at r1](https://reviewable.io/reviews/memkind/memkind/415#-MNx9eCEBtM1RKUHSdKo:-MNx5YQ_0sWD5onJVvs5:b8rx2yo) ([raw file](https://github.com/memkind/memkind/blob/b1f00664106edb06c95712e1e6cd904da86c26ed/AUTHORS#L27)):*
> ```
> Yuan Zhou <yuan.zhou@intel.com>
> Harald Servat <harald.servat@intel.com>
> Rafal Rudnicki <rafal.rudnicki@intel.com>
> ```

Please add an empty line at the end of this file
___
*[MANIFEST, line 60 at r1](https://reviewable.io/reviews/memkind/memkind/415#-MNx5bjk4eWuKu9g3L39:-MNx5bjlDJnNfwis6NCN:b-wzjtxx) ([raw file](https://github.com/memkind/memkind/blob/b1f00664106edb06c95712e1e6cd904da86c26ed/MANIFEST#L60)):*
> ```
> include/memkind/internal/memkind_private.h
> include/memkind/internal/memkind_regular.h
> include/memkind/internal/memkind_hmat.h
> ```

alphabetical order
___
*[MANIFEST, line 424 at r1](https://reviewable.io/reviews/memkind/memkind/415#-MNx5fBiCNMMlZlt1Qu-:-MNx5fBiCNMMlZlt1Qu0:b3kqx) ([raw file](https://github.com/memkind/memkind/blob/b1f00664106edb06c95712e1e6cd904da86c26ed/MANIFEST#L424)):*
> ```
> src/memkind_pmem.c
> src/memkind_regular.c
> src/memkind_hmat.c
> ```

.
___
*[MANIFEST, line 512 at r1](https://reviewable.io/reviews/memkind/memkind/415#-MNx5h_7EjTD7W0yAIuL:-MNx5h_7EjTD7W0yAIuM:b3kqx) ([raw file](https://github.com/memkind/memkind/blob/b1f00664106edb06c95712e1e6cd904da86c26ed/MANIFEST#L512)):*
> ```
> test/memkind-slts.ts
> test/memkind_dax_kmem_test.cpp
> test/memkind_hmat_tests.cpp
> ```

.
___
*[Makefile.am, line 24 at r1](https://reviewable.io/reviews/memkind/memkind/415#-MNx5ip11CQrLyb4hXdU:-MNx5ip11CQrLyb4hXdV:b3kqx) ([raw file](https://github.com/memkind/memkind/blob/b1f00664106edb06c95712e1e6cd904da86c26ed/Makefile.am#L24)):*
> ```Makefile
>                         src/memkind_pmem.c \
>                         src/memkind_regular.c \
>                         src/memkind_hmat.c \
> ```

.
___
*[memkind.spec.mk, line 181 at r1](https://reviewable.io/reviews/memkind/memkind/415#-MNx5jh51jyJcbebx20Y:-MNx5jh678cz1EK794_K:b3kqx) ([raw file](https://github.com/memkind/memkind/blob/b1f00664106edb06c95712e1e6cd904da86c26ed/memkind.spec.mk#L181)):*
> ```Makefile
> $(memkind_test_dir)/gb_page_tests_bind_policy
> $(memkind_test_dir)/filter_memkind
> ${memkind_test_dir}/hmat_test
> ```

.
___
*[include/memkind_allocator.h, line 125 at r1](https://reviewable.io/reviews/memkind/memkind/415#-MNx5rjG5BTRjhXK85FE:-MNx5rjG5BTRjhXK85FF:bllj09h) ([raw file](https://github.com/memkind/memkind/blob/b1f00664106edb06c95712e1e6cd904da86c26ed/include/memkind_allocator.h#L125)):*
> ```
> _kind = MEMKIND_HIGHEST_CAPACITY;
> ```
update memkindallocator.3
___
*[man/memkind.3, line 683 at r1](https://reviewable.io/reviews/memkind/memkind/415#-MNx89aU2CSgSTKBEZJu:-MNx89aV1xDhVc7ZhCG0:b-34umlh) ([raw file](https://github.com/memkind/memkind/blob/b1f00664106edb06c95712e1e6cd904da86c26ed/man/memkind.3#L683)):*
> ```
> node
> ```
node(s)
___
*[src/memkind_hmat.c, line 4 at r1](https://reviewable.io/reviews/memkind/memkind/415#-MNxBkp_BcU_8W6if7oc:-MNxBkpa38MAtkePP9Yh:b-o1igqa) ([raw file](https://github.com/memkind/memkind/blob/b1f00664106edb06c95712e1e6cd904da86c26ed/src/memkind_hmat.c#L4)):*
<details><summary><i alt="summary">Quoted 8 lines of code…</i></summary>

> ```
> #include <memkind/internal/memkind_bandwidth.h>
> #include <memkind/internal/memkind_dax_kmem.h>
> #include <memkind/internal/memkind_default.h>
> #include <memkind/internal/memkind_arena.h>
> #include <memkind/internal/memkind_private.h>
> #include <memkind/internal/memkind_log.h>
> #include <memkind/internal/heap_manager.h>
> #include "config.h"
> ```
</details>

#include <memkind/internal/memkind_arena.h>
#include <memkind/internal/memkind_default.h>
#include <memkind/internal/memkind_private.h>
#include <memkind/internal/memkind_log.h>

#include <numa.h>
___
*[src/memkind_hmat.c, line 36 at r1](https://reviewable.io/reviews/memkind/memkind/415#-MNxATuj2p5ESGPAS1sd:-MNxATuj2p5ESGPAS1se:b95jzbq) ([raw file](https://github.com/memkind/memkind/blob/b1f00664106edb06c95712e1e6cd904da86c26ed/src/memkind_hmat.c#L36)):*
> ```
>  numa_bitmask_clearall(g->numa_nodes);
> ```
See my comment from #412
___
*[src/memkind_hmat.c, line 39 at r1](https://reviewable.io/reviews/memkind/memkind/415#-MNx6U_Z2NdR9MZGA2RC:-MNx6U_Z2NdR9MZGA2RD:b-qnjuqp) ([raw file](https://github.com/memkind/memkind/blob/b1f00664106edb06c95712e1e6cd904da86c26ed/src/memkind_hmat.c#L39)):*
> ```
> numa_node_size64
> ```
nit: please check against error (value -1) and call continue if the current is equal to -1
___
*[src/memkind_hmat.c, line 46 at r1](https://reviewable.io/reviews/memkind/memkind/415#-MNx7oqd6hB8cbQQkM6v:-MNx7oqeDAtaagthQQsf:bdqixpa) ([raw file](https://github.com/memkind/memkind/blob/b1f00664106edb06c95712e1e6cd904da86c26ed/src/memkind_hmat.c#L46)):*
> ```
> if
> ```
else if
___
*[test/memkind_hmat_tests.cpp, line 50 at r1](https://reviewable.io/reviews/memkind/memkind/415#-MNx6h_nEMcXWCJ8u_wT:-MNx6h_nEMcXWCJ8u_wU:b-pqa6x4) ([raw file](https://github.com/memkind/memkind/blob/b1f00664106edb06c95712e1e6cd904da86c26ed/test/memkind_hmat_tests.cpp#L50)):*
> ```
>  get_mempolicy
> ```
check if this is succeed 
___
*[test/memkind_hmat_tests.cpp, line 94 at r1](https://reviewable.io/reviews/memkind/memkind/415#-MNx6aQG-SS64yBI-VzL:-MNx6aQG-SS64yBI-VzM:b-jgwcra) ([raw file](https://github.com/memkind/memkind/blob/b1f00664106edb06c95712e1e6cd904da86c26ed/test/memkind_hmat_tests.cpp#L94)):*
> ```
>             // TODO DEBUG
>             printf("numa: %i, free: %lld\n", i, numa_free);
>             fflush(stdout);
> ```
?
___
*[test/memkind_hmat_tests.cpp, line 113 at r1](https://reviewable.io/reviews/memkind/memkind/415#-MNx6bn8C6SD6Iu6cGh1:-MNx6bn8C6SD6Iu6cGh2:b-kzdjwx) ([raw file](https://github.com/memkind/memkind/blob/b1f00664106edb06c95712e1e6cd904da86c26ed/test/memkind_hmat_tests.cpp#L113)):*
> ```
>   // TODO DEBUG
> ```
?
___
*[test/memkind_hmat_tests.cpp, line 130 at r1](https://reviewable.io/reviews/memkind/memkind/415#-MNx6cla-Ri53rt1xAHk:-MNx6cla-Ri53rt1xAHl:b-q4u0cn) ([raw file](https://github.com/memkind/memkind/blob/b1f00664106edb06c95712e1e6cd904da86c26ed/test/memkind_hmat_tests.cpp#L130)):*
> ```
>         // TODO DEBUG
>         printf("do alloc on swap\n");
>         fflush(stdout);
> ```
?
___
*[test/memkind_hmat_tests.cpp, line 138 at r1](https://reviewable.io/reviews/memkind/memkind/415#-MNx6dWLBVpi9Fbd_RMg:-MNx6dWLBVpi9Fbd_RMh:b-3om6db) ([raw file](https://github.com/memkind/memkind/blob/b1f00664106edb06c95712e1e6cd904da86c26ed/test/memkind_hmat_tests.cpp#L138)):*
> ```
>     // TODO DEBUG
>     printf("free\n");
>     fflush(stdout);
> ```
?


<!-- Sent from Reviewable.io -->

2020-12-07 13:17 UTC, bratpiorka reviewed
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/415)* status: 5 of 25 files reviewed, 16 unresolved discussions (waiting on @michalbiesek)

___
*[AUTHORS, line 27 at r1](https://reviewable.io/reviews/memkind/memkind/415#-MNx9eCEBtM1RKUHSdKo:-MNxJxNm0zJUbnfvnaFh:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/b1f00664106edb06c95712e1e6cd904da86c26ed/AUTHORS#L27)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

Please add an empty line at the end of this file
</blockquote></details>

Done.
___
*[MANIFEST, line 60 at r1](https://reviewable.io/reviews/memkind/memkind/415#-MNx5bjk4eWuKu9g3L39:-MNxJzgE2h_tdw1vwxTH:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/b1f00664106edb06c95712e1e6cd904da86c26ed/MANIFEST#L60)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

alphabetical order
</blockquote></details>

Done.
___
*[MANIFEST, line 424 at r1](https://reviewable.io/reviews/memkind/memkind/415#-MNx5fBiCNMMlZlt1Qu-:-MNxK-q_34QAZB--tzMw:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/b1f00664106edb06c95712e1e6cd904da86c26ed/MANIFEST#L424)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[MANIFEST, line 512 at r1](https://reviewable.io/reviews/memkind/memkind/415#-MNx5h_7EjTD7W0yAIuL:-MNxKXCi5HbVrH13ejd2:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/b1f00664106edb06c95712e1e6cd904da86c26ed/MANIFEST#L512)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[Makefile.am, line 24 at r1](https://reviewable.io/reviews/memkind/memkind/415#-MNx5ip11CQrLyb4hXdU:-MNxKZMm9qXebQGIqUC0:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/b1f00664106edb06c95712e1e6cd904da86c26ed/Makefile.am#L24)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[memkind.spec.mk, line 181 at r1](https://reviewable.io/reviews/memkind/memkind/415#-MNx5jh51jyJcbebx20Y:-MNxKa8U1-tj9vbfz3vh:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/b1f00664106edb06c95712e1e6cd904da86c26ed/memkind.spec.mk#L181)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[include/memkind_allocator.h, line 125 at r1](https://reviewable.io/reviews/memkind/memkind/415#-MNx5rjG5BTRjhXK85FE:-MNxKbdn3_wsm7sjvimg:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/b1f00664106edb06c95712e1e6cd904da86c26ed/include/memkind_allocator.h#L125)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> _kind = MEMKIND_HIGHEST_CAPACITY;
> ```
update memkindallocator.3
</blockquote></details>

Done.
___
*[man/memkind.3, line 683 at r1](https://reviewable.io/reviews/memkind/memkind/415#-MNx89aU2CSgSTKBEZJu:-MNxKcfW4TyscLYm1_bl:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/b1f00664106edb06c95712e1e6cd904da86c26ed/man/memkind.3#L683)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> node
> ```
node(s)
</blockquote></details>

Done.
___
*[src/memkind_hmat.c, line 4 at r1](https://reviewable.io/reviews/memkind/memkind/415#-MNxBkp_BcU_8W6if7oc:-MNxKe-W1IlAILRIdShx:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/b1f00664106edb06c95712e1e6cd904da86c26ed/src/memkind_hmat.c#L4)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> #include <memkind/internal/memkind_bandwidth.h>
> #include <memkind/internal/memkind_dax_kmem.h>
> #include <memkind/internal/memkind_default.h>
> #include <memkind/internal/memkind_arena.h>
> #include <memkind/internal/memkind_private.h>
> #include <memkind/internal/memkind_log.h>
> #include <memkind/internal/heap_manager.h>
> #include "config.h"
> ```
#include <memkind/internal/memkind_arena.h>
#include <memkind/internal/memkind_default.h>
#include <memkind/internal/memkind_private.h>
#include <memkind/internal/memkind_log.h>

#include <numa.h>
</blockquote></details>

Done.
___
*[src/memkind_hmat.c, line 36 at r1](https://reviewable.io/reviews/memkind/memkind/415#-MNxATuj2p5ESGPAS1sd:-MNxLLpv9fjK3K60AnKV:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/b1f00664106edb06c95712e1e6cd904da86c26ed/src/memkind_hmat.c#L36)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
>  numa_bitmask_clearall(g->numa_nodes);
> ```
See my comment from #412
</blockquote></details>

Done.
___
*[src/memkind_hmat.c, line 46 at r1](https://reviewable.io/reviews/memkind/memkind/415#-MNx7oqd6hB8cbQQkM6v:-MNxKhfh-Tas5XpQWbvo:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/b1f00664106edb06c95712e1e6cd904da86c26ed/src/memkind_hmat.c#L46)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> if
> ```
else if
</blockquote></details>

Done.
___
*[test/memkind_hmat_tests.cpp, line 50 at r1](https://reviewable.io/reviews/memkind/memkind/415#-MNx6h_nEMcXWCJ8u_wT:-MNxKk8i2wiDFKUwyMi4:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/b1f00664106edb06c95712e1e6cd904da86c26ed/test/memkind_hmat_tests.cpp#L50)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
>  get_mempolicy
> ```
check if this is succeed 
</blockquote></details>

Done.
___
*[test/memkind_hmat_tests.cpp, line 94 at r1](https://reviewable.io/reviews/memkind/memkind/415#-MNx6aQG-SS64yBI-VzL:-MNxKlPY7g8957kQWWix:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/b1f00664106edb06c95712e1e6cd904da86c26ed/test/memkind_hmat_tests.cpp#L94)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
>             // TODO DEBUG
>             printf("numa: %i, free: %lld\n", i, numa_free);
>             fflush(stdout);
> ```
?
</blockquote></details>

Done.
___
*[test/memkind_hmat_tests.cpp, line 113 at r1](https://reviewable.io/reviews/memkind/memkind/415#-MNx6bn8C6SD6Iu6cGh1:-MNxKljE867_EL79ud4w:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/b1f00664106edb06c95712e1e6cd904da86c26ed/test/memkind_hmat_tests.cpp#L113)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
>   // TODO DEBUG
> ```
?
</blockquote></details>

Done.
___
*[test/memkind_hmat_tests.cpp, line 130 at r1](https://reviewable.io/reviews/memkind/memkind/415#-MNx6cla-Ri53rt1xAHk:-MNxKm8g4D57jxtMy4ze:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/b1f00664106edb06c95712e1e6cd904da86c26ed/test/memkind_hmat_tests.cpp#L130)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
>         // TODO DEBUG
>         printf("do alloc on swap\n");
>         fflush(stdout);
> ```
?
</blockquote></details>

Done.
___
*[test/memkind_hmat_tests.cpp, line 138 at r1](https://reviewable.io/reviews/memkind/memkind/415#-MNx6dWLBVpi9Fbd_RMg:-MNxKmU47HUJyhxB6ar0:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/b1f00664106edb06c95712e1e6cd904da86c26ed/test/memkind_hmat_tests.cpp#L138)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
>     // TODO DEBUG
>     printf("free\n");
>     fflush(stdout);
> ```
?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-12-07 13:58 UTC, michalbiesek requested changes
> Reviewed 1 of 17 files at r1, 9 of 19 files at r2.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/415)* status: 15 of 25 files reviewed, 8 unresolved discussions (waiting on @bratpiorka and @michalbiesek)

___
*[AUTHORS, line 10 at r2](https://reviewable.io/reviews/memkind/memkind/415#-MNxRHdl4MPqUQ5hIWpl:-MNxRHdmBRhWYtUhrEjH:b-8kkiw) ([raw file](https://github.com/memkind/memkind/blob/b7f53199626e05484768f2845488c97f56dd8400/AUTHORS#L10)):*
> ```
> Krzysztof Kulakowski <krzysztof.kulakowski@intel.com>
> Rafael Aquini <aquini@redhat.com>
> Alexandr Konovalov <alexandr.konovalov@intel.com>
> ```

Please rebase to upstream/hmat-devel and resolve the conflicts.
___
*[MANIFEST, line 424 at r2](https://reviewable.io/reviews/memkind/memkind/415#-MNxRoK-1e-G_i_aJHgm:-MNxRoK-1e-G_i_aJHgn:b63s6xa) ([raw file](https://github.com/memkind/memkind/blob/b7f53199626e05484768f2845488c97f56dd8400/MANIFEST#L424)):*
> ```
> src/memkind_hmat.c
> ```
Between src/memkind_hbw.c and src/memkind_hugetlb.c please
___
*[Makefile.am, line 24 at r1](https://reviewable.io/reviews/memkind/memkind/415#-MNx5ip11CQrLyb4hXdU:-MNxQIMJ0Q_cLd6VCtaD:b-oez2ui) ([raw file](https://github.com/memkind/memkind/blob/b1f00664106edb06c95712e1e6cd904da86c26ed/Makefile.am#L24)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Nope, Between src/memkind_hbw.c and src/memkind_hugetlb.c please
___
*[Makefile.am, line 504 at r2](https://reviewable.io/reviews/memkind/memkind/415#-MNxRbSX3ZmOcdTuq3NZ:-MNxRbSX3ZmOcdTuq3N_:bv6cqlr) ([raw file](https://github.com/memkind/memkind/blob/b7f53199626e05484768f2845488c97f56dd8400/Makefile.am#L504)):*
> ```
> unit_tests_highcapacity: checkprogs
> 	test/test_highcapacity.sh
> ```
actually, this is not needed you don't have test_highcapacity.sh - you could remove this new target
___
*[copying_headers/MANIFEST.freeBSD, line 74 at r2](https://reviewable.io/reviews/memkind/memkind/415#-MNxQCEBCEN-CM_qHSee:-MNxQCEBCEN-CM_qHSef:b63s6xa) ([raw file](https://github.com/memkind/memkind/blob/b7f53199626e05484768f2845488c97f56dd8400/copying_headers/MANIFEST.freeBSD#L74)):*
> ```
> src/memkind_hmat.c
> ```
Between src/memkind_hbw.c and src/memkind_hugetlb.c please
___
*[man/memkindallocator.3, line 48 at r2](https://reviewable.io/reviews/memkind/memkind/415#-MNxTCyu4h-_zGbKWA2S:-MNxTCyu4h-_zGbKWA2T:b-9ce8fm) ([raw file](https://github.com/memkind/memkind/blob/b7f53199626e05484768f2845488c97f56dd8400/man/memkindallocator.3#L48)):*
> ```
> satifies
> ```
satisfies 
___
*[src/memkind_hmat.c, line 36 at r1](https://reviewable.io/reviews/memkind/memkind/415#-MNxATuj2p5ESGPAS1sd:-MNxPpuxCQGe2IoX1nsS:b-klmxbv) ([raw file](https://github.com/memkind/memkind/blob/b1f00664106edb06c95712e1e6cd904da86c26ed/src/memkind_hmat.c#L36)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Nope. The numa_bitmask_clearall call is still here and IMHO is obsolete.
___
*[test/allocate_to_max_stress_test.cpp, line 143 at r2](https://reviewable.io/reviews/memkind/memkind/415#-MNxSC1V7LZ7vg9dDAAt:-MNxSC1V7LZ7vg9dDAAu:b-edhs9a) ([raw file](https://github.com/memkind/memkind/blob/b7f53199626e05484768f2845488c97f56dd8400/test/allocate_to_max_stress_test.cpp#L143)):*
> ```
>  kinds.enable_type(AllocatorTypes::MEMKIND_HIGHEST_CAPACITY);
> ```
I think for this case in test support memkind_highcapacity_test would do the job.
We could add support for these new kinds in other tests later (as we spoke offline)


<!-- Sent from Reviewable.io -->

2020-12-07 14:25 UTC, bratpiorka reviewed
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/415)* status: 7 of 19 files reviewed, 8 unresolved discussions (waiting on @michalbiesek)

___
*[AUTHORS, line 10 at r2](https://reviewable.io/reviews/memkind/memkind/415#-MNxRHdl4MPqUQ5hIWpl:-MNx_tVvEvURs5JG1Eo9:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/b7f53199626e05484768f2845488c97f56dd8400/AUTHORS#L10)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

Please rebase to upstream/hmat-devel and resolve the conflicts.
</blockquote></details>

Done.
___
*[MANIFEST, line 424 at r2](https://reviewable.io/reviews/memkind/memkind/415#-MNxRoK-1e-G_i_aJHgm:-MNx_u3aClVHuY2wqN-8:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/b7f53199626e05484768f2845488c97f56dd8400/MANIFEST#L424)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> src/memkind_hmat.c
> ```
Between src/memkind_hbw.c and src/memkind_hugetlb.c please

</blockquote></details>

Done.
___
*[Makefile.am, line 504 at r2](https://reviewable.io/reviews/memkind/memkind/415#-MNxRbSX3ZmOcdTuq3NZ:-MNx_vB2C2mIT6nAhM4z:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/b7f53199626e05484768f2845488c97f56dd8400/Makefile.am#L504)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> unit_tests_highcapacity: checkprogs
> 	test/test_highcapacity.sh
> ```
actually, this is not needed you don't have test_highcapacity.sh - you could remove this new target
</blockquote></details>

Done.
___
*[copying_headers/MANIFEST.freeBSD, line 74 at r2](https://reviewable.io/reviews/memkind/memkind/415#-MNxQCEBCEN-CM_qHSee:-MNx_vyAETVgVNBIWu1y:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/b7f53199626e05484768f2845488c97f56dd8400/copying_headers/MANIFEST.freeBSD#L74)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> src/memkind_hmat.c
> ```
Between src/memkind_hbw.c and src/memkind_hugetlb.c please

</blockquote></details>

Done.
___
*[man/memkindallocator.3, line 48 at r2](https://reviewable.io/reviews/memkind/memkind/415#-MNxTCyu4h-_zGbKWA2S:-MNx_wU83z181bprVCZ9:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/b7f53199626e05484768f2845488c97f56dd8400/man/memkindallocator.3#L48)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> satifies
> ```
satisfies 
</blockquote></details>

Done.
___
*[test/allocate_to_max_stress_test.cpp, line 143 at r2](https://reviewable.io/reviews/memkind/memkind/415#-MNxSC1V7LZ7vg9dDAAt:-MNx_yAU5bK7wZ7jsEXZ:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/b7f53199626e05484768f2845488c97f56dd8400/test/allocate_to_max_stress_test.cpp#L143)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
>  kinds.enable_type(AllocatorTypes::MEMKIND_HIGHEST_CAPACITY);
> ```
I think for this case in test support memkind_highcapacity_test would do the job.
We could add support for these new kinds in other tests later (as we spoke offline)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-12-07 14:45 UTC, michalbiesek requested changes
> Reviewed 3 of 19 files at r2, 8 of 16 files at r3.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/415)* status: 13 of 19 files reviewed, 3 unresolved discussions (waiting on @bratpiorka and @michalbiesek)

___
*[man/memkindallocator.3, line 47 at r2](https://reviewable.io/reviews/memkind/memkind/415#-MNxd3y6BeeWRRFnQdYb:-MNxd3y6BeeWRRFnQdYc:b-dopzlp) ([raw file](https://github.com/memkind/memkind/blob/b7f53199626e05484768f2845488c97f56dd8400/man/memkindallocator.3#L47)):*
> ```Roff
> Default allocation using standard memory and default page size.
> .PP
> .B libmemkind::kinds::HIGHEST_CAPACITY
> ```

Why you remove this - please restore (and change "satifies" to "satisfies")
___
*[src/memkind_hmat.c, line 35 at r2](https://reviewable.io/reviews/memkind/memkind/415#-MNxdHL04WjVJy3qRmCz:-MNxdHL04WjVJy3qRmD-:b14wky7) ([raw file](https://github.com/memkind/memkind/blob/b7f53199626e05484768f2845488c97f56dd8400/src/memkind_hmat.c#L35)):*
> ```
> int i
> ```
can we declare i outside the for loop https://travis-ci.org/github/memkind/memkind/jobs/748134469 ?
___
*[test/memkind_highcapacity_tests.cpp, line 10 at r3](https://reviewable.io/reviews/memkind/memkind/415#-MNxdbj49__FhmF2A3Nc:-MNxdbj5DPywizGPgOgA:b-ki2t22) ([raw file](https://github.com/memkind/memkind/blob/888e3c3254d02d58f61677ad2169ad6d4dd53930/test/memkind_highcapacity_tests.cpp#L10)):*
> ```
> #include <numa.h>
> #include <math.h>
> ```
remove duplicated includes, please


<!-- Sent from Reviewable.io -->

2020-12-07 15:09 UTC, bratpiorka reviewed
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/415)* status: 12 of 20 files reviewed, 3 unresolved discussions (waiting on @michalbiesek)

___
*[man/memkindallocator.3, line 47 at r2](https://reviewable.io/reviews/memkind/memkind/415#-MNxd3y6BeeWRRFnQdYb:-MNxjsFQ0P0DjEgZiDNW:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/b7f53199626e05484768f2845488c97f56dd8400/man/memkindallocator.3#L47)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

Why you remove this - please restore (and change "satifies" to "satisfies")
</blockquote></details>

Done.
___
*[src/memkind_hmat.c, line 35 at r2](https://reviewable.io/reviews/memkind/memkind/415#-MNxdHL04WjVJy3qRmCz:-MNxjtfDCce3lVN4ymw3:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/b7f53199626e05484768f2845488c97f56dd8400/src/memkind_hmat.c#L35)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> int i
> ```
can we declare i outside the for loop https://travis-ci.org/github/memkind/memkind/jobs/748134469 ?
</blockquote></details>

Done.
___
*[test/memkind_highcapacity_tests.cpp, line 10 at r3](https://reviewable.io/reviews/memkind/memkind/415#-MNxdbj49__FhmF2A3Nc:-MNxjwt41NH706RXRg-8:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/888e3c3254d02d58f61677ad2169ad6d4dd53930/test/memkind_highcapacity_tests.cpp#L10)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> #include <numa.h>
> #include <math.h>
> ```
remove duplicated includes, please
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-12-07 15:15 UTC, michalbiesek approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>
@patkamin please review

> Reviewed 5 of 16 files at r3, 2 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/415#-:-MNxkxKP4YDEEGyk5bbG:b-ln28uq)* status: 19 of 20 files reviewed, all discussions resolved (waiting on @michalbiesek)



<!-- Sent from Reviewable.io -->

2020-12-08 09:22 UTC, PatKamin reviewed
> Reviewed 4 of 17 files at r1, 4 of 19 files at r2, 7 of 16 files at r3, 2 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/415)* status: all files reviewed, 2 unresolved discussions (waiting on @bratpiorka)

___
*[src/memkind_hmat.c, line 53 at r4](https://reviewable.io/reviews/memkind/memkind/415#-MO0YPDTAiGIqIFUak0o:-MO0YPDTAiGIqIFUak0p:b-6iba7r) ([raw file](https://github.com/memkind/memkind/blob/ff45c1a0d0411c65dda30610a60e21f0389994f4/src/memkind_hmat.c#L53)):*
> ```C
>     if (numa_bitmask_weight(g->numa_nodes) == 0) {
>         numa_bitmask_free(g->numa_nodes);
>         g->init_err = MEMKIND_ERROR_MEMTYPE_NOT_AVAILABLE;
> ```

It seems to be overwritten by the final line in this function. Add return?
___
*[src/memkind_hmat.c, line 68 at r4](https://reviewable.io/reviews/memkind/memkind/415#-MO0bAHU1u6N29PoLYk7:-MO0bAHU1u6N29PoLYk8:bmujzdt) ([raw file](https://github.com/memkind/memkind/blob/ff45c1a0d0411c65dda30610a60e21f0389994f4/src/memkind_hmat.c#L68)):*
> ```C
>     if (MEMKIND_LIKELY(!g->init_err)) {
>         struct bitmask nodemask_bm = {maxnode, nodemask};
>         numa_bitmask_clearall(&nodemask_bm);
> ```

I think it's unnecessary since you already overwrite the nodemask in the next line.


<!-- Sent from Reviewable.io -->

2020-12-08 10:33 UTC, bratpiorka reviewed
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/415)* status: 19 of 20 files reviewed, 2 unresolved discussions (waiting on @PatKamin)

___
*[src/memkind_hmat.c, line 53 at r4](https://reviewable.io/reviews/memkind/memkind/415#-MO0YPDTAiGIqIFUak0o:-MO0uPGeDL3ItqZlWi5K:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/ff45c1a0d0411c65dda30610a60e21f0389994f4/src/memkind_hmat.c#L53)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

It seems to be overwritten by the final line in this function. Add return?
</blockquote></details>

Done.
___
*[src/memkind_hmat.c, line 68 at r4](https://reviewable.io/reviews/memkind/memkind/415#-MO0bAHU1u6N29PoLYk7:-MO0uQ4r32d1AUGRI8vb:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/ff45c1a0d0411c65dda30610a60e21f0389994f4/src/memkind_hmat.c#L68)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

I think it's unnecessary since you already overwrite the nodemask in the next line.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-12-08 12:51 UTC, PatKamin reviewed
> Reviewed 1 of 19 files at r2, 1 of 16 files at r3, 1 of 3 files at r4, 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/415)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @bratpiorka)



<!-- Sent from Reviewable.io -->

2020-12-08 12:54 UTC, bratpiorka reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/415#-:-MO1PkosBML2Ap4y9jqM:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @bratpiorka)



<!-- Sent from Reviewable.io -->

2020-12-08 12:55 UTC, merged