add new LOCAL_HIGHEST_CAPACITY kind
memkind/memkind pull request #436
Opened 2020-12-17 15:06 UTC by bratpiorka

### Description

### Types of changes

- [ ] Bugfix (non-breaking change which fixes issue linked in Description above)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Documentation (correction or otherwise)
- [ ] Cosmetics (whitespace, appearance)
- [ ] Other

### Checklist

- [x] Code compiles without errors
- [x] All tests pass locally with my changes (see TESTING section in CONTRIBUTING file)
- [x] Created tests which will fail without the change (if possible)
- [x] Extended the README/documentation (if necessary)
- [x] All newly added files have proprietary license (if necessary)
- [x] All newly added files are referenced in MANIFEST files (if necessary)

## Further comments

2020-12-17 15:08 UTC, bratpiorka commented
@pmem-bot-ae
test this please

2020-12-18 09:59 UTC, michalbiesek commented
Please mark this as a draft and when CI will pass assign people to review and mark this PR as ready to review.

2020-12-18 12:46 UTC, michalbiesek reviewed
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/436)* status: 0 of 13 files reviewed, 12 unresolved discussions (waiting on @bratpiorka)

___
*[README, line 146 at r1](https://reviewable.io/reviews/memkind/memkind/436#-MOlLfcS8g6XSxUny644:-MOlLfcS8g6XSxUny645:b-x4cx40) ([raw file](https://github.com/memkind/memkind/blob/b3de240a987574a7625fc412185c8ad8b6b7ce9e/README#L146)):*
> ```
> | MEMKIND_HIGHEST_CAPACITY           | X     |             |           |            |                                     |      |
> | MEMKIND_HIGHEST_CAPACITY_PREFERRED | X     |             |           |            |                                     |      |
> | MEMKIND_LOCAL_HIGHEST_CAPACITY     |       |             |           |            |                                     |      |
> ```

Not true (the conditions you described here)
___
*[include/memkind.h, line 286 at r2](https://reviewable.io/reviews/memkind/memkind/436#-MOpplG28R2G6cTChH1d:-MOpplG3DTXYo8BOdEFj:b-371ef3) ([raw file](https://github.com/memkind/memkind/blob/fb050a6711c29ff8baec492987e415db0f13394b/include/memkind.h#L286)):*
> ```
> MEMKIND_LOCAL_HIGHEST_CAPACITY
> ```
MEMKIND_HIGHEST_CAPACITY_LOCAL

Can we keep this kind of naming convention. MMEKIND as prefix HIGHEST_CAPACITY as "memory property" and LOCAL as "other property"
___
*[include/memkind_allocator.h, line 132 at r1](https://reviewable.io/reviews/memkind/memkind/436#-MOlLmwO1UC3kc3hM11w:-MOlLmwO1UC3kc3hM11x:b-ta5flj) ([raw file](https://github.com/memkind/memkind/blob/b3de240a987574a7625fc412185c8ad8b6b7ce9e/include/memkind_allocator.h#L132)):*
> ```objc
>                     case libmemkind::kinds::HIGHEST_CAPACITY:
>                         _kind = MEMKIND_HIGHEST_CAPACITY;
>                     case libmemkind::kinds::LOCAL_HIGHEST_CAPACITY:
> ```

you remove break
___
*[include/memkind_allocator.h, line 47 at r2](https://reviewable.io/reviews/memkind/memkind/436#-MOppMCu2I_Dt4mFo769:-MOppMCu2I_Dt4mFo76A:bgrsb20) ([raw file](https://github.com/memkind/memkind/blob/fb050a6711c29ff8baec492987e415db0f13394b/include/memkind_allocator.h#L47)):*
> ```
> #ifdef MEMKIND_HWLOC
> ```
We don't want ifdef hell :)
Consider logical similar as in the case of using MEMKIND_HBW when you don't have High Bandwidth memory on your environment
___
*[include/memkind/internal/memkind_hmat.h, line 13 at r1](https://reviewable.io/reviews/memkind/memkind/436#-MOlLrOL5fy2xAMRvLc5:-MOlLrOL5fy2xAMRvLc6:b-exhr03) ([raw file](https://github.com/memkind/memkind/blob/b3de240a987574a7625fc412185c8ad8b6b7ce9e/include/memkind/internal/memkind_hmat.h#L13)):*
> ```objc
> extern struct memkind_ops MEMKIND_HIGHEST_CAPACITY_OPS;
> extern struct memkind_ops MEMKIND_HIGHEST_CAPACITY_PREFERRED_OPS;
> ```

no need for newline
___
*[man/memkindallocator.3, line 58 at r1](https://reviewable.io/reviews/memkind/memkind/436#-MOlM-M6DGpLljB0MqZm:-MOlM-M6DGpLljB0MqZn:b3kre) ([raw file](https://github.com/memkind/memkind/blob/b3de240a987574a7625fc412185c8ad8b6b7ce9e/man/memkindallocator.3#L58)):*
> ```Roff
> For this kind, the allocation will not succeed if there are two or more NUMA nodes
> that have the highest capacity.
> .B libmemkind::kinds::LOCAL_HIGHEST_CAPACITY
> ```

?
___
*[src/memkind_hmat.c, line 84 at r1](https://reviewable.io/reviews/memkind/memkind/436#-MOlMMzPCWCEq9Utu6WL:-MOlMMzPCWCEq9Utu6WM:b83bufh) ([raw file](https://github.com/memkind/memkind/blob/b3de240a987574a7625fc412185c8ad8b6b7ce9e/src/memkind_hmat.c#L84)):*
> ```
>  struct bitmask *node_cpus = numa_allocate_cpumask();
> ```
This could fail so provide error handling
___
*[src/memkind_hmat.c, line 165 at r1](https://reviewable.io/reviews/memkind/memkind/436#-MOlNnZp9mOmutbUMso5:-MOlNnZp9mOmutbUMso6:b-dzumro) ([raw file](https://github.com/memkind/memkind/blob/b3de240a987574a7625fc412185c8ad8b6b7ce9e/src/memkind_hmat.c#L165)):*
> ```
>     int cpu_id = sched_getcpu();
>     int cpu_node = numa_node_of_cpu(cpu_id);
> ```
This would be call on every malloc so maybe we just keep the solution with:
mapping initatior CPU and destination Memory Node and avoid this numa_node_of_cpu
___
*[src/memkind_hmat.c, line 205 at r1](https://reviewable.io/reviews/memkind/memkind/436#-MOlM5K97ySSHhTp_j_t:-MOlM5KA0PlIkIUnQnGs:b-amayei) ([raw file](https://github.com/memkind/memkind/blob/b3de240a987574a7625fc412185c8ad8b6b7ce9e/src/memkind_hmat.c#L205)):*
> ```
> MEMKIND_LOCAL_HIGHEST_CAPACITY_OPS
> ```
what happened if I don't have libhwloc and would try to build memkind project
___
*[test/memkind_highcapacity_tests.cpp, line 18 at r1](https://reviewable.io/reviews/memkind/memkind/436#-MOlMhTqEG4jHMNuBfFv:-MOlMhTqEG4jHMNuBfFw:bv4vynr) ([raw file](https://github.com/memkind/memkind/blob/b3de240a987574a7625fc412185c8ad8b6b7ce9e/test/memkind_highcapacity_tests.cpp#L18)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
> #include "config.h"
> #ifdef MEMKIND_HWLOC
> #include <hwloc.h>
> #endif
> ```
</details>

not needed
___
*[test/memkind_hmat_tests.cpp, line 45 at r2](https://reviewable.io/reviews/memkind/memkind/436#-MOpqAM7EqNB9H8EuLiJ:-MOpqAM7EqNB9H8EuLiK:b-mowohl) ([raw file](https://github.com/memkind/memkind/blob/fb050a6711c29ff8baec492987e415db0f13394b/test/memkind_hmat_tests.cpp#L45)):*
> ```
> CascadeLake2Var1
> ```
As we spoke offline you should extend the variant for this - so imagine the case when you have PMEM only on first socket. Or on first and third socket
___
*[test/memkind_hmat_tests.cpp, line 75 at r2](https://reviewable.io/reviews/memkind/memkind/436#-MOprSU77R9FQD1Q79lF:-MOprSU8B4vE8cl4iuRz:b-zhfffw) ([raw file](https://github.com/memkind/memkind/blob/fb050a6711c29ff8baec492987e415db0f13394b/test/memkind_hmat_tests.cpp#L75)):*
> ```
> printf("MEMKIND_TEST_TOPOLOGY: %s\n", envp);
> ```
you could easily remove this - this was used only for draft version of this file


<!-- Sent from Reviewable.io -->

2020-12-18 16:34 UTC, PatKamin reviewed
> Reviewed 10 of 13 files at r3.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/436)* status: 8 of 14 files reviewed, 17 unresolved discussions (waiting on @bratpiorka and @PatKamin)

___
*[copying_headers/MANIFEST.freeBSD, line 210 at r3](https://reviewable.io/reviews/memkind/memkind/436#-MOqgOQGAY2gX1ATpL2h:-MOqgOQH4AUPajBnbxZO:bxy335l) ([raw file](https://github.com/memkind/memkind/blob/6f2ff2db3ed5c0261f48b9bd08f79e34c107bfb6/copying_headers/MANIFEST.freeBSD#L210)):*
> ```
> utils/qemu/topology/single_hbw_node.xml
> utils/qemu/topology/single_memory_node.xml
> utils/qemu/topology/csl_2_var1.xml
> ```

Rebase branch
___
*[include/memkind_allocator.h, line 48 at r3](https://reviewable.io/reviews/memkind/memkind/436#-MOqae5V3O5AisgtOCDg:-MOqae5V3O5AisgtOCDh:bo3usrh) ([raw file](https://github.com/memkind/memkind/blob/6f2ff2db3ed5c0261f48b9bd08f79e34c107bfb6/include/memkind_allocator.h#L48)):*
> ```objc
>         HIGHEST_CAPACITY_PREFERRED = 16,
> #ifdef MEMKIND_HWLOC
>         LOCAL_HIGHEST_CAPACITY = 17,
> ```

Remove the colon, rename to HIGHEST_CAPACITY_LOCAL.
___
*[man/memkind.3, line 690 at r3](https://reviewable.io/reviews/memkind/memkind/436#-MOqbmcW8CsCBsJo5S4Z:-MOqbmcW8CsCBsJo5S4_:b6jg2vc) ([raw file](https://github.com/memkind/memkind/blob/6f2ff2db3ed5c0261f48b9bd08f79e34c107bfb6/man/memkind.3#L690)):*
> ```Roff
> .B MEMKIND_HIGHEST_CAPACITY_LOCAL
> Allocate from a NUMA node(s) that has the highest capacity among local nodes
> (placed in the same package) in the system.
> ```

I'm not sure if it's equivalent, but I would use term `socket` rather than `package`.
___
*[man/memkind.3, line 692 at r3](https://reviewable.io/reviews/memkind/memkind/436#-MOqc6gw-18nyDyyENHd:-MOqc6gw-18nyDyyENHe:b-fpyi5j) ([raw file](https://github.com/memkind/memkind/blob/6f2ff2db3ed5c0261f48b9bd08f79e34c107bfb6/man/memkind.3#L692)):*
> ```Roff
> (placed in the same package) in the system.
> .BR Note:
> There could be a sitution, when allocating from MEMKIND_HIGHEST_CAPACITY nodes
> ```

situation
___
*[man/memkind.3, line 693 at r3](https://reviewable.io/reviews/memkind/memkind/436#-MOqcH4j6gX-PMT2VskI:-MOqcH4j6gX-PMT2VskJ:b-5qly8i) ([raw file](https://github.com/memkind/memkind/blob/6f2ff2db3ed5c0261f48b9bd08f79e34c107bfb6/man/memkind.3#L693)):*
> ```Roff
> .BR Note:
> There could be a sitution, when allocating from MEMKIND_HIGHEST_CAPACITY nodes
> would do alloactions from nodes that are very far from CPU that requested
> ```

allocations


<!-- Sent from Reviewable.io -->

2021-01-05 07:19 UTC, bratpiorka reviewed
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/436)* status: 1 of 17 files reviewed, 19 unresolved discussions (waiting on @michalbiesek and @PatKamin)

___
*[README, line 146 at r1](https://reviewable.io/reviews/memkind/memkind/436#-MOlLfcS8g6XSxUny644:-MOqlu967Mr7Yz6XCMnx:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/b3de240a987574a7625fc412185c8ad8b6b7ce9e/README#L146)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

Not true (the conditions you described here)
</blockquote></details>

Done.
___
*[copying_headers/MANIFEST.freeBSD, line 210 at r3](https://reviewable.io/reviews/memkind/memkind/436#-MOqgOQGAY2gX1ATpL2h:-MOqlxu64dlXF5fcd66-:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/6f2ff2db3ed5c0261f48b9bd08f79e34c107bfb6/copying_headers/MANIFEST.freeBSD#L210)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Rebase branch
</blockquote></details>

Done.
___
*[include/memkind.h, line 286 at r2](https://reviewable.io/reviews/memkind/memkind/436#-MOpplG28R2G6cTChH1d:-MOq_0rK9Hj_62aCHkws:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/fb050a6711c29ff8baec492987e415db0f13394b/include/memkind.h#L286)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> MEMKIND_LOCAL_HIGHEST_CAPACITY
> ```
MEMKIND_HIGHEST_CAPACITY_LOCAL

Can we keep this kind of naming convention. MMEKIND as prefix HIGHEST_CAPACITY as "memory property" and LOCAL as "other property"
</blockquote></details>

Done.
___
*[include/memkind_allocator.h, line 132 at r1](https://reviewable.io/reviews/memkind/memkind/436#-MOlLmwO1UC3kc3hM11w:-MOq_BGK0y2QG7dphSE6:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/b3de240a987574a7625fc412185c8ad8b6b7ce9e/include/memkind_allocator.h#L132)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

you remove break
</blockquote></details>

Done.
___
*[include/memkind_allocator.h, line 47 at r2](https://reviewable.io/reviews/memkind/memkind/436#-MOppMCu2I_Dt4mFo769:-MQBg0TB8CvG0UAROT2v:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/fb050a6711c29ff8baec492987e415db0f13394b/include/memkind_allocator.h#L47)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> #ifdef MEMKIND_HWLOC
> ```
We don't want ifdef hell :)
Consider logical similar as in the case of using MEMKIND_HBW when you don't have High Bandwidth memory on your environment
</blockquote></details>

Done.
___
*[include/memkind_allocator.h, line 48 at r3](https://reviewable.io/reviews/memkind/memkind/436#-MOqae5V3O5AisgtOCDg:-MQBhWPO3qWQQEnLDdqR:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/6f2ff2db3ed5c0261f48b9bd08f79e34c107bfb6/include/memkind_allocator.h#L48)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Remove the colon, rename to HIGHEST_CAPACITY_LOCAL.
</blockquote></details>

Done.
___
*[include/memkind/internal/memkind_hmat.h, line 13 at r1](https://reviewable.io/reviews/memkind/memkind/436#-MOlLrOL5fy2xAMRvLc5:-MOq_GIB2ow_1vcrwy5T:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/b3de240a987574a7625fc412185c8ad8b6b7ce9e/include/memkind/internal/memkind_hmat.h#L13)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

no need for newline
</blockquote></details>

Done.
___
*[man/memkind.3, line 690 at r3](https://reviewable.io/reviews/memkind/memkind/436#-MOqbmcW8CsCBsJo5S4Z:-MOqmHFw-mrxQrKjS0KV:b2f3njj) ([raw file](https://github.com/memkind/memkind/blob/6f2ff2db3ed5c0261f48b9bd08f79e34c107bfb6/man/memkind.3#L690)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

I'm not sure if it's equivalent, but I would use term `socket` rather than `package`.
</blockquote></details>

"Package" is a term used by hwloc - I would rather to stay with that.
___
*[man/memkind.3, line 692 at r3](https://reviewable.io/reviews/memkind/memkind/436#-MOqc6gw-18nyDyyENHd:-MOqmJLqBHbWuQP_jgR5:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/6f2ff2db3ed5c0261f48b9bd08f79e34c107bfb6/man/memkind.3#L692)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

situation
</blockquote></details>

Done.
___
*[man/memkind.3, line 693 at r3](https://reviewable.io/reviews/memkind/memkind/436#-MOqcH4j6gX-PMT2VskI:-MOqmJbk6EtWkSnhlYFC:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/6f2ff2db3ed5c0261f48b9bd08f79e34c107bfb6/man/memkind.3#L693)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

allocations
</blockquote></details>

Done.
___
*[man/memkindallocator.3, line 58 at r1](https://reviewable.io/reviews/memkind/memkind/436#-MOlM-M6DGpLljB0MqZm:-MOqme-XARW4lh3p1Gdq:bk0sxjj) ([raw file](https://github.com/memkind/memkind/blob/b3de240a987574a7625fc412185c8ad8b6b7ce9e/man/memkindallocator.3#L58)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

?
</blockquote></details>

"libmemkind::kinds::HIGHEST_CAPACITY" was previously doubled.
___
*[src/memkind_capacity.c, line 157 at r7](https://reviewable.io/reviews/memkind/memkind/436#-MQD15CZChvgIG4euy5D:-MQD15CZChvgIG4euy5E:b-nzp79b) ([raw file](https://github.com/memkind/memkind/blob/72805f79dae1f6209095e118c1e77c5a759c0792/src/memkind_capacity.c#L157)):*
> ```C
> static void memkind_hi_cap_loc_numanodes_init(void)
> {
>     struct memkind_hi_cap_loc_numanodes_t *g = &memkind_hi_cap_loc_numanodes_g;
> ```

is this way of handling lack of hwloc support OK?
___
*[src/memkind_hmat.c, line 84 at r1](https://reviewable.io/reviews/memkind/memkind/436#-MOlMMzPCWCEq9Utu6WL:-MOq_NjR4L4mXRmISZ1h:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/b3de240a987574a7625fc412185c8ad8b6b7ce9e/src/memkind_hmat.c#L84)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
>  struct bitmask *node_cpus = numa_allocate_cpumask();
> ```
This could fail so provide error handling
</blockquote></details>

Done.
___
*[src/memkind_hmat.c, line 165 at r1](https://reviewable.io/reviews/memkind/memkind/436#-MOlNnZp9mOmutbUMso5:-MOqmrKA9GktYkfR7rEC:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/b3de240a987574a7625fc412185c8ad8b6b7ce9e/src/memkind_hmat.c#L165)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
>     int cpu_id = sched_getcpu();
>     int cpu_node = numa_node_of_cpu(cpu_id);
> ```
This would be call on every malloc so maybe we just keep the solution with:
mapping initatior CPU and destination Memory Node and avoid this numa_node_of_cpu
</blockquote></details>

Done.
___
*[src/memkind_hmat.c, line 205 at r1](https://reviewable.io/reviews/memkind/memkind/436#-MOlM5K97ySSHhTp_j_t:-MOq_Sg-1W03fdPdQMu4:bvhnmb7) ([raw file](https://github.com/memkind/memkind/blob/b3de240a987574a7625fc412185c8ad8b6b7ce9e/src/memkind_hmat.c#L205)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> MEMKIND_LOCAL_HIGHEST_CAPACITY_OPS
> ```
what happened if I don't have libhwloc and would try to build memkind project
</blockquote></details>

I checked and it builds correctly
___
*[test/memkind_highcapacity_tests.cpp, line 18 at r1](https://reviewable.io/reviews/memkind/memkind/436#-MOlMhTqEG4jHMNuBfFv:-MOqmtxNDJ9YCvIP3tm4:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/b3de240a987574a7625fc412185c8ad8b6b7ce9e/test/memkind_highcapacity_tests.cpp#L18)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> #include "config.h"
> #ifdef MEMKIND_HWLOC
> #include <hwloc.h>
> #endif
> ```
not needed
</blockquote></details>

Done.
___
*[test/memkind_hmat_tests.cpp, line 45 at r2](https://reviewable.io/reviews/memkind/memkind/436#-MOpqAM7EqNB9H8EuLiJ:-MQD0IYF8-QfxevNdc0z:b-896fix) ([raw file]( [...]

2021-01-05 08:55 UTC, michalbiesek reviewed
> Reviewed 7 of 15 files at r4, 1 of 5 files at r5.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/436)* status: 7 of 17 files reviewed, 33 unresolved discussions (waiting on @bratpiorka, @michalbiesek, and @PatKamin)

___
*[README, line 146 at r4](https://reviewable.io/reviews/memkind/memkind/436#-MQBqIwp6ni6J5RVFT2-:-MQBqIwq3E5OiN6EzcZI:b-5zaqhh) ([raw file](https://github.com/memkind/memkind/blob/9661d27816029399532c37a96f2b4cb3b7081f3c/README#L146)):*
> ```
>  MEMKIND_HIGHEST_CAPACITY_LOCAL
> ```
the last column should be distinguished I mean the user is required to have libhwloc for this kind and hmat is not necessary for MEMKIND_HIGHEST_CAPACITY_LOCAL
___
*[copying_headers/MANIFEST.freeBSD, line 211 at r4](https://reviewable.io/reviews/memkind/memkind/436#-MQCe5GW1D2UTmA46ZIU:-MQCe5GW1D2UTmA46ZIV:bxd9kzi) ([raw file](https://github.com/memkind/memkind/blob/9661d27816029399532c37a96f2b4cb3b7081f3c/copying_headers/MANIFEST.freeBSD#L211)):*
> ```
> utils/qemu/requirements.txt
> utils/qemu/topology/clx_2_var1.xml
> utils/qemu/topology/clx_4_var1.xml
> ```

Add references to new xml in Manifest also and Makefile.am
___
*[include/memkind_allocator.h, line 16 at r4](https://reviewable.io/reviews/memkind/memkind/436#-MQCiDNc5AFp2dnPYAKL:-MQCiDNc5AFp2dnPYAKM:bxuqp1q) ([raw file](https://github.com/memkind/memkind/blob/9661d27816029399532c37a96f2b4cb3b7081f3c/include/memkind_allocator.h#L16)):*
> ```
> #include "config.h"
> ```
remove
___
*[include/memkind_deprecated.h, line 34 at r4](https://reviewable.io/reviews/memkind/memkind/436#-MQCiJA_B7BTann7gmBX:-MQCiJA_B7BTann7gmBY:bxuqp1q) ([raw file](https://github.com/memkind/memkind/blob/9661d27816029399532c37a96f2b4cb3b7081f3c/include/memkind_deprecated.h#L34)):*
> ```
> #include "config.h"
> ```
remove
___
*[include/memkind/internal/memkind_capacity.h, line 9 at r4](https://reviewable.io/reviews/memkind/memkind/436#-MQCiQdG9kuVzwt84Ke4:-MQCiQdG9kuVzwt84Ke5:boswjcm) ([raw file](https://github.com/memkind/memkind/blob/9661d27816029399532c37a96f2b4cb3b7081f3c/include/memkind/internal/memkind_capacity.h#L9)):*
<details><summary><i alt="summary">Quoted 5 lines of code…</i></summary>

> ```
> #include "config.h"
> #include <memkind.h>
> #ifdef MEMKIND_HWLOC
> #include <hwloc.h>
> #endif // MEMKIND_HWLOC
> ```
</details>

remove these changes
___
*[man/memkind.3, line 690 at r3](https://reviewable.io/reviews/memkind/memkind/436#-MOqbmcW8CsCBsJo5S4Z:-MQGYiak0H5WJsG98ErV:b-xs0kld) ([raw file](https://github.com/memkind/memkind/blob/6f2ff2db3ed5c0261f48b9bd08f79e34c107bfb6/man/memkind.3#L690)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

"Package" is a term used by hwloc - I would rather to stay with that.
</blockquote></details>

See my comment in memkindallocator.3
___
*[man/memkind.3, line 683 at r4](https://reviewable.io/reviews/memkind/memkind/436#-MQCijUX71E3c_aY8xf-:-MQCijUX71E3c_aY8xf0:b-oktppc) ([raw file](https://github.com/memkind/memkind/blob/9661d27816029399532c37a96f2b4cb3b7081f3c/man/memkind.3#L683)):*
> ```
>  nodes
> ```
all nodes
___
*[man/memkind.3, line 684 at r4](https://reviewable.io/reviews/memkind/memkind/436#-MQCih7K1N0A-23vF7fz:-MQCih7K1N0A-23vF7g-:b-luy630) ([raw file](https://github.com/memkind/memkind/blob/9661d27816029399532c37a96f2b4cb3b7081f3c/man/memkind.3#L684)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
> .BR Note:
> If there is more than one node that satisfies this condition, e.g. there are two
> nodes that have the same capacity and it is the highest capacity in the system,
> allocation will be done from both of them.
> ```
</details>

Actually, this is ditto seen - that you mention in the previous sentence about Node(s).- please remove this note.
___
*[man/memkindallocator.3, line 48 at r4](https://reviewable.io/reviews/memkind/memkind/436#-MQCXpeUEHcAHF4gbnY0:-MQCXpeUEHcAHF4gbnY1:b-2hsq4b) ([raw file](https://github.com/memkind/memkind/blob/9661d27816029399532c37a96f2b4cb3b7081f3c/man/memkindallocator.3#L48)):*
> ```
> Note: there could be more than one node that satisfies this condition.
> ```
Actually, this is ditto seen - that you mention in the previous sentence about Node(s).- please remove this note.
___
*[man/memkindallocator.3, line 61 at r4](https://reviewable.io/reviews/memkind/memkind/436#-MQCioAt8S9dfrWjcKtU:-MQCioAt8S9dfrWjcKtV:bp52oqc) ([raw file](https://github.com/memkind/memkind/blob/9661d27816029399532c37a96f2b4cb3b7081f3c/man/memkindallocator.3#L61)):*
> ```
> except that highest capacity nodes are selected among nodes that are
> local (placed in the same package) to CPU that do allocations.
> ```
Be consistent with this description with memkind.3.
This form here is better to consider the situation that the user doesn't have any knowledge about hwloc and the description here should be understandable for him. I would describe it as something like:
Allocate from a NUMA node(s) that has the highest capacity among all NUMA Nodes from the local domain. NUMA Nodes have the same local domain for a set of CPUs associated with them, e.g. socket or sub-NUMA cluster.

The note with the usage description is not needed in the manual.
___
*[src/memkind.c, line 212 at r4](https://reviewable.io/reviews/memkind/memkind/436#-MQBqdpAArA6Szr9iT0A:-MQBqdpBAifXoy40glJE:b-3b8c6d) ([raw file](https://github.com/memkind/memkind/blob/9661d27816029399532c37a96f2b4cb3b7081f3c/src/memkind.c#L212)):*
> ```
> "MEMKIND_HIGHEST_CAPACITY_LOCAL"
> ```
please keep a small letters convention
___
*[src/memkind_capacity.c, line 2 at r4](https://reviewable.io/reviews/memkind/memkind/436#-MQBqiv_ClY1afjVxrJh:-MQBqiv_ClY1afjVxrJi:buec63x) ([raw file](https://github.com/memkind/memkind/blob/9661d27816029399532c37a96f2b4cb3b7081f3c/src/memkind_capacity.c#L2)):*
> ```
> 2020
> ```
nit: please bump all modified files to 2021
___
*[src/memkind_capacity.c, line 36 at r4](https://reviewable.io/reviews/memkind/memkind/436#-MQBqpiwC2dDQzirM5xf:-MQBqpiwC2dDQzirM5xg:bqfoh4d) ([raw file](https://github.com/memkind/memkind/blob/9661d27816029399532c37a96f2b4cb3b7081f3c/src/memkind_capacity.c#L36)):*
> ```
> #ifdef MEMKIND_HWLOC
> ```
move both implementations to memkind_mem_attributes.c - that was the intention of this file to keep this ifdef division in one place
___
*[src/memkind_capacity.c, line 97 at r4](https://reviewable.io/reviews/memkind/memkind/436#-MQBriNH73pjxUxXwUip:-MQBriNH73pjxUxXwUiq:bh6hfpq) ([raw file](https://github.com/memkind/memkind/blob/9661d27816029399532c37a96f2b4cb3b7081f3c/src/memkind_capacity.c#L97)):*
<details><summary><i alt="summary">Quoted 8 lines of code…</i></summary>

> ```
>     while ((cpu_object = hwloc_get_next_obj_by_type(topology, HWLOC_OBJ_PU,
>                                                     cpu_object)) != NULL) {
>         // allocate a NUMA bitmask for HIGHEST_LOCAL_CAPACITY nodes if it is not
>         // allocated yet
>         struct bitmask *numa_bitmask = g->per_cpu_numa_nodes[cpu_object->os_index];
>         if (numa_bitmask == NULL) {
>             numa_bitmask = numa_bitmask_alloc(max_node_id + 1);
>             if (MEMKIND_UNLIKELY(numa_bitmask == NULL)) {
> ```
</details>

I believe your implementation could be simplified to
- outside iteration over nodes which could be the initiator of the memory request
- for the node which could be the initiator you could call the function presented in 23.30.4.1 in hwloc_documentation to get list of local nodes
- Finally, you could iterate over nodes from the previous step and find the Node(s) with the highest capacity
___
*[src/memkind_capacity.c, line 142 at r8](https://reviewable.io/reviews/memkind/memkind/436#-MQGaWJKAutG1BTSqhtT:-MQGaWJKAutG1BTSqhtU:bct7333) ([raw file](https://github.com/memkind/memkind/blob/2caf3a116541359e0313f7ddfa2ebcfd0d7d3e50/src/memkind_capacity.c#L142)):*
> ```
> max_node_id
> ```
You allocate space for num_cpus and iterate over max_node_id or I miss something
___
*[src/memkind_cap [...]

2021-01-05 14:25 UTC, PatKamin reviewed
> Reviewed 9 of 22 files at r9, 2 of 5 files at r10.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/436)* status: 11 of 23 files reviewed, 30 unresolved discussions (waiting on @bratpiorka, @michalbiesek, and @PatKamin)

___
*[src/memkind_capacity.c, line 74 at r10](https://reviewable.io/reviews/memkind/memkind/436#-MQHsfSpCUoyugf-oBtk:-MQHsfSpCUoyugf-oBtl:bgn31et) ([raw file](https://github.com/memkind/memkind/blob/8e1fcdd88b3b61f4231732ff48eaba9c846946b7/src/memkind_capacity.c#L74)):*
> ```C
>     int err = hwloc_topology_init(&topology);
>     if (MEMKIND_UNLIKELY(err)) {
>         log_err("hwloc initialize failed");
> ```

initialization


<!-- Sent from Reviewable.io -->

2021-01-07 10:02 UTC, bratpiorka reviewed
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/436)* status: 6 of 24 files reviewed, 14 unresolved discussions (waiting on @michalbiesek and @PatKamin)

___
*[README, line 146 at r4](https://reviewable.io/reviews/memkind/memkind/436#-MQBqIwp6ni6J5RVFT2-:-MQHK_eu30bKmJT1744U:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/9661d27816029399532c37a96f2b4cb3b7081f3c/README#L146)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
>  MEMKIND_HIGHEST_CAPACITY_LOCAL
> ```
the last column should be distinguished I mean the user is required to have libhwloc for this kind and hmat is not necessary for MEMKIND_HIGHEST_CAPACITY_LOCAL
</blockquote></details>

Done.
___
*[README, line 141 at r10](https://reviewable.io/reviews/memkind/memkind/436#-MQI-3T80KtgMmwmY0XJ:-MQR02Bo5WfxG14Dl8n0:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/8e1fcdd88b3b61f4231732ff48eaba9c846946b7/README#L141)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> libhwloc
> ```
For this column please also add "X with an asterisk" for all the MEMKIND_HBW variants
</blockquote></details>

Done.
___
*[README, line 222 at r10](https://reviewable.io/reviews/memkind/memkind/436#-MQI-JPjBYfzkk3oZCxZ:-MQR0CmaCyhWxrT0FoRM:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/8e1fcdd88b3b61f4231732ff48eaba9c846946b7/README#L222)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> To get locality characteristics of NUMA nodes in the system needed by MEMKIND_HIGHEST_CAPACITY_LOCAL
> ```
To get locality characteristics of NUMA nodes in the system you need hwloc-devel v2.3.0 (or later).
</blockquote></details>

Done.
___
*[copying_headers/MANIFEST.freeBSD, line 211 at r4](https://reviewable.io/reviews/memkind/memkind/436#-MQCe5GW1D2UTmA46ZIU:-MQHKe0m8I3bU480gi-O:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/9661d27816029399532c37a96f2b4cb3b7081f3c/copying_headers/MANIFEST.freeBSD#L211)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

Add references to new xml in Manifest also and Makefile.am
</blockquote></details>

Done.
___
*[include/memkind_allocator.h, line 16 at r4](https://reviewable.io/reviews/memkind/memkind/436#-MQCiDNc5AFp2dnPYAKL:-MQHKgMB8o4WcQt9oSoW:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/9661d27816029399532c37a96f2b4cb3b7081f3c/include/memkind_allocator.h#L16)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> #include "config.h"
> ```
remove
</blockquote></details>

Done.
___
*[include/memkind_deprecated.h, line 34 at r4](https://reviewable.io/reviews/memkind/memkind/436#-MQCiJA_B7BTann7gmBX:-MQHKjdC3v8bDThelS0L:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/9661d27816029399532c37a96f2b4cb3b7081f3c/include/memkind_deprecated.h#L34)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> #include "config.h"
> ```
remove
</blockquote></details>

Done.
___
*[include/memkind/internal/memkind_capacity.h, line 9 at r4](https://reviewable.io/reviews/memkind/memkind/436#-MQCiQdG9kuVzwt84Ke4:-MQHKmB_4XOmDeDNimjT:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/9661d27816029399532c37a96f2b4cb3b7081f3c/include/memkind/internal/memkind_capacity.h#L9)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> #include "config.h"
> #include <memkind.h>
> #ifdef MEMKIND_HWLOC
> #include <hwloc.h>
> #endif // MEMKIND_HWLOC
> ```
remove these changes
</blockquote></details>

Done.
___
*[man/memkind.3, line 683 at r4](https://reviewable.io/reviews/memkind/memkind/436#-MQCijUX71E3c_aY8xf-:-MQHKqUgCimiZhsJpEXz:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/9661d27816029399532c37a96f2b4cb3b7081f3c/man/memkind.3#L683)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
>  nodes
> ```
all nodes
</blockquote></details>

Done.
___
*[man/memkind.3, line 684 at r4](https://reviewable.io/reviews/memkind/memkind/436#-MQCih7K1N0A-23vF7fz:-MQHKpiX5wxQmSwT10no:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/9661d27816029399532c37a96f2b4cb3b7081f3c/man/memkind.3#L684)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> .BR Note:
> If there is more than one node that satisfies this condition, e.g. there are two
> nodes that have the same capacity and it is the highest capacity in the system,
> allocation will be done from both of them.
> ```
Actually, this is ditto seen - that you mention in the previous sentence about Node(s).- please remove this note.
</blockquote></details>

Done.
___
*[man/memkindallocator.3, line 48 at r4](https://reviewable.io/reviews/memkind/memkind/436#-MQCXpeUEHcAHF4gbnY0:-MQHL_fa92S3tYUZ10XR:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/9661d27816029399532c37a96f2b4cb3b7081f3c/man/memkindallocator.3#L48)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> Note: there could be more than one node that satisfies this condition.
> ```
Actually, this is ditto seen - that you mention in the previous sentence about Node(s).- please remove this note.
</blockquote></details>

Done.
___
*[man/memkindallocator.3, line 61 at r4](https://reviewable.io/reviews/memkind/memkind/436#-MQCioAt8S9dfrWjcKtU:-MQHL_AP7N94PCuRkudy:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/9661d27816029399532c37a96f2b4cb3b7081f3c/man/memkindallocator.3#L61)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> except that highest capacity nodes are selected among nodes that are
> local (placed in the same package) to CPU that do allocations.
> ```
Be consistent with this description with memkind.3.
This form here is better to consider the situation that the user doesn't have any knowledge about hwloc and the description here should be understandable for him. I would describe it as something like:
Allocate from a NUMA node(s) that has the highest capacity among all NUMA Nodes from the local domain. NUMA Nodes have the same local domain for a set of CPUs associated with them, e.g. socket or sub-NUMA cluster.

The note with the usage description is not needed in the manual.

</blockquote></details>

Done.
___
*[src/memkind.c, line 212 at r4](https://reviewable.io/reviews/memkind/memkind/436#-MQBqdpAArA6Szr9iT0A:-MQHLadi6LoB_w0gtn3f:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/9661d27816029399532c37a96f2b4cb3b7081f3c/src/memkind.c#L212)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> "MEMKIND_HIGHEST_CAPACITY_LOCAL"
> ```
please keep a small letters convention
</blockquote></details>

Done.
___
*[src/memkind_capacity.c, line 36 at r4](https://reviewable.io/reviews/memkind/memkind/436#-MQBqpiwC2dDQzirM5xf:-MQR65H468rGoWSXaoxl:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/9661d27816029399532c37a96f2b4cb3b7081f3c/src/memkind_capacity.c#L36)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> #ifdef MEMKIND_HWLOC
> ```
move both implementations to memkind_mem_attributes.c - that was the intention of this file to keep this ifdef division in one place
</blockquote></details>

Done.
___
*[src/memkind_capacity.c, line 97 at r4](https://reviewable.io/reviews/memkind/memkind/436#-MQBriNH73pjxUxXwUip:-MQR12Bl7px193QJovlZ:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/9661d27816029399532c37a96f2b4cb3b7081f3c/src/memkind_capacity.c#L97)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
>     while ((cpu_object = hwloc_get_next_obj_by_type(topology, HWLOC_OBJ_PU,
>                                                     cpu_object)) != NULL) {
>         // allocate a NUMA bitmask for HIGHEST_LOCAL_CAPACITY nodes i [...]

2021-01-07 16:14 UTC, PatKamin reviewed
> Reviewed 5 of 22 files at r9, 1 of 5 files at r10, 10 of 12 files at r11.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/436)* status: 21 of 24 files reviewed, 21 unresolved discussions (waiting on @bratpiorka, @michalbiesek, and @PatKamin)

___
*[test/memkind_hmat_tests.cpp, line 20 at r11](https://reviewable.io/reviews/memkind/memkind/436#-MQS_ijp9zzqGF6PaziP:-MQS_ijp9zzqGF6PaziQ:b-ft77ce) ([raw file](https://github.com/memkind/memkind/blob/60e4078e9f84d29ac9976a28ee8194f4c6214bfe/test/memkind_hmat_tests.cpp#L20)):*
> ```cpp
> typedef std::pair<std::string, NumaMap> Topology;
> 
> // NOTE: this is hardcoded and should match topoligies in utils/qemu/topology
> ```

topologies
___
*[test/memkind_hmat_tests.cpp, line 91 at r11](https://reviewable.io/reviews/memkind/memkind/436#-MQSb_1X53R7sLMM-QPT:-MQSb_1X53R7sLMM-QPU:b-sz5axl) ([raw file](https://github.com/memkind/memkind/blob/60e4078e9f84d29ac9976a28ee8194f4c6214bfe/test/memkind_hmat_tests.cpp#L91)):*
> ```cpp
>             {1, {1}},
>             {2, {2}},
>             {3, {5}} // TODO should be 5 + 6 but QEMU shows bad capacity values
> ```

If we cannot do it in QEMU, then remove node 6 from the topology.
___
*[utils/qemu/topology/README.md, line 10 at r11](https://reviewable.io/reviews/memkind/memkind/436#-MQSYPE7Bs2IMm9dJjVf:-MQSYPE8C8cYBer22zwO:bcqc1he) ([raw file](https://github.com/memkind/memkind/blob/60e4078e9f84d29ac9976a28ee8194f4c6214bfe/utils/qemu/topology/README.md#L10)):*
> ```Markdown
> - knm_snc2.xml - Knights Mill, cluster mode: SNC-2 - memory: DRAM+MCDRAM
> - knm_snc4.xml - Knights Mill, cluster mode: SNC-4 - memory: DRAM+MCDRAM
> - clx_2_var1.xml - Cascade Lake, 2 sockets - memory DRAM+PMEM - PMEM on 1 socket
> ```

(...) on socket 0
___
*[utils/qemu/topology/README.md, line 11 at r11](https://reviewable.io/reviews/memkind/memkind/436#-MQSXZF89Pf521zQXYRd:-MQSXZFBDqp2qM3ssDTm:bcqc1hf) ([raw file](https://github.com/memkind/memkind/blob/60e4078e9f84d29ac9976a28ee8194f4c6214bfe/utils/qemu/topology/README.md#L11)):*
> ```Markdown
> - knm_snc4.xml - Knights Mill, cluster mode: SNC-4 - memory: DRAM+MCDRAM
> - clx_2_var1.xml - Cascade Lake, 2 sockets - memory DRAM+PMEM - PMEM on 1 socket
> - clx_2_var2.xml - Cascade Lake, 2 sockets - memory DRAM+PMEM - PMEM on 2 socket
> ```

(...) on socket 1
___
*[utils/qemu/topology/README.md, line 13 at r11](https://reviewable.io/reviews/memkind/memkind/436#-MQSYlsjEhE1VmGmnAMb:-MQSYlsjEhE1VmGmnAMc:bbobxi0) ([raw file](https://github.com/memkind/memkind/blob/60e4078e9f84d29ac9976a28ee8194f4c6214bfe/utils/qemu/topology/README.md#L13)):*
> ```Markdown
> - clx_2_var2.xml - Cascade Lake, 2 sockets - memory DRAM+PMEM - PMEM on 2 socket
> - clx_2_var3.xml - Cascade Lake, 2 sockets - memory DRAM+PMEM - PMEM on both sockets
> - clx_4_var1.xml - Cascade Lake, 4 sockets - memory DRAM+PMEM - PMEM on 4 sockets
> ```

(...) on **all** 4 sockets.
___
*[utils/qemu/topology/README.md, line 14 at r11](https://reviewable.io/reviews/memkind/memkind/436#-MQSZBgTBvqd0osKeiq8:-MQSZBgTBvqd0osKeiq9:bcqc1hf) ([raw file](https://github.com/memkind/memkind/blob/60e4078e9f84d29ac9976a28ee8194f4c6214bfe/utils/qemu/topology/README.md#L14)):*
> ```Markdown
> - clx_2_var3.xml - Cascade Lake, 2 sockets - memory DRAM+PMEM - PMEM on both sockets
> - clx_4_var1.xml - Cascade Lake, 4 sockets - memory DRAM+PMEM - PMEM on 4 sockets
> - clx_4_var2.xml - Cascade Lake, 4 sockets - memory DRAM+PMEM - PMEM on socket 2
> ```

(...) on socket 1
___
*[utils/qemu/topology/README.md, line 15 at r11](https://reviewable.io/reviews/memkind/memkind/436#-MQSZY8g49eD1CJCbckD:-MQSZY8g49eD1CJCbckE:b-xo7ch6) ([raw file](https://github.com/memkind/memkind/blob/60e4078e9f84d29ac9976a28ee8194f4c6214bfe/utils/qemu/topology/README.md#L15)):*
> ```Markdown
> - clx_4_var1.xml - Cascade Lake, 4 sockets - memory DRAM+PMEM - PMEM on 4 sockets
> - clx_4_var2.xml - Cascade Lake, 4 sockets - memory DRAM+PMEM - PMEM on socket 2
> - clx_4_var3.xml - Cascade Lake, 4 sockets - memory DRAM+PMEM - PMEM on sockets 1, 2 and 4
> ```

(...) on sockets 0, 1 and 3
___
*[utils/qemu/topology/README.md, line 16 at r11](https://reviewable.io/reviews/memkind/memkind/436#-MQSZqdq64iDL20fTtOo:-MQSZqdq64iDL20fTtOp:bsyykkg) ([raw file](https://github.com/memkind/memkind/blob/60e4078e9f84d29ac9976a28ee8194f4c6214bfe/utils/qemu/topology/README.md#L16)):*
> ```Markdown
> - clx_4_var2.xml - Cascade Lake, 4 sockets - memory DRAM+PMEM - PMEM on socket 2
> - clx_4_var3.xml - Cascade Lake, 4 sockets - memory DRAM+PMEM - PMEM on sockets 1, 2 and 4
> - clx_4_var4.xml - Cascade Lake, 4 sockets - memory DRAM+PMEM - PMEM on sockets 1 and 2 PMEMs on socket 4
> ```

(...) on socket 0 and 2 PMEMs on socket 3


<!-- Sent from Reviewable.io -->

2021-01-08 11:31 UTC, bratpiorka reviewed
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/436)* status: 18 of 24 files reviewed, 21 unresolved discussions (waiting on @michalbiesek and @PatKamin)

___
*[test/memkind_hmat_tests.cpp, line 20 at r11](https://reviewable.io/reviews/memkind/memkind/436#-MQS_ijp9zzqGF6PaziP:-MQW2ChNBFb_fSkihLLD:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/60e4078e9f84d29ac9976a28ee8194f4c6214bfe/test/memkind_hmat_tests.cpp#L20)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

topologies
</blockquote></details>

Done.
___
*[test/memkind_hmat_tests.cpp, line 91 at r11](https://reviewable.io/reviews/memkind/memkind/436#-MQSb_1X53R7sLMM-QPT:-MQW2DNg7T7nxkdTlyE1:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/60e4078e9f84d29ac9976a28ee8194f4c6214bfe/test/memkind_hmat_tests.cpp#L91)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

If we cannot do it in QEMU, then remove node 6 from the topology.
</blockquote></details>

Done.
___
*[utils/qemu/topology/README.md, line 16 at r10](https://reviewable.io/reviews/memkind/memkind/436#-MQI0yan6MXFgorFApay:-MQW2II171GwFIaX8Wfg:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/8e1fcdd88b3b61f4231732ff48eaba9c846946b7/utils/qemu/topology/README.md#L16)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

> PMEM on socket 1 and 2 PMEMs on socket 4
No: one PMEM on socket #1 and two PMEMs on socket #4
</blockquote></details>

Done.
___
*[utils/qemu/topology/README.md, line 10 at r11](https://reviewable.io/reviews/memkind/memkind/436#-MQSYPE7Bs2IMm9dJjVf:-MQW2FBP0ca8ivLRXVu2:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/60e4078e9f84d29ac9976a28ee8194f4c6214bfe/utils/qemu/topology/README.md#L10)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

(...) on socket 0
</blockquote></details>

Done.
___
*[utils/qemu/topology/README.md, line 11 at r11](https://reviewable.io/reviews/memkind/memkind/436#-MQSXZF89Pf521zQXYRd:-MQW2H6hE8t3qBp2-3wf:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/60e4078e9f84d29ac9976a28ee8194f4c6214bfe/utils/qemu/topology/README.md#L11)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

(...) on socket 1
</blockquote></details>

Done.
___
*[utils/qemu/topology/README.md, line 13 at r11](https://reviewable.io/reviews/memkind/memkind/436#-MQSYlsjEhE1VmGmnAMb:-MQW2HSWAZoHcwq2XXwu:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/60e4078e9f84d29ac9976a28ee8194f4c6214bfe/utils/qemu/topology/README.md#L13)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

(...) on **all** 4 sockets.
</blockquote></details>

Done.
___
*[utils/qemu/topology/README.md, line 14 at r11](https://reviewable.io/reviews/memkind/memkind/436#-MQSZBgTBvqd0osKeiq8:-MQW2HibADHmYtkQiNWB:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/60e4078e9f84d29ac9976a28ee8194f4c6214bfe/utils/qemu/topology/README.md#L14)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

(...) on socket 1
</blockquote></details>

Done.
___
*[utils/qemu/topology/README.md, line 15 at r11](https://reviewable.io/reviews/memkind/memkind/436#-MQSZY8g49eD1CJCbckD:-MQW2I-0-yxLAUnC2qve:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/60e4078e9f84d29ac9976a28ee8194f4c6214bfe/utils/qemu/topology/README.md#L15)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

(...) on sockets 0, 1 and 3
</blockquote></details>

Done.
___
*[utils/qemu/topology/README.md, line 16 at r11](https://reviewable.io/reviews/memkind/memkind/436#-MQSZqdq64iDL20fTtOo:-MQW2IpVEtl2oSRYfeH6:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/60e4078e9f84d29ac9976a28ee8194f4c6214bfe/utils/qemu/topology/README.md#L16)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

(...) on socket 0 and 2 PMEMs on socket 3
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-01-11 08:12 UTC, michalbiesek reviewed
> Reviewed 8 of 22 files at r9, 7 of 12 files at r11, 5 of 5 files at r12.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/436)* status: all files reviewed, 36 unresolved discussions (waiting on @bratpiorka and @PatKamin)

___
*[include/memkind/internal/memkind_mem_attributes.h, line 2 at r12](https://reviewable.io/reviews/memkind/memkind/436#-MQhmWH2-2Q9qf0zHu4l:-MQhmWH36BLi7HNY1Ssi:b1n57m5) ([raw file](https://github.com/memkind/memkind/blob/7d356263ad3da7c4eff45c0fdbcb4391125b4608/include/memkind/internal/memkind_mem_attributes.h#L2)):*
> ```
> 2020
> ```
2020 - 2021
___
*[man/memkindallocator.3, line 58 at r12](https://reviewable.io/reviews/memkind/memkind/436#-MQhmv_B9Dx83uf4V6p-:-MQhmv_B9Dx83uf4V6p0:b-7ixejl) ([raw file](https://github.com/memkind/memkind/blob/7d356263ad3da7c4eff45c0fdbcb4391125b4608/man/memkindallocator.3#L58)):*
> ```
> .B libmemkind::kinds::HIGHEST_CAPACITY_LOCAL
> ```
.PP
.B libmemkind::kinds::HIGHEST_CAPACITY_LOCAL
___
*[man/memkindallocator.3, line 158 at r12](https://reviewable.io/reviews/memkind/memkind/436#-MQi8xLN354Woxan_Q9u:-MQi8xLN354Woxan_Q9v:bvks6g4) ([raw file](https://github.com/memkind/memkind/blob/7d356263ad3da7c4eff45c0fdbcb4391125b4608/man/memkindallocator.3#L158)):*
> ```Roff
> .br
> .BI "T *libmemkind::static_kind::allocator<T>::allocate(std::size_t " "n")
> allocates memory using
> ```

nit: please start the commit message from the capital letter.
___
*[man/memkindallocator.3, line 192 at r12](https://reviewable.io/reviews/memkind/memkind/436#-MQhn0h8By12dd3W9Pr5:-MQhn0h8By12dd3W9Pr6:b-c42xa4) ([raw file](https://github.com/memkind/memkind/blob/7d356263ad3da7c4eff45c0fdbcb4391125b4608/man/memkindallocator.3#L192)):*
> ```
> 2020
> ```
2021
___
*[src/memkind_capacity.c, line 10 at r12](https://reviewable.io/reviews/memkind/memkind/436#-MQhnK3v1JRXn6ZmplUl:-MQhnK3v1JRXn6ZmplUm:bqff3os) ([raw file](https://github.com/memkind/memkind/blob/7d356263ad3da7c4eff45c0fdbcb4391125b4608/src/memkind_capacity.c#L10)):*
> ```
> #include "config.h"
> ```
not needed
___
*[src/memkind_capacity.c, line 13 at r12](https://reviewable.io/reviews/memkind/memkind/436#-MQhnHgvEFKtsHTRxod0:-MQhnHgvEFKtsHTRxod1:bc2tuys) ([raw file](https://github.com/memkind/memkind/blob/7d356263ad3da7c4eff45c0fdbcb4391125b4608/src/memkind_capacity.c#L13)):*
> ```
> #ifdef MEMKIND_HWLOC
> #include <hwloc.h>
> #endif
> ```
not needed
___
*[src/memkind_capacity.c, line 42 at r12](https://reviewable.io/reviews/memkind/memkind/436#-MQi73FE9sN5oCSMOfPO:-MQi73FE9sN5oCSMOfPP:b-njy5r) ([raw file](https://github.com/memkind/memkind/blob/7d356263ad3da7c4eff45c0fdbcb4391125b4608/src/memkind_capacity.c#L42)):*
<details><summary><i alt="summary">Quoted 6 lines of code…</i></summary>

> ```
>     g->per_cpu_numa_nodes = calloc(sizeof(struct bitmask *), num_cpus);
>     if (MEMKIND_UNLIKELY(g->per_cpu_numa_nodes == NULL)) {
>         g->init_err = MEMKIND_ERROR_MALLOC;
>         log_err("malloc() failed.");
>         return;
>     }
> ```
</details>

I am not sure but is it possible to move this inside get_per_cpu_hi_cap_local_nodes_mask ? Therefore you could call free on this whole structure - only in case of success.
___
*[src/memkind_capacity.c, line 45 at r12](https://reviewable.io/reviews/memkind/memkind/436#-MQkJUm58vZ6BvUoHxYD:-MQkJUm58vZ6BvUoHxYE:bo20nxu) ([raw file](https://github.com/memkind/memkind/blob/7d356263ad3da7c4eff45c0fdbcb4391125b4608/src/memkind_capacity.c#L45)):*
> ```
> malloc()
> ```
with current implementation: calloc()
___
*[src/memkind_capacity.c, line 51 at r12](https://reviewable.io/reviews/memkind/memkind/436#-MQhnUPk3emaHUuesuRF:-MQhnUPk3emaHUuesuRG:b-yultt2) ([raw file](https://github.com/memkind/memkind/blob/7d356263ad3da7c4eff45c0fdbcb4391125b4608/src/memkind_capacity.c#L51)):*
> ```
>  return;
> ```
not needed
___
*[src/memkind_capacity.c, line 79 at r12](https://reviewable.io/reviews/memkind/memkind/436#-MQhrLiz0X3abRiVS7WX:-MQhrLiz0X3abRiVS7WY:b-p6z5e1) ([raw file](https://github.com/memkind/memkind/blob/7d356263ad3da7c4eff45c0fdbcb4391125b4608/src/memkind_capacity.c#L79)):*
> ```
> i <= num_cpu
> ```
i < num_cpu ?
___
*[src/memkind_capacity.c, line 88 at r12](https://reviewable.io/reviews/memkind/memkind/436#-MQi6tZa73eYWwuwQZVO:-MQi6tZa73eYWwuwQZVP:bismj8z) ([raw file](https://github.com/memkind/memkind/blob/7d356263ad3da7c4eff45c0fdbcb4391125b4608/src/memkind_capacity.c#L88)):*
> ```
> return 0;
> ```
return memkind_arena_finalize(kind); 
I mean you don't call arena_destroy in memkind_hi_cap_loc_finalize or I miss something? Please check the negative case I mean in a situation when you don't have libhwloc. I am not sure if in this case the jemalloc arena will be created.
___
*[src/memkind_mem_attributes.c, line 2 at r12](https://reviewable.io/reviews/memkind/memkind/436#-MQhzS2I8pabY6sn7Qy6:-MQhzS2I8pabY6sn7Qy7:b1n57m5) ([raw file](https://github.com/memkind/memkind/blob/7d356263ad3da7c4eff45c0fdbcb4391125b4608/src/memkind_mem_attributes.c#L2)):*
> ```
> 2020
> ```
2020 - 2021
___
*[src/memkind_mem_attributes.c, line 37 at r12](https://reviewable.io/reviews/memkind/memkind/436#-MQhnlH6B076pN4ecM6J:-MQhnlH6B076pN4ecM6K:b-yobr10) ([raw file](https://github.com/memkind/memkind/blob/7d356263ad3da7c4eff45c0fdbcb4391125b4608/src/memkind_mem_attributes.c#L37)):*
> ```
>     hwloc_obj_t *local_nodes = calloc(sizeof(struct hwloc_obj_t *),
>                                       max_node_id + 1);
> ```
malloc - I don't see the point for zeroing the memory or I miss something?
___
*[src/memkind_mem_attributes.c, line 37 at r12](https://reviewable.io/reviews/memkind/memkind/436#-MQhtmpnC3-T64sXqrWR:-MQhtmpnC3-T64sXqrWS:bxl7xiw) ([raw file](https://github.com/memkind/memkind/blob/7d356263ad3da7c4eff45c0fdbcb4391125b4608/src/memkind_mem_attributes.c#L37)):*
> ```
> struct hwloc_obj_t *
> ```
struct hwloc_obj_t ?
___
*[src/memkind_mem_attributes.c, line 38 at r12](https://reviewable.io/reviews/memkind/memkind/436#-MQhpA3tBiwxzdfD8xHf:-MQhpA3tBiwxzdfD8xHg:b-gthpak) ([raw file](https://github.com/memkind/memkind/blob/7d356263ad3da7c4eff45c0fdbcb4391125b4608/src/memkind_mem_attributes.c#L38)):*
> ```
> max_node_id + 1
> ```
actually, you don't need here the highest NUMA Node  +1 you need the number of configured NUMA Nodes - total number of NUMA Nodes. Consider a scenario where we could have:

available: 5 nodes (0-3,5) - max_node_id is 5 and in your implementation, you allocate space for 6 Nodes and you actually need only to allocate space for 5 Nodes (Node 0,1,2,3,5)
___
*[src/memkind_mem_attributes.c, line 41 at r12](https://reviewable.io/reviews/memkind/memkind/436#-MQhnrE009mVEX4FVbhZ:-MQhnrE009mVEX4FVbh_:bdpen6g) ([raw file](https://github.com/memkind/memkind/blob/7d356263ad3da7c4eff45c0fdbcb4391125b4608/src/memkind_mem_attributes.c#L41)):*
> ```
> calloc()
> ```
malloc
___
*[src/memkind_mem_attributes.c, line 42 at r12](https://reviewable.io/reviews/memkind/memkind/436#-MQhnuId7TEonWqtqjoy:-MQhnuId7TEonWqtqjoz:bifx010) ([raw file](https://github.com/memkind/memkind/blob/7d356263ad3da7c4eff45c0fdbcb4391125b4608/src/memkind_mem_attributes.c#L42)):*
> ```
> goto error;
> ```
please be consistent with returning see that in the previous situation (similar in case of allocated structures) you call return;
___
*[src/memkind_mem_attributes.c, line 46 at r12](https://reviewable.io/reviews/memkind/memkind/436#-MQhqlbBBubJwQbw0_GQ:-MQhqlbBBubJwQbw0_GR:b86bt1y) ([raw file](https://github.com/memkind/memkind/blob/7d356263ad3da7c4eff45c0fdbcb4391125b4608/src/memkind_mem_attributes.c#L46)):*
> ```
>     while ((init_node = hwloc_get_next_obj_by_type(topology, HWLOC_OBJ_PU,
>                                                    init_node)) != NULL) {
> ```
Consider modifying this to use HWLOC_OBJ_NUMANODE.
Currently, you iterate over each processing unit (I think the intention of variable name and logic below is a little confusing), and for each processing unit, you check the capacity for all local nodes.

You could do this as iterate  [...]

2021-01-11 11:49 UTC, bratpiorka reviewed
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/436)* status: 19 of 24 files reviewed, 35 unresolved discussions (waiting on @michalbiesek and @PatKamin)

___
*[include/memkind/internal/memkind_mem_attributes.h, line 2 at r12](https://reviewable.io/reviews/memkind/memkind/436#-MQhmWH2-2Q9qf0zHu4l:-MQlG704EVKqvhCEEQCG:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/7d356263ad3da7c4eff45c0fdbcb4391125b4608/include/memkind/internal/memkind_mem_attributes.h#L2)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> 2020
> ```
2020 - 2021
</blockquote></details>

Done.
___
*[man/memkindallocator.3, line 58 at r12](https://reviewable.io/reviews/memkind/memkind/436#-MQhmv_B9Dx83uf4V6p-:-MQlG8RCA2JT47UjHWmr:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/7d356263ad3da7c4eff45c0fdbcb4391125b4608/man/memkindallocator.3#L58)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> .B libmemkind::kinds::HIGHEST_CAPACITY_LOCAL
> ```
.PP
.B libmemkind::kinds::HIGHEST_CAPACITY_LOCAL
</blockquote></details>

Done.
___
*[man/memkindallocator.3, line 192 at r12](https://reviewable.io/reviews/memkind/memkind/436#-MQhn0h8By12dd3W9Pr5:-MQlGAMUAiXRxiYe8mKB:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/7d356263ad3da7c4eff45c0fdbcb4391125b4608/man/memkindallocator.3#L192)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> 2020
> ```
2021
</blockquote></details>

Done.
___
*[src/memkind_capacity.c, line 10 at r12](https://reviewable.io/reviews/memkind/memkind/436#-MQhnK3v1JRXn6ZmplUl:-MQlGBBm-KajcZdM2365:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/7d356263ad3da7c4eff45c0fdbcb4391125b4608/src/memkind_capacity.c#L10)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> #include "config.h"
> ```
not needed
</blockquote></details>

Done.
___
*[src/memkind_capacity.c, line 13 at r12](https://reviewable.io/reviews/memkind/memkind/436#-MQhnHgvEFKtsHTRxod0:-MQlGBPu-S3m8AzYk9-I:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/7d356263ad3da7c4eff45c0fdbcb4391125b4608/src/memkind_capacity.c#L13)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> #ifdef MEMKIND_HWLOC
> #include <hwloc.h>
> #endif
> ```
not needed
</blockquote></details>

Done.
___
*[src/memkind_capacity.c, line 42 at r12](https://reviewable.io/reviews/memkind/memkind/436#-MQi73FE9sN5oCSMOfPO:-MQlGfqCEFp8Z8H2LkpE:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/7d356263ad3da7c4eff45c0fdbcb4391125b4608/src/memkind_capacity.c#L42)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
>     g->per_cpu_numa_nodes = calloc(sizeof(struct bitmask *), num_cpus);
>     if (MEMKIND_UNLIKELY(g->per_cpu_numa_nodes == NULL)) {
>         g->init_err = MEMKIND_ERROR_MALLOC;
>         log_err("malloc() failed.");
>         return;
>     }
> ```
I am not sure but is it possible to move this inside get_per_cpu_hi_cap_local_nodes_mask ? Therefore you could call free on this whole structure - only in case of success.
</blockquote></details>

Done.
___
*[src/memkind_capacity.c, line 45 at r12](https://reviewable.io/reviews/memkind/memkind/436#-MQkJUm58vZ6BvUoHxYD:-MQlGgNKCDKaWVdv5L-y:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/7d356263ad3da7c4eff45c0fdbcb4391125b4608/src/memkind_capacity.c#L45)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> malloc()
> ```
with current implementation: calloc()
</blockquote></details>

Done.
___
*[src/memkind_capacity.c, line 51 at r12](https://reviewable.io/reviews/memkind/memkind/436#-MQhnUPk3emaHUuesuRF:-MQlGh9I-ZS_4o-Kee6H:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/7d356263ad3da7c4eff45c0fdbcb4391125b4608/src/memkind_capacity.c#L51)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
>  return;
> ```
not needed
</blockquote></details>

Done.
___
*[src/memkind_capacity.c, line 79 at r12](https://reviewable.io/reviews/memkind/memkind/436#-MQhrLiz0X3abRiVS7WX:-MQlGi0IBO3VPtvZaR2i:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/7d356263ad3da7c4eff45c0fdbcb4391125b4608/src/memkind_capacity.c#L79)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> i <= num_cpu
> ```
i < num_cpu ?
</blockquote></details>

Done.
___
*[src/memkind_capacity.c, line 88 at r12](https://reviewable.io/reviews/memkind/memkind/436#-MQi6tZa73eYWwuwQZVO:-MQlGiur3PdIbfvDkok8:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/7d356263ad3da7c4eff45c0fdbcb4391125b4608/src/memkind_capacity.c#L88)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> return 0;
> ```
return memkind_arena_finalize(kind); 
I mean you don't call arena_destroy in memkind_hi_cap_loc_finalize or I miss something? Please check the negative case I mean in a situation when you don't have libhwloc. I am not sure if in this case the jemalloc arena will be created.
</blockquote></details>

Done.
___
*[src/memkind_mem_attributes.c, line 2 at r12](https://reviewable.io/reviews/memkind/memkind/436#-MQhzS2I8pabY6sn7Qy6:-MQlGCoO4SK-u0IRgQ3N:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/7d356263ad3da7c4eff45c0fdbcb4391125b4608/src/memkind_mem_attributes.c#L2)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> 2020
> ```
2020 - 2021
</blockquote></details>

Done.
___
*[src/memkind_mem_attributes.c, line 37 at r12](https://reviewable.io/reviews/memkind/memkind/436#-MQhnlH6B076pN4ecM6J:-MQlGMP43KS5QW2NGrs6:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/7d356263ad3da7c4eff45c0fdbcb4391125b4608/src/memkind_mem_attributes.c#L37)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
>     hwloc_obj_t *local_nodes = calloc(sizeof(struct hwloc_obj_t *),
>                                       max_node_id + 1);
> ```
malloc - I don't see the point for zeroing the memory or I miss something?
</blockquote></details>

Done.
___
*[src/memkind_mem_attributes.c, line 37 at r12](https://reviewable.io/reviews/memkind/memkind/436#-MQhtmpnC3-T64sXqrWR:-MQlGMcK4ttjjIZG0dH0:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/7d356263ad3da7c4eff45c0fdbcb4391125b4608/src/memkind_mem_attributes.c#L37)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> struct hwloc_obj_t *
> ```
struct hwloc_obj_t ?
</blockquote></details>

Done.
___
*[src/memkind_mem_attributes.c, line 38 at r12](https://reviewable.io/reviews/memkind/memkind/436#-MQhpA3tBiwxzdfD8xHf:-MQlGNm0BlfTaOhs2Db3:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/7d356263ad3da7c4eff45c0fdbcb4391125b4608/src/memkind_mem_attributes.c#L38)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> max_node_id + 1
> ```
actually, you don't need here the highest NUMA Node  +1 you need the number of configured NUMA Nodes - total number of NUMA Nodes. Consider a scenario where we could have:

available: 5 nodes (0-3,5) - max_node_id is 5 and in your implementation, you allocate space for 6 Nodes and you actually need only to allocate space for 5 Nodes (Node 0,1,2,3,5)

</blockquote></details>

Done.
___
*[src/memkind_mem_attributes.c, line 41 at r12](https://reviewable.io/reviews/memkind/memkind/436#-MQhnrE009mVEX4FVbhZ:-MQlGPHU5vpjk-VPx9-a:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/7d356263ad3da7c4eff45c0fdbcb4391125b4608/src/memkind_mem_attributes.c#L41)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> calloc()
> ```
malloc
</blockquote></details>

Done.
___
*[src/memkind_mem_attributes.c, line 42 at r12](https://reviewable.io/reviews/memkind/memkind/436#-MQhnuId [...]

2021-01-11 12:51 UTC, michalbiesek reviewed
> Reviewed 2 of 5 files at r13.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/436)* status: 21 of 24 files reviewed, 19 unresolved discussions (waiting on @bratpiorka, @michalbiesek, and @PatKamin)

___
*[MANIFEST, line 580 at r13](https://reviewable.io/reviews/memkind/memkind/436#-MQlT_4XBk0NcNfZPWCe:-MQlT_4XBk0NcNfZPWCf:bp7lppc) ([raw file](https://github.com/memkind/memkind/blob/dac53e574262eddc50c637a2852cd07abb6018b0/MANIFEST#L580)):*
> ```
> utils/qemu/topology/clx_4_var2.xml
> utils/qemu/topology/clx_4_var3.xml
> utils/qemu/topology/knm_all2all.xml
> ```

add utils/qemu/topology/clx_4_var4.xml
___
*[Makefile.am, line 413 at r13](https://reviewable.io/reviews/memkind/memkind/436#-MQlTWnDDY7zN3mF52sR:-MQlTWnDDY7zN3mF52sS:bpie3gg) ([raw file](https://github.com/memkind/memkind/blob/dac53e574262eddc50c637a2852cd07abb6018b0/Makefile.am#L413)):*
> ```Makefile
>              utils/qemu/topology/clx_4_var2.xml \
>              utils/qemu/topology/clx_4_var3.xml \
>              utils/qemu/topology/knm_all2all.xml \
> ```


add utils/qemu/topology/clx_4_var4.xml
___
*[copying_headers/MANIFEST.freeBSD, line 216 at r13](https://reviewable.io/reviews/memkind/memkind/436#-MQlR4elEMLCH_jF3ENh:-MQlR4elEMLCH_jF3ENi:b-i8z5gi) ([raw file](https://github.com/memkind/memkind/blob/dac53e574262eddc50c637a2852cd07abb6018b0/copying_headers/MANIFEST.freeBSD#L216)):*
> ```
> utils/qemu/topology/clx_4_var1.xml
> utils/qemu/topology/clx_4_var2.xml
> utils/qemu/topology/clx_4_var3.xml
> ```


Add: utils/qemu/topology/clx_4_var4.xml
___
*[include/memkind/internal/memkind_mem_attributes.h, line 2 at r12](https://reviewable.io/reviews/memkind/memkind/436#-MQhmWH2-2Q9qf0zHu4l:-MQlRBsu1R3HaRqJfKli:b6euavv) ([raw file](https://github.com/memkind/memkind/blob/7d356263ad3da7c4eff45c0fdbcb4391125b4608/include/memkind/internal/memkind_mem_attributes.h#L2)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

2020 - 2021 not 2021
___
*[src/memkind_capacity.c, line 34 at r13](https://reviewable.io/reviews/memkind/memkind/436#-MQlRaDM20ajjWXeOUjf:-MQlRaDN3xffO7sM9EVe:b9brqr6) ([raw file](https://github.com/memkind/memkind/blob/dac53e574262eddc50c637a2852cd07abb6018b0/src/memkind_capacity.c#L34)):*
> ```
> int num_cpus = numa_num_configured_cpus();
> ```
I believe you could call this inside get_per_cpu_hi_cap_local_nodes_mask.
___
*[src/memkind_capacity.c, line 74 at r13](https://reviewable.io/reviews/memkind/memkind/436#-MQlRtp_BoGNCi1CVVWM:-MQlRtp_BoGNCi1CVVWN:bb5wsu4) ([raw file](https://github.com/memkind/memkind/blob/dac53e574262eddc50c637a2852cd07abb6018b0/src/memkind_capacity.c#L74)):*
> ```
> free(g->per_cpu_numa_nodes);
> ```
move this inside if above
___
*[src/memkind_mem_attributes.c, line 2 at r12](https://reviewable.io/reviews/memkind/memkind/436#-MQhzS2I8pabY6sn7Qy6:-MQlRyel9lgudkqOcwll:bhf9n9f) ([raw file](https://github.com/memkind/memkind/blob/7d356263ad3da7c4eff45c0fdbcb4391125b4608/src/memkind_mem_attributes.c#L2)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

2020 - 2021. not only 2021
___
*[src/memkind_mem_attributes.c, line 42 at r12](https://reviewable.io/reviews/memkind/memkind/436#-MQhnuId7TEonWqtqjoy:-MQlUN3d6fNl4d1k0e2N:b-x5hza3) ([raw file](https://github.com/memkind/memkind/blob/7d356263ad3da7c4eff45c0fdbcb4391125b4608/src/memkind_mem_attributes.c#L42)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Actually this comment was related to line: *nodes_mask = calloc(sizeof(struct bitmask *), num_cpus); - my bad if I point it here.


<!-- Sent from Reviewable.io -->

2021-01-12 08:55 UTC, michalbiesek reviewed
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/436)* status: 21 of 24 files reviewed, 20 unresolved discussions (waiting on @bratpiorka, @michalbiesek, and @PatKamin)

___
*[src/memkind_capacity.c, line 12 at r13](https://reviewable.io/reviews/memkind/memkind/436#-MQpnPYf6j1aa0aq3Lt5:-MQpnPYf6j1aa0aq3Lt6:bnu66s) ([raw file](https://github.com/memkind/memkind/blob/dac53e574262eddc50c637a2852cd07abb6018b0/src/memkind_capacity.c#L12)):*
> ```
> memkind_hi_cap_loc_numanodes_t
> ```
nit: could you rename this without "memkind" prefix -> hi_cap_loc_numanodes_t, therefore this will be similar to naming for structure below.


<!-- Sent from Reviewable.io -->

2021-01-12 10:02 UTC, bratpiorka reviewed
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/436)* status: 13 of 26 files reviewed, 19 unresolved discussions (waiting on @bratpiorka, @michalbiesek, and @PatKamin)

___
*[Makefile.am, line 413 at r13](https://reviewable.io/reviews/memkind/memkind/436#-MQlTWnDDY7zN3mF52sR:-MQq1bop04L-JjOv0dQF:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/dac53e574262eddc50c637a2852cd07abb6018b0/Makefile.am#L413)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

add utils/qemu/topology/clx_4_var4.xml
</blockquote></details>

Done.
___
*[copying_headers/MANIFEST.freeBSD, line 216 at r13](https://reviewable.io/reviews/memkind/memkind/436#-MQlR4elEMLCH_jF3ENh:-MQq1dNF7GcaNTpRCWDO:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/dac53e574262eddc50c637a2852cd07abb6018b0/copying_headers/MANIFEST.freeBSD#L216)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

Add: utils/qemu/topology/clx_4_var4.xml
</blockquote></details>

Done.
___
*[src/memkind_capacity.c, line 34 at r13](https://reviewable.io/reviews/memkind/memkind/436#-MQlRaDM20ajjWXeOUjf:-MQq1m-vA2lQqsMkm-by:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/dac53e574262eddc50c637a2852cd07abb6018b0/src/memkind_capacity.c#L34)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> int num_cpus = numa_num_configured_cpus();
> ```
I believe you could call this inside get_per_cpu_hi_cap_local_nodes_mask.
</blockquote></details>

Done.
___
*[src/memkind_capacity.c, line 74 at r13](https://reviewable.io/reviews/memkind/memkind/436#-MQlRtp_BoGNCi1CVVWM:-MQq1mvq0Kl0h-G8wE70:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/dac53e574262eddc50c637a2852cd07abb6018b0/src/memkind_capacity.c#L74)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> free(g->per_cpu_numa_nodes);
> ```
move this inside if above
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-01-12 10:21 UTC, michalbiesek reviewed
> Reviewed 1 of 12 files at r11, 11 of 13 files at r14, 1 of 1 files at r15.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/436)* status: 24 of 26 files reviewed, 15 unresolved discussions (waiting on @bratpiorka, @michalbiesek, and @PatKamin)

___
*[src/memkind_mem_attributes.c, line 37 at r12](https://reviewable.io/reviews/memkind/memkind/436#-MQhtmpnC3-T64sXqrWR:-MQq48wU87RVJT_kRc71:bke8wwn) ([raw file](https://github.com/memkind/memkind/blob/7d356263ad3da7c4eff45c0fdbcb4391125b4608/src/memkind_mem_attributes.c#L37)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

As we spoke offline:
Replace
local_nodes = malloc(sizeof(struct hwloc_obj_t *) * num_nodes);
with:
local_nodes = malloc(sizeof(hwloc_obj_t) * num_nodes);
___
*[test/memkind_hmat_tests.cpp, line 95 at r14](https://reviewable.io/reviews/memkind/memkind/436#-MQq5blnCG8r1ssIDAzg:-MQq4miSEWQCryPTD3nM:br13v0i) ([raw file](https://github.com/memkind/memkind/blob/d5b2244db9be4f6441c0a1f4398fddf5536138a6/test/memkind_hmat_tests.cpp#L95)):*
> ```cpp
>         }
>     }
> }
> ```

Your second test - with a fallback strategy was a good point here
___
*[utils/qemu/topology/clx_4_var1.xml, line 2 at r14](https://reviewable.io/reviews/memkind/memkind/436#-MQq5RoI0uDPe-qt7goL:-MQq5RoI0uDPe-qt7goM:b8lsyqk) ([raw file](https://github.com/memkind/memkind/blob/d5b2244db9be4f6441c0a1f4398fddf5536138a6/utils/qemu/topology/clx_4_var1.xml#L2)):*
> ```
> 2020
> ```
nit: 2020 - 2021


<!-- Sent from Reviewable.io -->

2021-01-12 11:05 UTC, PatKamin reviewed
> Reviewed 1 of 5 files at r12, 1 of 5 files at r13, 11 of 13 files at r14.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/436)* status: 25 of 26 files reviewed, 8 unresolved discussions (waiting on @bratpiorka, @michalbiesek, and @PatKamin)

___
*[test/memkind_hmat_tests.cpp, line 49 at r14](https://reviewable.io/reviews/memkind/memkind/436#-MQqFH0p4SujFF2MfOBr:-MQqFH0q339wcep-5Yua:b-asut7u) ([raw file](https://github.com/memkind/memkind/blob/d5b2244db9be4f6441c0a1f4398fddf5536138a6/test/memkind_hmat_tests.cpp#L49)):*
> ```cpp
>             TopologyMap.emplace(MemoryTpg("CascadeLake4Var4", TpgPtr(new CLX_4_var4)));
> ```

Remove one of the empty lines. Maybe even both.


<!-- Sent from Reviewable.io -->

2021-01-12 13:03 UTC, bratpiorka reviewed
> Reviewed 7 of 22 files at r9, 1 of 5 files at r10, 3 of 12 files at r11, 1 of 5 files at r12, 1 of 5 files at r13, 12 of 13 files at r14, 1 of 1 files at r15, 5 of 5 files at r16.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/436)* status: all files reviewed, 7 unresolved discussions (waiting on @michalbiesek and @PatKamin)

___
*[MANIFEST, line 580 at r13](https://reviewable.io/reviews/memkind/memkind/436#-MQlT_4XBk0NcNfZPWCe:-MQq5ozw4kg9selsSIsd:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/dac53e574262eddc50c637a2852cd07abb6018b0/MANIFEST#L580)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

add utils/qemu/topology/clx_4_var4.xml
</blockquote></details>

Done.
___
*[test/memkind_hmat_tests.cpp, line 49 at r14](https://reviewable.io/reviews/memkind/memkind/436#-MQqFH0p4SujFF2MfOBr:-MQqgNU3A8BauTy_FR1k:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/d5b2244db9be4f6441c0a1f4398fddf5536138a6/test/memkind_hmat_tests.cpp#L49)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Remove one of the empty lines. Maybe even both.
</blockquote></details>

Done.
___
*[test/memkind_hmat_tests.cpp, line 95 at r14](https://reviewable.io/reviews/memkind/memkind/436#-MQq5blnCG8r1ssIDAzg:-MQqgKRsE8DjDG3P58ts:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/d5b2244db9be4f6441c0a1f4398fddf5536138a6/test/memkind_hmat_tests.cpp#L95)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

Your second test - with a fallback strategy was a good point here
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-01-12 13:07 UTC, PatKamin reviewed
> Reviewed 2 of 5 files at r16.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/436)* status: all files reviewed, 7 unresolved discussions (waiting on @bratpiorka, @michalbiesek, and @PatKamin)

___
*[test/memory_topology.h, line 48 at r16](https://reviewable.io/reviews/memkind/memkind/436#-MQqh3pe9CifeAiUbeMV:-MQqh3pe9CifeAiUbeMW:b-ngeb1d) ([raw file](https://github.com/memkind/memkind/blob/65f815980cca914adf5f7e1110200e5d966b21fc/test/memory_topology.h#L48)):*
> ```objc
>         std::cout << "Failed for, Init: " << nodes.init << " Target: " << nodes.target
>                   <<
>                   std::endl;
> ```

Move this to the line before.


<!-- Sent from Reviewable.io -->

2021-01-12 13:31 UTC, michalbiesek requested changes
> Reviewed 2 of 5 files at r16.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/436)* status: all files reviewed, 8 unresolved discussions (waiting on @bratpiorka, @michalbiesek, and @PatKamin)

___
*[test/memkind_hmat_tests.cpp, line 44 at r16](https://reviewable.io/reviews/memkind/memkind/436#-MQqlBuW9PLoVBjWEY7X:-MQqlBuW9PLoVBjWEY7Y:bm8nt6o) ([raw file](https://github.com/memkind/memkind/blob/65f815980cca914adf5f7e1110200e5d966b21fc/test/memkind_hmat_tests.cpp#L44)):*
> ```cpp
>             TopologyMap.emplace(MemoryTpg("KnightsMillSNC4", TpgPtr(new KNM_SNC4)));
>             TopologyMap.emplace(MemoryTpg("CascadeLake2Var1", TpgPtr(new CLX_2_var1)));
>             TopologyMap.emplace(MemoryTpg("CascadeLake2Var2", TpgPtr(new CLX_2_var2)));
> ```

Do you miss CLX_2_var3?
After adding update: TopologyMap.reserve(9); -> TopologyMap.reserve(10);
Please also add a reference to XML to Makefile.am and Manifest files.
___
*[test/memkind_hmat_tests.cpp, line 105 at r16](https://reviewable.io/reviews/memkind/memkind/436#-MQqhVhwBNoh4HPgFpp5:-MQqhVhwBNoh4HPgFpp6:b-1wnaa1) ([raw file](https://github.com/memkind/memkind/blob/65f815980cca914adf5f7e1110200e5d966b21fc/test/memkind_hmat_tests.cpp#L105)):*
> ```
> return;
> ```
GTEST_SKIP();
___
*[test/memory_topology.h, line 60 at r16](https://reviewable.io/reviews/memkind/memkind/436#-MQqiSCQBblwWnDO3CE-:-MQqiSCQBblwWnDO3CE0:bcgtw3) ([raw file](https://github.com/memkind/memkind/blob/65f815980cca914adf5f7e1110200e5d966b21fc/test/memory_topology.h#L60)):*
> ```
> std::unordered_set<int>()
> ```
{}


<!-- Sent from Reviewable.io -->

2021-01-12 14:29 UTC, bratpiorka reviewed
> Reviewed 5 of 5 files at r17, 2 of 2 files at r18.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/436)* status: all files reviewed, 8 unresolved discussions (waiting on @michalbiesek and @PatKamin)

___
*[src/memkind_mem_attributes.c, line 46 at r12](https://reviewable.io/reviews/memkind/memkind/436#-MQhqlbBBubJwQbw0_GQ:-MQqznRR0XUbtGRx_gK5:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/7d356263ad3da7c4eff45c0fdbcb4391125b4608/src/memkind_mem_attributes.c#L46)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

ack
</blockquote></details>

Done.
___
*[src/memkind_mem_attributes.c, line 60 at r12](https://reviewable.io/reviews/memkind/memkind/436#-MQhu-J-EHXgwS6O6prW:-MQqznzq7ltYbBgepXdr:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/7d356263ad3da7c4eff45c0fdbcb4391125b4608/src/memkind_mem_attributes.c#L60)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

it is needed if the initiator has HWLOC_OBJ_PU type
</blockquote></details>

Done.
___
*[test/memkind_highcapacity_tests.cpp, line 8 at r8](https://reviewable.io/reviews/memkind/memkind/436#-MQGZbng3_0Scp440vBA:-MQqztfP-da_bM0C1vK1:bvth56w) ([raw file](https://github.com/memkind/memkind/blob/2caf3a116541359e0313f7ddfa2ebcfd0d7d3e50/test/memkind_highcapacity_tests.cpp#L8)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

So the removal is necessary? - again this kind of changes obfuscate the intention fo this PR if you want this change please open a separate PR or do this in another commit
</blockquote></details>

reverted
___
*[test/memkind_hmat_tests.cpp, line 44 at r16](https://reviewable.io/reviews/memkind/memkind/436#-MQqlBuW9PLoVBjWEY7X:-MQqxNL29gonhGkrE6nH:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/65f815980cca914adf5f7e1110200e5d966b21fc/test/memkind_hmat_tests.cpp#L44)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

Do you miss CLX_2_var3?
After adding update: TopologyMap.reserve(9); -> TopologyMap.reserve(10);
Please also add a reference to XML to Makefile.am and Manifest files.
</blockquote></details>

Done.
___
*[test/memkind_hmat_tests.cpp, line 105 at r16](https://reviewable.io/reviews/memkind/memkind/436#-MQqhVhwBNoh4HPgFpp5:-MQqxO595xd9EsdTmUyX:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/65f815980cca914adf5f7e1110200e5d966b21fc/test/memkind_hmat_tests.cpp#L105)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> return;
> ```
GTEST_SKIP();
</blockquote></details>

Done.
___
*[test/memory_topology.h, line 48 at r16](https://reviewable.io/reviews/memkind/memkind/436#-MQqh3pe9CifeAiUbeMV:-MQqxPZn686bWXkVk6SL:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/65f815980cca914adf5f7e1110200e5d966b21fc/test/memory_topology.h#L48)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Move this to the line before.
</blockquote></details>

Done.
___
*[test/memory_topology.h, line 60 at r16](https://reviewable.io/reviews/memkind/memkind/436#-MQqiSCQBblwWnDO3CE-:-MQqxQAa-VSrnPoWAiZD:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/65f815980cca914adf5f7e1110200e5d966b21fc/test/memory_topology.h#L60)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> std::unordered_set<int>()
> ```
{}
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-01-12 14:55 UTC, michalbiesek requested changes
> Reviewed 5 of 5 files at r17, 1 of 2 files at r18.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/436)* status: all files reviewed, 3 unresolved discussions (waiting on @bratpiorka and @PatKamin)

___
*[src/memkind_mem_attributes.c, line 116 at r18](https://reviewable.io/reviews/memkind/memkind/436#-MQr3hTFC97aH3Cohomt:-MQr3hTFC97aH3Cohomu:b5pf6rx) ([raw file](https://github.com/memkind/memkind/blob/2d4c77a311f86408600c01299ce9e248e16becb7/src/memkind_mem_attributes.c#L116)):*
> ```
> f (numa_node_of_cpu(i) == init_node->os_index) {
> ```
you could use numa_bitmask_isbitset(node_cpu, i) - 
Therfore you avoid allocation which happened inside numa_node_of_cpu function.


<!-- Sent from Reviewable.io -->

2021-01-12 15:15 UTC, bratpiorka reviewed
> Reviewed 1 of 1 files at r19.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/436)* status: all files reviewed, 3 unresolved discussions (waiting on @michalbiesek and @PatKamin)

___
*[src/memkind_mem_attributes.c, line 116 at r18](https://reviewable.io/reviews/memkind/memkind/436#-MQr3hTFC97aH3Cohomt:-MQr9Rdy693V7OM_cN1Q:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/2d4c77a311f86408600c01299ce9e248e16becb7/src/memkind_mem_attributes.c#L116)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> f (numa_node_of_cpu(i) == init_node->os_index) {
> ```
you could use numa_bitmask_isbitset(node_cpu, i) - 
Therfore you avoid allocation which happened inside numa_node_of_cpu function.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-01-12 15:16 UTC, michalbiesek approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>
I try to stabilize the test_tc_memkind_HMAT_verify_InitTargetNode. I merge this after rest of the jobs will pass. You could start working on the next PR with Preferred Variant of highest_capacity_local.

> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/436#-:-MQr9aLnBfLjo410ddPH:b-qp957j)* status: all files reviewed, 2 unresolved discussions (waiting on @PatKamin)



<!-- Sent from Reviewable.io -->

2021-01-12 15:19 UTC, PatKamin reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 5 of 5 files at r17, 1 of 2 files at r18, 1 of 1 files at r19.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/436#-:-MQrATv9DHAhVmTEwvbf:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @bratpiorka)



<!-- Sent from Reviewable.io -->

2021-01-12 16:03 UTC, merged