API for enabling/disabling je_background thread
memkind/memkind pull request #478
Opened 2021-01-20 11:36 UTC by PatKamin

### Description

### Types of changes

- [ ] Bugfix (non-breaking change which fixes issue linked in Description above)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation (correction or otherwise)
- [ ] Cosmetics (whitespace, appearance)
- [ ] Other

### Checklist

- [x] Code compiles without errors
- [x] All tests pass locally with my changes (see TESTING section in CONTRIBUTING file)
- [x] Created tests which will fail without the change (if possible)
- [ ] Extended the README/documentation (if necessary)
- [x] All newly added files have proprietary license (if necessary)
- [x] All newly added files are referenced in MANIFEST files (if necessary)

## Further comments

2021-01-20 11:41 UTC, michalbiesek reviewed
> Reviewed 4 of 12 files at r1.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/478)* status: 4 of 12 files reviewed, 5 unresolved discussions (waiting on @PatKamin)

___
*[include/memkind.h, line 422 at r1](https://reviewable.io/reviews/memkind/memkind/478#-MRU_OnOCZtafn9eSycn:-MRU_OnOCZtafn9eSyco:bo8oxiq) ([raw file](https://github.com/memkind/memkind/blob/ce82d9c817137d742b5c5b8d24e88ab8960a4709/include/memkind.h#L422)):*
> ```
> int memkind_set_background_threads(bool enable);
> int set_background_threads(bool enable);
> ```
Please add doxygen comments.
I am not sure about bool but let me think about it.
___
*[src/heap_manager.c, line 37 at r1](https://reviewable.io/reviews/memkind/memkind/478#-MRUaDHO2sxG5B7BCR5l:-MRUaDHO2sxG5B7BCR5m:b-al1a1b) ([raw file](https://github.com/memkind/memkind/blob/ce82d9c817137d742b5c5b8d24e88ab8960a4709/src/heap_manager.c#L37)):*
> ```
> set_background_threads
> ```
memkind_arena_set_background_threads
___
*[src/memkind.c, line 928 at r1](https://reviewable.io/reviews/memkind/memkind/478#-MRUa2012Dlkc6oLxuUf:-MRUa2012Dlkc6oLxuUg:b-7t9iy0) ([raw file](https://github.com/memkind/memkind/blob/ce82d9c817137d742b5c5b8d24e88ab8960a4709/src/memkind.c#L928)):*
<details><summary><i alt="summary">Quoted 8 lines of code…</i></summary>

> ```
> int set_background_threads(bool enable) {
>     int err = jemk_mallctl("background_thread", NULL, NULL, &enable, sizeof(bool));
>     if (err) {
>         log_err("Error while enabling/disabling background thread");
>         return MEMKIND_ERROR_INVALID;
>     }
>     return err;
> }
> ```
</details>

please move this to memkind_arena module
___
*[src/memkind_arena.c, line 840 at r1](https://reviewable.io/reviews/memkind/memkind/478#-MRU_cz140eg6u439go0:-MRU_cz2AG_I93-_XnDB:bwwlgq7) ([raw file](https://github.com/memkind/memkind/blob/ce82d9c817137d742b5c5b8d24e88ab8960a4709/src/memkind_arena.c#L840)):*
> ```
> -1
> ```
MEMKIND_ERROR_INVALID; ?
___
*[test/background_threads_tests.cpp, line 31 at r1](https://reviewable.io/reviews/memkind/memkind/478#-MRU_gI25lEn7oCZLdMb:-MRU_gI25lEn7oCZLdMc:bo7esww) ([raw file](https://github.com/memkind/memkind/blob/ce82d9c817137d742b5c5b8d24e88ab8960a4709/test/background_threads_tests.cpp#L31)):*
> ```cpp
> 
>     for (unsigned i = 0; i < 10 * cpus_count; i++) {
> 		ASSERT_TRUE(memkind_malloc(MEMKIND_REGULAR, 1) != NULL);
> ```

run astyle please


<!-- Sent from Reviewable.io -->

2021-01-20 11:56 UTC, michalbiesek reviewed
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/478)* status: 4 of 12 files reviewed, 7 unresolved discussions (waiting on @PatKamin)

___
*[include/memkind.h, line 424 at r1](https://reviewable.io/reviews/memkind/memkind/478#-MRUdVIVDSa6QWSU-o8E:-MRUdVIVDSa6QWSU-o8F:bff89nz) ([raw file](https://github.com/memkind/memkind/blob/ce82d9c817137d742b5c5b8d24e88ab8960a4709/include/memkind.h#L424)):*
> ```
> int set_background_threads(bool enable);
> ```
No need to expose this outside.
___
*[src/memkind.c, line 58 at r1](https://reviewable.io/reviews/memkind/memkind/478#-MRUdMOk5O0AE9VLRJNm:-MRUdMOk5O0AE9VLRJNn:bxg2yu1) ([raw file](https://github.com/memkind/memkind/blob/ce82d9c817137d742b5c5b8d24e88ab8960a4709/src/memkind.c#L58)):*
> ```
> m_set_background_threads
> ```
m_set_bg_thread


<!-- Sent from Reviewable.io -->

2021-01-20 12:25 UTC, PatKamin reviewed
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/478)* status: 3 of 13 files reviewed, 7 unresolved discussions (waiting on @michalbiesek and @PatKamin)

___
*[include/memkind.h, line 424 at r1](https://reviewable.io/reviews/memkind/memkind/478#-MRUdVIVDSa6QWSU-o8E:-MRUkS8Z-Pnkrj3radnL:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/ce82d9c817137d742b5c5b8d24e88ab8960a4709/include/memkind.h#L424)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> int set_background_threads(bool enable);
> ```
No need to expose this outside.
</blockquote></details>

Done.
___
*[src/heap_manager.c, line 37 at r1](https://reviewable.io/reviews/memkind/memkind/478#-MRUaDHO2sxG5B7BCR5l:-MRUkQmU0fugutR9N1B5:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/ce82d9c817137d742b5c5b8d24e88ab8960a4709/src/heap_manager.c#L37)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> set_background_threads
> ```
memkind_arena_set_background_threads
</blockquote></details>

Done.
___
*[src/memkind.c, line 928 at r1](https://reviewable.io/reviews/memkind/memkind/478#-MRUa2012Dlkc6oLxuUf:-MRUkQ3A6MzIBakF8jLF:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/ce82d9c817137d742b5c5b8d24e88ab8960a4709/src/memkind.c#L928)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> int set_background_threads(bool enable) {
>     int err = jemk_mallctl("background_thread", NULL, NULL, &enable, sizeof(bool));
>     if (err) {
>         log_err("Error while enabling/disabling background thread");
>         return MEMKIND_ERROR_INVALID;
>     }
>     return err;
> }
> ```
please move this to memkind_arena module
</blockquote></details>

Done.
___
*[src/memkind_arena.c, line 840 at r1](https://reviewable.io/reviews/memkind/memkind/478#-MRU_cz140eg6u439go0:-MRUkWhi3teygfsKllww:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/ce82d9c817137d742b5c5b8d24e88ab8960a4709/src/memkind_arena.c#L840)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> -1
> ```
MEMKIND_ERROR_INVALID; ?
</blockquote></details>

Done.
___
*[test/background_threads_tests.cpp, line 31 at r1](https://reviewable.io/reviews/memkind/memkind/478#-MRU_gI25lEn7oCZLdMb:-MRUkOQK2U8-gftFUmlE:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/ce82d9c817137d742b5c5b8d24e88ab8960a4709/test/background_threads_tests.cpp#L31)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

run astyle please
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-01-20 12:29 UTC, PatKamin reviewed
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/478)* status: 3 of 13 files reviewed, 7 unresolved discussions (waiting on @michalbiesek and @PatKamin)

___
*[include/memkind.h, line 422 at r1](https://reviewable.io/reviews/memkind/memkind/478#-MRU_OnOCZtafn9eSycn:-MRUlM_26ZjMZvxi09j9:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/ce82d9c817137d742b5c5b8d24e88ab8960a4709/include/memkind.h#L422)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> int memkind_set_background_threads(bool enable);
> int set_background_threads(bool enable);
> ```
Please add doxygen comments.
I am not sure about bool but let me think about it.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-01-20 12:32 UTC, PatKamin reviewed
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/478)* status: 3 of 13 files reviewed, 7 unresolved discussions (waiting on @michalbiesek)

___
*[src/memkind.c, line 58 at r1](https://reviewable.io/reviews/memkind/memkind/478#-MRUdMOk5O0AE9VLRJNm:-MRUm1dh4JE5-kwBCmUh:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/ce82d9c817137d742b5c5b8d24e88ab8960a4709/src/memkind.c#L58)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> m_set_background_threads
> ```
m_set_bg_thread
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-01-20 12:42 UTC, michalbiesek reviewed
> Reviewed 2 of 7 files at r2, 1 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/478)* status: 6 of 13 files reviewed, 6 unresolved discussions (waiting on @michalbiesek and @PatKamin)

___
*[include/memkind.h, line 423 at r2](https://reviewable.io/reviews/memkind/memkind/478#-MRUlCkk60T3KtoAewbQ:-MRUlCkk60T3KtoAewbR:budhb9a) ([raw file](https://github.com/memkind/memkind/blob/fcddabf5a7f46e06b71d46d9592823069d9af62a/include/memkind.h#L423)):*
> ```
> Verifies if file-backed memory kind in the specified directory can be created with the DAX attribute
> ```
Update to properly one
___
*[src/memkind.c, line 58 at r3](https://reviewable.io/reviews/memkind/memkind/478#-MRUnkjr7enTlaDF9J7D:-MRUnkjr7enTlaDF9J7E:b-z0lbr) ([raw file](https://github.com/memkind/memkind/blob/850d88d9ede41800b9d073c89b4b553f46feb870/src/memkind.c#L58)):*
> ```
> set_background_threads
> ```
memkind_arena_set_background_threads and fix the column with name please - you could use everywhere basically "set_bg_threads" instead of "set_background_threads"
___
*[src/memkind.c, line 924 at r3](https://reviewable.io/reviews/memkind/memkind/478#-MRUo2s39FBpsGuN_pGe:-MRUo2s46EwapXgOC75_:b-omxm30) ([raw file](https://github.com/memkind/memkind/blob/850d88d9ede41800b9d073c89b4b553f46feb870/src/memkind.c#L924)):*
> ```
> int memkind_set_background_threads(bool enable)
> ```
update man3 files.
___
*[test/background_threads_tests.cpp, line 5 at r3](https://reviewable.io/reviews/memkind/memkind/478#-MRUnKrQDhkrN7cG2OLk:-MRUnKrQDhkrN7cG2OLl:bpod7mt) ([raw file](https://github.com/memkind/memkind/blob/850d88d9ede41800b9d073c89b4b553f46feb870/test/background_threads_tests.cpp#L5)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
> #include <memkind/internal/memkind_default.h>
> #include <memkind/internal/memkind_arena.h>
> #include <memkind/internal/memkind_private.h>
> #include <memkind/internal/memkind_log.h>
> ```
</details>

you are sure you need all these includes?
___
*[test/background_threads_tests.cpp, line 31 at r3](https://reviewable.io/reviews/memkind/memkind/478#-MRUnQYn8skcnrmj_N5O:-MRUnQYn8skcnrmj_N5P:b-vqyhfl) ([raw file](https://github.com/memkind/memkind/blob/850d88d9ede41800b9d073c89b4b553f46feb870/test/background_threads_tests.cpp#L31)):*
> ```
> (memkind_malloc
> ```
this is a memory leak - please clean the memory when you finish the test case


<!-- Sent from Reviewable.io -->

2021-01-20 15:17 UTC, PatKamin reviewed
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/478)* status: 3 of 15 files reviewed, 6 unresolved discussions (waiting on @michalbiesek)

___
*[include/memkind.h, line 423 at r2](https://reviewable.io/reviews/memkind/memkind/478#-MRUlCkk60T3KtoAewbQ:-MRUpX9g-AKnjWaKlEZo:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/fcddabf5a7f46e06b71d46d9592823069d9af62a/include/memkind.h#L423)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> Verifies if file-backed memory kind in the specified directory can be created with the DAX attribute
> ```
Update to properly one
</blockquote></details>

Done.
___
*[src/memkind.c, line 58 at r3](https://reviewable.io/reviews/memkind/memkind/478#-MRUnkjr7enTlaDF9J7D:-MRUsGV41dCR8cqSsm-u:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/850d88d9ede41800b9d073c89b4b553f46feb870/src/memkind.c#L58)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> set_background_threads
> ```
memkind_arena_set_background_threads and fix the column with name please - you could use everywhere basically "set_bg_threads" instead of "set_background_threads"
</blockquote></details>

Done.
___
*[src/memkind.c, line 924 at r3](https://reviewable.io/reviews/memkind/memkind/478#-MRUo2s39FBpsGuN_pGe:-MRVGTnT1eQr2kLyabAU:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/850d88d9ede41800b9d073c89b4b553f46feb870/src/memkind.c#L924)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> int memkind_set_background_threads(bool enable)
> ```
update man3 files.
</blockquote></details>

Done.
___
*[test/background_threads_tests.cpp, line 5 at r3](https://reviewable.io/reviews/memkind/memkind/478#-MRUnKrQDhkrN7cG2OLk:-MRVJD935B3n-1YhS9Ud:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/850d88d9ede41800b9d073c89b4b553f46feb870/test/background_threads_tests.cpp#L5)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> #include <memkind/internal/memkind_default.h>
> #include <memkind/internal/memkind_arena.h>
> #include <memkind/internal/memkind_private.h>
> #include <memkind/internal/memkind_log.h>
> ```
you are sure you need all these includes?
</blockquote></details>

Done.
___
*[test/background_threads_tests.cpp, line 31 at r3](https://reviewable.io/reviews/memkind/memkind/478#-MRUnQYn8skcnrmj_N5O:-MRVMajn2Gz3vK_gTlan:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/850d88d9ede41800b9d073c89b4b553f46feb870/test/background_threads_tests.cpp#L31)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> (memkind_malloc
> ```
this is a memory leak - please clean the memory when you finish the test case
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-01-26 13:50 UTC, michalbiesek reviewed
> Reviewed 1 of 7 files at r2, 2 of 11 files at r4.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/478)* status: 4 of 16 files reviewed, 7 unresolved discussions (waiting on @michalbiesek and @PatKamin)

___
*[include/memkind.h, line 423 at r4](https://reviewable.io/reviews/memkind/memkind/478#-MRVOyaMBqVacOns77UC:-MRVOyaMBqVacOns77UD:b-ulm2se) ([raw file](https://github.com/memkind/memkind/blob/e56400b22f239cf4d382bc362fdc5009cf9c2f2c/include/memkind.h#L423)):*
> ```
> Verifies if background threads from jemalloc API can be enabled/disabled
> ```
"Enables/disables background thread"
___
*[src/memkind.c, line 48 at r4](https://reviewable.io/reviews/memkind/memkind/478#-MRVPWS0AYXyWhoxo10T:-MRVPWS0AYXyWhoxo10U:b-rh7hv) ([raw file](https://github.com/memkind/memkind/blob/e56400b22f239cf4d382bc362fdc5009cf9c2f2c/src/memkind.c#L48)):*
> ```
> boolean
> ```
boolean ->enable
___
*[test/background_threads_tests.cpp, line 44 at r4](https://reviewable.io/reviews/memkind/memkind/478#-MRVPARg8Lhd0vcc1-Wk:-MRVPARg8Lhd0vcc1-Wl:b-e8oiu6) ([raw file](https://github.com/memkind/memkind/blob/e56400b22f239cf4d382bc362fdc5009cf9c2f2c/test/background_threads_tests.cpp#L44)):*
> ```cpp
>         memkind_free(MEMKIND_REGULAR, ptr);
>     }
> }
> ```

nit newline please
___
*[test/background_threads_tests.cpp, line 9 at r5](https://reviewable.io/reviews/memkind/memkind/478#-MRywiDTCxqAlw1nL0fK:-MRywiDTCxqAlw1nL0fL:bw9krwf) ([raw file](https://github.com/memkind/memkind/blob/f31bf21a621580163e4cf28c0f5c15ff8e014fc4/test/background_threads_tests.cpp#L9)):*
> ```
> #include <numa.h>
> ```
I am not sure if you actually need this basically cpus_count could be hardcoded or even one allocation would do the job
___
*[test/proc_stat.h, line 2 at r5](https://reviewable.io/reviews/memkind/memkind/478#-MRyxIoyBXSlCS0VEbR4:-MRyxIoyBXSlCS0VEbR5:b-c36tab) ([raw file](https://github.com/memkind/memkind/blob/f31bf21a621580163e4cf28c0f5c15ff8e014fc4/test/proc_stat.h#L2)):*
> ```
> 2020
> ```
bump
___
*[test/proc_stat.h, line 38 at r5](https://reviewable.io/reviews/memkind/memkind/478#-MRywyr6CFKx6UU0yjJ4:-MRywyr6CFKx6UU0yjJ5:b-q7drj3) ([raw file](https://github.com/memkind/memkind/blob/f31bf21a621580163e4cf28c0f5c15ff8e014fc4/test/proc_stat.h#L38)):*
<details><summary><i alt="summary">Quoted 5 lines of code…</i></summary>

> ```
>         {
>             char dirname[64];
>             snprintf(dirname, sizeof dirname, "/proc/self/task");
>             proc_dir = opendir(dirname);
>         }
> ```
</details>

why {} ?
___
*[test/proc_stat.h, line 44 at r5](https://reviewable.io/reviews/memkind/memkind/478#-MRyx1n45vOpPIJOESb-:-MRyx1n45vOpPIJOESb0:bcrmw8h) ([raw file](https://github.com/memkind/memkind/blob/f31bf21a621580163e4cf28c0f5c15ff8e014fc4/test/proc_stat.h#L44)):*
> ```
> if(direntry->d_name[0] != '.')
> ```
direntry->d_type == DT_DIR
Check please I don't remember exactly value to compare.


<!-- Sent from Reviewable.io -->

2021-01-26 15:31 UTC, PatKamin reviewed
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/478)* status: 4 of 16 files reviewed, 6 unresolved discussions (waiting on @michalbiesek)

___
*[include/memkind.h, line 423 at r4](https://reviewable.io/reviews/memkind/memkind/478#-MRVOyaMBqVacOns77UC:-MRz3v-H0WYe_0uCQHjP:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/e56400b22f239cf4d382bc362fdc5009cf9c2f2c/include/memkind.h#L423)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> Verifies if background threads from jemalloc API can be enabled/disabled
> ```
"Enables/disables background thread"
</blockquote></details>

Done.
___
*[src/memkind.c, line 48 at r4](https://reviewable.io/reviews/memkind/memkind/478#-MRVPWS0AYXyWhoxo10T:-MRz3wJeE9r1kF2XDc0e:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/e56400b22f239cf4d382bc362fdc5009cf9c2f2c/src/memkind.c#L48)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> boolean
> ```
boolean ->enable
</blockquote></details>

Done.
___
*[test/background_threads_tests.cpp, line 44 at r4](https://reviewable.io/reviews/memkind/memkind/478#-MRVPARg8Lhd0vcc1-Wk:-MRz41LPD4JTbhiojpO2:bb6un1j) ([raw file](https://github.com/memkind/memkind/blob/e56400b22f239cf4d382bc362fdc5009cf9c2f2c/test/background_threads_tests.cpp#L44)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

nit newline please
</blockquote></details>

Done
___
*[test/background_threads_tests.cpp, line 9 at r5](https://reviewable.io/reviews/memkind/memkind/478#-MRywiDTCxqAlw1nL0fK:-MRz7iJv-XSZ7ElyIzB7:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/f31bf21a621580163e4cf28c0f5c15ff8e014fc4/test/background_threads_tests.cpp#L9)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> #include <numa.h>
> ```
I am not sure if you actually need this basically cpus_count could be hardcoded or even one allocation would do the job
</blockquote></details>

Done.
___
*[test/proc_stat.h, line 2 at r5](https://reviewable.io/reviews/memkind/memkind/478#-MRyxIoyBXSlCS0VEbR4:-MRz48fs0UTiddcoI3kJ:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/f31bf21a621580163e4cf28c0f5c15ff8e014fc4/test/proc_stat.h#L2)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> 2020
> ```
bump
</blockquote></details>

Done.
___
*[test/proc_stat.h, line 38 at r5](https://reviewable.io/reviews/memkind/memkind/478#-MRywyr6CFKx6UU0yjJ4:-MRz4G39ED0DosePL-MW:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/f31bf21a621580163e4cf28c0f5c15ff8e014fc4/test/proc_stat.h#L38)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
>         {
>             char dirname[64];
>             snprintf(dirname, sizeof dirname, "/proc/self/task");
>             proc_dir = opendir(dirname);
>         }
> ```
why {} ?
</blockquote></details>

Done.
___
*[test/proc_stat.h, line 44 at r5](https://reviewable.io/reviews/memkind/memkind/478#-MRyx1n45vOpPIJOESb-:-MRz9KwI-H4HH36mmLV3:bn7r0jd) ([raw file](https://github.com/memkind/memkind/blob/f31bf21a621580163e4cf28c0f5c15ff8e014fc4/test/proc_stat.h#L44)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> if(direntry->d_name[0] != '.')
> ```
direntry->d_type == DT_DIR
Check please I don't remember exactly value to compare.
</blockquote></details>

DT_DIR counts both `.` and `..` as a dir object. I may use DT_DIR anyway, because aforementioned "directories" won't change during the test and doesn't have any impact on asserts made. Let me know what you think.


<!-- Sent from Reviewable.io -->

2021-01-27 12:12 UTC, michalbiesek reviewed
> Reviewed 1 of 11 files at r4, 1 of 10 files at r6, 8 of 16 files at r7.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/478)* status: 9 of 18 files reviewed, 11 unresolved discussions (waiting on @michalbiesek and @PatKamin)

___
*[memkind.spec.mk, line 2 at r7](https://reviewable.io/reviews/memkind/memkind/478#-MS2iAiZEe0iFTGgGuRM:-MS2iAiZEe0iFTGgGuRN:b-c36tab) ([raw file](https://github.com/memkind/memkind/blob/5d8e67b7915b5da33da73d73a68eccde5fa74888/memkind.spec.mk#L2)):*
> ```
> 2020
> ```
bump
___
*[include/memkind.h, line 425 at r7](https://reviewable.io/reviews/memkind/memkind/478#-MS2iU_S5SJwWmhuYDsK:-MS2iU_S5SJwWmhuYDsL:b-o4hsnj) ([raw file](https://github.com/memkind/memkind/blob/5d8e67b7915b5da33da73d73a68eccde5fa74888/include/memkind.h#L425)):*
> ```
> enable
> ```
state
___
*[man/memkind.3, line 105 at r7](https://reviewable.io/reviews/memkind/memkind/478#-MS2in4qCoMiBUAM0DbY:-MS2in4qCoMiBUAM0DbZ:b-k51xp5) ([raw file](https://github.com/memkind/memkind/blob/5d8e67b7915b5da33da73d73a68eccde5fa74888/man/memkind.3#L105)):*
> ```
> enable"
> ```
state
___
*[man/memkind.3, line 619 at r7](https://reviewable.io/reviews/memkind/memkind/478#-MS2jp5WB_VkdFD3Zf9d:-MS2jp5WB_VkdFD3Zf9e:b-dnwbkn) ([raw file](https://github.com/memkind/memkind/blob/5d8e67b7915b5da33da73d73a68eccde5fa74888/man/memkind.3#L619)):*
> ```
> enables and disables
> ```
enables/disables
___
*[man/memkind_arena.3, line 31 at r7](https://reviewable.io/reviews/memkind/memkind/478#-MS2iysq4_g7rjFcWV_4:-MS2iysq4_g7rjFcWV_5:b-o4hsnj) ([raw file](https://github.com/memkind/memkind/blob/5d8e67b7915b5da33da73d73a68eccde5fa74888/man/memkind_arena.3#L31)):*
> ```
> enable
> ```
state
___
*[man/memkind_arena.3, line 194 at r7](https://reviewable.io/reviews/memkind/memkind/478#-MS2kEVk16jNHIAB2JOT:-MS2kEVk16jNHIAB2JOU:bzs9kb) ([raw file](https://github.com/memkind/memkind/blob/5d8e67b7915b5da33da73d73a68eccde5fa74888/man/memkind_arena.3#L194)):*
> ```
> enables and disables
> ```
 enables/disables
___
*[src/memkind.c, line 48 at r7](https://reviewable.io/reviews/memkind/memkind/478#-MS2j5G5-f_kFCsMsS3h:-MS2j5G5-f_kFCsMsS3i:b-o4hsnj) ([raw file](https://github.com/memkind/memkind/blob/5d8e67b7915b5da33da73d73a68eccde5fa74888/src/memkind.c#L48)):*
> ```
> enable
> ```
state
___
*[src/memkind.c, line 48 at r7](https://reviewable.io/reviews/memkind/memkind/478#-MS2jABt5vvLKEeRm1bU:-MS2jABt5vvLKEeRm1bV:b-o4hsnj) ([raw file](https://github.com/memkind/memkind/blob/5d8e67b7915b5da33da73d73a68eccde5fa74888/src/memkind.c#L48)):*
> ```
> enable
> ```
state
___
*[src/memkind.c, line 58 at r7](https://reviewable.io/reviews/memkind/memkind/478#-MS2j7gk9ZqnyLn25k6r:-MS2j7gk9ZqnyLn25k6s:b-o4hsnj) ([raw file](https://github.com/memkind/memkind/blob/5d8e67b7915b5da33da73d73a68eccde5fa74888/src/memkind.c#L58)):*
> ```
> enable
> ```
state
___
*[src/memkind.c, line 58 at r7](https://reviewable.io/reviews/memkind/memkind/478#-MS2j9AZ5rnn5yw3z3WF:-MS2j9AZ5rnn5yw3z3WG:b-o4hsnj) ([raw file](https://github.com/memkind/memkind/blob/5d8e67b7915b5da33da73d73a68eccde5fa74888/src/memkind.c#L58)):*
> ```
> enable
> ```
state
___
*[test/background_threads_test.cpp, line 36 at r7](https://reviewable.io/reviews/memkind/memkind/478#-MS2jPhD1IbGkSBqXqNb:-MS2jPhD1IbGkSBqXqNc:b-fcc63x) ([raw file](https://github.com/memkind/memkind/blob/5d8e67b7915b5da33da73d73a68eccde5fa74888/test/background_threads_test.cpp#L36)):*
> ```
> state = 0;
> ```
remove this variable and call the state directly by value: true/false therefore you don't even the comments


<!-- Sent from Reviewable.io -->

2021-01-27 12:39 UTC, PatKamin reviewed
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/478)* status: 5 of 18 files reviewed, 11 unresolved discussions (waiting on @michalbiesek)

___
*[memkind.spec.mk, line 2 at r7](https://reviewable.io/reviews/memkind/memkind/478#-MS2iAiZEe0iFTGgGuRM:-MS2q_jSATDIWGxSm0WV:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/5d8e67b7915b5da33da73d73a68eccde5fa74888/memkind.spec.mk#L2)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> 2020
> ```
bump
</blockquote></details>

Done.
___
*[include/memkind.h, line 425 at r7](https://reviewable.io/reviews/memkind/memkind/478#-MS2iU_S5SJwWmhuYDsK:-MS2qbt606mtR_ZDyLl3:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/5d8e67b7915b5da33da73d73a68eccde5fa74888/include/memkind.h#L425)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> enable
> ```
state
</blockquote></details>

Done.
___
*[man/memkind.3, line 105 at r7](https://reviewable.io/reviews/memkind/memkind/478#-MS2in4qCoMiBUAM0DbY:-MS2qdeD-lZ_oi-FGJlX:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/5d8e67b7915b5da33da73d73a68eccde5fa74888/man/memkind.3#L105)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> enable"
> ```
state
</blockquote></details>

Done.
___
*[man/memkind.3, line 619 at r7](https://reviewable.io/reviews/memkind/memkind/478#-MS2jp5WB_VkdFD3Zf9d:-MS2qesYEQlLi8LjC57d:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/5d8e67b7915b5da33da73d73a68eccde5fa74888/man/memkind.3#L619)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> enables and disables
> ```
enables/disables
</blockquote></details>

Done.
___
*[man/memkind_arena.3, line 31 at r7](https://reviewable.io/reviews/memkind/memkind/478#-MS2iysq4_g7rjFcWV_4:-MS2qgfpDzPTv7jLdxkP:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/5d8e67b7915b5da33da73d73a68eccde5fa74888/man/memkind_arena.3#L31)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> enable
> ```
state
</blockquote></details>

Done.
___
*[man/memkind_arena.3, line 194 at r7](https://reviewable.io/reviews/memkind/memkind/478#-MS2kEVk16jNHIAB2JOT:-MS2qig42UOhnR_hq41U:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/5d8e67b7915b5da33da73d73a68eccde5fa74888/man/memkind_arena.3#L194)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> enables and disables
> ```
 enables/disables
</blockquote></details>

Done.
___
*[src/memkind.c, line 48 at r7](https://reviewable.io/reviews/memkind/memkind/478#-MS2j5G5-f_kFCsMsS3h:-MS2qjaIAfiTuemrXsRe:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/5d8e67b7915b5da33da73d73a68eccde5fa74888/src/memkind.c#L48)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> enable
> ```
state
</blockquote></details>

Done.
___
*[src/memkind.c, line 48 at r7](https://reviewable.io/reviews/memkind/memkind/478#-MS2jABt5vvLKEeRm1bU:-MS2qk846OetlvQ_-JwK:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/5d8e67b7915b5da33da73d73a68eccde5fa74888/src/memkind.c#L48)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> enable
> ```
state
</blockquote></details>

Done.
___
*[src/memkind.c, line 58 at r7](https://reviewable.io/reviews/memkind/memkind/478#-MS2j7gk9ZqnyLn25k6r:-MS2qlIwBctJ5gMKQ2dN:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/5d8e67b7915b5da33da73d73a68eccde5fa74888/src/memkind.c#L58)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> enable
> ```
state
</blockquote></details>

Done.
___
*[src/memkind.c, line 58 at r7](https://reviewable.io/reviews/memkind/memkind/478#-MS2j9AZ5rnn5yw3z3WF:-MS2qmUWAKIUR7C-mz5U:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/5d8e67b7915b5da33da73d73a68eccde5fa74888/src/memkind.c#L58)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> enable
> ```
state
</blockquote></details>

Done.
___
*[test/background_threads_test.cpp, line 36 at r7](https://reviewable.io/reviews/memkind/memkind/478#-MS2jPhD1IbGkSBqXqNb:-MS2qpto-4uGikuqxCmO:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/5d8e67b7915b5da33da73d73a68eccde5fa74888/test/background_threads_test.cpp#L36)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> state = 0;
> ```
remove this variable and call the state directly by value: true/false therefore you don't even the comments
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-01-27 12:49 UTC, michalbiesek requested changes
> Reviewed 4 of 16 files at r7, 5 of 7 files at r8.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/478)* status: 14 of 18 files reviewed, 7 unresolved discussions (waiting on @michalbiesek and @PatKamin)

___
*[include/memkind.h, line 425 at r8](https://reviewable.io/reviews/memkind/memkind/478#-MS2rrNXD1EplrmktrJE:-MS2rrNY-OsVonj0LtAl:bmfips9) ([raw file](https://github.com/memkind/memkind/blob/1c5576937b35c3e0561663135cdad92ec2e40290/include/memkind.h#L425)):*
> ```
> set this flag to true if you want to enable background threads, set it to false otherwise
> ```
expected state of background threads true if enabled, false if disabled
___
*[test/background_threads_test.cpp, line 31 at r8](https://reviewable.io/reviews/memkind/memkind/478#-MS2sSmE5LJRKSD3gFI3:-MS2sSmE5LJRKSD3gFI4:bc13cbm) ([raw file](https://github.com/memkind/memkind/blob/1c5576937b35c3e0561663135cdad92ec2e40290/test/background_threads_test.cpp#L31)):*
> ```
> bool state = true;
> ```
remove
___
*[test/background_threads_test.cpp, line 32 at r8](https://reviewable.io/reviews/memkind/memkind/478#-MS2sRjJDj2lvesdAnwt:-MS2sRjJDj2lvesdAnwu:bkwg4yu) ([raw file](https://github.com/memkind/memkind/blob/1c5576937b35c3e0561663135cdad92ec2e40290/test/background_threads_test.cpp#L32)):*
> ```
> state
> ```
true
___
*[test/background_threads_test.cpp, line 35 at r8](https://reviewable.io/reviews/memkind/memkind/478#-MS2sMspB3m1ETDwimDv:-MS2sMspB3m1ETDwimDw:buj0bas) ([raw file](https://github.com/memkind/memkind/blob/1c5576937b35c3e0561663135cdad92ec2e40290/test/background_threads_test.cpp#L35)):*
> ```
>     ASSERT_GT(new_threads_count,
>               old_threads_count); // check if there are more threads now
> ```
one line?
___
*[test/background_threads_test.cpp, line 36 at r8](https://reviewable.io/reviews/memkind/memkind/478#-MS2sTnl-hWDFSLJKgjf:-MS2sTnl-hWDFSLJKgjg:bq0w6hc) ([raw file](https://github.com/memkind/memkind/blob/1c5576937b35c3e0561663135cdad92ec2e40290/test/background_threads_test.cpp#L36)):*
> ```
>  state = 0;
> ```
remove
___
*[test/background_threads_test.cpp, line 37 at r8](https://reviewable.io/reviews/memkind/memkind/478#-MS2sV1Y8GiYIIFIZ9uc:-MS2sV1Y8GiYIIFIZ9ud:b8fvmvf) ([raw file](https://github.com/memkind/memkind/blob/1c5576937b35c3e0561663135cdad92ec2e40290/test/background_threads_test.cpp#L37)):*
> ```
> state
> ```
false


<!-- Sent from Reviewable.io -->

2021-01-27 13:03 UTC, PatKamin reviewed
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/478)* status: 14 of 18 files reviewed, 7 unresolved discussions (waiting on @michalbiesek)

___
*[include/memkind.h, line 425 at r8](https://reviewable.io/reviews/memkind/memkind/478#-MS2rrNXD1EplrmktrJE:-MS2v7IJ92uuMS6GPtcc:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/1c5576937b35c3e0561663135cdad92ec2e40290/include/memkind.h#L425)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> set this flag to true if you want to enable background threads, set it to false otherwise
> ```
expected state of background threads true if enabled, false if disabled
</blockquote></details>

Done.
___
*[test/background_threads_test.cpp, line 31 at r8](https://reviewable.io/reviews/memkind/memkind/478#-MS2sSmE5LJRKSD3gFI3:-MS2v8RcEN435Ywny6mi:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/1c5576937b35c3e0561663135cdad92ec2e40290/test/background_threads_test.cpp#L31)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> bool state = true;
> ```
remove
</blockquote></details>

Done.
___
*[test/background_threads_test.cpp, line 32 at r8](https://reviewable.io/reviews/memkind/memkind/478#-MS2sRjJDj2lvesdAnwt:-MS2v98f5QPNJDh2FK2G:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/1c5576937b35c3e0561663135cdad92ec2e40290/test/background_threads_test.cpp#L32)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> state
> ```
true
</blockquote></details>

Done.
___
*[test/background_threads_test.cpp, line 35 at r8](https://reviewable.io/reviews/memkind/memkind/478#-MS2sMspB3m1ETDwimDv:-MS2vAP66NebPNJywE6K:b-jmzxjg) ([raw file](https://github.com/memkind/memkind/blob/1c5576937b35c3e0561663135cdad92ec2e40290/test/background_threads_test.cpp#L35)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
>     ASSERT_GT(new_threads_count,
>               old_threads_count); // check if there are more threads now
> ```
one line?
</blockquote></details>

astyle forbids
___
*[test/background_threads_test.cpp, line 36 at r8](https://reviewable.io/reviews/memkind/memkind/478#-MS2sTnl-hWDFSLJKgjf:-MS2vCUbC73XT_0ICpaR:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/1c5576937b35c3e0561663135cdad92ec2e40290/test/background_threads_test.cpp#L36)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
>  state = 0;
> ```
remove
</blockquote></details>

Done.
___
*[test/background_threads_test.cpp, line 37 at r8](https://reviewable.io/reviews/memkind/memkind/478#-MS2sV1Y8GiYIIFIZ9uc:-MS2vCxi3cxCp5YAqvaB:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/1c5576937b35c3e0561663135cdad92ec2e40290/test/background_threads_test.cpp#L37)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> state
> ```
false
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-01-27 13:16 UTC, michalbiesek approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 16 files at r7, 1 of 7 files at r8, 1 of 3 files at r9.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/478#-:-MS2yl_R8k-HQuq2BBO_:bnfp4nl)* status: 16 of 18 files reviewed, 1 unresolved discussion (waiting on @michalbiesek and @PatKamin)

___
*[man/memkind_arena.3, line 30 at r9](https://reviewable.io/reviews/memkind/memkind/478#-MS2z-f87wCYwWzX38_l:-MS2z-f87wCYwWzX38_m:b-a5ornk) ([raw file](https://github.com/memkind/memkind/blob/e77343a59ee17bd4ce9638845878cdc6efd80c93/man/memkind_arena.3#L30)):*
> ```
> "threads_limit" " );
> ```
nit: "threads_limit" );


<!-- Sent from Reviewable.io -->

2021-01-27 13:21 UTC, bratpiorka reviewed
> Reviewed 3 of 12 files at r1, 2 of 7 files at r2, 1 of 2 files at r3, 1 of 11 files at r4, 11 of 11 files at r5, 1 of 3 files at r9, 1 of 1 files at r10.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/478)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @PatKamin)



<!-- Sent from Reviewable.io -->

2021-01-28 09:11 UTC, michalbiesek requested changes
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/478)* status: 17 of 18 files reviewed, 1 unresolved discussion (waiting on @bratpiorka and @PatKamin)

___
*[test/background_threads_test.cpp, line 37 at r11](https://reviewable.io/reviews/memkind/memkind/478#-MS7FV9A6wiMXlii-6qS:-MS7FV9A6wiMXlii-6qT:b-p4p3jg) ([raw file](https://github.com/memkind/memkind/blob/f60b0dfd6928bb18976c8707f4a56b5322c4c286/test/background_threads_test.cpp#L37)):*
> ```
> usleep(2 * 1000 * 1000)
> ```
sleep(2)


<!-- Sent from Reviewable.io -->

2021-01-28 09:15 UTC, PatKamin reviewed
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/478)* status: 17 of 18 files reviewed, 1 unresolved discussion (waiting on @bratpiorka and @michalbiesek)

___
*[test/background_threads_test.cpp, line 37 at r11](https://reviewable.io/reviews/memkind/memkind/478#-MS7FV9A6wiMXlii-6qS:-MS7GitR9BbUCndm4GjW:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/f60b0dfd6928bb18976c8707f4a56b5322c4c286/test/background_threads_test.cpp#L37)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> usleep(2 * 1000 * 1000)
> ```
sleep(2)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-01-28 10:00 UTC, bratpiorka reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r11, 2 of 2 files at r12.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/478#-:-MS7Qr4x9WGORO6CTIZO:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @michalbiesek)



<!-- Sent from Reviewable.io -->

2021-01-29 08:07 UTC, merged