Add tests for env var MEMKIND_HBW_THRESHOLD
memkind/memkind pull request #490
Opened 2021-01-25 14:51 UTC by bratpiorka

### Description

### Types of changes

- [ ] Bugfix (non-breaking change which fixes issue linked in Description above)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation (correction or otherwise)
- [ ] Cosmetics (whitespace, appearance)
- [x] Other: tests

### Checklist

- [ ] Code compiles without errors
- [ ] All tests pass locally with my changes (see TESTING section in CONTRIBUTING file)
- [ ] Created tests which will fail without the change (if possible)
- [ ] Extended the README/documentation (if necessary)
- [ ] All newly added files have proprietary license (if necessary)
- [ ] All newly added files are referenced in MANIFEST files (if necessary)

## Further comments

2021-01-27 12:42 UTC, michalbiesek reviewed
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/490)* status: 0 of 11 files reviewed, 2 unresolved discussions (waiting on @bratpiorka)

___
*[Makefile.am, line 543 at r1](https://reviewable.io/reviews/memkind/memkind/490#-MS2qyVo1V-9nZhStf2-:-MS2qyVo1V-9nZhStf20:b9evvp1) ([raw file](https://github.com/memkind/memkind/blob/8fa5ca295d0c864371fc09b1aa976512d57f0418/Makefile.am#L543)):*
> ```
> test/test_hbw_threshold.sh
> ```
I am not sure if we actually want this shell script I know where you take it from but in this case (HMAT tests), calling here python and pytest on your python file should be sufficient.
___
*[utils/qemu/ubuntu-packer.json, line 65 at r1](https://reviewable.io/reviews/memkind/memkind/490#-MS2rE1Q5rh3rNeskChB:-MS2rE1R-OLaR6Czq8dN:b-a329v) ([raw file](https://github.com/memkind/memkind/blob/8fa5ca295d0c864371fc09b1aa976512d57f0418/utils/qemu/ubuntu-packer.json#L65)):*
> ```
>  "sudo pip install --upgrade pip && sudo pip install wheel && sudo pip install pytest==3.9.2",
> ```
could you please extract this change to separate PR (I would merge this sooner) it actually be useful for one of my tests.


<!-- Sent from Reviewable.io -->

2021-01-27 12:56 UTC, bratpiorka reviewed
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/490)* status: 0 of 11 files reviewed, 2 unresolved discussions (waiting on @bratpiorka and @michalbiesek)

___
*[utils/qemu/ubuntu-packer.json, line 65 at r1](https://reviewable.io/reviews/memkind/memkind/490#-MS2rE1Q5rh3rNeskChB:-MS2u_zi0BX_4P4Wg9z_:b-qc9whm) ([raw file](https://github.com/memkind/memkind/blob/8fa5ca295d0c864371fc09b1aa976512d57f0418/utils/qemu/ubuntu-packer.json#L65)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
>  "sudo pip install --upgrade pip && sudo pip install wheel && sudo pip install pytest==3.9.2",
> ```
could you please extract this change to separate PR (I would merge this sooner) it actually be useful for one of my tests.
</blockquote></details>

done, see PR #498


<!-- Sent from Reviewable.io -->

2021-01-28 12:04 UTC, PatKamin reviewed
> Reviewed 2 of 11 files at r1, 4 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/490)* status: 5 of 10 files reviewed, 8 unresolved discussions (waiting on @bratpiorka and @michalbiesek)

___
*[test/environ_err_hbw_threshold_test.cpp, line 52 at r2](https://reviewable.io/reviews/memkind/memkind/490#-MS7mW1C3HD0ZRBfaH_N:-MS7mW1C3HD0ZRBfaH_O:b-2vb6ks) ([raw file](https://github.com/memkind/memkind/blob/59a95c9da9514ba8997e92649709d30050108ada/test/environ_err_hbw_threshold_test.cpp#L52)):*
> ```cpp
>         int status = numa_available();
>         if (status != 0) {
>             return -1;
> ```

Add cout stating what happened.
___
*[test/environ_err_hbw_threshold_test.cpp, line 78 at r2](https://reviewable.io/reviews/memkind/memkind/490#-MS7rcPmBTmSS0etoOrE:-MS7rcPmBTmSS0etoOrF:b-xk50w0) ([raw file](https://github.com/memkind/memkind/blob/59a95c9da9514ba8997e92649709d30050108ada/test/environ_err_hbw_threshold_test.cpp#L78)):*
> ```cpp
>                     std::cout << "Kind supported but allocation failed" << std::endl;
>                     any_fail = true;
>                     continue;
> ```

break; ?
___
*[test/environ_err_hbw_threshold_test.cpp, line 87 at r2](https://reviewable.io/reviews/memkind/memkind/490#-MS7rwLi92_lj4riptVF:-MS7rwLi92_lj4riptVG:bimsbrm) ([raw file](https://github.com/memkind/memkind/blob/59a95c9da9514ba8997e92649709d30050108ada/test/environ_err_hbw_threshold_test.cpp#L87)):*
> ```cpp
> 
>                 if (res != true) {
>                     std::cout << "Verify kind failed failed" << std::endl;
> ```

nit: double failed
___
*[test/environ_err_hbw_threshold_test.cpp, line 88 at r2](https://reviewable.io/reviews/memkind/memkind/490#-MS7s0cuDC4jaFja7bbW:-MS7s0cuDC4jaFja7bbX:b-7smvhi) ([raw file](https://github.com/memkind/memkind/blob/59a95c9da9514ba8997e92649709d30050108ada/test/environ_err_hbw_threshold_test.cpp#L88)):*
> ```cpp
>                 if (res != true) {
>                     std::cout << "Verify kind failed failed" << std::endl;
>                     any_fail = true;
> ```

break
___
*[test/environ_err_hbw_threshold_test.cpp, line 94 at r2](https://reviewable.io/reviews/memkind/memkind/490#-MS7sHMh76h5W90pPV5y:-MS7sHMh76h5W90pPV5z:b-rruge1) ([raw file](https://github.com/memkind/memkind/blob/59a95c9da9514ba8997e92649709d30050108ada/test/environ_err_hbw_threshold_test.cpp#L94)):*
> ```cpp
>             } else {
>                 if (ptr != nullptr) {
>                     std::cout << "Kind not supported but allocation succed" << std::endl;
> ```

nit: succeeded
___
*[test/environ_err_hbw_threshold_test.cpp, line 95 at r2](https://reviewable.io/reviews/memkind/memkind/490#-MS7sLbu1vOh8dq4zEe4:-MS7sLbu1vOh8dq4zEe5:b-skcy3j) ([raw file](https://github.com/memkind/memkind/blob/59a95c9da9514ba8997e92649709d30050108ada/test/environ_err_hbw_threshold_test.cpp#L95)):*
> ```cpp
>                 if (ptr != nullptr) {
>                     std::cout << "Kind not supported but allocation succed" << std::endl;
>                     any_fail = true;
> ```

break;


<!-- Sent from Reviewable.io -->

2021-01-28 12:11 UTC, PatKamin reviewed
> Reviewed 2 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/490)* status: 6 of 10 files reviewed, 13 unresolved discussions (waiting on @bratpiorka and @michalbiesek)

___
*[test/hbw_env_var_test.py, line 10 at r2](https://reviewable.io/reviews/memkind/memkind/490#-MS7ssas77-_ppJjOs5X:-MS7ssat3tq8n1hlc-VZ:bpp6stj) ([raw file](https://github.com/memkind/memkind/blob/59a95c9da9514ba8997e92649709d30050108ada/test/hbw_env_var_test.py#L10)):*
> ```Python
> 
> class Test_hbw_env_var(object):
>     os.environ["PATH"] += os.pathsep + os.path.dirname(os.path.dirname(__file__))
> ```

not needed
___
*[test/hbw_env_var_test.py, line 11 at r2](https://reviewable.io/reviews/memkind/memkind/490#-MS7svdx98-I8X4LrRgS:-MS7svdx98-I8X4LrRgT:b2hcpui) ([raw file](https://github.com/memkind/memkind/blob/59a95c9da9514ba8997e92649709d30050108ada/test/hbw_env_var_test.py#L11)):*
> ```Python
> class Test_hbw_env_var(object):
>     os.environ["PATH"] += os.pathsep + os.path.dirname(os.path.dirname(__file__))
>     fail_msg = "Test failed with:\n Error: Execution of: \'{0}\' returns: {1} \noutput: {2}"
> ```

Use f-string, please.
___
*[test/hbw_env_var_test.py, line 16 at r2](https://reviewable.io/reviews/memkind/memkind/490#-MS7t9RV4tLX7S-bgeWQ:-MS7t9RV4tLX7S-bgeWR:b-9q54b5) ([raw file](https://github.com/memkind/memkind/blob/59a95c9da9514ba8997e92649709d30050108ada/test/hbw_env_var_test.py#L16)):*
> ```Python
>     retcode_success = 0
>     retcode_not_available = 1
>     retcode_error = 2
> ```

not used
___
*[test/hbw_env_var_test.py, line 19 at r2](https://reviewable.io/reviews/memkind/memkind/490#-MS7tJZW7z0Vh48Hzzy3:-MS7tJZW7z0Vh48Hzzy4:b2hcpui) ([raw file](https://github.com/memkind/memkind/blob/59a95c9da9514ba8997e92649709d30050108ada/test/hbw_env_var_test.py#L19)):*
> ```Python
> 
>     def run_test(self, threshold, kind, expected_retcode):
>         env = "MEMKIND_HBW_THRESHOLD=" + str(threshold)
> ```

Use f-string, please.
___
*[test/hbw_env_var_test.py, line 22 at r2](https://reviewable.io/reviews/memkind/memkind/490#-MS7tdks1AkmMP187zl6:-MS7tdks1AkmMP187zl7:bg3dw1e) ([raw file](https://github.com/memkind/memkind/blob/59a95c9da9514ba8997e92649709d30050108ada/test/hbw_env_var_test.py#L22)):*
> ```Python
>         bin_path = self.cmd_helper.get_command_path(self.environ_err_threshold_test)
>         command = " ".join([env, bin_path, kind])
>         output, retcode = self.cmd_helper.execute_cmd(command, sudo=False)
> ```

sudo=False is a default for this method, no need to pass it here.


<!-- Sent from Reviewable.io -->

2021-01-28 12:24 UTC, PatKamin commented on test/hbw_env_var_test.py
> +from distutils.spawn import find_executable
Not used.

2021-02-02 07:24 UTC, michalbiesek requested changes
> Reviewed 1 of 7 files at r2, 2 of 14 files at r4, 7 of 10 files at r5.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/490)* status: 7 of 12 files reviewed, 16 unresolved discussions (waiting on @bratpiorka and @PatKamin)

___
*[test/environ_err_hbw_threshold_test.cpp, line 43 at r5](https://reviewable.io/reviews/memkind/memkind/490#-MSWbfsmBdYtzIrND0Ea:-MSWbfsmBdYtzIrND0Eb:bxbg9t2) ([raw file](https://github.com/memkind/memkind/blob/cbf51d437269830fbfe21b00beb0eb7a40dc8223/test/environ_err_hbw_threshold_test.cpp#L43)):*
> ```
>  static const int negative_value = -1;
> ```
this is not related strictly with tests but could you try to provide in separate commit (could be done in this PR but as a separate commit) - handling the negative value as invalid value and end the handling it here:
https://github.com/memkind/memkind/blob/46e6b883665a9eda651f4ee775c214282dbe6651/src/memkind_mem_attributes.c#L232-L235
___
*[test/environ_err_hbw_threshold_test.cpp, line 101 at r5](https://reviewable.io/reviews/memkind/memkind/490#-MSU8x4tDdpnVgwn2utW:-MSU8x4tDdpnVgwn2utX:b-7l0ses) ([raw file](https://github.com/memkind/memkind/blob/cbf51d437269830fbfe21b00beb0eb7a40dc8223/test/environ_err_hbw_threshold_test.cpp#L101)):*
> ```
>         switch (m_threshold_val) {
>             case TestPrereq_threshold::low_value: {
> ```
nit: just if-else when it is just "one case" - please apply everywhere, in this commit 
___
*[test/environ_err_hbw_threshold_test.cpp, line 845 at r5](https://reviewable.io/reviews/memkind/memkind/490#-MSUBgamCow-90FWWvsN:-MSUBgamCow-90FWWvsO:b-oakuu9) ([raw file](https://github.com/memkind/memkind/blob/cbf51d437269830fbfe21b00beb0eb7a40dc8223/test/environ_err_hbw_threshold_test.cpp#L845)):*
> ```
>     if (!tp.is_libhwloc_supported()) {
>         return 0;
>     }
> ```
after merge #506 this wouldn't probably be needed.
___
*[test/environ_err_hbw_threshold_test.cpp, line 882 at r5](https://reviewable.io/reviews/memkind/memkind/490#-MSUBr_10eD0AkRjTdrp:-MSUBr_10eD0AkRjTdrq:bpijx9h) ([raw file](https://github.com/memkind/memkind/blob/cbf51d437269830fbfe21b00beb0eb7a40dc8223/test/environ_err_hbw_threshold_test.cpp#L882)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
>     if (status)
>         return 0;
>     else
>         return -1;
> ```
</details>

return (status) ? 0 : -1;


<!-- Sent from Reviewable.io -->

2021-02-02 08:30 UTC, bratpiorka reviewed
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/490)* status: 7 of 12 files reviewed, 13 unresolved discussions (waiting on @michalbiesek and @PatKamin)

___
*[Makefile.am, line 543 at r1](https://reviewable.io/reviews/memkind/memkind/490#-MS2qyVo1V-9nZhStf2-:-MS3oNwl8qENYO7v6jUA:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/8fa5ca295d0c864371fc09b1aa976512d57f0418/Makefile.am#L543)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> test/test_hbw_threshold.sh
> ```
I am not sure if we actually want this shell script I know where you take it from but in this case (HMAT tests), calling here python and pytest on your python file should be sufficient.
</blockquote></details>

Done.
___
*[test/environ_err_hbw_threshold_test.cpp, line 52 at r2](https://reviewable.io/reviews/memkind/memkind/490#-MS7mW1C3HD0ZRBfaH_N:-MSDa4lO4u41N1m5tl3j:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/59a95c9da9514ba8997e92649709d30050108ada/test/environ_err_hbw_threshold_test.cpp#L52)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Add cout stating what happened.
</blockquote></details>

Done.
___
*[test/environ_err_hbw_threshold_test.cpp, line 78 at r2](https://reviewable.io/reviews/memkind/memkind/490#-MS7rcPmBTmSS0etoOrE:-MS8D6U6DDv1lMg_3grb:bqkk6fy) ([raw file](https://github.com/memkind/memkind/blob/59a95c9da9514ba8997e92649709d30050108ada/test/environ_err_hbw_threshold_test.cpp#L78)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

break; ?
</blockquote></details>

I can't use "break" in OpenMP for loop. My any_fail/alloc flags handle all possible paths.
___
*[test/environ_err_hbw_threshold_test.cpp, line 88 at r2](https://reviewable.io/reviews/memkind/memkind/490#-MS7s0cuDC4jaFja7bbW:-MSDa8lT9iGyjvc519Db:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/59a95c9da9514ba8997e92649709d30050108ada/test/environ_err_hbw_threshold_test.cpp#L88)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

break
</blockquote></details>

Done.
___
*[test/environ_err_hbw_threshold_test.cpp, line 95 at r2](https://reviewable.io/reviews/memkind/memkind/490#-MS7sLbu1vOh8dq4zEe4:-MSDbVqCEMTs4cu5kHP-:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/59a95c9da9514ba8997e92649709d30050108ada/test/environ_err_hbw_threshold_test.cpp#L95)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

break;
</blockquote></details>

Done.
___
*[test/environ_err_hbw_threshold_test.cpp, line 43 at r5](https://reviewable.io/reviews/memkind/memkind/490#-MSWbfsmBdYtzIrND0Ea:-MSWqMrGB_g4nDcdlDmC:bveago2) ([raw file](https://github.com/memkind/memkind/blob/cbf51d437269830fbfe21b00beb0eb7a40dc8223/test/environ_err_hbw_threshold_test.cpp#L43)):*
> andling the negative value 
I will do it in separate PR
___
*[test/environ_err_hbw_threshold_test.cpp, line 845 at r5](https://reviewable.io/reviews/memkind/memkind/490#-MSUBgamCow-90FWWvsN:-MSWnt3T4zLxWhucFjIN:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/cbf51d437269830fbfe21b00beb0eb7a40dc8223/test/environ_err_hbw_threshold_test.cpp#L845)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
>     if (!tp.is_libhwloc_supported()) {
>         return 0;
>     }
> ```
after merge #506 this wouldn't probably be needed.
</blockquote></details>

Done.
___
*[test/environ_err_hbw_threshold_test.cpp, line 882 at r5](https://reviewable.io/reviews/memkind/memkind/490#-MSUBr_10eD0AkRjTdrp:-MSWkvxQD6bNu89USuBX:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/cbf51d437269830fbfe21b00beb0eb7a40dc8223/test/environ_err_hbw_threshold_test.cpp#L882)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
>     if (status)
>         return 0;
>     else
>         return -1;
> ```
return (status) ? 0 : -1;
</blockquote></details>

Done.
___
*[test/hbw_env_var_test.py, line 4 at r2](https://reviewable.io/reviews/memkind/memkind/490#-MRu0oByOZ5lGs31_7RR-r2-4:-MSDbWJN98EKl_Llq_X1:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/59a95c9da9514ba8997e92649709d30050108ada/test/hbw_env_var_test.py#L4)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Not used.
</blockquote></details>

Done.
___
*[test/hbw_env_var_test.py, line 10 at r2](https://reviewable.io/reviews/memkind/memkind/490#-MS7ssas77-_ppJjOs5X:-MSDbmsp5vjmlRvwhdCl:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/59a95c9da9514ba8997e92649709d30050108ada/test/hbw_env_var_test.py#L10)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

not needed
</blockquote></details>

Done.
___
*[test/hbw_env_var_test.py, line 11 at r2](https://reviewable.io/reviews/memkind/memkind/490#-MS7svdx98-I8X4LrRgS:-MSDbmO8CzGEbEAyuR8E:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/59a95c9da9514ba8997e92649709d30050108ada/test/hbw_env_var_test.py#L11)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Use f-string, please.
</blockquote></details>

Done.
___
*[test/hbw_env_var_test.py, line 16 at r2](https://reviewable.io/reviews/memkind/memkind/490#-MS7t9RV4tLX7S-bgeWQ:-MSDbm7qDWSFzWpELcoB:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/59a95c9da9514ba8997e92649709d30050108ada/test/hbw_env_var_test.py#L16)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

not used
</blockquote></details>

Done.
___
*[test/hbw_env_var_test.py, line 19 at r2](https://reviewable.io/reviews/memkind/memkind/490#-MS7tJZW7z0Vh48Hzzy3:-MSDbbSWCOshy1PGbkya:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/59a95c9da9514ba8997e92649709d30050108ada/test/hbw_env_var_test.py#L19)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Use f-string, please.
</blockquote></details>

Done.
___
*[test/hbw_env_var_test.py, line 22 at r2](https://reviewable.io/reviews/memkind/memkind/490#-MS7tdks1AkmMP187zl6:-MSDbaxaBvB1CmIuMUvZ:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/59a95c9da9514ba8997e92649709d30050108ada/test/hbw_env_var_test.py#L22)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

sudo=False is a default for this method, no need to pass it here.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-02-02 09:06 UTC, PatKamin reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 14 files at r4, 9 of 10 files at r5, 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/490#-:-MSWzawA-t_71ODAq2Au:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @michalbiesek)



<!-- Sent from Reviewable.io -->

2021-02-02 09:17 UTC, michalbiesek requested changes
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/490)* status: all files reviewed, 10 unresolved discussions (waiting on @bratpiorka)

___
*[test/environ_err_hbw_threshold_test.cpp, line 43 at r5](https://reviewable.io/reviews/memkind/memkind/490#-MSWbfsmBdYtzIrND0Ea:-MSX-WMn2zTn61L3myBE:bb6mt9b) ([raw file](https://github.com/memkind/memkind/blob/cbf51d437269830fbfe21b00beb0eb7a40dc8223/test/environ_err_hbw_threshold_test.cpp#L43)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

> andling the negative value 
I will do it in separate PR
</blockquote></details>

:+1:
___
*[test/environ_err_hbw_threshold_test.cpp, line 268 at r6](https://reviewable.io/reviews/memkind/memkind/490#-MSX0P-m8DkMyPe1aWR6:-MSX0P-n7S7Rmrpf3PFV:bfbqx6e) ([raw file](https://github.com/memkind/memkind/blob/cf928bacb395438f3ca0f88ab76827b7e46d9b07/test/environ_err_hbw_threshold_test.cpp#L268)):*
> ```
>             case TestPrereq_threshold::negative_value:
>             case TestPrereq_threshold::high_value:
>                 return MapNodeSet {};
> ```
make it as default and move it in the end. call explicitly CLX_2_var3_HBW::HBW_nodes() just for TestPrereq_threshold::default_value
___
*[test/environ_err_hbw_threshold_test.cpp, line 286 at r6](https://reviewable.io/reviews/memkind/memkind/490#-MSX-xVV1pJfbfQoa8Z8:-MSX-xVV1pJfbfQoa8Z9:b-5xb7nc) ([raw file](https://github.com/memkind/memkind/blob/cf928bacb395438f3ca0f88ab76827b7e46d9b07/test/environ_err_hbw_threshold_test.cpp#L286)):*
> ```
>             case TestPrereq_threshold::negative_value:
>             case TestPrereq_threshold::high_value:
>                 return MapNodeSet {};
> ```
make it as default and move it in the end.  call explicitly CLX_2_var3_HBW::HBW_all_nodes()just for TestPrereq_threshold::default_value
 I merge #506 so please also rebase
___
*[test/environ_err_hbw_threshold_test.cpp, line 314 at r6](https://reviewable.io/reviews/memkind/memkind/490#-MSX0cmQ0TPFhni5adsp:-MSX0cmQ0TPFhni5adsq:b-v1cgno) ([raw file](https://github.com/memkind/memkind/blob/cf928bacb395438f3ca0f88ab76827b7e46d9b07/test/environ_err_hbw_threshold_test.cpp#L314)):*
> ```
>             case TestPrereq_threshold::low_value:
>             case TestPrereq_threshold::default_value:
>             default:
> ```
just default
___
*[test/environ_err_hbw_threshold_test.cpp, line 327 at r6](https://reviewable.io/reviews/memkind/memkind/490#-MSX0eMLCjrhzkd52Xht:-MSX0eMLCjrhzkd52Xhu:b-v1cgno) ([raw file](https://github.com/memkind/memkind/blob/cf928bacb395438f3ca0f88ab76827b7e46d9b07/test/environ_err_hbw_threshold_test.cpp#L327)):*
> ```
>             case TestPrereq_threshold::low_value:
>             case TestPrereq_threshold::default_value:
>             default:
> ```
just default
___
*[test/environ_err_hbw_threshold_test.cpp, line 350 at r6](https://reviewable.io/reviews/memkind/memkind/490#-MSX0h5CEzCMutms9-mR:-MSX0h5CEzCMutms9-mS:b-7v4se1) ([raw file](https://github.com/memkind/memkind/blob/cf928bacb395438f3ca0f88ab76827b7e46d9b07/test/environ_err_hbw_threshold_test.cpp#L350)):*
> ```
>             case TestPrereq_threshold::negative_value:
>             case TestPrereq_threshold::high_value:
>                 return MapNodeSet {};
> ```
make it as default and move it in the end.  call explicitly CLX_4_var1_HMAT::HBW_nodes() just for TestPrereq_threshold::default_value
___
*[test/environ_err_hbw_threshold_test.cpp, line 370 at r6](https://reviewable.io/reviews/memkind/memkind/490#-MSX0p4YBR7LbFDD7UFW:-MSX0p4YBR7LbFDD7UFX:b-v3k0or) ([raw file](https://github.com/memkind/memkind/blob/cf928bacb395438f3ca0f88ab76827b7e46d9b07/test/environ_err_hbw_threshold_test.cpp#L370)):*
> ```
>             case TestPrereq_threshold::negative_value:
>             case TestPrereq_threshold::high_value:
>                 return MapNodeSet {};
> ```
.
___
*[test/environ_err_hbw_threshold_test.cpp, line 397 at r6](https://reviewable.io/reviews/memkind/memkind/490#-MSX0qX-450iLjuxkVgv:-MSX0qX03k07EZ_fop8f:b-v3k0or) ([raw file](https://github.com/memkind/memkind/blob/cf928bacb395438f3ca0f88ab76827b7e46d9b07/test/environ_err_hbw_threshold_test.cpp#L397)):*
> ```
>             case TestPrereq_threshold::negative_value:
>             case TestPrereq_threshold::high_value:
>                 return MapNodeSet {};
> ```
.
___
*[test/environ_err_hbw_threshold_test.cpp, line 417 at r6](https://reviewable.io/reviews/memkind/memkind/490#-MSX0rcz8CPHTEp69nC2:-MSX0rcz8CPHTEp69nC3:b-v3k0or) ([raw file](https://github.com/memkind/memkind/blob/cf928bacb395438f3ca0f88ab76827b7e46d9b07/test/environ_err_hbw_threshold_test.cpp#L417)):*
> ```
>             case TestPrereq_threshold::negative_value:
>             case TestPrereq_threshold::high_value:
>                 return MapNodeSet {};
> ```
.
___
*[test/environ_err_hbw_threshold_test.cpp, line 658 at r6](https://reviewable.io/reviews/memkind/memkind/490#-MSX0x9nDg1STSRNqaDO:-MSX0x9nDg1STSRNqaDP:bud5mas) ([raw file](https://github.com/memkind/memkind/blob/cf928bacb395438f3ca0f88ab76827b7e46d9b07/test/environ_err_hbw_threshold_test.cpp#L658)):*
> ```
>             case TestPrereq_threshold::negative_value:
>             case TestPrereq_threshold::high_value:
> ```
.


<!-- Sent from Reviewable.io -->

2021-02-02 09:45 UTC, bratpiorka reviewed
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/490)* status: 8 of 10 files reviewed, 10 unresolved discussions (waiting on @michalbiesek and @PatKamin)

___
*[test/environ_err_hbw_threshold_test.cpp, line 43 at r5](https://reviewable.io/reviews/memkind/memkind/490#-MSWbfsmBdYtzIrND0Ea:-MSX23nL-N_pYedbuMnI:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/cbf51d437269830fbfe21b00beb0eb7a40dc8223/test/environ_err_hbw_threshold_test.cpp#L43)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

:+1:
</blockquote></details>

Done.
___
*[test/environ_err_hbw_threshold_test.cpp, line 268 at r6](https://reviewable.io/reviews/memkind/memkind/490#-MSX0P-m8DkMyPe1aWR6:-MSX7GeF0G3Nk3I3h06T:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/cf928bacb395438f3ca0f88ab76827b7e46d9b07/test/environ_err_hbw_threshold_test.cpp#L268)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
>             case TestPrereq_threshold::negative_value:
>             case TestPrereq_threshold::high_value:
>                 return MapNodeSet {};
> ```
make it as default and move it in the end. call explicitly CLX_2_var3_HBW::HBW_nodes() just for TestPrereq_threshold::default_value
</blockquote></details>

Done.
___
*[test/environ_err_hbw_threshold_test.cpp, line 286 at r6](https://reviewable.io/reviews/memkind/memkind/490#-MSX-xVV1pJfbfQoa8Z8:-MSX7HF24698W3uYvdvw:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/cf928bacb395438f3ca0f88ab76827b7e46d9b07/test/environ_err_hbw_threshold_test.cpp#L286)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
>             case TestPrereq_threshold::negative_value:
>             case TestPrereq_threshold::high_value:
>                 return MapNodeSet {};
> ```
make it as default and move it in the end.  call explicitly CLX_2_var3_HBW::HBW_all_nodes()just for TestPrereq_threshold::default_value
 I merge #506 so please also rebase
</blockquote></details>

Done.
___
*[test/environ_err_hbw_threshold_test.cpp, line 314 at r6](https://reviewable.io/reviews/memkind/memkind/490#-MSX0cmQ0TPFhni5adsp:-MSX7K6WD5PZ7yz4NZQK:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/cf928bacb395438f3ca0f88ab76827b7e46d9b07/test/environ_err_hbw_threshold_test.cpp#L314)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
>             case TestPrereq_threshold::low_value:
>             case TestPrereq_threshold::default_value:
>             default:
> ```
just default
</blockquote></details>

Done.
___
*[test/environ_err_hbw_threshold_test.cpp, line 327 at r6](https://reviewable.io/reviews/memkind/memkind/490#-MSX0eMLCjrhzkd52Xht:-MSX7KXADKdYuerSfKnn:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/cf928bacb395438f3ca0f88ab76827b7e46d9b07/test/environ_err_hbw_threshold_test.cpp#L327)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
>             case TestPrereq_threshold::low_value:
>             case TestPrereq_threshold::default_value:
>             default:
> ```
just default
</blockquote></details>

Done.
___
*[test/environ_err_hbw_threshold_test.cpp, line 350 at r6](https://reviewable.io/reviews/memkind/memkind/490#-MSX0h5CEzCMutms9-mR:-MSX7M2rD4FI1qfZqBwY:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/cf928bacb395438f3ca0f88ab76827b7e46d9b07/test/environ_err_hbw_threshold_test.cpp#L350)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
>             case TestPrereq_threshold::negative_value:
>             case TestPrereq_threshold::high_value:
>                 return MapNodeSet {};
> ```
make it as default and move it in the end.  call explicitly CLX_4_var1_HMAT::HBW_nodes() just for TestPrereq_threshold::default_value
</blockquote></details>

Done.
___
*[test/environ_err_hbw_threshold_test.cpp, line 370 at r6](https://reviewable.io/reviews/memkind/memkind/490#-MSX0p4YBR7LbFDD7UFW:-MSX7MOz6KH_l4PXKDna:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/cf928bacb395438f3ca0f88ab76827b7e46d9b07/test/environ_err_hbw_threshold_test.cpp#L370)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
>             case TestPrereq_threshold::negative_value:
>             case TestPrereq_threshold::high_value:
>                 return MapNodeSet {};
> ```
.
</blockquote></details>

Done.
___
*[test/environ_err_hbw_threshold_test.cpp, line 397 at r6](https://reviewable.io/reviews/memkind/memkind/490#-MSX0qX-450iLjuxkVgv:-MSX7QHK2XNhIj11H9jS:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/cf928bacb395438f3ca0f88ab76827b7e46d9b07/test/environ_err_hbw_threshold_test.cpp#L397)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
>             case TestPrereq_threshold::negative_value:
>             case TestPrereq_threshold::high_value:
>                 return MapNodeSet {};
> ```
.
</blockquote></details>

Done.
___
*[test/environ_err_hbw_threshold_test.cpp, line 417 at r6](https://reviewable.io/reviews/memkind/memkind/490#-MSX0rcz8CPHTEp69nC2:-MSX7QoCEvf_miyyRv55:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/cf928bacb395438f3ca0f88ab76827b7e46d9b07/test/environ_err_hbw_threshold_test.cpp#L417)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
>             case TestPrereq_threshold::negative_value:
>             case TestPrereq_threshold::high_value:
>                 return MapNodeSet {};
> ```
.
</blockquote></details>

Done.
___
*[test/environ_err_hbw_threshold_test.cpp, line 658 at r6](https://reviewable.io/reviews/memkind/memkind/490#-MSX0x9nDg1STSRNqaDO:-MSX7RGgDxlI--8ePZC2:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/cf928bacb395438f3ca0f88ab76827b7e46d9b07/test/environ_err_hbw_threshold_test.cpp#L658)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
>             case TestPrereq_threshold::negative_value:
>             case TestPrereq_threshold::high_value:
> ```
.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-02-02 10:44 UTC, michalbiesek approved these changes
> Reviewed 1 of 4 files at r7.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/490)* status: 9 of 10 files reviewed, all discussions resolved (waiting on @PatKamin)



<!-- Sent from Reviewable.io -->

2021-02-02 11:46 UTC, PatKamin reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 4 of 4 files at r8.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/490#-:-MSXZC-3BHhbPJAKXqpM:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @bratpiorka)



<!-- Sent from Reviewable.io -->

2021-02-02 12:00 UTC, michalbiesek approved these changes
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/490)* status: 8 of 10 files reviewed, all discussions resolved (waiting on @PatKamin)



<!-- Sent from Reviewable.io -->

2021-02-02 12:02 UTC, PatKamin reviewed
> Reviewed 2 of 2 files at r9.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/490)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @bratpiorka)



<!-- Sent from Reviewable.io -->

2021-02-02 12:17 UTC, merged