Add malloc_stats_print() to API
memkind/memkind pull request #513
Opened 2021-02-03 10:48 UTC by PatKamin

Add to API function memkind_stats_print() which wraps over je_malloc_stats_print().

- [ ] Documentation

### Description

### Types of changes

- [ ] Bugfix (non-breaking change which fixes issue linked in Description above)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation (correction or otherwise)
- [ ] Cosmetics (whitespace, appearance)
- [ ] Other

### Checklist

- [x] Code compiles without errors
- [x] All tests pass locally with my changes (see TESTING section in CONTRIBUTING file)
- [x] Created tests which will fail without the change (if possible)
- [ ] Extended the README/documentation (if necessary)
- [x] All newly added files have proprietary license (if necessary)
- [x] All newly added files are referenced in MANIFEST files (if necessary)

## Further comments

2021-02-03 11:06 UTC, michalbiesek requested changes
> Reviewed 9 of 13 files at r1.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/513)* status: 9 of 13 files reviewed, 6 unresolved discussions (waiting on @PatKamin)

___
*[include/memkind.h, line 343 at r1](https://reviewable.io/reviews/memkind/memkind/513#-MSbY44D-5xByT6EkpGR:-MSbY44D-5xByT6EkpGS:b-hl6t04) ([raw file](https://github.com/memkind/memkind/blob/5c9e9c94e744e30f8f787a3a62f4eb66df9e0b59/include/memkind.h#L343)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
> /// \brief Print memkind stats
> /// \note STANDARD API
> /// \param write_cb callback function pointer
> /// \param cbopaque data passed to write_cb
> ```
</details>

Please extend this description 
___
*[include/memkind.h, line 348 at r1](https://reviewable.io/reviews/memkind/memkind/513#-MSbYz6QEnJ_h5rvfSXM:-MSbYz6QEnJ_h5rvfSXN:ba7eip4) ([raw file](https://github.com/memkind/memkind/blob/5c9e9c94e744e30f8f787a3a62f4eb66df9e0b59/include/memkind.h#L348)):*
> ```
> memkind_stats_print
> ```
please update memkind_arena.3 and memkind.3
___
*[include/memkind.h, line 348 at r1](https://reviewable.io/reviews/memkind/memkind/513#-MSbZBNS9LgIEE9culYG:-MSbZBNS9LgIEE9culYH:btqo4sn) ([raw file](https://github.com/memkind/memkind/blob/5c9e9c94e744e30f8f787a3a62f4eb66df9e0b59/include/memkind.h#L348)):*
> ```
> emkind_stats_print
> ```
this function could be also used in the example which already use the statistics API.
___
*[src/heap_manager.c, line 24 at r1](https://reviewable.io/reviews/memkind/memkind/513#-MSbYHD7-kbg2fZYQDEO:-MSbYHD7-kbg2fZYQDEP:b-7vaj54) ([raw file](https://github.com/memkind/memkind/blob/5c9e9c94e744e30f8f787a3a62f4eb66df9e0b59/src/heap_manager.c#L24)):*
> ```
> oid (*heap_manager_stats_print)(void (*write_cb) (void *, const char *), void *cbopaque);
> ```
nit: please move in the end so stats_print be the last method (applies everywhere in structure here)
___
*[src/memkind.c, line 61 at r1](https://reviewable.io/reviews/memkind/memkind/513#-MSbYQ_b9cKvhxG-Efpj:-MSbYQ_b9cKvhxG-Efpk:b-wjmxst) ([raw file](https://github.com/memkind/memkind/blob/5c9e9c94e744e30f8f787a3a62f4eb66df9e0b59/src/memkind.c#L61)):*
<details><summary><i alt="summary">Quoted 23 lines of code…</i></summary>

> ```
> #ifdef MEMKIND_ENABLE_HEAP_MANAGER
> #define m_detect_kind(ptr)             heap_manager_detect_kind(ptr)
> #define m_free(ptr)                    heap_manager_free(ptr)
> #define m_realloc(ptr, size)           heap_manager_realloc(ptr, size)
> #define m_usable_size(ptr)             heap_manager_malloc_usable_size(ptr)
> #define m_defrag_reallocate(ptr)       heap_manager_defrag_reallocate(ptr)
> #define m_get_global_stat(stat, value) heap_manager_get_stat(stat, value)
> #define m_update_cached_stats          heap_manager_update_cached_stats
> #define m_stats_print(write_cb, cbopaque)                  heap_manager_stats_print(write_cb, cbopaque)
> #define m_init                         heap_manager_init
> #define m_set_bg_threads(state)        heap_manager_set_bg_threads(state)
> #else
> #define m_detect_kind(ptr)             memkind_arena_detect_kind(ptr)
> #define m_free(ptr)                    memkind_arena_free_with_kind_detect(ptr)
> #define m_realloc(ptr, size)           memkind_arena_realloc_with_kind_detect(ptr, size)
> #define m_usable_size(ptr)             memkind_default_malloc_usable_size(NULL, ptr)
> #define m_defrag_reallocate(ptr)       memkind_arena_defrag_reallocate_with_kind_detect(ptr)
> #define m_get_global_stat(stat, value) memkind_arena_get_global_stat(stat, value)
> #define m_update_cached_stats          memkind_arena_update_cached_stats
> #define m_stats_print(write_cb, cbopaque)                  memkind_arena_stats_print(write_cb, cbopaque)
> #define m_init                         memkind_arena_init
> #define m_set_bg_threads(state)        memkind_arena_set_bg_threads(state)
> #endif
> ```
</details>

Please align the column so this part be more readable 
___
*[test/Makefile.mk, line 127 at r1](https://reviewable.io/reviews/memkind/memkind/513#-MSbZP764B9sbdWpPnYB:-MSbZP764B9sbdWpPnYC:bvw7w5s) ([raw file](https://github.com/memkind/memkind/blob/5c9e9c94e744e30f8f787a3a62f4eb66df9e0b59/test/Makefile.mk#L127)):*
> ```
> malloc_stats_print_test_helper.c
> ```
I think you miss git add. But please test all possible combinations of parameters in your new function.

/// \param write_cb callback function pointer
/// \param cbopaque data passed to write_cb


<!-- Sent from Reviewable.io -->

2021-02-03 11:08 UTC, michalbiesek requested changes
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/513)* status: 9 of 13 files reviewed, 7 unresolved discussions (waiting on @PatKamin)

___
*[src/memkind.c, line 924 at r1](https://reviewable.io/reviews/memkind/memkind/513#-MSbZrIZ5Uxf_NEme1Dd:-MSbZrIZ5Uxf_NEme1De:b-5csz4l) ([raw file](https://github.com/memkind/memkind/blob/5c9e9c94e744e30f8f787a3a62f4eb66df9e0b59/src/memkind.c#L924)):*
> ```
> return 
> ```
remove - see this is void


<!-- Sent from Reviewable.io -->

2021-02-04 08:55 UTC, PatKamin reviewed
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/513)* status: 0 of 17 files reviewed, 6 unresolved discussions (waiting on @michalbiesek and @PatKamin)

___
*[include/memkind.h, line 343 at r1](https://reviewable.io/reviews/memkind/memkind/513#-MSbY44D-5xByT6EkpGR:-MSbtWB16Yuakad1LYtp:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/5c9e9c94e744e30f8f787a3a62f4eb66df9e0b59/include/memkind.h#L343)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> /// \brief Print memkind stats
> /// \note STANDARD API
> /// \param write_cb callback function pointer
> /// \param cbopaque data passed to write_cb
> ```
Please extend this description 
</blockquote></details>

Done.
___
*[include/memkind.h, line 348 at r1](https://reviewable.io/reviews/memkind/memkind/513#-MSbYz6QEnJ_h5rvfSXM:-MSbwUpv9S_09FpXDzFp:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/5c9e9c94e744e30f8f787a3a62f4eb66df9e0b59/include/memkind.h#L348)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> memkind_stats_print
> ```
please update memkind_arena.3 and memkind.3
</blockquote></details>

Done.
___
*[include/memkind.h, line 348 at r1](https://reviewable.io/reviews/memkind/memkind/513#-MSbZBNS9LgIEE9culYG:-MSc5wjW0K0M2Gl12ciI:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/5c9e9c94e744e30f8f787a3a62f4eb66df9e0b59/include/memkind.h#L348)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> emkind_stats_print
> ```
this function could be also used in the example which already use the statistics API.
</blockquote></details>

Done.
___
*[src/memkind.c, line 61 at r1](https://reviewable.io/reviews/memkind/memkind/513#-MSbYQ_b9cKvhxG-Efpj:-MSc95rX7AUzKZQ4YwWn:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/5c9e9c94e744e30f8f787a3a62f4eb66df9e0b59/src/memkind.c#L61)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> #ifdef MEMKIND_ENABLE_HEAP_MANAGER
> #define m_detect_kind(ptr)             heap_manager_detect_kind(ptr)
> #define m_free(ptr)                    heap_manager_free(ptr)
> #define m_realloc(ptr, size)           heap_manager_realloc(ptr, size)
> #define m_usable_size(ptr)             heap_manager_malloc_usable_size(ptr)
> #define m_defrag_reallocate(ptr)       heap_manager_defrag_reallocate(ptr)
> #define m_get_global_stat(stat, value) heap_manager_get_stat(stat, value)
> #define m_update_cached_stats          heap_manager_update_cached_stats
> #define m_stats_print(write_cb, cbopaque)                  heap_manager_stats_print(write_cb, cbopaque)
> #define m_init                         heap_manager_init
> #define m_set_bg_threads(state)        heap_manager_set_bg_threads(state)
> #else
> #define m_detect_kind(ptr)             memkind_arena_detect_kind(ptr)
> #define m_free(ptr)                    memkind_arena_free_with_kind_detect(ptr)
> #define m_realloc(ptr, size)           memkind_arena_realloc_with_kind_detect(ptr, size)
> #define m_usable_size(ptr)             memkind_default_malloc_usable_size(NULL, ptr)
> #define m_defrag_reallocate(ptr)       memkind_arena_defrag_reallocate_with_kind_detect(ptr)
> #define m_get_global_stat(stat, value) memkind_arena_get_global_stat(stat, value)
> #define m_update_cached_stats          memkind_arena_update_cached_stats
> #define m_stats_print(write_cb, cbopaque)                  memkind_arena_stats_print(write_cb, cbopaque)
> #define m_init                         memkind_arena_init
> #define m_set_bg_threads(state)        memkind_arena_set_bg_threads(state)
> #endif
> ```
Please align the column so this part be more readable 
</blockquote></details>

Done.
___
*[src/memkind.c, line 924 at r1](https://reviewable.io/reviews/memkind/memkind/513#-MSbZrIZ5Uxf_NEme1Dd:-MSc9Ls-5QtlPMI62rY_:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/5c9e9c94e744e30f8f787a3a62f4eb66df9e0b59/src/memkind.c#L924)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> return 
> ```
remove - see this is void
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-02-04 09:43 UTC, michalbiesek requested changes
> Reviewed 4 of 17 files at r2.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/513)* status: 4 of 17 files reviewed, 3 unresolved discussions (waiting on @michalbiesek and @PatKamin)

___
*[examples/memkind_get_stat.c, line 2 at r2](https://reviewable.io/reviews/memkind/memkind/513#-MSgFgq97iHT83FKRI3W:-MSgFgq97iHT83FKRI3X:bf70fwn) ([raw file](https://github.com/memkind/memkind/blob/33ea827f263b6a181f01f27fe7b416e10cd0b6c8/examples/memkind_get_stat.c#L2)):*
> ```
> 2020
> ```
.
___
*[examples/memkind_get_stat.c, line 23 at r2](https://reviewable.io/reviews/memkind/memkind/513#-MSgFcYh7Y7DCx8b7SwW:-MSgFcYh7Y7DCx8b7SwX:bg6m6u0) ([raw file](https://github.com/memkind/memkind/blob/33ea827f263b6a181f01f27fe7b416e10cd0b6c8/examples/memkind_get_stat.c#L23)):*
> ```
> printf
> ```
can we stick with fprintf and stdout?
___
*[man/memkind.3, line 580 at r2](https://reviewable.io/reviews/memkind/memkind/513#-MSgFwMkDVC14kojFnE5:-MSgFwMkDVC14kojFnE6:b-w4rutc) ([raw file](https://github.com/memkind/memkind/blob/33ea827f263b6a181f01f27fe7b416e10cd0b6c8/man/memkind.3#L580)):*
> ```
> prints memkind malloc statistics.
> ```
any chance to provide a description of parameters?


<!-- Sent from Reviewable.io -->

2021-02-04 10:43 UTC, michalbiesek requested changes
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/513)* status: 4 of 17 files reviewed, 5 unresolved discussions (waiting on @michalbiesek and @PatKamin)

___
*[src/heap_manager.c, line 38 at r2](https://reviewable.io/reviews/memkind/memkind/513#-MSgcoBq7grLPEvSHR4x:-MSgcoBq7grLPEvSHR4y:bnas7s3) ([raw file](https://github.com/memkind/memkind/blob/33ea827f263b6a181f01f27fe7b416e10cd0b6c8/src/heap_manager.c#L38)):*
> ```
>  .heap_manager_stats_print = memkind_arena_stats_print,
> ```
move to the end of structure
___
*[src/heap_manager.c, line 51 at r2](https://reviewable.io/reviews/memkind/memkind/513#-MSgcd4U1rje6l1zH1UZ:-MSgcd4U1rje6l1zH1U_:b-r5v62q) ([raw file](https://github.com/memkind/memkind/blob/33ea827f263b6a181f01f27fe7b416e10cd0b6c8/src/heap_manager.c#L51)):*
> ```
> .heap_manager_stats_print = NULL,
> ```
please provide "empty implementation" and move to the end of structure


<!-- Sent from Reviewable.io -->

2021-02-04 14:46 UTC, PatKamin reviewed
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/513)* status: 3 of 19 files reviewed, 5 unresolved discussions (waiting on @michalbiesek)

___
*[examples/memkind_get_stat.c, line 2 at r2](https://reviewable.io/reviews/memkind/memkind/513#-MSgFgq97iHT83FKRI3W:-MShBpXY59SG-8JpHkOs:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/33ea827f263b6a181f01f27fe7b416e10cd0b6c8/examples/memkind_get_stat.c#L2)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> 2020
> ```
.
</blockquote></details>

Done.
___
*[examples/memkind_get_stat.c, line 23 at r2](https://reviewable.io/reviews/memkind/memkind/513#-MSgFcYh7Y7DCx8b7SwW:-MShBwu54NSyM_ZyqUpL:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/33ea827f263b6a181f01f27fe7b416e10cd0b6c8/examples/memkind_get_stat.c#L23)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> printf
> ```
can we stick with fprintf and stdout?
</blockquote></details>

Done.
___
*[man/memkind.3, line 580 at r2](https://reviewable.io/reviews/memkind/memkind/513#-MSgFwMkDVC14kojFnE5:-MShI8UJ95Sj5L8cXN9V:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/33ea827f263b6a181f01f27fe7b416e10cd0b6c8/man/memkind.3#L580)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> prints memkind malloc statistics.
> ```
any chance to provide a description of parameters?
</blockquote></details>

Done.
___
*[src/heap_manager.c, line 38 at r2](https://reviewable.io/reviews/memkind/memkind/513#-MSgcoBq7grLPEvSHR4x:-MShIKOV3B1HkeC64Ges:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/33ea827f263b6a181f01f27fe7b416e10cd0b6c8/src/heap_manager.c#L38)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
>  .heap_manager_stats_print = memkind_arena_stats_print,
> ```
move to the end of structure
</blockquote></details>

Done.
___
*[src/heap_manager.c, line 51 at r2](https://reviewable.io/reviews/memkind/memkind/513#-MSgcd4U1rje6l1zH1UZ:-MShKPBbEER84Ki4Ljpq:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/33ea827f263b6a181f01f27fe7b416e10cd0b6c8/src/heap_manager.c#L51)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> .heap_manager_stats_print = NULL,
> ```
please provide "empty implementation" and move to the end of structure
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-02-05 13:09 UTC, michalbiesek requested changes
> Reviewed 4 of 17 files at r2, 5 of 13 files at r3.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/513)* status: 10 of 19 files reviewed, 5 unresolved discussions (waiting on @michalbiesek and @PatKamin)

___
*[examples/memkind_get_stat.c, line 24 at r3](https://reviewable.io/reviews/memkind/memkind/513#-MSm48K1A_oikod0kjV3:-MSm48K1A_oikod0kjV4:bksvzgk) ([raw file](https://github.com/memkind/memkind/blob/96b6ee732588d7eed695fd79693cb7e243fd73d8/examples/memkind_get_stat.c#L24)):*
> ```
> \n\n
> ```
single newline?
___
*[examples/memkind_get_stat.c, line 24 at r3](https://reviewable.io/reviews/memkind/memkind/513#-MSm4BFqCOuXJ9Whkoxt:-MSm4BFqCOuXJ9Whkoxu:b-xpnhco) ([raw file](https://github.com/memkind/memkind/blob/96b6ee732588d7eed695fd79693cb7e243fd73d8/examples/memkind_get_stat.c#L24)):*
> ```
> \\summary
> ```
Summary - without \\
___
*[include/memkind.h, line 374 at r3](https://reviewable.io/reviews/memkind/memkind/513#-MSm4INK1E9rnMBEdBNX:-MSm4INK1E9rnMBEdBNY:b-k8z3o7) ([raw file](https://github.com/memkind/memkind/blob/96b6ee732588d7eed695fd79693cb7e243fd73d8/include/memkind.h#L374)):*
> ```
> const char *opts)
> ```
missing doxygen description
___
*[man/memkind.3, line 583 at r3](https://reviewable.io/reviews/memkind/memkind/513#-MSmFk5-6CISk3TjNojb:-MSmFk5-6CISk3TjNojc:bf1gkf2) ([raw file](https://github.com/memkind/memkind/blob/96b6ee732588d7eed695fd79693cb7e243fd73d8/man/memkind.3#L583)):*
<details><summary><i alt="summary">Quoted 7 lines of code…</i></summary>

> ```
> .I write_cb
> function to print the output. Use
> .BR syscall(2)
> rather than
> .BR write(2)
> when possible in order to avoid the possibility of memory allocation within libc. This is necessary on FreeBSD.
> Pass NULL in order to use the default write_cb function which prints the output to the stderr. Use
> ```
</details>

maybe more generic description this is basically functionality which provides for user possibility to have a custom writer - there is no need to deep dive into FreeBSD details.
___
*[man/memkind.3, line 594 at r3](https://reviewable.io/reviews/memkind/memkind/513#-MSmGGdi3pCacXxu8Kco:-MSmGGdi3pCacXxu8Kcp:b-ajwaek) ([raw file](https://github.com/memkind/memkind/blob/96b6ee732588d7eed695fd79693cb7e243fd73d8/man/memkind.3#L594)):*
> ```
> .I opts
> string, ie. pass "J" to get output in JSON format. For more information see jemalloc documentation.
> ```
not sure maybe opaque this as enum see that other options are supported as well, see that you could pass here for example “m”, “d”, and “a”.
something like:

void memkind_stats_print(void " "(*write_cb) (void *, const char *)" ", void " "*cbopaque" ", int opts );

memkind_stats_print(NULL, NULL, JSON_FORMAT | OMIT_MERGED_ARENAS);
So the user doesn't need to look into jemalloc API.


<!-- Sent from Reviewable.io -->

2021-02-12 06:54 UTC, michalbiesek requested changes
> Reviewed 1 of 17 files at r2, 10 of 12 files at r4.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/513)* status: 16 of 19 files reviewed, 12 unresolved discussions (waiting on @michalbiesek and @PatKamin)

___
*[include/memkind.h, line 148 at r4](https://reviewable.io/reviews/memkind/memkind/513#-MTH_v-sCdJxfNt4Cs6Y:-MTH_v-sCdJxfNt4Cs6Z:bb3p3s1) ([raw file](https://github.com/memkind/memkind/blob/3140f66d8cb086e9becbedb7eea45b6867224c6e/include/memkind.h#L148)):*
> ```
> NONE
> ```
Use common prefix for this - see the naming convention in another enum in this header file.
___
*[include/memkind.h, line 149 at r4](https://reviewable.io/reviews/memkind/memkind/513#-MTHbUfL7lUewZd1OYke:-MTHbUfL7lUewZd1OYkf:blmn87q) ([raw file](https://github.com/memkind/memkind/blob/3140f66d8cb086e9becbedb7eea45b6867224c6e/include/memkind.h#L149)):*
> ```
> 0
> ```
Use bit-shifting
0;
1 = (1U << 0) ;
..
(1U << 1)
(1U << 2)
___
*[include/memkind.h, line 150 at r4](https://reviewable.io/reviews/memkind/memkind/513#-MTK-ZR7A3rhtFUmI3_t:-MTK-ZR82GQGxsSTDgVg:b-v24t5j) ([raw file](https://github.com/memkind/memkind/blob/3140f66d8cb086e9becbedb7eea45b6867224c6e/include/memkind.h#L150)):*
> ```
> **< Omit general information that never changes during execution */
> ```
Please stick with the comment form like:
```
    /**
     * Interleave allocation across local memory.
     * For n memory types the allocation will be interleaved across all of
     * them.
     */
```
See https://github.com/memkind/memkind/pull/516#pullrequestreview-587330254 regarding enum unifying
___
*[include/memkind.h, line 383 at r4](https://reviewable.io/reviews/memkind/memkind/513#-MTHduZm5qhbb0F2CgRm:-MTHduZm5qhbb0F2CgRn:b-gutm6r) ([raw file](https://github.com/memkind/memkind/blob/3140f66d8cb086e9becbedb7eea45b6867224c6e/include/memkind.h#L383)):*
> ```
> statisitcs
> ```
statistics
___
*[include/memkind.h, line 384 at r4](https://reviewable.io/reviews/memkind/memkind/513#-MTHe0wS5JnVIqqkEVO7:-MTHe0wS5JnVIqqkEVO8:bua6dp1) ([raw file](https://github.com/memkind/memkind/blob/3140f66d8cb086e9becbedb7eea45b6867224c6e/include/memkind.h#L384)):*
> ```
> which prints to the STDERR_FILENO file descriptor
> ```
not needed - this could be easily founded in manual
___
*[src/memkind_arena.c, line 891 at r4](https://reviewable.io/reviews/memkind/memkind/513#-MTHbG0Q6hah-s4IY-4M:-MTHbG0Q6hah-s4IY-4N:b-u335v5) ([raw file](https://github.com/memkind/memkind/blob/3140f66d8cb086e9becbedb7eea45b6867224c6e/src/memkind_arena.c#L891)):*
> ```
>     if (opts == NONE) {
>         char_opts = NULL;
>     } else {
> ```
```
char_opts = NULL;
if (opts != NONE)
```
___
*[src/memkind_arena.c, line 894 at r4](https://reviewable.io/reviews/memkind/memkind/513#-MTHbzV65J3ptq9rpt6C:-MTHbzV65J3ptq9rpt6D:b9e06y7) ([raw file](https://github.com/memkind/memkind/blob/3140f66d8cb086e9becbedb7eea45b6867224c6e/src/memkind_arena.c#L894)):*
> ```
> CHECK_BIT(opts, 0)
> ```
why can't you use  JSON_FORMAT ? I mean value directly from memkind.h ? No need for this macro
___
*[src/memkind_arena.c, line 895 at r4](https://reviewable.io/reviews/memkind/memkind/513#-MTHcOBXBvDJHGuWL23C:-MTHcOBXBvDJHGuWL23D:b-qvhf4h) ([raw file](https://github.com/memkind/memkind/blob/3140f66d8cb086e9becbedb7eea45b6867224c6e/src/memkind_arena.c#L895)):*
> ```
> strcat
> ```
strncat please
___
*[src/memkind_arena.c, line 918 at r4](https://reviewable.io/reviews/memkind/memkind/513#-MTHemxD3KnntSKlotN1:-MTHemxD3KnntSKlotN2:bq3mo43) ([raw file](https://github.com/memkind/memkind/blob/3140f66d8cb086e9becbedb7eea45b6867224c6e/src/memkind_arena.c#L918)):*
> ```
>         if (CHECK_BIT(opts, 8)) {
>             strcat(temp, "e");
>         }
> ```
What will happen if I pass an option which is not supported e.g = 1024. I mean jemalloc handles it/or you provide an interface for error handling? For error handling see validate_memtype_bits for similar action, 
I would rather see this as changing return type from function exposed in memkind.h (void to int) and provide here error handling, please add test for it also
___
*[src/memkind_arena.c, line 922 at r4](https://reviewable.io/reviews/memkind/memkind/513#-MTHg3CC4mtfTxE_mLMV:-MTHg3CC4mtfTxE_mLMW:bhl0amf) ([raw file](https://github.com/memkind/memkind/blob/3140f66d8cb086e9becbedb7eea45b6867224c6e/src/memkind_arena.c#L922)):*
> ```
>     if (strcmp(temp, "\0")) {
>         char_opts = temp;
>     }
> ```
This could be inside if (opts != NONE) block
___
*[test/malloc_stats_print_test_helper.c, line 23 at r4](https://reviewable.io/reviews/memkind/memkind/513#-MTHczRD-jvaak3h6xX0:-MTHczRECYhaYkmXOqDo:bgpwdct) ([raw file](https://github.com/memkind/memkind/blob/3140f66d8cb086e9becbedb7eea45b6867224c6e/test/malloc_stats_print_test_helper.c#L23)):*
> ```
>         err = -1;
>         return err;
> ```
return -1;


<!-- Sent from Reviewable.io -->

2021-02-15 11:39 UTC, PatKamin reviewed
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/513)* status: 16 of 19 files reviewed, 12 unresolved discussions (waiting on @michalbiesek)

___
*[examples/memkind_get_stat.c, line 24 at r3](https://reviewable.io/reviews/memkind/memkind/513#-MSm48K1A_oikod0kjV3:-MT0iDscAa8y6ybDYO0k:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/96b6ee732588d7eed695fd79693cb7e243fd73d8/examples/memkind_get_stat.c#L24)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> \n\n
> ```
single newline?
</blockquote></details>

Done.
___
*[examples/memkind_get_stat.c, line 24 at r3](https://reviewable.io/reviews/memkind/memkind/513#-MSm4BFqCOuXJ9Whkoxt:-MT0iEDbC_r1haCt1dZz:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/96b6ee732588d7eed695fd79693cb7e243fd73d8/examples/memkind_get_stat.c#L24)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> \\summary
> ```
Summary - without \\
</blockquote></details>

Done.
___
*[include/memkind.h, line 374 at r3](https://reviewable.io/reviews/memkind/memkind/513#-MSm4INK1E9rnMBEdBNX:-MT0mc6-50-1S2eJ60KO:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/96b6ee732588d7eed695fd79693cb7e243fd73d8/include/memkind.h#L374)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> const char *opts)
> ```
missing doxygen description
</blockquote></details>

Done.
___
*[include/memkind.h, line 148 at r4](https://reviewable.io/reviews/memkind/memkind/513#-MTH_v-sCdJxfNt4Cs6Y:-MTZfxOMCnKdbkhmg0RW:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/3140f66d8cb086e9becbedb7eea45b6867224c6e/include/memkind.h#L148)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> NONE
> ```
Use common prefix for this - see the naming convention in another enum in this header file.
</blockquote></details>

Done.
___
*[include/memkind.h, line 149 at r4](https://reviewable.io/reviews/memkind/memkind/513#-MTHbUfL7lUewZd1OYke:-MTL9dDK5BPOzVpQntZo:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/3140f66d8cb086e9becbedb7eea45b6867224c6e/include/memkind.h#L149)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> 0
> ```
Use bit-shifting
0;
1 = (1U << 0) ;
..
(1U << 1)
(1U << 2)
</blockquote></details>

Done.
___
*[include/memkind.h, line 150 at r4](https://reviewable.io/reviews/memkind/memkind/513#-MTK-ZR7A3rhtFUmI3_t:-MTLBWsC7sTb0QutKUw3:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/3140f66d8cb086e9becbedb7eea45b6867224c6e/include/memkind.h#L150)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> **< Omit general information that never changes during execution */
> ```
Please stick with the comment form like:
```
    /**
     * Interleave allocation across local memory.
     * For n memory types the allocation will be interleaved across all of
     * them.
     */
```
See https://github.com/memkind/memkind/pull/516#pullrequestreview-587330254 regarding enum unifying
</blockquote></details>

Done.
___
*[include/memkind.h, line 383 at r4](https://reviewable.io/reviews/memkind/memkind/513#-MTHduZm5qhbb0F2CgRm:-MTLDwXKCTsiEDQK7bnG:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/3140f66d8cb086e9becbedb7eea45b6867224c6e/include/memkind.h#L383)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> statisitcs
> ```
statistics
</blockquote></details>

Done.
___
*[include/memkind.h, line 384 at r4](https://reviewable.io/reviews/memkind/memkind/513#-MTHe0wS5JnVIqqkEVO7:-MTLQpjB90sPTfny_r6n:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/3140f66d8cb086e9becbedb7eea45b6867224c6e/include/memkind.h#L384)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> which prints to the STDERR_FILENO file descriptor
> ```
not needed - this could be easily founded in manual
</blockquote></details>

Done.
___
*[man/memkind.3, line 583 at r3](https://reviewable.io/reviews/memkind/memkind/513#-MSmFk5-6CISk3TjNojb:-MT0nWSnEXqyz87krqX-:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/96b6ee732588d7eed695fd79693cb7e243fd73d8/man/memkind.3#L583)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> .I write_cb
> function to print the output. Use
> .BR syscall(2)
> rather than
> .BR write(2)
> when possible in order to avoid the possibility of memory allocation within libc. This is necessary on FreeBSD.
> Pass NULL in order to use the default write_cb function which prints the output to the stderr. Use
> ```
maybe more generic description this is basically functionality which provides for user possibility to have a custom writer - there is no need to deep dive into FreeBSD details.
</blockquote></details>

Done.
___
*[src/memkind_arena.c, line 891 at r4](https://reviewable.io/reviews/memkind/memkind/513#-MTHbG0Q6hah-s4IY-4M:-MTL_IS-3_BsbVxN4f0d:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/3140f66d8cb086e9becbedb7eea45b6867224c6e/src/memkind_arena.c#L891)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
>     if (opts == NONE) {
>         char_opts = NULL;
>     } else {
> ```
```
char_opts = NULL;
if (opts != NONE)
```
</blockquote></details>

Done.
___
*[src/memkind_arena.c, line 894 at r4](https://reviewable.io/reviews/memkind/memkind/513#-MTHbzV65J3ptq9rpt6C:-MTLfW5GBp7FWrkSkbyd:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/3140f66d8cb086e9becbedb7eea45b6867224c6e/src/memkind_arena.c#L894)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> CHECK_BIT(opts, 0)
> ```
why can't you use  JSON_FORMAT ? I mean value directly from memkind.h ? No need for this macro
</blockquote></details>

Done.
___
*[src/memkind_arena.c, line 895 at r4](https://reviewable.io/reviews/memkind/memkind/513#-MTHcOBXBvDJHGuWL23C:-MTLftgE1Nm5dWpuGTTQ:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/3140f66d8cb086e9becbedb7eea45b6867224c6e/src/memkind_arena.c#L895)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> strcat
> ```
strncat please
</blockquote></details>

Done.
___
*[src/memkind_arena.c, line 918 at r4](https://reviewable.io/reviews/memkind/memkind/513#-MTHemxD3KnntSKlotN1:-MTZiBMZ85vimLY0kany:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/3140f66d8cb086e9becbedb7eea45b6867224c6e/src/memkind_arena.c#L918)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
>         if (CHECK_BIT(opts, 8)) {
>             strcat(temp, "e");
>         }
> ```
What will happen if I pass an option which is not supported e.g = 1024. I mean jemalloc handles it/or you provide an interface for error handling? For error handling see validate_memtype_bits for similar action, 
I would rather see this as changing return type from function exposed in memkind.h (void to int) and provide here error handling, please add test for it also
</blockquote></details>

Done.
___
*[src/memkind_arena.c, line 922 at r4](https://reviewable.io/reviews/memkind/memkind/513#-MTHg3CC4mtfTxE_mLMV:-MTLjAiW-TiDhKyUNx1U:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/3140f66d8cb086e9becbedb7eea45b6867224c6e/src/memkind_arena.c#L922)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
>     if (strcmp(temp, "\0")) {
>         char_opts = temp;
>     }
> ```
This could be inside if (opts != NONE) block
</blockquote></details>

Done.
___
*[test/malloc_stats_print_test_helper.c, line 23 at r4](https://reviewable.io/reviews/memkind/memkind/513#-MTHczRD-jvaak3h6xX0:-MTZjS599jBbkAvlIla_:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/3140f66d8cb086e9becbedb7eea45b6867224c6e/test/malloc_stats_print_test_helper.c#L23)):*
<details><summary>< [...]

2021-02-15 12:19 UTC, michalbiesek requested changes
> Reviewed 5 of 15 files at r5.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/513)* status: 9 of 19 files reviewed, 11 unresolved discussions (waiting on @michalbiesek and @PatKamin)

___
*[include/memkind.h, line 152 at r5](https://reviewable.io/reviews/memkind/memkind/513#-MT_bHNa5oQu9-rd8eje:-MT_bHNa5oQu9-rd8ejf:bk4ycz1) ([raw file](https://github.com/memkind/memkind/blob/b900e890ff014d9517f4b9afe39540ff8a99cb45/include/memkind.h#L152)):*
> ```
> MEMKIND_STAT_PRINT_NONE
> ```
The name could be confusing STAT_PRINT_NONE I could interpret as don't print stats?
Maybe some kind of form "default" in the name will be better.
___
*[man/memkind.3, line 81 at r5](https://reviewable.io/reviews/memkind/memkind/513#-MT__zXo6jt7ywGlJNmh:-MT__zXp0E9-nA3GUO2Y:bbnp7z4) ([raw file](https://github.com/memkind/memkind/blob/b900e890ff014d9517f4b9afe39540ff8a99cb45/man/memkind.3#L81)):*
> ```
> void
> ```
int
___
*[man/memkind.3, line 81 at r5](https://reviewable.io/reviews/memkind/memkind/513#-MT_aw4vA1OJK02A8dKr:-MT_aw4vA1OJK02A8dKs:bluckfc) ([raw file](https://github.com/memkind/memkind/blob/b900e890ff014d9517f4b9afe39540ff8a99cb45/man/memkind.3#L81)):*
> ```
> const char "*opts"
> ```
change to the correct type and provide documentation for it.
___
*[man/memkind.3, line 588 at r5](https://reviewable.io/reviews/memkind/memkind/513#-MT_aGWy05nOU9Pvzj7G:-MT_aGWy05nOU9Pvzj7H:b-hnf74x) ([raw file](https://github.com/memkind/memkind/blob/b900e890ff014d9517f4b9afe39540ff8a99cb45/man/memkind.3#L588)):*
> ```
> NULL
> ```
.IR "NULL" . see different places in memkind.3
___
*[man/memkind_arena.3, line 206 at r5](https://reviewable.io/reviews/memkind/memkind/513#-MT_aBWx2_N1a1zNnBVU:-MT_aBWx2_N1a1zNnBVV:b-hnf74x) ([raw file](https://github.com/memkind/memkind/blob/b900e890ff014d9517f4b9afe39540ff8a99cb45/man/memkind_arena.3#L206)):*
> ```
> NULL
> ```
.IR "NULL" . see different places in memkind.3
___
*[src/memkind_arena.c, line 900 at r5](https://reviewable.io/reviews/memkind/memkind/513#-MT_aVAv7Vy5qVi8Rlnb:-MT_aVAv7Vy5qVi8Rlnc:b-auk7is) ([raw file](https://github.com/memkind/memkind/blob/b900e890ff014d9517f4b9afe39540ff8a99cb45/src/memkind_arena.c#L900)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
>     if (opts != 0) {
>         return -1;
>     }
>     return 0;
> ```
</details>

nit: use ternary operator here.
___
*[src/memkind_arena.c, line 910 at r5](https://reviewable.io/reviews/memkind/memkind/513#-MT_bjv-B44M9-PXvOla:-MT_bjv-B44M9-PXvOlb:b-w6x1ov) ([raw file](https://github.com/memkind/memkind/blob/b900e890ff014d9517f4b9afe39540ff8a99cb45/src/memkind_arena.c#L910)):*
> ```
> Error:
> ```
No need for this "Error" part see other calls for log_err
___
*[src/memkind_arena.c, line 914 at r5](https://reviewable.io/reviews/memkind/memkind/513#-MT__NvG4O89nO0WcJrn:-MT__NvG4O89nO0WcJro:b3d0wp3) ([raw file](https://github.com/memkind/memkind/blob/b900e890ff014d9517f4b9afe39540ff8a99cb45/src/memkind_arena.c#L914)):*
> ```
> char temp[12] = ""
> ```
can you provide a test to pass all possible options?
___
*[src/memkind_arena.c, line 946 at r5](https://reviewable.io/reviews/memkind/memkind/513#-MT_aeT9A7UlH2EqBFaB:-MT_aeT9A7UlH2EqBFaC:b-krn9bo) ([raw file](https://github.com/memkind/memkind/blob/b900e890ff014d9517f4b9afe39540ff8a99cb45/src/memkind_arena.c#L946)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
>         } else {
>             log_err("Error: Printing statistics failed. Unsupported options '%d'", opts);
>             return MEMKIND_ERROR_INVALID;
>         }
> ```
</details>

when this could happen? I mean you validate the opts, right?
___
*[src/memkind_arena.c, line 947 at r5](https://reviewable.io/reviews/memkind/memkind/513#-MT_buepCthAVVH4C90p:-MT_buepCthAVVH4C90q:b-46b6qr) ([raw file](https://github.com/memkind/memkind/blob/b900e890ff014d9517f4b9afe39540ff8a99cb45/src/memkind_arena.c#L947)):*
> ```
> Error:
> ```
.
___
*[test/malloc_stats_print_test_helper.c, line 53 at r5](https://reviewable.io/reviews/memkind/memkind/513#-MT_c1HE6pVf_wj_qZGG:-MT_c1HE6pVf_wj_qZGH:b-vz6ypd) ([raw file](https://github.com/memkind/memkind/blob/b900e890ff014d9517f4b9afe39540ff8a99cb45/test/malloc_stats_print_test_helper.c#L53)):*
> ```
> -13
> ```
MEMKIND_ERROR_INVALID ?


<!-- Sent from Reviewable.io -->

2021-02-15 13:17 UTC, PatKamin reviewed
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/513)* status: 4 of 20 files reviewed, 10 unresolved discussions (waiting on @michalbiesek and @PatKamin)

___
*[include/memkind.h, line 152 at r5](https://reviewable.io/reviews/memkind/memkind/513#-MT_bHNa5oQu9-rd8eje:-MT_kUUSAC30f5N_WunZ:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/b900e890ff014d9517f4b9afe39540ff8a99cb45/include/memkind.h#L152)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> MEMKIND_STAT_PRINT_NONE
> ```
The name could be confusing STAT_PRINT_NONE I could interpret as don't print stats?
Maybe some kind of form "default" in the name will be better.
</blockquote></details>

Done.
___
*[man/memkind.3, line 81 at r5](https://reviewable.io/reviews/memkind/memkind/513#-MT__zXo6jt7ywGlJNmh:-MT_kfxq5KSWypXnDT1K:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/b900e890ff014d9517f4b9afe39540ff8a99cb45/man/memkind.3#L81)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> void
> ```
int
</blockquote></details>

Done.
___
*[man/memkind.3, line 81 at r5](https://reviewable.io/reviews/memkind/memkind/513#-MT_aw4vA1OJK02A8dKr:-MT_kgoN2gS1-y_DGWlV:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/b900e890ff014d9517f4b9afe39540ff8a99cb45/man/memkind.3#L81)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> const char "*opts"
> ```
change to the correct type and provide documentation for it.
</blockquote></details>

Done.
___
*[man/memkind.3, line 588 at r5](https://reviewable.io/reviews/memkind/memkind/513#-MT_aGWy05nOU9Pvzj7G:-MT_lwg-16sj9M8dEykc:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/b900e890ff014d9517f4b9afe39540ff8a99cb45/man/memkind.3#L588)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> NULL
> ```
.IR "NULL" . see different places in memkind.3
</blockquote></details>

Done.
___
*[man/memkind_arena.3, line 206 at r5](https://reviewable.io/reviews/memkind/memkind/513#-MT_aBWx2_N1a1zNnBVU:-MT_mxs8E1iaRzgMlVl1:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/b900e890ff014d9517f4b9afe39540ff8a99cb45/man/memkind_arena.3#L206)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> NULL
> ```
.IR "NULL" . see different places in memkind.3
</blockquote></details>

Done.
___
*[src/memkind_arena.c, line 910 at r5](https://reviewable.io/reviews/memkind/memkind/513#-MT_bjv-B44M9-PXvOla:-MT_npXP7Vd14WlL0Xq-:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/b900e890ff014d9517f4b9afe39540ff8a99cb45/src/memkind_arena.c#L910)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> Error:
> ```
No need for this "Error" part see other calls for log_err
</blockquote></details>

Done.
___
*[src/memkind_arena.c, line 946 at r5](https://reviewable.io/reviews/memkind/memkind/513#-MT_aeT9A7UlH2EqBFaB:-MT_nyfc4G7MYP7HpfOM:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/b900e890ff014d9517f4b9afe39540ff8a99cb45/src/memkind_arena.c#L946)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
>         } else {
>             log_err("Error: Printing statistics failed. Unsupported options '%d'", opts);
>             return MEMKIND_ERROR_INVALID;
>         }
> ```
when this could happen? I mean you validate the opts, right?
</blockquote></details>

Done.
___
*[src/memkind_arena.c, line 947 at r5](https://reviewable.io/reviews/memkind/memkind/513#-MT_buepCthAVVH4C90p:-MT_o-aq8mrAgsvWbRF3:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/b900e890ff014d9517f4b9afe39540ff8a99cb45/src/memkind_arena.c#L947)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> Error:
> ```
.
</blockquote></details>

Done.
___
*[test/malloc_stats_print_test_helper.c, line 53 at r5](https://reviewable.io/reviews/memkind/memkind/513#-MT_c1HE6pVf_wj_qZGG:-MT_o5qk924EoWXk1yP1:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/b900e890ff014d9517f4b9afe39540ff8a99cb45/test/malloc_stats_print_test_helper.c#L53)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> -13
> ```
MEMKIND_ERROR_INVALID ?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-02-15 15:01 UTC, michalbiesek requested changes
> Reviewed 2 of 15 files at r5, 6 of 13 files at r6.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/513)* status: 12 of 20 files reviewed, 4 unresolved discussions (waiting on @michalbiesek and @PatKamin)

___
*[src/memkind_arena.c, line 888 at r6](https://reviewable.io/reviews/memkind/memkind/513#-MTaBSPuEnMR4N_hHo0c:-MTaBSPuEnMR4N_hHo0d:b-mwata4) ([raw file](https://github.com/memkind/memkind/blob/536c472d0a41428805ef72b4aa7167ee016a1528/src/memkind_arena.c#L888)):*
> ```
> int
> ```
nit: this could be bool - true/false will be slightly more readable-> you already have a header for this in this file.
___
*[src/memkind_arena.c, line 900 at r6](https://reviewable.io/reviews/memkind/memkind/513#-MTaBaBI7c114GXKqEGS:-MTaBaBI7c114GXKqEGT:b-rw3lw0) ([raw file](https://github.com/memkind/memkind/blob/536c472d0a41428805ef72b4aa7167ee016a1528/src/memkind_arena.c#L900)):*
> ```
> opts != 0 ? -1 : 0
> ```
opts == 0
___
*[test/stats_print_test_helper.c, line 54 at r6](https://reviewable.io/reviews/memkind/memkind/513#-MTaAdIX6ZAho_ZqcC2K:-MTaAdIX6ZAho_ZqcC2L:b-y9r38e) ([raw file](https://github.com/memkind/memkind/blob/536c472d0a41428805ef72b4aa7167ee016a1528/test/stats_print_test_helper.c#L54)):*
> ```
>         if (retcode == MEMKIND_ERROR_INVALID) {
>             return 3;
> ```
wouldn't be simple for you to return from this: only status 0 in case of success and 1 or whatever else in case of failure? the logic of failure could be done only on this layer.


<!-- Sent from Reviewable.io -->

2021-02-15 15:34 UTC, PatKamin reviewed
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/513)* status: 11 of 20 files reviewed, 3 unresolved discussions (waiting on @michalbiesek and @PatKamin)

___
*[src/memkind_arena.c, line 900 at r6](https://reviewable.io/reviews/memkind/memkind/513#-MTaBaBI7c114GXKqEGS:-MTaDqvp9QvpGEg-73FK:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/536c472d0a41428805ef72b4aa7167ee016a1528/src/memkind_arena.c#L900)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> opts != 0 ? -1 : 0
> ```
opts == 0
</blockquote></details>

Done.
___
*[test/stats_print_test_helper.c, line 54 at r6](https://reviewable.io/reviews/memkind/memkind/513#-MTaAdIX6ZAho_ZqcC2K:-MTaEQRu5m4htfpQr9Iz:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/536c472d0a41428805ef72b4aa7167ee016a1528/test/stats_print_test_helper.c#L54)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
>         if (retcode == MEMKIND_ERROR_INVALID) {
>             return 3;
> ```
wouldn't be simple for you to return from this: only status 0 in case of success and 1 or whatever else in case of failure? the logic of failure could be done only on this layer.

</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-02-16 08:16 UTC, michalbiesek requested changes
> Reviewed 1 of 15 files at r5, 5 of 13 files at r6.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/513)* status: 16 of 20 files reviewed, 4 unresolved discussions (waiting on @michalbiesek and @PatKamin)

___
*[man/memkind.3, line 597 at r7](https://reviewable.io/reviews/memkind/memkind/513#-MTbYDto7C9TiUSAldKa:-MTbYDto7C9TiUSAldKb:b4s1xq0) ([raw file](https://github.com/memkind/memkind/blob/cfc908cec697bdc17babf14e342d698bd6933025/man/memkind.3#L597)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
> .I memkind_stat_print_opt
> in the
> .I memkind.h
> header file. Returns MEMKIND_ERROR_INVALID when failed to parse options string, MEMKIND_SUCCESS on success.
> ```
</details>

Describe it here in memkind.3
___
*[test/stats_print_test_helper.c, line 29 at r7](https://reviewable.io/reviews/memkind/memkind/513#-MTdtzl41ygLyE_e68ea:-MTdtzl41ygLyE_e68eb:brnuw9i) ([raw file](https://github.com/memkind/memkind/blob/cfc908cec697bdc17babf14e342d698bd6933025/test/stats_print_test_helper.c#L29)):*
> ```
> 1
> ```
nit: STDOUT_FILENO and you could easily remove the comment
___
*[test/stats_print_test_helper.c, line 33 at r7](https://reviewable.io/reviews/memkind/memkind/513#-MTdtqee0fkJF83O8FD2:-MTdtqee0fkJF83O8FD3:bgb8sh0) ([raw file](https://github.com/memkind/memkind/blob/cfc908cec697bdc17babf14e342d698bd6933025/test/stats_print_test_helper.c#L33)):*
> ```
> 1
> ```
nit:  STDOUT_FILENO and you could easily remove the comment


<!-- Sent from Reviewable.io -->

2021-02-16 15:48 UTC, PatKamin reviewed
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/513)* status: 16 of 20 files reviewed, 2 unresolved discussions (waiting on @michalbiesek and @PatKamin)

___
*[src/memkind_arena.c, line 914 at r5](https://reviewable.io/reviews/memkind/memkind/513#-MT__NvG4O89nO0WcJrn:-MTfVw-14gkCWopUiFdu:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/b900e890ff014d9517f4b9afe39540ff8a99cb45/src/memkind_arena.c#L914)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> char temp[12] = ""
> ```
can you provide a test to pass all possible options?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-02-17 08:18 UTC, michalbiesek requested changes
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/513)* status: 16 of 20 files reviewed, 3 unresolved discussions (waiting on @michalbiesek and @PatKamin)

___
*[test/stats_print_test.py, line 42 at r8](https://reviewable.io/reviews/memkind/memkind/513#-MTfdv4N03JdPnfWRizW:-MTfdv4N03JdPnfWRizX:be6vmm8) ([raw file](https://github.com/memkind/memkind/blob/4cfc5a6c3243c69843be4399a1b5d328acbf5b74/test/stats_print_test.py#L42)):*
> ```Python
>                self.error_msg.format("MEMKIND_STAT_PRINT_OMIT_PER_ARENA")
>         assert "extents:" not in output, \
>                self.error_msg.format("MEMKIND_STAT_PRINT_OMIT_EXTENT")
> ```

missing newline - please check this against some linter flake8 maybe
___
*[test/stats_print_test_helper.c, line 48 at r8](https://reviewable.io/reviews/memkind/memkind/513#-MTfdPcY6ox26qK4DySF:-MTfdPcY6ox26qK4DySG:b-ug0slz) ([raw file](https://github.com/memkind/memkind/blob/4cfc5a6c3243c69843be4399a1b5d328acbf5b74/test/stats_print_test_helper.c#L48)):*
<details><summary><i alt="summary">Quoted 16 lines of code…</i></summary>

> ```
>         memkind_t kind = MEMKIND_REGULAR;
>         void *ptr = memkind_malloc(kind, 1024);
>         memkind_free(kind, ptr);
>         memkind_arena_destroy(kind);
>         memkind_arena_malloc(kind, 1024);
>         ptr = memkind_malloc(kind, 1024);
>         int ret = memkind_stats_print(NULL, NULL,
>                                       MEMKIND_STAT_PRINT_JSON_FORMAT
>                                       | MEMKIND_STAT_PRINT_OMIT_GENERAL
>                                       | MEMKIND_STAT_PRINT_OMIT_MERGED_ARENA
>                                       | MEMKIND_STAT_PRINT_OMIT_DESTROYED_MERGED_ARENA
>                                       | MEMKIND_STAT_PRINT_OMIT_PER_ARENA
>                                       | MEMKIND_STAT_PRINT_OMIT_PER_SIZE_CLASS_BINS
>                                       | MEMKIND_STAT_PRINT_OMIT_PER_SIZE_CLASS_LARGE
>                                       | MEMKIND_STAT_PRINT_OMIT_MUTEX
>                                       | MEMKIND_STAT_PRINT_OMIT_EXTENT);
> ```
</details>

my intention with this was to just test all possible options.
I wouldn't manipulate the arena since this interface is not even available for users.
You use an internal header but I believe you don't need it.

If you want to have a situation when you call destroy arena consider this with pmem legacy solution based on fs dax and memkind_destory_kind operation


<!-- Sent from Reviewable.io -->

2021-02-17 15:15 UTC, PatKamin reviewed
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/513)* status: 16 of 20 files reviewed, 3 unresolved discussions (waiting on @michalbiesek)

___
*[man/memkind.3, line 597 at r7](https://reviewable.io/reviews/memkind/memkind/513#-MTbYDto7C9TiUSAldKa:-MTkYfZb-JmYtrcajFSZ:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/cfc908cec697bdc17babf14e342d698bd6933025/man/memkind.3#L597)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> .I memkind_stat_print_opt
> in the
> .I memkind.h
> header file. Returns MEMKIND_ERROR_INVALID when failed to parse options string, MEMKIND_SUCCESS on success.
> ```
Describe it here in memkind.3
</blockquote></details>

Done.
___
*[test/stats_print_test.py, line 42 at r8](https://reviewable.io/reviews/memkind/memkind/513#-MTfdv4N03JdPnfWRizW:-MTjV3CX9LnRhl3DROT2:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/4cfc5a6c3243c69843be4399a1b5d328acbf5b74/test/stats_print_test.py#L42)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

missing newline - please check this against some linter flake8 maybe
</blockquote></details>

Done.
___
*[test/stats_print_test_helper.c, line 48 at r8](https://reviewable.io/reviews/memkind/memkind/513#-MTfdPcY6ox26qK4DySF:-MTkW2D_2mP7DBLgLMVf:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/4cfc5a6c3243c69843be4399a1b5d328acbf5b74/test/stats_print_test_helper.c#L48)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
>         memkind_t kind = MEMKIND_REGULAR;
>         void *ptr = memkind_malloc(kind, 1024);
>         memkind_free(kind, ptr);
>         memkind_arena_destroy(kind);
>         memkind_arena_malloc(kind, 1024);
>         ptr = memkind_malloc(kind, 1024);
>         int ret = memkind_stats_print(NULL, NULL,
>                                       MEMKIND_STAT_PRINT_JSON_FORMAT
>                                       | MEMKIND_STAT_PRINT_OMIT_GENERAL
>                                       | MEMKIND_STAT_PRINT_OMIT_MERGED_ARENA
>                                       | MEMKIND_STAT_PRINT_OMIT_DESTROYED_MERGED_ARENA
>                                       | MEMKIND_STAT_PRINT_OMIT_PER_ARENA
>                                       | MEMKIND_STAT_PRINT_OMIT_PER_SIZE_CLASS_BINS
>                                       | MEMKIND_STAT_PRINT_OMIT_PER_SIZE_CLASS_LARGE
>                                       | MEMKIND_STAT_PRINT_OMIT_MUTEX
>                                       | MEMKIND_STAT_PRINT_OMIT_EXTENT);
> ```
my intention with this was to just test all possible options.
I wouldn't manipulate the arena since this interface is not even available for users.
You use an internal header but I believe you don't need it.

If you want to have a situation when you call destroy arena consider this with pmem legacy solution based on fs dax and memkind_destory_kind operation
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-02-18 13:24 UTC, PatKamin reviewed
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/513)* status: 10 of 20 files reviewed, 6 unresolved discussions (waiting on @michalbiesek)

___
*[man/memkind.3, line 579 at r10](https://reviewable.io/reviews/memkind/memkind/513#-MTlaL5nBA3z4WbSA1JQ:-MTo2N-e1fawpFUUx5_U:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/7108ae45c4ac35d1c08fbad3c8c8a6412ae885ff/man/memkind.3#L579)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> .PP
> .BR memkind_stats_print ()
> ```
please see how you break the description in memkind_get_stat explanation - call man memkind.3

please move your section in the end (right before .sp
.B "DECORATORS:")

</blockquote></details>

Done.
___
*[man/memkind.3, line 596 at r10](https://reviewable.io/reviews/memkind/memkind/513#-MTlcBCk1sIybItiL9uy:-MTo2qtA9DEXKd3yDUUU:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/7108ae45c4ac35d1c08fbad3c8c8a6412ae885ff/man/memkind.3#L596)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> string
> ```
?
</blockquote></details>

Done.
___
*[man/memkind.3, line 596 at r10](https://reviewable.io/reviews/memkind/memkind/513#-MTlcLg48FUKJDKGvrgt:-MTp7isdE5sGizy6pVpj:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/7108ae45c4ac35d1c08fbad3c8c8a6412ae885ff/man/memkind.3#L596)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> function. Pass additional options using the
> .I opts
> string. Accepted options are:
> ```
 Pass additional printing options using the
.I opts
For more details about
.I opts
see the
.B "MEMORY STATISTICS TYPE"
</blockquote></details>

Done.
___
*[man/memkind.3, line 598 at r10](https://reviewable.io/reviews/memkind/memkind/513#-MTlbrXV6tFoTqwdVVxg:-MTpD-70E8J92CzB2QB2:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/7108ae45c4ac35d1c08fbad3c8c8a6412ae885ff/man/memkind.3#L598)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> MEMKIND_STAT_PRINT_ALL
> ```
I would like to see it in a form where you have a distinguished section for all your option (similar as for MEMORY STATISTICS TYPE)

For more details about
.I stat
see the
.B "MEMORY STATISTICS PRINTING OPTION"  <-- you probably find better name for this


</blockquote></details>

Done.
___
*[man/memkind_arena.3, line 214 at r10](https://reviewable.io/reviews/memkind/memkind/513#-MTlaWgs4t0K7uLHgPTb:-MTpD0_N94aMYOIFL3je:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/7108ae45c4ac35d1c08fbad3c8c8a6412ae885ff/man/memkind_arena.3#L214)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> string. Accepted options are:
> .br
> ```
.
</blockquote></details>

Done.
___
*[test/stats_print_test_helper.c, line 50 at r10](https://reviewable.io/reviews/memkind/memkind/513#-MTlaz4Q9YKpAY8ZqoYq:-MTpGeWC6ilMXouCSncS:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/7108ae45c4ac35d1c08fbad3c8c8a6412ae885ff/test/stats_print_test_helper.c#L50)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
>         memkind_create_pmem(dir, max_size, &kind);
>         void *ptr = memkind_malloc(kind, 1024);
>         memkind_free(kind, ptr);
>         memkind_destroy_kind(kind);
>         memkind_create_pmem(dir, max_size, &kind);
> ```
Do you want to create it double times?
Please call destroy_kind explicitly for a second call if it is necessary
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-02-18 13:36 UTC, michalbiesek requested changes
> Reviewed 1 of 10 files at r11, 5 of 8 files at r12.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/513)* status: 15 of 20 files reviewed, 3 unresolved discussions (waiting on @michalbiesek and @PatKamin)

___
*[man/memkind.3, line 578 at r12](https://reviewable.io/reviews/memkind/memkind/513#-MTpJwhKDrZUTu2zwt5l:-MTpJwhKDrZUTu2zwt5m:b9q54pm) ([raw file](https://github.com/memkind/memkind/blob/6677b9dce9154fb51186ed0e70d5c2b71620a763/man/memkind.3#L578)):*
> ```
> .PP
> ```
nit: remove this change
___
*[man/memkind.3, line 617 at r12](https://reviewable.io/reviews/memkind/memkind/513#-MTpKsFt0-ccZAXt2b-4:-MTpKsFt0-ccZAXt2b-5:b-kpyeof) ([raw file](https://github.com/memkind/memkind/blob/6677b9dce9154fb51186ed0e70d5c2b71620a763/man/memkind.3#L617)):*
> ```
> .I opts.
> ```
.IR "opts" .
___
*[man/memkind_arena.3, line 212 at r11](https://reviewable.io/reviews/memkind/memkind/513#-MTpL1dUA7IHc4aZeCTx:-MTpL1dUA7IHc4aZeCTy:b-kpyeof) ([raw file](https://github.com/memkind/memkind/blob/7bed4549ce4b33a7820fc7a73b973940e4330d8a/man/memkind_arena.3#L212)):*
> ```
> .I opts.
> ```
.IR "opts" .


<!-- Sent from Reviewable.io -->

2021-02-18 13:56 UTC, PatKamin reviewed
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/513)* status: 10 of 20 files reviewed, 2 unresolved discussions (waiting on @michalbiesek)

___
*[man/memkind.3, line 617 at r12](https://reviewable.io/reviews/memkind/memkind/513#-MTpKsFt0-ccZAXt2b-4:-MTpMvgy6Gb5NGOoUR0R:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/6677b9dce9154fb51186ed0e70d5c2b71620a763/man/memkind.3#L617)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> .I opts.
> ```
.IR "opts" .
</blockquote></details>

Done.
___
*[man/memkind_arena.3, line 212 at r11](https://reviewable.io/reviews/memkind/memkind/513#-MTpL1dUA7IHc4aZeCTx:-MTpNEsi-ANJbQgoGiZ0:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/7bed4549ce4b33a7820fc7a73b973940e4330d8a/man/memkind_arena.3#L212)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> .I opts.
> ```
.IR "opts" .
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-02-18 14:02 UTC, michalbiesek approved these changes
> Reviewed 1 of 10 files at r13, 7 of 8 files at r14, 1 of 1 files at r15.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/513)* status: 19 of 20 files reviewed, all discussions resolved (waiting on @michalbiesek)



<!-- Sent from Reviewable.io -->

2021-02-18 14:02 UTC, michalbiesek reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/513#-:-MTpRe7V-wCaqDLOYbr-:bnfp4nl)* status: 19 of 20 files reviewed, all discussions resolved (waiting on @michalbiesek)



<!-- Sent from Reviewable.io -->

2021-02-18 15:38 UTC, merged