Master clang format
memkind/memkind pull request #516
Opened 2021-02-05 08:08 UTC by bratpiorka

### Description

### Types of changes

- [ ] Bugfix (non-breaking change which fixes issue linked in Description above)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation (correction or otherwise)
- [ ] Cosmetics (whitespace, appearance)
- [ ] Other

### Checklist

- [ ] Code compiles without errors
- [ ] All tests pass locally with my changes (see TESTING section in CONTRIBUTING file)
- [ ] Created tests which will fail without the change (if possible)
- [ ] Extended the README/documentation (if necessary)
- [ ] All newly added files have proprietary license (if necessary)
- [ ] All newly added files are referenced in MANIFEST files (if necessary)

## Further comments

2021-02-05 11:26 UTC, michalbiesek requested changes
> Reviewed 12 of 173 files at r1.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/516)* status: 12 of 173 files reviewed, 9 unresolved discussions (waiting on @bratpiorka)

___
*[.clang-format, line 2 at r1](https://reviewable.io/reviews/memkind/memkind/516#-MSlw3EX3c3-yI1r3cn1:-MSlw3EY8hxLIew06OoF:byibalw) ([raw file](https://github.com/memkind/memkind/blob/f86d0365e45f9f03cb4628a3416589e94eb6ff6d/.clang-format#L2)):*
> ```YAML
> BasedOnStyle: LLVM
> IndentWidth: 4
> ```

Regarding the second commit: and formatted files for me the style presented here is OK - just bump the dates in changed files.
___
*[.clang-format, line 6 at r1](https://reviewable.io/reviews/memkind/memkind/516#-MSloyWr8PXOxTMYUk7W:-MSloyWr8PXOxTMYUk7X:brnko58) ([raw file](https://github.com/memkind/memkind/blob/f86d0365e45f9f03cb4628a3416589e94eb6ff6d/.clang-format#L6)):*
> ```
> AfterClass:true
> ```
Can this form could be done without tabs: ?
AfterControlStatement: true

A same form like in "SplitEmptyFunction"
___
*[CONTRIBUTING, line 64 at r1](https://reviewable.io/reviews/memkind/memkind/516#-MSlpBuX0u1G6Rc_vjYA:-MSlpBuX0u1G6Rc_vjYB:b-gjrt5i) ([raw file](https://github.com/memkind/memkind/blob/f86d0365e45f9f03cb4628a3416589e94eb6ff6d/CONTRIBUTING#L64)):*
> ```
> TODO
> ```
remove.
As we spoke offline You could try adding a new target in code:
"make format" and after this you could call this shell script to ensure that formatting is ok.
Adding here note like:
 that before submitting a patch for inclusion, please ensure that if follows coding style by calling make format or something like that. Should be sufficient regarding coding style
___
*[CONTRIBUTING, line 66 at r1](https://reviewable.io/reviews/memkind/memkind/516#-MSlpAaJE7x9o-3jsvAz:-MSlpAaJE7x9o-3jsvB-:b-p4yj25) ([raw file](https://github.com/memkind/memkind/blob/f86d0365e45f9f03cb4628a3416589e94eb6ff6d/CONTRIBUTING#L66)):*
<details><summary><i alt="summary">Quoted 5 lines of code…</i></summary>

> ```
> Before submitting a patch for inclusion, please run the modified
> source code files through astyle with the following options
>     $ astyle --style=linux --indent=spaces=4 -S --max-continuation-indent=80 \
>              --max-code-length=80 --break-after-logical --indent-namespaces -z2 \
>              --align-pointer=name
> ```
</details>

remove this 
___
*[clang-format.sh, line 5 at r1](https://reviewable.io/reviews/memkind/memkind/516#-MSlv4E-4epb_swdcvQs:-MSlv4E-4epb_swdcvQt:b-fcgdn5) ([raw file](https://github.com/memkind/memkind/blob/f86d0365e45f9f03cb4628a3416589e94eb6ff6d/clang-format.sh#L5)):*
<details><summary><i alt="summary">Quoted 16 lines of code…</i></summary>

> ```
> CLANG_FORMAT_BIN="clang-format-10"
> CLANG_FORMAT_MIN_VER="10.0.0"
> CLANG_FORMAT_OPT="-i --style=file"
> if ! CLANG_FORMAT=$(which $CLANG_FORMAT_BIN)
> then
>     echo "Package $CLANG_FORMAT_BIN was not found. Unable to check source files format policy." >&2
>     exit 1
> fi
> CLANG_FORMAT_VER=$($CLANG_FORMAT_BIN --version 2>&1 | sed -E "s/.* ([0-9.]+).*/\1/")
> dpkg --compare-versions $CLANG_FORMAT_VER "ge" $CLANG_FORMAT_MIN_VER
> if (($?));
> then
>     echo "Minimal required version of clang-format is $CLANG_FORMAT_MIN_VER. Detected version is $CLANG_FORMAT_VER" >&2
>     echo "Unable to check source files format policy." >&2
>     exit 1
> fi
> ```
</details>

I think this code regarding checking the required package and checking minimal required version could be done on Autoconf/Makefile.am layer.

See that here you for example dump version from "clang-format-10" :) - not from "clang-format" so it is rather unexpected that clang-format-10 would be something like 11 or 9 and less than 10.0.0
___
*[install_clang-format.sh, line 2 at r1](https://reviewable.io/reviews/memkind/memkind/516#-MSlq4XX8yqq7yrn1fIp:-MSlq4XX8yqq7yrn1fIq:buxy1vx) ([raw file](https://github.com/memkind/memkind/blob/f86d0365e45f9f03cb4628a3416589e94eb6ff6d/install_clang-format.sh#L2)):*
<details><summary><i alt="summary">Quoted 6 lines of code…</i></summary>

> ```
> #!/bin/bash
> # SPDX-License-Identifier: BSD-2-Clause
> # Copyright (C) 2021 Intel Corporation.
> set -ex
> echo "Install clang-format"
> sudo apt install clang-format-10
> ```
</details>

I am not sure if this needed, imagine that you have some old OS where the default clang version in OS is below 10. Before install clang-format-10 you will also need to add LLVM to the apt repository. Long story short IMHO this script is not needed.
___
*[MANIFEST, line 9 at r1](https://reviewable.io/reviews/memkind/memkind/516#-MSlqZWT7eWWg1v3Ke52:-MSlqZWU97w2iOOuHuNQ:b-ece2ur) ([raw file](https://github.com/memkind/memkind/blob/f86d0365e45f9f03cb4628a3416589e94eb6ff6d/MANIFEST#L9)):*
> ```
> Makefile.am
> NEWS
> README
> ```

.clang_format ?
___
*[NEWS, line 36 at r1](https://reviewable.io/reviews/memkind/memkind/516#-MSlqerNEZJUEFQRMeu7:-MSlqerNEZJUEFQRMeu8:bhsjpet) ([raw file](https://github.com/memkind/memkind/blob/f86d0365e45f9f03cb4628a3416589e94eb6ff6d/NEWS#L36)):*
<details><summary><i alt="summary">Quoted 5 lines of code…</i></summary>

> ```
> - White space formatting generally conforms to
> TODO
>   $ astyle --style=linux --indent=spaces=4 -S --max-continuation-indent=80 \
>            --max-code-length=80 --break-after-logical --indent-namespaces -z2 \
>            --align-pointer=name
> ```
</details>

IMHO the whole section could be removed (doesn't need to be even updated). We could address the project presentation layer, like contribution guide/NEW/README.md in different PR.
___
*[.github/workflows/gha.yml, line 11 at r1](https://reviewable.io/reviews/memkind/memkind/516#-MSlr8A20jDO47yDbycg:-MSlr8A20jDO47yDbych:b-rm16e9) ([raw file](https://github.com/memkind/memkind/blob/f86d0365e45f9f03cb4628a3416589e94eb6ff6d/.github/workflows/gha.yml#L11)):*
> ```
>     - name: Install clang-format
>       run: sudo apt install clang-format-10
> ```
Not needed see:
https://github.com/memkind/memkind/runs/1837250430?check_suite_focus=true
"install clang-format" step: "clang-format-10 is already the newest version (1:10.0.0-4ubuntu1)."


<!-- Sent from Reviewable.io -->

2021-02-08 07:01 UTC, PatKamin commented on copying_headers/MANIFEST.freeBSD
> +install_clang-format.sh
Add this file to the commit.

2021-02-08 08:42 UTC, PatKamin commented on .clang-format
> +  AfterEnum: true
I think that `AfterExternBlock: False` could be useful, too.

2021-02-08 08:42 UTC, PatKamin commented on .clang-format
> +  BeforeElse: false
`BeforeWhile: false`  could be useful.

2021-02-08 10:42 UTC, bratpiorka reviewed
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/516)* status: 2 of 173 files reviewed, 9 unresolved discussions (waiting on @michalbiesek)

___
*[.clang-format, line 2 at r1](https://reviewable.io/reviews/memkind/memkind/516#-MSlw3EX3c3-yI1r3cn1:-MSmJKRi1-n7Fb5Z6zDV:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/f86d0365e45f9f03cb4628a3416589e94eb6ff6d/.clang-format#L2)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

Regarding the second commit: and formatted files for me the style presented here is OK - just bump the dates in changed files.
</blockquote></details>

Done.
___
*[.clang-format, line 6 at r1](https://reviewable.io/reviews/memkind/memkind/516#-MSloyWr8PXOxTMYUk7W:-MSmX5EK8dEqaaYMK1HY:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/f86d0365e45f9f03cb4628a3416589e94eb6ff6d/.clang-format#L6)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> AfterClass:true
> ```
Can this form could be done without tabs: ?
AfterControlStatement: true

A same form like in "SplitEmptyFunction"
</blockquote></details>

Done.
___
*[CONTRIBUTING, line 64 at r1](https://reviewable.io/reviews/memkind/memkind/516#-MSlpBuX0u1G6Rc_vjYA:-MSmXfFx6jIOVAaYPwCI:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/f86d0365e45f9f03cb4628a3416589e94eb6ff6d/CONTRIBUTING#L64)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> TODO
> ```
remove.
As we spoke offline You could try adding a new target in code:
"make format" and after this you could call this shell script to ensure that formatting is ok.
Adding here note like:
 that before submitting a patch for inclusion, please ensure that if follows coding style by calling make format or something like that. Should be sufficient regarding coding style
</blockquote></details>

Done.
___
*[CONTRIBUTING, line 66 at r1](https://reviewable.io/reviews/memkind/memkind/516#-MSlpAaJE7x9o-3jsvAz:-MSmXfZhEbCLafd5j2_e:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/f86d0365e45f9f03cb4628a3416589e94eb6ff6d/CONTRIBUTING#L66)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> Before submitting a patch for inclusion, please run the modified
> source code files through astyle with the following options
>     $ astyle --style=linux --indent=spaces=4 -S --max-continuation-indent=80 \
>              --max-code-length=80 --break-after-logical --indent-namespaces -z2 \
>              --align-pointer=name
> ```
remove this 
</blockquote></details>

Done.
___
*[clang-format.sh, line 5 at r1](https://reviewable.io/reviews/memkind/memkind/516#-MSlv4E-4epb_swdcvQs:-MT0DuvP-iOnSJIOQI7O:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/f86d0365e45f9f03cb4628a3416589e94eb6ff6d/clang-format.sh#L5)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> CLANG_FORMAT_BIN="clang-format-10"
> CLANG_FORMAT_MIN_VER="10.0.0"
> CLANG_FORMAT_OPT="-i --style=file"
> if ! CLANG_FORMAT=$(which $CLANG_FORMAT_BIN)
> then
>     echo "Package $CLANG_FORMAT_BIN was not found. Unable to check source files format policy." >&2
>     exit 1
> fi
> CLANG_FORMAT_VER=$($CLANG_FORMAT_BIN --version 2>&1 | sed -E "s/.* ([0-9.]+).*/\1/")
> dpkg --compare-versions $CLANG_FORMAT_VER "ge" $CLANG_FORMAT_MIN_VER
> if (($?));
> then
>     echo "Minimal required version of clang-format is $CLANG_FORMAT_MIN_VER. Detected version is $CLANG_FORMAT_VER" >&2
>     echo "Unable to check source files format policy." >&2
>     exit 1
> fi
> ```
I think this code regarding checking the required package and checking minimal required version could be done on Autoconf/Makefile.am layer.

See that here you for example dump version from "clang-format-10" :) - not from "clang-format" so it is rather unexpected that clang-format-10 would be something like 11 or 9 and less than 10.0.0
</blockquote></details>

Done.
___
*[install_clang-format.sh, line 2 at r1](https://reviewable.io/reviews/memkind/memkind/516#-MSlq4XX8yqq7yrn1fIp:-MSmXs_ZCBdud78Hf9ZG:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/f86d0365e45f9f03cb4628a3416589e94eb6ff6d/install_clang-format.sh#L2)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> #!/bin/bash
> # SPDX-License-Identifier: BSD-2-Clause
> # Copyright (C) 2021 Intel Corporation.
> set -ex
> echo "Install clang-format"
> sudo apt install clang-format-10
> ```
I am not sure if this needed, imagine that you have some old OS where the default clang version in OS is below 10. Before install clang-format-10 you will also need to add LLVM to the apt repository. Long story short IMHO this script is not needed.
</blockquote></details>

Done.
___
*[MANIFEST, line 9 at r1](https://reviewable.io/reviews/memkind/memkind/516#-MSlqZWT7eWWg1v3Ke52:-MT0Dyyx14Y5UyHh2lIv:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/f86d0365e45f9f03cb4628a3416589e94eb6ff6d/MANIFEST#L9)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

.clang_format ?
</blockquote></details>

Done.
___
*[NEWS, line 36 at r1](https://reviewable.io/reviews/memkind/memkind/516#-MSlqerNEZJUEFQRMeu7:-MSmY4N56OoJW4dRaLr7:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/f86d0365e45f9f03cb4628a3416589e94eb6ff6d/NEWS#L36)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> - White space formatting generally conforms to
> TODO
>   $ astyle --style=linux --indent=spaces=4 -S --max-continuation-indent=80 \
>            --max-code-length=80 --break-after-logical --indent-namespaces -z2 \
>            --align-pointer=name
> ```
IMHO the whole section could be removed (doesn't need to be even updated). We could address the project presentation layer, like contribution guide/NEW/README.md in different PR.
</blockquote></details>

Done.
___
*[.github/workflows/gha.yml, line 11 at r1](https://reviewable.io/reviews/memkind/memkind/516#-MSlr8A20jDO47yDbycg:-MSmuVqe80t2fTK26fQZ:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/f86d0365e45f9f03cb4628a3416589e94eb6ff6d/.github/workflows/gha.yml#L11)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
>     - name: Install clang-format
>       run: sudo apt install clang-format-10
> ```
Not needed see:
https://github.com/memkind/memkind/runs/1837250430?check_suite_focus=true
"install clang-format" step: "clang-format-10 is already the newest version (1:10.0.0-4ubuntu1)."
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-02-08 11:05 UTC, michalbiesek requested changes
> Reviewed 1 of 173 files at r1, 19 of 138 files at r2, 2 of 7 files at r3.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/516)* status: 17 of 173 files reviewed, 4 unresolved discussions (waiting on @bratpiorka and @michalbiesek)

___
*[.clang-format, line 13 at r2](https://reviewable.io/reviews/memkind/memkind/516#-MSnDwVJ2ziRX9MgAlS1:-MSnDwVJ2ziRX9MgAlS2:b3teeh) ([raw file](https://github.com/memkind/memkind/blob/db3dc74b5fa83bd587e4ff6997d013657c034906/.clang-format#L13)):*
> ```
> AfterUnion:false
> ```
tab -> space
___
*[configure.ac, line 2 at r3](https://reviewable.io/reviews/memkind/memkind/516#-MT0FqVv2vYoTblbaq6u:-MT0FqVw8DygORiwgLDp:bf70fwn) ([raw file](https://github.com/memkind/memkind/blob/98356424530503af56760d30177c40f2bbf094d8/configure.ac#L2)):*
> ```
> 2020
> ```
.
___
*[configure.ac, line 28 at r3](https://reviewable.io/reviews/memkind/memkind/516#-MT0Ey_s8vkB1jX8VlTq:-MT0Ey_tD5hcJzzcpGiL:b-ow9s08) ([raw file](https://github.com/memkind/memkind/blob/98356424530503af56760d30177c40f2bbf094d8/configure.ac#L28)):*
> ```
> 9.0.0
> ```
9 or 10 ? as greater equal


<!-- Sent from Reviewable.io -->

2021-02-08 13:39 UTC, bratpiorka reviewed
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/516)* status: 15 of 174 files reviewed, 4 unresolved discussions (waiting on @michalbiesek)

___
*[.clang-format, line 13 at r2](https://reviewable.io/reviews/memkind/memkind/516#-MSnDwVJ2ziRX9MgAlS1:-MT0RjI_3Nd0mZ0Qz5wJ:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/db3dc74b5fa83bd587e4ff6997d013657c034906/.clang-format#L13)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> AfterUnion:false
> ```
tab -> space
</blockquote></details>

Done.
___
*[configure.ac, line 2 at r3](https://reviewable.io/reviews/memkind/memkind/516#-MT0FqVv2vYoTblbaq6u:-MT0RlmV3HbYRModNFpF:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/98356424530503af56760d30177c40f2bbf094d8/configure.ac#L2)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> 2020
> ```
.
</blockquote></details>

Done.
___
*[configure.ac, line 28 at r3](https://reviewable.io/reviews/memkind/memkind/516#-MT0Ey_s8vkB1jX8VlTq:-MT0RoigB368SB2UMne5:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/98356424530503af56760d30177c40f2bbf094d8/configure.ac#L28)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> 9.0.0
> ```
9 or 10 ? as greater equal
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-02-08 21:07 UTC, michalbiesek requested changes
> Reviewed 1 of 7 files at r3, 3 of 6 files at r4.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/516)* status: 19 of 174 files reviewed, 11 unresolved discussions (waiting on @bratpiorka and @michalbiesek)

___
*[clang-format.sh, line 12 at r4](https://reviewable.io/reviews/memkind/memkind/516#-MT2PezmEELqpo_2nB1W:-MT2PezmEELqpo_2nB1X:b-h6o2oj) ([raw file](https://github.com/memkind/memkind/blob/a187a978ce85acb50baeca49c88d07a1e96d1857/clang-format.sh#L12)):*
<details><summary><i alt="summary">Quoted 6 lines of code…</i></summary>

> ```
> if  ! [ -z "$(git diff --name-only)" ]
> then
>     echo "Please stage or stash all modified files before running this script."
>     git diff --name-only
>     exit 1
> fi
> ```
</details>

not sure if this whole git diff is needed,
IMHO this could be handled differently with two separate targets
make format-check - would perform check without  apply changes (--dry-run instead of i)
make format - would perform clang-format logic and apply changes

Rename the target if you find a better name.

The advantage of this is that you don't need this script at all which does two things(format and git diff) and currently you have the limitation that you cannot call it in case of a situation that you have only modified files. You could have all the logic of this script in Makefile therefore you will not need separately scripts for this.

In CI, you could just call make format-check.
On the dev machine, the user is more interested in calling performing make-format.
___
*[clang-format.sh, line 19 at r4](https://reviewable.io/reviews/memkind/memkind/516#-MT2IgVBCP62wmqgVO8i:-MT2IgVBCP62wmqgVO8j:bu93nyr) ([raw file](https://github.com/memkind/memkind/blob/a187a978ce85acb50baeca49c88d07a1e96d1857/clang-format.sh#L19)):*
> ```
> rm -f clang-format.out
> ```
when this file is created?
___
*[configure.ac, line 275 at r4](https://reviewable.io/reviews/memkind/memkind/516#-MT13_dj-MHUDzCR0h3h:-MT13_dj-MHUDzCR0h3i:bxbgkh0) ([raw file](https://github.com/memkind/memkind/blob/a187a978ce85acb50baeca49c88d07a1e96d1857/configure.ac#L275)):*
> ```
> clang-format-10 
> ```
this should be extended by clang-format-11 since this is a latest stable release
___
*[configure.ac, line 277 at r4](https://reviewable.io/reviews/memkind/memkind/516#-MT142zy8tXUeqbsNsmk:-MT142zy8tXUeqbsNsml:b-2i4lax) ([raw file](https://github.com/memkind/memkind/blob/a187a978ce85acb50baeca49c88d07a1e96d1857/configure.ac#L277)):*
> ```
> AC_MSG_NOTICE([clang-format is required for code style checking])
> ```
See how this is represented in output in case of calling ./configure in case of missing clang-format and wrong version. The output could be easily omitted by the user.

```
./configure
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking how to create a pax tar archive... gnutar
checking whether make supports nested variables... (cached) yes
checking for style of include used by make... GNU
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking dependency style of gcc... gcc3
checking for ar... ar
checking the archiver (ar) interface... ar
checking for g++... g++
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking dependency style of g++... gcc3
checking for gcc... (cached) gcc
checking whether we are using the GNU C compiler... (cached) yes
checking whether gcc accepts -g... (cached) yes
checking for gcc option to accept ISO C89... (cached) none needed
checking whether gcc understands -c and -o together... (cached) yes
checking dependency style of gcc... (cached) gcc3
checking for gcc option to support OpenMP... -fopenmp
checking for numa_available in -lnuma... yes
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking for a sed that does not truncate output... /bin/sed
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking whether gcc is Clang... no
checking whether pthreads work with -pthread... yes
checking for joinable pthread attribute... PTHREAD_CREATE_JOINABLE
checking whether more special flags are required for pthreads... no
checking for PTHREAD_PRIO_INHERIT... yes
checking for secure_getenv... yes
checking for daxctl_dev_get_memory in -ldaxctl... yes
checking for hwloc_memattr_get_best_target in -lhwloc... yes
checking for clang-format-10... no
checking for clang-format... no
configure: clang-format is required for code style checking
checking whether g++ supports C++11 features with -std=c++11... yes
checking how to print strings... printf
checking for a sed that does not truncate output... (cached) /bin/sed
checking for fgrep... /bin/grep -F
checking for ld used by gcc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1572864
checking how to convert x86_64-pc-linux-gnu file names to x86_64-pc-linux-gnu format... func_convert_file_noop
checking how to convert x86_64-pc-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /usr/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /usr/bin/nm -B output from gcc object... ok
checking for sysroot... no
checking for a working dd... /bin/dd
checking how to truncate binary pipes... /bin/dd bs=4096 count=1
checking for mt... mt
checking if mt is a manifest tool... no
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... no
checking for gcc option to produce PIC... -fPIC -DPIC
checking if gcc PIC flag -fPIC -DPIC works... yes
checking if gcc static flag -static works... no
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
checking how to run the C++ preprocessor... g++ -std=c++11 -E
checking for ld used by g++ -std=c++11... /usr/bin/ld -m elf_x86_64
checking if the linker (/usr/bin/ld -m elf_x86_64) is GNU ld... yes
checking whether the g++ -std=c++11 linker (/usr/bin/ld -m elf_x86_64) supports shared libr [...]

2021-02-09 11:12 UTC, bratpiorka reviewed
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/516)* status: 15 of 173 files reviewed, 11 unresolved discussions (waiting on @bratpiorka and @michalbiesek)

___
*[clang-format.sh, line 12 at r4](https://reviewable.io/reviews/memkind/memkind/516#-MT2PezmEELqpo_2nB1W:-MT5QenFEqcHhgGDTByS:b-psgmue) ([raw file](https://github.com/memkind/memkind/blob/a187a978ce85acb50baeca49c88d07a1e96d1857/clang-format.sh#L12)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> if  ! [ -z "$(git diff --name-only)" ]
> then
>     echo "Please stage or stash all modified files before running this script."
>     git diff --name-only
>     exit 1
> fi
> ```
not sure if this whole git diff is needed,
IMHO this could be handled differently with two separate targets
make format-check - would perform check without  apply changes (--dry-run instead of i)
make format - would perform clang-format logic and apply changes

Rename the target if you find a better name.

The advantage of this is that you don't need this script at all which does two things(format and git diff) and currently you have the limitation that you cannot call it in case of a situation that you have only modified files. You could have all the logic of this script in Makefile therefore you will not need separately scripts for this.

In CI, you could just call make format-check.
On the dev machine, the user is more interested in calling performing make-format.
</blockquote></details>

Done, added make code-style-check and code-style-apply targets
___
*[clang-format.sh, line 19 at r4](https://reviewable.io/reviews/memkind/memkind/516#-MT2IgVBCP62wmqgVO8i:-MT4w5e74A1G0RLhka3w:bqm8mjp) ([raw file](https://github.com/memkind/memkind/blob/a187a978ce85acb50baeca49c88d07a1e96d1857/clang-format.sh#L19)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> rm -f clang-format.out
> ```
when this file is created?
</blockquote></details>

Done, removed
___
*[configure.ac, line 275 at r4](https://reviewable.io/reviews/memkind/memkind/516#-MT13_dj-MHUDzCR0h3h:-MT4rSol-4LPLC8OtFZg:b-z696qp) ([raw file](https://github.com/memkind/memkind/blob/a187a978ce85acb50baeca49c88d07a1e96d1857/configure.ac#L275)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> clang-format-10 
> ```
this should be extended by clang-format-11 since this is a latest stable release
</blockquote></details>

Done, added clang-format-11
___
*[configure.ac, line 277 at r4](https://reviewable.io/reviews/memkind/memkind/516#-MT142zy8tXUeqbsNsmk:-MT4wDwOCA5c9rU7tYXO:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/a187a978ce85acb50baeca49c88d07a1e96d1857/configure.ac#L277)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> AC_MSG_NOTICE([clang-format is required for code style checking])
> ```
See how this is represented in output in case of calling ./configure in case of missing clang-format and wrong version. The output could be easily omitted by the user.

```
./configure
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking how to create a pax tar archive... gnutar
checking whether make supports nested variables... (cached) yes
checking for style of include used by make... GNU
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking dependency style of gcc... gcc3
checking for ar... ar
checking the archiver (ar) interface... ar
checking for g++... g++
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking dependency style of g++... gcc3
checking for gcc... (cached) gcc
checking whether we are using the GNU C compiler... (cached) yes
checking whether gcc accepts -g... (cached) yes
checking for gcc option to accept ISO C89... (cached) none needed
checking whether gcc understands -c and -o together... (cached) yes
checking dependency style of gcc... (cached) gcc3
checking for gcc option to support OpenMP... -fopenmp
checking for numa_available in -lnuma... yes
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking for a sed that does not truncate output... /bin/sed
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking whether gcc is Clang... no
checking whether pthreads work with -pthread... yes
checking for joinable pthread attribute... PTHREAD_CREATE_JOINABLE
checking whether more special flags are required for pthreads... no
checking for PTHREAD_PRIO_INHERIT... yes
checking for secure_getenv... yes
checking for daxctl_dev_get_memory in -ldaxctl... yes
checking for hwloc_memattr_get_best_target in -lhwloc... yes
checking for clang-format-10... no
checking for clang-format... no
configure: clang-format is required for code style checking
checking whether g++ supports C++11 features with -std=c++11... yes
checking how to print strings... printf
checking for a sed that does not truncate output... (cached) /bin/sed
checking for fgrep... /bin/grep -F
checking for ld used by gcc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1572864
checking how to convert x86_64-pc-linux-gnu file names to x86_64-pc-linux-gnu format... func_convert_file_noop
checking how to convert x86_64-pc-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /usr/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /usr/bin/nm -B output from gcc object... ok
checking for sysroot... no
checking for a working dd... /bin/dd
checking how to truncate binary pipes... /bin/dd bs=4096 count=1
checking for mt... mt
checking if mt is a manifest tool... no
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... no
checking for gcc option to produce PIC... -fPIC -DPIC
checking if gcc PIC flag -fPIC -DPIC works... yes
checking if gcc static flag -static works... no
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build [...]

2021-02-10 07:50 UTC, michalbiesek requested changes
> Reviewed 1 of 7 files at r3, 5 of 19 files at r5.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/516)* status: 5 of 173 files reviewed, 11 unresolved discussions (waiting on @bratpiorka and @michalbiesek)

___
*[clang-format.sh, line 12 at r4](https://reviewable.io/reviews/memkind/memkind/516#-MT2PezmEELqpo_2nB1W:-MT7hYIEBR8XcsolBd2h:b-mgvus7) ([raw file](https://github.com/memkind/memkind/blob/a187a978ce85acb50baeca49c88d07a1e96d1857/clang-format.sh#L12)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

Done, added make code-style-check and code-style-apply targets
</blockquote></details>

Regarding get rid of this script see my other comments The advantages of the proposed solution are:
- make code-style-check and make code-style-apply are only official and presente way for calling the formatting - since there will be no more shell script to execute
- one less file to maintain
- see that I use all possible information from configure layer - don't need to use 'which' to check again for clang-format support - I pass this information from configure layer
- no need to perform logic with handling the argument and the solution is done in two layers instead of three
___
*[clang-format.sh, line 13 at r5](https://reviewable.io/reviews/memkind/memkind/516#-MT7k1_4Cj5dguLJXUvX:-MT7k1_4Cj5dguLJXUvY:b-cx0jxz) ([raw file](https://github.com/memkind/memkind/blob/f9c63bd47e1247d37722d63f542254865e43d281/clang-format.sh#L13)):*
> ```
> -Werror
> ```
According to doc:
https://clang.llvm.org/docs/ClangFormat.html
it is "--Werror", but see my other comments regarding this script
___
*[configure.ac, line 275 at r5](https://reviewable.io/reviews/memkind/memkind/516#-MT7fOrt1eLklu2CNfZ9:-MT7fOrt1eLklu2CNfZA:b-cd9gpn) ([raw file](https://github.com/memkind/memkind/blob/f9c63bd47e1247d37722d63f542254865e43d281/configure.ac#L275)):*
<details><summary><i alt="summary">Quoted 7 lines of code…</i></summary>

> ```
> AC_CHECK_PROGS(CLANG_FORMAT, [clang-format-11 clang-format-10 clang-format], [error])
> if test "$CLANG_FORMAT" != "error"; then
>   CLANG_FORMAT_VERSION=$($CLANG_FORMAT --version)
>   AX_COMPARE_VERSION([$CLANG_FORMAT_VERSION], [ge], [10.0.0],,
>     AC_MSG_NOTICE([$CLANG_FORMAT version: $CLANG_FORMAT_VERSION too low]))
> fi
> AC_SUBST([clang_format], $CLANG_FORMAT)
> ```
</details>

 ```
clang_support=no;
AC_CHECK_PROGS(CLANG_FORMAT, [clang-format-11 clang-format-10 clang-format], "")
if test "$CLANG_FORMAT" != ""; then
  CLANG_FORMAT_VERSION=$($CLANG_FORMAT --version)
  AX_COMPARE_VERSION([$CLANG_FORMAT_VERSION], [ge], [10.0.0], [clang_support=yes], [])
fi
AC_SUBST([clang_format], $CLANG_FORMAT)
AM_CONDITIONAL([HAVE_CLANG_FORMAT], [test "x$clang_support" = xyes])
 ```
The construction above allows you to pass an information (to Makefile.am layer) if expected version of clang_format is supported or not
___
*[configure.ac, line 279 at r5](https://reviewable.io/reviews/memkind/memkind/516#-MT7fCfr1avfASswBwjl:-MT7fCfr1avfASswBwjm:b-dsfb89) ([raw file](https://github.com/memkind/memkind/blob/f9c63bd47e1247d37722d63f542254865e43d281/configure.ac#L279)):*
> ```
> AC_MSG_NOTICE([$CLANG_FORMAT version: $CLANG_FORMAT_VERSION too low]))
> ```
consider that user probably won't even notice it - see my other comment here regarding implementation
___
*[configure.ac, line 295 at r5](https://reviewable.io/reviews/memkind/memkind/516#-MT68pJABmlav14DHeGZ:-MT68pJABmlav14DHeG_:btfn2ym) ([raw file](https://github.com/memkind/memkind/blob/f9c63bd47e1247d37722d63f542254865e43d281/configure.ac#L295)):*
> ```
>                =
> ```
Please restore
___
*[configure.ac, line 316 at r5](https://reviewable.io/reviews/memkind/memkind/516#-MT7fyTw-cjb8i_GjvDv:-MT7fyTw-cjb8i_GjvDw:b-x1ytvo) ([raw file](https://github.com/memkind/memkind/blob/f9c63bd47e1247d37722d63f542254865e43d281/configure.ac#L316)):*
> ```
> if test "$CLANG_FORMAT" != "error" ; then
> ```
nit:
can we keep convention with "yes" instead of error see check for libdaxctl and libhwloc, e.g.
 ```
if test $clang_support = "yes" ; then
 ```
___
*[configure.ac, line 318 at r5](https://reviewable.io/reviews/memkind/memkind/516#-MT63tkm53fe7j2s63x6:-MT63tkm53fe7j2s63x7:bbx6uet) ([raw file](https://github.com/memkind/memkind/blob/f9c63bd47e1247d37722d63f542254865e43d281/configure.ac#L318)):*
> ```
> supported
> ```
nit: enabled
A minor advantage of this change is syntax coloring in the terminal - if the terminal supports it.
___
*[configure.ac, line 324 at r5](https://reviewable.io/reviews/memkind/memkind/516#-MT7gePcBlnqnn7F9qBR:-MT7gePcBlnqnn7F9qBS:b-4ojvre) ([raw file](https://github.com/memkind/memkind/blob/f9c63bd47e1247d37722d63f542254865e43d281/configure.ac#L324)):*
> ```
>                Automatic code style formatting is disabled. It requires clang-format version
>                10.0.0 or above.])
> ```
nit:
can we keep convention with as for libdaxctl and libhwloc, e.g.

To enable this feature please install clang-format v10.0.0 or later
               and run configure again
___
*[Makefile.am, line 7 at r5](https://reviewable.io/reviews/memkind/memkind/516#-MT7exZb3CI-9yKwRnp5:-MT7exZb3CI-9yKwRnp6:beoz1xb) ([raw file](https://github.com/memkind/memkind/blob/f9c63bd47e1247d37722d63f542254865e43d281/Makefile.am#L7)):*
> ```Makefile
> AM_CPPFLAGS = -I$(top_srcdir)/include -I$(top_srcdir)/jemalloc/include
> MAN2HTML = groff -mandoc -Thtml
> ```

Please add here:
```
CLANG_FORMAT = @clang_format@ --style=file
CLANG_FORMAT_FILES = . -path "./jemalloc" -prune -false -o -path "./test/gtest_fused" -prune -false -o \
                     -iname "*.h" -o -iname "*.hpp" -o -iname "*.c" -o -iname "*.cpp"
```
If you find a more convenient solution for CLANG_FORMAT_FILES use it
___
*[Makefile.am, line 551 at r5](https://reviewable.io/reviews/memkind/memkind/516#-MT6ADkQ4Y2AiQtom_Jn:-MT6ADkRDfU1yOoE6krm:bjkx9gy) ([raw file](https://github.com/memkind/memkind/blob/f9c63bd47e1247d37722d63f542254865e43d281/Makefile.am#L551)):*
> ```
> @CLANG_FORMAT_BIN=@clang_format@ CLANG_FORMAT_ACTION=check ./clang-format.sh
> ```
```
code-style-check:
if HAVE_CLANG_FORMAT
	find $(CLANG_FORMAT_FILES) | xargs $(CLANG_FORMAT) --dry-run --Werror
else
	@echo "clang-format not found please install version >= 10.0.0 or later and run configure again"
	exit 1
endif

code-style-apply:
if HAVE_CLANG_FORMAT
	find $(CLANG_FORMAT_FILES) | xargs $(CLANG_FORMAT) -i
else
	@echo "clang-format not found please install version >= 10.0.0 or later and run configure again"
	exit 1
endif
```
___
*[include/memkind.h, line 122 at r4](https://reviewable.io/reviews/memkind/memkind/516#-MT2EmHO6CvDEbld5uyi:-MT7nTVz2EokQnNva-U-:b523ykx) ([raw file](https://github.com/memkind/memkind/blob/a187a978ce85acb50baeca49c88d07a1e96d1857/include/memkind.h#L122)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
>     MEMKIND_SUCCESS = 0,            /**<  Operation success */
>     MEMKIND_ERROR_UNAVAILABLE = -1, /**<  Error: Memory kind is not available */
>     MEMKIND_ERROR_MBIND = -2,       /**<  Error: Call to mbind() failed */
>     MEMKIND_ERROR_MMAP = -3,        /**<  Error: Call to mmap() failed */
>     MEMKIND_ERROR_MALLOC = -6,      /**<  Error: Call to malloc() failed */
>     MEMKIND_ERROR_ENVIRON =
>         -12, /**<  Error: Unable to parse environment variable */
>     MEMKIND_ERROR_INVALID = -13, /**<  Error: Invalid argument */
>     MEMKIND_ERROR_TOOMANY = -15, /**<  Error: Attempt to initialize more than
>                                     MEMKIND_MAX_KIND number of kinds */
>     MEMKIND_ERROR_BADOPS = -17,  /**<  Error: Invalid memkind_ops structure */
>     MEMKIND_ERROR_HUGETLB = -18, /**<  Error: Unable to allocate huge pages */
>     MEMKIND_ERROR_MEMTYPE_NOT_AVAILABLE =
>         -20, /**<  Error: Requested memory type is not available */
>     MEMKIND_ERROR_OPERATION_FAILED = -21, /**<  Error: Operation failed */
>     MEMKIND_ERROR_ARENAS_CREATE =
>         -22 [...]

2021-02-10 10:15 UTC, bratpiorka reviewed
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/516)* status: 2 of 173 files reviewed, 8 unresolved discussions (waiting on @michalbiesek)

___
*[clang-format.sh, line 13 at r5](https://reviewable.io/reviews/memkind/memkind/516#-MT7k1_4Cj5dguLJXUvX:-MTA4SlJAF4JDGXceHv4:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/f9c63bd47e1247d37722d63f542254865e43d281/clang-format.sh#L13)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> -Werror
> ```
According to doc:
https://clang.llvm.org/docs/ClangFormat.html
it is "--Werror", but see my other comments regarding this script
</blockquote></details>

Done.
___
*[configure.ac, line 275 at r5](https://reviewable.io/reviews/memkind/memkind/516#-MT7fOrt1eLklu2CNfZ9:-MTA3h9B32ESCVfrg9O1:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/f9c63bd47e1247d37722d63f542254865e43d281/configure.ac#L275)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> AC_CHECK_PROGS(CLANG_FORMAT, [clang-format-11 clang-format-10 clang-format], [error])
> if test "$CLANG_FORMAT" != "error"; then
>   CLANG_FORMAT_VERSION=$($CLANG_FORMAT --version)
>   AX_COMPARE_VERSION([$CLANG_FORMAT_VERSION], [ge], [10.0.0],,
>     AC_MSG_NOTICE([$CLANG_FORMAT version: $CLANG_FORMAT_VERSION too low]))
> fi
> AC_SUBST([clang_format], $CLANG_FORMAT)
> ```
 ```
clang_support=no;
AC_CHECK_PROGS(CLANG_FORMAT, [clang-format-11 clang-format-10 clang-format], "")
if test "$CLANG_FORMAT" != ""; then
  CLANG_FORMAT_VERSION=$($CLANG_FORMAT --version)
  AX_COMPARE_VERSION([$CLANG_FORMAT_VERSION], [ge], [10.0.0], [clang_support=yes], [])
fi
AC_SUBST([clang_format], $CLANG_FORMAT)
AM_CONDITIONAL([HAVE_CLANG_FORMAT], [test "x$clang_support" = xyes])
 ```
The construction above allows you to pass an information (to Makefile.am layer) if expected version of clang_format is supported or not
</blockquote></details>

Done.
___
*[configure.ac, line 279 at r5](https://reviewable.io/reviews/memkind/memkind/516#-MT7fCfr1avfASswBwjl:-MTA3jJGCQvnfvj7umry:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/f9c63bd47e1247d37722d63f542254865e43d281/configure.ac#L279)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> AC_MSG_NOTICE([$CLANG_FORMAT version: $CLANG_FORMAT_VERSION too low]))
> ```
consider that user probably won't even notice it - see my other comment here regarding implementation
</blockquote></details>

Done.
___
*[configure.ac, line 295 at r5](https://reviewable.io/reviews/memkind/memkind/516#-MT68pJABmlav14DHeGZ:-MTA1MyD6w87C_F8K-Zz:b-yb2oqv) ([raw file](https://github.com/memkind/memkind/blob/f9c63bd47e1247d37722d63f542254865e43d281/configure.ac#L295)):*
> ke code-style-apply are only official and presente way for calling the formatting - since there will be no more shell script to execute
> one less file to maintain
> see that I use all possible information

IMHO with this change output looks better, but OK - restored
___
*[Makefile.am, line 7 at r5](https://reviewable.io/reviews/memkind/memkind/516#-MT7exZb3CI-9yKwRnp5:-MTA4DhiEePRTcqX2G1X:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/f9c63bd47e1247d37722d63f542254865e43d281/Makefile.am#L7)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

Please add here:
```
CLANG_FORMAT = @clang_format@ --style=file
CLANG_FORMAT_FILES = . -path "./jemalloc" -prune -false -o -path "./test/gtest_fused" -prune -false -o \
                     -iname "*.h" -o -iname "*.hpp" -o -iname "*.c" -o -iname "*.cpp"
```
If you find a more convenient solution for CLANG_FORMAT_FILES use it
</blockquote></details>

Done.
___
*[Makefile.am, line 551 at r5](https://reviewable.io/reviews/memkind/memkind/516#-MT6ADkQ4Y2AiQtom_Jn:-MTA4OHCB4NOf5ZJtBCa:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/f9c63bd47e1247d37722d63f542254865e43d281/Makefile.am#L551)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> @CLANG_FORMAT_BIN=@clang_format@ CLANG_FORMAT_ACTION=check ./clang-format.sh
> ```
```
code-style-check:
if HAVE_CLANG_FORMAT
	find $(CLANG_FORMAT_FILES) | xargs $(CLANG_FORMAT) --dry-run --Werror
else
	@echo "clang-format not found please install version >= 10.0.0 or later and run configure again"
	exit 1
endif

code-style-apply:
if HAVE_CLANG_FORMAT
	find $(CLANG_FORMAT_FILES) | xargs $(CLANG_FORMAT) -i
else
	@echo "clang-format not found please install version >= 10.0.0 or later and run configure again"
	exit 1
endif
```
</blockquote></details>

Done.
___
*[include/memkind.h, line 122 at r4](https://reviewable.io/reviews/memkind/memkind/516#-MT2EmHO6CvDEbld5uyi:-MTAQvgMAKKNnzHCqkKk:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/a187a978ce85acb50baeca49c88d07a1e96d1857/include/memkind.h#L122)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

AlignConsecutiveAssignments: true
But this also will require a manual change here :/ 

maybe the best idea is to unify this comment form for enum in this header as it is the official interface 
like it was done for memkind_memtype_t - this would probably also apply to memkind_const,memkind_stat_type, memkind_mem_usage_policy

</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-02-10 12:38 UTC, michalbiesek approved these changes
> Reviewed 26 of 173 files at r1, 2 of 7 files at r3, 5 of 19 files at r5, 139 of 139 files at r6.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/516)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @bratpiorka)

___
*[configure.ac, line 295 at r5](https://reviewable.io/reviews/memkind/memkind/516#-MT68pJABmlav14DHeGZ:-MTAn2Mx9EIVP2IlwQN5:bq6er2b) ([raw file](https://github.com/memkind/memkind/blob/f9c63bd47e1247d37722d63f542254865e43d281/configure.ac#L295)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

> ke code-style-apply are only official and presente way for calling the formatting - since there will be no more shell script to execute
> one less file to maintain
> see that I use all possible information

IMHO with this change output looks better, but OK - restored
</blockquote></details>

Feel free to open new PR regarding improving the look output (just consider the output should be somehow unified)
___
*[configure.ac, line 274 at r6](https://reviewable.io/reviews/memkind/memkind/516#-MTAr4Yn6DypoJIAGPw7:-MTAr4Yo8AaJptHrg8uO:bjzo8ky) ([raw file](https://github.com/memkind/memkind/blob/05ebb61d0eda814cdc4295920be07fc0a2565ccc/configure.ac#L274)):*
> ```M4Sugar
> AC_SUBST([enable_heap_manager])
> 
> #===============================clang-format====================================
> ```

Thanks for this PR, the first commit is IMHO ok, please just bump dates in modified files from the second commit. 
As we spoke offline, I will merge this PR after #515 


<!-- Sent from Reviewable.io -->

2021-02-10 12:59 UTC, bratpiorka reviewed
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/516)* status: 43 of 172 files reviewed, all discussions resolved (waiting on @michalbiesek)

___
*[configure.ac, line 274 at r6](https://reviewable.io/reviews/memkind/memkind/516#-MTAr4Yn6DypoJIAGPw7:-MTB0Jg-AhkJL-YSADX3:b-u13rau) ([raw file](https://github.com/memkind/memkind/blob/05ebb61d0eda814cdc4295920be07fc0a2565ccc/configure.ac#L274)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

Thanks for this PR, the first commit is IMHO ok, please just bump dates in modified files from the second commit. 
As we spoke offline, I will merge this PR after #515 
</blockquote></details>


ok, bumped


<!-- Sent from Reviewable.io -->

2021-02-19 08:20 UTC, michalbiesek commented
Please rebase

2021-02-19 09:56 UTC, michalbiesek approved these changes
> Reviewed 1 of 129 files at r7.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/516)* status: 28 of 175 files reviewed, all discussions resolved (waiting on @michalbiesek)



<!-- Sent from Reviewable.io -->

2021-02-23 09:02 UTC, PatKamin reviewed
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/516)* status: 28 of 175 files reviewed, 1 unresolved discussion (waiting on @bratpiorka and @michalbiesek)

___
*[.clang-format, line 17 at r8](https://reviewable.io/reviews/memkind/memkind/516#-MUD7-IO76KdOoP-v-cH:-MUD7-IO76KdOoP-v-cI:bjpgfl6) ([raw file](https://github.com/memkind/memkind/blob/cf8d0b09ce72d0068124a5be1ed13deacfb88215/.clang-format#L17)):*
> ```YAML
>   AfterUnion: false
>   BeforeCatch: false
>   BeforeElse: false
> ```

BeforeWhile: false could be useful.


<!-- Sent from Reviewable.io -->

2021-03-01 07:28 UTC, merged