Feat tiering lib
memkind/memkind pull request #544
Opened 2021-02-26 11:40 UTC by bratpiorka

### Description

### Types of changes

- [ ] Bugfix (non-breaking change which fixes issue linked in Description above)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation (correction or otherwise)
- [ ] Cosmetics (whitespace, appearance)
- [ ] Other

### Checklist

- [x] Code compiles without errors
- [x] All tests pass locally with my changes (see TESTING section in CONTRIBUTING file)
- [x] Created tests which will fail without the change (if possible)
- [ ] Extended the README/documentation (if necessary)
- [x] All newly added files have proprietary license (if necessary)
- [ ] All newly added files are referenced in MANIFEST files (if necessary)

## Further comments

2021-02-26 11:50 UTC, bratpiorka reviewed
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/544)* status: 0 of 12 files reviewed, 7 unresolved discussions (waiting on @michalbiesek and @PatKamin)

___
*[MANIFEST, line 556 at r2](https://reviewable.io/reviews/memkind/memkind/544#-MUT8GwD094pJD71Qr8-:-MUT8GwD094pJD71Qr80:b-sjmjav) ([raw file](https://github.com/memkind/memkind/blob/ca61b922dc7d0087b981a75b118cbfa7b29d0ee5/MANIFEST#L556)):*
> ```
> test/trial_generator.cpp
> test/trial_generator.h
> tiering/Makefile.mk
> ```

I created separate folder for tiering lib - is this ok?
Also I noticed that main file of libmemtier.so will have the same name as in @michalbiesek commit "Add mockup for memkind_memtier" - we should probably rename either mine or Michal's file
___
*[Makefile.am, line 554 at r2](https://reviewable.io/reviews/memkind/memkind/544#-MUT8wcS57Ojo9CXqMV0:-MUT8wcS57Ojo9CXqMV1:b-c22iqa) ([raw file](https://github.com/memkind/memkind/blob/ca61b922dc7d0087b981a75b118cbfa7b29d0ee5/Makefile.am#L554)):*
> ```Makefile
> 
> unit_tests_tiering: tiering/libmemtier.la
> 	python3 -m pytest -s test/tiering-wip/tiering_tests.py
> ```

I call here python3 explicitly - this was a WA for problems with CI, but I also think that this is OK since the test is written in python3
___
*[memkind.spec.mk, line 133 at r2](https://reviewable.io/reviews/memkind/memkind/544#-MUT9CpuDpR0UyobEK8A:-MUT9CpuDpR0UyobEK8B:b-l7ahqq) ([raw file](https://github.com/memkind/memkind/blob/ca61b922dc7d0087b981a75b118cbfa7b29d0ee5/memkind.spec.mk#L133)):*
> ```Makefile
> %{__install} test/python_framework/*.py %{buildroot}/$(memkind_test_dir)/python_framework
> rm -f %{buildroot}$(memkind_test_dir)/libautohbw.*
> rm -f %{buildroot}$(memkind_test_dir)/libmemtier.*
> ```

I'm not sure about this changes but I don't know how to test them.
___
*[test/tiering-wip/README, line 1 at r2](https://reviewable.io/reviews/memkind/memkind/544#-MUT9JtL922nPFHdGhPR:-MUT9JtL922nPFHdGhPS:btpdybh) ([raw file](https://github.com/memkind/memkind/blob/ca61b922dc7d0087b981a75b118cbfa7b29d0ee5/test/tiering-wip/README#L1)):*
> ```
> * this folder contains tests used only for tiering-wip purposes
> ```

We should decide if we leave these tests (and whole tiering-wip folder) until final merge to master or don't merge them to FEAT branch at all. Notice that CI isn't enabled for FEAT branch yet (does it should be?)
___
*[test/tiering-wip/tiering_tests.py, line 7 at r2](https://reviewable.io/reviews/memkind/memkind/544#-MUT9id32-a4tsoigOaI:-MUT9id32-a4tsoigOaJ:b6djai1) ([raw file](https://github.com/memkind/memkind/blob/ca61b922dc7d0087b981a75b118cbfa7b29d0ee5/test/tiering-wip/tiering_tests.py#L7)):*
> ```Python
> import pytest
> import re
> from python_framework import CMD_helper
> ```

I use python_framework here and because this test is in separate folder I had to make copy of these module
___
*[test/tiering-wip/tiering_tests.py, line 14 at r2](https://reviewable.io/reviews/memkind/memkind/544#-MUT9suyCvlpT8q57Pxt:-MUT9suyCvlpT8q57Pxu:bf7579p) ([raw file](https://github.com/memkind/memkind/blob/ca61b922dc7d0087b981a75b118cbfa7b29d0ee5/test/tiering-wip/tiering_tests.py#L14)):*
> ```Python
>     utils_lib_path = "tiering/.libs/libmemtier.so"
>     ld_preload_env = "LD_PRELOAD=" + utils_lib_path
>     bin_path = "ls -l"
> ```

I choose ls -l because it calls all allocation funcions (malloc, calloc, realloc and free)
___
*[tiering/Makefile.mk, line 10 at r2](https://reviewable.io/reviews/memkind/memkind/544#-MUTA3EgDO2Wex1VJ8pp:-MUTA3EgDO2Wex1VJ8pq:b-x9b479) ([raw file](https://github.com/memkind/memkind/blob/ca61b922dc7d0087b981a75b118cbfa7b29d0ee5/tiering/Makefile.mk#L10)):*
> ```Makefile
> tiering_libmemtier_la_LDFLAGS = -rpath /nowhere
> 
> # TODO - handle debug version
> ```

do we want to have debug version of this library? if so I will add new story for this to JIRA


<!-- Sent from Reviewable.io -->

2021-02-26 12:30 UTC, PatKamin reviewed
> Reviewed 12 of 12 files at r1.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/544)* status: 10 of 12 files reviewed, 18 unresolved discussions (waiting on @bratpiorka, @michalbiesek, and @PatKamin)

___
*[test/tiering-wip/README, line 1 at r2](https://reviewable.io/reviews/memkind/memkind/544#-MUT9JtL922nPFHdGhPR:-MUTCv1Z-e8LI_nnK6pb:b9codp6) ([raw file](https://github.com/memkind/memkind/blob/ca61b922dc7d0087b981a75b118cbfa7b29d0ee5/test/tiering-wip/README#L1)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

We should decide if we leave these tests (and whole tiering-wip folder) until final merge to master or don't merge them to FEAT branch at all. Notice that CI isn't enabled for FEAT branch yet (does it should be?)
</blockquote></details>

I think we should leave these tests and modify them when mockups are implemented. There definitely should be CI running on feat branch.
___
*[test/tiering-wip/tiering_tests.py, line 5 at r1](https://reviewable.io/reviews/memkind/memkind/544#-MUTDbfJ4nbbGnPPdACt:-MUTDbfJ4nbbGnPPdACu:boeh5up) ([raw file](https://github.com/memkind/memkind/blob/624ac9ffb63b77a8279b377d35814feea4fe0608/test/tiering-wip/tiering_tests.py#L5)):*
> ```Python
> 
> import os
> import pytest
> ```

Add blank line between standard library modules and custom one.
___
*[test/tiering-wip/tiering_tests.py, line 58 at r1](https://reviewable.io/reviews/memkind/memkind/544#-MUTF3fWC2pPm1whaxDy:-MUTF3fWC2pPm1whaxDz:bcsfxyi) ([raw file](https://github.com/memkind/memkind/blob/624ac9ffb63b77a8279b377d35814feea4fe0608/test/tiering-wip/tiering_tests.py#L58)):*
> ```Python
>     def test_utils_log_level_debug(self):
>         # run command without LD_PRELOAD
>         default_output, retcode = self.cmd_helper.execute_cmd(self.bin_path)
> ```

`_` instead of `retcode` - `retcode` is not used
___
*[test/tiering-wip/tiering_tests.py, line 63 at r1](https://reviewable.io/reviews/memkind/memkind/544#-MUTF1HIEGLWf0khU942:-MUTF1HIEGLWf0khU943:bcsfxyi) ([raw file](https://github.com/memkind/memkind/blob/624ac9ffb63b77a8279b377d35814feea4fe0608/test/tiering-wip/tiering_tests.py#L63)):*
> ```Python
>         log_level_env = "MEMKIND_MEM_TIERING_LOG_LEVEL=2"
>         command = " ".join([self.ld_preload_env, log_level_env, self.bin_path])
>         output, retcode = self.cmd_helper.execute_cmd(command)
> ```

`_` instead of `retcode` - `retcode` is not used
___
*[test/tiering-wip/tiering_tests.py, line 78 at r1](https://reviewable.io/reviews/memkind/memkind/544#-MUTEy9H4svJf4ypJ-B8:-MUTEy9H4svJf4ypJ-B9:bcsfxyi) ([raw file](https://github.com/memkind/memkind/blob/624ac9ffb63b77a8279b377d35814feea4fe0608/test/tiering-wip/tiering_tests.py#L78)):*
> ```Python
>         log_level_env = "MEMKIND_MEM_TIERING_LOG_LEVEL=-1"
>         command = " ".join([self.ld_preload_env, log_level_env, self.bin_path])
>         output_level_neg, retcode = self.cmd_helper.execute_cmd(command)
> ```

`_` instead of `retcode` - `retcode` is not used
___
*[test/tiering-wip/tiering_tests.py, line 86 at r1](https://reviewable.io/reviews/memkind/memkind/544#-MUTEooE1AZ2Aom7reQu:-MUTEooE1AZ2Aom7reQv:bcsfxyi) ([raw file](https://github.com/memkind/memkind/blob/624ac9ffb63b77a8279b377d35814feea4fe0608/test/tiering-wip/tiering_tests.py#L86)):*
> ```Python
>         log_level_env = "MEMKIND_MEM_TIERING_LOG_LEVEL=4"
>         command = " ".join([self.ld_preload_env, log_level_env, self.bin_path])
>         output_level_neg, retcode = self.cmd_helper.execute_cmd(command)
> ```

`_` instead of `retcode` - `retcode` is not used
___
*[test/tiering-wip/tiering_tests.py, line 14 at r2](https://reviewable.io/reviews/memkind/memkind/544#-MUT9suyCvlpT8q57Pxt:-MUTDlps4yXgzG2winee:bd9t6dg) ([raw file](https://github.com/memkind/memkind/blob/ca61b922dc7d0087b981a75b118cbfa7b29d0ee5/test/tiering-wip/tiering_tests.py#L14)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

I choose ls -l because it calls all allocation funcions (malloc, calloc, realloc and free)
</blockquote></details>

I see that there is `ls`, not `ls -l`
___
*[test/tiering-wip/python_framework/__init__.py, line 1 at r1](https://reviewable.io/reviews/memkind/memkind/544#-MUTFbKR47-SDKO7QEEA:-MUTFbKSBsK3qE9XUgZe:bzfqctp) ([raw file](https://github.com/memkind/memkind/blob/624ac9ffb63b77a8279b377d35814feea4fe0608/test/tiering-wip/python_framework/__init__.py#L1)):*
> ```Python
> # SPDX-License-Identifier: BSD-2-Clause
> ```

Most probably file not needed.
___
*[test/tiering-wip/python_framework/cmd_helper.py, line 7 at r1](https://reviewable.io/reviews/memkind/memkind/544#-MUTFiHr0mdj3iwLKdj6:-MUTFiHs2i7ga6NHjfKv:bkycap1) ([raw file](https://github.com/memkind/memkind/blob/624ac9ffb63b77a8279b377d35814feea4fe0608/test/tiering-wip/python_framework/cmd_helper.py#L7)):*
> ```Python
> import os
> import tempfile
> import subprocess
> ```

Alphabetical order, please.
___
*[test/tiering-wip/python_framework/cmd_helper.py, line 13 at r1](https://reviewable.io/reviews/memkind/memkind/544#-MUTH14n2A8FLxc7T2NL:-MUTH14oDALthpkHxuUv:b-de9xil) ([raw file](https://github.com/memkind/memkind/blob/624ac9ffb63b77a8279b377d35814feea4fe0608/test/tiering-wip/python_framework/cmd_helper.py#L13)):*
> ```Python
>     def execute_cmd(self, command, sudo=False):
>         if sudo:
>             command = "sudo {0}".format(command)
> ```

Use f-string, please, it's easier to read.
___
*[test/tiering-wip/python_framework/cmd_helper.py, line 31 at r1](https://reviewable.io/reviews/memkind/memkind/544#-MUTIMdh9ln9MNaWsHTZ:-MUTIMdjAq8mNniLVvB7:bfr5hxb) ([raw file](https://github.com/memkind/memkind/blob/624ac9ffb63b77a8279b377d35814feea4fe0608/test/tiering-wip/python_framework/cmd_helper.py#L31)):*
> ```Python
>         return stdout.decode("utf-8"), retcode
> 
>     def get_command_path(self, binary):
> ```

Not used.
___
*[test/tiering-wip/python_framework/huge_page_organizer.py, line 6 at r1](https://reviewable.io/reviews/memkind/memkind/544#-MUTIP9s6llzZDjvA3I2:-MUTIP9s6llzZDjvA3I3:b-xe5810) ([raw file](https://github.com/memkind/memkind/blob/624ac9ffb63b77a8279b377d35814feea4fe0608/test/tiering-wip/python_framework/huge_page_organizer.py#L6)):*
> ```Python
> from python_framework.cmd_helper import CMD_helper
> import os
> import itertools
> ```

Alphabetical order, please. Separate custom module with a blank line.
___
*[tiering/memtier.c, line 45 at r1](https://reviewable.io/reviews/memkind/memkind/544#-MUTJ467DJDVyedR9WrO:-MUTJ467DJDVyedR9WrP:bgjg8n) ([raw file](https://github.com/memkind/memkind/blob/624ac9ffb63b77a8279b377d35814feea4fe0608/tiering/memtier.c#L45)):*
> ```C
> }
> 
> void log_generic(message_type_t type, const char *format, va_list args);
> ```

I think this whole log handling functions should be in a separate file. @michalbiesek , @bratpiorka , what do you think?


<!-- Sent from Reviewable.io -->

2021-02-26 12:31 UTC, PatKamin reviewed
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/544)* status: all files reviewed, 18 unresolved discussions (waiting on @bratpiorka and @michalbiesek)



<!-- Sent from Reviewable.io -->

2021-02-26 13:37 UTC, michalbiesek requested changes
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/544)* status: 10 of 12 files reviewed, 25 unresolved discussions (waiting on @bratpiorka and @PatKamin)

___
*[Makefile.am, line 554 at r2](https://reviewable.io/reviews/memkind/memkind/544#-MUT8wcS57Ojo9CXqMV0:-MUTBzqX5t-oY_DP4DKa:bxh6vec) ([raw file](https://github.com/memkind/memkind/blob/ca61b922dc7d0087b981a75b118cbfa7b29d0ee5/Makefile.am#L554)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

I call here python3 explicitly - this was a WA for problems with CI, but I also think that this is OK since the test is written in python3
</blockquote></details>

Why can't the code itself be compatible with python2 as well? what is the stopper here?
___
*[memkind.spec.mk, line 133 at r2](https://reviewable.io/reviews/memkind/memkind/544#-MUT9CpuDpR0UyobEK8A:-MUTT8WhDvBA5SZHHbZk:bxbt9so) ([raw file](https://github.com/memkind/memkind/blob/ca61b922dc7d0087b981a75b118cbfa7b29d0ee5/memkind.spec.mk#L133)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

I'm not sure about this changes but I don't know how to test them.
</blockquote></details>

build rpm
___
*[test/tiering-wip/tiering_tests.py, line 3 at r1](https://reviewable.io/reviews/memkind/memkind/544#-MUTUSwN95VOOmR92nmq:-MUTUSwN95VOOmR92nmr:b-cc3gyk) ([raw file](https://github.com/memkind/memkind/blob/624ac9ffb63b77a8279b377d35814feea4fe0608/test/tiering-wip/tiering_tests.py#L3)):*
> ```Python
> # SPDX-License-Identifier: BSD-2-Clause
> # Copyright (C) 2021 Intel Corporation.
> ```

Makefile.am Manifest files?
___
*[test/tiering-wip/tiering_tests.py, line 11 at r1](https://reviewable.io/reviews/memkind/memkind/544#-MUTRU5PDtXKcQm2NkAK:-MUTRU5QCCY0kDgIhBfu:b-50omrr) ([raw file](https://github.com/memkind/memkind/blob/624ac9ffb63b77a8279b377d35814feea4fe0608/test/tiering-wip/tiering_tests.py#L11)):*
> ```
>     utils_lib_path = "tiering/.libs/libmemtier.so"
>     ld_preload_env = "LD_PRELOAD=" + utils_lib_path
> ```
merge into one
___
*[test/tiering-wip/tiering_tests.py, line 34 at r1](https://reviewable.io/reviews/memkind/memkind/544#-MUTSmJ60d5FNkfP-K5Y:-MUTSmJ73B2c5zGLQ9nS:b-izcnwe) ([raw file](https://github.com/memkind/memkind/blob/624ac9ffb63b77a8279b377d35814feea4fe0608/test/tiering-wip/tiering_tests.py#L34)):*
> ```Python
>         rest_output = "\n".join(output.split("\n")[1:])
>         assert rest_output == default_output, "Bad command output"
> ```

run some linter on python files like flake8
___
*[test/tiering-wip/tiering_tests.py, line 7 at r2](https://reviewable.io/reviews/memkind/memkind/544#-MUT9id32-a4tsoigOaI:-MUTCGgp6fJP_XtSyrlE:b2hg3w7) ([raw file](https://github.com/memkind/memkind/blob/ca61b922dc7d0087b981a75b118cbfa7b29d0ee5/test/tiering-wip/tiering_tests.py#L7)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

I use python_framework here and because this test is in separate folder I had to make copy of these module
</blockquote></details>

Why not move tiering_test.py in the test directory - this could avoid these python files related to hugepage/cmd copy/paste what's the reason to keep in a separate directory?
___
*[tiering/memtier.c, line 7 at r1](https://reviewable.io/reviews/memkind/memkind/544#-MUTUnRR8m7m8SqkVf5t:-MUTUnRS73fZtP_YUyoW:b-65t1op) ([raw file](https://github.com/memkind/memkind/blob/624ac9ffb63b77a8279b377d35814feea4fe0608/tiering/memtier.c#L7)):*
> ```C
> 
> #include <assert.h>
> #include <errno.h>
> ```

add manual (template at least) for this library
___
*[tiering/memtier.c, line 14 at r1](https://reviewable.io/reviews/memkind/memkind/544#-MUTSIY5Eg7NdQykGoNk:-MUTSIY5Eg7NdQykGoNl:b-67gsez) ([raw file](https://github.com/memkind/memkind/blob/624ac9ffb63b77a8279b377d35814feea4fe0608/tiering/memtier.c#L14)):*
> ```
> #define UTILS_EXPORT __attribute__((visibility("default")))
> #define UTILS_INIT   __attribute__((constructor))
> #define UTILS_FINI   __attribute__((destructor))
> ```
macro naming should be more related to the module itself
___
*[tiering/memtier.c, line 45 at r1](https://reviewable.io/reviews/memkind/memkind/544#-MUTJ467DJDVyedR9WrO:-MUTVDKbEiIq7cfjSUlL:b-8ayu6x) ([raw file](https://github.com/memkind/memkind/blob/624ac9ffb63b77a8279b377d35814feea4fe0608/tiering/memtier.c#L45)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

I think this whole log handling functions should be in a separate file. @michalbiesek , @bratpiorka , what do you think?
</blockquote></details>

Agree
___
*[tiering/memtier.c, line 105 at r1](https://reviewable.io/reviews/memkind/memkind/544#-MUTRqTa8UeZ_yCQGG1Q:-MUTRqTa8UeZ_yCQGG1R:b-b5a09i) ([raw file](https://github.com/memkind/memkind/blob/624ac9ffb63b77a8279b377d35814feea4fe0608/tiering/memtier.c#L105)):*
> ```
>     fprintf(stderr, "%s: ", message_prefixes[type]);
>     vfprintf(stderr, format, args);
>     fprintf(stderr, "\n");
> ```
This allocates memory, right? As it was already said it please use a function that avoids buffer allocation see:
https://www.gnu.org/software/libc/manual/html_node/Hooks-for-Malloc.html (print comment) since this will be used for malloc interception
___
*[tiering/memtier.c, line 117 at r4](https://reviewable.io/reviews/memkind/memkind/544#-MUTY7WqCei2yuVMqdtE:-MUTY7WqCei2yuVMqdtF:b-wwdl58) ([raw file](https://github.com/memkind/memkind/blob/8cd1a0bba476a775750fad96a28f367d7a9c67e9/tiering/memtier.c#L117)):*
> ```
> __libc_free
> ```
__libc_memalign ?


<!-- Sent from Reviewable.io -->

2021-02-26 16:28 UTC, PatKamin reviewed
> Reviewed 11 of 12 files at r5.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/544)* status: 8 of 10 files reviewed, 19 unresolved discussions (waiting on @bratpiorka and @PatKamin)



<!-- Sent from Reviewable.io -->

2021-03-01 09:44 UTC, michalbiesek requested changes
> Reviewed 3 of 12 files at r5.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/544)* status: 3 of 12 files reviewed, 17 unresolved discussions (waiting on @bratpiorka and @PatKamin)

___
*[tiering/Makefile.mk, line 8 at r5](https://reviewable.io/reviews/memkind/memkind/544#-MUgiXSE4mJo-9LXBOHb:-MUgiXSE4mJo-9LXBOHc:b8hgjcy) ([raw file](https://github.com/memkind/memkind/blob/3d4b76d69da56914eb7969e338dd25d2ba129441/tiering/Makefile.mk#L8)):*
> ```
> -rpath /nowhere
> ```
is this needed?
___
*[tiering/memtier.c, line 24 at r5](https://reviewable.io/reviews/memkind/memkind/544#-MUgi_1T0dcdpgbYUsGB:-MUgi_1T0dcdpgbYUsGC:b33ugt4) ([raw file](https://github.com/memkind/memkind/blob/3d4b76d69da56914eb7969e338dd25d2ba129441/tiering/memtier.c#L24)):*
> ```
> %u
> ```
%zu is correct specifier for size_t - update everywhere
___
*[tiering/memtier.c, line 4 at r8](https://reviewable.io/reviews/memkind/memkind/544#-MUh9Xlp1aD1-8lvpMv4:-MUh9Xlp1aD1-8lvpMv5:bkgw8ah) ([raw file](https://github.com/memkind/memkind/blob/a8be3ef0ff138bb9b688a2c4c7f5aa0949722092/tiering/memtier.c#L4)):*
> ```
> #include "../config.h"
> ```
is this needed?
___
*[tiering/memtier.c, line 20 at r8](https://reviewable.io/reviews/memkind/memkind/544#-MUh9qOa7TrXUrHLWvqv:-MUh9qOa7TrXUrHLWvqw:b-2r3n9a) ([raw file](https://github.com/memkind/memkind/blob/a8be3ef0ff138bb9b688a2c4c7f5aa0949722092/tiering/memtier.c#L20)):*
> ```
> void MEMTIER_EXPORT *
> ```
please keep this more readable:
MEMTIER_EXPORT void *
now you break the return type
___
*[tiering/memtier_log.h, line 14 at r5](https://reviewable.io/reviews/memkind/memkind/544#-MUgirG72EbtgYfFIJOT:-MUgirG72EbtgYfFIJOU:b-bzi5e8) ([raw file](https://github.com/memkind/memkind/blob/3d4b76d69da56914eb7969e338dd25d2ba129441/tiering/memtier_log.h#L14)):*
> ```
> void log_generic(message_type_t type, const char *format, va_list args);
> ```
no need to expose this - make it static and remove it from the memtier_log.h.
___
*[tiering/memtier_log.c, line 5 at r7](https://reviewable.io/reviews/memkind/memkind/544#-MUh9bEgBxJCd7-8fysW:-MUh9bEgBxJCd7-8fysX:b-3zscgd) ([raw file](https://github.com/memkind/memkind/blob/2e27e6d5a2fedb66952e8ca8bdbddd8be4805184/tiering/memtier_log.c#L5)):*
<details><summary><i alt="summary">Quoted 9 lines of code…</i></summary>

> ```
> #include "../config.h"
> #include <assert.h>
> #include <errno.h>
> #include <limits.h>
> #include <malloc.h>
> #include <pthread.h>
> #include <stdarg.h>
> #include <stdio.h>
> #include <stdlib.h>
> ```
</details>

Please verify if all the includes are needed
___
*[test/tiering-wip/tiering_tests.py, line 14 at r2](https://reviewable.io/reviews/memkind/memkind/544#-MUT9suyCvlpT8q57Pxt:-MUghmjn6YpBcdOqhhWy:bhgsh7n) ([raw file](https://github.com/memkind/memkind/blob/ca61b922dc7d0087b981a75b118cbfa7b29d0ee5/test/tiering-wip/tiering_tests.py#L14)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

I see that there is `ls`, not `ls -l`
</blockquote></details>

By calling an external program (ls) to test your malloc shim library- you depend on its implementation - in other words, you don't have any control over which function you test it.
IMHO there should be some helpful binary maintain by us to test explicitly malloc/realloc and all the other function which are tested here


<!-- Sent from Reviewable.io -->

2021-03-01 10:13 UTC, PatKamin reviewed
> Reviewed 9 of 9 files at r7.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/544)* status: 10 of 12 files reviewed, 17 unresolved discussions (waiting on @bratpiorka, @michalbiesek, and @PatKamin)

___
*[test/tiering-wip/tiering_tests.py, line 34 at r1](https://reviewable.io/reviews/memkind/memkind/544#-MUTSmJ60d5FNkfP-K5Y:-MUhGV8p0GmrRSmXZQsY:b32v57) ([raw file](https://github.com/memkind/memkind/blob/624ac9ffb63b77a8279b377d35814feea4fe0608/test/tiering-wip/tiering_tests.py#L34)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

run some linter on python files like flake8
</blockquote></details>

+1


<!-- Sent from Reviewable.io -->

2021-03-01 10:21 UTC, bratpiorka reviewed
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/544)* status: 7 of 12 files reviewed, 15 unresolved discussions (waiting on @bratpiorka, @kilobyte, @michalbiesek, and @PatKamin)

___
*[test/tiering-wip/README, line 1 at r2](https://reviewable.io/reviews/memkind/memkind/544#-MUT9JtL922nPFHdGhPR:-MUTs-b52uBvJeGtgSHU:b-540jn7) ([raw file](https://github.com/memkind/memkind/blob/ca61b922dc7d0087b981a75b118cbfa7b29d0ee5/test/tiering-wip/README#L1)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

I think we should leave these tests and modify them when mockups are implemented. There definitely should be CI running on feat branch.
</blockquote></details>

I left "tiering_tests.py" but I moved it to test/ folder and removed whole test/tiering-wip including this file
___
*[test/tiering-wip/python_framework/__init__.py, line 1 at r1](https://reviewable.io/reviews/memkind/memkind/544#-MUTFbKR47-SDKO7QEEA:-MUTrmr9EOnkBeAek2PC:bntv4u9) ([raw file](https://github.com/memkind/memkind/blob/624ac9ffb63b77a8279b377d35814feea4fe0608/test/tiering-wip/python_framework/__init__.py#L1)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Most probably file not needed.
</blockquote></details>

file removed
___
*[test/tiering-wip/python_framework/cmd_helper.py, line 7 at r1](https://reviewable.io/reviews/memkind/memkind/544#-MUTFiHr0mdj3iwLKdj6:-MUTrpaJ8JmPBPfe25sW:buuzgcd) ([raw file](https://github.com/memkind/memkind/blob/624ac9ffb63b77a8279b377d35814feea4fe0608/test/tiering-wip/python_framework/cmd_helper.py#L7)):*
> p
file removed
___
*[test/tiering-wip/python_framework/cmd_helper.py, line 13 at r1](https://reviewable.io/reviews/memkind/memkind/544#-MUTH14n2A8FLxc7T2NL:-MUTrqHwCP8-FbL-yEWW:bntv4u9) ([raw file](https://github.com/memkind/memkind/blob/624ac9ffb63b77a8279b377d35814feea4fe0608/test/tiering-wip/python_framework/cmd_helper.py#L13)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Use f-string, please, it's easier to read.
</blockquote></details>

file removed
___
*[test/tiering-wip/python_framework/cmd_helper.py, line 31 at r1](https://reviewable.io/reviews/memkind/memkind/544#-MUTIMdh9ln9MNaWsHTZ:-MUTrqcI6Ki69WZoKTQ_:bntv4u9) ([raw file](https://github.com/memkind/memkind/blob/624ac9ffb63b77a8279b377d35814feea4fe0608/test/tiering-wip/python_framework/cmd_helper.py#L31)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Not used.
</blockquote></details>

file removed
___
*[test/tiering-wip/python_framework/huge_page_organizer.py, line 6 at r1](https://reviewable.io/reviews/memkind/memkind/544#-MUTIP9s6llzZDjvA3I2:-MUTrr8i2rp5K280OWJE:bntv4u9) ([raw file](https://github.com/memkind/memkind/blob/624ac9ffb63b77a8279b377d35814feea4fe0608/test/tiering-wip/python_framework/huge_page_organizer.py#L6)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Alphabetical order, please. Separate custom module with a blank line.
</blockquote></details>

file removed
___
*[tiering/Makefile.mk, line 8 at r5](https://reviewable.io/reviews/memkind/memkind/544#-MUgiXSE4mJo-9LXBOHb:-MUhEOp48aE2yosGsRaj:bih37md) ([raw file](https://github.com/memkind/memkind/blob/3d4b76d69da56914eb7969e338dd25d2ba129441/tiering/Makefile.mk#L8)):*
> ```
> tiering_libmemtier_la_LDFLAGS = -rpath /nowhere
> ```

I'm not sure how this works, but without this, make doesn't create .so library
___
*[tiering/memtier.c, line 7 at r1](https://reviewable.io/reviews/memkind/memkind/544#-MUTUnRR8m7m8SqkVf5t:-MUgqzB10ywqUqqAHdbs:bte8a78) ([raw file](https://github.com/memkind/memkind/blob/624ac9ffb63b77a8279b377d35814feea4fe0608/tiering/memtier.c#L7)):*
> This allocates memory, right? As it was already said it please use a function that avoids buffer allocation see:
> https://www.gnu.org/software/libc/manual/html_node/Hooks-for-Malloc.html (print comment) since this will be used for malloc interception

done - see man/memtier.7
___
*[tiering/memtier.c, line 14 at r1](https://reviewable.io/reviews/memkind/memkind/544#-MUTSIY5Eg7NdQykGoNk:-MUTrtHb5w_tJ6nSOZ-h:b-5kb4ex) ([raw file](https://github.com/memkind/memkind/blob/624ac9ffb63b77a8279b377d35814feea4fe0608/tiering/memtier.c#L14)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> #define UTILS_EXPORT __attribute__((visibility("default")))
> #define UTILS_INIT   __attribute__((constructor))
> #define UTILS_FINI   __attribute__((destructor))
> ```
macro naming should be more related to the module itself
</blockquote></details>

Done - used MEMTIER_EXPORT etc
___
*[tiering/memtier.c, line 45 at r1](https://reviewable.io/reviews/memkind/memkind/544#-MUTJ467DJDVyedR9WrO:-MUTrw1QBKhd2xS-uKpa:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/624ac9ffb63b77a8279b377d35814feea4fe0608/tiering/memtier.c#L45)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

Agree
</blockquote></details>

Done.
___
*[tiering/memtier.c, line 105 at r1](https://reviewable.io/reviews/memkind/memkind/544#-MUTRqTa8UeZ_yCQGG1Q:-MUhBQ-k3GgwNjlL5NsM:baui1hl) ([raw file](https://github.com/memkind/memkind/blob/624ac9ffb63b77a8279b377d35814feea4fe0608/tiering/memtier.c#L105)):*
> args

As @kilobyte checked fprintf/vfprintf doesn't use malloc, at least for formats that we use. 
___
*[tiering/memtier.c, line 117 at r4](https://reviewable.io/reviews/memkind/memkind/544#-MUTY7WqCei2yuVMqdtE:-MUTrx-5-0XWJ7gErcCv:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/8cd1a0bba476a775750fad96a28f367d7a9c67e9/tiering/memtier.c#L117)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> __libc_free
> ```
__libc_memalign ?
</blockquote></details>

Done.
___
*[tiering/memtier.c, line 24 at r5](https://reviewable.io/reviews/memkind/memkind/544#-MUgi_1T0dcdpgbYUsGB:-MUhEphg416gQHUAhjDS:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/3d4b76d69da56914eb7969e338dd25d2ba129441/tiering/memtier.c#L24)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> %u
> ```
%zu is correct specifier for size_t - update everywhere
</blockquote></details>

Done.
___
*[tiering/memtier.c, line 4 at r8](https://reviewable.io/reviews/memkind/memkind/544#-MUh9Xlp1aD1-8lvpMv4:-MUhFvDo4cAzIuyHpaQV:b-j2m3r9) ([raw file](https://github.com/memkind/memkind/blob/a8be3ef0ff138bb9b688a2c4c7f5aa0949722092/tiering/memtier.c#L4)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> #include "../config.h"
> ```
is this needed?
</blockquote></details>

not - removed
___
*[tiering/memtier.c, line 20 at r8](https://reviewable.io/reviews/memkind/memkind/544#-MUh9qOa7TrXUrHLWvqv:-MUhIYcZ8hEiEtp3HySr:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/a8be3ef0ff138bb9b688a2c4c7f5aa0949722092/tiering/memtier.c#L20)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> void MEMTIER_EXPORT *
> ```
please keep this more readable:
MEMTIER_EXPORT void *
now you break the return type
</blockquote></details>

Done.
___
*[tiering/memtier_log.h, line 14 at r5](https://reviewable.io/reviews/memkind/memkind/544#-MUgirG72EbtgYfFIJOT:-MUhF2RB13KkznstPN0S:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/3d4b76d69da56914eb7969e338dd25d2ba129441/tiering/memtier_log.h#L14)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> void log_generic(message_type_t type, const char *format, va_list args);
> ```
no need to expose this - make it static and remove it from the memtier_log.h.
</blockquote></details>

Done.
___
*[tiering/memtier_log.c, line 5 at r7](https://reviewable.io/reviews/memkind/memkind/544#-MUh9bEgBxJCd7-8fysW:-MUhFbUmAMmZ0bNWZicH:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/2e27e6d5a2fedb66952e [...]

2021-03-01 10:24 UTC, PatKamin reviewed
> Reviewed 1 of 2 files at r8, 4 of 5 files at r9.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/544)* status: 9 of 12 files reviewed, 20 unresolved discussions (waiting on @bratpiorka, @kilobyte, @michalbiesek, and @PatKamin)

___
*[tiering/memtier_log.c, line 28 at r9](https://reviewable.io/reviews/memkind/memkind/544#-MUhJ0KAAOJMsJRZeV2s:-MUhJ0KAAOJMsJRZeV2t:bws4vbk) ([raw file](https://github.com/memkind/memkind/blob/6f87ed4c56fd902a246622dba59de8988bc3b0c2/tiering/memtier_log.c#L28)):*
> ```C
> }
> 
> static void log_generic(message_type_t type, const char *format, va_list args);
> ```

nit: The implementation can be placed here, just below `log_lock` variable.
___
*[test/tiering_tests.py, line 33 at r8](https://reviewable.io/reviews/memkind/memkind/544#-MUhHGBwDjzH80oalbLU:-MUhHGBwDjzH80oalbLV:bxnh95w) ([raw file](https://github.com/memkind/memkind/blob/a8be3ef0ff138bb9b688a2c4c7f5aa0949722092/test/tiering_tests.py#L33)):*
> ```Python
> 
>         # run command without LD_PRELOAD
>         default_output, ls_retcode = self.cmd_helper.execute_cmd(self.bin_path)
> ```

Check for ls_retcode.
___
*[test/tiering_tests.py, line 57 at r9](https://reviewable.io/reviews/memkind/memkind/544#-MUhHsWw80Ak3iwitePL:-MUhHsWw80Ak3iwitePM:bmv6xkf) ([raw file](https://github.com/memkind/memkind/blob/6f87ed4c56fd902a246622dba59de8988bc3b0c2/test/tiering_tests.py#L57)):*
> ```Python
>         output_level_0 = self.cmd_helper.execute_cmd(command)
> 
>         assert output_level_0 == default_output, "Bad command output"
> ```

Misleading message. You check here both for output equality and for retcode equality.
___
*[test/tiering_tests.py, line 67 at r9](https://reviewable.io/reviews/memkind/memkind/544#-MUhIDXq9sUVcQ8zx-dp:-MUhIDXq9sUVcQ8zx-dq:brhumzt) ([raw file](https://github.com/memkind/memkind/blob/6f87ed4c56fd902a246622dba59de8988bc3b0c2/test/tiering_tests.py#L67)):*
> ```Python
>         output = self.cmd_helper.execute_cmd(command)
> 
>         assert output == default_output, "Bad command output"
> ```

Same here.
___
*[test/tiering_tests.py, line 71 at r9](https://reviewable.io/reviews/memkind/memkind/544#-MUhIKhy04TL-FppeqUS:-MUhIKhy04TL-FppeqUT:b-wamz9h) ([raw file](https://github.com/memkind/memkind/blob/6f87ed4c56fd902a246622dba59de8988bc3b0c2/test/tiering_tests.py#L71)):*
> ```Python
>     def test_utils_log_level_debug(self):
>         # run command without LD_PRELOAD
>         default_output, retcode = self.cmd_helper.execute_cmd(self.bin_path)
> ```

Either check for this retcode or use dummy `_` instead. Same in other places.


<!-- Sent from Reviewable.io -->

2021-03-01 10:28 UTC, PatKamin reviewed
> Reviewed 1 of 5 files at r9, 2 of 2 files at r10.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/544)* status: all files reviewed, 20 unresolved discussions (waiting on @bratpiorka, @kilobyte, @michalbiesek, and @PatKamin)



<!-- Sent from Reviewable.io -->

2021-03-01 11:40 UTC, michalbiesek requested changes
> Reviewed 1 of 9 files at r7.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/544)* status: 8 of 12 files reviewed, 15 unresolved discussions (waiting on @bratpiorka, @kilobyte, @michalbiesek, and @PatKamin)

___
*[tiering/Makefile.mk, line 4 at r12](https://reviewable.io/reviews/memkind/memkind/544#-MUhYmsdCiXxg5RTWZzQ:-MUhYmse6unpc60WiBe8:bke1s61) ([raw file](https://github.com/memkind/memkind/blob/3e84933e95430a9c000e685c60debffb51788cb5/tiering/Makefile.mk#L4)):*
> ```
> noinst
> ```
https://www.gnu.org/software/automake/manual/html_node/Uniform.html
"The special prefix ‘noinst_’  ...."
___
*[tiering/memtier_log.c, line 30 at r9](https://reviewable.io/reviews/memkind/memkind/544#-MUhOVl79Hr4vFCnekFm:-MUhOVl79Hr4vFCnekFn:bcv7inc) ([raw file](https://github.com/memkind/memkind/blob/6f87ed4c56fd902a246622dba59de8988bc3b0c2/tiering/memtier_log.c#L30)):*
> ```
> size_t
> ```
unsigned I believe you don't need 64bits for this enum
___
*[tiering/memtier_log.c, line 78 at r9](https://reviewable.io/reviews/memkind/memkind/544#-MUhOSNz6T0Dv6iLUidC:-MUhOSNz6T0Dv6iLUidD:bkvbpyo) ([raw file](https://github.com/memkind/memkind/blob/6f87ed4c56fd902a246622dba59de8988bc3b0c2/tiering/memtier_log.c#L78)):*
> ```
> d
> ```
u
___
*[test/tiering-wip/tiering_tests.py, line 14 at r2](https://reviewable.io/reviews/memkind/memkind/544#-MUT9suyCvlpT8q57Pxt:-MUhIxZ8-fTmvq8lGlAA:b-6qcl4v) ([raw file](https://github.com/memkind/memkind/blob/ca61b922dc7d0087b981a75b118cbfa7b29d0ee5/test/tiering-wip/tiering_tests.py#L14)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

@michalbiesek - agree. Can we do it in separate PR/JIRA story?
</blockquote></details>

Fine, please add here TODO and create PR for that.


<!-- Sent from Reviewable.io -->

2021-03-01 12:15 UTC, bratpiorka reviewed
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/544)* status: 7 of 12 files reviewed, 12 unresolved discussions (waiting on @kilobyte, @michalbiesek, and @PatKamin)

___
*[tiering/Makefile.mk, line 4 at r12](https://reviewable.io/reviews/memkind/memkind/544#-MUhYmsdCiXxg5RTWZzQ:-MUhhDGZ-89YQi1D_EYZ:bojs4zg) ([raw file](https://github.com/memkind/memkind/blob/3e84933e95430a9c000e685c60debffb51788cb5/tiering/Makefile.mk#L4)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> noinst
> ```
https://www.gnu.org/software/automake/manual/html_node/Uniform.html
"The special prefix ‘noinst_’  ...."
</blockquote></details>

thanks, now rpm is built correctly
___
*[tiering/memtier_log.c, line 30 at r9](https://reviewable.io/reviews/memkind/memkind/544#-MUhOVl79Hr4vFCnekFm:-MUhb_6H2wptVTkW54ms:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/6f87ed4c56fd902a246622dba59de8988bc3b0c2/tiering/memtier_log.c#L30)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> size_t
> ```
unsigned I believe you don't need 64bits for this enum
</blockquote></details>

Done.
___
*[tiering/memtier_log.c, line 78 at r9](https://reviewable.io/reviews/memkind/memkind/544#-MUhOSNz6T0Dv6iLUidC:-MUhb6S25svqzJik_5z3:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/6f87ed4c56fd902a246622dba59de8988bc3b0c2/tiering/memtier_log.c#L78)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> d
> ```
u
</blockquote></details>

Done.
___
*[test/tiering_tests.py, line 33 at r8](https://reviewable.io/reviews/memkind/memkind/544#-MUhHGBwDjzH80oalbLU:-MUhLgTj4aOeRCKHC3zx:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/a8be3ef0ff138bb9b688a2c4c7f5aa0949722092/test/tiering_tests.py#L33)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Check for ls_retcode.
</blockquote></details>

Done.
___
*[test/tiering_tests.py, line 57 at r9](https://reviewable.io/reviews/memkind/memkind/544#-MUhHsWw80Ak3iwitePL:-MUhMLs5Dp_Lh_vO1uuB:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/6f87ed4c56fd902a246622dba59de8988bc3b0c2/test/tiering_tests.py#L57)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Misleading message. You check here both for output equality and for retcode equality.
</blockquote></details>

Done.
___
*[test/tiering_tests.py, line 67 at r9](https://reviewable.io/reviews/memkind/memkind/544#-MUhIDXq9sUVcQ8zx-dp:-MUhMcUeEM1YrUBZDRHa:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/6f87ed4c56fd902a246622dba59de8988bc3b0c2/test/tiering_tests.py#L67)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Same here.
</blockquote></details>

Done.
___
*[test/tiering_tests.py, line 71 at r9](https://reviewable.io/reviews/memkind/memkind/544#-MUhIKhy04TL-FppeqUS:-MUhPB7o3O9Th8Td4RXi:b6dwdxg) ([raw file](https://github.com/memkind/memkind/blob/6f87ed4c56fd902a246622dba59de8988bc3b0c2/test/tiering_tests.py#L71)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Either check for this retcode or use dummy `_` instead. Same in other places.
</blockquote></details>

ok, I decided for testing of output+retcode for default binary only in *_init, *_default and *_not_set tests. In rest I used dummy _


<!-- Sent from Reviewable.io -->

2021-03-01 12:22 UTC, michalbiesek requested changes
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/544)* status: 7 of 12 files reviewed, 10 unresolved discussions (waiting on @bratpiorka, @kilobyte, and @PatKamin)

___
*[tiering/Makefile.mk, line 10 at r2](https://reviewable.io/reviews/memkind/memkind/544#-MUTA3EgDO2Wex1VJ8pp:-MUhfioJ3wny79O_nyyH:b-i2f8c2) ([raw file](https://github.com/memkind/memkind/blob/ca61b922dc7d0087b981a75b118cbfa7b29d0ee5/tiering/Makefile.mk#L10)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

do we want to have debug version of this library? if so I will add new story for this to JIRA
</blockquote></details>

IMHO this is not currently needed.
___
*[tiering/memtier_log.h, line 5 at r13](https://reviewable.io/reviews/memkind/memkind/544#-MUhgGlmAflYnqtmxbJV:-MUhgGlmAflYnqtmxbJW:bgj4ye0) ([raw file](https://github.com/memkind/memkind/blob/d338e72e7d1238443405d3ef3702892cae991f3a/tiering/memtier_log.h#L5)):*
> ```objc
> 
> #include <stdio.h>
> ```

#pragma once
#ifdef __cplusplus
extern "C" {
#endif
___
*[tiering/memtier_log.h, line 17 at r13](https://reviewable.io/reviews/memkind/memkind/544#-MUhgIbT4bEzTVQFcgvV:-MUhgIbT4bEzTVQFcgvW:bz9danf) ([raw file](https://github.com/memkind/memkind/blob/d338e72e7d1238443405d3ef3702892cae991f3a/tiering/memtier_log.h#L17)):*
> ```objc
> void log_err(const char *format, ...);
> void log_debug(const char *format, ...);
> void log_init_once(void);
> ```

#ifdef __cplusplus
}
#endif


<!-- Sent from Reviewable.io -->

2021-03-01 12:24 UTC, michalbiesek reviewed
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/544)* status: 7 of 12 files reviewed, 11 unresolved discussions (waiting on @bratpiorka, @kilobyte, and @PatKamin)

___
*[tiering/memtier_log.c, line 13 at r14](https://reviewable.io/reviews/memkind/memkind/544#-MUhjlXE9-BYsnWQdvAB:-MUhjlXE9-BYsnWQdvAC:b-ywqsxf) ([raw file](https://github.com/memkind/memkind/blob/5ad46959b5b3baf34ecea678a191403013e03596/tiering/memtier_log.c#L13)):*
> ```
> static char *
> ```
nit: static const char*


<!-- Sent from Reviewable.io -->

2021-03-01 12:28 UTC, michalbiesek requested changes
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/544)* status: 7 of 12 files reviewed, 12 unresolved discussions (waiting on @bratpiorka, @kilobyte, and @PatKamin)

___
*[tiering/Makefile.mk, line 13 at r14](https://reviewable.io/reviews/memkind/memkind/544#-MUhkE3a6MgEeyqFH35s:-MUhkE3a6MgEeyqFH35t:b-lndl8c) ([raw file](https://github.com/memkind/memkind/blob/5ad46959b5b3baf34ecea678a191403013e03596/tiering/Makefile.mk#L13)):*
> ```
> memtier-clean
> ```
So you have a target for cleaning as make memtier-clean, but for building it is make tiering - please unify this.
See autobhw for reference


<!-- Sent from Reviewable.io -->

2021-03-01 12:45 UTC, bratpiorka reviewed
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/544)* status: 6 of 12 files reviewed, 10 unresolved discussions (waiting on @kilobyte, @michalbiesek, and @PatKamin)

___
*[tiering/Makefile.mk, line 10 at r2](https://reviewable.io/reviews/memkind/memkind/544#-MUTA3EgDO2Wex1VJ8pp:-MUhjUPJ0_CiwC0KHSH9:bxnly7i) ([raw file](https://github.com/memkind/memkind/blob/ca61b922dc7d0087b981a75b118cbfa7b29d0ee5/tiering/Makefile.mk#L10)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

IMHO this is not currently needed.
</blockquote></details>

ok, I will remove this TODO
___
*[tiering/Makefile.mk, line 13 at r14](https://reviewable.io/reviews/memkind/memkind/544#-MUhkE3a6MgEeyqFH35s:-MUhnFyLDs_L38Dg7FLG:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/5ad46959b5b3baf34ecea678a191403013e03596/tiering/Makefile.mk#L13)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> memtier-clean
> ```
So you have a target for cleaning as make memtier-clean, but for building it is make tiering - please unify this.
See autobhw for reference
</blockquote></details>

Done.
___
*[tiering/memtier_log.h, line 5 at r13](https://reviewable.io/reviews/memkind/memkind/544#-MUhgGlmAflYnqtmxbJV:-MUhlFV29bZfUN7Vz3SJ:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/d338e72e7d1238443405d3ef3702892cae991f3a/tiering/memtier_log.h#L5)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

#pragma once
#ifdef __cplusplus
extern "C" {
#endif
</blockquote></details>

Done.
___
*[tiering/memtier_log.h, line 17 at r13](https://reviewable.io/reviews/memkind/memkind/544#-MUhgIbT4bEzTVQFcgvV:-MUhkg4c8s2oPSr539qZ:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/d338e72e7d1238443405d3ef3702892cae991f3a/tiering/memtier_log.h#L17)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

#ifdef __cplusplus
}
#endif
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-03-01 12:55 UTC, PatKamin reviewed
> Reviewed 2 of 4 files at r11, 2 of 2 files at r12, 1 of 5 files at r15.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/544)* status: 7 of 12 files reviewed, 6 unresolved discussions (waiting on @kilobyte, @michalbiesek, and @PatKamin)



<!-- Sent from Reviewable.io -->

2021-03-01 13:12 UTC, michalbiesek reviewed
> Reviewed 1 of 5 files at r15.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/544)* status: 8 of 12 files reviewed, 3 unresolved discussions (waiting on @bratpiorka and @PatKamin)

___
*[tiering/memtier.c, line 105 at r1](https://reviewable.io/reviews/memkind/memkind/544#-MUTRqTa8UeZ_yCQGG1Q:-MUhJOov9DPLKWUK8H50:b-mg5k0k) ([raw file](https://github.com/memkind/memkind/blob/624ac9ffb63b77a8279b377d35814feea4fe0608/tiering/memtier.c#L105)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

> args

As @kilobyte checked fprintf/vfprintf doesn't use malloc, at least for formats that we use. 

</blockquote></details>

IMHO: At least for formats that are **currently** used.
Again this depends on the usage of fprintf implementation AFAIK the implementation could easily change and call malloc for the format which is used underneath.
What I highly recommend is to have your own logging layer which doesn't use allocation, but for now, the current solution could be as it is.
___
*[tiering/memtier.c, line 48 at r15](https://reviewable.io/reviews/memkind/memkind/544#-MUhtLqrE71E0vm_nmmr:-MUhtLqsABia0-UOP9Iu:b-9chz8z) ([raw file](https://github.com/memkind/memkind/blob/a1eacda8eda74d3a33e569ca4af754d616eb6180/tiering/memtier.c#L48)):*
> ```
> MEMTIER_EXPORT void free(void *ptr)
> ```
Extend commit message that this is support for malloc/realloc/calloc/memalign function or 
add here  TODO for other functions like e.g. posix_memalign aligned_alloc ... since when this will go through the memkind the allocation should be somehow handled or at least manual should be extended I don't want to forget about this.


<!-- Sent from Reviewable.io -->

2021-03-01 13:13 UTC, michalbiesek approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/544#-:-MUhuuHD6jP0lyGh5oEx:bnfp4nl)* status: 8 of 12 files reviewed, 3 unresolved discussions (waiting on @bratpiorka and @PatKamin)



<!-- Sent from Reviewable.io -->

2021-03-01 13:15 UTC, PatKamin reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 3 of 5 files at r15.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/544#-:-MUhvV6R1eNIPFQwk_sq:bnfp4nl)* status: 10 of 12 files reviewed, 3 unresolved discussions (waiting on @bratpiorka and @PatKamin)



<!-- Sent from Reviewable.io -->

2021-03-01 13:16 UTC, PatKamin reviewed
> Reviewed 1 of 5 files at r15, 2 of 2 files at r16.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/544)* status: all files reviewed, 3 unresolved discussions (waiting on @bratpiorka)



<!-- Sent from Reviewable.io -->

2021-03-01 13:18 UTC, bratpiorka reviewed
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/544)* status: all files reviewed, 3 unresolved discussions (waiting on @bratpiorka and @michalbiesek)

___
*[tiering/memtier.c, line 105 at r1](https://reviewable.io/reviews/memkind/memkind/544#-MUTRqTa8UeZ_yCQGG1Q:-MUhw5TY3yrhbbEWmuGB:breacby) ([raw file](https://github.com/memkind/memkind/blob/624ac9ffb63b77a8279b377d35814feea4fe0608/tiering/memtier.c#L105)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

IMHO: At least for formats that are **currently** used.
Again this depends on the usage of fprintf implementation AFAIK the implementation could easily change and call malloc for the format which is used underneath.
What I highly recommend is to have your own logging layer which doesn't use allocation, but for now, the current solution could be as it is.
</blockquote></details>

I will add such requirement to JIRA
___
*[tiering/memtier.c, line 48 at r15](https://reviewable.io/reviews/memkind/memkind/544#-MUhtLqrE71E0vm_nmmr:-MUhw0dd3wdzEJLM9RTe:bpel500) ([raw file](https://github.com/memkind/memkind/blob/a1eacda8eda74d3a33e569ca4af754d616eb6180/tiering/memtier.c#L48)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> MEMTIER_EXPORT void free(void *ptr)
> ```
Extend commit message that this is support for malloc/realloc/calloc/memalign function or 
add here  TODO for other functions like e.g. posix_memalign aligned_alloc ... since when this will go through the memkind the allocation should be somehow handled or at least manual should be extended I don't want to forget about this.
</blockquote></details>

ok I will add a TODO for other functions


<!-- Sent from Reviewable.io -->

2021-03-01 13:27 UTC, michalbiesek approved these changes
LGTM if the whole CI pass

> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/544#-:-MUhy6VE2LvAY4X2iLvW:bevowon)* status: all files reviewed, 2 unresolved discussions (waiting on @bratpiorka)



<!-- Sent from Reviewable.io -->

2021-03-03 11:00 UTC, PatKamin reviewed
> Reviewed 4 of 4 files at r17.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/544)* status: 10 of 12 files reviewed, all discussions resolved (waiting on @PatKamin)



<!-- Sent from Reviewable.io -->

2021-03-03 12:39 UTC, merged