Wip stack dram1
memkind/memkind pull request #557
Opened 2021-03-05 09:00 UTC by bratpiorka

### Description

### Types of changes

- [ ] Bugfix (non-breaking change which fixes issue linked in Description above)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation (correction or otherwise)
- [ ] Cosmetics (whitespace, appearance)
- [ ] Other

### Checklist

- [ ] Code compiles without errors
- [ ] All tests pass locally with my changes (see TESTING section in CONTRIBUTING file)
- [ ] Created tests which will fail without the change (if possible)
- [ ] Extended the README/documentation (if necessary)
- [ ] All newly added files have proprietary license (if necessary)
- [ ] All newly added files are referenced in MANIFEST files (if necessary)

## Further comments

2021-03-08 11:44 UTC, PatKamin reviewed
> Reviewed 4 of 4 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/557)* status: all files reviewed, 2 unresolved discussions (waiting on @bratpiorka and @michalbiesek)

___
*[test/tiering_tests.py, line 43 at r1](https://reviewable.io/reviews/memkind/memkind/557#-MVGQ7_M9wjGQKuqKBWZ:-MVGQ7_M9wjGQKuqKBW_:bfhj154) ([raw file](https://github.com/memkind/memkind/blob/ee50fe63e5ba00005187e014162384bf57931992/test/tiering_tests.py#L43)):*
> ```Python
>             "Test failed with error: \nExecution of: '" + command + \
>             "' returns: " + str(retcode) + "\noutput: " + output
>         return output
> ```

return output.splitlines()
___
*[test/tiering_tests.py, line 51 at r1](https://reviewable.io/reviews/memkind/memkind/557#-MVGQBJK3S90FSrrtU2z:-MVGQBJK3S90FSrrtU3-:brhumzt) ([raw file](https://github.com/memkind/memkind/blob/ee50fe63e5ba00005187e014162384bf57931992/test/tiering_tests.py#L51)):*
> ```Python
>             "Test failed with error: \nExecution of: '" + self.bin_path + \
>             "' returns: " + str(retcode) + "\noutput: " + output
>         return output
> ```

Same here.


<!-- Sent from Reviewable.io -->

2021-03-09 07:33 UTC, michalbiesek requested changes
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/557)* status: all files reviewed, 10 unresolved discussions (waiting on @bratpiorka and @PatKamin)

___
*[Makefile.am, line 561 at r2](https://reviewable.io/reviews/memkind/memkind/557#-MVIPxiU3mBeOsVaCILO:-MVIPxiU3mBeOsVaCILP:b-12iwzn) ([raw file](https://github.com/memkind/memkind/blob/a79447458b4285b063f5825bc2914052c29066a4/Makefile.am#L561)):*
> ```
> -vv
> ```
? 
___
*[src/memkind_memtier.c, line 108 at r2](https://reviewable.io/reviews/memkind/memkind/557#-MVISWUOAXwXkKXFnLgz:-MVISWUP7G6ymvFsygn9:bne12r2) ([raw file](https://github.com/memkind/memkind/blob/a79447458b4285b063f5825bc2914052c29066a4/src/memkind_memtier.c#L108)):*
> ```
>     log_info("malloc(%zu) = %p from kind: %s", size, ptr,
>              kind->todo_kind->name);
> ```
I would rather suggest decorators solution see:
https://github.com/memkind/memkind/commit/7509b41eef72afb5814bb392231eb99184c238bb
Even if you disable the logging in memtier/memkind layer you call log_info,log_generic for all the allocations which are obsolete calls.
You do this solution on both layers - on the memtier layer and on the memkind layer - the second one is obsolete. Keep in my mind that this log is on every allocation function.

And you don't miss freeing operation just like in:
<details><summary><i alt="summary">Quoted 6 lines of code…</i></summary>

> ```
>     void *ret = NULL;
>   if (size == 0 && ptr != NULL) {
>        memkind_free(tier->kind, ptr);
>        // TODO provide decrement counter logic
>         return ret;
> 
> ```
</details>

___
*[test/tiering_tests.py, line 18 at r1](https://reviewable.io/reviews/memkind/memkind/557#-MVIQ9TS05qprm_a5-cD:-MVIQ9TS05qprm_a5-cE:bur38pv) ([raw file](https://github.com/memkind/memkind/blob/ee50fe63e5ba00005187e014162384bf57931992/test/tiering_tests.py#L18)):*
<details><summary><i alt="summary">Quoted 14 lines of code…</i></summary>

> ```
>     log_msg_prefix = "MEMKIND_MEM_TIERING_LOG_DEBUG: "
>     re_hex_or_nil = r"((0[xX][a-fA-F0-9]+)|\(nil\))"
>     re_log_valid_messages = [
>         log_msg_prefix + r"malloc\(\d+\) = " + re_hex_or_nil,
>         log_msg_prefix +
>         r"realloc\(" + re_hex_or_nil + r", \d+\) = " + re_hex_or_nil,
>         log_msg_prefix + r"calloc\(\d+, \d+\) = " + re_hex_or_nil,
>         log_msg_prefix + r"memalign\(\d+, \d +\) = " + re_hex_or_nil,
>         log_msg_prefix + r"free\(" + re_hex_or_nil + r"\)",
>         log_msg_prefix + r"kind_name: \w+",
>         log_msg_prefix + r"pmem_path: .*",  # TODO add path re
>         log_msg_prefix + r"pmem_size: (N/A)|\d+",
>         log_msg_prefix + r"ratio_value: \d+",
>     ]
> ```
</details>

AFAIK this is used in one test so there is no need to be a class attribute
___
*[test/tiering_tests.py, line 43 at r1](https://reviewable.io/reviews/memkind/memkind/557#-MVGQ7_M9wjGQKuqKBWZ:-MVITgcABedolrZVr3lN:bvyl1nu) ([raw file](https://github.com/memkind/memkind/blob/ee50fe63e5ba00005187e014162384bf57931992/test/tiering_tests.py#L43)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

return output.splitlines()
</blockquote></details>

+1 then I think you could remove ".split("\n")"
___
*[test/tiering_tests.py, line 83 at r1](https://reviewable.io/reviews/memkind/memkind/557#-MVIQgHG3rAz_SVv_a6l:-MVIQgHG3rAz_SVv_a6m:b-l3ohaz) ([raw file](https://github.com/memkind/memkind/blob/ee50fe63e5ba00005187e014162384bf57931992/test/tiering_tests.py#L83)):*
> ```
> log_level=None
> ```
why since you already have support for the default parameters?
___
*[tiering/memtier.c, line 4 at r1](https://reviewable.io/reviews/memkind/memkind/557#-MVIRB85DoENklZK5h3b:-MVIRB85DoENklZK5h3c:b-qxmq6a) ([raw file](https://github.com/memkind/memkind/blob/ee50fe63e5ba00005187e014162384bf57931992/tiering/memtier.c#L4)):*
> ```
> #include <memkind/internal/memkind_private.h>
> ```
why?
___
*[tiering/memtier.c, line 118 at r1](https://reviewable.io/reviews/memkind/memkind/557#-MVIRS7nB8bsUL1a7z_F:-MVIRS7nB8bsUL1a7z_G:b-gndm0o) ([raw file](https://github.com/memkind/memkind/blob/ee50fe63e5ba00005187e014162384bf57931992/tiering/memtier.c#L118)):*
> ```
>     // TODO change MEMTIER_DUMMY_VALUE to some tiering algorithm extracted from
>     // env when available
>     memtier_builder_set_policy(builder, MEMTIER_DUMMY_VALUE);
> ```
I think this comment will be naturally removed when the policy will have real value.
___
*[tiering/memtier.c, line 94 at r2](https://reviewable.io/reviews/memkind/memkind/557#-MVIWtun8On7RsGbwZAS:-MVIWtun8On7RsGbwZAT:b-koqxrz) ([raw file](https://github.com/memkind/memkind/blob/a79447458b4285b063f5825bc2914052c29066a4/tiering/memtier.c#L94)):*
> ```
> log_debug("free(%p)", ptr);
> ```
logging before freeing
___
*[tiering/memtier.c, line 117 at r2](https://reviewable.io/reviews/memkind/memkind/557#-MVIXMFxASop9Q01waDu:-MVIXMFxASop9Q01waDv:bdo529g) ([raw file](https://github.com/memkind/memkind/blob/a79447458b4285b063f5825bc2914052c29066a4/tiering/memtier.c#L117)):*
<details><summary><i alt="summary">Quoted 5 lines of code…</i></summary>

> ```
>     memtier_builder_add_tier(builder, current_tier, ratio_value);
>     // TODO change MEMTIER_DUMMY_VALUE to some tiering algorithm extracted from
>     // env when available
>     memtier_builder_set_policy(builder, MEMTIER_DUMMY_VALUE);
>     memtier_builder_construct_kind(builder, &current_kind);
> ```
</details>

You should check the status of these commands and perform logic based on it - this could be done easily now


<!-- Sent from Reviewable.io -->

2021-03-09 10:06 UTC, bratpiorka reviewed
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/557)* status: 1 of 4 files reviewed, 10 unresolved discussions (waiting on @michalbiesek and @PatKamin)

___
*[Makefile.am, line 561 at r2](https://reviewable.io/reviews/memkind/memkind/557#-MVIPxiU3mBeOsVaCILO:-MVL5s6L4KvFQW524HrL:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/a79447458b4285b063f5825bc2914052c29066a4/Makefile.am#L561)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> -vv
> ```
? 
</blockquote></details>

Done.
___
*[src/memkind_memtier.c, line 108 at r2](https://reviewable.io/reviews/memkind/memkind/557#-MVISWUOAXwXkKXFnLgz:-MVLO7Ti1XXVOC21XecY:b-okacsy) ([raw file](https://github.com/memkind/memkind/blob/a79447458b4285b063f5825bc2914052c29066a4/src/memkind_memtier.c#L108)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
>     log_info("malloc(%zu) = %p from kind: %s", size, ptr,
>              kind->todo_kind->name);
> ```
I would rather suggest decorators solution see:
https://github.com/memkind/memkind/commit/7509b41eef72afb5814bb392231eb99184c238bb
Even if you disable the logging in memtier/memkind layer you call log_info,log_generic for all the allocations which are obsolete calls.
You do this solution on both layers - on the memtier layer and on the memkind layer - the second one is obsolete. Keep in my mind that this log is on every allocation function.

And you don't miss freeing operation just like in:
> ```
>     void *ret = NULL;
>   if (size == 0 && ptr != NULL) {
>        memkind_free(tier->kind, ptr);
>        // TODO provide decrement counter logic
>         return ret;
> 
> ```
</blockquote></details>

So you suggest to remove logging from memkind_memtier layer at all? It could provide useful info for user (and probably for future tests) about which tier was used for allocations.
___
*[test/tiering_tests.py, line 18 at r1](https://reviewable.io/reviews/memkind/memkind/557#-MVIQ9TS05qprm_a5-cD:-MVL5uPk-XdZNF3SHiI4:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/ee50fe63e5ba00005187e014162384bf57931992/test/tiering_tests.py#L18)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
>     log_msg_prefix = "MEMKIND_MEM_TIERING_LOG_DEBUG: "
>     re_hex_or_nil = r"((0[xX][a-fA-F0-9]+)|\(nil\))"
>     re_log_valid_messages = [
>         log_msg_prefix + r"malloc\(\d+\) = " + re_hex_or_nil,
>         log_msg_prefix +
>         r"realloc\(" + re_hex_or_nil + r", \d+\) = " + re_hex_or_nil,
>         log_msg_prefix + r"calloc\(\d+, \d+\) = " + re_hex_or_nil,
>         log_msg_prefix + r"memalign\(\d+, \d +\) = " + re_hex_or_nil,
>         log_msg_prefix + r"free\(" + re_hex_or_nil + r"\)",
>         log_msg_prefix + r"kind_name: \w+",
>         log_msg_prefix + r"pmem_path: .*",  # TODO add path re
>         log_msg_prefix + r"pmem_size: (N/A)|\d+",
>         log_msg_prefix + r"ratio_value: \d+",
>     ]
> ```
AFAIK this is used in one test so there is no need to be a class attribute
</blockquote></details>

Done.
___
*[test/tiering_tests.py, line 43 at r1](https://reviewable.io/reviews/memkind/memkind/557#-MVGQ7_M9wjGQKuqKBWZ:-MVL5tW_-AGOBqOYGU_5:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/ee50fe63e5ba00005187e014162384bf57931992/test/tiering_tests.py#L43)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

+1 then I think you could remove ".split("\n")"
</blockquote></details>

Done.
___
*[test/tiering_tests.py, line 51 at r1](https://reviewable.io/reviews/memkind/memkind/557#-MVGQBJK3S90FSrrtU2z:-MVL5tkIAxzaS41B3SQx:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/ee50fe63e5ba00005187e014162384bf57931992/test/tiering_tests.py#L51)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Same here.
</blockquote></details>

Done.
___
*[test/tiering_tests.py, line 83 at r1](https://reviewable.io/reviews/memkind/memkind/557#-MVIQgHG3rAz_SVv_a6l:-MVL5uor8LExfK8JBR4O:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/ee50fe63e5ba00005187e014162384bf57931992/test/tiering_tests.py#L83)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> log_level=None
> ```
why since you already have support for the default parameters?
</blockquote></details>

Done.
___
*[tiering/memtier.c, line 4 at r1](https://reviewable.io/reviews/memkind/memkind/557#-MVIRB85DoENklZK5h3b:-MVL7UaAD9zFyqBXhfJM:b-mpglgt) ([raw file](https://github.com/memkind/memkind/blob/ee50fe63e5ba00005187e014162384bf57931992/tiering/memtier.c#L4)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> #include <memkind/internal/memkind_private.h>
> ```
why?
</blockquote></details>

yes, this was unnecessary
___
*[tiering/memtier.c, line 118 at r1](https://reviewable.io/reviews/memkind/memkind/557#-MVIRS7nB8bsUL1a7z_F:-MVL5xby2u8z9_VILVTP:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/ee50fe63e5ba00005187e014162384bf57931992/tiering/memtier.c#L118)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
>     // TODO change MEMTIER_DUMMY_VALUE to some tiering algorithm extracted from
>     // env when available
>     memtier_builder_set_policy(builder, MEMTIER_DUMMY_VALUE);
> ```
I think this comment will be naturally removed when the policy will have real value.
</blockquote></details>

Done.
___
*[tiering/memtier.c, line 94 at r2](https://reviewable.io/reviews/memkind/memkind/557#-MVIWtun8On7RsGbwZAS:-MVL5wJjCIWav2kkDWNT:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/a79447458b4285b063f5825bc2914052c29066a4/tiering/memtier.c#L94)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> log_debug("free(%p)", ptr);
> ```
logging before freeing
</blockquote></details>

Done.
___
*[tiering/memtier.c, line 117 at r2](https://reviewable.io/reviews/memkind/memkind/557#-MVIXMFxASop9Q01waDu:-MVLRGhG0S1Ka9Ayyh1b:b-ja4a5s) ([raw file](https://github.com/memkind/memkind/blob/a79447458b4285b063f5825bc2914052c29066a4/tiering/memtier.c#L117)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
>     memtier_builder_add_tier(builder, current_tier, ratio_value);
>     // TODO change MEMTIER_DUMMY_VALUE to some tiering algorithm extracted from
>     // env when available
>     memtier_builder_set_policy(builder, MEMTIER_DUMMY_VALUE);
>     memtier_builder_construct_kind(builder, &current_kind);
> ```
You should check the status of these commands and perform logic based on it - this could be done easily now
</blockquote></details>

Done, but what should we do in case when add_tier or set_policy fails? Should I call jemk_free(builder) directly? I would rather call sth like "memtier_builder_delete" but do we want to add it to API?


<!-- Sent from Reviewable.io -->

2021-03-09 10:46 UTC, michalbiesek requested changes
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/557)* status: 1 of 4 files reviewed, 9 unresolved discussions (waiting on @bratpiorka and @PatKamin)

___
*[src/memkind_memtier.c, line 108 at r2](https://reviewable.io/reviews/memkind/memkind/557#-MVISWUOAXwXkKXFnLgz:-MVLRoZE-M-N20_H1Vgw:b1li0lx) ([raw file](https://github.com/memkind/memkind/blob/a79447458b4285b063f5825bc2914052c29066a4/src/memkind_memtier.c#L108)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

So you suggest to remove logging from memkind_memtier layer at all? It could provide useful info for user (and probably for future tests) about which tier was used for allocations.
</blockquote></details>

My consideration is performance - it could be useful information no doubt on it, but what if I am not interested in it? Why do I need to call this obsolete stack? The tests don't matter here - your test methodology, should not impact the performance - the solution in the source code.

Regarding the memtier.c:
If you would want to track the information about allocation - I am fine with this - use log_info there, but rather to avoid the unnecessary call of the stack in memkind_memtier.c (see my previous comment) - this is basically duplicated call with additional information about memory kind.

The decorator part should be placed in the memkind_memtier layer (it should be moved regarding your current solution)

Regarding the memkind_memtier part:
Again I would rather suggest a solution introduced in 96a9073,7509b41, see how it was used in https://github.com/memkind/memkind/blob/046db28dc771b2d0a155dd93d5b3a3ccf50f7009/utils/memkind_malloc_wrapper/memkind_malloc_wrapper.c#L30-L70 - the disadvantage of this solution is that I have two versions of the library but I avoid this logging call stack entirely. Additional value is that you could even customize your logging part on memtier.c - not depend on log_info of the library itself.
___
*[test/tiering_tests.py, line 132 at r4](https://reviewable.io/reviews/memkind/memkind/557#-MVLSq_47fBeoB-jBlhK:-MVLSq_47fBeoB-jBlhL:b-p3xwrv) ([raw file](https://github.com/memkind/memkind/blob/0f1c8c2e152162de6c0b887ba057441a88ff3a3e/test/tiering_tests.py#L132)):*
> ```
> # NOTE: this script should be called from the root of memkind repository
> ```
this ld_preload_env is duplicate in each classes consider some abstraction a class from which you inherit to extract common code.
___
*[tiering/memtier.c, line 117 at r2](https://reviewable.io/reviews/memkind/memkind/557#-MVIXMFxASop9Q01waDu:-MVLS54h8ceDi0RHxXw8:b-k7jk3h) ([raw file](https://github.com/memkind/memkind/blob/a79447458b4285b063f5825bc2914052c29066a4/tiering/memtier.c#L117)):*
This is the corner case (at least in memtier.c) but you are right regarding general usage - I need to think about it how to support it, and
this is the corner case because if create_tiered_kind_from_env should return status different than 0 the application should exit.
~~
>        if (ret != 0) {
>           log_err("Couldn't load MEMKIND_MEM_TIERING_CONFIG env var");
~~
should be something like:
~~
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

>        if (ret != 0) {
>           log_fatal("Couldn't load MEMKIND_MEM_TIERING_CONFIG env var");
>           abort();
>        }
</details>
~~
___
*[tiering/memtier.c, line 19 at r4](https://reviewable.io/reviews/memkind/memkind/557#-MVLRZGT1bdxiiltkAHS:-MVLRZGT1bdxiiltkAHT:b-62hjj4) ([raw file](https://github.com/memkind/memkind/blob/0f1c8c2e152162de6c0b887ba057441a88ff3a3e/tiering/memtier.c#L19)):*
> ```
> static int initialized = 0;
> static int destructed = 0;
> ```
Since you don't assign the NULL pointer to pointers below, can you keep the one convention here?
The int static variable by default is initialized to value 0.
___
*[tiering/memtier.c, line 23 at r4](https://reviewable.io/reviews/memkind/memkind/557#-MVLRXAv7Hyoty4Ylb85:-MVLRXAw3c9-3YWBC9aK:b-9jy1zc) ([raw file](https://github.com/memkind/memkind/blob/0f1c8c2e152162de6c0b887ba057441a88ff3a3e/tiering/memtier.c#L23)):*
> ```
> struct memtier_kind *current_kind;
> struct memtier_tier *current_tier;
> ```
static?
___
*[tiering/memtier.c, line 137 at r4](https://reviewable.io/reviews/memkind/memkind/557#-MVLTIfAA3Hiz0ofloqf:-MVLTIfAA3Hiz0ofloqg:b-wjgsr4) ([raw file](https://github.com/memkind/memkind/blob/0f1c8c2e152162de6c0b887ba057441a88ff3a3e/tiering/memtier.c#L137)):*
> ```
> ret == -1
> ```
ret != 0 since we could distinguish return status in the future, in other words, "0 is success other values are a failure"
___
*[tiering/memtier.c, line 143 at r4](https://reviewable.io/reviews/memkind/memkind/557#-MVLTNSOCrcq6HnJxlIu:-MVLTNSOCrcq6HnJxlIv:b-wjgsr4) ([raw file](https://github.com/memkind/memkind/blob/0f1c8c2e152162de6c0b887ba057441a88ff3a3e/tiering/memtier.c#L143)):*
> ```
> ret == -1
> ```
ret != 0 since we could distinguish return status in the future, in other words, "0 is success other values are a failure"


<!-- Sent from Reviewable.io -->

2021-03-09 12:34 UTC, bratpiorka reviewed
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/557)* status: 1 of 3 files reviewed, 9 unresolved discussions (waiting on @michalbiesek and @PatKamin)

___
*[src/memkind_memtier.c, line 108 at r2](https://reviewable.io/reviews/memkind/memkind/557#-MVISWUOAXwXkKXFnLgz:-MVLyIxi5fm1QfqMwK3Y:bcfeaba) ([raw file](https://github.com/memkind/memkind/blob/a79447458b4285b063f5825bc2914052c29066a4/src/memkind_memtier.c#L108)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

My consideration is performance - it could be useful information no doubt on it, but what if I am not interested in it? Why do I need to call this obsolete stack? The tests don't matter here - your test methodology, should not impact the performance - the solution in the source code.

Regarding the memtier.c:
If you would want to track the information about allocation - I am fine with this - use log_info there, but rather to avoid the unnecessary call of the stack in memkind_memtier.c (see my previous comment) - this is basically duplicated call with additional information about memory kind.

The decorator part should be placed in the memkind_memtier layer (it should be moved regarding your current solution)

Regarding the memkind_memtier part:
Again I would rather suggest a solution introduced in 96a9073,7509b41, see how it was used in https://github.com/memkind/memkind/blob/046db28dc771b2d0a155dd93d5b3a3ccf50f7009/utils/memkind_malloc_wrapper/memkind_malloc_wrapper.c#L30-L70 - the disadvantage of this solution is that I have two versions of the library but I avoid this logging call stack entirely. Additional value is that you could even customize your logging part on memtier.c - not depend on log_info of the library itself.


</blockquote></details>

I removed logging from memkind_memtier - this will be done in separate story/PR
___
*[test/tiering_tests.py, line 132 at r4](https://reviewable.io/reviews/memkind/memkind/557#-MVLSq_47fBeoB-jBlhK:-MVLfog_5Gbp3P4KouMc:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/0f1c8c2e152162de6c0b887ba057441a88ff3a3e/test/tiering_tests.py#L132)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> # NOTE: this script should be called from the root of memkind repository
> ```
this ld_preload_env is duplicate in each classes consider some abstraction a class from which you inherit to extract common code.
</blockquote></details>

Done.
___
*[tiering/memtier.c, line 117 at r2](https://reviewable.io/reviews/memkind/memkind/557#-MVIXMFxASop9Q01waDu:-MVLgSc_6O-C10uJAN81:br1ppfv) ([raw file](https://github.com/memkind/memkind/blob/a79447458b4285b063f5825bc2914052c29066a4/tiering/memtier.c#L117)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

This is the corner case (at least in memtier.c) but you are right regarding general usage - I need to think about it how to support it, and
this is the corner case because if create_tiered_kind_from_env should return status different than 0 the application should exit.
~~
>        if (ret != 0) {
>           log_err("Couldn't load MEMKIND_MEM_TIERING_CONFIG env var");
~~
should be something like:
~~
>        if (ret != 0) {
>           log_fatal("Couldn't load MEMKIND_MEM_TIERING_CONFIG env var");
>           abort();
>        }
~~
</blockquote></details>

Ok I added abort(). Here log_err is similar to log_fatal from memkind - it is a default value of logging level and it is always printed. About deleting memtier builder - can I leave TODO in the code and add separate story to JIRA for this scenario?
___
*[tiering/memtier.c, line 19 at r4](https://reviewable.io/reviews/memkind/memkind/557#-MVLRZGT1bdxiiltkAHS:-MVLg0d77f9raNApvnZA:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/0f1c8c2e152162de6c0b887ba057441a88ff3a3e/tiering/memtier.c#L19)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> static int initialized = 0;
> static int destructed = 0;
> ```
Since you don't assign the NULL pointer to pointers below, can you keep the one convention here?
The int static variable by default is initialized to value 0.
</blockquote></details>

Done.
___
*[tiering/memtier.c, line 23 at r4](https://reviewable.io/reviews/memkind/memkind/557#-MVLRXAv7Hyoty4Ylb85:-MVLg0vH6aWFf25-msAa:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/0f1c8c2e152162de6c0b887ba057441a88ff3a3e/tiering/memtier.c#L23)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> struct memtier_kind *current_kind;
> struct memtier_tier *current_tier;
> ```
static?
</blockquote></details>

Done.
___
*[tiering/memtier.c, line 137 at r4](https://reviewable.io/reviews/memkind/memkind/557#-MVLTIfAA3Hiz0ofloqf:-MVLh-HHATLPsSzM1SDw:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/0f1c8c2e152162de6c0b887ba057441a88ff3a3e/tiering/memtier.c#L137)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> ret == -1
> ```
ret != 0 since we could distinguish return status in the future, in other words, "0 is success other values are a failure"
</blockquote></details>

Done.
___
*[tiering/memtier.c, line 143 at r4](https://reviewable.io/reviews/memkind/memkind/557#-MVLTNSOCrcq6HnJxlIu:-MVLh0-e443E15P2K4kR:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/0f1c8c2e152162de6c0b887ba057441a88ff3a3e/tiering/memtier.c#L143)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> ret == -1
> ```
ret != 0 since we could distinguish return status in the future, in other words, "0 is success other values are a failure"
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-03-09 12:41 UTC, michalbiesek requested changes
> Reviewed 1 of 3 files at r5.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/557)* status: 1 of 3 files reviewed, 7 unresolved discussions (waiting on @bratpiorka and @PatKamin)

___
*[test/tiering_tests.py, line 23 at r5](https://reviewable.io/reviews/memkind/memkind/557#-MVLzkRl-OcAvX46sPCi:-MVLzkRl-OcAvX46sPCj:bpomj9m) ([raw file](https://github.com/memkind/memkind/blob/200d2804437626310bb4b3a4703bd3b62f383bbb/test/tiering_tests.py#L23)):*
> ```
>     @classmethod
>     def get_ld_preload_cmd_output(cls, config_env, log_level=None,
>                                   negative=False):
> ```
     def get_ld_preload_cmd_output(self, config_env, log_level=None,
                                 negative=False):

And you could easily have access for this in derived classes - without reference to Helper.
___
*[test/tiering_tests.py, line 48 at r5](https://reviewable.io/reviews/memkind/memkind/557#-MVLynUG0_6JuVEvU1F9:-MVLynUHBELosKJyW5jA:bosc00p) ([raw file](https://github.com/memkind/memkind/blob/200d2804437626310bb4b3a4703bd3b62f383bbb/test/tiering_tests.py#L48)):*
> ```
> object
> ```
Helper ? and you just call self.get_default_cmd_output() ? -see my comment regarding class method
___
*[test/tiering_tests.py, line 141 at r5](https://reviewable.io/reviews/memkind/memkind/557#-MVLyu1kB8E9eQcQJCIq:-MVLyu1kB8E9eQcQJCIr:b-vkgwi6) ([raw file](https://github.com/memkind/memkind/blob/200d2804437626310bb4b3a4703bd3b62f383bbb/test/tiering_tests.py#L141)):*
> ```
> object
> ```
Helper
___
*[test/tiering_tests.py, line 179 at r5](https://reviewable.io/reviews/memkind/memkind/557#-MVLzwsn3ACcbna0DUAo:-MVLzwsn3ACcbna0DUAp:b-vkgwi6) ([raw file](https://github.com/memkind/memkind/blob/200d2804437626310bb4b3a4703bd3b62f383bbb/test/tiering_tests.py#L179)):*
> ```
> object
> ```
Helper
___
*[tiering/memtier.c, line 117 at r2](https://reviewable.io/reviews/memkind/memkind/557#-MVIXMFxASop9Q01waDu:-MVLzOCQB2H331zA2qER:bdpsumx) ([raw file](https://github.com/memkind/memkind/blob/a79447458b4285b063f5825bc2914052c29066a4/tiering/memtier.c#L117)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

Ok I added abort(). Here log_err is similar to log_fatal from memkind - it is a default value of logging level and it is always printed. About deleting memtier builder - can I leave TODO in the code and add separate story to JIRA for this scenario?
</blockquote></details>

Yes TODO is fine by me.
___
*[tiering/memtier.c, line 155 at r5](https://reviewable.io/reviews/memkind/memkind/557#-MVLzM51E9D4PPf5IuLj:-MVLzM51E9D4PPf5IuLk:ba0g9zi) ([raw file](https://github.com/memkind/memkind/blob/200d2804437626310bb4b3a4703bd3b62f383bbb/tiering/memtier.c#L155)):*
> ```
> log_err
> ```
log_fatal please since after this you abort program (see other places with log_fatal call)


<!-- Sent from Reviewable.io -->

2021-03-09 13:24 UTC, bratpiorka reviewed
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/557)* status: 1 of 3 files reviewed, 7 unresolved discussions (waiting on @bratpiorka, @michalbiesek, and @PatKamin)

___
*[test/tiering_tests.py, line 23 at r5](https://reviewable.io/reviews/memkind/memkind/557#-MVLzkRl-OcAvX46sPCi:-MVM5b3Z9nHTyQydwd1U:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/200d2804437626310bb4b3a4703bd3b62f383bbb/test/tiering_tests.py#L23)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
>     @classmethod
>     def get_ld_preload_cmd_output(cls, config_env, log_level=None,
>                                   negative=False):
> ```
     def get_ld_preload_cmd_output(self, config_env, log_level=None,
                                 negative=False):

And you could easily have access for this in derived classes - without reference to Helper.
</blockquote></details>

Done.
___
*[test/tiering_tests.py, line 48 at r5](https://reviewable.io/reviews/memkind/memkind/557#-MVLynUG0_6JuVEvU1F9:-MVM5b_gDHRO3lzCBF6o:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/200d2804437626310bb4b3a4703bd3b62f383bbb/test/tiering_tests.py#L48)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> object
> ```
Helper ? and you just call self.get_default_cmd_output() ? -see my comment regarding class method
</blockquote></details>

Done.
___
*[test/tiering_tests.py, line 141 at r5](https://reviewable.io/reviews/memkind/memkind/557#-MVLyu1kB8E9eQcQJCIq:-MVM5c2WDnXJTD06wE0f:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/200d2804437626310bb4b3a4703bd3b62f383bbb/test/tiering_tests.py#L141)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> object
> ```
Helper
</blockquote></details>

Done.
___
*[test/tiering_tests.py, line 179 at r5](https://reviewable.io/reviews/memkind/memkind/557#-MVLzwsn3ACcbna0DUAo:-MVM5cTFCe0H6KklfxQZ:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/200d2804437626310bb4b3a4703bd3b62f383bbb/test/tiering_tests.py#L179)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> object
> ```
Helper
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-03-09 13:48 UTC, michalbiesek requested changes
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/557)* status: 1 of 3 files reviewed, 7 unresolved discussions (waiting on @bratpiorka, @michalbiesek, and @PatKamin)

___
*[test/tiering_tests.py, line 23 at r5](https://reviewable.io/reviews/memkind/memkind/557#-MVLzkRl-OcAvX46sPCi:-MVMEi-sCfD7KuiJaSK1:ba66mqr) ([raw file](https://github.com/memkind/memkind/blob/200d2804437626310bb4b3a4703bd3b62f383bbb/test/tiering_tests.py#L23)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Forget to push? Since I don't see any new changes


<!-- Sent from Reviewable.io -->

2021-03-09 14:48 UTC, michalbiesek reviewed
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/557)* status: 1 of 3 files reviewed, 3 unresolved discussions (waiting on @bratpiorka and @PatKamin)

___
*[test/tiering_tests.py, line 24 at r6](https://reviewable.io/reviews/memkind/memkind/557#-MVMR_QkBnkk-tqo88BV:-MVMR_QkBnkk-tqo88BW:b-z5bfnm) ([raw file](https://github.com/memkind/memkind/blob/895cf16ae3a091567db32aef4a27b26cdc92baa5/test/tiering_tests.py#L24)):*
> ```
> negative
> ```
nit: the name of this variable could be more meaningful, see the responsibility of this variable is to assert the return status of the cmd or not.
"negative" -> valid_retcode, valid_status

Therefore you could avoid this negation of negation logic and would be much easier to read since valid_retcode or valid_status will be by default True.


<!-- Sent from Reviewable.io -->

2021-03-09 14:52 UTC, bratpiorka reviewed
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/557)* status: 1 of 3 files reviewed, 3 unresolved discussions (waiting on @michalbiesek and @PatKamin)

___
*[test/tiering_tests.py, line 24 at r6](https://reviewable.io/reviews/memkind/memkind/557#-MVMR_QkBnkk-tqo88BV:-MVMTCkN19B6MdxRwe47:brqzur2) ([raw file](https://github.com/memkind/memkind/blob/895cf16ae3a091567db32aef4a27b26cdc92baa5/test/tiering_tests.py#L24)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> negative
> ```
nit: the name of this variable could be more meaningful, see the responsibility of this variable is to assert the return status of the cmd or not.
"negative" -> valid_retcode, valid_status

Therefore you could avoid this negation of negation logic and would be much easier to read since valid_retcode or valid_status will be by default True.
</blockquote></details>

agree, I change this


<!-- Sent from Reviewable.io -->

2021-03-09 15:00 UTC, michalbiesek reviewed
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/557)* status: 1 of 3 files reviewed, 3 unresolved discussions (waiting on @bratpiorka and @PatKamin)

___
*[test/tiering_tests.py, line 24 at r6](https://reviewable.io/reviews/memkind/memkind/557#-MVMR_QkBnkk-tqo88BV:-MVMUzj9Dmtse7lw4Y0v:bto2uck) ([raw file](https://github.com/memkind/memkind/blob/895cf16ae3a091567db32aef4a27b26cdc92baa5/test/tiering_tests.py#L24)):*
validate_retcode=True by default

Is:
> if validate_retcode is False:

Should be:
>if validate_retcode:

Also please update the invocation in your calls.


<!-- Sent from Reviewable.io -->

2021-03-10 10:29 UTC, michalbiesek requested changes
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/557)* status: 1 of 3 files reviewed, 4 unresolved discussions (waiting on @bratpiorka and @PatKamin)



<!-- Sent from Reviewable.io -->

2021-03-10 11:00 UTC, bratpiorka reviewed
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/557)* status: 1 of 3 files reviewed, 4 unresolved discussions (waiting on @michalbiesek and @PatKamin)

___
*[test/tiering_tests.py, line 24 at r6](https://reviewable.io/reviews/memkind/memkind/557#-MVMR_QkBnkk-tqo88BV:-MVQhzlPAHEKmcDV7Mf8:baul16o) ([raw file](https://github.com/memkind/memkind/blob/895cf16ae3a091567db32aef4a27b26cdc92baa5/test/tiering_tests.py#L24)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

validate_retcode=True by default is not done.
</blockquote></details>

sorry, I missed this
___
*[test/tiering_tests.py, line 4 at r7](https://reviewable.io/reviews/memkind/memkind/557#-MVQeoSb0lAZP6hjVwdi:-MVQhuGZ3LjxpSPezbyi:ba5plgl) ([raw file](https://github.com/memkind/memkind/blob/597158f4cefc26265fe2b382d3ad81c1da39a17e/test/tiering_tests.py#L4)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> from _pytest.outcomes import fail
> ```
where is this needed? flake8 report this as unused
</blockquote></details>

I really don't know how this line was added... :) OK - removed


<!-- Sent from Reviewable.io -->

2021-03-10 11:02 UTC, michalbiesek approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> I merge this when the test passes

> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/557#-:-MVQn7vZ3pIj4mlnpQPW:b-610jtg)* status: 1 of 3 files reviewed, 2 unresolved discussions (waiting on @PatKamin)



<!-- Sent from Reviewable.io -->

2021-03-10 14:41 UTC, merged