Validate pmem size in MEMKIND_MEM_TIERING_CONFIG env var
memkind/memkind pull request #558
Opened 2021-03-08 16:58 UTC by PatKamin

### Description

### Types of changes

- [ ] Bugfix (non-breaking change which fixes issue linked in Description above)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation (correction or otherwise)
- [ ] Cosmetics (whitespace, appearance)
- [ ] Other

### Checklist

- [x] Code compiles without errors
- [x] All tests pass locally with my changes (see TESTING section in CONTRIBUTING file)
- [] Created tests which will fail without the change (if possible)
- [ ] Extended the README/documentation (if necessary)
- [ ] All newly added files have proprietary license (if necessary)
- [ ] All newly added files are referenced in MANIFEST files (if necessary)

## Further comments

2021-03-09 06:44 UTC, michalbiesek requested changes
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/558)* status: 0 of 4 files reviewed, 9 unresolved discussions (waiting on @bratpiorka and @PatKamin)

___
*[test/tiering_tests.py, line 172 at r2](https://reviewable.io/reviews/memkind/memkind/558#-MVILl25CzckjxvZENta:-MVILl25CzckjxvZENtb:b-hu5jbj) ([raw file](https://github.com/memkind/memkind/blob/4992caaaced4e131f26ebd9b6778f20a7865ee63/test/tiering_tests.py#L172)):*
> ```
> test_FSDAX_only_pmem_size
> ```
sorry, I don't quite get it the naming convention test_FSDAX_only_pmem_size test_FSDAX_only_pmem_size_max:
testing only FS-DAX solution with pmem_size as 0 and 1 ?
___
*[test/tiering_tests.py, line 224 at r2](https://reviewable.io/reviews/memkind/memkind/558#-MVILYU-DUw_bbA79r4-:-MVILYU-DUw_bbA79r40:b-ra7ol7) ([raw file](https://github.com/memkind/memkind/blob/4992caaaced4e131f26ebd9b6778f20a7865ee63/test/tiering_tests.py#L224)):*
> ```
> ["as", "10k1", "M", "M2", "10kM"])
> ```
+1 for this
___
*[tiering/ctl.c, line 16 at r1](https://reviewable.io/reviews/memkind/memkind/558#-MVIGZJS5zuNYmNCgPPn:-MVIGZJS5zuNYmNCgPPo:b-etw74g) ([raw file](https://github.com/memkind/memkind/blob/5a2421f48bdc5d83e43367842a9cd8b463a1a367/tiering/ctl.c#L16)):*
> ```
> #define k             1024
> #define M             (1024 * 1024)
> ```
KB ..
MB ..
You don't need to pass only one letter in macro. The format above should improve readability a little bit since it often used in other parts of code.
___
*[tiering/ctl.c, line 63 at r1](https://reviewable.io/reviews/memkind/memkind/558#-MVIHXp7AVzpA_YiA-2l:-MVIHXp7AVzpA_YiA-2m:b4jzcma) ([raw file](https://github.com/memkind/memkind/blob/5a2421f48bdc5d83e43367842a9cd8b463a1a367/tiering/ctl.c#L63)):*
> ```
> kM
> ```
kMG see my other comment regarding the type
___
*[tiering/ctl.c, line 63 at r1](https://reviewable.io/reviews/memkind/memkind/558#-MVIMXRU-I2GpdVkiTVp:-MVIMXRU-I2GpdVkiTVq:b-36c5do) ([raw file](https://github.com/memkind/memkind/blob/5a2421f48bdc5d83e43367842a9cd8b463a1a367/tiering/ctl.c#L63)):*
> ```
> {0,1}
> ```
is this ratio? - still, I am confused since I don't have any reference in the manual - would be much easier for me to review this regexp if I know what its expected behavior of it
___
*[tiering/ctl.c, line 75 at r1](https://reviewable.io/reviews/memkind/memkind/558#-MVIHV7N8P7PHPYb16kn:-MVIHV7N8P7PHPYb16ko:b-ky09lj) ([raw file](https://github.com/memkind/memkind/blob/5a2421f48bdc5d83e43367842a9cd8b463a1a367/tiering/ctl.c#L75)):*
> ```
> ctl_parse_u
> ```
I would rather leave GB support here and change the type of pmem_size to "size_t" see that in the current state of the patch:
The maximum size of created pmem kind will be 32 MB which limits the created kind too much (capacity will be often passed in GB):
https://github.com/memkind/memkind/blob/046db28dc771b2d0a155dd93d5b3a3ccf50f7009/man/memkind.3#L65
My comment here: https://github.com/memkind/memkind/pull/532#pullrequestreview-600647587 regarding pmem_size and unsigned was wrong - for pmem_size it should be size_t
___
*[tiering/ctl.c, line 85 at r1](https://reviewable.io/reviews/memkind/memkind/558#-MVIHKyp5L9khiuZXMyF:-MVIHKyp5L9khiuZXMyG:b-lbud3s) ([raw file](https://github.com/memkind/memkind/blob/5a2421f48bdc5d83e43367842a9cd8b463a1a367/tiering/ctl.c#L85)):*
> ```
> *pmem_size = *pmem_size
> ```
 *pmem_size *=
___
*[tiering/ctl.c, line 140 at r1](https://reviewable.io/reviews/memkind/memkind/558#-MVIL3UoAEz8CgBo-Mvu:-MVIL3UoAEz8CgBo-Mvv:b-s648ph) ([raw file](https://github.com/memkind/memkind/blob/5a2421f48bdc5d83e43367842a9cd8b463a1a367/tiering/ctl.c#L140)):*
> ```
> // TODO: Raise error
> ```
why do you need to raise an error? I am not even sure if in your solution you need to set it for NULL and 0 - currently maybe since it is used for logging (I think) but in case of a kind different than fsdax this could be considered as "optional output" or I am wrong here?
___
*[tiering/ctl.c, line 146 at r1](https://reviewable.io/reviews/memkind/memkind/558#-MVIP1YD9fMyZwZjZ-n-:-MVIP1YE5iCtTcl93TXJ:b-lg0hz2) ([raw file](https://github.com/memkind/memkind/blob/5a2421f48bdc5d83e43367842a9cd8b463a1a367/tiering/ctl.c#L146)):*
> ```
>     char *ratio_value_str = NULL;
>     ratio_value_str = strtok_r(NULL, CTL_VALUE_SEPARATOR, &sptr);
> ```
not related with this PR but why not in one line?
___
*[tiering/memtier.c, line 66 at r1](https://reviewable.io/reviews/memkind/memkind/558#-MVIJvDN8sIZ6UF01IFp:-MVIJvDN8sIZ6UF01IFq:b-w7x610) ([raw file](https://github.com/memkind/memkind/blob/5a2421f48bdc5d83e43367842a9cd8b463a1a367/tiering/memtier.c#L66)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
>     log_debug("kind_name: %s", kind_name);
>     log_debug("pmem_path: %s", pmem_path);
>     log_debug("pmem_size: %u", pmem_size);
>     log_debug("ratio_value: %u", ratio_value);
> ```
</details>

This is not related to this PR, but I would like to see a description of this environment variable in the manual since now this functionality is pretty extensive and the correct usage is not documented. Now If I want to use this functionality in my dev I would like to lookup for correct way of using it in manual like format and lmiitations (like the end-user) rather than lookup in  tests.


<!-- Sent from Reviewable.io -->

2021-03-09 08:09 UTC, bratpiorka reviewed
> Reviewed 3 of 3 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/558)* status: all files reviewed, 9 unresolved discussions (waiting on @michalbiesek and @PatKamin)

___
*[tiering/ctl.c, line 63 at r1](https://reviewable.io/reviews/memkind/memkind/558#-MVIMXRU-I2GpdVkiTVp:-MVL0LIt9xIhVrdOLRxT:bkfuysg) ([raw file](https://github.com/memkind/memkind/blob/5a2421f48bdc5d83e43367842a9cd8b463a1a367/tiering/ctl.c#L63)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> {0,1}
> ```
is this ratio? - still, I am confused since I don't have any reference in the manual - would be much easier for me to review this regexp if I know what its expected behavior of it
</blockquote></details>

this is exact num of matches for previous [kM] pattern
___
*[tiering/memtier.c, line 66 at r1](https://reviewable.io/reviews/memkind/memkind/558#-MVIJvDN8sIZ6UF01IFp:-MVL0mWC-2cfWax28q59:b32v57) ([raw file](https://github.com/memkind/memkind/blob/5a2421f48bdc5d83e43367842a9cd8b463a1a367/tiering/memtier.c#L66)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
>     log_debug("kind_name: %s", kind_name);
>     log_debug("pmem_path: %s", pmem_path);
>     log_debug("pmem_size: %u", pmem_size);
>     log_debug("ratio_value: %u", ratio_value);
> ```
This is not related to this PR, but I would like to see a description of this environment variable in the manual since now this functionality is pretty extensive and the correct usage is not documented. Now If I want to use this functionality in my dev I would like to lookup for correct way of using it in manual like format and lmiitations (like the end-user) rather than lookup in  tests.
</blockquote></details>

+1


<!-- Sent from Reviewable.io -->

2021-03-09 08:33 UTC, michalbiesek reviewed
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/558)* status: all files reviewed, 9 unresolved discussions (waiting on @bratpiorka, @michalbiesek, and @PatKamin)

___
*[tiering/ctl.c, line 63 at r1](https://reviewable.io/reviews/memkind/memkind/558#-MVIMXRU-I2GpdVkiTVp:-MVL5kkPAAg2iisJW9iW:brmtjxq) ([raw file](https://github.com/memkind/memkind/blob/5a2421f48bdc5d83e43367842a9cd8b463a1a367/tiering/ctl.c#L63)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

this is exact num of matches for previous [kM] pattern
</blockquote></details>

Regex magic - thanks. You could just use a question mark "?" instead of "{0,1}" to match zero or one occurrence of the preceding element.


<!-- Sent from Reviewable.io -->

2021-03-09 20:04 UTC, michalbiesek requested changes
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/558)* status: 0 of 5 files reviewed, 11 unresolved discussions (waiting on @bratpiorka and @PatKamin)

___
*[man/memtier.7, line 30 at r5](https://reviewable.io/reviews/memkind/memkind/558#-MVNK0LeE2nNG0y2bRzM:-MVNK0LeE2nNG0y2bRzN:b-xjhew3) ([raw file](https://github.com/memkind/memkind/blob/0190ffdf7ce64a3986a4d7170dc4362d675ec414/man/memtier.7#L30)):*
> ```
> The accepted formats are: 1, 1KB, 1MB, 1GB. Valid values of size are from zero to the maximum value of
> .I size_t
> ```
I think the best place to point here limitation of size will be memkind.3 and memkind_create_pmem function the part regarding size limitation
___
*[man/memtier.7, line 33 at r5](https://reviewable.io/reviews/memkind/memkind/558#-MVN_VpX6ZrwFbeP7LkA:-MVN_VpX6ZrwFbeP7LkB:bt0wnn5) ([raw file](https://github.com/memkind/memkind/blob/0190ffdf7ce64a3986a4d7170dc4362d675ec414/man/memtier.7#L33)):*
> ```Roff
> .I size_t
> .IP
> .BR 
> ```

@patkamin please ask @mjsmolarek technical doc review:
___
*[man/memtier.7, line 37 at r5](https://reviewable.io/reviews/memkind/memkind/558#-MVNJ_Ec9Elnxv1OAFKI:-MVNJ_Ec9Elnxv1OAFKJ:blwa0uh) ([raw file](https://github.com/memkind/memkind/blob/0190ffdf7ce64a3986a4d7170dc4362d675ec414/man/memtier.7#L37)):*
> ```
> type. Valid values have to be greater than zero and no greater than
> .I UINT_MAX
> ```
Value should be from range 1 to
.I UINT_MAX
___
*[man/memtier.7, line 40 at r5](https://reviewable.io/reviews/memkind/memkind/558#-MVNKN7_1K4dUUey1XdA:-MVNKN7_1K4dUUey1XdB:b-gvrpp) ([raw file](https://github.com/memkind/memkind/blob/0190ffdf7ce64a3986a4d7170dc4362d675ec414/man/memtier.7#L40)):*
> ```
> Example usage where 20% of allocations will go to PMEM and 80% of allocations will go to DRAM:
> MEMKIND_MEM_TIERING_CONFIG="FS_DAX:/tmp/:10M:1,DRAM:4"
> ```
Actually, you have an examples section below please move this, please extend the description of this example about details where fs dax is and what is the limit of it -> TBH it will actually fail so please make this a real value (the pmem kind size )
___
*[test/tiering_tests.py, line 171 at r5](https://reviewable.io/reviews/memkind/memkind/558#-MVNYOTOEE78stTJaQRu:-MVNYOTOEE78stTJaQRv:b-hoi957) ([raw file](https://github.com/memkind/memkind/blob/0190ffdf7ce64a3986a4d7170dc4362d675ec414/test/tiering_tests.py#L171)):*
> ```Python
>                "Wrong message"
> 
>     @pytest.mark.parametrize("pmem_size", ["0", "1", "65535"])
> ```

18446744073709551615 ? as max possible value
___
*[tiering/ctl.c, line 15 at r5](https://reviewable.io/reviews/memkind/memkind/558#-MVNMYsq1rUGEQKz28zd:-MVNMYsq1rUGEQKz28ze:b-fghc5d) ([raw file](https://github.com/memkind/memkind/blob/0190ffdf7ce64a3986a4d7170dc4362d675ec414/tiering/ctl.c#L15)):*
> ```
> 1024
> ```
nit: could you use parenthesis?
___
*[tiering/ctl.c, line 18 at r5](https://reviewable.io/reviews/memkind/memkind/558#-MVNMXs98hhyV63tPVqO:-MVNMXs98hhyV63tPVqP:bke3fqy) ([raw file](https://github.com/memkind/memkind/blob/0190ffdf7ce64a3986a4d7170dc4362d675ec414/tiering/ctl.c#L18)):*
> ```
> (size_t)-1
> ```
SIZE_MAX
___
*[tiering/ctl.c, line 117 at r5](https://reviewable.io/reviews/memkind/memkind/558#-MVNZCi05jIplwamxlQo:-MVNZCi05jIplwamxlQp:bkiav1e) ([raw file](https://github.com/memkind/memkind/blob/0190ffdf7ce64a3986a4d7170dc4362d675ec414/tiering/ctl.c#L117)):*
> ```
>     } else if (parsed_size <= MAX_SIZE && strchr(pmem_size_str, 'k') == NULL &&
>                strchr(pmem_size_str, 'M') == NULL &&
>                strchr(pmem_size_str, 'G') == NULL) {
> ```
else if (parsed_size <= MAX_SIZE && strpbrk(pmem_size_str, "kMG") == NULL) ?
___
*[tiering/memtier.c, line 68 at r3](https://reviewable.io/reviews/memkind/memkind/558#-MVNI165-SM6sShUYetw:-MVNI166CUHSaxiYJ0ru:b7o3b8v) ([raw file](https://github.com/memkind/memkind/blob/8b35cd659884a277c822965cb7333e926e562eb7/tiering/memtier.c#L68)):*
> ```
> llu
> ```
zu


<!-- Sent from Reviewable.io -->

2021-03-10 11:43 UTC, bratpiorka reviewed
> Reviewed 3 of 4 files at r3, 1 of 1 files at r4, 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/558)* status: all files reviewed, 12 unresolved discussions (waiting on @PatKamin)

___
*[man/memtier.7, line 19 at r5](https://reviewable.io/reviews/memkind/memkind/558#-MVQuN267VF1Rxg8kOb8:-MVQuN267VF1Rxg8kOb9:bisxc8z) ([raw file](https://github.com/memkind/memkind/blob/0190ffdf7ce64a3986a4d7170dc4362d675ec414/man/memtier.7#L19)):*
> ```
> "kind_name:path_to_pmem:pmem_file_size:ratio"
> ```

maybe "kind_name[:path_to_pmem:pmem_file_size]:ratio" to mark that FS_DAX-related args are optional?
___
*[man/memtier.7, line 26 at r5](https://reviewable.io/reviews/memkind/memkind/558#-MVQuqc74p4Uds2XN_cO:-MVQuqc74p4Uds2XN_cP:bjd829a) ([raw file](https://github.com/memkind/memkind/blob/0190ffdf7ce64a3986a4d7170dc4362d675ec414/man/memtier.7#L26)):*
> ```Roff
> .IP
> .BR
> path_to_pmem - the path to the location where pmem file will be created. The path has to exist.
> ```

Add info that this is mandatory only for FS_DAX


<!-- Sent from Reviewable.io -->

2021-03-12 12:01 UTC, mjsmolarek commented on man/memtier.7
> +ratio - the part of ratio tied to the given kind. It's represented as an
This is a bit confusing. Are they supposed to be a nominator and denominator of a fraction? Why not use a simple percentage ratio? Or maybe only indicate how many allocations should got to one of the kinds and all the rest to the other one?

2021-03-12 12:05 UTC, mjsmolarek commented on man/memtier.7
> +MEMKIND_MEM_TIERING_CONFIG="FS_DAX:/tmp/:10M:1,DRAM:4"
"FS_DAX:/tmp/:10M:1,DRAM:4", ok, FS_DAX is kind_name, /tmp/ is path_to_pmem, 10M is pmem_file_size and 1,DRAM:4 is... ratio? what is 1? what is DRAM:4? why another colon? Please consider my previous comment and add a more specific description.

2021-03-12 14:59 UTC, PatKamin reviewed
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/558)* status: 1 of 5 files reviewed, 13 unresolved discussions (waiting on @bratpiorka, @michalbiesek, @mjsmolarek, and @PatKamin)

___
*[man/memtier.7, line 19 at r5](https://reviewable.io/reviews/memkind/memkind/558#-MVQuN267VF1Rxg8kOb8:-MVabbxe6VviTBrDdpRr:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/0190ffdf7ce64a3986a4d7170dc4362d675ec414/man/memtier.7#L19)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

> ```
> "kind_name:path_to_pmem:pmem_file_size:ratio"
> ```

maybe "kind_name[:path_to_pmem:pmem_file_size]:ratio" to mark that FS_DAX-related args are optional?
</blockquote></details>

Done.
___
*[man/memtier.7, line 26 at r5](https://reviewable.io/reviews/memkind/memkind/558#-MVQuqc74p4Uds2XN_cO:-MVabgtH5AJGIc0a-UkC:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/0190ffdf7ce64a3986a4d7170dc4362d675ec414/man/memtier.7#L26)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

Add info that this is mandatory only for FS_DAX
</blockquote></details>

Done.
___
*[man/memtier.7, line 30 at r5](https://reviewable.io/reviews/memkind/memkind/558#-MVNK0LeE2nNG0y2bRzM:-MVajMtb8kBkeVwl-tEH:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/0190ffdf7ce64a3986a4d7170dc4362d675ec414/man/memtier.7#L30)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> The accepted formats are: 1, 1KB, 1MB, 1GB. Valid values of size are from zero to the maximum value of
> .I size_t
> ```
I think the best place to point here limitation of size will be memkind.3 and memkind_create_pmem function the part regarding size limitation
</blockquote></details>

Done.
___
*[man/memtier.7, line 33 at r5](https://reviewable.io/reviews/memkind/memkind/558#-MVN_VpX6ZrwFbeP7LkA:-MVajOBSELp8eAKUnok2:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/0190ffdf7ce64a3986a4d7170dc4362d675ec414/man/memtier.7#L33)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

@patkamin please ask @mjsmolarek technical doc review:
</blockquote></details>

Done.
___
*[man/memtier.7, line 34 at r5](https://reviewable.io/reviews/memkind/memkind/558#-MVNAgX2SNaBEP9FNV7q-r5-34:-MVajQ8rEY_-V2xCtLxR:b-x1m481) ([raw file](https://github.com/memkind/memkind/blob/0190ffdf7ce64a3986a4d7170dc4362d675ec414/man/memtier.7#L34)):*
<details><summary><i>Previously, mjsmolarek wrote…</i></summary><blockquote>

This is a bit confusing. Are they supposed to be a nominator and denominator of a fraction? Why not use a simple percentage ratio? Or maybe only indicate how many allocations should got to one of the kinds and all the rest to the other one?
</blockquote></details>

Not nominator and denominator as there will be more that two kinds with different "parts of ratios" allowed. I would like to use simple values and parse them later to the percentage to avoid having to validate whether provided percentages sum up tp 100 or not.
___
*[man/memtier.7, line 37 at r5](https://reviewable.io/reviews/memkind/memkind/558#-MVNJ_Ec9Elnxv1OAFKI:-MVakG5CAK2TEMsr1XXW:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/0190ffdf7ce64a3986a4d7170dc4362d675ec414/man/memtier.7#L37)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> type. Valid values have to be greater than zero and no greater than
> .I UINT_MAX
> ```
Value should be from range 1 to
.I UINT_MAX
</blockquote></details>

Done.
___
*[man/memtier.7, line 40 at r5](https://reviewable.io/reviews/memkind/memkind/558#-MVNKN7_1K4dUUey1XdA:-MVammqm1V3QGAQyND2K:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/0190ffdf7ce64a3986a4d7170dc4362d675ec414/man/memtier.7#L40)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> Example usage where 20% of allocations will go to PMEM and 80% of allocations will go to DRAM:
> MEMKIND_MEM_TIERING_CONFIG="FS_DAX:/tmp/:10M:1,DRAM:4"
> ```
Actually, you have an examples section below please move this, please extend the description of this example about details where fs dax is and what is the limit of it -> TBH it will actually fail so please make this a real value (the pmem kind size )
</blockquote></details>

Done.
___
*[man/memtier.7, line 41 at r5](https://reviewable.io/reviews/memkind/memkind/558#-MVNAgX2SNaBEP9FNV7q-r5-41:-MVampra7sr0gwMPI7fY:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/0190ffdf7ce64a3986a4d7170dc4362d675ec414/man/memtier.7#L41)):*
<details><summary><i>Previously, mjsmolarek wrote…</i></summary><blockquote>

"FS_DAX:/tmp/:10M:1,DRAM:4", ok, FS_DAX is kind_name, /tmp/ is path_to_pmem, 10M is pmem_file_size and 1,DRAM:4 is... ratio? what is 1? what is DRAM:4? why another colon? Please consider my previous comment and add a more specific description.
</blockquote></details>

Done.
___
*[test/tiering_tests.py, line 171 at r5](https://reviewable.io/reviews/memkind/memkind/558#-MVNYOTOEE78stTJaQRu:-MVau0Uf43nKChTbtpAq:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/0190ffdf7ce64a3986a4d7170dc4362d675ec414/test/tiering_tests.py#L171)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

18446744073709551615 ? as max possible value
</blockquote></details>

Done.
___
*[tiering/ctl.c, line 18 at r5](https://reviewable.io/reviews/memkind/memkind/558#-MVNMXs98hhyV63tPVqO:-MVathRI0qreoz2E-TVf:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/0190ffdf7ce64a3986a4d7170dc4362d675ec414/tiering/ctl.c#L18)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> (size_t)-1
> ```
SIZE_MAX
</blockquote></details>

Done.
___
*[tiering/ctl.c, line 117 at r5](https://reviewable.io/reviews/memkind/memkind/558#-MVNZCi05jIplwamxlQo:-MVav13Q6NIaOIP3HYPX:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/0190ffdf7ce64a3986a4d7170dc4362d675ec414/tiering/ctl.c#L117)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
>     } else if (parsed_size <= MAX_SIZE && strchr(pmem_size_str, 'k') == NULL &&
>                strchr(pmem_size_str, 'M') == NULL &&
>                strchr(pmem_size_str, 'G') == NULL) {
> ```
else if (parsed_size <= MAX_SIZE && strpbrk(pmem_size_str, "kMG") == NULL) ?
</blockquote></details>

Done.
___
*[tiering/memtier.c, line 68 at r3](https://reviewable.io/reviews/memkind/memkind/558#-MVNI165-SM6sShUYetw:-MVavFb893OxPiTERNbq:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/8b35cd659884a277c822965cb7333e926e562eb7/tiering/memtier.c#L68)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> llu
> ```
zu
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-03-12 15:02 UTC, bratpiorka reviewed
> Reviewed 3 of 4 files at r6, 1 of 1 files at r7, 1 of 1 files at r8.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/558)* status: all files reviewed, 11 unresolved discussions (waiting on @michalbiesek, @mjsmolarek, and @PatKamin)



<!-- Sent from Reviewable.io -->

2021-03-12 15:03 UTC, PatKamin reviewed
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/558)* status: all files reviewed, 11 unresolved discussions (waiting on @michalbiesek and @mjsmolarek)

___
*[tiering/ctl.c, line 146 at r1](https://reviewable.io/reviews/memkind/memkind/558#-MVIP1YD9fMyZwZjZ-n-:-MVaxCWh8Ychfzofcvd1:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/5a2421f48bdc5d83e43367842a9cd8b463a1a367/tiering/ctl.c#L146)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
>     char *ratio_value_str = NULL;
>     ratio_value_str = strtok_r(NULL, CTL_VALUE_SEPARATOR, &sptr);
> ```
not related with this PR but why not in one line?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-03-12 15:15 UTC, michalbiesek requested changes
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/558)* status: 2 of 5 files reviewed, 8 unresolved discussions (waiting on @bratpiorka, @mjsmolarek, and @PatKamin)

___
*[man/memtier.7, line 18 at r8](https://reviewable.io/reviews/memkind/memkind/558#-MVazvOd8Dvx5N5rvhWg:-MVazvOd8Dvx5N5rvhWh:b-a72z5j) ([raw file](https://github.com/memkind/memkind/blob/dc4242f96a882f507ec009f06f6bbeb396107290/man/memtier.7#L18)):*
> ```
> The configuration
> ```
Maybe single memory kind configuration and get rid off his (...)
___
*[man/memtier.7, line 20 at r8](https://reviewable.io/reviews/memkind/memkind/558#-MVazqT82kjJBKoz9NGp:-MVazqT82kjJBKoz9NGq:b-lhlsru) ([raw file](https://github.com/memkind/memkind/blob/dc4242f96a882f507ec009f06f6bbeb396107290/man/memtier.7#L20)):*
> ```
> (...),policy
> ```
,policy
___
*[man/memtier.7, line 28 at r8](https://reviewable.io/reviews/memkind/memkind/558#-MVaypT40Wf2iMe7G57G:-MVaypT40Wf2iMe7G57H:b-x6zxqj) ([raw file](https://github.com/memkind/memkind/blob/dc4242f96a882f507ec009f06f6bbeb396107290/man/memtier.7#L28)):*
> ```
> path_to_pmem - the path to the location where pmem file will be created. The path has to exist. Pass this option
> only with FS_DAX kind.
> ```
I would like to include information that this option is required (valid) only for FS_DAX kind and cannot be present in the case of other memory kinds.
@mjsmolarek please help me with this
___
*[man/memtier.7, line 31 at r8](https://reviewable.io/reviews/memkind/memkind/558#-MVb-EN_8_CcdS7CO4m1:-MVb-ENa0qJFyMyvz7en:bxosq6r) ([raw file](https://github.com/memkind/memkind/blob/dc4242f96a882f507ec009f06f6bbeb396107290/man/memtier.7#L31)):*
> ```
> pmem_file_size - the size of pmem file, it's the maximum size of total allocations to PMEM. Pass this option
> only with FS_DAX kind. The accepted formats are: 1, 1KB, 1MB, 1GB. See
> ```
I would like to include information that this option is required (valid) only for FS_DAX kind and cannot be present in the case of other memory kinds.
@mjsmolarek please help me with this
___
*[man/memtier.7, line 32 at r8](https://reviewable.io/reviews/memkind/memkind/558#-MVayS9K3_k1O4JfWZm5:-MVayS9LBbXBLiIH3NGa:bfm1b6p) ([raw file](https://github.com/memkind/memkind/blob/dc4242f96a882f507ec009f06f6bbeb396107290/man/memtier.7#L32)):*
> ```
> 1, 1KB, 1MB, 1GB
> ```
with "B" ?
___
*[tiering/ctl.c, line 18 at r5](https://reviewable.io/reviews/memkind/memkind/558#-MVNMXs98hhyV63tPVqO:-MVaxwXN6Ki5XyUbz8FU:b8p77oe) ([raw file](https://github.com/memkind/memkind/blob/0190ffdf7ce64a3986a4d7170dc4362d675ec414/tiering/ctl.c#L18)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Remove this and just include stdint.h


<!-- Sent from Reviewable.io -->

2021-03-12 15:17 UTC, michalbiesek reviewed
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/558)* status: 2 of 5 files reviewed, 6 unresolved discussions (waiting on @bratpiorka, @mjsmolarek, and @PatKamin)

___
*[man/memtier.7, line 18 at r8](https://reviewable.io/reviews/memkind/memkind/558#-MVazvOd8Dvx5N5rvhWg:-MVb-lUr-C8OGNR-FoBO:b-i84ygj) ([raw file](https://github.com/memkind/memkind/blob/dc4242f96a882f507ec009f06f6bbeb396107290/man/memtier.7#L18)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> The configuration
> ```
Maybe single memory kind configuration and get rid off his (...)
</blockquote></details>

Ignore my previous comment.


<!-- Sent from Reviewable.io -->

2021-03-18 07:21 UTC, PatKamin reviewed
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/558)* status: 1 of 5 files reviewed, 6 unresolved discussions (waiting on @bratpiorka, @michalbiesek, and @mjsmolarek)

___
*[man/memtier.7, line 20 at r8](https://reviewable.io/reviews/memkind/memkind/558#-MVazqT82kjJBKoz9NGp:-MW3C2A3AwysrYk9ngSJ:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/dc4242f96a882f507ec009f06f6bbeb396107290/man/memtier.7#L20)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> (...),policy
> ```
,policy
</blockquote></details>

Done.
___
*[man/memtier.7, line 28 at r8](https://reviewable.io/reviews/memkind/memkind/558#-MVaypT40Wf2iMe7G57G:-MW3BwN95OjKl-OlByYS:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/dc4242f96a882f507ec009f06f6bbeb396107290/man/memtier.7#L28)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> path_to_pmem - the path to the location where pmem file will be created. The path has to exist. Pass this option
> only with FS_DAX kind.
> ```
I would like to include information that this option is required (valid) only for FS_DAX kind and cannot be present in the case of other memory kinds.
@mjsmolarek please help me with this
</blockquote></details>

Done.
___
*[man/memtier.7, line 31 at r8](https://reviewable.io/reviews/memkind/memkind/558#-MVb-EN_8_CcdS7CO4m1:-MW3CQhdBz2Cc0dkqo45:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/dc4242f96a882f507ec009f06f6bbeb396107290/man/memtier.7#L31)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> pmem_file_size - the size of pmem file, it's the maximum size of total allocations to PMEM. Pass this option
> only with FS_DAX kind. The accepted formats are: 1, 1KB, 1MB, 1GB. See
> ```
I would like to include information that this option is required (valid) only for FS_DAX kind and cannot be present in the case of other memory kinds.
@mjsmolarek please help me with this
</blockquote></details>

Done.
___
*[man/memtier.7, line 32 at r8](https://reviewable.io/reviews/memkind/memkind/558#-MVayS9K3_k1O4JfWZm5:-MW3Bpt74NhT70-jgsDj:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/dc4242f96a882f507ec009f06f6bbeb396107290/man/memtier.7#L32)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> 1, 1KB, 1MB, 1GB
> ```
with "B" ?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-03-18 08:32 UTC, michalbiesek requested changes
> Reviewed 1 of 1 files at r13.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/558)* status: 2 of 5 files reviewed, 9 unresolved discussions (waiting on @bratpiorka, @mjsmolarek, and @PatKamin)

___
*[tiering/ctl.c, line 74 at r12](https://reviewable.io/reviews/memkind/memkind/558#-MW3Pa9YE6z4aOA7KOxQ:-MW3Pa9YE6z4aOA7KOxR:b-r4rqli) ([raw file](https://github.com/memkind/memkind/blob/93b64d5a8d3457c07c50b1b371940f05532fddd1/tiering/ctl.c#L74)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
> struct suff {
>     const char *suff;
>     uint64_t mag;
> };
> ```
</details>

since you use it only once in function below define this in the function below
___
*[tiering/ctl.c, line 76 at r12](https://reviewable.io/reviews/memkind/memkind/558#-MW3Rz8W1Z-GhJWdW-ba:-MW3Rz8W1Z-GhJWdW-bb:bsyh8g3) ([raw file](https://github.com/memkind/memkind/blob/93b64d5a8d3457c07c50b1b371940f05532fddd1/tiering/ctl.c#L76)):*
> ```
>  uint64_t 
> ```
size_t it's pretty the same but I would like use one type of value
___
*[tiering/ctl.c, line 100 at r12](https://reviewable.io/reviews/memkind/memkind/558#-MW3RFQb6l0m2fdvepvh:-MW3RFQb6l0m2fdvepvi:bb2bdie) ([raw file](https://github.com/memkind/memkind/blob/93b64d5a8d3457c07c50b1b371940f05532fddd1/tiering/ctl.c#L100)):*
> ```
> res = 0;
> ```
return 0;
___
*[tiering/ctl.c, line 111 at r12](https://reviewable.io/reviews/memkind/memkind/558#-MW3RAPr-xB6g5h4EM8r:-MW3RAPr-xB6g5h4EM8s:bbf426k) ([raw file](https://github.com/memkind/memkind/blob/93b64d5a8d3457c07c50b1b371940f05532fddd1/tiering/ctl.c#L111)):*
> ```
>                 res = 0;
>                 break;
> ```
return 0;
___
*[tiering/ctl.c, line 116 at r12](https://reviewable.io/reviews/memkind/memkind/558#-MW3R5Ia0VX8QdkJDGdD:-MW3R5Ia0VX8QdkJDGdE:b-pnepiy) ([raw file](https://github.com/memkind/memkind/blob/93b64d5a8d3457c07c50b1b371940f05532fddd1/tiering/ctl.c#L116)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
>     } else {
>         return -1;
>     }
>     return res;
> ```
</details>

return -1 - in the end one else less and I believe you could use only res/ret instead of two variables.
___
*[tiering/ctl.c, line 163 at r12](https://reviewable.io/reviews/memkind/memkind/558#-MW3QUtW1fSHFmbRhSzK:-MW3QUtW1fSHFmbRhSzL:btpv38) ([raw file](https://github.com/memkind/memkind/blob/93b64d5a8d3457c07c50b1b371940f05532fddd1/tiering/ctl.c#L163)):*
> ```
> pmem_size_str = strtok_r(NULL, CTL_VALUE_SEPARATOR, &sptr);
> ```
char *pmem_size_str = strtok_r(NULL, CTL_VALUE_SEPARATOR, &sptr); ?
___
*[tiering/memtier.c, line 132 at r12](https://reviewable.io/reviews/memkind/memkind/558#-MW3Q9x73Pb1bZLuxIrJ:-MW3Q9x73Pb1bZLuxIrK:bcpj10) ([raw file](https://github.com/memkind/memkind/blob/93b64d5a8d3457c07c50b1b371940f05532fddd1/tiering/memtier.c#L132)):*
> ```
> || ratio_value == 0
> ```
I would rather move this here:
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
>    ret = ctl_parse_ratio(ratio_value_str, ratio_value);
>    if (ret != 0) {
>        return -1;
>    }
> ```
</details>


This logic will be probably moved there anyway.


<!-- Sent from Reviewable.io -->

2021-03-18 09:09 UTC, PatKamin reviewed
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/558)* status: 2 of 5 files reviewed, 9 unresolved discussions (waiting on @bratpiorka, @michalbiesek, and @mjsmolarek)

___
*[tiering/ctl.c, line 74 at r12](https://reviewable.io/reviews/memkind/memkind/558#-MW3Pa9YE6z4aOA7KOxQ:-MW3XH0yBRbs334xUN83:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/93b64d5a8d3457c07c50b1b371940f05532fddd1/tiering/ctl.c#L74)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> struct suff {
>     const char *suff;
>     uint64_t mag;
> };
> ```
since you use it only once in function below define this in the function below
</blockquote></details>

Done.
___
*[tiering/ctl.c, line 76 at r12](https://reviewable.io/reviews/memkind/memkind/558#-MW3Rz8W1Z-GhJWdW-ba:-MW3XNe_Bphfga2E5duQ:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/93b64d5a8d3457c07c50b1b371940f05532fddd1/tiering/ctl.c#L76)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
>  uint64_t 
> ```
size_t it's pretty the same but I would like use one type of value
</blockquote></details>

Done.
___
*[tiering/ctl.c, line 100 at r12](https://reviewable.io/reviews/memkind/memkind/558#-MW3RFQb6l0m2fdvepvh:-MW3ZFth21D63oBcwe-x:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/93b64d5a8d3457c07c50b1b371940f05532fddd1/tiering/ctl.c#L100)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> res = 0;
> ```
return 0;
</blockquote></details>

Done.
___
*[tiering/ctl.c, line 111 at r12](https://reviewable.io/reviews/memkind/memkind/558#-MW3RAPr-xB6g5h4EM8r:-MW3ZXWG38NzGo2o-1u2:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/93b64d5a8d3457c07c50b1b371940f05532fddd1/tiering/ctl.c#L111)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
>                 res = 0;
>                 break;
> ```
return 0;
</blockquote></details>

Done.
___
*[tiering/ctl.c, line 116 at r12](https://reviewable.io/reviews/memkind/memkind/558#-MW3R5Ia0VX8QdkJDGdD:-MW3ZXnR5qv_VOACn7m0:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/93b64d5a8d3457c07c50b1b371940f05532fddd1/tiering/ctl.c#L116)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
>     } else {
>         return -1;
>     }
>     return res;
> ```
return -1 - in the end one else less and I believe you could use only res/ret instead of two variables.
</blockquote></details>

Done.
___
*[tiering/ctl.c, line 163 at r12](https://reviewable.io/reviews/memkind/memkind/558#-MW3QUtW1fSHFmbRhSzK:-MW3ZoCT7rh_zt9UL0rF:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/93b64d5a8d3457c07c50b1b371940f05532fddd1/tiering/ctl.c#L163)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> pmem_size_str = strtok_r(NULL, CTL_VALUE_SEPARATOR, &sptr);
> ```
char *pmem_size_str = strtok_r(NULL, CTL_VALUE_SEPARATOR, &sptr); ?
</blockquote></details>

Done.
___
*[tiering/memtier.c, line 132 at r12](https://reviewable.io/reviews/memkind/memkind/558#-MW3Q9x73Pb1bZLuxIrJ:-MW3_ovc1rTZ0RD-jmQL:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/93b64d5a8d3457c07c50b1b371940f05532fddd1/tiering/memtier.c#L132)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> || ratio_value == 0
> ```
I would rather move this here:
> ```
>    ret = ctl_parse_ratio(ratio_value_str, ratio_value);
>    if (ret != 0) {
>        return -1;
>    }
> ```

This logic will be probably moved there anyway.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-03-18 09:21 UTC, michalbiesek approved these changes
> Reviewed 1 of 4 files at r16, 1 of 1 files at r18.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/558)* status: 2 of 5 files reviewed, 3 unresolved discussions (waiting on @bratpiorka, @michalbiesek, @mjsmolarek, and @PatKamin)

___
*[tiering/ctl.c, line 77 at r16](https://reviewable.io/reviews/memkind/memkind/558#-MW3clEhAXbfpa3_1oy9:-MW3clEhAXbfpa3_1oyA:b3y3870) ([raw file](https://github.com/memkind/memkind/blob/4feeff15e773a91b35ec97aa43a4eeb4da0dc13f/tiering/ctl.c#L77)):*
> ```
> int ctl_parse_size
> ```
static ?
maybe rename something as it is pretty similar with ctl_parse_size_t


<!-- Sent from Reviewable.io -->

2021-03-18 12:31 UTC, bratpiorka reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 3 files at r9, 1 of 1 files at r10, 1 of 1 files at r11, 2 of 4 files at r12, 1 of 1 files at r13, 1 of 1 files at r14, 1 of 1 files at r15, 2 of 4 files at r16, 1 of 1 files at r17.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/558#-:-MW4JOY-2JfatqESuXQj:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @mjsmolarek and @PatKamin)



<!-- Sent from Reviewable.io -->

2021-03-18 13:05 UTC, PatKamin reviewed
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/558)* status: 2 of 5 files reviewed, 3 unresolved discussions (waiting on @bratpiorka, @michalbiesek, and @mjsmolarek)

___
*[tiering/ctl.c, line 77 at r16](https://reviewable.io/reviews/memkind/memkind/558#-MW3clEhAXbfpa3_1oy9:-MW3dKsa7wbM7Jgm7pNq:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/4feeff15e773a91b35ec97aa43a4eeb4da0dc13f/tiering/ctl.c#L77)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> int ctl_parse_size
> ```
static ?
maybe rename something as it is pretty similar with ctl_parse_size_t
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-03-18 13:34 UTC, michalbiesek approved these changes
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/558)* status: 2 of 5 files reviewed, 2 unresolved discussions (waiting on @bratpiorka, @michalbiesek, and @mjsmolarek)



<!-- Sent from Reviewable.io -->

2021-03-18 13:34 UTC, merged