Don't use stdio buffers when logging.
memkind/memkind pull request #559
Opened 2021-03-09 08:31 UTC by kilobyte

Instead of FILE output (which uses malloced memory), write directly to file descriptor.  This is done by glibc's `dprintf`.

All straightforward printf formats (or posibly even all) use a stack-alloced buffer.

No outside-visible changes: `fprintf(stderr)` already flushes after each call, which split the output into three pieces.

2021-03-09 14:24 UTC, michalbiesek requested changes
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/559)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @bratpiorka and @kilobyte)

___
*[tiering/memtier_log.c, line 37 at r1](https://reviewable.io/reviews/memkind/memkind/559#-MVML4Cc52eP1568hl0l:-MVML4Cc52eP1568hl0m:bsstq5d) ([raw file](https://github.com/memkind/memkind/blob/590b5f333a80884dd71f382e849d825f0cf8d4f9/tiering/memtier_log.c#L37)):*
1. Please extend the commit message with information placed on Github PR
2. 
>"Instead of FILE output (which uses malloced memory), write directly to file descriptor. This is done by glibc's dprintf."
>"All straightforward printf formats (or posibly even all) use a stack-alloced buffer." 

Could you please share some source information about it? Or you check it empirically?
___
*[tiering/memtier_log.c, line 37 at r1](https://reviewable.io/reviews/memkind/memkind/559#-MVL6_lBBHn14A4aU7qV:-MVMM2V-9r4LjXFdG7St:b3huxwx) ([raw file](https://github.com/memkind/memkind/blob/590b5f333a80884dd71f382e849d825f0cf8d4f9/tiering/memtier_log.c#L37)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

is "stderr" defined as "2" somewhere?
</blockquote></details>

STDERR_FILENO -> unistd.h


<!-- Sent from Reviewable.io -->

2021-03-12 09:00 UTC, PatKamin commented on tiering/memtier_log.c
> +        if (write(2, overflow_msg, sizeof overflow_msg))
Possibly relevant comment: https://github.com/memkind/memkind/blob/wip-memory-tiering/jemalloc/include/jemalloc/internal/malloc_io.h#L70

2021-03-15 10:44 UTC, bratpiorka reviewed
> Reviewed 1 of 1 files at r1, 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/559)* status: 1 of 2 files reviewed, 4 unresolved discussions (waiting on @bratpiorka and @kilobyte)

___
*[tiering/memtier_log.c, line 44 at r2](https://reviewable.io/reviews/memkind/memkind/559#-MVpELnKCLq1r-ARX2hT:-MVpELnKCLq1r-ARX2hU:bwh7fib) ([raw file](https://github.com/memkind/memkind/blob/a7a394ca8913ec21720c939d3c94b0e9c7215b46/tiering/memtier_log.c#L44)):*
> ```C
>     const char overflow_msg[] = "Warning: message truncated.\n";
>     if (len >= blen)
>         if (write(2, overflow_msg, sizeof overflow_msg))
> ```

why empty if? is this some kind of optimization?


<!-- Sent from Reviewable.io -->

2021-03-16 17:19 UTC, kilobyte reviewed
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/559)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @bratpiorka, @michalbiesek, and @PatKamin)

___
*[tiering/memtier_log.c, line 37 at r1](https://reviewable.io/reviews/memkind/memkind/559#-MVML4Cc52eP1568hl0l:-MVRVQ__D7hT5Q7v7bei:bgb5vzr) ([raw file](https://github.com/memkind/memkind/blob/590b5f333a80884dd71f382e849d825f0cf8d4f9/tiering/memtier_log.c#L37)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

1. Please extend the commit message with information placed on Github PR
2. 
>"Instead of FILE output (which uses malloced memory), write directly to file descriptor. This is done by glibc's dprintf."
>"All straightforward printf formats (or posibly even all) use a stack-alloced buffer." 

Could you please share some source information about it? Or you check it empirically?
</blockquote></details>

Turns out that dprintf can call malloc, too.  And ironically, in the current test, it does while regular fprintf(stderr) did so before our call, while dprintf failed.

I've just explicitly allocated the buffer on stack — with the added benefit of avoiding multiple `write()` calls.
___
*[tiering/memtier_log.c, line 37 at r1](https://reviewable.io/reviews/memkind/memkind/559#-MVL6_lBBHn14A4aU7qV:-MVvWrXj8z_8dzNWSwYr:b80mk0v) ([raw file](https://github.com/memkind/memkind/blob/590b5f333a80884dd71f382e849d825f0cf8d4f9/tiering/memtier_log.c#L37)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

STDERR_FILENO -> unistd.h
</blockquote></details>

It's usually written as number (esp. because of shell redirections), but 'ere you go.
___
*[tiering/memtier_log.c, line 44 at r2](https://reviewable.io/reviews/memkind/memkind/559#-MVpELnKCLq1r-ARX2hT:-MVvVmRo4xRodeGjJyG0:b-x16kva) ([raw file](https://github.com/memkind/memkind/blob/a7a394ca8913ec21720c939d3c94b0e9c7215b46/tiering/memtier_log.c#L44)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

why empty if? is this some kind of optimization?
</blockquote></details>

If the `write()` fails, there's nowhere to report the error, thus we need to ignore the return value.

Yet, the traditional way to do so, a cast to `(void)`, is currently broken: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=25509
___
*[tiering/memtier_log.c, line 44 at r2](https://reviewable.io/reviews/memkind/memkind/559#-MVL6A9WYJp86I27Q4pe-r2-44:-MVvndy97IPv32YJhDpR:btv0usa) ([raw file](https://github.com/memkind/memkind/blob/a7a394ca8913ec21720c939d3c94b0e9c7215b46/tiering/memtier_log.c#L44)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Possibly relevant comment: https://github.com/memkind/memkind/blob/wip-memory-tiering/jemalloc/include/jemalloc/internal/malloc_io.h#L70
</blockquote></details>

Are we going to support non-Linux?


<!-- Sent from Reviewable.io -->

2021-03-16 20:20 UTC, michalbiesek reviewed
LGTM

> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/559#-:-MVwaJeT6eFIUa7-LVji:bb6ywmx)* status: 0 of 1 files reviewed, 6 unresolved discussions (waiting on @bratpiorka, @kilobyte, and @PatKamin)

___
*[tiering/memtier_log.c, line 44 at r2](https://reviewable.io/reviews/memkind/memkind/559#-MVpELnKCLq1r-ARX2hT:-MVwgNW_Ec7gbHh6Jb4W:b-te90xl) ([raw file](https://github.com/memkind/memkind/blob/a7a394ca8913ec21720c939d3c94b0e9c7215b46/tiering/memtier_log.c#L44)):*
<details><summary><i>Previously, kilobyte (Adam Borowski) wrote…</i></summary><blockquote>

If the `write()` fails, there's nowhere to report the error, thus we need to ignore the return value.

Yet, the traditional way to do so, a cast to `(void)`, is currently broken: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=25509
</blockquote></details>

nit: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=66425#c34 should do the job without if - is a little bit shorter
___
*[tiering/memtier_log.c, line 37 at r3](https://reviewable.io/reviews/memkind/memkind/559#-MVwaRuY9UQmNghMl4dz:-MVwaRuY9UQmNghMl4e-:bk73v3z) ([raw file](https://github.com/memkind/memkind/blob/aec8318e2167f1faaeaa39ed56a20f4a70347da6/tiering/memtier_log.c#L37)):*
> ```
> sizeof buf
> ```
nit: sizeof(buf)
___
*[tiering/memtier_log.c, line 42 at r3](https://reviewable.io/reviews/memkind/memkind/559#-MVwd-LcAlXmnC2T8Fqv:-MVwd-LcAlXmnC2T8Fqw:bji2blw) ([raw file](https://github.com/memkind/memkind/blob/aec8318e2167f1faaeaa39ed56a20f4a70347da6/tiering/memtier_log.c#L42)):*
> ```
>     const char overflow_msg[] = "Warning: message truncated.\n";
>     if (len >= blen)
>         if (write(STDERR_FILENO, overflow_msg, sizeof overflow_msg))
> ```
shouldn't this be inside the lock?
___
*[tiering/memtier_log.c, line 44 at r3](https://reviewable.io/reviews/memkind/memkind/559#-MVwaNNY3iGf5Beiu4XU:-MVwaNNY3iGf5Beiu4XV:b-z3cz49) ([raw file](https://github.com/memkind/memkind/blob/aec8318e2167f1faaeaa39ed56a20f4a70347da6/tiering/memtier_log.c#L44)):*
> ```
> sizeof overflow_msg
> ```
nit: sizeof(overflow_msg)


<!-- Sent from Reviewable.io -->

2021-03-17 07:30 UTC, bratpiorka reviewed
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/559)* status: all files reviewed, 5 unresolved discussions (waiting on @kilobyte, @michalbiesek, and @PatKamin)

___
*[tiering/memtier_log.c, line 37 at r3](https://reviewable.io/reviews/memkind/memkind/559#-MVwaRuY9UQmNghMl4dz:-MVz4V5vBk8AzCL19-gN:bjg0swp) ([raw file](https://github.com/memkind/memkind/blob/aec8318e2167f1faaeaa39ed56a20f4a70347da6/tiering/memtier_log.c#L37)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> sizeof buf
> ```
nit: sizeof(buf)
</blockquote></details>

+1... currently it looks like sizeof (buf + (buf - b) - 1) == sizeof (-b - 1)


<!-- Sent from Reviewable.io -->

2021-03-17 09:58 UTC, kilobyte reviewed
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/559)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @bratpiorka, @michalbiesek, and @PatKamin)

___
*[tiering/memtier_log.c, line 44 at r2](https://reviewable.io/reviews/memkind/memkind/559#-MVpELnKCLq1r-ARX2hT:-MVzbdsIE2MKeyBuCZXE:bdkgtm2) ([raw file](https://github.com/memkind/memkind/blob/a7a394ca8913ec21720c939d3c94b0e9c7215b46/tiering/memtier_log.c#L44)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

nit: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=66425#c34 should do the job without if - is a little bit shorter
</blockquote></details>

Nice find!
___
*[tiering/memtier_log.c, line 37 at r3](https://reviewable.io/reviews/memkind/memkind/559#-MVwaRuY9UQmNghMl4dz:-MVzYmlj53pxYqVAfxi9:bvdobca) ([raw file](https://github.com/memkind/memkind/blob/aec8318e2167f1faaeaa39ed56a20f4a70347da6/tiering/memtier_log.c#L37)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

+1... currently it looks like sizeof (buf + (buf - b) - 1) == sizeof (-b - 1)
</blockquote></details>

M'kay.
___
*[tiering/memtier_log.c, line 42 at r3](https://reviewable.io/reviews/memkind/memkind/559#-MVwd-LcAlXmnC2T8Fqv:-MVzZ09i6RSff9n7E6bf:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/aec8318e2167f1faaeaa39ed56a20f4a70347da6/tiering/memtier_log.c#L42)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
>     const char overflow_msg[] = "Warning: message truncated.\n";
>     if (len >= blen)
>         if (write(STDERR_FILENO, overflow_msg, sizeof overflow_msg))
> ```
shouldn't this be inside the lock?
</blockquote></details>

Done.
___
*[tiering/memtier_log.c, line 44 at r3](https://reviewable.io/reviews/memkind/memkind/559#-MVwaNNY3iGf5Beiu4XU:-MVzZ9v_CW6nASX5qQ4O:bua1jy0) ([raw file](https://github.com/memkind/memkind/blob/aec8318e2167f1faaeaa39ed56a20f4a70347da6/tiering/memtier_log.c#L44)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> sizeof overflow_msg
> ```
nit: sizeof(overflow_msg)
</blockquote></details>

The parentheses are redundant, but ok.


<!-- Sent from Reviewable.io -->

2021-03-17 10:02 UTC, michalbiesek approved these changes
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/559)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @bratpiorka and @PatKamin)



<!-- Sent from Reviewable.io -->

2021-03-17 10:04 UTC, bratpiorka reviewed
LGTM

> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/559#-:-MVzd37g8n4M7Bdr7pqc:bb6ywmx)* status: all files reviewed, 1 unresolved discussion (waiting on @PatKamin)



<!-- Sent from Reviewable.io -->

2021-03-17 11:32 UTC, PatKamin reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/559#-:-MVzxHpO6YB4kAsF26M1:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @kilobyte)

___
*[tiering/memtier_log.c, line 44 at r2](https://reviewable.io/reviews/memkind/memkind/559#-MVL6A9WYJp86I27Q4pe-r2-44:-MVzwN2w8GsFjzNtBtoy:b5ysop5) ([raw file](https://github.com/memkind/memkind/blob/a7a394ca8913ec21720c939d3c94b0e9c7215b46/tiering/memtier_log.c#L44)):*
<details><summary><i>Previously, kilobyte (Adam Borowski) wrote…</i></summary><blockquote>

Are we going to support non-Linux?
</blockquote></details>

I thought that we already are supporting freebsd as jemalloc supports it. But if we're not supporting non-linux, then this comment is irrelevant for us.


<!-- Sent from Reviewable.io -->

2021-03-17 11:48 UTC, kilobyte reviewed
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/559)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @bratpiorka and @PatKamin)

___
*[tiering/memtier_log.c, line 44 at r2](https://reviewable.io/reviews/memkind/memkind/559#-MVL6A9WYJp86I27Q4pe-r2-44:-MW--h2EEGGRb5zAGURm:b-gh8ahy) ([raw file](https://github.com/memkind/memkind/blob/a7a394ca8913ec21720c939d3c94b0e9c7215b46/tiering/memtier_log.c#L44)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

I thought that we already are supporting freebsd as jemalloc supports it. But if we're not supporting non-linux, then this comment is irrelevant for us.
</blockquote></details>

Hmm, safer to do that then, just in case.  I've added a separate commit, for a more readable history.


<!-- Sent from Reviewable.io -->

2021-03-17 11:52 UTC, PatKamin reviewed
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/559)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @bratpiorka and @PatKamin)



<!-- Sent from Reviewable.io -->

2021-03-17 11:57 UTC, bratpiorka reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/559#-:-MW-1t9N6cx901pgGqS9:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @kilobyte)



<!-- Sent from Reviewable.io -->

2021-03-17 12:23 UTC, michalbiesek approved these changes
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/559)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @kilobyte)



<!-- Sent from Reviewable.io -->

2021-03-17 12:23 UTC, merged