Feat static ratio
memkind/memkind pull request #599
Opened 2021-03-25 08:55 UTC by bratpiorka

### Description

### Types of changes

- [ ] Bugfix (non-breaking change which fixes issue linked in Description above)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation (correction or otherwise)
- [ ] Cosmetics (whitespace, appearance)
- [ ] Other

### Checklist

- [ ] Code compiles without errors
- [ ] All tests pass locally with my changes (see TESTING section in CONTRIBUTING file)
- [ ] Created tests which will fail without the change (if possible)
- [ ] Extended the README/documentation (if necessary)
- [ ] All newly added files have proprietary license (if necessary)
- [ ] All newly added files are referenced in MANIFEST files (if necessary)

## Further comments

2021-03-25 10:59 UTC, michalbiesek requested changes
> Reviewed 2 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/599)* status: 1 of 10 files reviewed, 7 unresolved discussions (waiting on @bratpiorka, @michalbiesek, and @PatKamin)

___
*[MANIFEST, line 432 at r1](https://reviewable.io/reviews/memkind/memkind/599#-MWczt9g-340pxIdhLMv:-MWczt9g-340pxIdhLMw:bj7ts2u) ([raw file](https://github.com/memkind/memkind/blob/ffa9fca8ce262b2a6d0ebb1d687f36a9e7aaeb57/MANIFEST#L432)):*
> ```
> memtier_policies
> ```
alphabetic order
___
*[Makefile.am, line 31 at r1](https://reviewable.io/reviews/memkind/memkind/599#-MWczumQDZsMXrnSUb7g:-MWczumQDZsMXrnSUb7h:bia8asf) ([raw file](https://github.com/memkind/memkind/blob/ffa9fca8ce262b2a6d0ebb1d687f36a9e7aaeb57/Makefile.am#L31)):*
> ```
> src/memtier_policies.c \
> ```
.
___
*[copying_headers/MANIFEST.freeBSD, line 81 at r1](https://reviewable.io/reviews/memkind/memkind/599#-MWczvXd4zX6vtdmgQLe:-MWczvXd4zX6vtdmgQLf:b-8uldr1) ([raw file](https://github.com/memkind/memkind/blob/ffa9fca8ce262b2a6d0ebb1d687f36a9e7aaeb57/copying_headers/MANIFEST.freeBSD#L81)):*
> ```
> src/memtier_policies.c
> ```
.
___
*[include/memkind/internal/memtier_private.h, line 5 at r1](https://reviewable.io/reviews/memkind/memkind/599#-MWczxAcBgCaw_QG11BR:-MWczxAcBgCaw_QG11BS:boqwy78) ([raw file](https://github.com/memkind/memkind/blob/ffa9fca8ce262b2a6d0ebb1d687f36a9e7aaeb57/include/memkind/internal/memtier_private.h#L5)):*
> ```
> #include <memkind/internal/memkind_private.h>
> ```
??? Circular dependency
___
*[src/memkind_memtier.c, line 99 at r2](https://reviewable.io/reviews/memkind/memkind/599#-MWd-AE-182CTlOy3-p1:-MWd-AE-182CTlOy3-p2:b-kq9far) ([raw file](https://github.com/memkind/memkind/blob/de8f911089827932da93802fda7cae2686ee2452/src/memkind_memtier.c#L99)):*
> ```
>     if (policy == MEMTIER_POLICY_CIRCULAR) {
>         builder->policy = &MEMTIER_POLICY_CIRCULAR_OBJ;
> ```
this should be removed with your change in other you should override this circular policy.
___
*[src/memtier_policies.c, line 26 at r1](https://reviewable.io/reviews/memkind/memkind/599#-MWd-Mjv0tGEYlR8AH2G:-MWd-MjwAhSVzG9TuY40:b-kia4lc) ([raw file](https://github.com/memkind/memkind/blob/ffa9fca8ce262b2a6d0ebb1d687f36a9e7aaeb57/src/memtier_policies.c#L26)):*
> ```C
>     .create = memtier_policy_circular_create,
>     .get_tier = memtier_policy_circular_get_tier,
>     .name = "POLICY_CIRCULAR",
> ```

you don't need a name to provide your functionality
___
*[tiering/ctl.c, line 16 at r2](https://reviewable.io/reviews/memkind/memkind/599#-MWd-gtF2B9kwY5oxWFO:-MWd-gtF2B9kwY5oxWFP:b-vsko4o) ([raw file](https://github.com/memkind/memkind/blob/de8f911089827932da93802fda7cae2686ee2452/tiering/ctl.c#L16)):*
> ```C
> 
> // TODO - remove this after logging cleanup
> #include <memkind/internal/memtier_private.h>
> ```

Rebase your PR


<!-- Sent from Reviewable.io -->

2021-03-25 10:59 UTC, michalbiesek reviewed
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/599)* status: 1 of 10 files reviewed, 7 unresolved discussions (waiting on @bratpiorka, @michalbiesek, and @PatKamin)

___
*[src/memkind_memtier.c, line 99 at r2](https://reviewable.io/reviews/memkind/memkind/599#-MWd-AE-182CTlOy3-p1:-MWd1V7dCBmjCrHTltlJ:b7ayl09) ([raw file](https://github.com/memkind/memkind/blob/de8f911089827932da93802fda7cae2686ee2452/src/memkind_memtier.c#L99)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
>     if (policy == MEMTIER_POLICY_CIRCULAR) {
>         builder->policy = &MEMTIER_POLICY_CIRCULAR_OBJ;
> ```
this should be removed with your change in other you should override this circular policy.
</blockquote></details>

* in other words


<!-- Sent from Reviewable.io -->

2021-03-25 12:24 UTC, bratpiorka reviewed
> Reviewed 2 of 8 files at r1, 1 of 8 files at r3, 7 of 7 files at r6.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/599)* status: all files reviewed, 7 unresolved discussions (waiting on @michalbiesek and @PatKamin)

___
*[MANIFEST, line 432 at r1](https://reviewable.io/reviews/memkind/memkind/599#-MWczt9g-340pxIdhLMv:-MWdFyng6jLsi3v6M-uS:b46t11s) ([raw file](https://github.com/memkind/memkind/blob/ffa9fca8ce262b2a6d0ebb1d687f36a9e7aaeb57/MANIFEST#L432)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> memtier_policies
> ```
alphabetic order
</blockquote></details>

this file is called "memtier" not "memkind" and memkind_* < memtier_*
___
*[Makefile.am, line 31 at r1](https://reviewable.io/reviews/memkind/memkind/599#-MWczumQDZsMXrnSUb7g:-MWdG5d14ukmExv5l8XO:b3kqx) ([raw file](https://github.com/memkind/memkind/blob/ffa9fca8ce262b2a6d0ebb1d687f36a9e7aaeb57/Makefile.am#L31)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> src/memtier_policies.c \
> ```
.
</blockquote></details>

.
___
*[copying_headers/MANIFEST.freeBSD, line 81 at r1](https://reviewable.io/reviews/memkind/memkind/599#-MWczvXd4zX6vtdmgQLe:-MWdG6bL3gm5uNq65bv7:b3kqx) ([raw file](https://github.com/memkind/memkind/blob/ffa9fca8ce262b2a6d0ebb1d687f36a9e7aaeb57/copying_headers/MANIFEST.freeBSD#L81)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> src/memtier_policies.c
> ```
.
</blockquote></details>

.
___
*[include/memkind/internal/memtier_private.h, line 5 at r1](https://reviewable.io/reviews/memkind/memkind/599#-MWczxAcBgCaw_QG11BR:-MWdJH9l5HtKooqiXOWK:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/ffa9fca8ce262b2a6d0ebb1d687f36a9e7aaeb57/include/memkind/internal/memtier_private.h#L5)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> #include <memkind/internal/memkind_private.h>
> ```
??? Circular dependency
</blockquote></details>

Done.
___
*[src/memkind_memtier.c, line 99 at r2](https://reviewable.io/reviews/memkind/memkind/599#-MWd-AE-182CTlOy3-p1:-MWdJIbxCRczAXP02R_v:bb6un1j) ([raw file](https://github.com/memkind/memkind/blob/de8f911089827932da93802fda7cae2686ee2452/src/memkind_memtier.c#L99)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

* in other words
</blockquote></details>

Done
___
*[src/memtier_policies.c, line 26 at r1](https://reviewable.io/reviews/memkind/memkind/599#-MWd-Mjv0tGEYlR8AH2G:-MWdGxMQ68TL19QrzN2n:b9c7xoc) ([raw file](https://github.com/memkind/memkind/blob/ffa9fca8ce262b2a6d0ebb1d687f36a9e7aaeb57/src/memtier_policies.c#L26)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

you don't need a name to provide your functionality
</blockquote></details>

I use "name" member for logging instead of using ctl_policy_to_str() (this PR removes this function)
___
*[tiering/ctl.c, line 16 at r2](https://reviewable.io/reviews/memkind/memkind/599#-MWd-gtF2B9kwY5oxWFO:-MWdGWMb6I8luFb3Rdro:bbcdjf7) ([raw file](https://github.com/memkind/memkind/blob/de8f911089827932da93802fda7cae2686ee2452/tiering/ctl.c#L16)):*
> ```
> / TODO - remove this after logging cleanup
> ```

this line was not added by mistake - this file is needed for definition of "policy" used in ctl_create_tier_kind_from_env in logging


<!-- Sent from Reviewable.io -->

2021-03-25 12:34 UTC, michalbiesek requested changes
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/599)* status: 9 of 10 files reviewed, 5 unresolved discussions (waiting on @bratpiorka and @PatKamin)

___
*[Makefile.am, line 63 at r7](https://reviewable.io/reviews/memkind/memkind/599#-MWdLZLx2j-CUnpE1n1x:-MWdLZLy9z29AjRmNWeu:b6u86ad) ([raw file](https://github.com/memkind/memkind/blob/734be31b134deec78e7a698b3a04673aa45edbc2/Makefile.am#L63)):*
> ```
> include/memkind/internal/memtier_private.h 
> ```
.
___
*[include/memkind/internal/memtier_private.h, line 21 at r5](https://reviewable.io/reviews/memkind/memkind/599#-MWdLdM91Hf3x8QScv8O:-MWdLdM91Hf3x8QScv8P:b-b2xx9c) ([raw file](https://github.com/memkind/memkind/blob/3a83affb18041033031cc84b53d7b5536e91351f/include/memkind/internal/memtier_private.h#L21)):*
<details><summary><i alt="summary">Quoted 18 lines of code…</i></summary>

> ```
> #if defined(MEMKIND_ATOMIC_C11_SUPPORT)
> #define memkind_atomic_increment(counter, val)                                 \
>     atomic_fetch_add_explicit(&counter, val, memory_order_relaxed)
> #define memkind_atomic_decrement(counter, val)                                 \
>     atomic_fetch_sub_explicit(&counter, val, memory_order_relaxed)
> #elif defined(MEMKIND_ATOMIC_BUILTINS_SUPPORT)
> #define memkind_atomic_increment(counter, val)                                 \
>     __atomic_add_fetch(&counter, val, __ATOMIC_RELAXED)
> #define memkind_atomic_decrement(counter, val)                                 \
>     __atomic_sub_fetch(&counter, val, __ATOMIC_RELAXED)
> #elif defined(MEMKIND_ATOMIC_SYNC_SUPPORT)
> #define memkind_atomic_increment(counter, val)                                 \
>     __sync_add_and_fetch(&counter, val)
> #define memkind_atomic_decrement(counter, val)                                 \
>     __sync_sub_and_fetch(&counter, val)
> #else
> #error "Missing atomic implementation."
> #endif
> ```
</details>

you don't need to expose this in here this is just needed to memkind_memtier.c 
___
*[src/memkind_memtier.c, line 99 at r2](https://reviewable.io/reviews/memkind/memkind/599#-MWd-AE-182CTlOy3-p1:-MWdLoQ45U2OR6ckYeU1:bmy84wb) ([raw file](https://github.com/memkind/memkind/blob/de8f911089827932da93802fda7cae2686ee2452/src/memkind_memtier.c#L99)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

Done
</blockquote></details>

You get me wrong - you extend the policies with static policy, You should overwrite it. After this change, there is no reason to keep a circular policy.
___
*[src/memtier_policies.c, line 26 at r1](https://reviewable.io/reviews/memkind/memkind/599#-MWd-Mjv0tGEYlR8AH2G:-MWdMAc48YZUi9qvy8WV:br338u6) ([raw file](https://github.com/memkind/memkind/blob/ffa9fca8ce262b2a6d0ebb1d687f36a9e7aaeb57/src/memtier_policies.c#L26)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

I use "name" member for logging instead of using ctl_policy_to_str() (this PR removes this function)
</blockquote></details>

get_tier is important every other thing is obsolete - you could keep this data in memkind_memtier layer and it still is readable - now you expose atomic/and every memtier structure to every layer which includes memkind_private.h and this is not needed.
___
*[tiering/ctl.c, line 16 at r2](https://reviewable.io/reviews/memkind/memkind/599#-MWd-gtF2B9kwY5oxWFO:-MWdMNt_BioG6OBCNeRR:b-gy44hq) ([raw file](https://github.com/memkind/memkind/blob/de8f911089827932da93802fda7cae2686ee2452/tiering/ctl.c#L16)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

> ```
> / TODO - remove this after logging cleanup
> ```

this line was not added by mistake - this file is needed for definition of "policy" used in ctl_create_tier_kind_from_env in logging
</blockquote></details>

Why - just track the allocation size is sufficient there is no reason to keep logging every information.


<!-- Sent from Reviewable.io -->

2021-03-25 13:28 UTC, bratpiorka reviewed
> Reviewed 1 of 1 files at r7, 6 of 7 files at r8, 7 of 7 files at r9.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/599)* status: all files reviewed, 5 unresolved discussions (waiting on @michalbiesek and @PatKamin)

___
*[Makefile.am, line 63 at r7](https://reviewable.io/reviews/memkind/memkind/599#-MWdLZLx2j-CUnpE1n1x:-MWdUrwu15bbrpEut6Fv:bvjmffk) ([raw file](https://github.com/memkind/memkind/blob/734be31b134deec78e7a698b3a04673aa45edbc2/Makefile.am#L63)):*
> and

I really don't know what is wrong with this line
___
*[include/memkind/internal/memtier_private.h, line 21 at r5](https://reviewable.io/reviews/memkind/memkind/599#-MWdLdM91Hf3x8QScv8O:-MWdUzV53AjJMso7reYN:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/3a83affb18041033031cc84b53d7b5536e91351f/include/memkind/internal/memtier_private.h#L21)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> #if defined(MEMKIND_ATOMIC_C11_SUPPORT)
> #define memkind_atomic_increment(counter, val)                                 \
>     atomic_fetch_add_explicit(&counter, val, memory_order_relaxed)
> #define memkind_atomic_decrement(counter, val)                                 \
>     atomic_fetch_sub_explicit(&counter, val, memory_order_relaxed)
> #elif defined(MEMKIND_ATOMIC_BUILTINS_SUPPORT)
> #define memkind_atomic_increment(counter, val)                                 \
>     __atomic_add_fetch(&counter, val, __ATOMIC_RELAXED)
> #define memkind_atomic_decrement(counter, val)                                 \
>     __atomic_sub_fetch(&counter, val, __ATOMIC_RELAXED)
> #elif defined(MEMKIND_ATOMIC_SYNC_SUPPORT)
> #define memkind_atomic_increment(counter, val)                                 \
>     __sync_add_and_fetch(&counter, val)
> #define memkind_atomic_decrement(counter, val)                                 \
>     __sync_sub_and_fetch(&counter, val)
> #else
> #error "Missing atomic implementation."
> #endif
> ```
you don't need to expose this in here this is just needed to memkind_memtier.c 
</blockquote></details>

Done.
___
*[src/memkind_memtier.c, line 99 at r2](https://reviewable.io/reviews/memkind/memkind/599#-MWd-AE-182CTlOy3-p1:-MWdSTxr1mPmBw97pEmK:b-7w0eor) ([raw file](https://github.com/memkind/memkind/blob/de8f911089827932da93802fda7cae2686ee2452/src/memkind_memtier.c#L99)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

You get me wrong - you extend the policies with static policy, You should overwrite it. After this change, there is no reason to keep a circular policy.
</blockquote></details>

? After your first comment, I removed circular policy at all. Maybe I'm doing sth wrong if you don't see this changes?
___
*[src/memtier_policies.c, line 26 at r1](https://reviewable.io/reviews/memkind/memkind/599#-MWd-Mjv0tGEYlR8AH2G:-MWdYXLX-w9bFJ8s3HgN:b55rvab) ([raw file](https://github.com/memkind/memkind/blob/ffa9fca8ce262b2a6d0ebb1d687f36a9e7aaeb57/src/memtier_policies.c#L26)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

get_tier is important every other thing is obsolete - you could keep this data in memkind_memtier layer and it still is readable - now you expose atomic/and every memtier structure to every layer which includes memkind_private.h and this is not needed.
</blockquote></details>

.create is needed for creating of .priv - structure where we keep internal, per-policy data. Should I move code from this file to memkind_memtier.c?
___
*[tiering/ctl.c, line 16 at r2](https://reviewable.io/reviews/memkind/memkind/599#-MWd-gtF2B9kwY5oxWFO:-MWdTe909nOeW8mY1EIv:b-oeo39h) ([raw file](https://github.com/memkind/memkind/blob/de8f911089827932da93802fda7cae2686ee2452/tiering/ctl.c#L16)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

Why - just track the allocation size is sufficient there is no reason to keep logging every information.
</blockquote></details>

Currently we are logging policy name and other properties like kind name, ratio, etc. All of them are checked in python test to check if code behaves correctly - should I remove/rewrite these tests?. Also, IMHO too much logging is better than too less logging. Let's do a cleanup of this later, in separate PR, when we'll have implemented few policies (with different names of course) and when we talk what data in log could be useful for user.


<!-- Sent from Reviewable.io -->

2021-03-25 14:22 UTC, michalbiesek requested changes
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/599)* status: all files reviewed, 9 unresolved discussions (waiting on @bratpiorka and @PatKamin)

___
*[include/memkind_memtier.h, line 29 at r9](https://reviewable.io/reviews/memkind/memkind/599#-MWdiJR59iVo464xXkUW:-MWdiJR67WqMDQ98-uuc:b-703ywi) ([raw file](https://github.com/memkind/memkind/blob/f5f8493b7410a8e9142a1b4de5f84f7e1c532c80/include/memkind_memtier.h#L29)):*
> ```
> 1
> ```
why not leave it as 0?
___
*[src/memtier_policies.c, line 26 at r1](https://reviewable.io/reviews/memkind/memkind/599#-MWd-Mjv0tGEYlR8AH2G:-MWdfnyr-rl3MNSk0AZC:b-y0x44q) ([raw file](https://github.com/memkind/memkind/blob/ffa9fca8ce262b2a6d0ebb1d687f36a9e7aaeb57/src/memtier_policies.c#L26)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

.create is needed for creating of .priv - structure where we keep internal, per-policy data. Should I move code from this file to memkind_memtier.c?
</blockquote></details>

ok fair enough create and get_tier methods IMHO you could easily move this to memkind_memtier.c - when these policies will be extending the code could be easily separated, you don't have even move the structures now - now you have only one politic which is in use
___
*[test/memkind_memtier_test.cpp, line 579 at r9](https://reviewable.io/reviews/memkind/memkind/599#-MWdhehD0IXkZGy6xBoQ:-MWdhehD0IXkZGy6xBoR:b-pzpbtl) ([raw file](https://github.com/memkind/memkind/blob/f5f8493b7410a8e9142a1b4de5f84f7e1c532c80/test/memkind_memtier_test.cpp#L579)):*
> ```
> MemkindMemtierStaticThresholdTest
> ```
can MemkindMemtierKindTest just be modified? 
___
*[test/memkind_memtier_test.cpp, line 670 at r9](https://reviewable.io/reviews/memkind/memkind/599#-MWdipaM8u8xLcM0PvrQ:-MWdipaM8u8xLcM0PvrR:bg5ukmw) ([raw file](https://github.com/memkind/memkind/blob/f5f8493b7410a8e9142a1b4de5f84f7e1c532c80/test/memkind_memtier_test.cpp#L670)):*
> ```cpp
>     ASSERT_EQ(32ULL, memtier_tier_allocated_size(m_tier_default));
>     ASSERT_EQ(128ULL, memtier_tier_allocated_size(m_tier_regular));
> ```

And what happened next after you reach the ratio you don't want to test if it is still kept after some allocations?
___
*[test/memkind_memtier_test.cpp, line 671 at r9](https://reviewable.io/reviews/memkind/memkind/599#-MWdihX25WjflIaAj-qd:-MWdihX25WjflIaAj-qe:b1qlnv2) ([raw file](https://github.com/memkind/memkind/blob/f5f8493b7410a8e9142a1b4de5f84f7e1c532c80/test/memkind_memtier_test.cpp#L671)):*
> ```
>     for (size_t i = 0; i < allocs.size(); ++i)
>         memtier_free(allocs[i]);
> ```
    for (auto const &ptr : allocs) {
        memtier_free(ptr);
    }
___
*[test/memkind_memtier_test.cpp, line 693 at r9](https://reviewable.io/reviews/memkind/memkind/599#-MWdjTXe9gj7G0NXlj2w:-MWdjTXe9gj7G0NXlj2x:b-rf94m4) ([raw file](https://github.com/memkind/memkind/blob/f5f8493b7410a8e9142a1b4de5f84f7e1c532c80/test/memkind_memtier_test.cpp#L693)):*
> ```
> m_tier_regular_ratio
> ```
nit: doesn't matter in this case but shouldn't this be normalized - against the first kind?
___
*[test/memkind_memtier_test.cpp, line 695 at r9](https://reviewable.io/reviews/memkind/memkind/599#-MWdkMnQAEre_vco2D3L:-MWdkMnQAEre_vco2D3M:b66vcxn) ([raw file](https://github.com/memkind/memkind/blob/f5f8493b7410a8e9142a1b4de5f84f7e1c532c80/test/memkind_memtier_test.cpp#L695)):*
> ```
>             ASSERT_GE(memtier_tier_allocated_size(m_tier_regular),
>                       regular_alloc_size);
> ```
I could miss something but why? I mean you set regular_alloc_size to memtier_tier_allocated_size(m_tier_regular) a couple lines above so why assert this
___
*[test/memkind_memtier_test.cpp, line 699 at r9](https://reviewable.io/reviews/memkind/memkind/599#-MWdj1Ug5nKmfwocvlLd:-MWdj1Ug5nKmfwocvlLe:be6620k) ([raw file](https://github.com/memkind/memkind/blob/f5f8493b7410a8e9142a1b4de5f84f7e1c532c80/test/memkind_memtier_test.cpp#L699)):*
> ```
>     for (i = 0; i < allocs.size(); ++i)
>         memtier_free(allocs[i]);
> ```
.
___
*[test/memkind_memtier_test.cpp, line 712 at r9](https://reviewable.io/reviews/memkind/memkind/599#-MWdjvBq1Tmgj9A8NDbc:-MWdjvBq1Tmgj9A8NDbd:bhk0lne) ([raw file](https://github.com/memkind/memkind/blob/f5f8493b7410a8e9142a1b4de5f84f7e1c532c80/test/memkind_memtier_test.cpp#L712)):*
> ```
> int operations[14]
> ```
operations_num
___
*[tiering/ctl.c, line 16 at r2](https://reviewable.io/reviews/memkind/memkind/599#-MWd-gtF2B9kwY5oxWFO:-MWdf00E5633bdiYUEcf:bffyjfm) ([raw file](https://github.com/memkind/memkind/blob/de8f911089827932da93802fda7cae2686ee2452/tiering/ctl.c#L16)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

Currently we are logging policy name and other properties like kind name, ratio, etc. All of them are checked in python test to check if code behaves correctly - should I remove/rewrite these tests?. Also, IMHO too much logging is better than too less logging. Let's do a cleanup of this later, in separate PR, when we'll have implemented few policies (with different names of course) and when we talk what data in log could be useful for user.
</blockquote></details>

1. What's the reason to move this there since you already have and even tested here the information about policy - this todo could be easily avoided, you already have your translation here.
2. Create an issue for cleaning this up 


<!-- Sent from Reviewable.io -->

2021-03-25 14:24 UTC, PatKamin reviewed
> Reviewed 2 of 8 files at r1, 1 of 8 files at r3, 6 of 7 files at r9.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/599)* status: all files reviewed, 12 unresolved discussions (waiting on @bratpiorka)

___
*[include/memkind_memtier.h, line 29 at r9](https://reviewable.io/reviews/memkind/memkind/599#-MWde1dwDCbOBcAGAait:-MWde1dwDCbOBcAGAaiu:b-62c9n7) ([raw file](https://github.com/memkind/memkind/blob/f5f8493b7410a8e9142a1b4de5f84f7e1c532c80/include/memkind_memtier.h#L29)):*
> ```objc
>      * Static Threshold policy
>      */
>     MEMTIER_POLICY_STATIC_THRESHOLD = 1,
> ```

Start from 0, unless you have a reason for starting from 1.
___
*[test/memkind_memtier_test.cpp, line 712 at r9](https://reviewable.io/reviews/memkind/memkind/599#-MWdk-f69Z2FQgVdTEiB:-MWdk-f69Z2FQgVdTEiC:beavi69) ([raw file](https://github.com/memkind/memkind/blob/f5f8493b7410a8e9142a1b4de5f84f7e1c532c80/test/memkind_memtier_test.cpp#L712)):*
> ```cpp
>     // allocations should be freed
>     const int operations_num = 14;
>     int operations[14] = {1, 1, -1, 1, -1, -1, 1, 1, 1, -1, -1, 1, -1, -1};
> ```

Add an extra '-1' in place where every allocation is already freed.
___
*[test/tiering_tests.py, line 234 at r9](https://reviewable.io/reviews/memkind/memkind/599#-MWdl4wrDN6X26PX2M4P:-MWdl4wrDN6X26PX2M4Q:b-9v09vq) ([raw file](https://github.com/memkind/memkind/blob/f5f8493b7410a8e9142a1b4de5f84f7e1c532c80/test/tiering_tests.py#L234)):*
> ```Python
>             "Wrong message"
> 
>     # TODO enable this check after implementing full FS_DAX support in
> ```

Remove this comment.


<!-- Sent from Reviewable.io -->

2021-03-26 09:00 UTC, bratpiorka reviewed
> Reviewed 7 of 10 files at r10, 1 of 1 files at r11.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/599)* status: all files reviewed, 11 unresolved discussions (waiting on @michalbiesek and @PatKamin)

___
*[include/memkind_memtier.h, line 29 at r9](https://reviewable.io/reviews/memkind/memkind/599#-MWdiJR59iVo464xXkUW:-MWhVPed9l7y14pqav4V:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/f5f8493b7410a8e9142a1b4de5f84f7e1c532c80/include/memkind_memtier.h#L29)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> 1
> ```
why not leave it as 0?
</blockquote></details>

Done.
___
*[include/memkind_memtier.h, line 29 at r9](https://reviewable.io/reviews/memkind/memkind/599#-MWde1dwDCbOBcAGAait:-MWhVPst0v_vwr6Se6HU:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/f5f8493b7410a8e9142a1b4de5f84f7e1c532c80/include/memkind_memtier.h#L29)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Start from 0, unless you have a reason for starting from 1.
</blockquote></details>

Done.
___
*[test/memkind_memtier_test.cpp, line 579 at r9](https://reviewable.io/reviews/memkind/memkind/599#-MWdhehD0IXkZGy6xBoQ:-MWh_8J2DK35r0rOZpZl:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/f5f8493b7410a8e9142a1b4de5f84f7e1c532c80/test/memkind_memtier_test.cpp#L579)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> MemkindMemtierStaticThresholdTest
> ```
can MemkindMemtierKindTest just be modified? 
</blockquote></details>

Done.
___
*[test/memkind_memtier_test.cpp, line 670 at r9](https://reviewable.io/reviews/memkind/memkind/599#-MWdipaM8u8xLcM0PvrQ:-MWhdniD3YyFFtignFdg:b-fh2m62) ([raw file](https://github.com/memkind/memkind/blob/f5f8493b7410a8e9142a1b4de5f84f7e1c532c80/test/memkind_memtier_test.cpp#L670)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

And what happened next after you reach the ratio you don't want to test if it is still kept after some allocations?
</blockquote></details>

Done. Should I move those allocations to a loop where I check for conditions described in some kind of array? Or what we have currently is fine?
___
*[test/memkind_memtier_test.cpp, line 671 at r9](https://reviewable.io/reviews/memkind/memkind/599#-MWdihX25WjflIaAj-qd:-MWhVVO59P1CHac__0fz:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/f5f8493b7410a8e9142a1b4de5f84f7e1c532c80/test/memkind_memtier_test.cpp#L671)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
>     for (size_t i = 0; i < allocs.size(); ++i)
>         memtier_free(allocs[i]);
> ```
    for (auto const &ptr : allocs) {
        memtier_free(ptr);
    }

</blockquote></details>

Done.
___
*[test/memkind_memtier_test.cpp, line 695 at r9](https://reviewable.io/reviews/memkind/memkind/599#-MWdkMnQAEre_vco2D3L:-MWhjxKWCusLxPoH08rS:bnlb177) ([raw file](https://github.com/memkind/memkind/blob/f5f8493b7410a8e9142a1b4de5f84f7e1c532c80/test/memkind_memtier_test.cpp#L695)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
>             ASSERT_GE(memtier_tier_allocated_size(m_tier_regular),
>                       regular_alloc_size);
> ```
I could miss something but why? I mean you set regular_alloc_size to memtier_tier_allocated_size(m_tier_regular) a couple lines above so why assert this
</blockquote></details>

Yes, I had a bug in a code. But currently we check if ratio before new allocation is lower that desired and if so, next allocation should go to regular tier and we assert if this is true
___
*[test/memkind_memtier_test.cpp, line 699 at r9](https://reviewable.io/reviews/memkind/memkind/599#-MWdj1Ug5nKmfwocvlLd:-MWhVWZy5KWnv2UGAT1q:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/f5f8493b7410a8e9142a1b4de5f84f7e1c532c80/test/memkind_memtier_test.cpp#L699)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
>     for (i = 0; i < allocs.size(); ++i)
>         memtier_free(allocs[i]);
> ```
.
</blockquote></details>

Done.
___
*[test/memkind_memtier_test.cpp, line 712 at r9](https://reviewable.io/reviews/memkind/memkind/599#-MWdjvBq1Tmgj9A8NDbc:-MWhVX4HBP0XWKbdsG6a:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/f5f8493b7410a8e9142a1b4de5f84f7e1c532c80/test/memkind_memtier_test.cpp#L712)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> int operations[14]
> ```
operations_num
</blockquote></details>

Done.
___
*[test/memkind_memtier_test.cpp, line 712 at r9](https://reviewable.io/reviews/memkind/memkind/599#-MWdk-f69Z2FQgVdTEiB:-MWhkIV78r7jgAJu5-V5:b971otf) ([raw file](https://github.com/memkind/memkind/blob/f5f8493b7410a8e9142a1b4de5f84f7e1c532c80/test/memkind_memtier_test.cpp#L712)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Add an extra '-1' in place where every allocation is already freed.
</blockquote></details>

I don't get this. Could you be more precise where I should add these "-1"?
___
*[test/tiering_tests.py, line 234 at r9](https://reviewable.io/reviews/memkind/memkind/599#-MWdl4wrDN6X26PX2M4P:-MWhVXgv8E-762q6Uzqh:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/f5f8493b7410a8e9142a1b4de5f84f7e1c532c80/test/tiering_tests.py#L234)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Remove this comment.
</blockquote></details>

Done.
___
*[tiering/ctl.c, line 16 at r2](https://reviewable.io/reviews/memkind/memkind/599#-MWd-gtF2B9kwY5oxWFO:-MWhYt8A7trOHI_yyy3M:bfk6t8) ([raw file](https://github.com/memkind/memkind/blob/de8f911089827932da93802fda7cae2686ee2452/tiering/ctl.c#L16)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

1. What's the reason to move this there since you already have and even tested here the information about policy - this todo could be easily avoided, you already have your translation here.
2. Create an issue for cleaning this up 
</blockquote></details>

Done, I reverted my changes and removed "name" member from policy. I also created a story for logging cleanup: AESC-45


<!-- Sent from Reviewable.io -->

2021-03-26 10:10 UTC, michalbiesek requested changes
> Reviewed 4 of 10 files at r10.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/599)* status: all files reviewed, 7 unresolved discussions (waiting on @bratpiorka and @PatKamin)

___
*[src/memkind_memtier.c, line 55 at r11](https://reviewable.io/reviews/memkind/memkind/599#-MWhp6Kw2Q4hBs0D-qOt:-MWhp6Kw2Q4hBs0D-qOu:b-wjwv8b) ([raw file](https://github.com/memkind/memkind/blob/8948be7aa32040c09cf3dba62ec195505e1dbe10/src/memkind_memtier.c#L55)):*
> ```
>  struct memtier_builder *builder; // Tiering kind configuration
> ```

What should memtier_kind consists of:

> ```
> unsigned size;                             // Number of memory tiers
> struct memtier_policy *policy; // Tiering policy
> struct memtier_tier_cfg *cfg;    // Memory Tier configuration
> ```

With your change it supports it but I think we should avoid modifying memtier_builder itself, feel free to modify the deep copy mechanism in construct kind.

For builder object -> the object used before construct kind, it is sufficient to know which policy it is (as it is now)
memtier_builder doesn't need to know anything about the policy structure - it's private data.

Actually, I think this is a better place: extend memtier_kind with your policy struct.
Currently, memtier_kind is basically a copy of the builder but without any chance to modify its data.
Although the representation should change.

Maybe rename struct memtier_builder will be beneficial here, but this is another consideration - not related to this PR.
___
*[src/memkind_memtier.c, line 63 at r11](https://reviewable.io/reviews/memkind/memkind/599#-MWhoj5F01erf_ZcZyAR:-MWhoj5F01erf_ZcZyAS:bax6bdp) ([raw file](https://github.com/memkind/memkind/blob/8948be7aa32040c09cf3dba62ec195505e1dbe10/src/memkind_memtier.c#L63)):*
> ```
>  char name[POLICY_NAME_LENGTH];
> ```
not used so it could be removed.
___
*[src/memkind_memtier.c, line 226 at r11](https://reviewable.io/reviews/memkind/memkind/599#-MWhqTvF5WMHrFvb4oD4:-MWhqTvF5WMHrFvb4oD5:b-dcjyts) ([raw file](https://github.com/memkind/memkind/blob/8948be7aa32040c09cf3dba62ec195505e1dbe10/src/memkind_memtier.c#L226)):*
> ```
> builder->policy->create(builder);
> ```
this could be done in memtier_builder_construct_kind, the logic of creating tiering policy private data.
Additionally, you could clean this policy private data when destroying memtier kind will be called, correct me if I am wrong, but now calling multiple times memtier_builder_set_policy results with memory leak.
___
*[src/memkind_memtier.c, line 231 at r11](https://reviewable.io/reviews/memkind/memkind/599#-MWhq7QhEDFKZjwE93BQ:-MWhq7QhEDFKZjwE93BR:b-ym2syc) ([raw file](https://github.com/memkind/memkind/blob/8948be7aa32040c09cf3dba62ec195505e1dbe10/src/memkind_memtier.c#L231)):*
> ```
> tier_kind->builder->policy->get_tier(tier_kind)
> ```
If you go with the solution mentioned in other comments this get_tier will be assigned to memtier_kind wouldn't be simplified here?
tier_kind->policy->get_tier(tier_kind)
___
*[test/memkind_memtier_test.cpp, line 670 at r9](https://reviewable.io/reviews/memkind/memkind/599#-MWdipaM8u8xLcM0PvrQ:-MWhm83NDqyd94q0rr_k:bnp1ga6) ([raw file](https://github.com/memkind/memkind/blob/f5f8493b7410a8e9142a1b4de5f84f7e1c532c80/test/memkind_memtier_test.cpp#L670)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

Done. Should I move those allocations to a loop where I check for conditions described in some kind of array? Or what we have currently is fine?
</blockquote></details>

IMHO is fine.


<!-- Sent from Reviewable.io -->

2021-03-26 12:06 UTC, closed without merging

2021-03-26 12:06 UTC, michalbiesek commented
Please change target branch to https://github.com/memkind/memkind/tree/feat-memory-tiering