Handle multiple tiers in env var
memkind/memkind pull request #604
Opened 2021-03-26 12:50 UTC by PatKamin

### Description

### Types of changes

- [ ] Bugfix (non-breaking change which fixes issue linked in Description above)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation (correction or otherwise)
- [ ] Cosmetics (whitespace, appearance)
- [ ] Other

### Checklist

- [ ] Code compiles without errors
- [ ] All tests pass locally with my changes (see TESTING section in CONTRIBUTING file)
- [ ] Created tests which will fail without the change (if possible)
- [ ] Extended the README/documentation (if necessary)
- [ ] All newly added files have proprietary license (if necessary)
- [ ] All newly added files are referenced in MANIFEST files (if necessary)

## Further comments

2021-03-26 12:58 UTC, michalbiesek reviewed
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/604)* status: 0 of 2 files reviewed, 7 unresolved discussions (waiting on @PatKamin)

___
*[test/tiering_tests.py, line 284 at r1](https://reviewable.io/reviews/memkind/memkind/604#-MWia0NZ7QcC47G88szV:-MWia0NZ7QcC47G88szW:b-qu9g9b) ([raw file](https://github.com/memkind/memkind/blob/05cfb89ded5cad6731d8291c34013e87f1618901/test/tiering_tests.py#L284)):*
<details><summary><i alt="summary">Quoted 8 lines of code…</i></summary>

> ```
>     @pytest.mark.parametrize("pmem_size",
>                              ["1", str(MEMKIND_PMEM_MIN_SIZE - 1)])
>     def test_FSDAX_pmem_size_too_small(self, pmem_size):
>         output = self.get_ld_preload_cmd_output(
>             "MEMKIND_MEM_TIERING_CONFIG=FS_DAX:/tmp/:" + pmem_size + ":1," +
>             self.default_policy, validate_retcode=False)
>         assert output[0] == self.log_error_prefix + \
>             "Error with parsing MEMKIND_MEM_TIERING_CONFIG", "Wrong message"
> ```
</details>

split this by separate commit please - correct me if I am wrong but could this be in test_FSDAX_pmem_size_outside_limits as extending params?
___
*[test/tiering_tests.py, line 444 at r1](https://reviewable.io/reviews/memkind/memkind/604#-MWiaGxZCEvt6WI9KjDJ:-MWiaGxZCEvt6WI9KjDK:b-kej6lg) ([raw file](https://github.com/memkind/memkind/blob/05cfb89ded5cad6731d8291c34013e87f1618901/test/tiering_tests.py#L444)):*
> ```
> validate_retcode=False
> ```
remove
___
*[tiering/ctl.c, line 18 at r1](https://reviewable.io/reviews/memkind/memkind/604#-MWib3NJB_-wcVbn5TUC:-MWib3NJB_-wcVbn5TUD:b93t5b9) ([raw file](https://github.com/memkind/memkind/blob/05cfb89ded5cad6731d8291c34013e87f1618901/tiering/ctl.c#L18)):*
> ```
> unsigned tier_count
> ```
static?
___
*[tiering/ctl.c, line 56 at r1](https://reviewable.io/reviews/memkind/memkind/604#-MWiaZ2kE1LW-5XC4agW:-MWiaZ2kE1LW-5XC4agX:b-y0i0hv) ([raw file](https://github.com/memkind/memkind/blob/05cfb89ded5cad6731d8291c34013e87f1618901/tiering/ctl.c#L56)):*
> ```
> *tier_cfgs
> ```
where you free the allocated memory?
___
*[tiering/ctl.c, line 264 at r1](https://reviewable.io/reviews/memkind/memkind/604#-MWiaLc7EobBoEHPdbSb:-MWiaLc7EobBoEHPdbSc:b-dg4vhb) ([raw file](https://github.com/memkind/memkind/blob/05cfb89ded5cad6731d8291c34013e87f1618901/tiering/ctl.c#L264)):*
> ```
> tier_cfgs
> ```
check and handle the situation in case of failure
___
*[tiering/ctl.c, line 264 at r1](https://reviewable.io/reviews/memkind/memkind/604#-MWiad_W5EToikzi3RyE:-MWiad_W5EToikzi3RyF:bgmu84q) ([raw file](https://github.com/memkind/memkind/blob/05cfb89ded5cad6731d8291c34013e87f1618901/tiering/ctl.c#L264)):*
> ```
> calloc
> ```
memkind_calloc(MEMKIND_DEFAULT ...
___
*[tiering/ctl.c, line 266 at r1](https://reviewable.io/reviews/memkind/memkind/604#-MWib-5ZDNxnImSOxRA1:-MWib-5ZDNxnImSOxRA2:b-gbq8u3) ([raw file](https://github.com/memkind/memkind/blob/05cfb89ded5cad6731d8291c34013e87f1618901/tiering/ctl.c#L266)):*
> ```
> query_count - 1
> ```
tier_count


<!-- Sent from Reviewable.io -->

2021-03-26 13:52 UTC, PatKamin reviewed
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/604)* status: 0 of 2 files reviewed, 7 unresolved discussions (waiting on @michalbiesek)

___
*[test/tiering_tests.py, line 284 at r1](https://reviewable.io/reviews/memkind/memkind/604#-MWia0NZ7QcC47G88szV:-MWijjU0Cg2pZQod1b80:bvok8nj) ([raw file](https://github.com/memkind/memkind/blob/05cfb89ded5cad6731d8291c34013e87f1618901/test/tiering_tests.py#L284)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
>     @pytest.mark.parametrize("pmem_size",
>                              ["1", str(MEMKIND_PMEM_MIN_SIZE - 1)])
>     def test_FSDAX_pmem_size_too_small(self, pmem_size):
>         output = self.get_ld_preload_cmd_output(
>             "MEMKIND_MEM_TIERING_CONFIG=FS_DAX:/tmp/:" + pmem_size + ":1," +
>             self.default_policy, validate_retcode=False)
>         assert output[0] == self.log_error_prefix + \
>             "Error with parsing MEMKIND_MEM_TIERING_CONFIG", "Wrong message"
> ```
split this by separate commit please - correct me if I am wrong but could this be in test_FSDAX_pmem_size_outside_limits as extending params?
</blockquote></details>

No, the error message is different. Moved to a new commit.
___
*[test/tiering_tests.py, line 444 at r1](https://reviewable.io/reviews/memkind/memkind/604#-MWiaGxZCEvt6WI9KjDJ:-MWik8YO0vSJsPxMQKDR:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/05cfb89ded5cad6731d8291c34013e87f1618901/test/tiering_tests.py#L444)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> validate_retcode=False
> ```
remove
</blockquote></details>

Done.
___
*[tiering/ctl.c, line 18 at r1](https://reviewable.io/reviews/memkind/memkind/604#-MWib3NJB_-wcVbn5TUC:-MWikCsmE07_9A_gHxjL:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/05cfb89ded5cad6731d8291c34013e87f1618901/tiering/ctl.c#L18)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> unsigned tier_count
> ```
static?
</blockquote></details>

Done.
___
*[tiering/ctl.c, line 56 at r1](https://reviewable.io/reviews/memkind/memkind/604#-MWiaZ2kE1LW-5XC4agW:-MWil3lFDD0wDBbFtjK5:bz8ca4o) ([raw file](https://github.com/memkind/memkind/blob/05cfb89ded5cad6731d8291c34013e87f1618901/tiering/ctl.c#L56)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> *tier_cfgs
> ```
where you free the allocated memory?
</blockquote></details>

Added memkind_free()
___
*[tiering/ctl.c, line 264 at r1](https://reviewable.io/reviews/memkind/memkind/604#-MWiad_W5EToikzi3RyE:-MWilHKC5sEReUBmUEW3:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/05cfb89ded5cad6731d8291c34013e87f1618901/tiering/ctl.c#L264)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> calloc
> ```
memkind_calloc(MEMKIND_DEFAULT ...
</blockquote></details>

Done.
___
*[tiering/ctl.c, line 264 at r1](https://reviewable.io/reviews/memkind/memkind/604#-MWiaLc7EobBoEHPdbSb:-MWilHvpB6qes-b6Xagd:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/05cfb89ded5cad6731d8291c34013e87f1618901/tiering/ctl.c#L264)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> tier_cfgs
> ```
check and handle the situation in case of failure
</blockquote></details>

Done.
___
*[tiering/ctl.c, line 266 at r1](https://reviewable.io/reviews/memkind/memkind/604#-MWib-5ZDNxnImSOxRA1:-MWilmxLC5NCmM0ti3dq:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/05cfb89ded5cad6731d8291c34013e87f1618901/tiering/ctl.c#L266)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> query_count - 1
> ```
tier_count
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-03-26 14:03 UTC, michalbiesek requested changes
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/604)* status: 1 of 2 files reviewed, 6 unresolved discussions (waiting on @PatKamin)

___
*[test/tiering_tests.py, line 438 at r3](https://reviewable.io/reviews/memkind/memkind/604#-MWipmM3-PlS4DvlEhw0:-MWipmM3-PlS4DvlEhw1:b-t8v63n) ([raw file](https://github.com/memkind/memkind/blob/35f6172fb8ff48c97d380058445878659c210da4/test/tiering_tests.py#L438)):*
> ```
> def test_multiple_tiers
> ```
can you handle here the case with three kinds (two FS_DAX) ?
___
*[tiering/ctl.c, line 283 at r3](https://reviewable.io/reviews/memkind/memkind/604#-MWiq287-DOw6gccqgfz:-MWiq287-DOw6gccqgg-:b-wma0sh) ([raw file](https://github.com/memkind/memkind/blob/35f6172fb8ff48c97d380058445878659c210da4/tiering/ctl.c#L283)):*
> ```
> ret = ctl_parse_policy(qbuf, policy);
> ```
you miss checking ret status
___
*[tiering/ctl.c, line 299 at r3](https://reviewable.io/reviews/memkind/memkind/604#-MWipN3y9VT2eGkB83Gc:-MWipN3y9VT2eGkB83Gd:bwijeb6) ([raw file](https://github.com/memkind/memkind/blob/35f6172fb8ff48c97d380058445878659c210da4/tiering/ctl.c#L299)):*
> ```
> FS_DAX
> ```
please restore this - open separate PR if you like for this kind of changes if you like but in this PR I would like to focus on support for multiple tier
___
*[tiering/ctl.c, line 337 at r3](https://reviewable.io/reviews/memkind/memkind/604#-MWioohd4rEURebcm4ym:-MWioohd4rEURebcm4yn:b-2slmr7) ([raw file](https://github.com/memkind/memkind/blob/35f6172fb8ff48c97d380058445878659c210da4/tiering/ctl.c#L337)):*
> ```
> return NULL;
> ```
goto builder_delete; ?
___
*[tiering/ctl.c, line 345 at r3](https://reviewable.io/reviews/memkind/memkind/604#-MWiopnn3RimuMb48kjc:-MWiopnn3RimuMb48kjd:b-2slmr7) ([raw file](https://github.com/memkind/memkind/blob/35f6172fb8ff48c97d380058445878659c210da4/tiering/ctl.c#L345)):*
> ```
> return NULL;
> ```
goto builder_delete; ?
___
*[tiering/ctl.c, line 361 at r3](https://reviewable.io/reviews/memkind/memkind/604#-MWip7tv3psfp0YLLK0w:-MWip7tv3psfp0YLLK0x:brz0gwt) ([raw file](https://github.com/memkind/memkind/blob/35f6172fb8ff48c97d380058445878659c210da4/tiering/ctl.c#L361)):*
> ```
>     for (i = 0; i < tier_count; ++i) {
>         memkind_free(MEMKIND_DEFAULT, tier_cfgs);
>     }
> ```
shouldn't this be moved I mean called in case of builder_delete?


<!-- Sent from Reviewable.io -->

2021-03-29 07:42 UTC, bratpiorka reviewed
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/604)* status: 1 of 2 files reviewed, 8 unresolved discussions (waiting on @PatKamin)

___
*[test/tiering_tests.py, line 449 at r3](https://reviewable.io/reviews/memkind/memkind/604#-MWwuP-qC-qzux-xYNdQ:-MWwuP-qC-qzux-xYNdR:bp1dfzp) ([raw file](https://github.com/memkind/memkind/blob/35f6172fb8ff48c97d380058445878659c210da4/test/tiering_tests.py#L449)):*
> ```
> self.kind_name_dict.get('DRAM')
> ```

use self.kind_name_dict.get('FS_DAX')
___
*[tiering/ctl.c, line 19 at r2](https://reviewable.io/reviews/memkind/memkind/604#-MWwvKh97gK1U0DnfzRC:-MWwvKh97gK1U0DnfzRD:bji6r80) ([raw file](https://github.com/memkind/memkind/blob/3d87ae155c80d072d9f9b35cf3045fd05bf7b784/tiering/ctl.c#L19)):*
> ```C
> 
> static unsigned tier_count;
> static struct memtier_tier *tiers[64] = {NULL};
> ```

where do you use this?


<!-- Sent from Reviewable.io -->

2021-03-29 07:45 UTC, bratpiorka reviewed
> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/604)* status: all files reviewed, 9 unresolved discussions (waiting on @PatKamin)

___
*[tiering/ctl.c, line 56 at r2](https://reviewable.io/reviews/memkind/memkind/604#-MWwwBr3-Ga7TDVJacJl:-MWwwBr3-Ga7TDVJacJm:b-g4ilnc) ([raw file](https://github.com/memkind/memkind/blob/3d87ae155c80d072d9f9b35cf3045fd05bf7b784/tiering/ctl.c#L56)):*
> ```C
>     memkind_free(MEMKIND_DEFAULT, fs_dax_reg_g.kinds);
> }
> static ctl_tier_cfg *tier_cfgs;
> ```

please move this to the top of this  file


<!-- Sent from Reviewable.io -->

2021-03-29 10:59 UTC, PatKamin reviewed
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/604)* status: 0 of 2 files reviewed, 9 unresolved discussions (waiting on @bratpiorka, @michalbiesek, and @PatKamin)

___
*[test/tiering_tests.py, line 438 at r3](https://reviewable.io/reviews/memkind/memkind/604#-MWipmM3-PlS4DvlEhw0:-MWxRE0x3pd82RtA_qwS:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/35f6172fb8ff48c97d380058445878659c210da4/test/tiering_tests.py#L438)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> def test_multiple_tiers
> ```
can you handle here the case with three kinds (two FS_DAX) ?
</blockquote></details>

Done.
___
*[test/tiering_tests.py, line 449 at r3](https://reviewable.io/reviews/memkind/memkind/604#-MWwuP-qC-qzux-xYNdQ:-MWxRcnN0sp5LHbABCYY:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/35f6172fb8ff48c97d380058445878659c210da4/test/tiering_tests.py#L449)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

> ```
> self.kind_name_dict.get('DRAM')
> ```

use self.kind_name_dict.get('FS_DAX')
</blockquote></details>

Done.
___
*[tiering/ctl.c, line 19 at r2](https://reviewable.io/reviews/memkind/memkind/604#-MWwvKh97gK1U0DnfzRC:-MWxSiQvAbdbyM_zRw3c:bb7yrnl) ([raw file](https://github.com/memkind/memkind/blob/3d87ae155c80d072d9f9b35cf3045fd05bf7b784/tiering/ctl.c#L19)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

where do you use this?
</blockquote></details>

Added the usage.
___
*[tiering/ctl.c, line 56 at r2](https://reviewable.io/reviews/memkind/memkind/604#-MWwwBr3-Ga7TDVJacJl:-MWxVNHS7CHd8Pmlp2cI:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/3d87ae155c80d072d9f9b35cf3045fd05bf7b784/tiering/ctl.c#L56)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

please move this to the top of this  file
</blockquote></details>

Done.
___
*[tiering/ctl.c, line 283 at r3](https://reviewable.io/reviews/memkind/memkind/604#-MWiq287-DOw6gccqgfz:-MWxVkzu8sv9X8u3FfMX:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/35f6172fb8ff48c97d380058445878659c210da4/tiering/ctl.c#L283)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> ret = ctl_parse_policy(qbuf, policy);
> ```
you miss checking ret status
</blockquote></details>

Done.
___
*[tiering/ctl.c, line 299 at r3](https://reviewable.io/reviews/memkind/memkind/604#-MWipN3y9VT2eGkB83Gc:-MWxWaxD7dGhe0YXAi5m:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/35f6172fb8ff48c97d380058445878659c210da4/tiering/ctl.c#L299)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> FS_DAX
> ```
please restore this - open separate PR if you like for this kind of changes if you like but in this PR I would like to focus on support for multiple tier
</blockquote></details>

Done.
___
*[tiering/ctl.c, line 345 at r3](https://reviewable.io/reviews/memkind/memkind/604#-MWiopnn3RimuMb48kjc:-MWx_9u64Owzgy6pVUB1:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/35f6172fb8ff48c97d380058445878659c210da4/tiering/ctl.c#L345)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> return NULL;
> ```
goto builder_delete; ?
</blockquote></details>

Done.
___
*[tiering/ctl.c, line 361 at r3](https://reviewable.io/reviews/memkind/memkind/604#-MWip7tv3psfp0YLLK0w:-MWxaR-ABGNV7GLFtkBd:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/35f6172fb8ff48c97d380058445878659c210da4/tiering/ctl.c#L361)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
>     for (i = 0; i < tier_count; ++i) {
>         memkind_free(MEMKIND_DEFAULT, tier_cfgs);
>     }
> ```
shouldn't this be moved I mean called in case of builder_delete?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-03-29 11:09 UTC, PatKamin reviewed
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/604)* status: 0 of 2 files reviewed, 9 unresolved discussions (waiting on @bratpiorka and @michalbiesek)

___
*[tiering/ctl.c, line 337 at r3](https://reviewable.io/reviews/memkind/memkind/604#-MWioohd4rEURebcm4ym:-MWxf3abEKxHlsIrOWqX:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/35f6172fb8ff48c97d380058445878659c210da4/tiering/ctl.c#L337)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> return NULL;
> ```
goto builder_delete; ?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-03-29 11:19 UTC, michalbiesek requested changes
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/604)* status: 0 of 2 files reviewed, 7 unresolved discussions (waiting on @bratpiorka, @michalbiesek, and @PatKamin)

___
*[tiering/ctl.c, line 283 at r3](https://reviewable.io/reviews/memkind/memkind/604#-MWiq287-DOw6gccqgfz:-MWxe3NZ2_UNnGZzren-:bprgdji) ([raw file](https://github.com/memkind/memkind/blob/35f6172fb8ff48c97d380058445878659c210da4/tiering/ctl.c#L283)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

return -1 ?
___
*[tiering/ctl.c, line 386 at r5](https://reviewable.io/reviews/memkind/memkind/604#-MWxeLnd0v7gZWbveXAl:-MWxeLnd0v7gZWbveXAm:b-st1xza) ([raw file](https://github.com/memkind/memkind/blob/0865c3c350a0bba4629f22f71d23365d26acf98e/tiering/ctl.c#L386)):*
> ```
> tier_delete
> ```
tiers_delete
___
*[tiering/ctl.c, line 387 at r7](https://reviewable.io/reviews/memkind/memkind/604#-MWxgpXG9JHl8g2UmX0L:-MWxgpXH8-vkuP2Qs5WS:b-w7n8g4) ([raw file](https://github.com/memkind/memkind/blob/b6b1a5526d66a53edbd2556e3a4a7352047c7d0c/tiering/ctl.c#L387)):*
<details><summary><i alt="summary">Quoted 6 lines of code…</i></summary>

> ```
>     for (i = 0; i < created_tiers; ++i) {
>         memtier_tier_delete(tiers[i]);
>     }
>     for (i = 0; i < tier_count; ++i) {
>         memkind_free(MEMKIND_DEFAULT, tier_cfgs);
>     }
> ```
</details>

Fix this, (memkind_free) and make it a static method since you should call both of this function on the ctl_destroy_kind method as well


<!-- Sent from Reviewable.io -->

2021-03-29 11:23 UTC, michalbiesek requested changes
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/604)* status: 0 of 2 files reviewed, 9 unresolved discussions (waiting on @bratpiorka, @michalbiesek, and @PatKamin)

___
*[tiering/ctl.c, line 335 at r7](https://reviewable.io/reviews/memkind/memkind/604#-MWxhd6388ast89qTlAd:-MWxhd6388ast89qTlAe:bmtefq4) ([raw file](https://github.com/memkind/memkind/blob/b6b1a5526d66a53edbd2556e3a4a7352047c7d0c/tiering/ctl.c#L335)):*
> ```
> struct memtier_tier *curr_tier = NULL;
> ```
Actually, do you need this?
___
*[tiering/ctl.c, line 354 at r7](https://reviewable.io/reviews/memkind/memkind/604#-MWxhrRT1ErVT4xE7ciy:-MWxhrRT1ErVT4xE7ciz:b-o85zlw) ([raw file](https://github.com/memkind/memkind/blob/b6b1a5526d66a53edbd2556e3a4a7352047c7d0c/tiering/ctl.c#L354)):*
> ```
> created_tiers = i;
> ```

can this just be assign once per loop (now you have 3 places where you assign created_tiers as:
<details><summary><i alt="summary">Quoted 5 lines of code…</i></summary>

> ```
>       curr_tier = memtier_tier_new(kind);
>      if (curr_tier == NULL) {
>        goto builder_delete;
>      }
>      created_tiers = i;
> ```
</details>



<!-- Sent from Reviewable.io -->

2021-03-29 11:24 UTC, michalbiesek requested changes
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/604)* status: 0 of 2 files reviewed, 9 unresolved discussions (waiting on @bratpiorka, @michalbiesek, and @PatKamin)

___
*[tiering/ctl.c, line 283 at r3](https://reviewable.io/reviews/memkind/memkind/604#-MWiq287-DOw6gccqgfz:-MWxiSQk5l284nhULe3o:b-emz3su) ([raw file](https://github.com/memkind/memkind/blob/35f6172fb8ff48c97d380058445878659c210da4/tiering/ctl.c#L283)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

return -1 ?
</blockquote></details>

nit: (ret !=0) -  it could be if(ret) but be consistent please at least in this function


<!-- Sent from Reviewable.io -->

2021-03-29 11:25 UTC, bratpiorka reviewed
> Reviewed 1 of 2 files at r4, 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/604)* status: all files reviewed, 6 unresolved discussions (waiting on @michalbiesek and @PatKamin)



<!-- Sent from Reviewable.io -->

2021-03-29 14:28 UTC, PatKamin reviewed
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/604)* status: all files reviewed, 6 unresolved discussions (waiting on @michalbiesek)

___
*[tiering/ctl.c, line 283 at r3](https://reviewable.io/reviews/memkind/memkind/604#-MWiq287-DOw6gccqgfz:-MWxpGLwDI6s6MtWgoLn:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/35f6172fb8ff48c97d380058445878659c210da4/tiering/ctl.c#L283)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

nit: (ret !=0) -  it could be if(ret) but be consistent please at least in this function
</blockquote></details>

Done.
___
*[tiering/ctl.c, line 386 at r5](https://reviewable.io/reviews/memkind/memkind/604#-MWxeLnd0v7gZWbveXAl:-MWyM1DkAYrWl0H92TPR:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/0865c3c350a0bba4629f22f71d23365d26acf98e/tiering/ctl.c#L386)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> tier_delete
> ```
tiers_delete
</blockquote></details>

Done.
___
*[tiering/ctl.c, line 335 at r7](https://reviewable.io/reviews/memkind/memkind/604#-MWxhd6388ast89qTlAd:-MWxpRhJEHxKuHinSW3S:b-8va0m1) ([raw file](https://github.com/memkind/memkind/blob/b6b1a5526d66a53edbd2556e3a4a7352047c7d0c/tiering/ctl.c#L335)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> struct memtier_tier *curr_tier = NULL;
> ```
Actually, do you need this?
</blockquote></details>

Not needed. Removed.
___
*[tiering/ctl.c, line 354 at r7](https://reviewable.io/reviews/memkind/memkind/604#-MWxhrRT1ErVT4xE7ciy:-MWyLzuU9zs2SlwTpFbA:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/b6b1a5526d66a53edbd2556e3a4a7352047c7d0c/tiering/ctl.c#L354)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> created_tiers = i;
> ```

can this just be assign once per loop (now you have 3 places where you assign created_tiers as:

> ```
>       curr_tier = memtier_tier_new(kind);
>      if (curr_tier == NULL) {
>        goto builder_delete;
>      }
>      created_tiers = i;
> ```
</blockquote></details>

Done.
___
*[tiering/ctl.c, line 387 at r7](https://reviewable.io/reviews/memkind/memkind/604#-MWxgpXG9JHl8g2UmX0L:-MWyN2TXCvChrDoHYils:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/b6b1a5526d66a53edbd2556e3a4a7352047c7d0c/tiering/ctl.c#L387)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
>     for (i = 0; i < created_tiers; ++i) {
>         memtier_tier_delete(tiers[i]);
>     }
>     for (i = 0; i < tier_count; ++i) {
>         memkind_free(MEMKIND_DEFAULT, tier_cfgs);
>     }
> ```
Fix this, (memkind_free) and make it a static method since you should call both of this function on the ctl_destroy_kind method as well
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-03-29 14:53 UTC, michalbiesek requested changes
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/604)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @bratpiorka and @PatKamin)

___
*[tiering/ctl.c, line 362 at r9](https://reviewable.io/reviews/memkind/memkind/604#-MWyR_UR26CvJTkRJcH4:-MWyR_USDfzdh8ToXlnp:b-y9ehdm) ([raw file](https://github.com/memkind/memkind/blob/10f8657fc3ba98b06bf9e5adc301fcf7ed408d52/tiering/ctl.c#L362)):*
> ```
>         if (!builder) {
>             goto tiers_delete;
>         }
> ```
this should be moved I believe (before the loop). and goto should be updated as well.
See that after this change:
<details><summary><i alt="summary">Quoted 6 lines of code…</i></summary>

> ```
>builder_delete:
>    memtier_builder_delete(builder);
> tiers_delete:
>    ctl_destroy_tiers(created_tiers);
>    ctl_destroy_fs_dax_reg();
>    return NULL;
> ```
</details>


should be modified to:
<details><summary><i alt="summary">Quoted 6 lines of code…</i></summary>

> ```
> tiers_delete:
>    ctl_destroy_tiers(created_tiers);
>    ctl_destroy_fs_dax_reg();
>builder_delete:
>    memtier_builder_delete(builder);
>    return NULL;
> ```
</details>

___
*[tiering/ctl.c, line 372 at r9](https://reviewable.io/reviews/memkind/memkind/604#-MWySjN26eGUdOUMX6_x:-MWySjN26eGUdOUMX6_y:bqnh1y0) ([raw file](https://github.com/memkind/memkind/blob/10f8657fc3ba98b06bf9e5adc301fcf7ed408d52/tiering/ctl.c#L372)):*
> ```
> memkind_free(MEMKIND_DEFAULT, tier_cfgs);
> ```
If you free this what happened at the end of the application - when ctl_destroy_kind is called, you call memkind_free(MEMKIND_DEFAULT, tier_cfgs); second time.


<!-- Sent from Reviewable.io -->

2021-03-29 15:09 UTC, michalbiesek requested changes
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/604)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @bratpiorka and @PatKamin)

___
*[tiering/ctl.c, line 348 at r9](https://reviewable.io/reviews/memkind/memkind/604#-MWyWUW_82-fmGl6V_QL:-MWyWUW_82-fmGl6V_QM:b-15ms5c) ([raw file](https://github.com/memkind/memkind/blob/10f8657fc3ba98b06bf9e5adc301fcf7ed408d52/tiering/ctl.c#L348)):*
> ```
> &tier_cfgs[i
> ```
I am fully aware that you want to clean up it later, but see what happened here - you could just pass i here.
tier_cfgs is static.


<!-- Sent from Reviewable.io -->

2021-03-29 15:13 UTC, michalbiesek reviewed
> Reviewed 1 of 1 files at r9.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/604)* status: 1 of 2 files reviewed, 4 unresolved discussions (waiting on @bratpiorka and @PatKamin)

___
*[test/tiering_tests.py, line 443 at r9](https://reviewable.io/reviews/memkind/memkind/604#-MWyXfyw14_IQDBiWPIc:-MWyXfyw14_IQDBiWPId:b-9u01pg) ([raw file](https://github.com/memkind/memkind/blob/10f8657fc3ba98b06bf9e5adc301fcf7ed408d52/test/tiering_tests.py#L443)):*
> ```
> M = 1024 * 1024
> ```
nit: IMHO you should have some static method for this, translation size see that you do same thing (the translation) in:


    def test_FSDAX_pmem_size_with_suffix(self, pmem_size):
        output = self.get_ld_preload_cmd_output(
            "MEMKIND_MEM_TIERING_CONFIG=FS_DAX:/tmp/:" +
            pmem_size + ":1," + self.default_policy,
            log_level="2")
        assert self.log_debug_prefix + "kind_name: " + \
            self.kind_name_dict.get('FS_DAX') in output, "Wrong message"
        assert self.log_debug_prefix + "pmem_path: /tmp/" in output, \
            "Wrong message"
        assert self.log_debug_prefix + "pmem_size: 1073741824" in output, \


<!-- Sent from Reviewable.io -->

2021-03-29 15:35 UTC, PatKamin reviewed
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/604)* status: 0 of 2 files reviewed, 4 unresolved discussions (waiting on @bratpiorka, @michalbiesek, and @PatKamin)

___
*[tiering/ctl.c, line 348 at r9](https://reviewable.io/reviews/memkind/memkind/604#-MWyWUW_82-fmGl6V_QL:-MWyZfcnAbthQmD8WcYu:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/10f8657fc3ba98b06bf9e5adc301fcf7ed408d52/tiering/ctl.c#L348)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> &tier_cfgs[i
> ```
I am fully aware that you want to clean up it later, but see what happened here - you could just pass i here.
tier_cfgs is static.
</blockquote></details>

Done.
___
*[tiering/ctl.c, line 362 at r9](https://reviewable.io/reviews/memkind/memkind/604#-MWyR_UR26CvJTkRJcH4:-MWy_ex14Z3zo4oDU9i-:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/10f8657fc3ba98b06bf9e5adc301fcf7ed408d52/tiering/ctl.c#L362)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
>         if (!builder) {
>             goto tiers_delete;
>         }
> ```
this should be moved I believe (before the loop). and goto should be updated as well.
See that after this change:

> ```
>builder_delete:
>    memtier_builder_delete(builder);
> tiers_delete:
>    ctl_destroy_tiers(created_tiers);
>    ctl_destroy_fs_dax_reg();
>    return NULL;
> ```

should be modified to:
> ```
> tiers_delete:
>    ctl_destroy_tiers(created_tiers);
>    ctl_destroy_fs_dax_reg();
>builder_delete:
>    memtier_builder_delete(builder);
>    return NULL;
> ```

</blockquote></details>

Done.
___
*[tiering/ctl.c, line 372 at r9](https://reviewable.io/reviews/memkind/memkind/604#-MWySjN26eGUdOUMX6_x:-MWyaSqbAnDsj4eBu03h:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/10f8657fc3ba98b06bf9e5adc301fcf7ed408d52/tiering/ctl.c#L372)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> memkind_free(MEMKIND_DEFAULT, tier_cfgs);
> ```
If you free this what happened at the end of the application - when ctl_destroy_kind is called, you call memkind_free(MEMKIND_DEFAULT, tier_cfgs); second time.

</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-03-29 15:57 UTC, michalbiesek requested changes
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/604)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @bratpiorka, @michalbiesek, and @PatKamin)

___
*[tiering/ctl.c, line 362 at r9](https://reviewable.io/reviews/memkind/memkind/604#-MWyR_UR26CvJTkRJcH4:-MWyeRMY5K3qRVO0eLB1:b-pgwaih) ([raw file](https://github.com/memkind/memkind/blob/10f8657fc3ba98b06bf9e5adc301fcf7ed408d52/tiering/ctl.c#L362)):*
My mistake I described it previous code snippet wrong here - now the freeing with goto is wrong. 

Please restore:
<details><summary><i alt="summary">Quoted 6 lines of code…</i></summary>

> ```
>builder_delete:
>  memtier_builder_delete(builder);
> tiers_delete:
>  ctl_destroy_tiers(created_tiers);
>  ctl_destroy_fs_dax_reg();
>  return NULL;
> ```
</details>


But change:
> ```
>         tiers[i] = memtier_tier_new(kind);
>         if (tiers[i] == NULL) {
>             goto builder_delete;
> ```
to:
> ```
>         tiers[i] = memtier_tier_new(kind);
>         if (tiers[i] == NULL) {
>             goto tiers_delete;
> ```
___
*[tiering/ctl.c, line 293 at r11](https://reviewable.io/reviews/memkind/memkind/604#-MWye2NoCPhxxK8aXAga:-MWye2NoCPhxxK8aXAgb:bh69rbe) ([raw file](https://github.com/memkind/memkind/blob/53f0b8184937639d21f096bdef56444afe2aa9f6/tiering/ctl.c#L293)):*
> ```
> const
> ```
remove


<!-- Sent from Reviewable.io -->

2021-03-29 16:08 UTC, michalbiesek requested changes
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/604)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @bratpiorka, @michalbiesek, and @PatKamin)

___
*[tiering/ctl.c, line 362 at r9](https://reviewable.io/reviews/memkind/memkind/604#-MWyR_UR26CvJTkRJcH4:-MWyid6d-_KtnTsBnjUU:bscyjjt) ([raw file](https://github.com/memkind/memkind/blob/10f8657fc3ba98b06bf9e5adc301fcf7ed408d52/tiering/ctl.c#L362)):*
Ignore the second part of my previous comment:
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
>         tiers[i] = memtier_tier_new(kind);
>         if (tiers[i] == NULL) {
>             goto builder_delete;
>         }
> ```
</details>


The method will work fine, after correcting label order (the first part of my previous comment)
___
*[tiering/ctl.c, line 345 at r13](https://reviewable.io/reviews/memkind/memkind/604#-MWyiNFxBp5vW9nwP96k:-MWyiNFxBp5vW9nwP96l:b-43bay9) ([raw file](https://github.com/memkind/memkind/blob/11159eda8429bb6e3499d14f50d5fd2752cd056d/tiering/ctl.c#L345)):*
> ```
> return NULL;
> ```
goto tiers_delete -> in case of failure caused by ctl_parse_query or ctl_parse_policy


<!-- Sent from Reviewable.io -->

2021-03-30 06:57 UTC, bratpiorka reviewed
> Reviewed 2 of 2 files at r8, 1 of 1 files at r9, 1 of 2 files at r10, 1 of 1 files at r12, 1 of 1 files at r13.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/604)* status: all files reviewed, 2 unresolved discussions (waiting on @PatKamin)



<!-- Sent from Reviewable.io -->

2021-03-30 10:41 UTC, PatKamin reviewed
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/604)* status: all files reviewed, 2 unresolved discussions (waiting on @michalbiesek)

___
*[tiering/ctl.c, line 293 at r11](https://reviewable.io/reviews/memkind/memkind/604#-MWye2NoCPhxxK8aXAga:-MX1CEAo5q5V0Iwtj6_Y:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/53f0b8184937639d21f096bdef56444afe2aa9f6/tiering/ctl.c#L293)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> const
> ```
remove
</blockquote></details>

Done.
___
*[tiering/ctl.c, line 345 at r13](https://reviewable.io/reviews/memkind/memkind/604#-MWyiNFxBp5vW9nwP96k:-MX1Dqhd66wjEN49Jj0f:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/11159eda8429bb6e3499d14f50d5fd2752cd056d/tiering/ctl.c#L345)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> return NULL;
> ```
goto tiers_delete -> in case of failure caused by ctl_parse_query or ctl_parse_policy
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-03-30 11:01 UTC, michalbiesek requested changes
> Reviewed 1 of 2 files at r14.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/604)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @bratpiorka and @PatKamin)

___
*[test/tiering_tests.py, line 34 at r15](https://reviewable.io/reviews/memkind/memkind/604#-MX1l8l65-O6x8voZGfd:-MX1l8l65-O6x8voZGfe:b-qavpii) ([raw file](https://github.com/memkind/memkind/blob/e32f7ef1689f00c347843673466aefd35fd73925/test/tiering_tests.py#L34)):*
> ```
>     M = 1 << 20
>     G = 1 << 30
> ```

def convert_bytes(self, bytes_str)
   // check last element if it is M/G/k
   // convert rest the string (before the last element) to int and multiply by specific number
  // convert calculated value to string


<!-- Sent from Reviewable.io -->

2021-03-30 11:05 UTC, michalbiesek approved these changes
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/604)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @bratpiorka and @PatKamin)

___
*[tiering/ctl.c, line 28 at r15](https://reviewable.io/reviews/memkind/memkind/604#-MX1nVF8-dP3mTv3s5He:-MX1nVF8-dP3mTv3s5Hf:bwas1es) ([raw file](https://github.com/memkind/memkind/blob/e32f7ef1689f00c347843673466aefd35fd73925/tiering/ctl.c#L28)):*
> ```
> static ctl_tier_cfg *tier_cfgs;
> ```
add TODO here that this should be cleaned up - since it could be done as another variable on a stack as not static variable after modyfing functionality in ctl_create_tier_kind_from_env.


<!-- Sent from Reviewable.io -->

2021-03-30 12:23 UTC, PatKamin reviewed
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/604)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @bratpiorka and @michalbiesek)

___
*[test/tiering_tests.py, line 34 at r15](https://reviewable.io/reviews/memkind/memkind/604#-MX1l8l65-O6x8voZGfd:-MX21cQ551nVfsDfeOrC:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/e32f7ef1689f00c347843673466aefd35fd73925/test/tiering_tests.py#L34)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
>     M = 1 << 20
>     G = 1 << 30
> ```

def convert_bytes(self, bytes_str)
   // check last element if it is M/G/k
   // convert rest the string (before the last element) to int and multiply by specific number
  // convert calculated value to string
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-03-30 12:28 UTC, bratpiorka reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 2 files at r16, 1 of 1 files at r17.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/604#-:-MX25qIT7ZZKfCjVAMfD:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @michalbiesek)



<!-- Sent from Reviewable.io -->

2021-03-30 15:17 UTC, merged