Add memtier STATIC_THRESHOLD policy
memkind/memkind pull request #605
Opened 2021-03-29 11:22 UTC by bratpiorka

- add MEMTIER_POLICY_STATIC_THRESHOLD
- remove MEMTIER_POLICY_CIRCULAR
- change policy used in tests to MEMTIER_POLICY_STATIC_THRESHOLD

### Description

### Types of changes

- [ ] Bugfix (non-breaking change which fixes issue linked in Description above)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation (correction or otherwise)
- [ ] Cosmetics (whitespace, appearance)
- [ ] Other

### Checklist

- [ ] Code compiles without errors
- [ ] All tests pass locally with my changes (see TESTING section in CONTRIBUTING file)
- [ ] Created tests which will fail without the change (if possible)
- [ ] Extended the README/documentation (if necessary)
- [ ] All newly added files have proprietary license (if necessary)
- [ ] All newly added files are referenced in MANIFEST files (if necessary)

## Further comments

2021-03-29 11:53 UTC, michalbiesek requested changes
> Reviewed 1 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/605)* status: 1 of 5 files reviewed, 10 unresolved discussions (waiting on @bratpiorka and @PatKamin)

___
*[include/memkind_memtier.h, line 27 at r1](https://reviewable.io/reviews/memkind/memkind/605#-MWxnLugEzVuX3Gy_uFd:-MWxnLugEzVuX3Gy_uFe:bs97r7c) ([raw file](https://github.com/memkind/memkind/blob/3d9c239ad96aedf226f16f9a3977572981b91e6d/include/memkind_memtier.h#L27)):*
> ```
> Static Threshold
> ```
@jschmieg you believe have some feedback about naming convention here.
___
*[src/memkind_memtier.c, line 50 at r1](https://reviewable.io/reviews/memkind/memkind/605#-MWxmYm73VyJkm_mwkiv:-MWxmYm73VyJkm_mwkiw:bknrx7i) ([raw file](https://github.com/memkind/memkind/blob/3d9c239ad96aedf226f16f9a3977572981b91e6d/src/memkind_memtier.c#L50)):*
> ```
> memtier_policy_t
> ```
consider change naming this type since it could be easily confused with memtier_policy struct below
___
*[src/memkind_memtier.c, line 56 at r1](https://reviewable.io/reviews/memkind/memkind/605#-MWxnaiyDA3cN7N1ts-k:-MWxnaiyDA3cN7N1ts-l:bo2olgi) ([raw file](https://github.com/memkind/memkind/blob/3d9c239ad96aedf226f16f9a3977572981b91e6d/src/memkind_memtier.c#L56)):*
> ```
> free_priv
> ```
destroy_priv -> since you have create method 
___
*[src/memkind_memtier.c, line 72 at r1](https://reviewable.io/reviews/memkind/memkind/605#-MWxmx3E-n7jM-7WsA9O:-MWxmx3E-n7jM-7WsA9P:b-ivtgq1) ([raw file](https://github.com/memkind/memkind/blob/3d9c239ad96aedf226f16f9a3977572981b91e6d/src/memkind_memtier.c#L72)):*
> ```
> int
> ```
static?
___
*[src/memkind_memtier.c, line 77 at r1](https://reviewable.io/reviews/memkind/memkind/605#-MWxmmlq8VDQvDk5Zh2E:-MWxmmlq8VDQvDk5Zh2F:b3xqkvb) ([raw file](https://github.com/memkind/memkind/blob/3d9c239ad96aedf226f16f9a3977572981b91e6d/src/memkind_memtier.c#L77)):*
> ```
> calloc
> ```
jemk_calloc
___
*[src/memkind_memtier.c, line 86 at r1](https://reviewable.io/reviews/memkind/memkind/605#-MWxo-K6APjsGtw1kPGX:-MWxo-K6APjsGtw1kPGY:bymruen) ([raw file](https://github.com/memkind/memkind/blob/3d9c239ad96aedf226f16f9a3977572981b91e6d/src/memkind_memtier.c#L86)):*
> ```
> 0
> ```
from 1 ? since you will override the value after the loop
___
*[src/memkind_memtier.c, line 96 at r1](https://reviewable.io/reviews/memkind/memkind/605#-MWxmvTC2GQqD_2TwUbi:-MWxmvTC2GQqD_2TwUbj:bfku3sy) ([raw file](https://github.com/memkind/memkind/blob/3d9c239ad96aedf226f16f9a3977572981b91e6d/src/memkind_memtier.c#L96)):*
> ```
> void
> ```
static?
___
*[src/memkind_memtier.c, line 101 at r1](https://reviewable.io/reviews/memkind/memkind/605#-MWxn0s997tfbd1tnLMR:-MWxn0s997tfbd1tnLMS:b45u57w) ([raw file](https://github.com/memkind/memkind/blob/3d9c239ad96aedf226f16f9a3977572981b91e6d/src/memkind_memtier.c#L101)):*
> ```C
> }
> 
> struct memtier_tier *
> ```

static?
___
*[src/memkind_memtier.c, line 247 at r1](https://reviewable.io/reviews/memkind/memkind/605#-MWxp1vx1tx6VBr9XPtO:-MWxp1vx1tx6VBr9XPtP:b-3vmrpy) ([raw file](https://github.com/memkind/memkind/blob/3d9c239ad96aedf226f16f9a3977572981b91e6d/src/memkind_memtier.c#L247)):*
> ```
> goto free_kind;
> ```
why? allocation fails so you could return -1
___
*[src/memkind_memtier.c, line 254 at r1](https://reviewable.io/reviews/memkind/memkind/605#-MWxpA_F2iIwZxDp66l6:-MWxpA_F2iIwZxDp66l7:bcy8x2t) ([raw file](https://github.com/memkind/memkind/blob/3d9c239ad96aedf226f16f9a3977572981b91e6d/src/memkind_memtier.c#L254)):*
> ```
> free_cfg
> ```
free_kind


<!-- Sent from Reviewable.io -->

2021-03-29 12:09 UTC, bratpiorka reviewed
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/605)* status: 1 of 5 files reviewed, 11 unresolved discussions (waiting on @bratpiorka, @michalbiesek, and @PatKamin)

___
*[src/memkind_memtier.c, line 50 at r1](https://reviewable.io/reviews/memkind/memkind/605#-MWxmYm73VyJkm_mwkiv:-MWxsVDY9KYnp_cSWi4J:bsqbvp4) ([raw file](https://github.com/memkind/memkind/blob/3d9c239ad96aedf226f16f9a3977572981b91e6d/src/memkind_memtier.c#L50)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> memtier_policy_t
> ```
consider change naming this type since it could be easily confused with memtier_policy struct below
</blockquote></details>

Done, I changed name of struct below
___
*[src/memkind_memtier.c, line 56 at r1](https://reviewable.io/reviews/memkind/memkind/605#-MWxnaiyDA3cN7N1ts-k:-MWxq2aW3N8d27LBBsha:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/3d9c239ad96aedf226f16f9a3977572981b91e6d/src/memkind_memtier.c#L56)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> free_priv
> ```
destroy_priv -> since you have create method 
</blockquote></details>

Done.
___
*[src/memkind_memtier.c, line 72 at r1](https://reviewable.io/reviews/memkind/memkind/605#-MWxmx3E-n7jM-7WsA9O:-MWxq26KEk0tj96kWHK7:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/3d9c239ad96aedf226f16f9a3977572981b91e6d/src/memkind_memtier.c#L72)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> int
> ```
static?
</blockquote></details>

Done.
___
*[src/memkind_memtier.c, line 77 at r1](https://reviewable.io/reviews/memkind/memkind/605#-MWxmmlq8VDQvDk5Zh2E:-MWxqiVI11J3jK25iVZ2:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/3d9c239ad96aedf226f16f9a3977572981b91e6d/src/memkind_memtier.c#L77)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> calloc
> ```
jemk_calloc
</blockquote></details>

Done.
___
*[src/memkind_memtier.c, line 86 at r1](https://reviewable.io/reviews/memkind/memkind/605#-MWxo-K6APjsGtw1kPGX:-MWxqPnz-Wf6zh2uTtpt:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/3d9c239ad96aedf226f16f9a3977572981b91e6d/src/memkind_memtier.c#L86)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> 0
> ```
from 1 ? since you will override the value after the loop
</blockquote></details>

Done.
___
*[src/memkind_memtier.c, line 96 at r1](https://reviewable.io/reviews/memkind/memkind/605#-MWxmvTC2GQqD_2TwUbi:-MWxqQUS-0Xkm7b6moQ6:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/3d9c239ad96aedf226f16f9a3977572981b91e6d/src/memkind_memtier.c#L96)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> void
> ```
static?
</blockquote></details>

Done.
___
*[src/memkind_memtier.c, line 101 at r1](https://reviewable.io/reviews/memkind/memkind/605#-MWxn0s997tfbd1tnLMR:-MWxqQz28ZobfznfmV5x:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/3d9c239ad96aedf226f16f9a3977572981b91e6d/src/memkind_memtier.c#L101)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

static?
</blockquote></details>

Done.
___
*[src/memkind_memtier.c, line 244 at r1](https://reviewable.io/reviews/memkind/memkind/605#-MWxslPJ8JJOaQYqBw4-:-MWxslPJ8JJOaQYqBw40:b-f2xnrp) ([raw file](https://github.com/memkind/memkind/blob/3d9c239ad96aedf226f16f9a3977572981b91e6d/src/memkind_memtier.c#L244)):*
> ```C
>     }
> 
>     *kind = jemk_malloc(sizeof(sizeof(struct memtier_kind)));
> ```

heh this line was a source of my problems with segmentation faults .. 
___
*[src/memkind_memtier.c, line 247 at r1](https://reviewable.io/reviews/memkind/memkind/605#-MWxp1vx1tx6VBr9XPtO:-MWxqYERBfjQ1lctRozi:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/3d9c239ad96aedf226f16f9a3977572981b91e6d/src/memkind_memtier.c#L247)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> goto free_kind;
> ```
why? allocation fails so you could return -1
</blockquote></details>

Done.
___
*[src/memkind_memtier.c, line 254 at r1](https://reviewable.io/reviews/memkind/memkind/605#-MWxpA_F2iIwZxDp66l6:-MWxqg5I4gLAeCAacqwC:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/3d9c239ad96aedf226f16f9a3977572981b91e6d/src/memkind_memtier.c#L254)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> free_cfg
> ```
free_kind
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-03-29 13:14 UTC, michalbiesek requested changes
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/605)* status: 1 of 5 files reviewed, 4 unresolved discussions (waiting on @bratpiorka and @PatKamin)

___
*[src/memkind_memtier.c, line 118 at r2](https://reviewable.io/reviews/memkind/memkind/605#-MWy-l7wEStNOnNbiJTh:-MWy-l7x0EvBfn5Hzvpl:blq6cfa) ([raw file](https://github.com/memkind/memkind/blob/c675eaa3e52011092a7cc51efb4cc7068c97a4bc/src/memkind_memtier.c#L118)):*
> ```
> cfg[0].tier->alloc_size
> ```
can this be zero? I mean is there any chance for zero division?
___
*[src/memkind_memtier.c, line 120 at r2](https://reviewable.io/reviews/memkind/memkind/605#-MWy5jby4tyETJlL6_K1:-MWy5jby4tyETJlL6_K2:b5o2gu6) ([raw file](https://github.com/memkind/memkind/blob/c675eaa3e52011092a7cc51efb4cc7068c97a4bc/src/memkind_memtier.c#L120)):*
> ```
>         if ((worse_tier == -1) || (cfg[i].tier->alloc_size == 0) ||
>             (ratio_distance < worse_ratio)) {
>             worse_tier = i;
> ```
so the worst_tier will be always assigned to the first right ? from worse_tier == -1, so you could just assign it from the start and avoid -1. and this simplifies the condition here or I am missing something?

@jschmieg you have experience with this ratio calculation - any comments on this implementation


<!-- Sent from Reviewable.io -->

2021-03-29 14:46 UTC, bratpiorka reviewed
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/605)* status: 1 of 5 files reviewed, 3 unresolved discussions (waiting on @bratpiorka, @jschmieg, @michalbiesek, and @PatKamin)

___
*[src/memkind_memtier.c, line 118 at r2](https://reviewable.io/reviews/memkind/memkind/605#-MWy-l7wEStNOnNbiJTh:-MWyRMkODguWeD6cqY2Q:b-b16tjm) ([raw file](https://github.com/memkind/memkind/blob/c675eaa3e52011092a7cc51efb4cc7068c97a4bc/src/memkind_memtier.c#L118)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> cfg[0].tier->alloc_size
> ```
can this be zero? I mean is there any chance for zero division?
</blockquote></details>

Done. Now it can't be zero here.
___
*[src/memkind_memtier.c, line 120 at r2](https://reviewable.io/reviews/memkind/memkind/605#-MWy5jby4tyETJlL6_K1:-MWyRUwF1xm-kUzzEGPh:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/c675eaa3e52011092a7cc51efb4cc7068c97a4bc/src/memkind_memtier.c#L120)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
>         if ((worse_tier == -1) || (cfg[i].tier->alloc_size == 0) ||
>             (ratio_distance < worse_ratio)) {
>             worse_tier = i;
> ```
so the worst_tier will be always assigned to the first right ? from worse_tier == -1, so you could just assign it from the start and avoid -1. and this simplifies the condition here or I am missing something?

@jschmieg you have experience with this ratio calculation - any comments on this implementation
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-03-29 14:58 UTC, PatKamin reviewed
> Reviewed 1 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/605)* status: all files reviewed, 6 unresolved discussions (waiting on @bratpiorka, @jschmieg, and @michalbiesek)

___
*[src/memkind_memtier.c, line 80 at r3](https://reviewable.io/reviews/memkind/memkind/605#-MWyU2QQDC2tataNXn6w:-MWyU2QRBrTswxo_VeTx:b8ts93n) ([raw file](https://github.com/memkind/memkind/blob/261386801d9f56ffff0bdce1cff44316d396ab9a/src/memkind_memtier.c#L80)):*
> ```C
>         jemk_calloc(tier_kind->size, sizeof(struct static_threshold_tier_data));
>     if (tier_kind->policy_priv == NULL) {
>         return -1;
> ```

Failure message?
___
*[src/memkind_memtier.c, line 114 at r3](https://reviewable.io/reviews/memkind/memkind/605#-MWyUCfv7HDWQ78KCmR2:-MWyUCfv7HDWQ78KCmR3:bnbbht7) ([raw file](https://github.com/memkind/memkind/blob/261386801d9f56ffff0bdce1cff44316d396ab9a/src/memkind_memtier.c#L114)):*
> ```C
> 
>     int i;
>     int worse_tier = 0;
> ```

worst_tier
___
*[src/memkind_memtier.c, line 123 at r3](https://reviewable.io/reviews/memkind/memkind/605#-MWyUFZ5DqZeAz9RFSAD:-MWyUFZ5DqZeAz9RFSAE:b-4u5c9y) ([raw file](https://github.com/memkind/memkind/blob/261386801d9f56ffff0bdce1cff44316d396ab9a/src/memkind_memtier.c#L123)):*
> ```
> cfg[i].tier_ratio
> ```
tiers[i].normalized_ratio ?


<!-- Sent from Reviewable.io -->

2021-03-29 15:17 UTC, bratpiorka reviewed
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/605)* status: all files reviewed, 6 unresolved discussions (waiting on @bratpiorka, @jschmieg, @michalbiesek, and @PatKamin)

___
*[src/memkind_memtier.c, line 118 at r2](https://reviewable.io/reviews/memkind/memkind/605#-MWy-l7wEStNOnNbiJTh:-MWyXyScEfPC3xPsfswU:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/c675eaa3e52011092a7cc51efb4cc7068c97a4bc/src/memkind_memtier.c#L118)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

Done. Now it can't be zero here.
</blockquote></details>

Done.
___
*[src/memkind_memtier.c, line 80 at r3](https://reviewable.io/reviews/memkind/memkind/605#-MWyU2QQDC2tataNXn6w:-MWyXqiwCqaBRNOSt6xz:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/261386801d9f56ffff0bdce1cff44316d396ab9a/src/memkind_memtier.c#L80)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Failure message?
</blockquote></details>

Done.
___
*[src/memkind_memtier.c, line 114 at r3](https://reviewable.io/reviews/memkind/memkind/605#-MWyUCfv7HDWQ78KCmR2:-MWyXwWjCpuq_qFHgVal:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/261386801d9f56ffff0bdce1cff44316d396ab9a/src/memkind_memtier.c#L114)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

worst_tier
</blockquote></details>

Done.
___
*[src/memkind_memtier.c, line 123 at r3](https://reviewable.io/reviews/memkind/memkind/605#-MWyUFZ5DqZeAz9RFSAD:-MWyYpSr8CSdECXqq_f2:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/261386801d9f56ffff0bdce1cff44316d396ab9a/src/memkind_memtier.c#L123)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

> ```
> cfg[i].tier_ratio
> ```
tiers[i].normalized_ratio ?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-03-29 15:21 UTC, michalbiesek reviewed
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/605)* status: all files reviewed, 4 unresolved discussions (waiting on @bratpiorka and @PatKamin)

___
*[src/memkind_memtier.c, line 123 at r3](https://reviewable.io/reviews/memkind/memkind/605#-MWyUFZ5DqZeAz9RFSAD:-MWyZle548zgEPf5rVfd:bav7tkx) ([raw file](https://github.com/memkind/memkind/blob/261386801d9f56ffff0bdce1cff44316d396ab9a/src/memkind_memtier.c#L123)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

After this suggestion would you even need the "actual_ratio" field ?


<!-- Sent from Reviewable.io -->

2021-03-30 06:45 UTC, bratpiorka reviewed
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/605)* status: all files reviewed, 4 unresolved discussions (waiting on @bratpiorka and @PatKamin)

___
*[src/memkind_memtier.c, line 123 at r3](https://reviewable.io/reviews/memkind/memkind/605#-MWyUFZ5DqZeAz9RFSAD:-MX0rNbl26zB4DtX7Dru:bovamho) ([raw file](https://github.com/memkind/memkind/blob/261386801d9f56ffff0bdce1cff44316d396ab9a/src/memkind_memtier.c#L123)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

After this suggestion would you even need the "actual_ratio" field ?
</blockquote></details>

You are right. And with further cleanup I don't even need private data etc. Maybe this will be useful when we implement other policies, but currently we don't need this.


<!-- Sent from Reviewable.io -->

2021-03-30 07:30 UTC, michalbiesek requested changes
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/605)* status: all files reviewed, 6 unresolved discussions (waiting on @bratpiorka and @PatKamin)

___
*[src/memkind_memtier.c, line 45 at r5](https://reviewable.io/reviews/memkind/memkind/605#-MX0wfjQ4WUBQRMetf2b:-MX0wfjQ4WUBQRMetf2c:b-r9t35o) ([raw file](https://github.com/memkind/memkind/blob/81aec72ca87f039138090e6a5f4704614f398115/src/memkind_memtier.c#L45)):*
> ```
> normaized_ratio;
> ```
1.typo
2.normalized_ratio or tier_ratio? I don't see this part of the normalization part in the assignment?
___
*[src/memkind_memtier.c, line 78 at r5](https://reviewable.io/reviews/memkind/memkind/605#-MX0xU8YBPdMkrkR-2DB:-MX0xU8YBPdMkrkR-2DC:bcgeyc5) ([raw file](https://github.com/memkind/memkind/blob/81aec72ca87f039138090e6a5f4704614f398115/src/memkind_memtier.c#L78)):*
> ```
>         float actual_ratio =
>             (float)cfg[i].tier->alloc_size / cfg[0].tier->alloc_size;
>         float ratio_distance = actual_ratio / cfg[i].normaized_ratio;
> ```
one expression? 

I think the best option would be to modify the comparison that cfg[0].tier->alloc_size could be used only once in the calculation - before the loop begins and start the loop from 1 - from the first look I think it is possible


<!-- Sent from Reviewable.io -->

2021-03-30 08:10 UTC, PatKamin reviewed
> Reviewed 2 of 5 files at r1, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/605)* status: all files reviewed, 4 unresolved discussions (waiting on @bratpiorka and @PatKamin)



<!-- Sent from Reviewable.io -->

2021-03-30 08:16 UTC, bratpiorka reviewed
> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/605)* status: all files reviewed, 4 unresolved discussions (waiting on @bratpiorka, @michalbiesek, and @PatKamin)

___
*[src/memkind_memtier.c, line 123 at r3](https://reviewable.io/reviews/memkind/memkind/605#-MWyUFZ5DqZeAz9RFSAD:-MX1C9H148RMqCmMpfg2:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/261386801d9f56ffff0bdce1cff44316d396ab9a/src/memkind_memtier.c#L123)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

You are right. And with further cleanup I don't even need private data etc. Maybe this will be useful when we implement other policies, but currently we don't need this.
</blockquote></details>

Done.
___
*[src/memkind_memtier.c, line 45 at r5](https://reviewable.io/reviews/memkind/memkind/605#-MX0wfjQ4WUBQRMetf2b:-MX197Zt9hK8dDjAx6ql:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/81aec72ca87f039138090e6a5f4704614f398115/src/memkind_memtier.c#L45)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> normaized_ratio;
> ```
1.typo
2.normalized_ratio or tier_ratio? I don't see this part of the normalization part in the assignment?
</blockquote></details>

Done.
___
*[src/memkind_memtier.c, line 78 at r5](https://reviewable.io/reviews/memkind/memkind/605#-MX0xU8YBPdMkrkR-2DB:-MX1C1av7bHk2ghOlIWd:btup1tr) ([raw file](https://github.com/memkind/memkind/blob/81aec72ca87f039138090e6a5f4704614f398115/src/memkind_memtier.c#L78)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
>         float actual_ratio =
>             (float)cfg[i].tier->alloc_size / cfg[0].tier->alloc_size;
>         float ratio_distance = actual_ratio / cfg[i].normaized_ratio;
> ```
one expression? 

I think the best option would be to modify the comparison that cfg[0].tier->alloc_size could be used only once in the calculation - before the loop begins and start the loop from 1 - from the first look I think it is possible
</blockquote></details>

is it ok now? I don't have better idea. 


<!-- Sent from Reviewable.io -->

2021-03-30 09:17 UTC, michalbiesek requested changes
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/605)* status: all files reviewed, 3 unresolved discussions (waiting on @bratpiorka and @PatKamin)

___
*[src/memkind_memtier.c, line 78 at r5](https://reviewable.io/reviews/memkind/memkind/605#-MX0xU8YBPdMkrkR-2DB:-MX1GZ020HWqKL1Risi9:b-95zbyv) ([raw file](https://github.com/memkind/memkind/blob/81aec72ca87f039138090e6a5f4704614f398115/src/memkind_memtier.c#L78)):*
You should do operations which are known - only one time - even better for construct kind - see that cfg[0]_tier ratio and cfg]i]_tier ratio doesn't change after construct kind so you don't need to divide - this is obsolete operation.

Consider just changing the expression here.
> ```
> ratio_distance < worst_ratio
> ```
Could be expressed as:

> ```
> (cfg[i].tier->alloc_size * cfg[i].tier_ratio)/(cfg[0].tier->alloc_size) < 1.0/ cfg[0].tier_ratio
> ```

so basically you could perform the decision here  based on a comparison of the absolute difference with 

> ```
> cfg[0].tier->alloc_size
> ```

And

> ```
>cfg[i].tier->alloc_size * NORMALIZED_RATIO
> ```
where NORMALIZED_RATIO is known after construct kind - as ratio[i]/ratio[0] (for ratio[0] it will be 1).

So instead of storing "ratio" in memtier_kind store "normalized ratio" there as this is calculated only once in constructing kind


<!-- Sent from Reviewable.io -->

2021-03-30 09:48 UTC, michalbiesek reviewed
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/605)* status: all files reviewed, 3 unresolved discussions (waiting on @bratpiorka and @PatKamin)

___
*[test/memkind_memtier_test.cpp, line 28 at r6](https://reviewable.io/reviews/memkind/memkind/605#-MX1WjKQ5Oiuu1eW3E6O:-MX1WjKQ5Oiuu1eW3E6P:b-kagbst) ([raw file](https://github.com/memkind/memkind/blob/907154fb816f4c1c5fe6d1ad237d1040f6ff4e29/test/memkind_memtier_test.cpp#L28)):*
> ```
>     const int m_tier_default_ratio = 1;
>     const int m_tier_regular_ratio = 4;
> ```
This could be done in separate PR but I would like to see the tests with:
-  3 kinds and 3 ratios
-  the test where tier[0] ratio is different than 1


<!-- Sent from Reviewable.io -->

2021-03-30 10:27 UTC, PatKamin reviewed
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/605)* status: all files reviewed, 3 unresolved discussions (waiting on @bratpiorka and @PatKamin)

___
*[test/memkind_memtier_test.cpp, line 28 at r6](https://reviewable.io/reviews/memkind/memkind/605#-MX1WjKQ5Oiuu1eW3E6O:-MX1eR-H3QwE5LTfMlXm:bgkarmp) ([raw file](https://github.com/memkind/memkind/blob/907154fb816f4c1c5fe6d1ad237d1040f6ff4e29/test/memkind_memtier_test.cpp#L28)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
>     const int m_tier_default_ratio = 1;
>     const int m_tier_regular_ratio = 4;
> ```
This could be done in separate PR but I would like to see the tests with:
-  3 kinds and 3 ratios
-  the test where tier[0] ratio is different than 1
</blockquote></details>

Definitely worth adding TODO as it has to be done, if not in this PR then in the next one.


<!-- Sent from Reviewable.io -->

2021-03-30 10:33 UTC, bratpiorka reviewed
> Reviewed 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/605)* status: all files reviewed, 4 unresolved discussions (waiting on @bratpiorka, @michalbiesek, and @PatKamin)

___
*[src/memkind_memtier.c, line 78 at r5](https://reviewable.io/reviews/memkind/memkind/605#-MX0xU8YBPdMkrkR-2DB:-MX1gBoJ99XmU59lrI60:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/81aec72ca87f039138090e6a5f4704614f398115/src/memkind_memtier.c#L78)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

You should do operations which are known - only one time - even better for construct kind - see that cfg[0]_tier ratio and cfg]i]_tier ratio doesn't change after construct kind so you don't need to divide - this is obsolete operation.

Consider just changing the expression here.
> ```
> ratio_distance < worst_ratio
> ```
Could be expressed as:

> ```
> (cfg[i].tier->alloc_size * cfg[i].tier_ratio)/(cfg[0].tier->alloc_size) < 1.0/ cfg[0].tier_ratio
> ```

so basically you could perform the decision here  based on a comparison of the absolute difference with 

> ```
> cfg[0].tier->alloc_size
> ```

And

> ```
>cfg[i].tier->alloc_size * NORMALIZED_RATIO
> ```
where NORMALIZED_RATIO is known after construct kind - as ratio[i]/ratio[0] (for ratio[0] it will be 1).

So instead of storing "ratio" in memtier_kind store "normalized ratio" there as this is calculated only once in constructing kind
</blockquote></details>

Done.
___
*[test/memkind_memtier_test.cpp, line 28 at r6](https://reviewable.io/reviews/memkind/memkind/605#-MX1WjKQ5Oiuu1eW3E6O:-MX1gCQgEYpw5PEct472:brz4um3) ([raw file](https://github.com/memkind/memkind/blob/907154fb816f4c1c5fe6d1ad237d1040f6ff4e29/test/memkind_memtier_test.cpp#L28)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Definitely worth adding TODO as it has to be done, if not in this PR then in the next one.
</blockquote></details>

will do in next PR but as a part of this JIRA story


<!-- Sent from Reviewable.io -->

2021-03-30 10:47 UTC, michalbiesek requested changes
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/605)* status: all files reviewed, 5 unresolved discussions (waiting on @bratpiorka and @PatKamin)

___
*[src/memkind_memtier.c, line 65 at r7](https://reviewable.io/reviews/memkind/memkind/605#-MX1iAD_9ziU49_72d57:-MX1iADa79pqP5S1wlTq:b-4jpvrc) ([raw file](https://github.com/memkind/memkind/blob/d09c81755fe10ae8d291d72645fbafcada369e41/src/memkind_memtier.c#L65)):*
> ```
>     if (cfg[0].tier->alloc_size == 0) {
>         return cfg[0].tier;
>     }
> ```
is this still needed?
___
*[src/memkind_memtier.c, line 70 at r7](https://reviewable.io/reviews/memkind/memkind/605#-MX1iPk97Ow-76r0d56z:-MX1iPk97Ow-76r0d57-:b-pabwv2) ([raw file](https://github.com/memkind/memkind/blob/d09c81755fe10ae8d291d72645fbafcada369e41/src/memkind_memtier.c#L70)):*
> ```
> worst_tier
> ```
nit: worst_tier maybe destination tier or any other meaningful name, since it's hard to determine after first look what "worst" means
___
*[test/memkind_memtier_test.cpp, line 28 at r6](https://reviewable.io/reviews/memkind/memkind/605#-MX1WjKQ5Oiuu1eW3E6O:-MX1ijiKBkm-W9fvxozC:b-a3p9k3) ([raw file](https://github.com/memkind/memkind/blob/907154fb816f4c1c5fe6d1ad237d1040f6ff4e29/test/memkind_memtier_test.cpp#L28)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

will do in next PR but as a part of this JIRA story
</blockquote></details>

sure, please add there note to consider a scenario: with multiple tiers and different proportion like e.g. 4:1:5, and using not only tier kind API but with a combination of tier as well - imagine the scenario where you simulate allocation only to one tier (using tiering API) and then switch to tiering kind API.


<!-- Sent from Reviewable.io -->

2021-03-30 10:50 UTC, PatKamin reviewed
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/605)* status: all files reviewed, 6 unresolved discussions (waiting on @bratpiorka and @PatKamin)

___
*[src/memkind_memtier.c, line 210 at r7](https://reviewable.io/reviews/memkind/memkind/605#-MX1k8J3DvTaJHeBRJKQ:-MX1k8J3DvTaJHeBRJKR:b-6edrvc) ([raw file](https://github.com/memkind/memkind/blob/d09c81755fe10ae8d291d72645fbafcada369e41/src/memkind_memtier.c#L210)):*
> ```C
>     }
> 
>     for (i = 0; i < builder->size; ++i) {
> ```

After this loop ends assign `(*kind)->cfg[0].tier_ratio = 1.0`


<!-- Sent from Reviewable.io -->

2021-03-30 11:05 UTC, bratpiorka reviewed
> Reviewed 2 of 2 files at r8.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/605)* status: all files reviewed, 4 unresolved discussions (waiting on @bratpiorka, @michalbiesek, and @PatKamin)

___
*[src/memkind_memtier.c, line 65 at r7](https://reviewable.io/reviews/memkind/memkind/605#-MX1iAD_9ziU49_72d57:-MX1mRAQ3EbV7npvhtrF:b-5mw4c9) ([raw file](https://github.com/memkind/memkind/blob/d09c81755fe10ae8d291d72645fbafcada369e41/src/memkind_memtier.c#L65)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
>     if (cfg[0].tier->alloc_size == 0) {
>         return cfg[0].tier;
>     }
> ```
is this still needed?
</blockquote></details>

Done. Removed
___
*[src/memkind_memtier.c, line 210 at r7](https://reviewable.io/reviews/memkind/memkind/605#-MX1k8J3DvTaJHeBRJKQ:-MX1lzsC6O1SZdq43gcI:bb6un1j) ([raw file](https://github.com/memkind/memkind/blob/d09c81755fe10ae8d291d72645fbafcada369e41/src/memkind_memtier.c#L210)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

After this loop ends assign `(*kind)->cfg[0].tier_ratio = 1.0`
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2021-03-30 11:09 UTC, michalbiesek approved these changes
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/605)* status: all files reviewed, 3 unresolved discussions (waiting on @bratpiorka and @PatKamin)



<!-- Sent from Reviewable.io -->

2021-03-30 11:13 UTC, jschmieg approved these changes

2021-03-30 11:29 UTC, michalbiesek approved these changes
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/605)* status: all files reviewed, 2 unresolved discussions (waiting on @PatKamin)



<!-- Sent from Reviewable.io -->

2021-03-30 12:30 UTC, bratpiorka reviewed
> Reviewed 1 of 1 files at r9.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/605)* status: all files reviewed, 1 unresolved discussion (waiting on @PatKamin)

___
*[include/memkind_memtier.h, line 27 at r1](https://reviewable.io/reviews/memkind/memkind/605#-MWxnLugEzVuX3Gy_uFd:-MX1psKoA8T7C1hdNUoj:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/3d9c239ad96aedf226f16f9a3977572981b91e6d/include/memkind_memtier.h#L27)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> Static Threshold
> ```
@jschmieg you believe have some feedback about naming convention here.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-03-31 05:30 UTC, merged