Change return type in constructing memtier memory
memkind/memkind pull request #622
Opened 2021-04-09 13:50 UTC by PatKamin

- change return type of memtier_builder_construct_memtier_memory()
API function from int to a memtier_memory pointer

### Description

### Types of changes

- [ ] Bugfix (non-breaking change which fixes issue linked in Description above)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation (correction or otherwise)
- [ ] Cosmetics (whitespace, appearance)
- [ ] Other

### Checklist

- [ ] Code compiles without errors
- [ ] All tests pass locally with my changes (see TESTING section in CONTRIBUTING file)
- [ ] Created tests which will fail without the change (if possible)
- [ ] Extended the README/documentation (if necessary)
- [ ] All newly added files have proprietary license (if necessary)
- [ ] All newly added files are referenced in MANIFEST files (if necessary)

## Further comments

2021-04-09 13:52 UTC, bratpiorka reviewed
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/622)* status: all files reviewed, 1 unresolved discussion (waiting on @PatKamin)

___
*[include/memkind_memtier.h, line 78 at r1](https://reviewable.io/reviews/memkind/memkind/622#-MXqtuHhDH8uge-nVZeb:-MXqtuHhDH8uge-nVZec:b-jx4fba) ([raw file](https://github.com/memkind/memkind/blob/da8fc7ad5c55929b7d9203f97afa0b9eab6e1b4e/include/memkind_memtier.h#L78)):*
> ```objc
> /// \param builder memtier builder
> /// \param memory pointer to memtier memory which will be created
> /// \return Operation status, 0 on success, other values on
> ```

update \return


<!-- Sent from Reviewable.io -->

2021-04-12 06:36 UTC, michalbiesek requested changes
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/622)* status: all files reviewed, 6 unresolved discussions (waiting on @PatKamin)

___
*[src/memkind_memtier.c, line 163 at r1](https://reviewable.io/reviews/memkind/memkind/622#-MY3ijGZ60-37ioeueKr:-MY3ijGZ60-37ioeueKs:b-puddkv) ([raw file](https://github.com/memkind/memkind/blob/da8fc7ad5c55929b7d9203f97afa0b9eab6e1b4e/src/memkind_memtier.c#L163)):*
> ```
>  
> ```
please update: https://github.com/memkind/memkind/blob/935bd1209424d73c5acce6452785210768f1a687/man/memkind_memtier.3#L27
___
*[src/memkind_memtier.c, line 163 at r1](https://reviewable.io/reviews/memkind/memkind/622#-MY3iqfz9y_-ki61p9hV:-MY3iqfz9y_-ki61p9hW:b-jyo327) ([raw file](https://github.com/memkind/memkind/blob/da8fc7ad5c55929b7d9203f97afa0b9eab6e1b4e/src/memkind_memtier.c#L163)):*
> ```
>  = NULL
> ```
not needed
___
*[test/memkind_memtier_test.cpp, line 23 at r1](https://reviewable.io/reviews/memkind/memkind/622#-MY3mTG94qUa4VPmaWma:-MY3mTGAAUzgG_mlL6PB:b-dvk2aq) ([raw file](https://github.com/memkind/memkind/blob/da8fc7ad5c55929b7d9203f97afa0b9eab6e1b4e/test/memkind_memtier_test.cpp#L23)):*
> ```
>  nullptr
> ```
not needed
___
*[test/memkind_memtier_test.cpp, line 62 at r1](https://reviewable.io/reviews/memkind/memkind/622#-MY3mVk75tUXh6KtMJ0p:-MY3mVk75tUXh6KtMJ0q:budbouf) ([raw file](https://github.com/memkind/memkind/blob/da8fc7ad5c55929b7d9203f97afa0b9eab6e1b4e/test/memkind_memtier_test.cpp#L62)):*
> ```
> = nullptr
> ```
not needed
___
*[tiering/ctl.c, line 233 at r1](https://reviewable.io/reviews/memkind/memkind/622#-MY3mkiL9QLhNGyxoCSA:-MY3mkiL9QLhNGyxoCSB:b-jyo327) ([raw file](https://github.com/memkind/memkind/blob/da8fc7ad5c55929b7d9203f97afa0b9eab6e1b4e/tiering/ctl.c#L233)):*
> ```
>  = NULL
> ```
not needed


<!-- Sent from Reviewable.io -->

2021-04-12 07:56 UTC, PatKamin reviewed
> Reviewed 2 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/622)* status: 0 of 5 files reviewed, 6 unresolved discussions (waiting on @bratpiorka, @michalbiesek, and @PatKamin)

___
*[include/memkind_memtier.h, line 78 at r1](https://reviewable.io/reviews/memkind/memkind/622#-MXqtuHhDH8uge-nVZeb:-MY424vB0NOFXgVtmsQ4:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/da8fc7ad5c55929b7d9203f97afa0b9eab6e1b4e/include/memkind_memtier.h#L78)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

update \return
</blockquote></details>

Done.
___
*[src/memkind_memtier.c, line 163 at r1](https://reviewable.io/reviews/memkind/memkind/622#-MY3ijGZ60-37ioeueKr:-MY426aw5UIFejTbQJdK:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/da8fc7ad5c55929b7d9203f97afa0b9eab6e1b4e/src/memkind_memtier.c#L163)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
>  
> ```
please update: https://github.com/memkind/memkind/blob/935bd1209424d73c5acce6452785210768f1a687/man/memkind_memtier.3#L27
</blockquote></details>

Done.
___
*[src/memkind_memtier.c, line 163 at r1](https://reviewable.io/reviews/memkind/memkind/622#-MY3iqfz9y_-ki61p9hV:-MY42Bx3BB_xN83yDymV:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/da8fc7ad5c55929b7d9203f97afa0b9eab6e1b4e/src/memkind_memtier.c#L163)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
>  = NULL
> ```
not needed
</blockquote></details>

Done.
___
*[test/memkind_memtier_test.cpp, line 23 at r1](https://reviewable.io/reviews/memkind/memkind/622#-MY3mTG94qUa4VPmaWma:-MY42HpUABaCC6b0Bbic:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/da8fc7ad5c55929b7d9203f97afa0b9eab6e1b4e/test/memkind_memtier_test.cpp#L23)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
>  nullptr
> ```
not needed
</blockquote></details>

Done.
___
*[test/memkind_memtier_test.cpp, line 62 at r1](https://reviewable.io/reviews/memkind/memkind/622#-MY3mVk75tUXh6KtMJ0p:-MY42KFWDV8zO68AYKCy:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/da8fc7ad5c55929b7d9203f97afa0b9eab6e1b4e/test/memkind_memtier_test.cpp#L62)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> = nullptr
> ```
not needed
</blockquote></details>

Done.
___
*[tiering/ctl.c, line 233 at r1](https://reviewable.io/reviews/memkind/memkind/622#-MY3mkiL9QLhNGyxoCSA:-MY42Q7q06LQDt_Xd8uT:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/da8fc7ad5c55929b7d9203f97afa0b9eab6e1b4e/tiering/ctl.c#L233)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
>  = NULL
> ```
not needed
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-04-12 08:02 UTC, michalbiesek requested changes
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/622)* status: 0 of 5 files reviewed, 2 unresolved discussions (waiting on @bratpiorka and @PatKamin)

___
*[include/memkind_memtier.h, line 77 at r2](https://reviewable.io/reviews/memkind/memkind/622#-MY45QB53xsZfgSnUFl1:-MY45QB53xsZfgSnUFl2:b-ts5xxw) ([raw file](https://github.com/memkind/memkind/blob/44822a82726796394b6a57c7edb82c37b66c1a09/include/memkind_memtier.h#L77)):*
> ```
> /// \param memory pointer to memtier memory which will be created
> ```
remove


<!-- Sent from Reviewable.io -->

2021-04-12 08:17 UTC, PatKamin reviewed
> Reviewed 3 of 5 files at r2, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/622)* status: all files reviewed, 2 unresolved discussions (waiting on @bratpiorka and @michalbiesek)

___
*[include/memkind_memtier.h, line 77 at r2](https://reviewable.io/reviews/memkind/memkind/622#-MY45QB53xsZfgSnUFl1:-MY493QOAyQOnSpyyqlI:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/44822a82726796394b6a57c7edb82c37b66c1a09/include/memkind_memtier.h#L77)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> /// \param memory pointer to memtier memory which will be created
> ```
remove
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-04-12 08:27 UTC, bratpiorka reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/622#-:-MY4BIaX1jaipupiV2jP:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @michalbiesek)



<!-- Sent from Reviewable.io -->

2021-04-12 08:42 UTC, michalbiesek approved these changes
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/622)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @PatKamin)



<!-- Sent from Reviewable.io -->

2021-04-12 10:15 UTC, merged