Initial implementation of DYNAMIC_THRESHOLD policy
memkind/memkind pull request #623
Opened 2021-04-14 10:27 UTC by bratpiorka

- added API for adding thresholds
- get_tier returns correct tier but threshold are not changing yet
- added tests that uses new API

### Description

### Types of changes

- [ ] Bugfix (non-breaking change which fixes issue linked in Description above)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation (correction or otherwise)
- [ ] Cosmetics (whitespace, appearance)
- [ ] Other

### Checklist

- [ ] Code compiles without errors
- [ ] All tests pass locally with my changes (see TESTING section in CONTRIBUTING file)
- [ ] Created tests which will fail without the change (if possible)
- [ ] Extended the README/documentation (if necessary)
- [ ] All newly added files have proprietary license (if necessary)
- [ ] All newly added files are referenced in MANIFEST files (if necessary)

## Further comments

2021-04-16 13:41 UTC, PatKamin reviewed
> Reviewed 2 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/623)* status: 2 of 4 files reviewed, 2 unresolved discussions (waiting on @bratpiorka and @michalbiesek)

___
*[src/memkind_memtier.c, line 142 at r2](https://reviewable.io/reviews/memkind/memkind/623#-MYPk4lP6oRbgbJMdRMB:-MYPk4lQB7HkMKwkOrgo:b-mw3ndx) ([raw file](https://github.com/memkind/memkind/blob/42e3343b0c60fbe120dfc45ea292944c8b336154/src/memkind_memtier.c#L142)):*
> ```C
>             float diff =
>                 1.0f - actual_ratio / cfg[i].kind_ratio * cfg[i + 1].kind_ratio;
>             change = (diff > POLICY_DYNAMIC_THRESHOLD_TRIGGER) ? -1
> ```

`if else` would be much easier to read. You can even set the `change` value to -1 while declaring it to omit the outer `else` statement and make this `if else` cleaner, too. Like this:

```
        int change = -1;
        if (prev_alloc_size > 0) {
            float actual_ratio = (float)next_alloc_size / prev_alloc_size;
            float diff =
                1.0f - actual_ratio / cfg[i].kind_ratio * cfg[i + 1].kind_ratio;
            if (diff < -POLICY_DYNAMIC_THRESHOLD_TRIGGER)
                    change = 1;
            else if (diff <= POLICY_DYNAMIC_THRESHOLD_TRIGGER)
                change = 0;
        }
```
___
*[src/memkind_memtier.c, line 222 at r2](https://reviewable.io/reviews/memkind/memkind/623#-MYPsarG53ozPllYbbo3:-MYPsarG53ozPllYbbo4:b-s8f2ha) ([raw file](https://github.com/memkind/memkind/blob/42e3343b0c60fbe120dfc45ea292944c8b336154/src/memkind_memtier.c#L222)):*
> ```C
> memtier_builder_add_threshold(struct memtier_builder *builder, size_t init)
> {
>     return memtier_builder_add_threshold_min_max(builder, init, 0, SIZE_MAX);
> ```

Seems like it doesn't have to be a separate function.


<!-- Sent from Reviewable.io -->

2021-04-19 10:07 UTC, michalbiesek requested changes
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/623)* status: 2 of 4 files reviewed, 13 unresolved discussions (waiting on @bratpiorka)

___
*[include/memkind_memtier.h, line 99 at r1](https://reviewable.io/reviews/memkind/memkind/623#-MYJD__TDQDJAdtdZw_c:-MYJD__TDQDJAdtdZw_d:b-25ul3u) ([raw file](https://github.com/memkind/memkind/blob/97d39f1a6405ef634f87c3c975ffed76ce8cf6d2/include/memkind_memtier.h#L99)):*
> ```
> int memtier_builder_add_threshold(struct memtier_builder *builder, size_t init);
> ```
I would rather avoid this function since this functionality could be done by memtier_builder_add_threshold_min_max. If this is explicitly requested by the client, then this should be added now it will confuse the user which function should be used.
___
*[include/memkind_memtier.h, line 88 at r2](https://reviewable.io/reviews/memkind/memkind/623#-MYdX2OtCD4dI4Q4-_xY:-MYdX2OtCD4dI4Q4-_xZ:bm2lpz1) ([raw file](https://github.com/memkind/memkind/blob/42e3343b0c60fbe120dfc45ea292944c8b336154/include/memkind_memtier.h#L88)):*
> ```
> ///
> int memtier_builder_add_threshold_min_max(struct memtier_builder *builder,
>                                           size_t init, size_t min, size_t max);
> ```

I think we should use CTL approach (https://pmem.io/pmdk/manpages/linux/v1.10/libpmemobj/pmemobj_ctl_get.3) - the set part. T
The CTL API will be considered as "API" for the advanced user.
This also required the definition of default values for the dynamic threshold at least for the basic scenario with two tiers.
Regarding default values for more tiers - this would be required using CTL API.

With CTL approach and default values, scenario like below make sense:

//memtier_builder_add_tier(DRAM, ratio=1)
//memtier_builder_add_tier(PMEM, ratio=4)
//memtier_builder_set_policy(MEMTIER_POLICY_DYNAMIC_THRESHOLD)

With API with memtier_builder_add_threshold_min_max/memtier_builder_add_threshold the memtier_builder_set_policy is just redundant operation.

Additional value of the CTL approach is to have a common interface for additional configuration of different policies. In other words, this could be used as a common interface for setting up exclusive policy parameters.

@jschmieg maybe you have additional comments on this.
___
*[src/memkind_memtier.c, line 51 at r2](https://reviewable.io/reviews/memkind/memkind/623#-MYPmTBl4Hs5sO1uCt1V:-MYPmTBl4Hs5sO1uCt1W:bsvnmd2) ([raw file](https://github.com/memkind/memkind/blob/42e3343b0c60fbe120dfc45ea292944c8b336154/src/memkind_memtier.c#L51)):*
> ```
> POLICY_DYNAMIC_THRESHOLD_CHANGE_VAL
> ```
THRESHOLD_STEP
___
*[src/memkind_memtier.c, line 60 at r2](https://reviewable.io/reviews/memkind/memkind/623#-MYPoZO184tV_qmUURua:-MYPoZO184tV_qmUURub:bzg496j) ([raw file](https://github.com/memkind/memkind/blob/42e3343b0c60fbe120dfc45ea292944c8b336154/src/memkind_memtier.c#L60)):*
> ```
> size_t val; // Actual threshold level
> ```
size_t threshold; I am not sure but maybe this would be more meaningful here
___
*[src/memkind_memtier.c, line 108 at r2](https://reviewable.io/reviews/memkind/memkind/623#-MYPrLYn6s4eueNowo0u:-MYPrLYn6s4eueNowo0v:b7v3zqz) ([raw file](https://github.com/memkind/memkind/blob/42e3343b0c60fbe120dfc45ea292944c8b336154/src/memkind_memtier.c#L108)):*
> ```
> memtier_policy_dynamic_threshold_get_kind
> ```
this does two operations, right? get kind - the first loop and "update the threshold config" - the second loop.
___
*[src/memkind_memtier.c, line 141 at r2](https://reviewable.io/reviews/memkind/memkind/623#-MYPhpbG-X6b6VCJ4fIt:-MYPhpbG-X6b6VCJ4fIu:b-y0yee) ([raw file](https://github.com/memkind/memkind/blob/42e3343b0c60fbe120dfc45ea292944c8b336154/src/memkind_memtier.c#L141)):*
> ```
> cfg[i].kind_ratio * cfg[i + 1].kind_ratio
> ```
this operation could be done one time right? you don't need to calculate it every time you perform looking up for correct memory kind - this is similar to the normalized part you have done in the case of previous policy
___
*[src/memkind_memtier.c, line 151 at r2](https://reviewable.io/reviews/memkind/memkind/623#-MYPnzhKDsfRYaQLcYrk:-MYPnzhLE9S9RG5I6kFP:bqdlp1b) ([raw file](https://github.com/memkind/memkind/blob/42e3343b0c60fbe120dfc45ea292944c8b336154/src/memkind_memtier.c#L151)):*
<details><summary><i alt="summary">Quoted 5 lines of code…</i></summary>

> ```
>             float new_val = thres[i].val *
>                 (1.0 + (float)change * POLICY_DYNAMIC_THRESHOLD_CHANGE_VAL);
>             thres[i].val = (new_val > thres[i].max) ? thres[i].max
>                 : (new_val < thres[i].min)          ? thres[i].min
>                                                     : new_val;
> ```
</details>

it will be much more readable with if-else and some macro for this threshold up/down operation 
___
*[src/memkind_memtier.c, line 209 at r2](https://reviewable.io/reviews/memkind/memkind/623#-MYPj0a077KslRSqZJnp:-MYPj0a1DvLBvAl-GC33:b7qsek0) ([raw file](https://github.com/memkind/memkind/blob/42e3343b0c60fbe120dfc45ea292944c8b336154/src/memkind_memtier.c#L209)):*
<details><summary><i alt="summary">Quoted 6 lines of code…</i></summary>

> ```
>     if ((policy == MEMTIER_POLICY_STATIC_THRESHOLD) ||
>         (policy == MEMTIER_POLICY_DYNAMIC_THRESHOLD)) {
>         builder->policy = policy;
>     } else {
>         log_err("Unrecognized memory policy %u", policy);
>         return -1;
> ```
</details>

switch case/default, please.
I think this could be optimized - the decision part with function pointer here but I will handle this in separate PR - you could mark here as TODO use function pointer for decision
___
*[src/memkind_memtier.c, line 229 at r2](https://reviewable.io/reviews/memkind/memkind/623#-MYPjKhrC9Kmgx-fS4De:-MYPjKhrC9Kmgx-fS4Df:b-1e4mu4) ([raw file](https://github.com/memkind/memkind/blob/42e3343b0c60fbe120dfc45ea292944c8b336154/src/memkind_memtier.c#L229)):*
<details><summary><i alt="summary">Quoted 5 lines of code…</i></summary>

> ```
>     if (builder->size < 2) {
>         log_err("There should be at least 2 tiers added to builder "
>                 "to define a threshold between them.");
>         return -1;
>     }
> ```
</details>

This is error-prone, the order shouldn't manner here

Why the situation is different:
- memtier_builder_add_tier(1)
- memtier_builder_add_tier(2)
- memtier_builder_add_threshold_min_max
- memtier_builder_add_threshold_min_max

Compared to:
- memtier_builder_add_tier(1)
- memtier_builder_add_threshold_min_max
- memtier_builder_add_tier(2)
- memtier_builder_add_threshold_min_max

But see my comment regarding CTL API
___
*[src/memkind_memtier.c, line 260 at r2](https://reviewable.io/reviews/memkind/memkind/623#-MYPgE0T7eoCAy4U29qB:-MYPgE0U-ppjtOpjg1vr:b9y1bh) ([raw file](https://github.com/memkind/memkind/blob/42e3343b0c60fbe120dfc45ea292944c8b336154/src/memkind_memtier.c#L260)):*
> ```
> *thres
> ```
where is this freed?
___
*[src/memkind_memtier.c, line 327 at r2](https://reviewable.io/reviews/memkind/memkind/623#-MYPgKUbAKK3g3euhFuP:-MYPgKUbAKK3g3euhFuQ:b-zd1bet) ([raw file](https://github.com/memkind/memkind/blob/42e3343b0c60fbe120dfc45ea292944c8b336154/src/memkind_memtier.c#L327)):*
> ```
> memory->thres
> ```
where is this freed?


<!-- Sent from Reviewable.io -->

2021-04-19 12:02 UTC, bratpiorka reviewed
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/623)* status: 1 of 4 files reviewed, 13 unresolved discussions (waiting on @bratpiorka, @jschmieg, @michalbiesek, and @PatKamin)

___
*[include/memkind_memtier.h, line 99 at r1](https://reviewable.io/reviews/memkind/memkind/623#-MYJD__TDQDJAdtdZw_c:-MYdwXiVBmOeXCZadDz9:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/97d39f1a6405ef634f87c3c975ffed76ce8cf6d2/include/memkind_memtier.h#L99)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> int memtier_builder_add_threshold(struct memtier_builder *builder, size_t init);
> ```
I would rather avoid this function since this functionality could be done by memtier_builder_add_threshold_min_max. If this is explicitly requested by the client, then this should be added now it will confuse the user which function should be used.
</blockquote></details>

Done.
___
*[include/memkind_memtier.h, line 88 at r2](https://reviewable.io/reviews/memkind/memkind/623#-MYdX2OtCD4dI4Q4-_xY:-MYdxBbs3kgOdWFVB6VY:b-34no36) ([raw file](https://github.com/memkind/memkind/blob/42e3343b0c60fbe120dfc45ea292944c8b336154/include/memkind_memtier.h#L88)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> ///
> int memtier_builder_add_threshold_min_max(struct memtier_builder *builder,
>                                           size_t init, size_t min, size_t max);
> ```

I think we should use CTL approach (https://pmem.io/pmdk/manpages/linux/v1.10/libpmemobj/pmemobj_ctl_get.3) - the set part. T
The CTL API will be considered as "API" for the advanced user.
This also required the definition of default values for the dynamic threshold at least for the basic scenario with two tiers.
Regarding default values for more tiers - this would be required using CTL API.

With CTL approach and default values, scenario like below make sense:

//memtier_builder_add_tier(DRAM, ratio=1)
//memtier_builder_add_tier(PMEM, ratio=4)
//memtier_builder_set_policy(MEMTIER_POLICY_DYNAMIC_THRESHOLD)

With API with memtier_builder_add_threshold_min_max/memtier_builder_add_threshold the memtier_builder_set_policy is just redundant operation.

Additional value of the CTL approach is to have a common interface for additional configuration of different policies. In other words, this could be used as a common interface for setting up exclusive policy parameters.

@jschmieg maybe you have additional comments on this.
</blockquote></details>

What do you think if I:
* remove memtier_builder_set_policy call - policy it will be set to STATIC by default unless someone doesn't call memtier_builder_add_threshold_min_max()
* add additional threshold "id" parameter to memtier_builder_add_threshold_min_max(). For id == N this call will set a threshold between Nth and N+1th tier

In this approach, there will be no default parameters for thresholds, so in 2 tiers scenario user will have to provide them. In my opinion we can't really set "right" default values (at least for initial level) so there will be no cases where user want to use them.
___
*[src/memkind_memtier.c, line 51 at r2](https://reviewable.io/reviews/memkind/memkind/623#-MYPmTBl4Hs5sO1uCt1V:-MYdw_Wc3HrUDOlpOF7M:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/42e3343b0c60fbe120dfc45ea292944c8b336154/src/memkind_memtier.c#L51)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> POLICY_DYNAMIC_THRESHOLD_CHANGE_VAL
> ```
THRESHOLD_STEP
</blockquote></details>

Done.
___
*[src/memkind_memtier.c, line 60 at r2](https://reviewable.io/reviews/memkind/memkind/623#-MYPoZO184tV_qmUURua:-MYdhJBeELvhk8F6_FzY:b-83g0qf) ([raw file](https://github.com/memkind/memkind/blob/42e3343b0c60fbe120dfc45ea292944c8b336154/src/memkind_memtier.c#L60)):*
> size_t val; // Actual threshold l

we access this variable like this "thres[i].val" and IMHO val is better than "thres[i].threshold"
___
*[src/memkind_memtier.c, line 108 at r2](https://reviewable.io/reviews/memkind/memkind/623#-MYPrLYn6s4eueNowo0u:-MYdweSg6lvwXLX_5wOI:bj8lgik) ([raw file](https://github.com/memkind/memkind/blob/42e3343b0c60fbe120dfc45ea292944c8b336154/src/memkind_memtier.c#L108)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> memtier_policy_dynamic_threshold_get_kind
> ```
this does two operations, right? get kind - the first loop and "update the threshold config" - the second loop.
</blockquote></details>

Renamed. Note, that to update config this loop needs "size" argument and "dest_tier" calculated in first loop, so I didn't split this function to two separate functions.
___
*[src/memkind_memtier.c, line 141 at r2](https://reviewable.io/reviews/memkind/memkind/623#-MYPhpbG-X6b6VCJ4fIt:-MYdwvXHDgKXWem5FX4d:bs7wumx) ([raw file](https://github.com/memkind/memkind/blob/42e3343b0c60fbe120dfc45ea292944c8b336154/src/memkind_memtier.c#L141)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> cfg[i].kind_ratio * cfg[i + 1].kind_ratio
> ```
this operation could be done one time right? you don't need to calculate it every time you perform looking up for correct memory kind - this is similar to the normalized part you have done in the case of previous policy
</blockquote></details>

Done. 
___
*[src/memkind_memtier.c, line 142 at r2](https://reviewable.io/reviews/memkind/memkind/623#-MYPk4lP6oRbgbJMdRMB:-MYdwuv47z6RQEibA43r:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/42e3343b0c60fbe120dfc45ea292944c8b336154/src/memkind_memtier.c#L142)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

`if else` would be much easier to read. You can even set the `change` value to -1 while declaring it to omit the outer `else` statement and make this `if else` cleaner, too. Like this:

```
        int change = -1;
        if (prev_alloc_size > 0) {
            float actual_ratio = (float)next_alloc_size / prev_alloc_size;
            float diff =
                1.0f - actual_ratio / cfg[i].kind_ratio * cfg[i + 1].kind_ratio;
            if (diff < -POLICY_DYNAMIC_THRESHOLD_TRIGGER)
                    change = 1;
            else if (diff <= POLICY_DYNAMIC_THRESHOLD_TRIGGER)
                change = 0;
        }
```
</blockquote></details>

Done.
___
*[src/memkind_memtier.c, line 151 at r2](https://reviewable.io/reviews/memkind/memkind/623#-MYPnzhKDsfRYaQLcYrk:-MYdwxxn4_FkZRTUIKS1:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/42e3343b0c60fbe120dfc45ea292944c8b336154/src/memkind_memtier.c#L151)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
>             float new_val = thres[i].val *
>                 (1.0 + (float)change * POLICY_DYNAMIC_THRESHOLD_CHANGE_VAL);
>             thres[i].val = (new_val > thres[i].max) ? thres[i].max
>                 : (new_val < thres[i].min)          ? thres[i].min
>                                                     : new_val;
> ```
it will be much more readable with if-else and some macro for this threshold up/down operation 
</blockquote></details>

Done.
___
*[src/memkind_memtier.c, line 209 at r2](https://reviewable.io/reviews/memkind/memkind/623#-MYPj0a077KslRSqZJnp:-MYdx1Kq9KwI1Exdwpd8:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/42e3343b0c60fbe120dfc45ea292944c8b336154/src/memkind_memtier.c#L209)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
>     if ((policy == MEMTIER_POLICY_STATIC_THRESHOLD) ||
>         (policy == MEMTIER_POLICY_DYNAMIC_THRESHOLD)) {
>         builder->policy = policy;
>     } else {
>         log_err("Unrecognized memory policy %u", policy);
>         return -1;
> ```
switch case/default, please.
I think this could be optimized - the decision part with function pointer here but I will handle this in separate PR - you could mark here as TODO use function pointer for decision
</b [...]

2021-04-19 12:30 UTC, michalbiesek requested changes
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/623)* status: 1 of 4 files reviewed, 5 unresolved discussions (waiting on @bratpiorka, @jschmieg, and @PatKamin)

___
*[include/memkind_memtier.h, line 88 at r2](https://reviewable.io/reviews/memkind/memkind/623#-MYdX2OtCD4dI4Q4-_xY:-MYe27SqDeNxEMOAbvBj:bje9dvh) ([raw file](https://github.com/memkind/memkind/blob/42e3343b0c60fbe120dfc45ea292944c8b336154/include/memkind_memtier.h#L88)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

What do you think if I:
* remove memtier_builder_set_policy call - policy it will be set to STATIC by default unless someone doesn't call memtier_builder_add_threshold_min_max()
* add additional threshold "id" parameter to memtier_builder_add_threshold_min_max(). For id == N this call will set a threshold between Nth and N+1th tier

In this approach, there will be no default parameters for thresholds, so in 2 tiers scenario user will have to provide them. In my opinion we can't really set "right" default values (at least for initial level) so there will be no cases where user want to use them.

</blockquote></details>

So in your approach what is the point to have the **memtier_builder_set_policy** function - what's the role of this function?

The memkind_memtier layer could deduct the policy itself only by checking if **memtier_builder_add_threshold_min_max** was called, but  @jschmieg provides a good explanation for leaving the memtier_policy_t parameter and have a universal interface (CTL) to set up additional parameters for different policies - the CTL API allows for this without providing a new function for each new policy.
___
*[src/memkind_memtier.c, line 260 at r2](https://reviewable.io/reviews/memkind/memkind/623#-MYPgE0T7eoCAy4U29qB:-MYe1p5mEZYKJSd4DrLG:bgph76v) ([raw file](https://github.com/memkind/memkind/blob/42e3343b0c60fbe120dfc45ea292944c8b336154/src/memkind_memtier.c#L260)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

Done. I fixed this in memtier_delete_memtier_memory
</blockquote></details>

memtier_builder_delete should be updated.


<!-- Sent from Reviewable.io -->

2021-04-19 12:54 UTC, bratpiorka reviewed
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/623)* status: 1 of 4 files reviewed, 5 unresolved discussions (waiting on @bratpiorka, @jschmieg, and @PatKamin)

___
*[include/memkind_memtier.h, line 88 at r2](https://reviewable.io/reviews/memkind/memkind/623#-MYdX2OtCD4dI4Q4-_xY:-MYeA-Fg79dXV_iPK6RP:bmxarm0) ([raw file](https://github.com/memkind/memkind/blob/42e3343b0c60fbe120dfc45ea292944c8b336154/include/memkind_memtier.h#L88)):*
> rameter and have a universal interface (CTL) to s

No, I wanted to remove memtier_builder_set_policy function. 


<!-- Sent from Reviewable.io -->

2021-04-19 13:33 UTC, PatKamin reviewed
> Reviewed 1 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/623)* status: 2 of 4 files reviewed, 3 unresolved discussions (waiting on @bratpiorka and @jschmieg)



<!-- Sent from Reviewable.io -->

2021-04-20 12:31 UTC, bratpiorka reviewed
> Reviewed 1 of 4 files at r1, 4 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/623)* status: all files reviewed, 3 unresolved discussions (waiting on @jschmieg and @michalbiesek)

___
*[include/memkind_memtier.h, line 88 at r2](https://reviewable.io/reviews/memkind/memkind/623#-MYdX2OtCD4dI4Q4-_xY:-MYjFndGDwE-MpcGsvJ-:b-r10kjq) ([raw file](https://github.com/memkind/memkind/blob/42e3343b0c60fbe120dfc45ea292944c8b336154/include/memkind_memtier.h#L88)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

> rameter and have a universal interface (CTL) to s

No, I wanted to remove memtier_builder_set_policy function. 
</blockquote></details>

OK - I removed memtier_builder_add_threshold_min_max  and added default values
___
*[src/memkind_memtier.c, line 229 at r2](https://reviewable.io/reviews/memkind/memkind/623#-MYPjKhrC9Kmgx-fS4De:-MYjFIVu7-Gf9qgQq3Xw:bdek3t1) ([raw file](https://github.com/memkind/memkind/blob/42e3343b0c60fbe120dfc45ea292944c8b336154/src/memkind_memtier.c#L229)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
>     if (builder->size < 2) {
>         log_err("There should be at least 2 tiers added to builder "
>                 "to define a threshold between them.");
>         return -1;
>     }
> ```
This is error-prone, the order shouldn't manner here

Why the situation is different:
- memtier_builder_add_tier(1)
- memtier_builder_add_tier(2)
- memtier_builder_add_threshold_min_max
- memtier_builder_add_threshold_min_max

Compared to:
- memtier_builder_add_tier(1)
- memtier_builder_add_threshold_min_max
- memtier_builder_add_tier(2)
- memtier_builder_add_threshold_min_max

But see my comment regarding CTL API
</blockquote></details>

done, removed
___
*[src/memkind_memtier.c, line 260 at r2](https://reviewable.io/reviews/memkind/memkind/623#-MYPgE0T7eoCAy4U29qB:-MYjFLJB7IDzMqR4TAdt:b-8rx23u) ([raw file](https://github.com/memkind/memkind/blob/42e3343b0c60fbe120dfc45ea292944c8b336154/src/memkind_memtier.c#L260)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

memtier_builder_delete should be updated.
</blockquote></details>

done - currently "thres" is not a part of builder struct 


<!-- Sent from Reviewable.io -->

2021-04-21 09:01 UTC, bratpiorka reviewed
> Reviewed 2 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/623)* status: all files reviewed, 3 unresolved discussions (waiting on @jschmieg and @michalbiesek)



<!-- Sent from Reviewable.io -->

2021-04-22 07:02 UTC, michalbiesek requested changes
> Reviewed 1 of 4 files at r1, 2 of 4 files at r4, 1 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/623)* status: all files reviewed, 13 unresolved discussions (waiting on @bratpiorka and @jschmieg)

___
*[src/memkind_memtier.c, line 108 at r2](https://reviewable.io/reviews/memkind/memkind/623#-MYPrLYn6s4eueNowo0u:-MYsHY0L0cI53AzuSi7u:bqm5joz) ([raw file](https://github.com/memkind/memkind/blob/42e3343b0c60fbe120dfc45ea292944c8b336154/src/memkind_memtier.c#L108)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

Renamed. Note, that to update config this loop needs "size" argument and "dest_tier" calculated in first loop, so I didn't split this function to two separate functions.
</blockquote></details>

Just to be clear I am not an expert on this, you and @jschmieg know more in this manner.
Correct me if I am wrong - the expected behavior here is once you reach the expected threshold value - you want to keep it in a stable state - in other words, if the ratio will change you want to detect this as soon as possible and adjust the values as quickly as you can.

What if I modify allocations from one tier freeing all the allocations (by memtier_free)  and for the second tier I reallocate memory increasing the memory in the second tier(by memtier_realloc), this threshold update functionality will not be called in this case.

IMHO updating thresholds and getting kind are separated functionality. The operation of updating thresholds should be done/called in each of the memory management function (memtier_free/memtier_*alloc/memtier_posix_memalign)
___
*[src/memkind_memtier.c, line 50 at r4](https://reviewable.io/reviews/memkind/memkind/623#-MYjLC1w7iDQA8-A4P5H:-MYjLC1w7iDQA8-A4P5I:b-w12c3g) ([raw file](https://github.com/memkind/memkind/blob/c19c72e52ff069b6d1706962cd25dcf4e91ed7a0/src/memkind_memtier.c#L50)):*
<details><summary><i alt="summary">Quoted 5 lines of code…</i></summary>

> ```
> // TODO move this after implementation of CTL API
> #define POLICY_DYNAMIC_THRESHOLD_TRIGGER       0.1  // 10%
> #define POLICY_DYNAMIC_THRESHOLD_STEP          0.25 // 25%
> #define POLICY_DYNAMIC_THRESHOLD_CHECK_CNT     5
> #define POLICY_DYNAMIC_THRESHOLD_DEF_INIT_STEP 1024
> ```
</details>

Be more descriptive in the commit message, you could put information about the defaults/behavior or anything which would be easier for other people to understand details of this PR
___
*[src/memkind_memtier.c, line 117 at r4](https://reviewable.io/reviews/memkind/memkind/623#-MYjSFEJ5_-OOiafEf9l:-MYjSFEJ5_-OOiafEf9m:brqunzq) ([raw file](https://github.com/memkind/memkind/blob/c19c72e52ff069b6d1706962cd25dcf4e91ed7a0/src/memkind_memtier.c#L117)):*
> ```
> for (i = 0; i < memory->size - 1; ++i) {
> ```
this is actually not related to this part of code but putting somewhere information (commit message/comment) about the nature of the next threshold values would be beneficial - they are expected to be in ascending order right?
___
*[src/memkind_memtier.c, line 53 at r5](https://reviewable.io/reviews/memkind/memkind/623#-MYptRGp2E4aknNkjmMV:-MYptRGp2E4aknNkjmMW:bp41e2s) ([raw file](https://github.com/memkind/memkind/blob/16dc9bc2a54bfb7bc0ecb00870dbfd8d7b394230/src/memkind_memtier.c#L53)):*
> ```
> POLICY_DYNAMIC_THRESHOLD_CHECK_CNT
> ```
nit: IMHO "POLICY_DYNAMIC_" as prefix could be removed in this macro's
___
*[src/memkind_memtier.c, line 53 at r5](https://reviewable.io/reviews/memkind/memkind/623#-MYq225d4aXOQQ_HY9N2:-MYq225e-pVN79vGJoWK:b-l5yqtr) ([raw file](https://github.com/memkind/memkind/blob/16dc9bc2a54bfb7bc0ecb00870dbfd8d7b394230/src/memkind_memtier.c#L53)):*
> ```
> CHECK_CNT
> ```
REFRESH_CNT?
___
*[src/memkind_memtier.c, line 144 at r5](https://reviewable.io/reviews/memkind/memkind/623#-MYq3lRlA4maKAZZjXnB:-MYq3lRlA4maKAZZjXnC:b7g5gho) ([raw file](https://github.com/memkind/memkind/blob/16dc9bc2a54bfb7bc0ecb00870dbfd8d7b394230/src/memkind_memtier.c#L144)):*
> ```
> actual_ratio
> ```
current_ratio
___
*[src/memkind_memtier.c, line 145 at r5](https://reviewable.io/reviews/memkind/memkind/623#-MYq5afR2el5i2KQsMbs:-MYq5afR2el5i2KQsMbt:bz25lxy) ([raw file](https://github.com/memkind/memkind/blob/16dc9bc2a54bfb7bc0ecb00870dbfd8d7b394230/src/memkind_memtier.c#L145)):*
> ```
> float diff = 1.0f - actual_ratio / thres[i].norm_ratio;
> ```
I could be missing something here, but shouldn't fabs (current_ratio-norm_ratio) would do the job here - for checking if the threshold should be changed? And for checking if the threshold should be increased/decreased you could just compare current_ratio with the actual ratio?
___
*[src/memkind_memtier.c, line 286 at r5](https://reviewable.io/reviews/memkind/memkind/623#-MYpughQ7KFQaJnKpJ0J:-MYpughR0vubwwO7OP0t:b-1s5q5c) ([raw file](https://github.com/memkind/memkind/blob/16dc9bc2a54bfb7bc0ecb00870dbfd8d7b394230/src/memkind_memtier.c#L286)):*
> ```
> builder->size - 1
> ```
To improve the readability of the code this could be exposed as macro, something like:
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
> # define THRESHOLD_NO(b) ((b->size) - 1)
>
> ....
>for (i = 0; i < THRESHOLD_NO(b); ++i) {
> ```
</details>


You probably find a better name for the macro - but I believe you got my point here.
___
*[src/memkind_memtier.c, line 287 at r5](https://reviewable.io/reviews/memkind/memkind/623#-MYpwH5707S_N7Gd8Ohv:-MYpwH58EfqyqP9d8nE8:b-a2xikq) ([raw file](https://github.com/memkind/memkind/blob/16dc9bc2a54bfb7bc0ecb00870dbfd8d7b394230/src/memkind_memtier.c#L287)):*
<details><summary><i alt="summary">Quoted 8 lines of code…</i></summary>

> ```
>             memory->thres[i].val =
>                 (i + 1) * POLICY_DYNAMIC_THRESHOLD_DEF_INIT_STEP;
>             memory->thres[i].min =
>                 ((float)i + 0.5f) * POLICY_DYNAMIC_THRESHOLD_DEF_INIT_STEP;
>             memory->thres[i].max =
>                 ((float)i + 1.5f) * POLICY_DYNAMIC_THRESHOLD_DEF_INIT_STEP - 1;
>             memory->thres[i].norm_ratio =
>                 builder->cfg[i + 1].kind_ratio / builder->cfg[i].kind_ratio;
> ```
</details>

Again this is actually not related to this part of code but putting somewhere information (commit message or whenever eles) that the ranges in different thresholds are expected to not overlap would be beneficial
___
*[test/memkind_memtier_test.cpp, line 217 at r4](https://reviewable.io/reviews/memkind/memkind/623#-MYjai2y8oLvXn_QeS4b:-MYjai2y8oLvXn_QeS4c:b-7y78sc) ([raw file](https://github.com/memkind/memkind/blob/c19c72e52ff069b6d1706962cd25dcf4e91ed7a0/test/memkind_memtier_test.cpp#L217)):*
> ```
> nullptr
> ```
not needed
___
*[test/memkind_memtier_test.cpp, line 233 at r4](https://reviewable.io/reviews/memkind/memkind/623#-MYjaeRt4uMZoDhXlB5i:-MYjaeRt4uMZoDhXlB5j:budbouf) ([raw file](https://github.com/memkind/memkind/blob/c19c72e52ff069b6d1706962cd25dcf4e91ed7a0/test/memkind_memtier_test.cpp#L233)):*
> ```
> = nullptr
> ```
not needed
___
*[test/memkind_memtier_test.cpp, line 251 at r4](https://reviewable.io/reviews/memkind/memkind/623#-MYjacg4EJfM9tk5KFOX:-MYjacg4EJfM9tk5KFOY:b-dvk2aq) ([raw file](https://github.com/memkind/memkind/blob/c19c72e52ff069b6d1706962cd25dcf4e91ed7a0/test/memkind_memtier_test.cpp#L251)):*
> ```
>  nullptr
> ```
not needed
___
*[test/memkind_memtier_test.cpp, line 979 at r5](https://reviewable.io/reviews/memkind/memkind/623#-MYoTRuh1_QAE4gRWYlg:-MYoTRuh1_QAE4gRWYlh:blo0v7v) ([raw file](https://github.com/memkind/memkind/blob/16dc9bc2a54bfb7bc0ecb00870dbfd8d7b394230/test/memkind_memtier_test.cpp#L979)):*
> ```
> unsigned num_allocs = 100;
> ```
const
___
*[test/memkind_memtier_test.cpp, line 984 at r5](https://reviewable.io/reviews/memkind/memkind/623#-MYoTWY76Yq2GFzrGPl-:-MYoTWY76Yq2GFzrGPl0:b-u0w6ul) ([raw file](https://github.com/memkind/memkind/blob/16dc9bc2a54bfb7bc0ecb00870dbfd8d7b394230/test/memkind_memtier_test.cpp#L984)):*
> ```
>     unsigned ratio_check_skip = 100;
>     float ma [...]

2021-04-22 11:42 UTC, bratpiorka reviewed
> Reviewed 4 of 4 files at r6, 3 of 3 files at r7.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/623)* status: all files reviewed, 12 unresolved discussions (waiting on @jschmieg and @michalbiesek)

___
*[src/memkind_memtier.c, line 50 at r4](https://reviewable.io/reviews/memkind/memkind/623#-MYjLC1w7iDQA8-A4P5H:-MYsc3uo5xTqQ2ILNouk:b-iak71t) ([raw file](https://github.com/memkind/memkind/blob/c19c72e52ff069b6d1706962cd25dcf4e91ed7a0/src/memkind_memtier.c#L50)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> // TODO move this after implementation of CTL API
> #define POLICY_DYNAMIC_THRESHOLD_TRIGGER       0.1  // 10%
> #define POLICY_DYNAMIC_THRESHOLD_STEP          0.25 // 25%
> #define POLICY_DYNAMIC_THRESHOLD_CHECK_CNT     5
> #define POLICY_DYNAMIC_THRESHOLD_DEF_INIT_STEP 1024
> ```
Be more descriptive in the commit message, you could put information about the defaults/behavior or anything which would be easier for other people to understand details of this PR
</blockquote></details>

I added comments to the code 
___
*[src/memkind_memtier.c, line 117 at r4](https://reviewable.io/reviews/memkind/memkind/623#-MYjSFEJ5_-OOiafEf9l:-MYsgVQVDzg3iSvYMyZv:bqwltkh) ([raw file](https://github.com/memkind/memkind/blob/c19c72e52ff069b6d1706962cd25dcf4e91ed7a0/src/memkind_memtier.c#L117)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> for (i = 0; i < memory->size - 1; ++i) {
> ```
this is actually not related to this part of code but putting somewhere information (commit message/comment) about the nature of the next threshold values would be beneficial - they are expected to be in ascending order right?
</blockquote></details>

I added comments to the code
___
*[src/memkind_memtier.c, line 53 at r5](https://reviewable.io/reviews/memkind/memkind/623#-MYptRGp2E4aknNkjmMV:-MYsgb9x4eaDHC7gChWh:bb6un1j) ([raw file](https://github.com/memkind/memkind/blob/16dc9bc2a54bfb7bc0ecb00870dbfd8d7b394230/src/memkind_memtier.c#L53)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> POLICY_DYNAMIC_THRESHOLD_CHECK_CNT
> ```
nit: IMHO "POLICY_DYNAMIC_" as prefix could be removed in this macro's
</blockquote></details>

Done
___
*[src/memkind_memtier.c, line 53 at r5](https://reviewable.io/reviews/memkind/memkind/623#-MYq225d4aXOQQ_HY9N2:-MYsVhsP0yurH6vdG0NP:bwpck2h) ([raw file](https://github.com/memkind/memkind/blob/16dc9bc2a54bfb7bc0ecb00870dbfd8d7b394230/src/memkind_memtier.c#L53)):*
> REFRESH_CNT

I prefer "CHECK" - note, that thresholds are refreshed only when ratio is far from desired, not every Nth call.
___
*[src/memkind_memtier.c, line 144 at r5](https://reviewable.io/reviews/memkind/memkind/623#-MYq3lRlA4maKAZZjXnB:-MYsn16-84NUFjvJOmjz:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/16dc9bc2a54bfb7bc0ecb00870dbfd8d7b394230/src/memkind_memtier.c#L144)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> actual_ratio
> ```
current_ratio
</blockquote></details>

Done.
___
*[src/memkind_memtier.c, line 145 at r5](https://reviewable.io/reviews/memkind/memkind/623#-MYq5afR2el5i2KQsMbs:-MYtIl5fCKq-k6ST1A-K:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/16dc9bc2a54bfb7bc0ecb00870dbfd8d7b394230/src/memkind_memtier.c#L145)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> float diff = 1.0f - actual_ratio / thres[i].norm_ratio;
> ```
I could be missing something here, but shouldn't fabs (current_ratio-norm_ratio) would do the job here - for checking if the threshold should be changed? And for checking if the threshold should be increased/decreased you could just compare current_ratio with the actual ratio?
</blockquote></details>

Done.
___
*[src/memkind_memtier.c, line 286 at r5](https://reviewable.io/reviews/memkind/memkind/623#-MYpughQ7KFQaJnKpJ0J:-MYsmvqyAmXrI8DtW9t1:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/16dc9bc2a54bfb7bc0ecb00870dbfd8d7b394230/src/memkind_memtier.c#L286)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> builder->size - 1
> ```
To improve the readability of the code this could be exposed as macro, something like:
> ```
> # define THRESHOLD_NO(b) ((b->size) - 1)
>
> ....
>for (i = 0; i < THRESHOLD_NO(b); ++i) {
> ```

You probably find a better name for the macro - but I believe you got my point here.
</blockquote></details>

Done.
___
*[src/memkind_memtier.c, line 287 at r5](https://reviewable.io/reviews/memkind/memkind/623#-MYpwH5707S_N7Gd8Ohv:-MYsmrOa1xQjmAKXtje3:bjfa7v) ([raw file](https://github.com/memkind/memkind/blob/16dc9bc2a54bfb7bc0ecb00870dbfd8d7b394230/src/memkind_memtier.c#L287)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
>             memory->thres[i].val =
>                 (i + 1) * POLICY_DYNAMIC_THRESHOLD_DEF_INIT_STEP;
>             memory->thres[i].min =
>                 ((float)i + 0.5f) * POLICY_DYNAMIC_THRESHOLD_DEF_INIT_STEP;
>             memory->thres[i].max =
>                 ((float)i + 1.5f) * POLICY_DYNAMIC_THRESHOLD_DEF_INIT_STEP - 1;
>             memory->thres[i].norm_ratio =
>                 builder->cfg[i + 1].kind_ratio / builder->cfg[i].kind_ratio;
> ```
Again this is actually not related to this part of code but putting somewhere information (commit message or whenever eles) that the ranges in different thresholds are expected to not overlap would be beneficial
</blockquote></details>


added
___
*[test/memkind_memtier_test.cpp, line 217 at r4](https://reviewable.io/reviews/memkind/memkind/623#-MYjai2y8oLvXn_QeS4b:-MYt4SnbAb8S2FppTy-T:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/c19c72e52ff069b6d1706962cd25dcf4e91ed7a0/test/memkind_memtier_test.cpp#L217)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> nullptr
> ```
not needed
</blockquote></details>

Done.
___
*[test/memkind_memtier_test.cpp, line 233 at r4](https://reviewable.io/reviews/memkind/memkind/623#-MYjaeRt4uMZoDhXlB5i:-MYt4TLu6haAzkZaYpUg:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/c19c72e52ff069b6d1706962cd25dcf4e91ed7a0/test/memkind_memtier_test.cpp#L233)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> = nullptr
> ```
not needed
</blockquote></details>

Done.
___
*[test/memkind_memtier_test.cpp, line 251 at r4](https://reviewable.io/reviews/memkind/memkind/623#-MYjacg4EJfM9tk5KFOX:-MYt4Tlh9eaV7ZEvlLml:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/c19c72e52ff069b6d1706962cd25dcf4e91ed7a0/test/memkind_memtier_test.cpp#L251)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
>  nullptr
> ```
not needed
</blockquote></details>

Done.
___
*[test/memkind_memtier_test.cpp, line 979 at r5](https://reviewable.io/reviews/memkind/memkind/623#-MYoTRuh1_QAE4gRWYlg:-MYt597h2oiyqvdskrku:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/16dc9bc2a54bfb7bc0ecb00870dbfd8d7b394230/test/memkind_memtier_test.cpp#L979)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> unsigned num_allocs = 100;
> ```
const
</blockquote></details>

Done.
___
*[test/memkind_memtier_test.cpp, line 984 at r5](https://reviewable.io/reviews/memkind/memkind/623#-MYoTWY76Yq2GFzrGPl-:-MYt57ZM82HWjyVCy8kw:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/16dc9bc2a54bfb7bc0ecb00870dbfd8d7b394230/test/memkind_memtier_test.cpp#L984)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
>     unsigned ratio_check_skip = 100;
>     float max_ratio_distance = 0.2; // 20%
> ```
const
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-04-22 12:58 UTC, PatKamin reviewed
> Reviewed 1 of 4 files at r6.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/623)* status: all files reviewed, 13 unresolved discussions (waiting on @bratpiorka, @jschmieg, and @michalbiesek)

___
*[src/memkind_memtier.c, line 161 at r7](https://reviewable.io/reviews/memkind/memkind/623#-MYteE1j2UVhgImgKRND:-MYteE1j2UVhgImgKRNE:b3plqp0) ([raw file](https://github.com/memkind/memkind/blob/449f37ac6f66dace2507d59b6152e5674744f03e/src/memkind_memtier.c#L161)):*
> ```C
>         float current_ratio = -1;
>         if (prev_alloc_size > 0) {
>             float current_ratio = (float)next_alloc_size / prev_alloc_size;
> ```

You redeclare current_ratio here. Remove declaration.


<!-- Sent from Reviewable.io -->

2021-04-22 13:12 UTC, michalbiesek requested changes
> Reviewed 1 of 3 files at r7.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/623)* status: all files reviewed, 7 unresolved discussions (waiting on @bratpiorka and @jschmieg)

___
*[include/memkind_memtier.h, line 202 at r7](https://reviewable.io/reviews/memkind/memkind/623#-MYtb8dI4crnZHPVpzWO:-MYtb8dI4crnZHPVpzWP:b-3zftce) ([raw file](https://github.com/memkind/memkind/blob/449f37ac6f66dace2507d59b6152e5674744f03e/include/memkind_memtier.h#L202)):*
> ```
> void memtier_memory_free(struct memtier_memory *memory, void *ptr);
> ```
I would rather avoid adding this function see my other comment.
___
*[src/memkind_memtier.c, line 58 at r7](https://reviewable.io/reviews/memkind/memkind/623#-MYtZ8lC6g7-PZXLVrUW:-MYtZ8lC6g7-PZXLVrUX:b-ogz0tc) ([raw file](https://github.com/memkind/memkind/blob/449f37ac6f66dace2507d59b6152e5674744f03e/src/memkind_memtier.c#L58)):*
> ```
> allocations
> ```
memory management operations
___
*[src/memkind_memtier.c, line 160 at r7](https://reviewable.io/reviews/memkind/memkind/623#-MYte3yy4r8MJpHGy27U:-MYte3yy4r8MJpHGy27V:b-n7vwuh) ([raw file](https://github.com/memkind/memkind/blob/449f37ac6f66dace2507d59b6152e5674744f03e/src/memkind_memtier.c#L160)):*
> ```
> prev_alloc_size
> ```
Question: so in case, there will be no memory allocated in the current kind (the lowest in the manner of threshold) you always decrease the threshold? I mean is it expected behavior or just avoiding the zero division inside the ratio calculation?
___
*[src/memkind_memtier.c, line 169 at r7](https://reviewable.io/reviews/memkind/memkind/623#-MYtfmPm-i5tObruyZgm:-MYtfmPm-i5tObruyZgn:bbw7ahl) ([raw file](https://github.com/memkind/memkind/blob/449f37ac6f66dace2507d59b6152e5674744f03e/src/memkind_memtier.c#L169)):*
<details><summary><i alt="summary">Quoted 13 lines of code…</i></summary>

> ```
>         // increase/decrease threshold value by THRESHOLD_STEP and clamp it
>         // to (min, max) range
>         if ((prev_alloc_size == 0) || (current_ratio > thres[i].norm_ratio)) {
>             thres[i].val -= thres[i].val * THRESHOLD_STEP;
>             if (thres[i].val < thres[i].min) {
>                 thres[i].val = thres[i].min;
>             }
>         } else {
>             thres[i].val += thres[i].val * THRESHOLD_STEP;
>             if (thres[i].val > thres[i].max) {
>                 thres[i].val = thres[i].max;
>             }
>         }
> ```
</details>

I think this could be slightly modified - imagine the scenario where you reach the limitation here - the min part: thres[i].min
In case you repeat this function you will always override thres[i].min with a new value and then assign thres[i].min once again, or I am missing something here?
___
*[src/memkind_memtier.c, line 358 at r7](https://reviewable.io/reviews/memkind/memkind/623#-MYtdTGG3Vz_xfV4zn00:-MYtdTGG3Vz_xfV4zn01:bsgf0jk) ([raw file](https://github.com/memkind/memkind/blob/449f37ac6f66dace2507d59b6152e5674744f03e/src/memkind_memtier.c#L358)):*
> ```
>     if (memory->policy == MEMTIER_POLICY_DYNAMIC_THRESHOLD) {
>         memtier_policy_dynamic_threshold_update_config(memory);
>     }
> ```
nit: can you please add this similar note "// TODO possible optimization - use function pointer for decision" ?
___
*[tiering/memtier.c, line 92 at r7](https://reviewable.io/reviews/memkind/memkind/623#-MYtamHD2jHq9CVc3Wrj:-MYtamHD2jHq9CVc3Wrk:bp8jwe1) ([raw file](https://github.com/memkind/memkind/blob/449f37ac6f66dace2507d59b6152e5674744f03e/tiering/memtier.c#L92)):*
> ```
> memtier_memory_free(current_memory, ptr)
> ```
If you want to update/refresh the threshold configuration here you could just call 
memtier_realloc(current_memory, ptr, 0);

I would rather avoid extending the external interface at least in this PR.


<!-- Sent from Reviewable.io -->

2021-04-22 13:31 UTC, PatKamin reviewed
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/623)* status: 6 of 7 files reviewed, 8 unresolved discussions (waiting on @bratpiorka and @jschmieg)

___
*[src/memkind_memtier.c, line 289 at r7](https://reviewable.io/reviews/memkind/memkind/623#-MYtib3W3_3P5smBSGh-:-MYtib3W3_3P5smBSGh0:b73fkd5) ([raw file](https://github.com/memkind/memkind/blob/449f37ac6f66dace2507d59b6152e5674744f03e/src/memkind_memtier.c#L289)):*
> ```C
>             log_err("There should be at least 2 tiers added to builder "
>                     "to use POLICY_DYNAMIC_THRESHOLD");
>             goto failure_calloc;
> ```

goto failure_cfg - see that memory->cfg is allocated successfully by now.


<!-- Sent from Reviewable.io -->

2021-04-22 13:40 UTC, bratpiorka reviewed
> Reviewed 3 of 3 files at r8, 1 of 1 files at r9.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/623)* status: all files reviewed, 7 unresolved discussions (waiting on @jschmieg, @michalbiesek, and @PatKamin)

___
*[include/memkind_memtier.h, line 202 at r7](https://reviewable.io/reviews/memkind/memkind/623#-MYtb8dI4crnZHPVpzWO:-MYtiIfdD6X9PLOg_I8Q:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/449f37ac6f66dace2507d59b6152e5674744f03e/include/memkind_memtier.h#L202)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> void memtier_memory_free(struct memtier_memory *memory, void *ptr);
> ```
I would rather avoid adding this function see my other comment.
</blockquote></details>

Done.
___
*[src/memkind_memtier.c, line 58 at r7](https://reviewable.io/reviews/memkind/memkind/623#-MYtZ8lC6g7-PZXLVrUW:-MYtiwSuE1-9xFh1BynQ:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/449f37ac6f66dace2507d59b6152e5674744f03e/src/memkind_memtier.c#L58)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> allocations
> ```
memory management operations
</blockquote></details>

Done.
___
*[src/memkind_memtier.c, line 160 at r7](https://reviewable.io/reviews/memkind/memkind/623#-MYte3yy4r8MJpHGy27U:-MYtj4wr1sntMA0XO2Yp:brq22zi) ([raw file](https://github.com/memkind/memkind/blob/449f37ac6f66dace2507d59b6152e5674744f03e/src/memkind_memtier.c#L160)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> prev_alloc_size
> ```
Question: so in case, there will be no memory allocated in the current kind (the lowest in the manner of threshold) you always decrease the threshold? I mean is it expected behavior or just avoiding the zero division inside the ratio calculation?

</blockquote></details>

There was a bug in my code (redeclaration of current_ratio). After fixing it I changed this code, so currently, when there are no allocations in Nth tier and some allocations in N+1, the threshold is increased, so there will be higher probability that next allocation will go to tier N. So this is an expected behavior
___
*[src/memkind_memtier.c, line 161 at r7](https://reviewable.io/reviews/memkind/memkind/623#-MYteE1j2UVhgImgKRND:-MYtixc57jg8kxYFI02H:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/449f37ac6f66dace2507d59b6152e5674744f03e/src/memkind_memtier.c#L161)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

You redeclare current_ratio here. Remove declaration.
</blockquote></details>

Done.
___
*[src/memkind_memtier.c, line 169 at r7](https://reviewable.io/reviews/memkind/memkind/623#-MYtfmPm-i5tObruyZgm:-MYtmhgU3YOk_xvyNJKP:b-oq2bjs) ([raw file](https://github.com/memkind/memkind/blob/449f37ac6f66dace2507d59b6152e5674744f03e/src/memkind_memtier.c#L169)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
>         // increase/decrease threshold value by THRESHOLD_STEP and clamp it
>         // to (min, max) range
>         if ((prev_alloc_size == 0) || (current_ratio > thres[i].norm_ratio)) {
>             thres[i].val -= thres[i].val * THRESHOLD_STEP;
>             if (thres[i].val < thres[i].min) {
>                 thres[i].val = thres[i].min;
>             }
>         } else {
>             thres[i].val += thres[i].val * THRESHOLD_STEP;
>             if (thres[i].val > thres[i].max) {
>                 thres[i].val = thres[i].max;
>             }
>         }
> ```
I think this could be slightly modified - imagine the scenario where you reach the limitation here - the min part: thres[i].min
In case you repeat this function you will always override thres[i].min with a new value and then assign thres[i].min once again, or I am missing something here?

</blockquote></details>

Yes, you are right. But how I can change the code to avoid this scenario?
___
*[src/memkind_memtier.c, line 289 at r7](https://reviewable.io/reviews/memkind/memkind/623#-MYtib3W3_3P5smBSGh-:-MYtmODw4cRHOiXKJJRO:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/449f37ac6f66dace2507d59b6152e5674744f03e/src/memkind_memtier.c#L289)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

goto failure_cfg - see that memory->cfg is allocated successfully by now.
</blockquote></details>

Done.
___
*[tiering/memtier.c, line 92 at r7](https://reviewable.io/reviews/memkind/memkind/623#-MYtamHD2jHq9CVc3Wrj:-MYtiYKbDZOU9xRSOvvS:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/449f37ac6f66dace2507d59b6152e5674744f03e/tiering/memtier.c#L92)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> memtier_memory_free(current_memory, ptr)
> ```
If you want to update/refresh the threshold configuration here you could just call 
memtier_realloc(current_memory, ptr, 0);

I would rather avoid extending the external interface at least in this PR.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-04-22 14:05 UTC, PatKamin reviewed
> Reviewed 1 of 3 files at r7.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/623)* status: all files reviewed, 9 unresolved discussions (waiting on @bratpiorka, @jschmieg, @michalbiesek, and @PatKamin)

___
*[src/memkind_memtier.c, line 79 at r7](https://reviewable.io/reviews/memkind/memkind/623#-MYtr9Xm8r72g73PkeOv:-MYtdSCh1oJkQ_X11Rkc:b-70qx9p) ([raw file](https://github.com/memkind/memkind/blob/449f37ac6f66dace2507d59b6152e5674744f03e/src/memkind_memtier.c#L79)):*
> ```C
>     size_t min;       // Minimum threshold level
>     size_t max;       // Maximum threshold level
>     float norm_ratio; // Ratio of ratios between adjacent tiers
> ```

// Normalized ratio between two adjacent tiers or sth similar
___
*[src/memkind_memtier.c, line 171 at r7](https://reviewable.io/reviews/memkind/memkind/623#-MYtseEeAn3YQr7gxaUV:-MYtseEeAn3YQr7gxaUW:b-ad9szi) ([raw file](https://github.com/memkind/memkind/blob/449f37ac6f66dace2507d59b6152e5674744f03e/src/memkind_memtier.c#L171)):*
> ```C
>         // increase/decrease threshold value by THRESHOLD_STEP and clamp it
>         // to (min, max) range
>         if ((prev_alloc_size == 0) || (current_ratio > thres[i].norm_ratio)) {
> ```

I think that in case there is no memory allocated on a given memory tier, it's threshold value should be raised, not lowered. By raising this value you would increase chances of allocating memory to the empty tier.
Now, when you lower the value, you decrease chances of allocating memory to the empty tier, thus allowing to allocate more and more memory on the rest of the tiers, leaving this one empty.


<!-- Sent from Reviewable.io -->

2021-04-22 14:16 UTC, PatKamin reviewed
> Reviewed 1 of 3 files at r8, 1 of 1 files at r9.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/623)* status: all files reviewed, 8 unresolved discussions (waiting on @bratpiorka, @jschmieg, and @michalbiesek)

___
*[man/memtier.7, line 54 at r9](https://reviewable.io/reviews/memkind/memkind/623#-MYttom-5kmzSp-IGO3F:-MYttom-5kmzSp-IGO3G:b-foz4z1) ([raw file](https://github.com/memkind/memkind/blob/0a95e652e1b0918924e10d84c8af8f1534b222a1/man/memtier.7#L54)):*
> ```Roff
> all allocations are made in such a way that the ratio between memory kinds is static. In
> .I POLICY_DYNAMIC_THRESHOLD
> the ratio between tiers is kept with a help of set of thresholds between kinds. TODO
> ```

between adjacent memory tiers


<!-- Sent from Reviewable.io -->

2021-04-22 15:07 UTC, PatKamin reviewed
> Reviewed 1 of 4 files at r4, 1 of 2 files at r5, 1 of 3 files at r7, 1 of 3 files at r8.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/623)* status: all files reviewed, 13 unresolved discussions (waiting on @bratpiorka, @jschmieg, and @michalbiesek)

___
*[test/memkind_memtier_test.cpp, line 228 at r9](https://reviewable.io/reviews/memkind/memkind/623#-MYtx6pk2bivHGdiZf50:-MYtx6pk2bivHGdiZf51:b9beujh) ([raw file](https://github.com/memkind/memkind/blob/0a95e652e1b0918924e10d84c8af8f1534b222a1/test/memkind_memtier_test.cpp#L228)):*
> ```cpp
>     tier_kind = memtier_builder_construct_memtier_memory(builder);
>     ASSERT_NE(nullptr, tier_kind);
>     memtier_builder_delete(builder);
> ```

Delete tier_kind, too. Creation of builder and declaration of memtier_memory pointer as well as deleting both can be done in a parent class. Currently it's SetUp() and TearDown() functions are empty.
___
*[test/memkind_memtier_test.cpp, line 246 at r9](https://reviewable.io/reviews/memkind/memkind/623#-MYtxBL8BklHKNSkEihO:-MYtxBL8BklHKNSkEihP:b-c96w4x) ([raw file](https://github.com/memkind/memkind/blob/0a95e652e1b0918924e10d84c8af8f1534b222a1/test/memkind_memtier_test.cpp#L246)):*
> ```cpp
>     tier_kind = memtier_builder_construct_memtier_memory(builder);
>     ASSERT_NE(nullptr, tier_kind);
>     memtier_builder_delete(builder);
> ```

Delete tier_kind, too.
___
*[test/memkind_memtier_test.cpp, line 993 at r9](https://reviewable.io/reviews/memkind/memkind/623#-MYu-W9A2Sb9t5v3SX_g:-MYu-W9A2Sb9t5v3SX_h:befvsd3) ([raw file](https://github.com/memkind/memkind/blob/0a95e652e1b0918924e10d84c8af8f1534b222a1/test/memkind_memtier_test.cpp#L993)):*
> ```cpp
>         allocs.push_back(ptr);
> 
>         if (i < ratio_check_skip) {
> ```

ratio_check_skip is equal to num_allocs, so this will always be true and the rest of this for loop will never be executed.
___
*[test/memkind_memtier_test.cpp, line 1015 at r9](https://reviewable.io/reviews/memkind/memkind/623#-MYu06Aj8sBRKp2A83nU:-MYu06Aj8sBRKp2A83nV:b-fvdwwg) ([raw file](https://github.com/memkind/memkind/blob/0a95e652e1b0918924e10d84c8af8f1534b222a1/test/memkind_memtier_test.cpp#L1015)):*
> ```cpp
> TEST_F(MemkindMemtierThresholdTest, test_various_alloc_size)
> {
>     const float tier_regular_normalized_ratio =
> ```

Move this to the parent class.
___
*[test/tiering_tests.py, line 375 at r9](https://reviewable.io/reviews/memkind/memkind/623#-MYu65I3BzoMxS3yLEBt:-MYu65I460lx6RNtZxh8:b-dmy3l8) ([raw file](https://github.com/memkind/memkind/blob/0a95e652e1b0918924e10d84c8af8f1534b222a1/test/tiering_tests.py#L375)):*
> ```Python
>         self.get_ld_preload_cmd_output(
>             "MEMKIND_MEM_TIERING_CONFIG=DRAM:1,FS_DAX:/tmp/:100M:4,"
>             "FS_DAX:/mnt:150M:8," + policy, log_level="2")
> ```

Add check as in the test_multiple_tiers_wrong_tier() test for the access to the /mnt directory.


<!-- Sent from Reviewable.io -->

2021-04-23 08:15 UTC, bratpiorka reviewed
> Reviewed 4 of 4 files at r10.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/623)* status: all files reviewed, 13 unresolved discussions (waiting on @jschmieg, @michalbiesek, and @PatKamin)

___
*[man/memtier.7, line 54 at r9](https://reviewable.io/reviews/memkind/memkind/623#-MYttom-5kmzSp-IGO3F:-MYxNZBV-HwyUDI4DlfJ:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/0a95e652e1b0918924e10d84c8af8f1534b222a1/man/memtier.7#L54)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

between adjacent memory tiers
</blockquote></details>

Done.
___
*[src/memkind_memtier.c, line 79 at r7](https://reviewable.io/reviews/memkind/memkind/623#-MYtr9Xm8r72g73PkeOv:-MYxNfH99nDjC3ZGcXMQ:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/449f37ac6f66dace2507d59b6152e5674744f03e/src/memkind_memtier.c#L79)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

// Normalized ratio between two adjacent tiers or sth similar
</blockquote></details>

Done.
___
*[src/memkind_memtier.c, line 171 at r7](https://reviewable.io/reviews/memkind/memkind/623#-MYtseEeAn3YQr7gxaUV:-MYxiv869sO0MZXmXOdp:b-qssecl) ([raw file](https://github.com/memkind/memkind/blob/449f37ac6f66dace2507d59b6152e5674744f03e/src/memkind_memtier.c#L171)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

I think that in case there is no memory allocated on a given memory tier, it's threshold value should be raised, not lowered. By raising this value you would increase chances of allocating memory to the empty tier.
Now, when you lower the value, you decrease chances of allocating memory to the empty tier, thus allowing to allocate more and more memory on the rest of the tiers, leaving this one empty.
</blockquote></details>

fixed
___
*[test/memkind_memtier_test.cpp, line 228 at r9](https://reviewable.io/reviews/memkind/memkind/623#-MYtx6pk2bivHGdiZf50:-MYxQ4188yywQ1a2Xwvt:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/0a95e652e1b0918924e10d84c8af8f1534b222a1/test/memkind_memtier_test.cpp#L228)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Delete tier_kind, too. Creation of builder and declaration of memtier_memory pointer as well as deleting both can be done in a parent class. Currently it's SetUp() and TearDown() functions are empty.
</blockquote></details>

Done.
___
*[test/memkind_memtier_test.cpp, line 246 at r9](https://reviewable.io/reviews/memkind/memkind/623#-MYtxBL8BklHKNSkEihO:-MYxQ4Tr3oOTEXadcde8:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/0a95e652e1b0918924e10d84c8af8f1534b222a1/test/memkind_memtier_test.cpp#L246)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Delete tier_kind, too.
</blockquote></details>

Done.
___
*[test/memkind_memtier_test.cpp, line 993 at r9](https://reviewable.io/reviews/memkind/memkind/623#-MYu-W9A2Sb9t5v3SX_g:-MYxfijl8VTmEMQ1wHXH:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/0a95e652e1b0918924e10d84c8af8f1534b222a1/test/memkind_memtier_test.cpp#L993)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

ratio_check_skip is equal to num_allocs, so this will always be true and the rest of this for loop will never be executed.
</blockquote></details>

Done.
___
*[test/memkind_memtier_test.cpp, line 1015 at r9](https://reviewable.io/reviews/memkind/memkind/623#-MYu06Aj8sBRKp2A83nU:-MYxg9Lc3CM4EzJ21Dfr:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/0a95e652e1b0918924e10d84c8af8f1534b222a1/test/memkind_memtier_test.cpp#L1015)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Move this to the parent class.
</blockquote></details>

Done.
___
*[test/tiering_tests.py, line 375 at r9](https://reviewable.io/reviews/memkind/memkind/623#-MYu65I3BzoMxS3yLEBt:-MYxgPiV3ZecYyjM7TyK:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/0a95e652e1b0918924e10d84c8af8f1534b222a1/test/tiering_tests.py#L375)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Add check as in the test_multiple_tiers_wrong_tier() test for the access to the /mnt directory.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-04-23 09:38 UTC, PatKamin reviewed
> Reviewed 4 of 4 files at r10.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/623)* status: all files reviewed, 6 unresolved discussions (waiting on @bratpiorka, @jschmieg, and @michalbiesek)

___
*[test/memkind_memtier_test.cpp, line 1015 at r9](https://reviewable.io/reviews/memkind/memkind/623#-MYu06Aj8sBRKp2A83nU:-MYy4hoR3R8clBlWyQLx:b-u0xvgs) ([raw file](https://github.com/memkind/memkind/blob/0a95e652e1b0918924e10d84c8af8f1534b222a1/test/memkind_memtier_test.cpp#L1015)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

It's not moved. See that it's also used in the previous test. this assignment could be moved to the parent class.


<!-- Sent from Reviewable.io -->

2021-04-23 10:00 UTC, michalbiesek reviewed
> Reviewed 1 of 3 files at r8, 1 of 4 files at r10.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/623)* status: all files reviewed, 3 unresolved discussions (waiting on @bratpiorka and @jschmieg)

___
*[src/memkind_memtier.c, line 169 at r7](https://reviewable.io/reviews/memkind/memkind/623#-MYtfmPm-i5tObruyZgm:-MYy8NXT-dNe_G9szDIR:bruvgcj) ([raw file](https://github.com/memkind/memkind/blob/449f37ac6f66dace2507d59b6152e5674744f03e/src/memkind_memtier.c#L169)):*
Something like the code below would do the job?
<details><summary><i alt="summary">Quoted 12 lines of code…</i></summary>

> ```
>	size_t threshold = thres[i].val * THRESHOLD_STEP;
>	if ((prev_alloc_size == 0) || (current_ratio > thres[i].norm_ratio)) {
>		size_t higher_threshold = thres[i].val + threshold
>		if (new_threshold <= thres[i].max) {
>			thres[i].val = higher_threshold;
>		 }
>	} else {
>		size_t lower_threshold  = thres[i].val - threshold;
>		if (lower_threshold  >= thres[i].min) {
>			thres[i].val = lower_threshold ; 
>		}
>	}
> ```
</details>

___
*[src/memkind_memtier.c, line 66 at r10](https://reviewable.io/reviews/memkind/memkind/623#-MYy9poR4sVopk7jW2VO:-MYy9poR4sVopk7jW2VP:b-64rsbc) ([raw file](https://github.com/memkind/memkind/blob/354914dab0b0344f8c0883fd9edb01367dc31a56/src/memkind_memtier.c#L66)):*
> ```
> // Macro to get number of thresholds from builder
> #define THRESHOLD_NUM(builder) ((builder->size) - 1)
> ```
Actually, you could use the same macro for struct memtier_memory in memtier_policy_dynamic_threshold_get_kind and memtier_policy_dynamic_threshold_update_config

Just update the comment and argument name to be more general


<!-- Sent from Reviewable.io -->

2021-04-23 12:12 UTC, bratpiorka reviewed
> Reviewed 2 of 2 files at r11.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/623)* status: all files reviewed, 3 unresolved discussions (waiting on @jschmieg, @michalbiesek, and @PatKamin)

___
*[src/memkind_memtier.c, line 169 at r7](https://reviewable.io/reviews/memkind/memkind/623#-MYtfmPm-i5tObruyZgm:-MYyVYD_6d2RYIfJrXhd:b-j2754h) ([raw file](https://github.com/memkind/memkind/blob/449f37ac6f66dace2507d59b6152e5674744f03e/src/memkind_memtier.c#L169)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

Something like the code below would do the job?

> ```
>	size_t threshold = thres[i].val * THRESHOLD_STEP;
>	if ((prev_alloc_size == 0) || (current_ratio > thres[i].norm_ratio)) {
>		size_t higher_threshold = thres[i].val + threshold
>		if (new_threshold <= thres[i].max) {
>			thres[i].val = higher_threshold;
>		 }
>	} else {
>		size_t lower_threshold  = thres[i].val - threshold;
>		if (lower_threshold  >= thres[i].min) {
>			thres[i].val = lower_threshold ; 
>		}
>	}
> ```
</blockquote></details>

thanks, it works
___
*[src/memkind_memtier.c, line 66 at r10](https://reviewable.io/reviews/memkind/memkind/623#-MYy9poR4sVopk7jW2VO:-MYyd7AEDjMLclS0wER7:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/354914dab0b0344f8c0883fd9edb01367dc31a56/src/memkind_memtier.c#L66)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> // Macro to get number of thresholds from builder
> #define THRESHOLD_NUM(builder) ((builder->size) - 1)
> ```
Actually, you could use the same macro for struct memtier_memory in memtier_policy_dynamic_threshold_get_kind and memtier_policy_dynamic_threshold_update_config

Just update the comment and argument name to be more general
</blockquote></details>

Done.
___
*[test/memkind_memtier_test.cpp, line 1015 at r9](https://reviewable.io/reviews/memkind/memkind/623#-MYu06Aj8sBRKp2A83nU:-MYyW6Ji3Sc_7cF1AXZ4:bo79glq) ([raw file](https://github.com/memkind/memkind/blob/0a95e652e1b0918924e10d84c8af8f1534b222a1/test/memkind_memtier_test.cpp#L1015)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

It's not moved. See that it's also used in the previous test. this assignment could be moved to the parent class.
</blockquote></details>

sorry, I moved some code but not in all cases. Now it is really DONE


<!-- Sent from Reviewable.io -->

2021-04-23 13:05 UTC, PatKamin reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 2 files at r11.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/623#-:-MYypY219gjDpmMp7BM9:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @jschmieg and @michalbiesek)



<!-- Sent from Reviewable.io -->

2021-04-23 16:26 UTC, michalbiesek approved these changes
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/623)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jschmieg)



<!-- Sent from Reviewable.io -->

2021-04-23 16:26 UTC, merged