Feat ctl policy api
memkind/memkind pull request #624
Opened 2021-04-21 14:08 UTC by bratpiorka

### Description

### Types of changes

- [ ] Bugfix (non-breaking change which fixes issue linked in Description above)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation (correction or otherwise)
- [ ] Cosmetics (whitespace, appearance)
- [ ] Other

### Checklist

- [ ] Code compiles without errors
- [ ] All tests pass locally with my changes (see TESTING section in CONTRIBUTING file)
- [ ] Created tests which will fail without the change (if possible)
- [ ] Extended the README/documentation (if necessary)
- [ ] All newly added files have proprietary license (if necessary)
- [ ] All newly added files are referenced in MANIFEST files (if necessary)

## Further comments

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/memkind/memkind/624)

2021-04-27 07:16 UTC, michalbiesek requested changes
> Reviewed 3 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/624)* status: 3 of 7 files reviewed, 20 unresolved discussions (waiting on @bratpiorka, @jschmieg, and @PatKamin)

___
*[include/memkind_memtier.h, line 95 at r2](https://reviewable.io/reviews/memkind/memkind/624#-MZDLjy3EoORFdY6wWfj:-MZDLjy42BvWiFbo3SnU:b-xbiku5) ([raw file](https://github.com/memkind/memkind/blob/6fededd62e5219a339f05f10fd8956f38389e67b/include/memkind_memtier.h#L95)):*
> ```
> Set memtier property
> ```
Set memtier property
___
*[include/memkind_memtier.h, line 98 at r3](https://reviewable.io/reviews/memkind/memkind/624#-MZH0W3Q4AEwzLkx9EjF:-MZH0W3Q4AEwzLkx9EjG:b-bdqq7a) ([raw file](https://github.com/memkind/memkind/blob/34bb19aa36e7e11b9b3bc5c52e9c878a8135e4eb/include/memkind_memtier.h#L98)):*
> ```
> path path to property in a tree-like structure
> ```
What "tree-like structure" / we don't even have "tree-like" structure in source code - change the description of this supposed to be understandable for the user who uses this library - he/she doesn't need to know the internals how property is stored.
___
*[include/memkind_memtier.h, line 103 at r3](https://reviewable.io/reviews/memkind/memkind/624#-MZH0Xcm7iwjOMC7Ub33:-MZH0Xcm7iwjOMC7Ub34:b4taxib) ([raw file](https://github.com/memkind/memkind/blob/34bb19aa36e7e11b9b3bc5c52e9c878a8135e4eb/include/memkind_memtier.h#L103)):*
> ```
> *path
> ```
path?  -> const char* name
___
*[include/memkind_memtier.h, line 103 at r3](https://reviewable.io/reviews/memkind/memkind/624#-MZH0cQV62vXivOZeM6H:-MZH0cQV62vXivOZeM6I:b-ur24my) ([raw file](https://github.com/memkind/memkind/blob/34bb19aa36e7e11b9b3bc5c52e9c878a8135e4eb/include/memkind_memtier.h#L103)):*
> ```objc
> /// failure
> ///
> int memtier_ctl_set(struct memtier_builder *builder, const char *path,
> ```

Move this function in the end of the header
___
*[include/memkind_memtier.h, line 104 at r3](https://reviewable.io/reviews/memkind/memkind/624#-MZH0xwGDjnBgK0HrWeF:-MZH0xwGDjnBgK0HrWeG:b70nxji) ([raw file](https://github.com/memkind/memkind/blob/34bb19aa36e7e11b9b3bc5c52e9c878a8135e4eb/include/memkind_memtier.h#L104)):*
> ```
> val
> ```
arg
___
*[src/memkind_memtier.c, line 101 at r2](https://reviewable.io/reviews/memkind/memkind/624#-MZDN_VN1BfwCAMlUXwm:-MZDN_VN1BfwCAMlUXwn:bdlr7uu) ([raw file](https://github.com/memkind/memkind/blob/6fededd62e5219a339f05f10fd8956f38389e67b/src/memkind_memtier.c#L101)):*
> ```
> memtier_policy_t policy;             // Tiering policy
> ```
?
___
*[src/memkind_memtier.c, line 267 at r2](https://reviewable.io/reviews/memkind/memkind/624#-MZDNrdyALSCK9Tf-28X:-MZDNrdyALSCK9Tf-28Y:b-7he47s) ([raw file](https://github.com/memkind/memkind/blob/6fededd62e5219a339f05f10fd8956f38389e67b/src/memkind_memtier.c#L267)):*
> ```
> int
> ```
static
___
*[src/memkind_memtier.c, line 321 at r2](https://reviewable.io/reviews/memkind/memkind/624#-MZDNmOp4QX3OTwvQxda:-MZDNmOp4QX3OTwvQxdb:b-7he47s) ([raw file](https://github.com/memkind/memkind/blob/6fededd62e5219a339f05f10fd8956f38389e67b/src/memkind_memtier.c#L321)):*
> ```
> int
> ```
static
___
*[src/memkind_memtier.c, line 462 at r2](https://reviewable.io/reviews/memkind/memkind/624#-MZDO5g1EMrb67Q1WxQd:-MZDO5g1EMrb67Q1WxQe:bmqp61e) ([raw file](https://github.com/memkind/memkind/blob/6fededd62e5219a339f05f10fd8956f38389e67b/src/memkind_memtier.c#L462)):*
> ```
> memory->policy = builder->policy;
> ```
?
___
*[src/memkind_memtier.c, line 69 at r3](https://reviewable.io/reviews/memkind/memkind/624#-MZH9itN8tHxFyGBZZ4_:-MZH9itN8tHxFyGBZZ4a:b-o70oxl) ([raw file](https://github.com/memkind/memkind/blob/34bb19aa36e7e11b9b3bc5c52e9c878a8135e4eb/src/memkind_memtier.c#L69)):*
> ```
> constants defined below are used only in DYNAMIC_THRESHOLD policy
> ```
default values for DYNAMIC_THRESHOLD configuration or something like that should be sufficient
___
*[src/memkind_memtier.c, line 70 at r3](https://reviewable.io/reviews/memkind/memkind/624#-MZH2K3O69HQ36z7eMCY:-MZH2K3O69HQ36z7eMCZ:bxbvo9w) ([raw file](https://github.com/memkind/memkind/blob/34bb19aa36e7e11b9b3bc5c52e9c878a8135e4eb/src/memkind_memtier.c#L70)):*
> ```
> //       These are default values that can be changed using CTL API.
> ```
IMHO this is not needed, the comment here what is the responsibility of these values are enough
___
*[src/memkind_memtier.c, line 74 at r3](https://reviewable.io/reviews/memkind/memkind/624#-MZHACH49S2P9uj7EUsQ:-MZHACH49S2P9uj7EUsR:bsotcyk) ([raw file](https://github.com/memkind/memkind/blob/34bb19aa36e7e11b9b3bc5c52e9c878a8135e4eb/src/memkind_memtier.c#L74)):*
> ```
> // CHANGE        - if an update is triggered, CHANGE is the value (in percents)
> //                 by which threshold will change
> ```
this is not related to your changes but this name is confusing with step - degree/level maybe would be better here
___
*[src/memkind_memtier.c, line 76 at r3](https://reviewable.io/reviews/memkind/memkind/624#-MZH2Xna-_JD4YfiZ9Cz:-MZH2Xna-_JD4YfiZ9D-:b-e26eik) ([raw file](https://github.com/memkind/memkind/blob/34bb19aa36e7e11b9b3bc5c52e9c878a8135e4eb/src/memkind_memtier.c#L76)):*
> ```
> minimum
> ```
? It is not minimum
___
*[src/memkind_memtier.c, line 104 at r3](https://reviewable.io/reviews/memkind/memkind/624#-MZH7wbd-cw8ejk_iIaq:-MZH7wbd-cw8ejk_iIar:b-qmj81x) ([raw file](https://github.com/memkind/memkind/blob/34bb19aa36e7e11b9b3bc5c52e9c878a8135e4eb/src/memkind_memtier.c#L104)):*
> ```
> unsigned cfg_size;                   // Number of Memory Tier configurations
> ```
what is the difference between this and the size field?
___
*[src/memkind_memtier.c, line 108 at r3](https://reviewable.io/reviews/memkind/memkind/624#-MZHAl73DThwpPbO9KFz:-MZHAl73DThwpPbO9KG-:b-wnhsgd) ([raw file](https://github.com/memkind/memkind/blob/34bb19aa36e7e11b9b3bc5c52e9c878a8135e4eb/src/memkind_memtier.c#L108)):*
> ```
> Minimum
> ```
.
___
*[src/memkind_memtier.c, line 112 at r3](https://reviewable.io/reviews/memkind/memkind/624#-MZHApf283SvMy8eSCN4:-MZHApf283SvMy8eSCN5:bjohjp3) ([raw file](https://github.com/memkind/memkind/blob/34bb19aa36e7e11b9b3bc5c52e9c878a8135e4eb/src/memkind_memtier.c#L112)):*
> ```
> Default
> ```
?
___
*[src/memkind_memtier.c, line 121 at r3](https://reviewable.io/reviews/memkind/memkind/624#-MZH1col1P3y7InTbKkM:-MZH1col1P3y7InTbKkN:bom1fxa) ([raw file](https://github.com/memkind/memkind/blob/34bb19aa36e7e11b9b3bc5c52e9c878a8135e4eb/src/memkind_memtier.c#L121)):*
> ```
> unsigned thres_size;           // Number of Memory threshold configuration
> ```
You are sure you need this here? shouldn't this be memtier_memory->size -1?
___
*[src/memkind_memtier.c, line 550 at r3](https://reviewable.io/reviews/memkind/memkind/624#-MZH-nTeCJS4oLGPRw1C:-MZH-nTeCJS4oLGPRw1D:bs5kouy) ([raw file](https://github.com/memkind/memkind/blob/34bb19aa36e7e11b9b3bc5c52e9c878a8135e4eb/src/memkind_memtier.c#L550)):*
<details><summary><i alt="summary">Quoted 8 lines of code…</i></summary>

> ```
>     // NOTE: currently the only supported queries are:
>     // * policy.dynamic_threshold.thresholds[ID].val (size_t)
>     // * policy.dynamic_threshold.thresholds[ID].min (size_t)
>     // * policy.dynamic_threshold.thresholds[ID].max (size_t)
>     // * policy.dynamic_threshold.check_cnt (unsigned)
>     // * policy.dynamic_threshold.trigger (float)
>     // * policy.dynamic_threshold.change (float)
>     // * policy.dynamic_threshold.step (size_t)
> ```
</details>

this should be in manual no need to put this there IMHO the policy prefix is obsolete here
___
*[src/memkind_memtier.c, line 579 at r3](https://reviewable.io/reviews/memkind/memkind/624#-MZH-wJN7GHTu7-IUrCr:-MZH-wJN7GHTu7-IUrCs:b-ct78z9) ([raw file](https://github.com/memkind/memkind/blob/34bb19aa36e7e11b9b3bc5c52e9c878a8135e4eb/src/memkind_memtier.c#L579)):*
<details><summary><i alt="summary">Quoted 17 lines of code…</i></summary>

> ```
>     if (ret && strcmp(res_str, "policy") == 0) {
>         query += chr_read;
>         ret = sscanf(query, "%[^.] [...]

2021-04-27 11:20 UTC, bratpiorka reviewed
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/624)* status: 2 of 8 files reviewed, 20 unresolved discussions (waiting on @jschmieg, @michalbiesek, and @PatKamin)

___
*[include/memkind_memtier.h, line 95 at r2](https://reviewable.io/reviews/memkind/memkind/624#-MZDLjy3EoORFdY6wWfj:-MZHL1xc2Edwlw9MgUA0:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/6fededd62e5219a339f05f10fd8956f38389e67b/include/memkind_memtier.h#L95)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> Set memtier property
> ```
Set memtier property
</blockquote></details>

Done.
___
*[include/memkind_memtier.h, line 98 at r3](https://reviewable.io/reviews/memkind/memkind/624#-MZH0W3Q4AEwzLkx9EjF:-MZHMfhD4b4dNks_U5EM:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/34bb19aa36e7e11b9b3bc5c52e9c878a8135e4eb/include/memkind_memtier.h#L98)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> path path to property in a tree-like structure
> ```
What "tree-like structure" / we don't even have "tree-like" structure in source code - change the description of this supposed to be understandable for the user who uses this library - he/she doesn't need to know the internals how property is stored.
</blockquote></details>

Done.
___
*[include/memkind_memtier.h, line 103 at r3](https://reviewable.io/reviews/memkind/memkind/624#-MZH0Xcm7iwjOMC7Ub33:-MZHLAEW5leqCBT8teVp:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/34bb19aa36e7e11b9b3bc5c52e9c878a8135e4eb/include/memkind_memtier.h#L103)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> *path
> ```
path?  -> const char* name
</blockquote></details>

Done.
___
*[include/memkind_memtier.h, line 103 at r3](https://reviewable.io/reviews/memkind/memkind/624#-MZH0cQV62vXivOZeM6H:-MZHM9Mi2mntKmkmSNzd:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/34bb19aa36e7e11b9b3bc5c52e9c878a8135e4eb/include/memkind_memtier.h#L103)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

Move this function in the end of the header
</blockquote></details>

Done.
___
*[include/memkind_memtier.h, line 104 at r3](https://reviewable.io/reviews/memkind/memkind/624#-MZH0xwGDjnBgK0HrWeF:-MZHM9__CjhA2Ifb19zW:b1syvi9) ([raw file](https://github.com/memkind/memkind/blob/34bb19aa36e7e11b9b3bc5c52e9c878a8135e4eb/include/memkind_memtier.h#L104)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> val
> ```
arg
</blockquote></details>

Why arg? If I have a "property" that I want to set then I can say "set a value of a property" not "set an argument of a property"
___
*[src/memkind_memtier.c, line 101 at r2](https://reviewable.io/reviews/memkind/memkind/624#-MZDN_VN1BfwCAMlUXwm:-MZHhSWqDL-gJVDr80fL:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/6fededd62e5219a339f05f10fd8956f38389e67b/src/memkind_memtier.c#L101)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> memtier_policy_t policy;             // Tiering policy
> ```
?
</blockquote></details>

Done.
___
*[src/memkind_memtier.c, line 267 at r2](https://reviewable.io/reviews/memkind/memkind/624#-MZDNrdyALSCK9Tf-28X:-MZHhlLo10RujxXi95FP:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/6fededd62e5219a339f05f10fd8956f38389e67b/src/memkind_memtier.c#L267)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> int
> ```
static
</blockquote></details>

Done.
___
*[src/memkind_memtier.c, line 321 at r2](https://reviewable.io/reviews/memkind/memkind/624#-MZDNmOp4QX3OTwvQxda:-MZHhpJ49EjG0dtKQ51B:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/6fededd62e5219a339f05f10fd8956f38389e67b/src/memkind_memtier.c#L321)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> int
> ```
static
</blockquote></details>

Done.
___
*[src/memkind_memtier.c, line 462 at r2](https://reviewable.io/reviews/memkind/memkind/624#-MZDO5g1EMrb67Q1WxQd:-MZHhr9tEwhaf2jTY6A8:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/6fededd62e5219a339f05f10fd8956f38389e67b/src/memkind_memtier.c#L462)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> memory->policy = builder->policy;
> ```
?
</blockquote></details>

Done.
___
*[src/memkind_memtier.c, line 69 at r3](https://reviewable.io/reviews/memkind/memkind/624#-MZH9itN8tHxFyGBZZ4_:-MZHNRCa1g0O0lhVBx3M:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/34bb19aa36e7e11b9b3bc5c52e9c878a8135e4eb/src/memkind_memtier.c#L69)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> constants defined below are used only in DYNAMIC_THRESHOLD policy
> ```
default values for DYNAMIC_THRESHOLD configuration or something like that should be sufficient
</blockquote></details>

Done.
___
*[src/memkind_memtier.c, line 70 at r3](https://reviewable.io/reviews/memkind/memkind/624#-MZH2K3O69HQ36z7eMCY:-MZHNRVe8vaT81SOnt1x:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/34bb19aa36e7e11b9b3bc5c52e9c878a8135e4eb/src/memkind_memtier.c#L70)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> //       These are default values that can be changed using CTL API.
> ```
IMHO this is not needed, the comment here what is the responsibility of these values are enough
</blockquote></details>

Done.
___
*[src/memkind_memtier.c, line 74 at r3](https://reviewable.io/reviews/memkind/memkind/624#-MZHACH49S2P9uj7EUsQ:-MZHszmJ2wKlI0CToAVV:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/34bb19aa36e7e11b9b3bc5c52e9c878a8135e4eb/src/memkind_memtier.c#L74)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> // CHANGE        - if an update is triggered, CHANGE is the value (in percents)
> //                 by which threshold will change
> ```
this is not related to your changes but this name is confusing with step - degree/level maybe would be better here
</blockquote></details>

Done.
___
*[src/memkind_memtier.c, line 76 at r3](https://reviewable.io/reviews/memkind/memkind/624#-MZH2Xna-_JD4YfiZ9Cz:-MZHlOucDDF9RTrOiBrL:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/34bb19aa36e7e11b9b3bc5c52e9c878a8135e4eb/src/memkind_memtier.c#L76)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> minimum
> ```
? It is not minimum
</blockquote></details>

Done.
___
*[src/memkind_memtier.c, line 104 at r3](https://reviewable.io/reviews/memkind/memkind/624#-MZH7wbd-cw8ejk_iIaq:-MZHjVE33GyYhxM_lSxH:b-8hqf07) ([raw file](https://github.com/memkind/memkind/blob/34bb19aa36e7e11b9b3bc5c52e9c878a8135e4eb/src/memkind_memtier.c#L104)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> unsigned cfg_size;                   // Number of Memory Tier configurations
> ```
what is the difference between this and the size field?
</blockquote></details>

Done. I left only "cfg_size". I added "cfg_" prefix because I also added "thres_size"
___
*[src/memkind_memtier.c, line 108 at r3](https://reviewable.io/reviews/memkind/memkind/624#-MZHAl73DThwpPbO9KFz:-MZHn8Wg-QyImhgDvcga:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/34bb19aa36e7e11b9b3bc5c52e9c878a8135e4eb/src/memkind_memtier.c#L108)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> Minimum
> ```
.
</blockquote></details>

Done.
___
*[src/memkind_memtier.c, line 112 at r3](https://reviewable.io/reviews/memkind/memkind/624#-MZHApf283SvMy8eSCN4:-MZHgPZA5tP40bdtz6ex:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/34bb19aa36e7e11b9b3bc5c52e9c878a8135e4eb/src/memkind_memtier.c#L112)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> Default
> ```
?
</blo [...]

2021-04-27 12:06 UTC, michalbiesek requested changes
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/624)* status: 2 of 8 files reviewed, 6 unresolved discussions (waiting on @bratpiorka, @jschmieg, @michalbiesek, and @PatKamin)

___
*[man/memkind_memtier.3, line 55 at r4](https://reviewable.io/reviews/memkind/memkind/624#-MZI3vpS3hn0KFyk2SDz:-MZI3vpS3hn0KFyk2SE-:bmmm7m7) ([raw file](https://github.com/memkind/memkind/blob/90fd476c8d6d033d5e998d4b669b407759473586/man/memkind_memtier.3#L55)):*
> ```
> POLICY
> ```
MEMTIER PROPERTY
___
*[src/memkind_memtier.c, line 114 at r4](https://reviewable.io/reviews/memkind/memkind/624#-MZI5EYn-fOQvWbM1bWQ:-MZI5EYn-fOQvWbM1bWR:bzfmqx2) ([raw file](https://github.com/memkind/memkind/blob/90fd476c8d6d033d5e998d4b669b407759473586/src/memkind_memtier.c#L114)):*
> ```
> size
> ```
rename this to cfg_size and update THRESHOLD_NUM(obj)  and use it for memtier_memory and for the builder object in your changes
___
*[src/memkind_memtier.c, line 253 at r4](https://reviewable.io/reviews/memkind/memkind/624#-MZI4OoOBk3Wp-iwro0O:-MZI4OoPD_wrfBj4yqHl:b-tqkxsv) ([raw file](https://github.com/memkind/memkind/blob/90fd476c8d6d033d5e998d4b669b407759473586/src/memkind_memtier.c#L253)):*
> ```
> THRESHOLD_CHANGE
> ```
thres_degree?
___
*[src/memkind_memtier.c, line 328 at r4](https://reviewable.io/reviews/memkind/memkind/624#-MZI9lFpCsxRQVLWuFy7:-MZI9lFpCsxRQVLWuFy8:bapclo3) ([raw file](https://github.com/memkind/memkind/blob/90fd476c8d6d033d5e998d4b669b407759473586/src/memkind_memtier.c#L328)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
>     if (builder->thres_size > id) {
>         // nothing to do
>         return 0;
>     }
> ```
</details>

So in the case of two tiers - I cannot define the threshold for tier 2 then for tier 1?
___
*[src/memkind_memtier.c, line 334 at r4](https://reviewable.io/reviews/memkind/memkind/624#-MZIAzv81WLIeyoajCLJ:-MZIAzv96Xk1lnjVCMvW:b-lecpqb) ([raw file](https://github.com/memkind/memkind/blob/90fd476c8d6d033d5e998d4b669b407759473586/src/memkind_memtier.c#L334)):*
> ```
>     struct memtier_threshold_cfg *thres =
>         jemk_realloc(builder->thres, sizeof(*thres) * (id + 1));
> ```

IMHO your logic would be fairly simpler if you handle builder->thres - the reallocation part during adding a new tier to the builder object, and I am aware that this is used only in case of a dynamic policy.

Not sure maybe just adding variant as a parameter for memtier_builder_new would do the job we will avoid another function with passing information about the policy to the builder.
___
*[src/memkind_memtier.c, line 394 at r4](https://reviewable.io/reviews/memkind/memkind/624#-MZIC82SA_XM4i3rrnS0:-MZIC82SA_XM4i3rrnS1:b2tkj2m) ([raw file](https://github.com/memkind/memkind/blob/90fd476c8d6d033d5e998d4b669b407759473586/src/memkind_memtier.c#L394)):*
> ```
> memory->thres
> ```
where is this freed in case of failure of memtier_policy_dynamic_threshold_construct_memtier_memory ?


<!-- Sent from Reviewable.io -->

2021-04-27 12:53 UTC, bratpiorka reviewed
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/624)* status: 2 of 8 files reviewed, 6 unresolved discussions (waiting on @jschmieg, @michalbiesek, and @PatKamin)

___
*[man/memkind_memtier.3, line 55 at r4](https://reviewable.io/reviews/memkind/memkind/624#-MZI3vpS3hn0KFyk2SDz:-MZIFdbT55vJik-a2knF:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/90fd476c8d6d033d5e998d4b669b407759473586/man/memkind_memtier.3#L55)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> POLICY
> ```
MEMTIER PROPERTY
</blockquote></details>

Done.
___
*[src/memkind_memtier.c, line 114 at r4](https://reviewable.io/reviews/memkind/memkind/624#-MZI5EYn-fOQvWbM1bWQ:-MZIG00H6C0F7uzSvCiA:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/90fd476c8d6d033d5e998d4b669b407759473586/src/memkind_memtier.c#L114)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> size
> ```
rename this to cfg_size and update THRESHOLD_NUM(obj)  and use it for memtier_memory and for the builder object in your changes
</blockquote></details>

Done.
___
*[src/memkind_memtier.c, line 253 at r4](https://reviewable.io/reviews/memkind/memkind/624#-MZI4OoOBk3Wp-iwro0O:-MZIGAju78DDYvjiv7H-:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/90fd476c8d6d033d5e998d4b669b407759473586/src/memkind_memtier.c#L253)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> THRESHOLD_CHANGE
> ```
thres_degree?
</blockquote></details>

Done.
___
*[src/memkind_memtier.c, line 328 at r4](https://reviewable.io/reviews/memkind/memkind/624#-MZI9lFpCsxRQVLWuFy7:-MZIIEOuEBFWHFVWsHBG:b427lwa) ([raw file](https://github.com/memkind/memkind/blob/90fd476c8d6d033d5e998d4b669b407759473586/src/memkind_memtier.c#L328)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
>     if (builder->thres_size > id) {
>         // nothing to do
>         return 0;
>     }
> ```
So in the case of two tiers - I cannot define the threshold for tier 2 then for tier 1?
</blockquote></details>

This function adds new threshold config if needed and set it's default parameters. In your scenario, when you first define e.g. "val" for threshold#1, both threshold#0 and threshold#1 will be added to builder and it's properties will be set to default. Later, you can overwrite default parameters but this function will not process these thresholds anymore.
___
*[src/memkind_memtier.c, line 334 at r4](https://reviewable.io/reviews/memkind/memkind/624#-MZIAzv81WLIeyoajCLJ:-MZIKNdr1XYXsHk4Q6pB:b-j1dase) ([raw file](https://github.com/memkind/memkind/blob/90fd476c8d6d033d5e998d4b669b407759473586/src/memkind_memtier.c#L334)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
>     struct memtier_threshold_cfg *thres =
>         jemk_realloc(builder->thres, sizeof(*thres) * (id + 1));
> ```

IMHO your logic would be fairly simpler if you handle builder->thres - the reallocation part during adding a new tier to the builder object, and I am aware that this is used only in case of a dynamic policy.

Not sure maybe just adding variant as a parameter for memtier_builder_new would do the job we will avoid another function with passing information about the policy to the builder.
</blockquote></details>

Yes it could be simpler but current code addresses all usage cases and is very flexible - you can add tiers/set policy/set properties in any order you want, and the whole thing is validated at memtier_policy_dynamic_threshold_construct_memtier_memory. 
___
*[src/memkind_memtier.c, line 394 at r4](https://reviewable.io/reviews/memkind/memkind/624#-MZIC82SA_XM4i3rrnS0:-MZIHHoV8tfAGDoJFVtT:b-yqwp04) ([raw file](https://github.com/memkind/memkind/blob/90fd476c8d6d033d5e998d4b669b407759473586/src/memkind_memtier.c#L394)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> memory->thres
> ```
where is this freed in case of failure of memtier_policy_dynamic_threshold_construct_memtier_memory ?
</blockquote></details>

Done, added freeing of this.


<!-- Sent from Reviewable.io -->

2021-04-27 13:03 UTC, michalbiesek requested changes
> Reviewed 2 of 5 files at r4, 1 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/624)* status: 5 of 8 files reviewed, 3 unresolved discussions (waiting on @bratpiorka, @jschmieg, and @PatKamin)

___
*[src/memkind_memtier.c, line 328 at r4](https://reviewable.io/reviews/memkind/memkind/624#-MZI9lFpCsxRQVLWuFy7:-MZIP03J1bUq5bzZNmXX:b5vuxil) ([raw file](https://github.com/memkind/memkind/blob/90fd476c8d6d033d5e998d4b669b407759473586/src/memkind_memtier.c#L328)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

This function adds new threshold config if needed and set it's default parameters. In your scenario, when you first define e.g. "val" for threshold#1, both threshold#0 and threshold#1 will be added to builder and it's properties will be set to default. Later, you can overwrite default parameters but this function will not process these thresholds anymore.
</blockquote></details>

What are the default parameters in the case of three tiers when I just define the values for the last one?
___
*[src/memkind_memtier.c, line 334 at r4](https://reviewable.io/reviews/memkind/memkind/624#-MZIAzv81WLIeyoajCLJ:-MZIP5UJ8NokY8FqYYMO:b-z77nzg) ([raw file](https://github.com/memkind/memkind/blob/90fd476c8d6d033d5e998d4b669b407759473586/src/memkind_memtier.c#L334)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

Yes it could be simpler but current code addresses all usage cases and is very flexible - you can add tiers/set policy/set properties in any order you want, and the whole thing is validated at memtier_policy_dynamic_threshold_construct_memtier_memory. 
</blockquote></details>

ok, I would make this API rearrangement in separate PR.
___
*[src/memkind_memtier.c, line 390 at r5](https://reviewable.io/reviews/memkind/memkind/624#-MZIPlO7C4bOjBPWS19A:-MZIPlO7C4bOjBPWS19B:b5ss84v) ([raw file](https://github.com/memkind/memkind/blob/a6dbe21a1e667b41ae91b878a928aa811f65c80a/src/memkind_memtier.c#L390)):*
> ```
> builder->cfg_size - 1
> ```
THRESHOLD_NUM
___
*[src/memkind_memtier.c, line 409 at r5](https://reviewable.io/reviews/memkind/memkind/624#-MZIPjPk80NUEYma-ae3:-MZIPjPk80NUEYma-ae4:b5ss84v) ([raw file](https://github.com/memkind/memkind/blob/a6dbe21a1e667b41ae91b878a928aa811f65c80a/src/memkind_memtier.c#L409)):*
> ```
> builder->cfg_size - 1
> ```
THRESHOLD_NUM


<!-- Sent from Reviewable.io -->

2021-04-27 14:13 UTC, bratpiorka reviewed
> Reviewed 1 of 7 files at r1, 2 of 6 files at r2, 2 of 5 files at r4, 1 of 2 files at r5, 2 of 2 files at r6.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/624)* status: all files reviewed, 3 unresolved discussions (waiting on @jschmieg, @michalbiesek, and @PatKamin)

___
*[src/memkind_memtier.c, line 328 at r4](https://reviewable.io/reviews/memkind/memkind/624#-MZI9lFpCsxRQVLWuFy7:-MZIe7Rd2PRGhndZeZB1:bp6siia) ([raw file](https://github.com/memkind/memkind/blob/90fd476c8d6d033d5e998d4b669b407759473586/src/memkind_memtier.c#L328)):*
> define the values for the last one

I added "test_tier_policy_dynamic_threshold_ctl_set_only_last" test that test this scenario. It sets val & max for thresold 1. After constructing memtier memory whole set of thresolds is: [(512, 1024, 1535), (1536, 8000, 9000)]
___
*[src/memkind_memtier.c, line 390 at r5](https://reviewable.io/reviews/memkind/memkind/624#-MZIPlO7C4bOjBPWS19A:-MZIRayL0HeU_l1iAXB8:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/a6dbe21a1e667b41ae91b878a928aa811f65c80a/src/memkind_memtier.c#L390)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> builder->cfg_size - 1
> ```
THRESHOLD_NUM
</blockquote></details>

Done.
___
*[src/memkind_memtier.c, line 409 at r5](https://reviewable.io/reviews/memkind/memkind/624#-MZIPjPk80NUEYma-ae3:-MZIRoLm84ubVXHsaEoh:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/a6dbe21a1e667b41ae91b878a928aa811f65c80a/src/memkind_memtier.c#L409)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> builder->cfg_size - 1
> ```
THRESHOLD_NUM
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-04-28 07:38 UTC, PatKamin reviewed
> Reviewed 2 of 7 files at r1, 2 of 5 files at r4, 1 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/624)* status: 7 of 8 files reviewed, 4 unresolved discussions (waiting on @bratpiorka, @jschmieg, and @michalbiesek)

___
*[src/memkind_memtier.c, line 412 at r7](https://reviewable.io/reviews/memkind/memkind/624#-MZMKqia2KQqrjTRaODk:-MZMKqia2KQqrjTRaODl:b-1v6byt) ([raw file](https://github.com/memkind/memkind/blob/644c9281d47ee5991a244808065243a21069d858/src/memkind_memtier.c#L412)):*
> ```C
>         int old_size = builder->thres_size;
>         int ret =
>             memtier_builder_create_threshold(builder, builder->cfg_size - 2);
> ```

THRESHOLD_NUM - 1


<!-- Sent from Reviewable.io -->

2021-04-28 08:14 UTC, bratpiorka reviewed
> Reviewed 1 of 1 files at r7, 1 of 1 files at r8.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/624)* status: all files reviewed, 4 unresolved discussions (waiting on @jschmieg, @michalbiesek, and @PatKamin)

___
*[src/memkind_memtier.c, line 412 at r7](https://reviewable.io/reviews/memkind/memkind/624#-MZMKqia2KQqrjTRaODk:-MZMRLEx5AS6ztTtcrUF:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/644c9281d47ee5991a244808065243a21069d858/src/memkind_memtier.c#L412)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

THRESHOLD_NUM - 1
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-04-28 10:02 UTC, PatKamin reviewed
> Reviewed 1 of 2 files at r6.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/624)* status: all files reviewed, 5 unresolved discussions (waiting on @bratpiorka, @jschmieg, @michalbiesek, and @PatKamin)

___
*[src/memkind_memtier.c, line 592 at r7](https://reviewable.io/reviews/memkind/memkind/624#-MZMvTXNAq88PML8p30_:-MZMvTXNAq88PML8p30a:b-idby8n) ([raw file](https://github.com/memkind/memkind/blob/644c9281d47ee5991a244808065243a21069d858/src/memkind_memtier.c#L592)):*
> ```C
>             }
>         } else if (ret && strcmp(name_substr, "check_cnt") == 0) {
>             builder->check_cnt = *(unsigned *)val;
> ```

There should be some kind of validation for these values.


<!-- Sent from Reviewable.io -->

2021-04-28 10:06 UTC, PatKamin reviewed
> Reviewed 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/624)* status: all files reviewed, 6 unresolved discussions (waiting on @bratpiorka, @jschmieg, @michalbiesek, and @PatKamin)

___
*[test/memkind_memtier_test.cpp, line 282 at r7](https://reviewable.io/reviews/memkind/memkind/624#-MZMvsmq7wN5vTY2U6U9:-MZMvsmq7wN5vTY2U6UA:br9rnok) ([raw file](https://github.com/memkind/memkind/blob/644c9281d47ee5991a244808065243a21069d858/test/memkind_memtier_test.cpp#L282)):*
> ```cpp
>     res = memtier_builder_add_tier(m_builder, MEMKIND_REGULAR, 2);
>     ASSERT_EQ(0, res);
>     size_t val = 64;
> ```

Add a negative test with val as alphanumeric.


<!-- Sent from Reviewable.io -->

2021-04-28 10:07 UTC, michalbiesek approved these changes
> Reviewed 1 of 5 files at r4, 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/624)* status: all files reviewed, 4 unresolved discussions (waiting on @bratpiorka, @jschmieg, and @PatKamin)

___
*[src/memkind_memtier.c, line 328 at r4](https://reviewable.io/reviews/memkind/memkind/624#-MZI9lFpCsxRQVLWuFy7:-MZMtAn27PxY4HksH4sL:b-2w1lap) ([raw file](https://github.com/memkind/memkind/blob/90fd476c8d6d033d5e998d4b669b407759473586/src/memkind_memtier.c#L328)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

> define the values for the last one

I added "test_tier_policy_dynamic_threshold_ctl_set_only_last" test that test this scenario. It sets val & max for thresold 1. After constructing memtier memory whole set of thresolds is: [(512, 1024, 1535), (1536, 8000, 9000)]
</blockquote></details>

So the default values stay untouched, and there is a pattern for default values for all the tiers.
Not sure if the user will be aware of this, maybe printing will be the best solution here (but this is a different issue), anyway, the reason I am asking is to find the best approach in case of using this API.
@jschmieg any comment on this?


<!-- Sent from Reviewable.io -->

2021-04-28 10:49 UTC, bratpiorka reviewed
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/624)* status: all files reviewed, 2 unresolved discussions (waiting on @jschmieg and @PatKamin)

___
*[src/memkind_memtier.c, line 592 at r7](https://reviewable.io/reviews/memkind/memkind/624#-MZMvTXNAq88PML8p30_:-MZN48r9AmBRyz8syeLj:b-oayg17) ([raw file](https://github.com/memkind/memkind/blob/644c9281d47ee5991a244808065243a21069d858/src/memkind_memtier.c#L592)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

There should be some kind of validation for these values.
</blockquote></details>

"trigger" and "degree" are validated in memtier_policy_dynamic_threshold_construct_memtier_memory, "check_cnt" and "step" could be basically any integer positive value, and because they are casted from "void*" no validation is needed. But on the other hand, because of this casting, I can't really do any validation here.
___
*[test/memkind_memtier_test.cpp, line 282 at r7](https://reviewable.io/reviews/memkind/memkind/624#-MZMvsmq7wN5vTY2U6U9:-MZN4sOQ-DN323JH1-Vb:b93yyut) ([raw file](https://github.com/memkind/memkind/blob/644c9281d47ee5991a244808065243a21069d858/test/memkind_memtier_test.cpp#L282)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Add a negative test with val as alphanumeric.
</blockquote></details>

Val is passed as "void*" and casted later to desired type, so even if I pass "a1b2b3" this will be interpreted as some possibly valid value. I have some negative tests for this API but because of this cast, validation is limited.


<!-- Sent from Reviewable.io -->

2021-04-29 10:17 UTC, PatKamin reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/624#-:-MZS7c5F8Y2xoFf_rXav:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jschmieg)



<!-- Sent from Reviewable.io -->

2021-04-29 10:20 UTC, merged