[WIP] Remove mallocx/rallocx check
memkind/memkind pull request #659
Opened 2021-06-01 09:11 UTC by michalbiesek

- allocx() size class overflow is behavior defined since jemalloc 4.1.0

2021-06-08 06:24 UTC, PatKamin requested changes
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/659)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @michalbiesek)

___
*[src/memkind_arena.c, line 708 at r1](https://reviewable.io/reviews/memkind/memkind/659#-MbeHfOI4vNZ26eExyBy:-MbeHfOI4vNZ26eExyBz:b-o94q6a) ([raw file](https://github.com/memkind/memkind/blob/6cabe79814139724339f08455cc6d30feb8bcab8/src/memkind_arena.c#L708)):*
> ```C
>             errno = ENOMEM;
>         return ptr;
>     } else {
> ```

`else` is not needed, just return `ptr`


<!-- Sent from Reviewable.io -->

2021-06-08 06:45 UTC, bratpiorka reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/659#-:-MbeM_MX9uqPEkgJwqI-:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @michalbiesek)



<!-- Sent from Reviewable.io -->

2021-06-08 09:27 UTC, michalbiesek reviewed
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/659)* status: all files reviewed, 1 unresolved discussion (waiting on @PatKamin)

___
*[src/memkind_arena.c, line 708 at r1](https://reviewable.io/reviews/memkind/memkind/659#-MbeHfOI4vNZ26eExyBy:-Mbewi99EqaGNzCU3WfZ:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/6cabe79814139724339f08455cc6d30feb8bcab8/src/memkind_arena.c#L708)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

`else` is not needed, just return `ptr`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-06-08 09:48 UTC, PatKamin approved these changes
> Reviewed 1 of 1 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/659)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @michalbiesek)



<!-- Sent from Reviewable.io -->

2021-07-07 07:11 UTC, bratpiorka approved these changes
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/659)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @michalbiesek)



<!-- Sent from Reviewable.io -->

2021-07-20 05:39 UTC, PatKamin approved these changes
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/659)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @michalbiesek)



<!-- Sent from Reviewable.io -->

2021-07-20 06:55 UTC, merged