Save logs from each process
memkind/memkind pull request #696
Opened 2021-07-22 10:38 UTC by jacekgrzybek

Save logs named by number pid of process

2021-07-22 11:07 UTC, PatKamin reviewed
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/696)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @jacekgrzybek)

___
*[tiering/memtier_log.c, line 45 at r1](https://reviewable.io/reviews/memkind/memkind/696#-MfCtJX90P6KWxKf8pFf:-MfCtJX90P6KWxKf8pFg:b-xekyf7) ([raw file](https://github.com/memkind/memkind/blob/1d8e55f5eda752661d5c38c1e06d9b56226e8d55/tiering/memtier_log.c#L45)):*
> ```C
> 	if(fd == -1){
> 		close(fd);
> 		fd = open(fileName, O_CREAT | O_WRONLY, 0600);
> ```

Check the return code for errors.
___
*[tiering/memtier_log.c, line 64 at r1](https://reviewable.io/reviews/memkind/memkind/696#-MfCtG4f4LIhqb3WC7tw:-MfCtG4g8rVLGfBc4rcV:ba6jeih) ([raw file](https://github.com/memkind/memkind/blob/1d8e55f5eda752661d5c38c1e06d9b56226e8d55/tiering/memtier_log.c#L64)):*
> ```C
>     char fileName[20];
>     sprintf(fileName, "%d", pid);
>     strncat(fileName, ".log", 4);
> ```

Do this in one line, please.


<!-- Sent from Reviewable.io -->

2021-07-22 11:08 UTC, bratpiorka reviewed
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/696)* status: all files reviewed, 5 unresolved discussions (waiting on @jacekgrzybek)

___
*[src/memkind_log.c, line 51 at r1](https://reviewable.io/reviews/memkind/memkind/696#-MfCsbgO2ZRIJKWrXeJ4:-MfCsbgO2ZRIJKWrXeJ5:b7oi40q) ([raw file](https://github.com/memkind/memkind/blob/1d8e55f5eda752661d5c38c1e06d9b56226e8d55/src/memkind_log.c#L51)):*
> ```C
> }
> 
> static void save_log_to_file(char *log, char *fileName){
> ```

please run "make code-style-apply"
___
*[src/memkind_log.c, line 66 at r1](https://reviewable.io/reviews/memkind/memkind/696#-MfCsiaS-uMhhgcw2Vbm:-MfCsiaS-uMhhgcw2Vbn:b-69dmdl) ([raw file](https://github.com/memkind/memkind/blob/1d8e55f5eda752661d5c38c1e06d9b56226e8d55/src/memkind_log.c#L66)):*
> ```C
>     pthread_once(&init_once, log_init_once);
> 
>     static char buf[4096], *b;
> ```

"b" is not used in this function.. it looks like this is a copy of code from memtier_log.c, where this var is used to handle message overflow case. Please add handling overflow here or remove this variable
___
*[src/memkind_log.c, line 73 at r1](https://reviewable.io/reviews/memkind/memkind/696#-MfCt6tz6Bxu_gIZHBWC:-MfCt6tz6Bxu_gIZHBWD:b265w3i) ([raw file](https://github.com/memkind/memkind/blob/1d8e55f5eda752661d5c38c1e06d9b56226e8d55/src/memkind_log.c#L73)):*
> ```C
>     b += len + 1;
> 
>     int pid = getpid();
> ```

please wrap all code related to writing to file with #ifdef. This code should be enabled only with e.g. --enable_logging_to_file (or better name) 


<!-- Sent from Reviewable.io -->

2021-07-23 06:59 UTC, PatKamin reviewed
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/696)* status: all files reviewed, 11 unresolved discussions (waiting on @jacekgrzybek)

___
*[src/memkind_log.c, line 14 at r2](https://reviewable.io/reviews/memkind/memkind/696#-MfH1SXF-BOhn899TAZ2:-MfH1SXF-BOhn899TAZ3:bwjlpbl) ([raw file](https://github.com/memkind/memkind/blob/e99ee14572207725ccd0db3158bfb8db11009ed6/src/memkind_log.c#L14)):*
> ```C
> #include <stdlib.h>
> #include <string.h>
> #include <sys/stat.h>
> ```

Redundant import.
___
*[src/memkind_log.c, line 16 at r2](https://reviewable.io/reviews/memkind/memkind/696#-MfH8Ki4BqFoDBQhub_l:-MfH8Ki4BqFoDBQhub_m:bkycap1) ([raw file](https://github.com/memkind/memkind/blob/e99ee14572207725ccd0db3158bfb8db11009ed6/src/memkind_log.c#L16)):*
> ```C
> #include <sys/stat.h>
> #include <fcntl.h>
> #include <unistd.h>
> ```

Alphabetical order, please.
___
*[src/memkind_log.c, line 55 at r2](https://reviewable.io/reviews/memkind/memkind/696#-MfH58bJ2rDZWSTMihga:-MfH58bK0SlYv3hqdi2T:b-5aatk4) ([raw file](https://github.com/memkind/memkind/blob/e99ee14572207725ccd0db3158bfb8db11009ed6/src/memkind_log.c#L55)):*
> ```C
> 	int fd = open(fileName, O_WRONLY | O_APPEND);
> 	if (fd == -1)
>         fd = open(fileName, O_CREAT | O_WRONLY, 0600);
> ```

If it fails, do not try to write to fd.
___
*[src/memkind_log.c, line 73 at r2](https://reviewable.io/reviews/memkind/memkind/696#-MfH6xvH2MegsuK4DsQz:-MfH6xvH2MegsuK4DsR-:bno6bnp) ([raw file](https://github.com/memkind/memkind/blob/e99ee14572207725ccd0db3158bfb8db11009ed6/src/memkind_log.c#L73)):*
> ```C
> 
>     int pid = getpid();
>     char fileName[20];
> ```

Max PID value is around 4 million, please adjust the array length.
___
*[tiering/memtier_log.c, line 15 at r2](https://reviewable.io/reviews/memkind/memkind/696#-MfH7JDeEtkbnBIez43y:-MfH7JDeEtkbnBIez43z:bwjlpbl) ([raw file](https://github.com/memkind/memkind/blob/e99ee14572207725ccd0db3158bfb8db11009ed6/tiering/memtier_log.c#L15)):*
> ```C
> #include <unistd.h>
> #include <string.h>
> #include <sys/stat.h>
> ```

Redundant import.
___
*[tiering/memtier_log.c, line 16 at r2](https://reviewable.io/reviews/memkind/memkind/696#-MfH8GCx6WJY3vnmjZ-3:-MfH8GCx6WJY3vnmjZ-4:bkycap1) ([raw file](https://github.com/memkind/memkind/blob/e99ee14572207725ccd0db3158bfb8db11009ed6/tiering/memtier_log.c#L16)):*
> ```C
> #include <string.h>
> #include <sys/stat.h>
> #include <fcntl.h>
> ```

Alphabetical order, please.


<!-- Sent from Reviewable.io -->

2021-07-27 09:01 UTC, bratpiorka reviewed
> Reviewed 2 of 2 files at r2, 1 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/696)* status: 1 of 3 files reviewed, 12 unresolved discussions (waiting on @bratpiorka, @jacekgrzybek, and @PatKamin)

___
*[src/memkind_log.c, line 74 at r3](https://reviewable.io/reviews/memkind/memkind/696#-MfbBSUR-TA6xVotQbI5:-MfbBSUR-TA6xVotQbI6:bfwfm0r) ([raw file](https://github.com/memkind/memkind/blob/6d529715bb45633b073366b2827f3271a5f03d6f/src/memkind_log.c#L74)):*
> ```C
>     b += len + 1;
> 
> #ifdef LOG_TO_FILE
> ```

please include ALL code that is used only for writing to file into LOG_TO_FILE definition


<!-- Sent from Reviewable.io -->

2021-08-09 11:14 UTC, PatKamin reviewed
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/696)* status: 1 of 3 files reviewed, 14 unresolved discussions (waiting on @bratpiorka, @jacekgrzybek, and @PatKamin)

___
*[configure.ac, line 75 at r4](https://reviewable.io/reviews/memkind/memkind/696#-MgebYq0BpKpMFy_ZdhV:-MgebYq0BpKpMFy_ZdhW:b-rw2n0j) ([raw file](https://github.com/memkind/memkind/blob/742339c2da4fb7fc898be38906dad7a8a9716e3b/configure.ac#L75)):*
> ```M4Sugar
> 
> #============================log_to_file=======================================
> AC_ARG_ENABLE([log_to_file],
> ```

Either `logging_to_file` here or `enable_log_to_file` in other places.
___
*[configure.ac, line 86 at r4](https://reviewable.io/reviews/memkind/memkind/696#-MgebgqJDA2qWxAiRrDZ:-MgebgqJDA2qWxAiRrD_:b-y16ezh) ([raw file](https://github.com/memkind/memkind/blob/742339c2da4fb7fc898be38906dad7a8a9716e3b/configure.ac#L86)):*
> ```M4Sugar
> )
> if test "x${enable_logging_to_file}" = "x1" ; then
>   AC_DEFINE([LOG_TO_FILE], [ ], [Enables log_to_file])
> ```

MEMKIND_LOG_TO_FILE as in other options.


<!-- Sent from Reviewable.io -->

2021-08-11 07:34 UTC, jacekgrzybek commented
> > Reviewed 1 of 2 files at r1.
> > _[Reviewable](https://reviewable.io/reviews/memkind/memkind/696)_ status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @jacekgrzybek)
> 
> _[tiering/memtier_log.c, line 45 at r1](https://reviewable.io/reviews/memkind/memkind/696#-MfCtJX90P6KWxKf8pFf:-MfCtJX90P6KWxKf8pFg:b-xekyf7) ([raw file](https://github.com/memkind/memkind/blob/1d8e55f5eda752661d5c38c1e06d9b56226e8d55/tiering/memtier_log.c#L45)):_
> 
> > ```c
> > 	if(fd == -1){
> > 		close(fd);
> > 		fd = open(fileName, O_CREAT | O_WRONLY, 0600);
> > ```
> 
> Check the return code for errors.
> 
> _[tiering/memtier_log.c, line 64 at r1](https://reviewable.io/reviews/memkind/memkind/696#-MfCtG4f4LIhqb3WC7tw:-MfCtG4g8rVLGfBc4rcV:ba6jeih) ([raw file](https://github.com/memkind/memkind/blob/1d8e55f5eda752661d5c38c1e06d9b56226e8d55/tiering/memtier_log.c#L64)):_
> 
> > ```c
> >     char fileName[20];
> >     sprintf(fileName, "%d", pid);
> >     strncat(fileName, ".log", 4);
> > ```
> 
> Do this in one line, please.

done

2021-08-11 07:45 UTC, jacekgrzybek reviewed
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/696)* status: 0 of 3 files reviewed, 14 unresolved discussions (waiting on @bratpiorka, @jacekgrzybek, and @PatKamin)

___
*[configure.ac, line 75 at r4](https://reviewable.io/reviews/memkind/memkind/696#-MgebYq0BpKpMFy_ZdhV:-Mgo90Jp9hSBF6Z0GgAK:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/742339c2da4fb7fc898be38906dad7a8a9716e3b/configure.ac#L75)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Either `logging_to_file` here or `enable_log_to_file` in other places.
</blockquote></details>

Done.
___
*[configure.ac, line 86 at r4](https://reviewable.io/reviews/memkind/memkind/696#-MgebgqJDA2qWxAiRrDZ:-Mgo93Od27--PUCa9xIc:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/742339c2da4fb7fc898be38906dad7a8a9716e3b/configure.ac#L86)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

MEMKIND_LOG_TO_FILE as in other options.
</blockquote></details>

Done.
___
*[src/memkind_log.c, line 73 at r1](https://reviewable.io/reviews/memkind/memkind/696#-MfCt6tz6Bxu_gIZHBWC:-Mgo9GVP2N-D0JV8h1fD:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/1d8e55f5eda752661d5c38c1e06d9b56226e8d55/src/memkind_log.c#L73)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

please wrap all code related to writing to file with #ifdef. This code should be enabled only with e.g. --enable_logging_to_file (or better name) 
</blockquote></details>

Done.
___
*[src/memkind_log.c, line 16 at r2](https://reviewable.io/reviews/memkind/memkind/696#-MfH8Ki4BqFoDBQhub_l:-Mgo9A5S36Iss7zXysfS:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/e99ee14572207725ccd0db3158bfb8db11009ed6/src/memkind_log.c#L16)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Alphabetical order, please.
</blockquote></details>

Done.
___
*[src/memkind_log.c, line 55 at r2](https://reviewable.io/reviews/memkind/memkind/696#-MfH58bJ2rDZWSTMihga:-Mgo9C65Bz3ZNl-xq1qP:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/e99ee14572207725ccd0db3158bfb8db11009ed6/src/memkind_log.c#L55)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

If it fails, do not try to write to fd.
</blockquote></details>

Done.
___
*[src/memkind_log.c, line 73 at r2](https://reviewable.io/reviews/memkind/memkind/696#-MfH6xvH2MegsuK4DsQz:-Mgo9HHREJ1wNwOMnsXU:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/e99ee14572207725ccd0db3158bfb8db11009ed6/src/memkind_log.c#L73)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Max PID value is around 4 million, please adjust the array length.
</blockquote></details>

Done.
___
*[src/memkind_log.c, line 74 at r3](https://reviewable.io/reviews/memkind/memkind/696#-MfbBSUR-TA6xVotQbI5:-Mgo9G-a-8QrufxV1769:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/6d529715bb45633b073366b2827f3271a5f03d6f/src/memkind_log.c#L74)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

please include ALL code that is used only for writing to file into LOG_TO_FILE definition
</blockquote></details>

Done.
___
*[tiering/memtier_log.c, line 64 at r1](https://reviewable.io/reviews/memkind/memkind/696#-MfCtG4f4LIhqb3WC7tw:-Mgo9bC9-QGjkbMtJuck:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/1d8e55f5eda752661d5c38c1e06d9b56226e8d55/tiering/memtier_log.c#L64)):*
<details><summary><i>Previously, jacekgrzybek (Jacek Grzybek) wrote…</i></summary><blockquote>

done
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-08-11 08:21 UTC, PatKamin reviewed
> Reviewed 3 of 3 files at r5.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/696)* status: all files reviewed, 12 unresolved discussions (waiting on @bratpiorka and @jacekgrzybek)

___
*[configure.ac, line 76 at r5](https://reviewable.io/reviews/memkind/memkind/696#-MgoANydAbqFnCAqk04v:-MgoANyg8UAC_Vi0sz5t:bkhj2c6) ([raw file](https://github.com/memkind/memkind/blob/98167259f1efb8f47471214a5f496da8a70b203f/configure.ac#L76)):*
> ```
> [Enable logging_to_file]
> ```
It's a description, so underscores are unwelcome here. More informative description, please. Same below.
___
*[configure.ac, line 107 at r5](https://reviewable.io/reviews/memkind/memkind/696#-Mgo6tO3CJwLXicfU6F7:-Mgo6tO3CJwLXicfU6F8:b-ybe39g) ([raw file](https://github.com/memkind/memkind/blob/98167259f1efb8f47471214a5f496da8a70b203f/configure.ac#L107)):*
> ```M4Sugar
> fi
> AC_SUBST([enable_debug])
> ```

Remove this empty line.
___
*[src/memkind_log.c, line 55 at r2](https://reviewable.io/reviews/memkind/memkind/696#-MfH58bJ2rDZWSTMihga:-MgoCkn67V8sA5rkmdeE:b-f6njb9) ([raw file](https://github.com/memkind/memkind/blob/e99ee14572207725ccd0db3158bfb8db11009ed6/src/memkind_log.c#L55)):*
<details><summary><i>Previously, jacekgrzybek (Jacek Grzybek) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

It's not done.
___
*[src/memkind_log.c, line 73 at r2](https://reviewable.io/reviews/memkind/memkind/696#-MfH6xvH2MegsuK4DsQz:-MgoHuSj6bYe94Ji6O0P:b-l47p5h) ([raw file](https://github.com/memkind/memkind/blob/e99ee14572207725ccd0db3158bfb8db11009ed6/src/memkind_log.c#L73)):*
<details><summary><i>Previously, jacekgrzybek (Jacek Grzybek) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Even less bytes would suffice.


<!-- Sent from Reviewable.io -->

2021-08-11 10:34 UTC, bratpiorka reviewed
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/696)* status: all files reviewed, 12 unresolved discussions (waiting on @jacekgrzybek)

___
*[src/memkind_log.c, line 54 at r3](https://reviewable.io/reviews/memkind/memkind/696#-MgisUnmB3xRdE-jnJWP:-MgisUnmB3xRdE-jnJWQ:b-lnmk14) ([raw file](https://github.com/memkind/memkind/blob/6d529715bb45633b073366b2827f3271a5f03d6f/src/memkind_log.c#L54)):*
> ```C
> static void save_log_to_file(char *log, char *fileName)
> {
> 	int fd = open(fileName, O_WRONLY | O_APPEND);
> ```

please don't use TABs
___
*[src/memkind_log.c, line 74 at r3](https://reviewable.io/reviews/memkind/memkind/696#-MfbBSUR-TA6xVotQbI5:-Mgol_Pk9lAVz8kMYZqs:b-27ht1h) ([raw file](https://github.com/memkind/memkind/blob/6d529715bb45633b073366b2827f3271a5f03d6f/src/memkind_log.c#L74)):*
<details><summary><i>Previously, jacekgrzybek (Jacek Grzybek) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

what about operations done on "b" variable above?


<!-- Sent from Reviewable.io -->

2021-08-11 10:54 UTC, PatKamin reviewed
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/696)* status: all files reviewed, 13 unresolved discussions (waiting on @jacekgrzybek)

___
*[tiering/memtier_log.c, line 51 at r5](https://reviewable.io/reviews/memkind/memkind/696#-Mgoq6Hw5-jzStaxLx5t:-Mgoq6Hx9Ris3cS4ZKxd:b-jgrc9w) ([raw file](https://github.com/memkind/memkind/blob/4dd5012ba46af0cd4420af211ed113de8715a366/tiering/memtier_log.c#L51)):*
> ```C
>         assert(0 && "failed to acquire log mutex");
>     }
> ```

Restore this empty line.


<!-- Sent from Reviewable.io -->

2021-08-11 10:58 UTC, PatKamin reviewed
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/696)* status: all files reviewed, 14 unresolved discussions (waiting on @jacekgrzybek)

___
*[src/memkind_log.c, line 56 at r5](https://reviewable.io/reviews/memkind/memkind/696#-MgoqJCE5ePELttm8xmc:-MgoqJCE5ePELttm8xmd:bwp3mf9) ([raw file](https://github.com/memkind/memkind/blob/98167259f1efb8f47471214a5f496da8a70b203f/src/memkind_log.c#L56)):*
> ```C
> 	int fd = open(fileName, O_WRONLY | O_APPEND);
> 	if (fd == -1){
>         int nd = open(fileName, O_CREAT | O_WRONLY, 0600);
> ```

Currently `nd` is detected in Codespell as a misspell. You can reuse `fd` here. This way the code will be easier to read plus the Codespell check will be successful.


<!-- Sent from Reviewable.io -->

2021-08-12 09:00 UTC, PatKamin reviewed
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/696)* status: 1 of 3 files reviewed, 16 unresolved discussions (waiting on @jacekgrzybek and @PatKamin)

___
*[src/memkind_log.c, line 55 at r8](https://reviewable.io/reviews/memkind/memkind/696#-MgtXwqU1aDIidgy5V15:-MgtXwqU1aDIidgy5V16:b-ujn6a6) ([raw file](https://github.com/memkind/memkind/blob/ff1441b9212c9d9d6f22d82b1b71d230f991bf8d/src/memkind_log.c#L55)):*
> ```C
> {
>     int fd = open(fileName, O_WRONLY | O_APPEND);
>     if (fd == -1) {
> ```

Please, check also which errno is assigned when the file doesn't exist. I see that's the only reason why you're trying to create the file after the first attempt of appending it fails.
___
*[src/memkind_log.c, line 57 at r8](https://reviewable.io/reviews/memkind/memkind/696#-Mgt_nQn6P-ViQ0v6BCF:-Mgt_nQo87MorHRx79sP:b-u40pvo) ([raw file](https://github.com/memkind/memkind/blob/ff1441b9212c9d9d6f22d82b1b71d230f991bf8d/src/memkind_log.c#L57)):*
> ```C
>     if (fd == -1) {
>         int new_fd = open(fileName, O_CREAT | O_WRONLY, 0600);
>         if (new_fd != -1) {
> ```

Print an error message that writing to file failed if fd == -1.


<!-- Sent from Reviewable.io -->

2021-08-24 14:36 UTC, bratpiorka reviewed
> Reviewed 3 of 3 files at r9.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/696)* status: all files reviewed, 13 unresolved discussions (waiting on @jacekgrzybek)

___
*[src/memkind_log.c, line 75 at r9](https://reviewable.io/reviews/memkind/memkind/696#-Mhs_NoeCsMoj7304FVK:-Mhs_NoeCsMoj7304FVL:b-b49uv4) ([raw file](https://github.com/memkind/memkind/blob/bcbb0b91e86a43223f3fa4858ee9cdb1ceef76d0/src/memkind_log.c#L75)):*
> ```C
> 
>     static char buf[4096];
>     sprintf(buf, "%s: ", message_prefixes[type]);
> ```

definition of buf and sprintf() should be moved below to "#ifdef MEMKIND_LOG_TO_FILE" section


<!-- Sent from Reviewable.io -->

2021-09-02 11:52 UTC, jacekgrzybek reviewed
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/696)* status: 1 of 3 files reviewed, 13 unresolved discussions (waiting on @bratpiorka, @jacekgrzybek, and @PatKamin)

___
*[configure.ac, line 107 at r5](https://reviewable.io/reviews/memkind/memkind/696#-Mgo6tO3CJwLXicfU6F7:-MiaH4q4-ZbHC9Z5lofG:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/98167259f1efb8f47471214a5f496da8a70b203f/configure.ac#L107)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Remove this empty line.
</blockquote></details>

Done.
___
*[src/memkind_log.c, line 66 at r1](https://reviewable.io/reviews/memkind/memkind/696#-MfCsiaS-uMhhgcw2Vbm:-MiaHL6W7RONK346AYMT:b-av1u4y) ([raw file](https://github.com/memkind/memkind/blob/1d8e55f5eda752661d5c38c1e06d9b56226e8d55/src/memkind_log.c#L66)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

"b" is not used in this function.. it looks like this is a copy of code from memtier_log.c, where this var is used to handle message overflow case. Please add handling overflow here or remove this variable
</blockquote></details>

b is used int this function to for example make new line in log
___
*[src/memkind_log.c, line 14 at r2](https://reviewable.io/reviews/memkind/memkind/696#-MfH1SXF-BOhn899TAZ2:-MiaH6ji8FCawgIyWA5Q:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/e99ee14572207725ccd0db3158bfb8db11009ed6/src/memkind_log.c#L14)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Redundant import.
</blockquote></details>

Done.
___
*[src/memkind_log.c, line 55 at r2](https://reviewable.io/reviews/memkind/memkind/696#-MfH58bJ2rDZWSTMihga:-MiaHGB35sLiH6TvTuCi:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/e99ee14572207725ccd0db3158bfb8db11009ed6/src/memkind_log.c#L55)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

It's not done.
</blockquote></details>

Done.
___
*[src/memkind_log.c, line 56 at r5](https://reviewable.io/reviews/memkind/memkind/696#-MgoqJCE5ePELttm8xmc:-MiaHIpe1y9w64a3fsIx:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/98167259f1efb8f47471214a5f496da8a70b203f/src/memkind_log.c#L56)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Currently `nd` is detected in Codespell as a misspell. You can reuse `fd` here. This way the code will be easier to read plus the Codespell check will be successful.
</blockquote></details>

Done.
___
*[src/memkind_log.c, line 57 at r8](https://reviewable.io/reviews/memkind/memkind/696#-Mgt_nQn6P-ViQ0v6BCF:-MiaHKNMB_okJ_-OrRlO:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/ff1441b9212c9d9d6f22d82b1b71d230f991bf8d/src/memkind_log.c#L57)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Print an error message that writing to file failed if fd == -1.
</blockquote></details>

Done.
___
*[src/memkind_log.c, line 75 at r9](https://reviewable.io/reviews/memkind/memkind/696#-Mhs_NoeCsMoj7304FVK:-MiaLLNH44MEk1ZJHB7E:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/bcbb0b91e86a43223f3fa4858ee9cdb1ceef76d0/src/memkind_log.c#L75)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

definition of buf and sprintf() should be moved below to "#ifdef MEMKIND_LOG_TO_FILE" section
</blockquote></details>

Done.
___
*[tiering/memtier_log.c, line 45 at r1](https://reviewable.io/reviews/memkind/memkind/696#-MfCtJX90P6KWxKf8pFf:-MiaLSUm6eVw6D5caAwz:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/1d8e55f5eda752661d5c38c1e06d9b56226e8d55/tiering/memtier_log.c#L45)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Check the return code for errors.
</blockquote></details>

Done.
___
*[tiering/memtier_log.c, line 15 at r2](https://reviewable.io/reviews/memkind/memkind/696#-MfH7JDeEtkbnBIez43y:-MiaLQp343HkNt2objbZ:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/e99ee14572207725ccd0db3158bfb8db11009ed6/tiering/memtier_log.c#L15)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Redundant import.
</blockquote></details>

Done.
___
*[tiering/memtier_log.c, line 16 at r2](https://reviewable.io/reviews/memkind/memkind/696#-MfH8GCx6WJY3vnmjZ-3:-MiaLR5h6V4qhDtj-Fbt:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/e99ee14572207725ccd0db3158bfb8db11009ed6/tiering/memtier_log.c#L16)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Alphabetical order, please.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-09-03 08:33 UTC, bratpiorka reviewed
> Reviewed 1 of 1 files at r10, 2 of 2 files at r11.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/696)* status: all files reviewed, 12 unresolved discussions (waiting on @jacekgrzybek and @PatKamin)



<!-- Sent from Reviewable.io -->

2021-09-06 09:09 UTC, bratpiorka approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/696#-:-MiuMUfF986q5laKV2Sm:bnfp4nl)* status: all files reviewed, 12 unresolved discussions (waiting on @jacekgrzybek and @PatKamin)



<!-- Sent from Reviewable.io -->

2021-09-06 10:03 UTC, PatKamin requested changes
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/696)* status: all files reviewed, 10 unresolved discussions (waiting on @jacekgrzybek and @PatKamin)

___
*[src/memkind_log.c, line 56 at r5](https://reviewable.io/reviews/memkind/memkind/696#-MgoqJCE5ePELttm8xmc:-MiuAAsQ6vHYz-W5yu2k:b-vfbyzk) ([raw file](https://github.com/memkind/memkind/blob/98167259f1efb8f47471214a5f496da8a70b203f/src/memkind_log.c#L56)):*
<details><summary><i>Previously, jacekgrzybek (Jacek Grzybek) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Please, reuse `fd` instead of creating `new_fd`.
___
*[tiering/memtier_log.c, line 47 at r11](https://reviewable.io/reviews/memkind/memkind/696#-MiuDRTj9EK39WxoIyXZ:-MiuDRTj9EK39WxoIyX_:bcvg4x0) ([raw file](https://github.com/memkind/memkind/blob/8281bbe0ad09608f226a161917e2dc9131eabc30/tiering/memtier_log.c#L47)):*
> ```C
>         int new_fd = open(fileName, O_CREAT | O_WRONLY, 0600);
>         if (new_fd == -1) {
>             fprintf(stderr, "MEMKIND_ERROR: cannot open file to save log\n");
> ```

Use swrite() or sth similar.


<!-- Sent from Reviewable.io -->

2021-09-07 10:33 UTC, bratpiorka approved these changes
> Reviewed 2 of 2 files at r12.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/696)* status: all files reviewed, 10 unresolved discussions (waiting on @jacekgrzybek and @PatKamin)



<!-- Sent from Reviewable.io -->

2021-09-08 09:09 UTC, jacekgrzybek reviewed
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/696)* status: all files reviewed, 10 unresolved discussions (waiting on @jacekgrzybek and @PatKamin)

___
*[src/memkind_log.c, line 56 at r5](https://reviewable.io/reviews/memkind/memkind/696#-MgoqJCE5ePELttm8xmc:-Mj3ePkU-bJvJ0NxZADF:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/98167259f1efb8f47471214a5f496da8a70b203f/src/memkind_log.c#L56)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Please, reuse `fd` instead of creating `new_fd`.
</blockquote></details>

Done.
___
*[src/memkind_log.c, line 55 at r8](https://reviewable.io/reviews/memkind/memkind/696#-MgtXwqU1aDIidgy5V15:-Mj3eOcT-4JEdcn0fBWL:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/ff1441b9212c9d9d6f22d82b1b71d230f991bf8d/src/memkind_log.c#L55)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Please, check also which errno is assigned when the file doesn't exist. I see that's the only reason why you're trying to create the file after the first attempt of appending it fails.
</blockquote></details>

Done.
___
*[tiering/memtier_log.c, line 51 at r5](https://reviewable.io/reviews/memkind/memkind/696#-Mgoq6Hw5-jzStaxLx5t:-Mj3eWRr6GGuoR9at_nL:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/4dd5012ba46af0cd4420af211ed113de8715a366/tiering/memtier_log.c#L51)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Restore this empty line.
</blockquote></details>

Done.
___
*[tiering/memtier_log.c, line 47 at r11](https://reviewable.io/reviews/memkind/memkind/696#-MiuDRTj9EK39WxoIyXZ:-Mj3eVZc6wBgqWDFFm9R:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/8281bbe0ad09608f226a161917e2dc9131eabc30/tiering/memtier_log.c#L47)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Use swrite() or sth similar.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-09-08 10:05 UTC, PatKamin requested changes
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/696)* status: all files reviewed, 6 unresolved discussions (waiting on @jacekgrzybek and @PatKamin)

___
*[src/memkind_log.c, line 80 at r12](https://reviewable.io/reviews/memkind/memkind/696#-Mj3pw6-DzNv-dKaIyOS:-Mj3pw60Dj57kaU24vbO:bqwsz9h) ([raw file](https://github.com/memkind/memkind/blob/740864f5dc8f11a6739ec6e6e8552fcccb8e7b1c/src/memkind_log.c#L80)):*
> ```C
> 
> static pthread_mutex_t log_lock = PTHREAD_MUTEX_INITIALIZER;
> void log_generic(message_type_t type, const char *format, va_list args)
> ```

Restore `static`.
___
*[tiering/memtier_log.c, line 43 at r12](https://reviewable.io/reviews/memkind/memkind/696#-Mj3q9FI9mmZqgm3uXmv:-Mj3q9FI9mmZqgm3uXmw:bxma8on) ([raw file](https://github.com/memkind/memkind/blob/740864f5dc8f11a6739ec6e6e8552fcccb8e7b1c/tiering/memtier_log.c#L43)):*
> ```C
> static void save_log_to_file(char *log, char *fileName)
> {
>     int fd = open(fileName, O_WRONLY | O_APPEND);
> ```

Merge this to: `int fd = open(fileName, O_WRONLY | O_APPEND | O_CREAT, 0600);`
___
*[tiering/memtier_log.c, line 56 at r12](https://reviewable.io/reviews/memkind/memkind/696#-Mj3qg5ZANOPWQXgqAYE:-Mj3qg5_Blb6VJNIxTB8:bluhg1) ([raw file](https://github.com/memkind/memkind/blob/740864f5dc8f11a6739ec6e6e8552fcccb8e7b1c/tiering/memtier_log.c#L56)):*
<details><summary><i alt="summary">Quoted 11 lines of code…</i></summary>

> ```
>         if (fd == -1) {
>             const char error_msg[] = "Error: cannot open file to save log.\n";
>             swrite(STDERR_FILENO, error_msg, sizeof(error_msg));
>         } else {
>             (void)!write(fd, log, strlen(log));
>             close(fd);
>         }
>     } else {
>         (void)!write(fd, log, strlen(log));
>         close(fd);
>     }
> ```
</details>


More concise:
```
         if (fd == -1) {
                ...
                return;
         }
         (void)!write(fd, log, strlen(log));
         close(fd);
```


<!-- Sent from Reviewable.io -->

2021-09-08 10:33 UTC, bratpiorka reviewed
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/696)* status: all files reviewed, 6 unresolved discussions (waiting on @jacekgrzybek and @PatKamin)

___
*[tiering/memtier_log.c, line 56 at r12](https://reviewable.io/reviews/memkind/memkind/696#-Mj3qg5ZANOPWQXgqAYE:-Mj3y2CGAagkGerZeu0x:b32v57) ([raw file](https://github.com/memkind/memkind/blob/740864f5dc8f11a6739ec6e6e8552fcccb8e7b1c/tiering/memtier_log.c#L56)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

> ```
>         if (fd == -1) {
>             const char error_msg[] = "Error: cannot open file to save log.\n";
>             swrite(STDERR_FILENO, error_msg, sizeof(error_msg));
>         } else {
>             (void)!write(fd, log, strlen(log));
>             close(fd);
>         }
>     } else {
>         (void)!write(fd, log, strlen(log));
>         close(fd);
>     }
> ```

More concise:
```
         if (fd == -1) {
                ...
                return;
         }
         (void)!write(fd, log, strlen(log));
         close(fd);
```

</blockquote></details>

+1


<!-- Sent from Reviewable.io -->

2021-09-08 10:55 UTC, bratpiorka requested changes
> Reviewed 2 of 2 files at r13.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/696)* status: all files reviewed, 8 unresolved discussions (waiting on @jacekgrzybek and @PatKamin)

___
*[src/memkind_log.c, line 67 at r13](https://reviewable.io/reviews/memkind/memkind/696#-Mj41rv71lqjkWaI1m-L:-Mj41rv71lqjkWaI1m-M:b-jnwqxj) ([raw file](https://github.com/memkind/memkind/blob/820f06303678c8bec8485911f31e8a6819ff15a8/src/memkind_log.c#L67)):*
> ```C
>         if (fd == -1) {
>             char error_msg[50];
>             sprintf(error_msg, "Error: Can't open file %s to save log",
> ```

please use snprintf(error_msg, sizeof(error_msg) ...
___
*[tiering/memtier_log.c, line 49 at r13](https://reviewable.io/reviews/memkind/memkind/696#-Mj422KG7JBtiun50lD_:-Mj422KG7JBtiun50lDa:b-jnwqxj) ([raw file](https://github.com/memkind/memkind/blob/820f06303678c8bec8485911f31e8a6819ff15a8/tiering/memtier_log.c#L49)):*
> ```C
>         if (fd == -1) {
>             char error_msg[50];
>             sprintf(error_msg, "Error: Can't open file %s to save log",
> ```

please use snprintf(error_msg, sizeof(error_msg) ...


<!-- Sent from Reviewable.io -->

2021-09-08 11:02 UTC, jacekgrzybek reviewed
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/696)* status: 1 of 3 files reviewed, 8 unresolved discussions (waiting on @bratpiorka, @jacekgrzybek, and @PatKamin)

___
*[tiering/memtier_log.c, line 56 at r12](https://reviewable.io/reviews/memkind/memkind/696#-Mj3qg5ZANOPWQXgqAYE:-Mj43gKj2QH8qaOKUqUi:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/740864f5dc8f11a6739ec6e6e8552fcccb8e7b1c/tiering/memtier_log.c#L56)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

+1
</blockquote></details>

Done.
___
*[tiering/memtier_log.c, line 49 at r13](https://reviewable.io/reviews/memkind/memkind/696#-Mj422KG7JBtiun50lD_:-Mj43gqp3UHdl3Vmai6R:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/820f06303678c8bec8485911f31e8a6819ff15a8/tiering/memtier_log.c#L49)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

please use snprintf(error_msg, sizeof(error_msg) ...
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-09-08 11:04 UTC, bratpiorka approved these changes
> Reviewed 2 of 2 files at r14.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/696)* status: all files reviewed, 6 unresolved discussions (waiting on @jacekgrzybek and @PatKamin)



<!-- Sent from Reviewable.io -->

2021-09-08 11:15 UTC, PatKamin requested changes
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/696)* status: all files reviewed, 9 unresolved discussions (waiting on @jacekgrzybek and @PatKamin)

___
*[src/memkind_log.c, line 100 at r12](https://reviewable.io/reviews/memkind/memkind/696#-Mj45OPW20rjcSik_xRy:-Mj45OPW20rjcSik_xRz:b-ofntbv) ([raw file](https://github.com/memkind/memkind/blob/740864f5dc8f11a6739ec6e6e8552fcccb8e7b1c/src/memkind_log.c#L100)):*
> ```C
>             assert(0 && "failed to acquire mutex");
> #ifdef MEMKIND_LOG_TO_FILE
>         save_log_to_file(buf, fileName);
> ```

You can pass `b - buf` to this function, so you won't have to use strlen().
___
*[src/memkind_log.c, line 100 at r12](https://reviewable.io/reviews/memkind/memkind/696#-Mj46-um-QWQF7QnhBqr:-Mj46-um-QWQF7QnhBqs:b1podok) ([raw file](https://github.com/memkind/memkind/blob/740864f5dc8f11a6739ec6e6e8552fcccb8e7b1c/src/memkind_log.c#L100)):*
> ```C
>             assert(0 && "failed to acquire mutex");
> #ifdef MEMKIND_LOG_TO_FILE
>         save_log_to_file(buf, fileName);
> ```

What if the msg doesn't fit into the buf? See here: https://github.com/memkind/memkind/blob/master/tiering/memtier_log.c#L52-L54
___
*[tiering/memtier_log.c, line 13 at r12](https://reviewable.io/reviews/memkind/memkind/696#-Mj4-NegDzQw_f_IqBHw:-Mj4-NegDzQw_f_IqBHx:b-s3hmk9) ([raw file](https://github.com/memkind/memkind/blob/740864f5dc8f11a6739ec6e6e8552fcccb8e7b1c/tiering/memtier_log.c#L13)):*
> ```C
> #include <stdarg.h>
> #include <stdlib.h>
> #include <string.h>
> ```

Not needed.


<!-- Sent from Reviewable.io -->

2021-09-08 13:48 UTC, PatKamin requested changes
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/696)* status: 1 of 3 files reviewed, 10 unresolved discussions (waiting on @bratpiorka, @jacekgrzybek, and @PatKamin)

___
*[src/memkind_log.c, line 104 at r12](https://reviewable.io/reviews/memkind/memkind/696#-Mj4eM6sBXlGlYUZXzcp:-Mj4eM6sBXlGlYUZXzcq:bd372ye) ([raw file](https://github.com/memkind/memkind/blob/740864f5dc8f11a6739ec6e6e8552fcccb8e7b1c/src/memkind_log.c#L104)):*
> ```
>         fprintf(stderr, "%s: ", message_prefixes[type]);
>         vfprintf(stderr, format, args);
>         fprintf(stderr, "\n");
> ```
Put this in the #ifndef MEMKIND_LOG_TO_FILE block to avoid printing rubbish to stdout.


<!-- Sent from Reviewable.io -->

2021-09-08 13:49 UTC, PatKamin requested changes
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/696)* status: 1 of 3 files reviewed, 10 unresolved discussions (waiting on @bratpiorka, @jacekgrzybek, and @PatKamin)

___
*[src/memkind_log.c, line 104 at r12](https://reviewable.io/reviews/memkind/memkind/696#-Mj4eM6sBXlGlYUZXzcp:-Mj4eeTK4nCylf898hFj:bfz5taw) ([raw file](https://github.com/memkind/memkind/blob/740864f5dc8f11a6739ec6e6e8552fcccb8e7b1c/src/memkind_log.c#L104)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

> ```
>         fprintf(stderr, "%s: ", message_prefixes[type]);
>         vfprintf(stderr, format, args);
>         fprintf(stderr, "\n");
> ```
Put this in the #ifndef MEMKIND_LOG_TO_FILE block to avoid printing rubbish to stdout.
</blockquote></details>

... or just simply use #else :)


<!-- Sent from Reviewable.io -->

2021-09-13 08:33 UTC, jacekgrzybek reviewed
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/696)* status: 1 of 3 files reviewed, 7 unresolved discussions (waiting on @bratpiorka, @jacekgrzybek, and @PatKamin)

___
*[src/memkind_log.c, line 104 at r12](https://reviewable.io/reviews/memkind/memkind/696#-Mj4eM6sBXlGlYUZXzcp:-MjTHX2hDeyMyTIiKzGn:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/740864f5dc8f11a6739ec6e6e8552fcccb8e7b1c/src/memkind_log.c#L104)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

... or just simply use #else :)
</blockquote></details>

Done.
___
*[tiering/memtier_log.c, line 43 at r12](https://reviewable.io/reviews/memkind/memkind/696#-Mj3q9FI9mmZqgm3uXmv:-Mj47UBH6srq9JWnmrHj:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/740864f5dc8f11a6739ec6e6e8552fcccb8e7b1c/tiering/memtier_log.c#L43)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Merge this to: `int fd = open(fileName, O_WRONLY | O_APPEND | O_CREAT, 0600);`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-09-13 08:53 UTC, PatKamin reviewed
> Reviewed 2 of 2 files at r17.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/696)* status: all files reviewed, 6 unresolved discussions (waiting on @jacekgrzybek)



<!-- Sent from Reviewable.io -->

2021-09-14 11:46 UTC, jacekgrzybek reviewed
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/696)* status: 0 of 3 files reviewed, 6 unresolved discussions (waiting on @bratpiorka, @jacekgrzybek, and @PatKamin)

___
*[src/memkind_log.c, line 73 at r2](https://reviewable.io/reviews/memkind/memkind/696#-MfH6xvH2MegsuK4DsQz:-MjZ1eXrE5MRdeB45E3e:b-meggqa) ([raw file](https://github.com/memkind/memkind/blob/e99ee14572207725ccd0db3158bfb8db11009ed6/src/memkind_log.c#L73)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Even less bytes would suffice.
</blockquote></details>

if pid for example is 1 million it gets 11 characters with suffix ".log"
___
*[src/memkind_log.c, line 100 at r12](https://reviewable.io/reviews/memkind/memkind/696#-Mj45OPW20rjcSik_xRy:-MjZ27rq-2v7uDafBtla:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/740864f5dc8f11a6739ec6e6e8552fcccb8e7b1c/src/memkind_log.c#L100)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

You can pass `b - buf` to this function, so you won't have to use strlen().
</blockquote></details>

Done.
___
*[src/memkind_log.c, line 67 at r13](https://reviewable.io/reviews/memkind/memkind/696#-Mj41rv71lqjkWaI1m-L:-MjZ1B2s-BhrWh47rVRp:bbkonj3) ([raw file](https://github.com/memkind/memkind/blob/820f06303678c8bec8485911f31e8a6819ff15a8/src/memkind_log.c#L67)):*
> b - bu


<!-- Sent from Reviewable.io -->

2021-09-14 12:45 UTC, jacekgrzybek reviewed
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/696)* status: 0 of 3 files reviewed, 6 unresolved discussions (waiting on @bratpiorka, @jacekgrzybek, and @PatKamin)

___
*[src/memkind_log.c, line 80 at r12](https://reviewable.io/reviews/memkind/memkind/696#-Mj3pw6-DzNv-dKaIyOS:-MjZKm24Da9uRTNDR6Cu:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/740864f5dc8f11a6739ec6e6e8552fcccb8e7b1c/src/memkind_log.c#L80)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Restore `static`.
</blockquote></details>

Done.
___
*[src/memkind_log.c, line 100 at r12](https://reviewable.io/reviews/memkind/memkind/696#-Mj46-um-QWQF7QnhBqr:-MjZKiXQ8zS-n_lCozzo:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/740864f5dc8f11a6739ec6e6e8552fcccb8e7b1c/src/memkind_log.c#L100)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

What if the msg doesn't fit into the buf? See here: https://github.com/memkind/memkind/blob/master/tiering/memtier_log.c#L52-L54
</blockquote></details>

Done.
___
*[tiering/memtier_log.c, line 13 at r12](https://reviewable.io/reviews/memkind/memkind/696#-Mj4-NegDzQw_f_IqBHw:-MjZKk6V6Z9PJLoBJxpy:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/740864f5dc8f11a6739ec6e6e8552fcccb8e7b1c/tiering/memtier_log.c#L13)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Not needed.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-09-15 09:23 UTC, jacekgrzybek reviewed
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/696)* status: 0 of 3 files reviewed, 5 unresolved discussions (waiting on @jacekgrzybek and @PatKamin)

___
*[src/memkind_log.c, line 73 at r2](https://reviewable.io/reviews/memkind/memkind/696#-MfH6xvH2MegsuK4DsQz:-Mjcl5cQ6cPHBDw_mCoK:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/e99ee14572207725ccd0db3158bfb8db11009ed6/src/memkind_log.c#L73)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Right, make it 12 then, so the NULL character will fit in.
</blockquote></details>

Done.
___
*[src/memkind_log.c, line 100 at r20](https://reviewable.io/reviews/memkind/memkind/696#-MjZRtmK1B5hct3jOleL:-Mjcl2bqBLO0LT56luqh:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/b2ae09657d6ff6aff1d762a0a5f025122f8031c5/src/memkind_log.c#L100)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Write it to the file.
</blockquote></details>

Done.
___
*[tiering/memtier_log.c, line 13 at r12](https://reviewable.io/reviews/memkind/memkind/696#-Mj4-NegDzQw_f_IqBHw:-Mjcl1Bw-wIZakM84ZdE:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/740864f5dc8f11a6739ec6e6e8552fcccb8e7b1c/tiering/memtier_log.c#L13)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Remove `string.h` include.
</blockquote></details>

Done.
___
*[tiering/memtier_log.c, line 82 at r21](https://reviewable.io/reviews/memkind/memkind/696#-MjZUFZ_-E2iUhWF3jAh:-Mjcl-oK2y0APC5YCdIA:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/95d2628ce44616b60fed890262a6e748a0b3176b/tiering/memtier_log.c#L82)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Log this message to file, too (when logging to file is enabled).
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-09-15 10:28 UTC, PatKamin requested changes
> Reviewed 1 of 1 files at r22, 2 of 2 files at r25.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/696)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @jacekgrzybek and @PatKamin)

___
*[src/memkind_log.c, line 100 at r20](https://reviewable.io/reviews/memkind/memkind/696#-MjZRtmK1B5hct3jOleL:-MjcwusN5pfHLHMv27nk:b-9r8zyk) ([raw file](https://github.com/memkind/memkind/blob/b2ae09657d6ff6aff1d762a0a5f025122f8031c5/src/memkind_log.c#L100)):*
<details><summary><i>Previously, jacekgrzybek (Jacek Grzybek) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Write it to stdout when logging to file is disabled. Don't write it to stdout when logging to file is enabled.


<!-- Sent from Reviewable.io -->

2021-09-15 10:51 UTC, PatKamin requested changes
> Reviewed 1 of 1 files at r27.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/696)* status: all files reviewed, 2 unresolved discussions (waiting on @jacekgrzybek)

___
*[src/memkind_log.c, line 102 at r27](https://reviewable.io/reviews/memkind/memkind/696#-Mjd2TgG4xXZRp4rluzC:-Mjd2TgHCg8rDHMXH57W:b8jq8ps) ([raw file](https://github.com/memkind/memkind/blob/c1e0118cea396db4db0b09e738b49e75414c19d1/src/memkind_log.c#L102)):*
> ```C
>         save_log_to_file(buf, fileName, b - buf);
> #else
>         char overflow_msg[] = "Warning: message truncated.\n";
> ```

Move this outside `#ifdef`.


<!-- Sent from Reviewable.io -->

2021-09-16 07:33 UTC, jacekgrzybek reviewed
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/696)* status: 1 of 3 files reviewed, 2 unresolved discussions (waiting on @PatKamin)

___
*[src/memkind_log.c, line 100 at r20](https://reviewable.io/reviews/memkind/memkind/696#-MjZRtmK1B5hct3jOleL:-MjhWSlG4vemppqpWfCt:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/b2ae09657d6ff6aff1d762a0a5f025122f8031c5/src/memkind_log.c#L100)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Write it to stdout when logging to file is disabled. Don't write it to stdout when logging to file is enabled.
</blockquote></details>

Done.
___
*[src/memkind_log.c, line 102 at r27](https://reviewable.io/reviews/memkind/memkind/696#-Mjd2TgG4xXZRp4rluzC:-MjhWQh50TtifPjLAZwE:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/c1e0118cea396db4db0b09e738b49e75414c19d1/src/memkind_log.c#L102)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Move this outside `#ifdef`.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-09-16 08:15 UTC, PatKamin requested changes
Please, add a note in a README that such an option exists.

> Reviewed 2 of 2 files at r29.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/696#-:-Mjheunt5P79BQU2irSg:b-7nivsb)* status: all files reviewed, 2 unresolved discussions (waiting on @jacekgrzybek)

___
*[src/memkind_log.c, line 103 at r29](https://reviewable.io/reviews/memkind/memkind/696#-MjhXACKAN7xTNGoeAqe:-MjhXACKAN7xTNGoeAqf:b739nbb) ([raw file](https://github.com/memkind/memkind/blob/49c84a91f0c0c858dc925718d4ec695fdc8ae8df/src/memkind_log.c#L103)):*
> ```C
>         if (len >= blen)
>             swrite(STDERR_FILENO, overflow_msg, sizeof(overflow_msg));
> ```

nit: Remove this empty line.
___
*[tiering/memtier_log.c, line 89 at r29](https://reviewable.io/reviews/memkind/memkind/696#-MjheeVUAInOd2TPUB7c:-MjheeVUAInOd2TPUB7d:b-9icf2p) ([raw file](https://github.com/memkind/memkind/blob/49c84a91f0c0c858dc925718d4ec695fdc8ae8df/tiering/memtier_log.c#L89)):*
<details><summary><i alt="summary">Quoted 11 lines of code…</i></summary>

> ```
> #ifdef MEMKIND_LOG_TO_FILE
>         save_log_to_file(overflow_msg, fileName, sizeof(overflow_msg));
> #else
>         swrite(STDERR_FILENO, overflow_msg, sizeof(overflow_msg));
> #endif
>     }
> #ifdef MEMKIND_LOG_TO_FILE
>     save_log_to_file(buf, fileName, b - buf);
> #else
>     swrite(STDERR_FILENO, buf, b - buf);
> #endif
> ```
</details>

Please, make it one `#ifdef` (like it's in memkind_log), it would be easier to read.


<!-- Sent from Reviewable.io -->

2021-09-17 09:35 UTC, PatKamin requested changes
> Reviewed 1 of 2 files at r32.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/696)* status: 2 of 4 files reviewed, 4 unresolved discussions (waiting on @jacekgrzybek and @PatKamin)

___
*[README, line 291 at r32](https://reviewable.io/reviews/memkind/memkind/696#-Mjn55YeBcKANrTdRIE0:-Mjn55YeBcKANrTdRIE1:blcn1xs) ([raw file](https://github.com/memkind/memkind/blob/0d5cc014368689e23c9184abd18d0e1a8d609d48/README#L291)):*
> ```
> like errors and general information about environment to stderr.
> 
> In memkind library logs can be saved and named by pid.
> ```

Break this into two sentences. Be more descriptive. You don't have to repeat a phrase `in memkind library` - it's already stated in the previous paragraph.
___
*[README, line 292 at r32](https://reviewable.io/reviews/memkind/memkind/696#-Mjn4nj0DU8ADMt8KwlH:-Mjn4nj0DU8ADMt8KwlI:bwzgl1r) ([raw file](https://github.com/memkind/memkind/blob/0d5cc014368689e23c9184abd18d0e1a8d609d48/README#L292)):*
> ```
> 
> In memkind library logs can be saved and named by pid.
> It could be enabled by setting MEMKIND_LOG_TO_FILE in configure option.
> ```

Please, provide an example of how one can enable logging to file(s).


<!-- Sent from Reviewable.io -->

2021-09-17 11:38 UTC, jacekgrzybek reviewed
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/696)* status: 1 of 4 files reviewed, 4 unresolved discussions (waiting on @jacekgrzybek and @PatKamin)

___
*[README, line 291 at r32](https://reviewable.io/reviews/memkind/memkind/696#-Mjn55YeBcKANrTdRIE0:-MjnYJJh-1ak3_VC7blZ:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/0d5cc014368689e23c9184abd18d0e1a8d609d48/README#L291)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Break this into two sentences. Be more descriptive. You don't have to repeat a phrase `in memkind library` - it's already stated in the previous paragraph.
</blockquote></details>

Done.
___
*[README, line 292 at r32](https://reviewable.io/reviews/memkind/memkind/696#-Mjn4nj0DU8ADMt8KwlH:-MjnYK0W0yvIiROAWDoe:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/0d5cc014368689e23c9184abd18d0e1a8d609d48/README#L292)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Please, provide an example of how one can enable logging to file(s).
</blockquote></details>

Done.
___
*[tiering/memtier_log.c, line 89 at r29](https://reviewable.io/reviews/memkind/memkind/696#-MjheeVUAInOd2TPUB7c:-MjnYDNg8nq0IZyUzwdy:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/49c84a91f0c0c858dc925718d4ec695fdc8ae8df/tiering/memtier_log.c#L89)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

> ```
> #ifdef MEMKIND_LOG_TO_FILE
>         save_log_to_file(overflow_msg, fileName, sizeof(overflow_msg));
> #else
>         swrite(STDERR_FILENO, overflow_msg, sizeof(overflow_msg));
> #endif
>     }
> #ifdef MEMKIND_LOG_TO_FILE
>     save_log_to_file(buf, fileName, b - buf);
> #else
>     swrite(STDERR_FILENO, buf, b - buf);
> #endif
> ```
Please, make it one `#ifdef` (like it's in memkind_log), it would be easier to read.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-09-17 12:43 UTC, PatKamin requested changes
> Reviewed 1 of 1 files at r31, 1 of 2 files at r32, 1 of 1 files at r33.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/696)* status: all files reviewed, 4 unresolved discussions (waiting on @jacekgrzybek)

___
*[README, line 291 at r32](https://reviewable.io/reviews/memkind/memkind/696#-Mjn55YeBcKANrTdRIE0:-MjndnTJ1mZANRgxLZK7:b-lhq5x7) ([raw file](https://github.com/memkind/memkind/blob/0d5cc014368689e23c9184abd18d0e1a8d609d48/README#L291)):*
<details><summary><i>Previously, jacekgrzybek (Jacek Grzybek) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Which processes? You can make more sentences out of it. First, indicate that logs can be saved to files. After that, describe that for every process which is using memkind a separate logfile is created. Next, note where the files will be written and what are their names (refer to PID, not pid).
___
*[README, line 292 at r32](https://reviewable.io/reviews/memkind/memkind/696#-Mjn4nj0DU8ADMt8KwlH:-MjnfPh88Y6d8rtOhF7q:bmiyarp) ([raw file](https://github.com/memkind/memkind/blob/0d5cc014368689e23c9184abd18d0e1a8d609d48/README#L292)):*
<details><summary><i>Previously, jacekgrzybek (Jacek Grzybek) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

`This feature could be enabled by passing the following variable to the configure script:`
___
*[tiering/memtier_log.c, line 75 at r33](https://reviewable.io/reviews/memkind/memkind/696#-Mjnlwkk8p9hEbQH4sfi:-Mjnlwkk8p9hEbQH4sfj:by8c8lk) ([raw file](https://github.com/memkind/memkind/blob/65871122774baea8d8e02decaf952da2576f1944/tiering/memtier_log.c#L75)):*
> ```C
>     }
> 
>     char overflow_msg[] = "Warning: message truncated.\n";
> ```

Restore `const`.


<!-- Sent from Reviewable.io -->

2021-09-20 10:13 UTC, PatKamin reviewed
> Reviewed 1 of 2 files at r34.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/696)* status: 3 of 4 files reviewed, 3 unresolved discussions (waiting on @jacekgrzybek and @PatKamin)



<!-- Sent from Reviewable.io -->

2021-09-20 14:29 UTC, PatKamin requested changes
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/696)* status: 3 of 4 files reviewed, 4 unresolved discussions (waiting on @jacekgrzybek and @PatKamin)

___
*[src/memkind_log.c, line 60 at r34](https://reviewable.io/reviews/memkind/memkind/696#-Mk2ax6d1fZMyniIpGSg:-Mk2ax6d1fZMyniIpGSh:b-r806vx) ([raw file](https://github.com/memkind/memkind/blob/c7ea84bc222ba17c3529d42df70fdf4c37713add/src/memkind_log.c#L60)):*
> ```C
> 
> #ifdef MEMKIND_LOG_TO_FILE
> static void save_log_to_file(char *log, char *fileName, int len)
> ```

Move swrite() and save_log_to_file() into one `#ifdef`.


<!-- Sent from Reviewable.io -->

2021-09-22 07:27 UTC, jacekgrzybek reviewed
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/696)* status: 1 of 4 files reviewed, 3 unresolved discussions (waiting on @jacekgrzybek and @PatKamin)

___
*[src/memkind_log.c, line 60 at r34](https://reviewable.io/reviews/memkind/memkind/696#-Mk2ax6d1fZMyniIpGSg:-MkBOfaB9KiM5XIumKgU:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/c7ea84bc222ba17c3529d42df70fdf4c37713add/src/memkind_log.c#L60)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Move swrite() and save_log_to_file() into one `#ifdef`.
</blockquote></details>

Done.
___
*[tiering/memtier_log.c, line 75 at r33](https://reviewable.io/reviews/memkind/memkind/696#-Mjnlwkk8p9hEbQH4sfi:-MkBOYeo5VvV4ZBsOr0A:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/65871122774baea8d8e02decaf952da2576f1944/tiering/memtier_log.c#L75)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Restore `const`.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-09-22 07:37 UTC, PatKamin reviewed
> Reviewed 1 of 2 files at r34, 1 of 2 files at r35.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/696)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @jacekgrzybek and @PatKamin)



<!-- Sent from Reviewable.io -->

2021-09-22 08:12 UTC, jacekgrzybek reviewed
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/696)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @PatKamin)

___
*[README, line 291 at r32](https://reviewable.io/reviews/memkind/memkind/696#-Mjn55YeBcKANrTdRIE0:-MkBZ7Au-p1gEyfOJX54:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/0d5cc014368689e23c9184abd18d0e1a8d609d48/README#L291)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Which processes? You can make more sentences out of it. First, indicate that logs can be saved to files. After that, describe that for every process which is using memkind a separate logfile is created. Next, note where the files will be written and what are their names (refer to PID, not pid).
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-09-22 09:48 UTC, merged