Add fixed kind
memkind/memkind pull request #714
Opened 2021-12-07 17:34 UTC by maciekpac

### Description

### Types of changes

- [ ] Bugfix (non-breaking change which fixes issue linked in Description above)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Documentation (correction or otherwise)
- [ ] Cosmetics (whitespace, appearance)
- [ ] Other

### Checklist

- [x] Code compiles without errors
- [x] All tests pass locally with my changes (see TESTING section in CONTRIBUTING file)
- [x] Created tests which will fail without the change (if possible)
- [x] Extended the README/documentation (if necessary)
- [x] All newly added files have proprietary license (if necessary)
- [x] All newly added files are referenced in MANIFEST files (if necessary)

## Further comments

According to discussion that took place on our daily meeting, I decided not to generalize code, at least not for now. Any comments related to this fact are welcome but, unless the discussion is repeated and our squad comes to a different conclusion, they will be taken into account only when preparing next pull request.

2021-12-08 08:43 UTC, bratpiorka requested changes
> Reviewed 9 of 9 files at r1, 4 of 4 files at r2, 2 of 2 files at r3, 1 of 1 files at r4, 1 of 1 files at r5, 2 of 2 files at r6, 7 of 7 files at r7, 5 of 5 files at r8, 2 of 2 files at r9, 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/714)* status: all files reviewed, 4 unresolved discussions (waiting on @maciekpac, @PatKamin, and @pbalcer)

___
*[examples/fixed_malloc.c, line 32 at r1](https://reviewable.io/reviews/memkind/memkind/714#-MqO6egVCqMGMwjI9MJW:-MqO6egVCqMGMwjI9MJX:bx5yqg0) ([raw file](https://github.com/memkind/memkind/blob/ccd2a3951d644b158f6159364139eb54bcc8bc3f/examples/fixed_malloc.c#L32)):*
> ```C
>     // Create PMEM partition with specific size
>     err = memkind_create_fixed(addr, FIXED_MAP_SIZE, &fixed_kind);
>     if (err) {
> ```

I'm really missing noun in this func name.. I wonder if "memkind_create_fixed_kind" or "memkind_use_mapping" would be better but it is only a suggestion
___
*[include/memkind.h, line 512 at r1](https://reviewable.io/reviews/memkind/memkind/714#-MqO7oS33fewOfPeLq1H:-MqO7oS4160n92FaCin4:bm4q7ai) ([raw file](https://github.com/memkind/memkind/blob/ccd2a3951d644b158f6159364139eb54bcc8bc3f/include/memkind.h#L512)):*
> ```objc
> /// \note STANDARD API
> /// \param addr address of the map
> /// \param size size of the map for kind
> ```

I would remove "for kind"
___
*[src/memkind.c, line 1062 at r1](https://reviewable.io/reviews/memkind/memkind/714#-MqO8Ps478QDzf0WeIw5:-MqO8Ps478QDzf0WeIw6:bqnxjkk) ([raw file](https://github.com/memkind/memkind/blob/ccd2a3951d644b158f6159364139eb54bcc8bc3f/src/memkind.c#L1062)):*
> ```C
>     priv->size = size;
> 
>     return 0;
> ```

please add support for "fixed_kind" to memkind_get_capacity() (remember to extend the doc)
___
*[src/memkind.c, line 1050 at r10](https://reviewable.io/reviews/memkind/memkind/714#-MqOC6ZlAH4TJZTzE62l:-MqOC6ZlAH4TJZTzE62m:b-olw1b8) ([raw file](https://github.com/memkind/memkind/blob/4929e9c790adf3c754005c1e7bccf1b407039e3b/src/memkind.c#L1050)):*
> ```C
> {
>     char name[32];
>     snprintf(name, sizeof(name), "pmem%p", addr);
> ```

please use different name
___
*[src/memkind_fixed.c, line 59 at r1](https://reviewable.io/reviews/memkind/memkind/714#-MqO9dzZ91tkKZNbpcGC:-MqO9dzZ91tkKZNbpcGD:b8rm92c) ([raw file](https://github.com/memkind/memkind/blob/ccd2a3951d644b158f6159364139eb54bcc8bc3f/src/memkind_fixed.c#L59)):*
> ```C
>     }
> 
>     addr = memkind_fixed_mmap(kind, new_addr, size);
> ```

I saw that we ignore alignment here and in PMEM kind. Is it ok?
___
*[src/memkind_fixed.c, line 65 at r1](https://reviewable.io/reviews/memkind/memkind/714#-MqO8zWGBZ_QKvPumHXq:-MqO8zWGBZ_QKvPumHXr:b-ewauce) ([raw file](https://github.com/memkind/memkind/blob/ccd2a3951d644b158f6159364139eb54bcc8bc3f/src/memkind_fixed.c#L65)):*
> ```C
>         *commit = true;
> 
>         /* XXX - check alignment */
> ```

this comment is copied, right? please remove at least it from here


<!-- Sent from Reviewable.io -->

2021-12-08 09:19 UTC, pbalcer approved these changes
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/714)* status: all files reviewed, 7 unresolved discussions (waiting on @bratpiorka, @maciekpac, and @PatKamin)

___
*[examples/fixed_malloc.c, line 26 at r1](https://reviewable.io/reviews/memkind/memkind/714#-MqOHoAr6eKKiyUGmEDM:-MqOHoAr6eKKiyUGmEDN:br4m2qc) ([raw file](https://github.com/memkind/memkind/blob/ccd2a3951d644b158f6159364139eb54bcc8bc3f/examples/fixed_malloc.c#L26)):*
> ```C
>     int err = 0;
> 
>     void *addr = mmap(NULL, FIXED_MAP_SIZE, PROT_READ | PROT_WRITE,
> ```

this doesn't have a corresponding munmap I think.
___
*[examples/fixed_malloc.c, line 32 at r1](https://reviewable.io/reviews/memkind/memkind/714#-MqO6egVCqMGMwjI9MJW:-MqOHUrJ-G6sXlefyUdh:bnaxp5j) ([raw file](https://github.com/memkind/memkind/blob/ccd2a3951d644b158f6159364139eb54bcc8bc3f/examples/fixed_malloc.c#L32)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

I'm really missing noun in this func name.. I wonder if "memkind_create_fixed_kind" or "memkind_use_mapping" would be better but it is only a suggestion
</blockquote></details>

This follows the naming convention set by existing functions (create_kind/create_pmem), so I wouldn't change it.
___
*[examples/fixed_malloc.c, line 37 at r1](https://reviewable.io/reviews/memkind/memkind/714#-MqOHsIe63IsFjFVjt1H:-MqOHsIe63IsFjFVjt1I:bsqcoqi) ([raw file](https://github.com/memkind/memkind/blob/ccd2a3951d644b158f6159364139eb54bcc8bc3f/examples/fixed_malloc.c#L37)):*
> ```C
>     }
> 
>     char *pmem_str1 = NULL;
> ```

old names :P
this is just a copy/paste of the pmem example, so I suggest just simplifying this whole thing into something like: malloc/check if ptr is in range of the map/free
___
*[src/memkind_fixed.c, line 59 at r1](https://reviewable.io/reviews/memkind/memkind/714#-MqO9dzZ91tkKZNbpcGC:-MqOJdhn7rzwmMauJo-S:bvkb5on) ([raw file](https://github.com/memkind/memkind/blob/ccd2a3951d644b158f6159364139eb54bcc8bc3f/src/memkind_fixed.c#L59)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

I saw that we ignore alignment here and in PMEM kind. Is it ok?
</blockquote></details>

right now - yes, but long-term probably not. Just to be safe, I would add a requirement for the fixed kind that the provided memory region needs to have alignment and size that are a multiple of page size.
___
*[src/memkind_fixed.c, line 28 at r10](https://reviewable.io/reviews/memkind/memkind/714#-MqOKRHh2fBYgyEoMoEc:-MqOKRHh2fBYgyEoMoEd:bc6ihyw) ([raw file](https://github.com/memkind/memkind/blob/4929e9c790adf3c754005c1e7bccf1b407039e3b/src/memkind_fixed.c#L28)):*
> ```C
>     .free = memkind_arena_free,
>     .mmap = memkind_fixed_mmap,
>     .get_mmap_flags = memkind_fixed_get_mmap_flags,
> ```

set this to NULL and remove the implementation for fixed kind.


<!-- Sent from Reviewable.io -->

2021-12-08 11:09 UTC, PatKamin commented on src/memkind.c
> +    char name[32];
Allow longer names. The longest name of static kinds is memkind_highest_bandwidth_local_preferred which is ca. 40 characters long. It's easy to imagine that one would like to use names with the similar char count.

2021-12-08 11:09 UTC, PatKamin commented on include/memkind/internal/memkind_fixed.h
> +#include <memkind.h>
nit: Use either `""` or `<>` for consistency.

2021-12-08 12:17 UTC, PatKamin commented on src/memkind_fixed.c
> +MEMKIND_EXPORT int memkind_fixed_get_mmap_flags(struct memkind *kind,
Add these functions to a manual.

2021-12-08 19:35 UTC, maciekpac reviewed
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/714)* status: all files reviewed, 29 unresolved discussions (waiting on @bratpiorka, @PatKamin, and @pbalcer)

___
*[examples/fixed_malloc.c, line 26 at r1](https://reviewable.io/reviews/memkind/memkind/714#-MqOHoAr6eKKiyUGmEDM:-MqQQBA_-fcvqgeT57Ai:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/ccd2a3951d644b158f6159364139eb54bcc8bc3f/examples/fixed_malloc.c#L26)):*
<details><summary><i>Previously, pbalcer (Piotr Balcer) wrote…</i></summary><blockquote>

this doesn't have a corresponding munmap I think.
</blockquote></details>

Done.
___
*[examples/fixed_malloc.c, line 32 at r1](https://reviewable.io/reviews/memkind/memkind/714#-MqO6egVCqMGMwjI9MJW:-MqQQDoA-iOHPKxLz47k:brw4o4b) ([raw file](https://github.com/memkind/memkind/blob/ccd2a3951d644b158f6159364139eb54bcc8bc3f/examples/fixed_malloc.c#L32)):*
<details><summary><i>Previously, pbalcer (Piotr Balcer) wrote…</i></summary><blockquote>

This follows the naming convention set by existing functions (create_kind/create_pmem), so I wouldn't change it.
</blockquote></details>

Not modified
___
*[examples/fixed_malloc.c, line 37 at r1](https://reviewable.io/reviews/memkind/memkind/714#-MqOHsIe63IsFjFVjt1H:-MqQSyXE07sncFogTM72:b-1jking) ([raw file](https://github.com/memkind/memkind/blob/ccd2a3951d644b158f6159364139eb54bcc8bc3f/examples/fixed_malloc.c#L37)):*
<details><summary><i>Previously, pbalcer (Piotr Balcer) wrote…</i></summary><blockquote>

old names :P
this is just a copy/paste of the pmem example, so I suggest just simplifying this whole thing into something like: malloc/check if ptr is in range of the map/free
</blockquote></details>

After discussing what PRs should contain during our daily meeting, we decided to do refactoring/simplifications in a separate PR.
___
*[include/memkind.h, line 512 at r1](https://reviewable.io/reviews/memkind/memkind/714#-MqO7oS33fewOfPeLq1H:-MqQREii7qGpRaJfYs52:bb6un1j) ([raw file](https://github.com/memkind/memkind/blob/ccd2a3951d644b158f6159364139eb54bcc8bc3f/include/memkind.h#L512)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

I would remove "for kind"
</blockquote></details>

Done
___
*[src/memkind.c, line 1062 at r1](https://reviewable.io/reviews/memkind/memkind/714#-MqO8Ps478QDzf0WeIw5:-MqQUE0PBEhEAT8MYNId:bb6un1j) ([raw file](https://github.com/memkind/memkind/blob/ccd2a3951d644b158f6159364139eb54bcc8bc3f/src/memkind.c#L1062)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

please add support for "fixed_kind" to memkind_get_capacity() (remember to extend the doc)
</blockquote></details>

Done
___
*[src/memkind.c, line 1050 at r10](https://reviewable.io/reviews/memkind/memkind/714#-MqOC6ZlAH4TJZTzE62l:-MqQRVpa6BLzQzFnEz4s:blkwblm) ([raw file](https://github.com/memkind/memkind/blob/4929e9c790adf3c754005c1e7bccf1b407039e3b/src/memkind.c#L1050)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

please use different name
</blockquote></details>

fixed%p
___
*[src/memkind_fixed.c, line 59 at r1](https://reviewable.io/reviews/memkind/memkind/714#-MqO9dzZ91tkKZNbpcGC:-MqQS4QsByCEihD0yRgU:b-gfoj2e) ([raw file](https://github.com/memkind/memkind/blob/ccd2a3951d644b158f6159364139eb54bcc8bc3f/src/memkind_fixed.c#L59)):*
<details><summary><i>Previously, pbalcer (Piotr Balcer) wrote…</i></summary><blockquote>

right now - yes, but long-term probably not. Just to be safe, I would add a requirement for the fixed kind that the provided memory region needs to have alignment and size that are a multiple of page size.
</blockquote></details>

Please check how this is handled in the new revision.
___
*[src/memkind_fixed.c, line 65 at r1](https://reviewable.io/reviews/memkind/memkind/714#-MqO8zWGBZ_QKvPumHXq:-MqQS91E6L4ncGwkKNmh:b-enhejg) ([raw file](https://github.com/memkind/memkind/blob/ccd2a3951d644b158f6159364139eb54bcc8bc3f/src/memkind_fixed.c#L65)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

this comment is copied, right? please remove at least it from here
</blockquote></details>

Removed && modified
___
*[src/memkind_fixed.c, line 28 at r10](https://reviewable.io/reviews/memkind/memkind/714#-MqOKRHh2fBYgyEoMoEc:-MqQS1HE-cQmW4L7OLnU:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/4929e9c790adf3c754005c1e7bccf1b407039e3b/src/memkind_fixed.c#L28)):*
<details><summary><i>Previously, pbalcer (Piotr Balcer) wrote…</i></summary><blockquote>

set this to NULL and remove the implementation for fixed kind.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-12-09 08:24 UTC, bratpiorka approved these changes
> Reviewed 15 of 15 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/714)* status: all files reviewed, 25 unresolved discussions (waiting on @PatKamin and @pbalcer)



<!-- Sent from Reviewable.io -->

2021-12-09 09:00 UTC, pbalcer requested changes
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/714)* status: all files reviewed, 23 unresolved discussions (waiting on @maciekpac and @PatKamin)

___
*[src/memkind_fixed.c, line 53 at r11](https://reviewable.io/reviews/memkind/memkind/714#-MqTPH4FAh6M1QwwUo2L:-MqTPH4FAh6M1QwwUo2M:b-hgxu2x) ([raw file](https://github.com/memkind/memkind/blob/30a379493d6542c576d884a0f873e5ca4a740ed0/src/memkind_fixed.c#L53)):*
> ```C
>     }
> 
>     if ((priv->size != 0 || align_offset != 0) &&
> ```

why this condition? 


<!-- Sent from Reviewable.io -->

2021-12-09 09:09 UTC, maciekpac reviewed
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/714)* status: all files reviewed, 23 unresolved discussions (waiting on @PatKamin and @pbalcer)

___
*[src/memkind_fixed.c, line 53 at r11](https://reviewable.io/reviews/memkind/memkind/714#-MqTPH4FAh6M1QwwUo2L:-MqTQqwfDD5GR3KC4usr:b-13xzfo) ([raw file](https://github.com/memkind/memkind/blob/30a379493d6542c576d884a0f873e5ca4a740ed0/src/memkind_fixed.c#L53)):*
<details><summary><i>Previously, pbalcer (Piotr Balcer) wrote…</i></summary><blockquote>

why this condition? 
</blockquote></details>

If size == 0, the pointer returned should still be aligned, even though we allocate 0 memory. We need to "use" some space, which we don't have, for memory alignment. Please correct me if your vision is different.


<!-- Sent from Reviewable.io -->

2021-12-09 09:10 UTC, PatKamin commented on .gitignore
> +/examples/fixed_cpp_allocator
Please, meld this commit with previous commits. Adding separate commits for review fixes can easily lead to a large amount of commits containing fixes. It's unnecessary burden given it's still a PR and commits can be amended anytime you want until the merge with the master branch. Please, sweep through the history of commits - there are no such commits as this one.

2021-12-09 10:46 UTC, PatKamin commented on include/fixed_allocator.h
> +/*
Meld this commit with 5a111884f510ac00b6c629c0d23362a606354c92

2021-12-09 10:46 UTC, PatKamin commented on examples/fixed_cpp_allocator.cpp
> +    {
Meld this commit with e54b3ea66ef30e2da63ca76cad91403dad24f987

2021-12-09 10:46 UTC, PatKamin commented on MANIFEST
> +man/fixedallocator.3
Meld this commit with 8c51f20b01cfa65c5964ddf21eee954d1f46181c

2021-12-09 15:35 UTC, maciekpac reviewed
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/714)* status: all files reviewed, 27 unresolved discussions (waiting on @maciekpac, @PatKamin, and @pbalcer)

___
*[.gitignore, line 45 at r11](https://reviewable.io/reviews/memkind/memkind/714#-MqQXvPi7Z3IwnyuqCU4-r11-45:-MqThDo5A7eLZXnWya_y:bz1sghk) ([raw file](https://github.com/memkind/memkind/blob/30a379493d6542c576d884a0f873e5ca4a740ed0/.gitignore#L45)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Please, meld this commit with previous commits. Adding separate commits for review fixes can easily lead to a large amount of commits containing fixes. It's unnecessary burden given it's still a PR and commits can be amended anytime you want until the merge with the master branch. Please, sweep through the history of commits - there are no such commits as this one.
</blockquote></details>

After a discussion, a decision was made to rewrite hisotry
___
*[include/fixed_allocator.h, line 16 at r4](https://reviewable.io/reviews/memkind/memkind/714#-MqKxRhq5YWMPkOxNZmF-r4-16:-MqUpBY8ApLQAUqcnaNa:b-2bpyei) ([raw file](https://github.com/memkind/memkind/blob/912f4d91b9db2009ef4214d5d21a7b225b4f257f/include/fixed_allocator.h#L16)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Meld this commit with 5a111884f510ac00b6c629c0d23362a606354c92
</blockquote></details>

History was re-written, please check it now
___
*[src/memkind_fixed.c, line 53 at r11](https://reviewable.io/reviews/memkind/memkind/714#-MqTPH4FAh6M1QwwUo2L:-MqUp3rD5f7zgRpICFyt:b-886gsx) ([raw file](https://github.com/memkind/memkind/blob/30a379493d6542c576d884a0f873e5ca4a740ed0/src/memkind_fixed.c#L53)):*
<details><summary><i>Previously, pbalcer (Piotr Balcer) wrote…</i></summary><blockquote>

This is not a malloc implementation, allocating 0 here is an error.
</blockquote></details>

Fixed


<!-- Sent from Reviewable.io -->

2021-12-10 07:47 UTC, PatKamin requested changes
> Reviewed 1 of 18 files at r12, 1 of 4 files at r13, 5 of 8 files at r14, 4 of 5 files at r15, 7 of 7 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/714)* status: all files reviewed, 15 unresolved discussions (waiting on @maciekpac and @pbalcer)

___
*[Makefile.am, line 44 at r16](https://reviewable.io/reviews/memkind/memkind/714#-MqXvj2z2o1A95GOLZL_:-MqXvj2z2o1A95GOLZLa:br4ijka) ([raw file](https://github.com/memkind/memkind/blob/155f633da2128a3b97def2190a958dbc6d9848d1/Makefile.am#L44)):*
> ```Makefile
>                   include/memkind_deprecated.h \
>                   include/pmem_allocator.h \
>                   include/fixed_allocator.h \
> ```

nit: alphabetical order, please. In other places in this file, too.
___
*[include/fixed_allocator.h, line 2 at r10](https://reviewable.io/reviews/memkind/memkind/714#-MqKxRhq5YWMPkOxNZmF-r10-2:-MqY1HzI7gGuevKTE3VE:b-tkr8g6) ([raw file](https://github.com/memkind/memkind/blob/4929e9c790adf3c754005c1e7bccf1b407039e3b/include/fixed_allocator.h#L2)):*
<details><summary><i>Previously, maciekpac wrote…</i></summary><blockquote>

Done
</blockquote></details>

Remove 2018 part. It's a brand new file.
___
*[include/memkind.h, line 514 at r16](https://reviewable.io/reviews/memkind/memkind/714#-MqY1mjDC9LCvXIIlObb:-MqY1mjDC9LCvXIIlObc:b-dce5pu) ([raw file](https://github.com/memkind/memkind/blob/155f633da2128a3b97def2190a958dbc6d9848d1/include/memkind.h#L514)):*
> ```objc
> /// \param size size of the mapping
> /// \param kind pointer to kind which will be created
> /// \return Memkind operation status, MEMKIND_SUCCESS on success, other values
> ```

Return MEMKIND_SUCCESS explicitly in this function.
___
*[include/memkind/internal/memkind_fixed.h, line 2 at r16](https://reviewable.io/reviews/memkind/memkind/714#-MqY1wFU1_Y7effN6TQ0:-MqY1wFU1_Y7effN6TQ1:b91lkk) ([raw file](https://github.com/memkind/memkind/blob/155f633da2128a3b97def2190a958dbc6d9848d1/include/memkind/internal/memkind_fixed.h#L2)):*
> ```objc
> // SPDX-License-Identifier: BSD-2-Clause
> /* Copyright (C) 2015 - 2021 Intel Corporation. */
> ```

Remove 2015 part.
___
*[man/fixedallocator.3, line 57 at r10](https://reviewable.io/reviews/memkind/memkind/714#-MqKxRhq5YWMPkOxNZmH-r10-57:-MqXymJH0mRBJEu61cX4:b11168d) ([raw file](https://github.com/memkind/memkind/blob/4929e9c790adf3c754005c1e7bccf1b407039e3b/man/fixedallocator.3#L57)):*
<details><summary><i>Previously, maciekpac wrote…</i></summary><blockquote>

General comment - this was copy-pasted from pmemallocator.3, the same error exists there, but is completely irrelevant to current PR - I'm not fixing that one (at least now), but maybe we should create a list of files to check?
</blockquote></details>

OK. Probably we could review all of the manuals, but not now.
___
*[man/fixedallocator.3, line 2 at r16](https://reviewable.io/reviews/memkind/memkind/714#-MqY1zxI-U4T4aU1Rt6X:-MqY1zxI-U4T4aU1Rt6Y:b-qqvlqh) ([raw file](https://github.com/memkind/memkind/blob/155f633da2128a3b97def2190a958dbc6d9848d1/man/fixedallocator.3#L2)):*
> ```Roff
> .\" SPDX-License-Identifier: BSD-2-Clause
> .\" Copyright (C) 2018 - 2021 Intel Corporation.
> ```

Remove 2018 part.
___
*[man/fixedallocator.3, line 3 at r16](https://reviewable.io/reviews/memkind/memkind/714#-MqY21IzAki_pNWKkIZp:-MqY21IzAki_pNWKkIZq:bs7lkq3) ([raw file](https://github.com/memkind/memkind/blob/155f633da2128a3b97def2190a958dbc6d9848d1/man/fixedallocator.3#L3)):*
> ```Roff
> .\" SPDX-License-Identifier: BSD-2-Clause
> .\" Copyright (C) 2018 - 2021 Intel Corporation.
> .\" TODO update constructors!
> ```

Is it still to do?
___
*[src/memkind_fixed.c, line 2 at r16](https://reviewable.io/reviews/memkind/memkind/714#-MqY1AVREM3is31HrtBM:-MqY1AVS8KjoMbgM71vo:b91lkk) ([raw file](https://github.com/memkind/memkind/blob/155f633da2128a3b97def2190a958dbc6d9848d1/src/memkind_fixed.c#L2)):*
> ```C
> // SPDX-License-Identifier: BSD-2-Clause
> /* Copyright (C) 2015 - 2021 Intel Corporation. */
> ```

Remove 2015 part.
___
*[test/fixed_allocator_tests.cpp, line 2 at r16](https://reviewable.io/reviews/memkind/memkind/714#-MqY2FTr6DewQbCKG_2Z:-MqY2FTs19D6Zmy7kOSU:b-qqvlqh) ([raw file](https://github.com/memkind/memkind/blob/155f633da2128a3b97def2190a958dbc6d9848d1/test/fixed_allocator_tests.cpp#L2)):*
> ```cpp
> // SPDX-License-Identifier: BSD-2-Clause
> /* Copyright (C) 2018 - 2021 Intel Corporation. */
> ```

Remove 2018 part.
___
*[test/fixed_allocator_tests.cpp, line 6 at r16](https://reviewable.io/reviews/memkind/memkind/714#-MqY2KGI7nzi3MEmzJUE:-MqY2KGI7nzi3MEmzJUF:b-v4dyjz) ([raw file](https://github.com/memkind/memkind/blob/155f633da2128a3b97def2190a958dbc6d9848d1/test/fixed_allocator_tests.cpp#L6)):*
> ```cpp
> #include "fixed_allocator.h"
> #include "memkind.h"
> #include <algorithm>
> ```

Add an extra empty line above for more clarity.
___
*[test/fixed_allocator_tests.cpp, line 27 at r16](https://reviewable.io/reviews/memkind/memkind/714#-MqYHhR72oFwgl8DqBCn:-MqYHhR72oFwgl8DqBCo:bw2gwgq) ([raw file](https://github.com/memkind/memkind/blob/155f633da2128a3b97def2190a958dbc6d9848d1/test/fixed_allocator_tests.cpp#L27)):*
> ```cpp
>     using int_alloc_ptr = std::shared_ptr<libmemkind::fixed::allocator<int>>;
>     int_alloc_ptr alloc_source;
>     int_alloc_ptr alloc_conservative;
> ```

It seems like only two pointers are needed in these tests.
___
*[test/fixed_allocator_tests.cpp, line 287 at r16](https://reviewable.io/reviews/memkind/memkind/714#-MqYHWNq0r6wkdxEqFKX:-MqYHWNr9KpZ8PAr_kLq:b-x3fqi7) ([raw file](https://github.com/memkind/memkind/blob/155f633da2128a3b97def2190a958dbc6d9848d1/test/fixed_allocator_tests.cpp#L287)):*
> ```cpp
>     typedef std::basic_string<char, std::char_traits<char>,
>                               libmemkind::fixed::allocator<char>>
>         pmem_string;
> ```

Remove `pmem` from naming in this test. Same comments apply in the other class.
___
*[test/fixed_allocator_tests.cpp, line 309 at r16](https://reviewable.io/reviews/memkind/memkind/714#-MqYHkbe5zDUrxvtZgyz:-MqYHkbe5zDUrxvtZgz-:brhumzt) ([raw file](https://github.com/memkind/memkind/blob/155f633da2128a3b97def2190a958dbc6d9848d1/test/fixed_allocator_tests.cpp#L309)):*
> ```cpp
>         pmem_string;
>     typedef int key_t;
>     typedef pmem_string value_t;
> ```

Same here.
___
*[test/fixed_allocator_tests.cpp, line 365 at r16](https://reviewable.io/reviews/memkind/memkind/714#-MqYDVFr9s3pfOvMthXu:-MqYDVFr9s3pfOvMthXv:bw2gwgq) ([raw file](https://github.com/memkind/memkind/blob/155f633da2128a3b97def2190a958dbc6d9848d1/test/fixed_allocator_tests.cpp#L365)):*
> ```cpp
>     using int_alloc_ptr = std::shared_ptr<libmemkind::fixed::allocator<int>>;
>     int_alloc_ptr alloc_source;
>     int_alloc_ptr alloc_conservative;
> ```

It seems like only two pointers are needed in these tests.
___
*[test/fixed_allocator_tests.cpp, line 475 at r16](https://reviewable.io/reviews/memkind/memkind/714#-MqYDELVCNEjFXsI_6MM:-MqYDELVCNEjFXsI_6MN:bc3k6s9) ([raw file](https://github.com/memkind/memkind/blob/155f633da2128a3b97def2190a958dbc6d9848d1/test/fixed_allocator_tests.cpp#L475)):*
> ```cpp
> }
> 
> // Single allocation-deallocation test conservative policy
> ```

There is no conservative policy here. Remove this test as it's the same as the one above.


<!-- Sent from Reviewable.io -->

2021-12-10 10:44 UTC, PatKamin requested changes
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/714)* status: all files reviewed, 16 unresolved discussions (waiting on @maciekpac and @pbalcer)

___
*[man/memkind_fixed.3, line 30 at r16](https://reviewable.io/reviews/memkind/memkind/714#-MqYwExO9u-yg9mWeb5L:-MqYwExO9u-yg9mWeb5M:bxvq311) ([raw file](https://github.com/memkind/memkind/blob/155f633da2128a3b97def2190a958dbc6d9848d1/man/memkind_fixed.3#L30)):*
> ```Roff
> The most convenient way to create fixed kinds is to use
> .BR memkind_create_fixed ()
> (see
> ```

It's not described in the memkind(3) manual. Please, add it.


<!-- Sent from Reviewable.io -->

2021-12-10 12:36 UTC, maciekpac reviewed
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/714)* status: 2 of 21 files reviewed, 15 unresolved discussions (waiting on @bratpiorka, @maciekpac, @PatKamin, and @pbalcer)

___
*[MANIFEST, line 411 at r8](https://reviewable.io/reviews/memkind/memkind/714#-MqKxRhq5YWMPkOxNZm5-r8-411:-MqZ2oqAAcbg5b3khUTP:bnimsay) ([raw file](https://github.com/memkind/memkind/blob/6b441b24a8fa905edd18f7968d97fc65c5646f44/MANIFEST#L411)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Meld this commit with 8c51f20b01cfa65c5964ddf21eee954d1f46181c
</blockquote></details>

History was rewritten and was accepted during daily meeting
___
*[Makefile.am, line 44 at r16](https://reviewable.io/reviews/memkind/memkind/714#-MqXvj2z2o1A95GOLZL_:-MqZ42Sa2I6wpJ0EGq9r:bb6un1j) ([raw file](https://github.com/memkind/memkind/blob/155f633da2128a3b97def2190a958dbc6d9848d1/Makefile.am#L44)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

nit: alphabetical order, please. In other places in this file, too.
</blockquote></details>

Done
___
*[examples/fixed_cpp_allocator.cpp, line 58 at r6](https://reviewable.io/reviews/memkind/memkind/714#-MqKxRhr5ZsaIQU23Tte-r6-58:-MqZ4AIc3UBsjGbRttFV:b8a6a1y) ([raw file](https://github.com/memkind/memkind/blob/628f2a370cd16691a19254c879bcdc590e27092d/examples/fixed_cpp_allocator.cpp#L58)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Meld this commit with e54b3ea66ef30e2da63ca76cad91403dad24f987
</blockquote></details>

outdated comment, history was rewritten and accepted during daily meeting
___
*[include/fixed_allocator.h, line 2 at r10](https://reviewable.io/reviews/memkind/memkind/714#-MqKxRhq5YWMPkOxNZmF-r10-2:-MqZ4LmuB32ei0kL1c7q:b-2io9sg) ([raw file](https://github.com/memkind/memkind/blob/4929e9c790adf3c754005c1e7bccf1b407039e3b/include/fixed_allocator.h#L2)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Remove 2018 part. It's a brand new file.
</blockquote></details>

Done. It was somehow messed up during rebase
___
*[include/memkind.h, line 514 at r16](https://reviewable.io/reviews/memkind/memkind/714#-MqY1mjDC9LCvXIIlObb:-MqZ5FeKDgFhBACKOBKa:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/155f633da2128a3b97def2190a958dbc6d9848d1/include/memkind.h#L514)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Return MEMKIND_SUCCESS explicitly in this function.
</blockquote></details>

Done.
___
*[include/memkind/internal/memkind_fixed.h, line 2 at r16](https://reviewable.io/reviews/memkind/memkind/714#-MqY1wFU1_Y7effN6TQ0:-MqZ5QU21oQmSvWyjl3o:bjq9psd) ([raw file](https://github.com/memkind/memkind/blob/155f633da2128a3b97def2190a958dbc6d9848d1/include/memkind/internal/memkind_fixed.h#L2)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Remove 2015 part.
</blockquote></details>

Done. Must have been messed up during rebase
___
*[man/fixedallocator.3, line 2 at r16](https://reviewable.io/reviews/memkind/memkind/714#-MqY1zxI-U4T4aU1Rt6X:-MqZ5dQD3XhNT5XN1SnH:b-rnna9m) ([raw file](https://github.com/memkind/memkind/blob/155f633da2128a3b97def2190a958dbc6d9848d1/man/fixedallocator.3#L2)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Remove 2018 part.
</blockquote></details>

Done. Must have been messed up during rebases
___
*[man/fixedallocator.3, line 3 at r16](https://reviewable.io/reviews/memkind/memkind/714#-MqY21IzAki_pNWKkIZp:-MqZ5guwBmGw2yxMV4WA:b-nl7cml) ([raw file](https://github.com/memkind/memkind/blob/155f633da2128a3b97def2190a958dbc6d9848d1/man/fixedallocator.3#L3)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Is it still to do?
</blockquote></details>

Not any more. Removed
___
*[src/memkind_fixed.c, line 2 at r16](https://reviewable.io/reviews/memkind/memkind/714#-MqY1AVREM3is31HrtBM:-MqZCjpY11RSJNQquS86:b-ly3p2) ([raw file](https://github.com/memkind/memkind/blob/155f633da2128a3b97def2190a958dbc6d9848d1/src/memkind_fixed.c#L2)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Remove 2015 part.
</blockquote></details>

Done, must have been messed up with rebase
___
*[test/fixed_allocator_tests.cpp, line 2 at r16](https://reviewable.io/reviews/memkind/memkind/714#-MqY2FTr6DewQbCKG_2Z:-MqZDCS4EQs0JMzlRC44:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/155f633da2128a3b97def2190a958dbc6d9848d1/test/fixed_allocator_tests.cpp#L2)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Remove 2018 part.
</blockquote></details>

Done.
___
*[test/fixed_allocator_tests.cpp, line 6 at r16](https://reviewable.io/reviews/memkind/memkind/714#-MqY2KGI7nzi3MEmzJUE:-MqZDEUV3akv3bStmPO7:bl76akh) ([raw file](https://github.com/memkind/memkind/blob/155f633da2128a3b97def2190a958dbc6d9848d1/test/fixed_allocator_tests.cpp#L6)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Add an extra empty line above for more clarity.
</blockquote></details>

Done, but shouldn't it be handled by clang-format?
___
*[test/fixed_allocator_tests.cpp, line 27 at r16](https://reviewable.io/reviews/memkind/memkind/714#-MqYHhR72oFwgl8DqBCn:-MqZDZV_4H27EnNu-FoX:b-r536dd) ([raw file](https://github.com/memkind/memkind/blob/155f633da2128a3b97def2190a958dbc6d9848d1/test/fixed_allocator_tests.cpp#L27)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

It seems like only two pointers are needed in these tests.
</blockquote></details>

All of them are used right now; possible refactoring might be done in a separate PR
___
*[test/fixed_allocator_tests.cpp, line 287 at r16](https://reviewable.io/reviews/memkind/memkind/714#-MqYHWNq0r6wkdxEqFKX:-MqZJkeO620_g32mc6uM:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/155f633da2128a3b97def2190a958dbc6d9848d1/test/fixed_allocator_tests.cpp#L287)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Remove `pmem` from naming in this test. Same comments apply in the other class.
</blockquote></details>

Done.
___
*[test/fixed_allocator_tests.cpp, line 309 at r16](https://reviewable.io/reviews/memkind/memkind/714#-MqYHkbe5zDUrxvtZgyz:-MqZJlTh71IdGfKvMWho:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/155f633da2128a3b97def2190a958dbc6d9848d1/test/fixed_allocator_tests.cpp#L309)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Same here.
</blockquote></details>

Done.
___
*[test/fixed_allocator_tests.cpp, line 365 at r16](https://reviewable.io/reviews/memkind/memkind/714#-MqYDVFr9s3pfOvMthXu:-MqZJmMGCQP1CT1Uo0rL:bivbhnz) ([raw file](https://github.com/memkind/memkind/blob/155f633da2128a3b97def2190a958dbc6d9848d1/test/fixed_allocator_tests.cpp#L365)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

It seems like only two pointers are needed in these tests.
</blockquote></details>

All of them are used right now; possible refactoring will come in a separate PR (as agreed during daily meeting)
___
*[test/fixed_allocator_tests.cpp, line 475 at r16](https://reviewable.io/reviews/memkind/memkind/714#-MqYDELVCNEjFXsI_6MM:-MqZL20s4aqdDrAlDpEF:b-j5uoso) ([raw file](https://github.com/memkind/memkind/blob/155f633da2128a3b97def2190a958dbc6d9848d1/test/fixed_allocator_tests.cpp#L475)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

There is no conservative policy here. Remove this test as it's the same as the one above.
</blockquote></details>

Removed; also removed the *conservative* pointer


<!-- Sent from Reviewable.io -->

2021-12-10 12:50 UTC, pbalcer reviewed
> Reviewed 2 of 8 files at r19, 2 of 5 files at r20, 4 of 7 files at r21, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/714)* status: 10 of 21 files reviewed, 14 unresolved discussions (waiting on @bratpiorka, @maciekpac, and @PatKamin)



<!-- Sent from Reviewable.io -->

2021-12-10 12:51 UTC, pbalcer reviewed
The word is 'squash', not 'meld'. See https://pmem.io/2014/09/09/git-workflow.html

2021-12-10 12:54 UTC, bratpiorka approved these changes
> Reviewed 1 of 18 files at r12, 19 of 19 files at r17, 4 of 4 files at r18, 8 of 8 files at r19, 5 of 5 files at r20, 6 of 7 files at r21, 1 of 1 files at r22, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/714)* status: all files reviewed, 14 unresolved discussions (waiting on @maciekpac and @PatKamin)



<!-- Sent from Reviewable.io -->

2021-12-10 13:06 UTC, PatKamin requested changes
> Reviewed 1 of 19 files at r17, 1 of 4 files at r18, 1 of 8 files at r19, 1 of 5 files at r20, 2 of 7 files at r21, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/714)* status: all files reviewed, 2 unresolved discussions (waiting on @maciekpac)

___
*[examples/fixed_malloc.c, line 30 at r22](https://reviewable.io/reviews/memkind/memkind/714#-MqZQfgeE9uKO5pVJOGq:-MqZQfgeE9uKO5pVJOGr:b-rq59it) ([raw file](https://github.com/memkind/memkind/blob/da80a01a1a137a78985c623e8eb7591bda093d2a/examples/fixed_malloc.c#L30)):*
> ```C
>     assert(addr != MAP_FAILED);
> 
>     // Create PMEM partition with specific size
> ```

PMEM partition?
___
*[examples/fixed_malloc.c, line 74 at r22](https://reviewable.io/reviews/memkind/memkind/714#-MqZQluP-BhvtqJfE4zM:-MqZQluP-BhvtqJfE4zN:b5ju6y) ([raw file](https://github.com/memkind/memkind/blob/da80a01a1a137a78985c623e8eb7591bda093d2a/examples/fixed_malloc.c#L74)):*
> ```C
>     sprintf(fixed_str1, "Hello world from fixed - fixed_str1.\n");
>     sprintf(fixed_str2, "Hello world from fixed - fixed_str2.\n");
>     sprintf(fixed_str3, "Hello world from persistent memory - fixed_str3.\n");
> ```

persistent memory?


<!-- Sent from Reviewable.io -->

2021-12-10 13:12 UTC, PatKamin commented
> The word is 'squash', not 'meld'. See https://pmem.io/2014/09/09/git-workflow.html

I think that both are correct, during interactive rebase we have such a message:
`# s, squash <commit> = use commit, but meld into previous commit`. Perhaps I should write meld into then. Or squash with. Anyway, I agree that `squash` is more understandable.

2021-12-14 07:36 UTC, bratpiorka approved these changes
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/714)* status: all files reviewed, 2 unresolved discussions (waiting on @maciekpac)



<!-- Sent from Reviewable.io -->

2021-12-14 10:36 UTC, pbalcer approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/714#-:-MqsW0nd9vYUkW8d_hT-:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @maciekpac)



<!-- Sent from Reviewable.io -->

2021-12-14 13:59 UTC, maciekpac reviewed
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/714)* status: 3 of 21 files reviewed, 2 unresolved discussions (waiting on @bratpiorka, @PatKamin, and @pbalcer)

___
*[examples/fixed_malloc.c, line 30 at r22](https://reviewable.io/reviews/memkind/memkind/714#-MqZQfgeE9uKO5pVJOGq:-MqtARQc2qzeNWIV5nsw:bg8a94i) ([raw file](https://github.com/memkind/memkind/blob/da80a01a1a137a78985c623e8eb7591bda093d2a/examples/fixed_malloc.c#L30)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

PMEM partition?
</blockquote></details>

Changed to create kind on mmapped area
___
*[examples/fixed_malloc.c, line 74 at r22](https://reviewable.io/reviews/memkind/memkind/714#-MqZQluP-BhvtqJfE4zM:-MqtAgwh3P_milZGZqvU:btygp1) ([raw file](https://github.com/memkind/memkind/blob/da80a01a1a137a78985c623e8eb7591bda093d2a/examples/fixed_malloc.c#L74)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

persistent memory?
</blockquote></details>

Changed to 
Hello world from mmapped memory
___
*[man/memkind_fixed.3, line 30 at r16](https://reviewable.io/reviews/memkind/memkind/714#-MqYwExO9u-yg9mWeb5L:-MqtESWUA3VUbpd10Kv7:bb6un1j) ([raw file](https://github.com/memkind/memkind/blob/155f633da2128a3b97def2190a958dbc6d9848d1/man/memkind_fixed.3#L30)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

It's not described in the memkind(3) manual. Please, add it.
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2021-12-14 14:10 UTC, bratpiorka approved these changes
> Reviewed 18 of 18 files at r23, 4 of 4 files at r24, 8 of 8 files at r25, 5 of 5 files at r26, 7 of 7 files at r27, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/714)* status: all files reviewed, 2 unresolved discussions (waiting on @PatKamin)



<!-- Sent from Reviewable.io -->

2021-12-14 14:39 UTC, PatKamin requested changes
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/714)* status: 4 of 21 files reviewed, 3 unresolved discussions (waiting on @bratpiorka, @maciekpac, and @PatKamin)

___
*[include/memkind.h, line 534 at r27](https://reviewable.io/reviews/memkind/memkind/714#-MqtI0AG31Ky3x9ceJZ5:-MqtI0AG31Ky3x9ceJZ6:b3gbhlt) ([raw file](https://github.com/memkind/memkind/blob/bb71b3ebfa732be590de148aa5585fbb3edc7cee/include/memkind.h#L534)):*
> ```objc
> /// \return Capacity on nodes from which a given kind could allocate
> ///         (file size or filesystem capacity in case of a file-backed PMEM
> ///         kind; memory area size for fixed kind) in bytes on success, -1
> ```

Please, add a test for using this kind in memkind_get_capacity() function.
___
*[man/memkind.3, line 464 at r27](https://reviewable.io/reviews/memkind/memkind/714#-MqtIMuS1dcPbisoNA_y:-MqtIMuS1dcPbisoNA_z:b8b75ey) ([raw file](https://github.com/memkind/memkind/blob/bb71b3ebfa732be590de148aa5585fbb3edc7cee/man/memkind.3#L464)):*
> ```Roff
> is a function used to create a kind under user-specified area of memory. The
> memory can be allocated in any possible way, e.g. it might be a static array
> or an mmap-ed area. User can specify any properties using functions
> ```

nit: `mmap-ed` -> `mmaped`


<!-- Sent from Reviewable.io -->

2021-12-14 14:40 UTC, PatKamin reviewed
> Reviewed 1 of 17 files at r28, 3 of 16 files at r29, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/714)* status: 8 of 21 files reviewed, 2 unresolved discussions (waiting on @bratpiorka and @maciekpac)



<!-- Sent from Reviewable.io -->

2021-12-14 15:28 UTC, maciekpac reviewed
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/714)* status: 8 of 21 files reviewed, 2 unresolved discussions (waiting on @bratpiorka, @maciekpac, and @PatKamin)

___
*[man/memkind.3, line 464 at r27](https://reviewable.io/reviews/memkind/memkind/714#-MqtIMuS1dcPbisoNA_y:-MqtWV3sCV9bnL7_MNie:b6k2vb1) ([raw file](https://github.com/memkind/memkind/blob/bb71b3ebfa732be590de148aa5585fbb3edc7cee/man/memkind.3#L464)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

nit: `mmap-ed` -> `mmaped`
</blockquote></details>

Actually, the correct version (most often used in linux kernel and on glibc man pages) seems to be  *mmapped* with double p, but without any other punctuation. For reference:https://github.com/torvalds/linux/search?q=mmapped

As a fun side note, all three versions (and others like mmap'ed) are used in the kernel, I guess there is no common consensus around that.


<!-- Sent from Reviewable.io -->

2021-12-14 16:28 UTC, maciekpac reviewed
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/714)* status: 8 of 22 files reviewed, 2 unresolved discussions (waiting on @bratpiorka, @PatKamin, and @pbalcer)

___
*[include/memkind.h, line 534 at r27](https://reviewable.io/reviews/memkind/memkind/714#-MqtI0AG31Ky3x9ceJZ5:-MqtlM1D84oNw7f5ognQ:b-mka63p) ([raw file](https://github.com/memkind/memkind/blob/bb71b3ebfa732be590de148aa5585fbb3edc7cee/include/memkind.h#L534)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Please, add a test for using this kind in memkind_get_capacity() function.
</blockquote></details>

As requested, a new test was added.


<!-- Sent from Reviewable.io -->

2021-12-15 06:40 UTC, PatKamin reviewed
> Reviewed 1 of 19 files at r17, 2 of 16 files at r29, 1 of 2 files at r30, 1 of 1 files at r31, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/714)* status: 12 of 22 files reviewed, all discussions resolved (waiting on @bratpiorka)



<!-- Sent from Reviewable.io -->

2021-12-15 07:46 UTC, bratpiorka approved these changes
> Reviewed 1 of 17 files at r28, 15 of 16 files at r29, 1 of 2 files at r30, 1 of 1 files at r31, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/714)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @maciekpac)



<!-- Sent from Reviewable.io -->

2021-12-15 09:00 UTC, PatKamin approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/714#-:-MqxJbCB3vb3p8zJPa0K:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @maciekpac)



<!-- Sent from Reviewable.io -->

2021-12-15 09:02 UTC, merged