A wrapper for common uses of memory tiering.
memkind/memkind pull request #718
Opened 2021-12-21 12:02 UTC by kilobyte

Supports only KMEM_DAX, but there's no real reason to use FS_DAX anymore.

2021-12-21 12:12 UTC, bratpiorka requested changes
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/718)* status: all files reviewed, 10 unresolved discussions (waiting on @kilobyte)

___
*[utils/memtier/memtier.c, line 42 at r1](https://reviewable.io/reviews/memkind/memkind/718#-MrRsxgLClaFcUbMhgb0:-MrRsxgLClaFcUbMhgb1:b-kdnbak) ([raw file](https://github.com/memkind/memkind/blob/9d35d22d356172a9078997d9fae98c2fc09e7a01/utils/memtier/memtier.c#L42)):*
> ```C
>     bool noratio = true;
>     const char *thresh = 0;
>     bool verbose = true; // TODO: flip to false
> ```

decide on verbosity level and remove this TODO
___
*[utils/memtier/memtier.c, line 52 at r1](https://reviewable.io/reviews/memkind/memkind/718#-MrRt7Hc-cuRLIHmvgtZ:-MrRt7Hc-cuRLIHmvgt_:b52qzoh) ([raw file](https://github.com/memkind/memkind/blob/9d35d22d356172a9078997d9fae98c2fc09e7a01/utils/memtier/memtier.c#L52)):*
> ```C
>             break;
>         }
>         if (!strcmp(argv[a], "-r") || !strcmp(argv[a], "--ratio")) { // TODO: -r1:3
> ```

what about this TODO?
___
*[utils/memtier/memtier.c, line 58 at r1](https://reviewable.io/reviews/memkind/memkind/718#-MrRu40FEUF4ol2J7CFk:-MrRu40FEUF4ol2J7CFl:biewjed) ([raw file](https://github.com/memkind/memkind/blob/9d35d22d356172a9078997d9fae98c2fc09e7a01/utils/memtier/memtier.c#L58)):*
> ```C
>             ratio[0] = strtoul(argv[a++], &br, 0);
>             if (*br != ':')
>                 die(PN": --ratio must have a colon.\n");
> ```

.. between values
___
*[utils/memtier/memtier.c, line 66 at r1](https://reviewable.io/reviews/memkind/memkind/718#-MrRu09B2pQSgjBNWVIa:-MrRu09B2pQSgjBNWVIb:b-80z19o) ([raw file](https://github.com/memkind/memkind/blob/9d35d22d356172a9078997d9fae98c2fc09e7a01/utils/memtier/memtier.c#L66)):*
> ```C
>             if (++a >= argc)
>                 die(PN": --threshold requires an argument.\n");
>             thresh = argv[a++]; // TODO: validate?
> ```

TODO?
___
*[utils/memtier/memtier.c, line 69 at r1](https://reviewable.io/reviews/memkind/memkind/718#-MrRtBsK0jykFdAJB9c8:-MrRtBsK0jykFdAJB9c9:bxajiyj) ([raw file](https://github.com/memkind/memkind/blob/9d35d22d356172a9078997d9fae98c2fc09e7a01/utils/memtier/memtier.c#L69)):*
> ```C
>         } else if (!strcmp(argv[a], "-v") || !strcmp(argv[a], "--verbose"))
>             ++a, verbose = true;
>         else
> ```

no --help
___
*[utils/memtier/memtier.c, line 85 at r1](https://reviewable.io/reviews/memkind/memkind/718#-MrRtEQ16IKrOZ9lX_Sy:-MrRtEQ16IKrOZ9lX_Sz:btpy8j6) ([raw file](https://github.com/memkind/memkind/blob/9d35d22d356172a9078997d9fae98c2fc09e7a01/utils/memtier/memtier.c#L85)):*
> ```C
> 
>     if (!ratio[0] && !ratio[1])
>         die(PN": no ratio → no memory → can't run stuff.\n");
> ```

improve this message
___
*[utils/memtier/memtier.c, line 91 at r1](https://reviewable.io/reviews/memkind/memkind/718#-MrRtHYs8E2MiGOhUMor:-MrRtHYs8E2MiGOhUMos:btpy8j6) ([raw file](https://github.com/memkind/memkind/blob/9d35d22d356172a9078997d9fae98c2fc09e7a01/utils/memtier/memtier.c#L91)):*
> ```C
> 
>     if (a >= argc)
>         die(PN": what program to run?\n");
> ```

improve this message
___
*[utils/memtier/memtier.c, line 107 at r1](https://reviewable.io/reviews/memkind/memkind/718#-MrRtjeVCfbiCS7r7qtE:-MrRtjeVCfbiCS7r7qtF:b-ctbdth) ([raw file](https://github.com/memkind/memkind/blob/9d35d22d356172a9078997d9fae98c2fc09e7a01/utils/memtier/memtier.c#L107)):*
> ```C
>     putenv(env);
> 
>     if (!ratio[1]) // DRAM only -- kind of pointless
> ```

remove "-- kind of pointless"
___
*[utils/memtier/memtier.c, line 109 at r1](https://reviewable.io/reviews/memkind/memkind/718#-MrRtp_NEAZKa3sgUiaM:-MrRtp_NEAZKa3sgUiaN:b7pdpfh) ([raw file](https://github.com/memkind/memkind/blob/9d35d22d356172a9078997d9fae98c2fc09e7a01/utils/memtier/memtier.c#L109)):*
> ```C
>     if (!ratio[1]) // DRAM only -- kind of pointless
>         putenv("MEMKIND_MEM_TIERS=KIND:DRAM,RATIO:1;POLICY:STATIC_RATIO");
>     else if (!ratio[0]) // PMEM only -- as vmmalloc
> ```

remove "-- as vmalloc"
___
*[utils/memtier/memtier.c~, line 1 at r1](https://reviewable.io/reviews/memkind/memkind/718#-MrRsuD1Daa2VdvHW5dT:-MrRsuD1Daa2VdvHW5dU:b-mu4n2x) ([raw file](https://github.com/memkind/memkind/blob/9d35d22d356172a9078997d9fae98c2fc09e7a01/utils/memtier/memtier.c~#L1)):*
> ```
> #include <stdarg.h>
> ```

remove this file


<!-- Sent from Reviewable.io -->

2021-12-21 13:03 UTC, PatKamin requested changes
> Reviewed 3 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/718)* status: all files reviewed, 19 unresolved discussions (waiting on @kilobyte)

___
*[utils/memtier/Makefile.mk~, line 1 at r1](https://reviewable.io/reviews/memkind/memkind/718#-MrRuITM5J7Wbny7SbkE:-MrRuITN6O1-iBamkSND:b7w5yuj) ([raw file](https://github.com/memkind/memkind/blob/9d35d22d356172a9078997d9fae98c2fc09e7a01/utils/memtier/Makefile.mk~#L1)):*
> ```
> # SPDX-License-Identifier: BSD-2-Clause
> ```

Temp file? Remove it.
___
*[utils/memtier/memtier.c, line 7 at r1](https://reviewable.io/reviews/memkind/memkind/718#-MrRuhow2h9NKfmdHNQ5:-MrRuhow2h9NKfmdHNQ6:b-tahy47) ([raw file](https://github.com/memkind/memkind/blob/9d35d22d356172a9078997d9fae98c2fc09e7a01/utils/memtier/memtier.c#L7)):*
> ```C
> #include <string.h>
> #include <unistd.h>
> #include <memkind.h>
> ```

nit: Split standard library headers from memkind one with an empty line.
___
*[utils/memtier/memtier.c, line 20 at r1](https://reviewable.io/reviews/memkind/memkind/718#-MrRwThW9IaW5d0L7iF-:-MrRwThW9IaW5d0L7iF0:bbfbb0v) ([raw file](https://github.com/memkind/memkind/blob/9d35d22d356172a9078997d9fae98c2fc09e7a01/utils/memtier/memtier.c#L20)):*
> ```C
>     int len = vsnprintf(buf, sizeof(buf), fmt, args);
>     va_end(args);
>     if (write(2, buf, len)) ;
> ```

Please, provide a variable `stderr`. Don't introduce a magic number.
___
*[utils/memtier/memtier.c, line 24 at r1](https://reviewable.io/reviews/memkind/memkind/718#-MrS-TY848cv5rDuNtYG:-MrS-TY848cv5rDuNtYH:bqh12z8) ([raw file](https://github.com/memkind/memkind/blob/9d35d22d356172a9078997d9fae98c2fc09e7a01/utils/memtier/memtier.c#L24)):*
> ```C
> }
> 
> static size_t gcd(size_t x, size_t y)
> ```

Please, extend the name of this function so that there would be no need for reading the function implementation to know what it's doing.
___
*[utils/memtier/memtier.c, line 74 at r1](https://reviewable.io/reviews/memkind/memkind/718#-MrS0Q6cA2xsPrJm-BOp:-MrS0Q6cA2xsPrJm-BOq:b-1grnx7) ([raw file](https://github.com/memkind/memkind/blob/9d35d22d356172a9078997d9fae98c2fc09e7a01/utils/memtier/memtier.c#L74)):*
> ```C
> 
>     if (noratio) {
>         ssize_t dram = memkind_get_capacity(MEMKIND_DEFAULT);
> ```

You will get the whole capacity of DRAM+PMEM here. Given the name of the variable I'm not sure that this is what you want to get. Try `MEMKIND_REGULAR`.
___
*[utils/memtier/memtier.c, line 78 at r1](https://reviewable.io/reviews/memkind/memkind/718#-MrS-GMT3O_8wXLc6gmu:-MrS-GMT3O_8wXLc6gmv:b-x9yntj) ([raw file](https://github.com/memkind/memkind/blob/9d35d22d356172a9078997d9fae98c2fc09e7a01/utils/memtier/memtier.c#L78)):*
> ```C
>         if (pmem == -1) // explicit ratio of 0 is ok, implicit suggests an error
>             die(PN": there appears to be no KMEM_DAX devices installed in this system.\n");
>         size_t d = gcd(dram, pmem);
> ```

`d` -> `greatest common divisor` ?
___
*[utils/memtier/memtier.c, line 94 at r1](https://reviewable.io/reviews/memkind/memkind/718#-MrS1c6L6hSEwFJ7QnIh:-MrS1c6L6hSEwFJ7QnIi:b-bq44kx) ([raw file](https://github.com/memkind/memkind/blob/9d35d22d356172a9078997d9fae98c2fc09e7a01/utils/memtier/memtier.c#L94)):*
> ```C
> 
>     char lib[4096];
>     // If our tool is not properly installed, assume the library lives in same dir.
> ```

nit: the same
___
*[utils/memtier/memtier.c, line 100 at r1](https://reviewable.io/reviews/memkind/memkind/718#-MrS2sJy68rpg90WhLOo:-MrS2sJy68rpg90WhLOp:b9ycm51) ([raw file](https://github.com/memkind/memkind/blob/9d35d22d356172a9078997d9fae98c2fc09e7a01/utils/memtier/memtier.c#L100)):*
> ```C
>     else
>         strcpy(lib, "libmemtier.so");
>     char *env = getenv("LD_PRELOAD");
> ```

Use secure_getenv, if possible: https://github.com/memkind/memkind/blob/78351aa8af14dfb681c0d0701ce6e4ded967b4ae/tiering/memtier_log.c#L22-L29
___
*[utils/memtier/memtier.c, line 129 at r1](https://reviewable.io/reviews/memkind/memkind/718#-MrS3dpN86OIxCjnoiOz:-MrS3dpN86OIxCjnoiP-:b-xtjfdj) ([raw file](https://github.com/memkind/memkind/blob/9d35d22d356172a9078997d9fae98c2fc09e7a01/utils/memtier/memtier.c#L129)):*
> ```C
> 
>     execvpe(argv[a], argv + a, environ);
>     die(PN": couldn't exec ｢%s｣: %m\n", argv[a]);
> ```

Please, provide tests for running this binary with different parameters, especially different ratios.


<!-- Sent from Reviewable.io -->

2021-12-21 15:35 UTC, maciekpac requested changes
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/718)* status: 3 of 6 files reviewed, 30 unresolved discussions (waiting on @bratpiorka, @kilobyte, and @PatKamin)

___
*[utils/memtier/memtier.c, line 20 at r1](https://reviewable.io/reviews/memkind/memkind/718#-MrRwThW9IaW5d0L7iF-:-MrSNJQg-DZeowp5udmS:b-ra3e2d) ([raw file](https://github.com/memkind/memkind/blob/9d35d22d356172a9078997d9fae98c2fc09e7a01/utils/memtier/memtier.c#L20)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Please, provide a variable `stderr`. Don't introduce a magic number.
</blockquote></details>

Besides, using exit gives me shivers. I think it would be best to
___
*[utils/memtier/memtier.c, line 24 at r1](https://reviewable.io/reviews/memkind/memkind/718#-MrS-TY848cv5rDuNtYG:-MrSNt0f5Fm9Vwkz4Uwk:b-s5zksv) ([raw file](https://github.com/memkind/memkind/blob/9d35d22d356172a9078997d9fae98c2fc09e7a01/utils/memtier/memtier.c#L24)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Please, extend the name of this function so that there would be no need for reading the function implementation to know what it's doing.
</blockquote></details>

I think it stands for "greatest common divisor", which is quite a common acronym, but I agree
___
*[utils/memtier/memtier.c, line 26 at r1](https://reviewable.io/reviews/memkind/memkind/718#-MrSRKd3Aay3mzODRf3w:-MrSRKd3Aay3mzODRf3x:b-cif9ju) ([raw file](https://github.com/memkind/memkind/blob/9d35d22d356172a9078997d9fae98c2fc09e7a01/utils/memtier/memtier.c#L26)):*
> ```C
> static size_t gcd(size_t x, size_t y)
> {
>     while (x && y)
> ```

Does this function actually work as it is supposed to be? Has it been tested? I'm actually not sure about its purpose, at this point... Is it really about greatest common divisor?
___
*[utils/memtier/memtier.c, line 35 at r1](https://reviewable.io/reviews/memkind/memkind/718#-MrSO9nHCZrXvhl0tHo5:-MrSO9nHCZrXvhl0tHo6:b-t44zde) ([raw file](https://github.com/memkind/memkind/blob/9d35d22d356172a9078997d9fae98c2fc09e7a01/utils/memtier/memtier.c#L35)):*
> ```C
> }
> 
> #define dprintf(...) if (verbose) fprintf(stderr, __VA_ARGS__)
> ```

Please use do {} while in macros. Putting the current macro inside such statement:

if (foo)
    dprintf("bar");
else
     foo = true;

would cause behavior that I don't think the author would expect. 
___
*[utils/memtier/memtier.c, line 42 at r1](https://reviewable.io/reviews/memkind/memkind/718#-MrRsxgLClaFcUbMhgb0:-MrSSrok7FqRJ31dydwP:bwsaneu) ([raw file](https://github.com/memkind/memkind/blob/9d35d22d356172a9078997d9fae98c2fc09e7a01/utils/memtier/memtier.c#L42)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

decide on verbosity level and remove this TODO
</blockquote></details>

I think this was just a temporary value - we can set verbose from args, but we cannot reset - it looks like false is the only default value that makes sense here.
___
*[utils/memtier/memtier.c, line 45 at r1](https://reviewable.io/reviews/memkind/memkind/718#-MrSQERR2oI79Je_wGXI:-MrSQERR2oI79Je_wGXJ:bz3ac31) ([raw file](https://github.com/memkind/memkind/blob/9d35d22d356172a9078997d9fae98c2fc09e7a01/utils/memtier/memtier.c#L45)):*
> ```C
> 
>     int a = 1;
>     while (a < argc) {
> ```

I think that a general comment about what arguments are expected would be great. Do we have some "display_help" function or sth like that?
___
*[utils/memtier/memtier.c, line 48 at r1](https://reviewable.io/reviews/memkind/memkind/718#-MrSPIE23sjDXygEFl1x:-MrSPIE23sjDXygEFl1y:b-65dulm) ([raw file](https://github.com/memkind/memkind/blob/9d35d22d356172a9078997d9fae98c2fc09e7a01/utils/memtier/memtier.c#L48)):*
> ```C
>         if (argv[a][0] != '-')
>             break;
>         if (!strcmp(argv[a], "--")) {
> ```

Could you please compare with zero? When strings match, a zero is returned, which is implicitly converted to "false" - I understand how your code works, but I think using "!" to denote a case when strings actually match is not the clearest thing to do.
___
*[utils/memtier/memtier.c, line 52 at r1](https://reviewable.io/reviews/memkind/memkind/718#-MrSPi9R2w5Wuxv3HNik:-MrSPi9R2w5Wuxv3HNil:b-5tawsa) ([raw file](https://github.com/memkind/memkind/blob/9d35d22d356172a9078997d9fae98c2fc09e7a01/utils/memtier/memtier.c#L52)):*
> ```C
>             break;
>         }
>         if (!strcmp(argv[a], "-r") || !strcmp(argv[a], "--ratio")) { // TODO: -r1:3
> ```

Will the program ever reach this place with argv[a] equal "--ratio" ? As I understand it, "--ratio" would match "--" 3 lines above and the program would exit from the while loop without ever reaching this place. Have you tested it?
___
*[utils/memtier/memtier.c, line 61 at r1](https://reviewable.io/reviews/memkind/memkind/718#-MrSTje83ffbsle69JGI:-MrSTje83ffbsle69JGJ:bwhrvxr) ([raw file](https://github.com/memkind/memkind/blob/9d35d22d356172a9078997d9fae98c2fc09e7a01/utils/memtier/memtier.c#L61)):*
> ```C
>             ratio[1] = strtoul(++br, &br, 0);
>             if (*br)
>                 die(PN": --ratio must have exactly two values in this version of memtier.\n");
> ```

I think all calls to "die" contain the "memkind" (PN) prefix, maybe this could be moved inside the "die" function?
___
*[utils/memtier/memtier.c, line 69 at r1](https://reviewable.io/reviews/memkind/memkind/718#-MrRtBsK0jykFdAJB9c8:-MrSUHSVB16YCxxefIh6:b32w74) ([raw file](https://github.com/memkind/memkind/blob/9d35d22d356172a9078997d9fae98c2fc09e7a01/utils/memtier/memtier.c#L69)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

no --help
</blockquote></details>

Up
___
*[utils/memtier/memtier.c, line 78 at r1](https://reviewable.io/reviews/memkind/memkind/718#-MrS-GMT3O_8wXLc6gmu:-MrSUYcVCjkIHyPdfBgS:bnaxrjm) ([raw file](https://github.com/memkind/memkind/blob/9d35d22d356172a9078997d9fae98c2fc09e7a01/utils/memtier/memtier.c#L78)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

`d` -> `greatest common divisor` ?
</blockquote></details>

Does the function work correctly?

Btw, calling this function with dram/pmem equal to zero would result in division by zero, was it explicitly checked?
___
*[utils/memtier/memtier.c, line 79 at r1](https://reviewable.io/reviews/memkind/memkind/718#-MrSVAdx2FlAukRd74Np:-MrSVAdy37zyvJTJIiOs:b-glkv21) ([raw file](https://github.com/memkind/memkind/blob/9d35d22d356172a9078997d9fae98c2fc09e7a01/utils/memtier/memtier.c#L79)):*
> ```C
>             die(PN": there appears to be no KMEM_DAX devices installed in this system.\n");
>         size_t d = gcd(dram, pmem);
>         ratio[0] = dram / d;
> ```

If the whole gcd operation was here only to scale ratios, do we really need it? Aren't ratios like 2:4 correctly handled by memkind?
___
*[utils/memtier/memtier.c, line 85 at r1](https://reviewable.io/reviews/memkind/memkind/718#-MrSVcL29b4k7UpW12fU:-MrSVcL29b4k7UpW12fV:b-o9kzfi) ([raw file](https://github.com/memkind/memkind/blob/9d35d22d356172a9078997d9fae98c2fc09e7a01/utils/memtier/memtier.c#L85)):*
> ```C
> 
>     if (!ratio[0] && !ratio[1])
>         die(PN": no ratio → no memory → can't run stuff.\n");
> ```

Do we correctly handle a case with pmem ratio equal 0 ? I remember some segfaults, I think that as long as this is not corrected we should block not only 0:0 ratio, but also 1:0 or 0:1, unless they are explicitly checked/handled (e.g. by propagating to only-dram).

EDIT: I can see the message below, we are already blocking it, but in this case does wrapper handle only-dram case?
___
*[utils/memtier/memtier.c, line 88 at r1](https://reviewable.io/reviews/memkind/memkind/718#-MrSWSGEDnS1jWaDK156:-MrSWSGEDnS1jWaDK157:b-atg8wj) ([raw file](https://github.com/memkind/memkind/blob/9d35d22d356172a9078997d9fae98c2fc09e7a01/utils/memtier/memtier.c#L88)):*
> ```C
> 
>     if (thresh && (!ratio[0] || !ratio[1]))
>   [...]

2021-12-21 16:40 UTC, kilobyte reviewed
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/718)* status: 3 of 6 files reviewed, 29 unresolved discussions (waiting on @bratpiorka, @kilobyte, @maciekpac, and @PatKamin)

___
*[utils/memtier/memtier.c, line 42 at r1](https://reviewable.io/reviews/memkind/memkind/718#-MrRsxgLClaFcUbMhgb0:-MrSeMtx8wKnFUkKTp3f:bdc64h4) ([raw file](https://github.com/memkind/memkind/blob/9d35d22d356172a9078997d9fae98c2fc09e7a01/utils/memtier/memtier.c#L42)):*
<details><summary><i>Previously, maciekpac wrote…</i></summary><blockquote>

I think this was just a temporary value - we can set verbose from args, but we cannot reset - it looks like false is the only default value that makes sense here.
</blockquote></details>

Well, this is a *draft* pull request, meant to test unpolished stuff. :)
I prioritized ease of debugging, leaving the TODO marker to not forget fixing it.
But if you insist to flip it immediately... done.
___
*[utils/memtier/memtier.c, line 45 at r1](https://reviewable.io/reviews/memkind/memkind/718#-MrSQERR2oI79Je_wGXI:-MrSmFts-_spG0VY7X-N:b-a7bx6n) ([raw file](https://github.com/memkind/memkind/blob/9d35d22d356172a9078997d9fae98c2fc09e7a01/utils/memtier/memtier.c#L45)):*
<details><summary><i>Previously, maciekpac wrote…</i></summary><blockquote>

I think that a general comment about what arguments are expected would be great. Do we have some "display_help" function or sth like that?
</blockquote></details>

I've added `--help`.
___
*[utils/memtier/memtier.c, line 52 at r1](https://reviewable.io/reviews/memkind/memkind/718#-MrSPi9R2w5Wuxv3HNik:-MrShL2z00g5ddMIclCn:b3ki0jc) ([raw file](https://github.com/memkind/memkind/blob/9d35d22d356172a9078997d9fae98c2fc09e7a01/utils/memtier/memtier.c#L52)):*
<details><summary><i>Previously, maciekpac wrote…</i></summary><blockquote>

Will the program ever reach this place with argv[a] equal "--ratio" ? As I understand it, "--ratio" would match "--" 3 lines above and the program would exit from the while loop without ever reaching this place. Have you tested it?
</blockquote></details>

It works, why wouldn't it?
___
*[utils/memtier/memtier.c, line 61 at r1](https://reviewable.io/reviews/memkind/memkind/718#-MrSTje83ffbsle69JGI:-MrShVS94wNAXJn9l8Gy:b-9ii4ue) ([raw file](https://github.com/memkind/memkind/blob/9d35d22d356172a9078997d9fae98c2fc09e7a01/utils/memtier/memtier.c#L61)):*
<details><summary><i>Previously, maciekpac wrote…</i></summary><blockquote>

I think all calls to "die" contain the "memkind" (PN) prefix, maybe this could be moved inside the "die" function?
</blockquote></details>

Not always at the start, eg. "Usage:".
___
*[utils/memtier/memtier.c, line 69 at r1](https://reviewable.io/reviews/memkind/memkind/718#-MrRtBsK0jykFdAJB9c8:-MrSmBSk6AMe0JLqS_G7:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/9d35d22d356172a9078997d9fae98c2fc09e7a01/utils/memtier/memtier.c#L69)):*
<details><summary><i>Previously, maciekpac wrote…</i></summary><blockquote>

Up
</blockquote></details>

Done.
___
*[utils/memtier/memtier.c, line 78 at r1](https://reviewable.io/reviews/memkind/memkind/718#-MrS-GMT3O_8wXLc6gmu:-MrSmfcl27HoKYW0vdw9:b-hsqequ) ([raw file](https://github.com/memkind/memkind/blob/9d35d22d356172a9078997d9fae98c2fc09e7a01/utils/memtier/memtier.c#L78)):*
<details><summary><i>Previously, maciekpac wrote…</i></summary><blockquote>

Does the function work correctly?

Btw, calling this function with dram/pmem equal to zero would result in division by zero, was it explicitly checked?
</blockquote></details>

You can't get here without at least one kind of memory above 0.
___
*[utils/memtier/memtier.c, line 79 at r1](https://reviewable.io/reviews/memkind/memkind/718#-MrSVAdx2FlAukRd74Np:-MrSnz5O3dVwLOew_VEL:bnfxw2e) ([raw file](https://github.com/memkind/memkind/blob/9d35d22d356172a9078997d9fae98c2fc09e7a01/utils/memtier/memtier.c#L79)):*
<details><summary><i>Previously, maciekpac wrote…</i></summary><blockquote>

If the whole gcd operation was here only to scale ratios, do we really need it? Aren't ratios like 2:4 correctly handled by memkind?
</blockquote></details>

They are, but ratios 2147483648:4294967296 are not.  That's why I'm reducing them, both for human readability and to avoid 31-bit ints inside memkind.
___
*[utils/memtier/memtier.c, line 85 at r1](https://reviewable.io/reviews/memkind/memkind/718#-MrRtEQ16IKrOZ9lX_Sy:-MrSp54LDlGxddahQTGa:bgief31) ([raw file](https://github.com/memkind/memkind/blob/9d35d22d356172a9078997d9fae98c2fc09e7a01/utils/memtier/memtier.c#L85)):*
<details><summary><i>Previously, kilobyte (Adam Borowski) wrote…</i></summary><blockquote>

can you suggest an appropriate division by zero joke? 😜
</blockquote></details>

Is this good enough?
___
*[utils/memtier/memtier.c, line 85 at r1](https://reviewable.io/reviews/memkind/memkind/718#-MrSVcL29b4k7UpW12fU:-MrSp9kb--Lrd0FeOJ4x:bwoa8bf) ([raw file](https://github.com/memkind/memkind/blob/9d35d22d356172a9078997d9fae98c2fc09e7a01/utils/memtier/memtier.c#L85)):*
<details><summary><i>Previously, maciekpac wrote…</i></summary><blockquote>

Do we correctly handle a case with pmem ratio equal 0 ? I remember some segfaults, I think that as long as this is not corrected we should block not only 0:0 ratio, but also 1:0 or 0:1, unless they are explicitly checked/handled (e.g. by propagating to only-dram).

EDIT: I can see the message below, we are already blocking it, but in this case does wrapper handle only-dram case?
</blockquote></details>

Ratios of 0 cause the given tier to be disabled: 1:0 is effectively a no-op, 0:1 does what old vmmalloc did.

The wrapper accepts dram-only case specified by the user, refuses it when autodetected.
___
*[utils/memtier/memtier.c, line 88 at r1](https://reviewable.io/reviews/memkind/memkind/718#-MrSWSGEDnS1jWaDK156:-MrSpkrPCt5XDHsn3jnn:bakyz2y) ([raw file](https://github.com/memkind/memkind/blob/9d35d22d356172a9078997d9fae98c2fc09e7a01/utils/memtier/memtier.c#L88)):*
<details><summary><i>Previously, maciekpac wrote…</i></summary><blockquote>

This would also be displayed if user explicitly specifies "0", is that correct? In that case, the message could be better.
</blockquote></details>

I've added "enabled", is this better?
___
*[utils/memtier/memtier.c, line 93 at r1](https://reviewable.io/reviews/memkind/memkind/718#-MrSaX7u-w8HQymyd0NQ:-MrSq_BnEOIMy-luW1m-:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/9d35d22d356172a9078997d9fae98c2fc09e7a01/utils/memtier/memtier.c#L93)):*
<details><summary><i>Previously, maciekpac wrote…</i></summary><blockquote>

Maybe some more descriptive name, like memtier_lib_path ?
</blockquote></details>

Done.
___
*[utils/memtier/memtier.c, line 94 at r1](https://reviewable.io/reviews/memkind/memkind/718#-MrS1c6L6hSEwFJ7QnIh:-MrSq5nnAJ-f0EoRXEji:b3sfi) ([raw file](https://github.com/memkind/memkind/blob/9d35d22d356172a9078997d9fae98c2fc09e7a01/utils/memtier/memtier.c#L94)):*
<details><summary><i>Previously, maciekpac wrote…</i></summary><blockquote>

I think it's about grammar error: "If our tool is not properly installed, assume the library lives in *THE* same dir."
</blockquote></details>

✓
___
*[utils/memtier/memtier.c, line 129 at r1](https://reviewable.io/reviews/memkind/memkind/718#-MrSb_DvCx-Vg8tVe_6_:-MrSqNX07ahrZzqPc6xn:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/9d35d22d356172a9078997d9fae98c2fc09e7a01/utils/memtier/memtier.c#L129)):*
<details><summary><i>Previously, maciekpac wrote…</i></summary><blockquote>

Maybe a short comment about execvpe?

Upon correct execution, current process is replaced and the line below is never called. I think this behavior is quite "special" and a short comment would be welcome.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-12-21 16:57 UTC, kilobyte reviewed
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/718)* status: 3 of 6 files reviewed, 29 unresolved discussions (waiting on @bratpiorka, @kilobyte, @maciekpac, and @PatKamin)

___
*[utils/memtier/memtier.c, line 26 at r1](https://reviewable.io/reviews/memkind/memkind/718#-MrSRKd3Aay3mzODRf3w:-MrSsGPYDwrLtScmRMSv:bijt797) ([raw file](https://github.com/memkind/memkind/blob/9d35d22d356172a9078997d9fae98c2fc09e7a01/utils/memtier/memtier.c#L26)):*
<details><summary><i>Previously, maciekpac wrote…</i></summary><blockquote>

Does this function actually work as it is supposed to be? Has it been tested? I'm actually not sure about its purpose, at this point... Is it really about greatest common divisor?
</blockquote></details>

Could you give me an example where it fails?
___
*[utils/memtier/memtier.c, line 35 at r1](https://reviewable.io/reviews/memkind/memkind/718#-MrSO9nHCZrXvhl0tHo5:-MrSsfG2CSYrxN0H1A8H:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/9d35d22d356172a9078997d9fae98c2fc09e7a01/utils/memtier/memtier.c#L35)):*
<details><summary><i>Previously, maciekpac wrote…</i></summary><blockquote>

Please use do {} while in macros. Putting the current macro inside such statement:

if (foo)
    dprintf("bar");
else
     foo = true;

would cause behavior that I don't think the author would expect. 
</blockquote></details>

Done.
___
*[utils/memtier/memtier.c, line 66 at r1](https://reviewable.io/reviews/memkind/memkind/718#-MrRu09B2pQSgjBNWVIa:-MrSsiojAj6QYDhDhbra:b-85p34e) ([raw file](https://github.com/memkind/memkind/blob/9d35d22d356172a9078997d9fae98c2fc09e7a01/utils/memtier/memtier.c#L66)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

TODO?
</blockquote></details>

The config is then parsed by the library inside and validated, making this TODO not urgent.  On the other hand, if we'd want a more user friendly syntax, then the argument would need to be parsed.
___
*[utils/memtier/memtier.c, line 97 at r1](https://reviewable.io/reviews/memkind/memkind/718#-MrSXOxx-Y6_5rOiyi0q:-MrSt9buANtk3AufYtPo:b-f781w9) ([raw file](https://github.com/memkind/memkind/blob/9d35d22d356172a9078997d9fae98c2fc09e7a01/utils/memtier/memtier.c#L97)):*
<details><summary><i>Previously, maciekpac wrote…</i></summary><blockquote>

I don't think this is readable. It took me way too long to understand the five lines given that the logic here is really simple. Besides, I think we can use a single if statement here:

const char *self_name = argv[0]; // optional, but seems more readable to me - maybe a different name would be better?

if (strncmp(...)) { // program installed in "/usr" directory
    size_t last_slash_offset = strrchr(self_name , '/') - self_name ;
    snprintf(lib, sizeof(lib), "%.*s/libmemtier.so", (int)last_slash_offset, self_name);
} else {
    strcpy(...)
}
</blockquote></details>

That doesn't work -- strrchr() may return zero.


<!-- Sent from Reviewable.io -->

2021-12-21 18:15 UTC, maciekpac requested changes
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/718)* status: 3 of 6 files reviewed, 27 unresolved discussions (waiting on @bratpiorka, @kilobyte, @maciekpac, and @PatKamin)

___
*[utils/memtier/memtier.c, line 26 at r1](https://reviewable.io/reviews/memkind/memkind/718#-MrSRKd3Aay3mzODRf3w:-MrT1XU8BLxzFy5ofmJb:buh3563) ([raw file](https://github.com/memkind/memkind/blob/9d35d22d356172a9078997d9fae98c2fc09e7a01/utils/memtier/memtier.c#L26)):*
<details><summary><i>Previously, kilobyte (Adam Borowski) wrote…</i></summary><blockquote>

Could you give me an example where it fails?
</blockquote></details>

I think it's commit author's duty to at least give some rudimentary hint on how the code works and which algorithms have been used, not reviewers. It would really suffice to add a short line like:

// Euclidean algorithm for greatest common divisor

and verification of correctness by a reviewer would take just a few seconds. Also, the code would be easier to maintain and modify.
___
*[utils/memtier/memtier.c, line 42 at r1](https://reviewable.io/reviews/memkind/memkind/718#-MrRsxgLClaFcUbMhgb0:-MrT7YcW-_3b5iR3-KhD:b-9to8bz) ([raw file](https://github.com/memkind/memkind/blob/9d35d22d356172a9078997d9fae98c2fc09e7a01/utils/memtier/memtier.c#L42)):*
<details><summary><i>Previously, kilobyte (Adam Borowski) wrote…</i></summary><blockquote>

Well, this is a *draft* pull request, meant to test unpolished stuff. :)
I prioritized ease of debugging, leaving the TODO marker to not forget fixing it.
But if you insist to flip it immediately... done.
</blockquote></details>

Are we supposed to unblock such "draft" commit ? Give it green light for a merge? I understand that sometimes it might be a good idea to review an unfinished/draft commit, but I thought this changes were supposed to be merged in the next release...
___
*[utils/memtier/memtier.c, line 79 at r1](https://reviewable.io/reviews/memkind/memkind/718#-MrSVAdx2FlAukRd74Np:-MrTA8EEA-y_6piwNfxn:biq4p8k) ([raw file](https://github.com/memkind/memkind/blob/9d35d22d356172a9078997d9fae98c2fc09e7a01/utils/memtier/memtier.c#L79)):*
<details><summary><i>Previously, kilobyte (Adam Borowski) wrote…</i></summary><blockquote>

They are, but ratios 2147483648:4294967296 are not.  That's why I'm reducing them, both for human readability and to avoid 31-bit ints inside memkind.
</blockquote></details>

What if we get two big prime numbers? This should not happen with KMEM_DAX, at least not now, but maybe we should handle such cases? 
___
*[utils/memtier/memtier.c, line 97 at r1](https://reviewable.io/reviews/memkind/memkind/718#-MrSXOxx-Y6_5rOiyi0q:-MrT90jVCXcwu0n8irVW:b-u61f9z) ([raw file](https://github.com/memkind/memkind/blob/9d35d22d356172a9078997d9fae98c2fc09e7a01/utils/memtier/memtier.c#L97)):*
<details><summary><i>Previously, kilobyte (Adam Borowski) wrote…</i></summary><blockquote>

That doesn't work -- strrchr() may return zero.
</blockquote></details>

Return Value
A pointer to the last occurrence of character in str.
If the character is not found, the function returns a null pointer.

Source:

https://www.cplusplus.com/reference/cstring/strrchr/?kw=strrchr

The only case is when character is not found, but the character already exists in the string - please note that strncmp matched "/usr".


<!-- Sent from Reviewable.io -->

2021-12-21 18:16 UTC, maciekpac requested changes
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/718)* status: 3 of 6 files reviewed, 27 unresolved discussions (waiting on @bratpiorka, @kilobyte, @maciekpac, and @PatKamin)

___
*[utils/memtier/memtier.c, line 26 at r1](https://reviewable.io/reviews/memkind/memkind/718#-MrSRKd3Aay3mzODRf3w:-MrTCCKiE-sZZQO5ymur:bz9ohhh) ([raw file](https://github.com/memkind/memkind/blob/9d35d22d356172a9078997d9fae98c2fc09e7a01/utils/memtier/memtier.c#L26)):*
<details><summary><i>Previously, maciekpac wrote…</i></summary><blockquote>

I think it's commit author's duty to at least give some rudimentary hint on how the code works and which algorithms have been used, not reviewers. It would really suffice to add a short line like:

// Euclidean algorithm for greatest common divisor

and verification of correctness by a reviewer would take just a few seconds. Also, the code would be easier to maintain and modify.
</blockquote></details>

You might also add it to the name of the function instead of a comment, but it should be visible somewhere


<!-- Sent from Reviewable.io -->

2021-12-22 06:36 UTC, PatKamin reviewed
> Reviewed 2 of 3 files at r2, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/718)* status: all files reviewed, 25 unresolved discussions (waiting on @bratpiorka, @kilobyte, @maciekpac, and @PatKamin)



<!-- Sent from Reviewable.io -->

2021-12-22 08:43 UTC, bratpiorka approved these changes
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/718)* status: all files reviewed, 14 unresolved discussions (waiting on @kilobyte, @maciekpac, and @PatKamin)



<!-- Sent from Reviewable.io -->

2021-12-22 09:30 UTC, maciekpac requested changes
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/718)* status: all files reviewed, 11 unresolved discussions (waiting on @kilobyte, @maciekpac, and @PatKamin)

___
*[utils/memtier/memtier.c, line 88 at r1](https://reviewable.io/reviews/memkind/memkind/718#-MrSWSGEDnS1jWaDK156:-MrWS-701soV404Oqs4r:b-xwg8se) ([raw file](https://github.com/memkind/memkind/blob/9d35d22d356172a9078997d9fae98c2fc09e7a01/utils/memtier/memtier.c#L88)):*
<details><summary><i>Previously, kilobyte (Adam Borowski) wrote…</i></summary><blockquote>

I've added "enabled", is this better?
</blockquote></details>

"non-zero"?
___
*[utils/memtier/memtier.c, line 118 at r4](https://reviewable.io/reviews/memkind/memkind/718#-MrWTZicEm_TMMdYVAQG:-MrWTZicEm_TMMdYVAQH:bz68d67) ([raw file](https://github.com/memkind/memkind/blob/5a91d0752390c8622582f7d785f23268d1ae9ea0/utils/memtier/memtier.c#L118)):*
> ```C
>     // If our tool is not properly installed, assume the library lives in the
>     // same dir.
>     char *exeslash = strncmp(argv[0], "/usr", 4) ? strrchr(argv[0], '/') : 0;
> ```

What do we want to achieve: if matches, should we return zero or number of characters before last '/' ? Please note that strncmp return zero (false) when strings match, is it really the way you want to handle this case?


<!-- Sent from Reviewable.io -->

2021-12-22 09:58 UTC, kilobyte reviewed
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/718)* status: all files reviewed, 11 unresolved discussions (waiting on @kilobyte, @maciekpac, and @PatKamin)

___
*[utils/memtier/memtier.c, line 97 at r1](https://reviewable.io/reviews/memkind/memkind/718#-MrSXOxx-Y6_5rOiyi0q:-MrWWmKM4mV0k2Qz-_Uu:b-395n8z) ([raw file](https://github.com/memkind/memkind/blob/9d35d22d356172a9078997d9fae98c2fc09e7a01/utils/memtier/memtier.c#L97)):*
<details><summary><i>Previously, maciekpac wrote…</i></summary><blockquote>

Return Value
A pointer to the last occurrence of character in str.
If the character is not found, the function returns a null pointer.

Source:

https://www.cplusplus.com/reference/cstring/strrchr/?kw=strrchr

The only case is when character is not found, but the character already exists in the string - please note that strncmp matched "/usr".
</blockquote></details>

But we don't even care about the path when we're in `/usr` — that'd be wrong as the binary would be `/usr/bin/memtier` library `/usr/lib/x86_64-linux-gnu/libmemtier.so.0` on Debian/glibc, `/usr/lib/x86_64-linux-musl/libmemtier.so.0` on Debian/musl, on Fedora `/usr/libc64/...`, etc.  Thus, we just return `libmemtier.so` which Just Works™.  This code is supposed to handle the case of non-installed library only.


<!-- Sent from Reviewable.io -->

2021-12-22 11:15 UTC, maciekpac requested changes
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/718)* status: all files reviewed, 9 unresolved discussions (waiting on @kilobyte, @maciekpac, and @PatKamin)

___
*[utils/memtier/memtier.c, line 97 at r1](https://reviewable.io/reviews/memkind/memkind/718#-MrSXOxx-Y6_5rOiyi0q:-MrWoJdV18jSaJ6EQX9x:bueou8h) ([raw file](https://github.com/memkind/memkind/blob/9d35d22d356172a9078997d9fae98c2fc09e7a01/utils/memtier/memtier.c#L97)):*
<details><summary><i>Previously, kilobyte (Adam Borowski) wrote…</i></summary><blockquote>

But we don't even care about the path when we're in `/usr` — that'd be wrong as the binary would be `/usr/bin/memtier` library `/usr/lib/x86_64-linux-gnu/libmemtier.so.0` on Debian/glibc, `/usr/lib/x86_64-linux-musl/libmemtier.so.0` on Debian/musl, on Fedora `/usr/libc64/...`, etc.  Thus, we just return `libmemtier.so` which Just Works™.  This code is supposed to handle the case of non-installed library only.
</blockquote></details>

Maybe some short comment in code? E.g.:

// if path starts with "/usr" (memkind is properly installed), return "libmemtier.so" which Just Works™
// else assume libmemtier.so is in the same directory as argv[0]

I can see the previous comment, but it does not say what it means to be "properly installed" and that, in such case, a bare "libmemtier.so" is taken.


<!-- Sent from Reviewable.io -->

2022-01-05 09:21 UTC, kilobyte reviewed
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/718)* status: 4 of 6 files reviewed, 9 unresolved discussions (waiting on @bratpiorka, @kilobyte, @maciekpac, and @PatKamin)

___
*[utils/memtier/memtier.c, line 20 at r1](https://reviewable.io/reviews/memkind/memkind/718#-MrRwThW9IaW5d0L7iF-:-Ms9ih5JCLj5hQ7guU0g:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/9d35d22d356172a9078997d9fae98c2fc09e7a01/utils/memtier/memtier.c#L20)):*
<details><summary><i>Previously, maciekpac wrote…</i></summary><blockquote>

Besides, using exit gives me shivers. I think it would be best to
</blockquote></details>

Done.
___
*[utils/memtier/memtier.c, line 24 at r1](https://reviewable.io/reviews/memkind/memkind/718#-MrS-TY848cv5rDuNtYG:-MsdWoGG199UbJEhAQKG:bgqaead) ([raw file](https://github.com/memkind/memkind/blob/9d35d22d356172a9078997d9fae98c2fc09e7a01/utils/memtier/memtier.c#L24)):*
<details><summary><i>Previously, maciekpac wrote…</i></summary><blockquote>

I think it stands for "greatest common divisor", which is quite a common acronym, but I agree
</blockquote></details>

gcd is an unthing now, and its replacement is named the way you suggested.
___
*[utils/memtier/memtier.c, line 26 at r1](https://reviewable.io/reviews/memkind/memkind/718#-MrSRKd3Aay3mzODRf3w:-MsdX5X56RDrx2eAuIJS:b-yrqiaw) ([raw file](https://github.com/memkind/memkind/blob/9d35d22d356172a9078997d9fae98c2fc09e7a01/utils/memtier/memtier.c#L26)):*
<details><summary><i>Previously, maciekpac wrote…</i></summary><blockquote>

You might also add it to the name of the function instead of a comment, but it should be visible somewhere
</blockquote></details>

This is moot now.
___
*[utils/memtier/memtier.c, line 52 at r1](https://reviewable.io/reviews/memkind/memkind/718#-MrRt7Hc-cuRLIHmvgtZ:-Ms4ToN-1HIVqzLLD4Kj:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/9d35d22d356172a9078997d9fae98c2fc09e7a01/utils/memtier/memtier.c#L52)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

what about this TODO?
</blockquote></details>

Done.
___
*[utils/memtier/memtier.c, line 79 at r1](https://reviewable.io/reviews/memkind/memkind/718#-MrSVAdx2FlAukRd74Np:-MsdXF718yFC-Mi74b5v:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/9d35d22d356172a9078997d9fae98c2fc09e7a01/utils/memtier/memtier.c#L79)):*
<details><summary><i>Previously, maciekpac wrote…</i></summary><blockquote>

What if we get two big prime numbers? This should not happen with KMEM_DAX, at least not now, but maybe we should handle such cases? 
</blockquote></details>

Done.
___
*[utils/memtier/memtier.c, line 88 at r1](https://reviewable.io/reviews/memkind/memkind/718#-MrSWSGEDnS1jWaDK156:-MsdXbnj1_C_MgEuJUsz:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/9d35d22d356172a9078997d9fae98c2fc09e7a01/utils/memtier/memtier.c#L88)):*
<details><summary><i>Previously, maciekpac wrote…</i></summary><blockquote>

"non-zero"?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-01-12 14:16 UTC, bratpiorka requested changes
> Reviewed 1 of 2 files at r5, 1 of 1 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/718)* status: all files reviewed, 14 unresolved discussions (waiting on @kilobyte, @maciekpac, and @PatKamin)

___
*[utils/memtier/fakecap.c, line 1 at r7](https://reviewable.io/reviews/memkind/memkind/718#-MtDdHqH6pncYn1KjufQ:-MtDdHqH6pncYn1KjufR:b68roa4) ([raw file](https://github.com/memkind/memkind/blob/17d4d23888380c0b710dc68cdefa25febb2e599c/utils/memtier/fakecap.c#L1)):*
> ```C
> #include <stdio.h>
> ```

where this file is used?
___
*[utils/memtier/fakecap.c, line 5 at r7](https://reviewable.io/reviews/memkind/memkind/718#-MtDbgXX9FnuyQcySyqi:-MtDbgXX9FnuyQcySyqj:b-uwphom) ([raw file](https://github.com/memkind/memkind/blob/17d4d23888380c0b710dc68cdefa25febb2e599c/utils/memtier/fakecap.c#L5)):*
> ```C
> #include <string.h>
> 
> // pointer to a struct or a string?  Всё равно!
> ```

please use only English 
___
*[utils/memtier/Makefile.mk, line 2 at r6](https://reviewable.io/reviews/memkind/memkind/718#-MtDaYEU6s_dXQPT9W5H:-MtDaYEU6s_dXQPT9W5I:bb6ht37) ([raw file](https://github.com/memkind/memkind/blob/d3ba83cdc2df2d37089c7ebc8a6410884b38568b/utils/memtier/Makefile.mk#L2)):*
> ```Makefile
> # SPDX-License-Identifier: BSD-2-Clause
> # Copyright (C) 2021 Intel Corporation.
> ```

2022
___
*[utils/memtier/memtier.c, line 26 at r1](https://reviewable.io/reviews/memkind/memkind/718#-MrSRKd3Aay3mzODRf3w:-MrWg9sO2gfGHgaGP_yC:b-p40ir) ([raw file](https://github.com/memkind/memkind/blob/9d35d22d356172a9078997d9fae98c2fc09e7a01/utils/memtier/memtier.c#L26)):*
<details><summary><i>Previously, maciekpac wrote…</i></summary><blockquote>

You might also add it to the name of the function instead of a comment, but it should be visible somewhere
</blockquote></details>

Adam: add info about source of this algorithm
___
*[utils/memtier/memtier.c, line 84 at r4](https://reviewable.io/reviews/memkind/memkind/718#-MrWfzwK2iKmfU1XvWkA:-MrWfzwK2iKmfU1XvWkB:b-i4vwmh) ([raw file](https://github.com/memkind/memkind/blob/5a91d0752390c8622582f7d785f23268d1ae9ea0/utils/memtier/memtier.c#L84)):*
> ```C
>                 "Options:\n"
>                 "    -r/--ratio      colon-separated relative portions of memory tiers to use,\n"
>                 "                    defaults to amount of memory installed on this system\n"
> ```

add info about expected values 
___
*[utils/memtier/memtier.c, line 1 at r6](https://reviewable.io/reviews/memkind/memkind/718#-MtDadwZBK9E_-1eEkFC:-MtDadwZBK9E_-1eEkFD:b-a900jv) ([raw file](https://github.com/memkind/memkind/blob/d3ba83cdc2df2d37089c7ebc8a6410884b38568b/utils/memtier/memtier.c#L1)):*
> ```C
> #define _GNU_SOURCE
> ```

could you also add a license to this file?


<!-- Sent from Reviewable.io -->

2022-01-12 16:37 UTC, maciekpac requested changes
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/718)* status: all files reviewed, 14 unresolved discussions (waiting on @bratpiorka, @kilobyte, and @PatKamin)

___
*[utils/memtier/memtier.c, line 26 at r1](https://reviewable.io/reviews/memkind/memkind/718#-MrSRKd3Aay3mzODRf3w:-MtE35D36VYsUfnFezJa:b32w74) ([raw file](https://github.com/memkind/memkind/blob/9d35d22d356172a9078997d9fae98c2fc09e7a01/utils/memtier/memtier.c#L26)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

Adam: add info about source of this algorithm
</blockquote></details>

Up
___
*[utils/memtier/memtier.c, line 78 at r1](https://reviewable.io/reviews/memkind/memkind/718#-MrS-GMT3O_8wXLc6gmu:-MtE5IVc-PzJ7SlCCy9Y:b32wtd) ([raw file](https://github.com/memkind/memkind/blob/9d35d22d356172a9078997d9fae98c2fc09e7a01/utils/memtier/memtier.c#L78)):*
<details><summary><i>Previously, kilobyte (Adam Borowski) wrote…</i></summary><blockquote>

You can't get here without at least one kind of memory above 0.
</blockquote></details>

ok
___
*[utils/memtier/memtier.c, line 63 at r6](https://reviewable.io/reviews/memkind/memkind/718#-MtE3i8tEBiYlT2dQcCr:-MtE3i8tEBiYlT2dQcCs:b-bpcas9) ([raw file](https://github.com/memkind/memkind/blob/d3ba83cdc2df2d37089c7ebc8a6410884b38568b/utils/memtier/memtier.c#L63)):*
> ```C
> {
>     unsigned long ratio[2];
>     bool noratio = true;
> ```

nit:

would probably be more readable as a variable without negation in the name (e.g. ratio_specified = false); I've heard that double negation (noratio = false, which is set in the switch below) is hard to read for some people (Clean Code: A Handbook of Agile Software Craftsmanship. Robert C. Martin., G29)
___
*[utils/memtier/memtier.c, line 78 at r6](https://reviewable.io/reviews/memkind/memkind/718#-MtE3SRxCyURp2N2Q7cM:-MtE3SRxCyURp2N2Q7cN:b-9dvcwr) ([raw file](https://github.com/memkind/memkind/blob/d3ba83cdc2df2d37089c7ebc8a6410884b38568b/utils/memtier/memtier.c#L78)):*
> ```C
>             case -1:
>                 goto endarg;
>             case 'r':; // ancient gcc requires an empty statement here
> ```

What version exactly? Why?
___
*[utils/memtier/memtier.c, line 90 at r6](https://reviewable.io/reviews/memkind/memkind/718#-MtE5Aif7xd5EYboGoCe:-MtE5Aif7xd5EYboGoCf:bb7462z) ([raw file](https://github.com/memkind/memkind/blob/d3ba83cdc2df2d37089c7ebc8a6410884b38568b/utils/memtier/memtier.c#L90)):*
> ```C
>                 break;
>             case 't':
>                 thresh = optarg; // TODO: validate?
> ```

TODO


<!-- Sent from Reviewable.io -->

2022-01-14 10:06 UTC, kilobyte reviewed
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/718)* status: 4 of 7 files reviewed, 13 unresolved discussions (waiting on @bratpiorka, @kilobyte, @maciekpac, and @PatKamin)

___
*[utils/memtier/fakecap.c, line 1 at r7](https://reviewable.io/reviews/memkind/memkind/718#-MtDdHqH6pncYn1KjufQ:-MtMiXtA6_GDLrJEtOpY:bxkfeaj) ([raw file](https://github.com/memkind/memkind/blob/17d4d23888380c0b710dc68cdefa25febb2e599c/utils/memtier/fakecap.c#L1)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

where this file is used?
</blockquote></details>

`fprintf()`
___
*[utils/memtier/fakecap.c, line 5 at r7](https://reviewable.io/reviews/memkind/memkind/718#-MtDbgXX9FnuyQcySyqi:-MtMiJ6UENM85tTR7Q-X:b-y7nh31) ([raw file](https://github.com/memkind/memkind/blob/17d4d23888380c0b710dc68cdefa25febb2e599c/utils/memtier/fakecap.c#L5)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

please use only English 
</blockquote></details>

Wot...  Didn't mean to leave it...
___
*[utils/memtier/Makefile.mk, line 2 at r6](https://reviewable.io/reviews/memkind/memkind/718#-MtDaYEU6s_dXQPT9W5H:-MtMiuEf1N1bwgyCzBPu:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/d3ba83cdc2df2d37089c7ebc8a6410884b38568b/utils/memtier/Makefile.mk#L2)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

2022
</blockquote></details>

Done.



_Code quote:_
```Makefile
# SPDX-License-Identifier: BSD-2-Clause
# Copyright (C) 2021 Intel Corporation.
```
___
*[utils/memtier/memtier.c, line 26 at r1](https://reviewable.io/reviews/memkind/memkind/718#-MrSRKd3Aay3mzODRf3w:-MtMjZVx4gomJvLTgMtq:bxi8d87) ([raw file](https://github.com/memkind/memkind/blob/9d35d22d356172a9078997d9fae98c2fc09e7a01/utils/memtier/memtier.c#L26)):*
<details><summary><i>Previously, maciekpac wrote…</i></summary><blockquote>

Up
</blockquote></details>

Source: some decaying matter between my ears, it tends to give deranged ideas.
___
*[utils/memtier/memtier.c, line 84 at r4](https://reviewable.io/reviews/memkind/memkind/718#-MrWfzwK2iKmfU1XvWkA:-MtMlQTU94MCQcyJhjwh:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/5a91d0752390c8622582f7d785f23268d1ae9ea0/utils/memtier/memtier.c#L84)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

add info about expected values 
</blockquote></details>

Done.
___
*[utils/memtier/memtier.c, line 1 at r6](https://reviewable.io/reviews/memkind/memkind/718#-MtDadwZBK9E_-1eEkFC:-MtMizuL8mjXhBzqx9Mk:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/d3ba83cdc2df2d37089c7ebc8a6410884b38568b/utils/memtier/memtier.c#L1)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

could you also add a license to this file?
</blockquote></details>

Done.
___
*[utils/memtier/memtier.c, line 63 at r6](https://reviewable.io/reviews/memkind/memkind/718#-MtE3i8tEBiYlT2dQcCr:-MtMkUW9DjEurBJYJVYN:bxl6i34) ([raw file](https://github.com/memkind/memkind/blob/d3ba83cdc2df2d37089c7ebc8a6410884b38568b/utils/memtier/memtier.c#L63)):*
<details><summary><i>Previously, maciekpac wrote…</i></summary><blockquote>

nit:

would probably be more readable as a variable without negation in the name (e.g. ratio_specified = false); I've heard that double negation (noratio = false, which is set in the switch below) is hard to read for some people (Clean Code: A Handbook of Agile Software Craftsmanship. Robert C. Martin., G29)
</blockquote></details>

I've renamed it to `guess_ratio`.

As for `b`, a ratio of 1:0 is valid, and means "use DRAM only".
___
*[utils/memtier/memtier.c, line 78 at r6](https://reviewable.io/reviews/memkind/memkind/718#-MtE3SRxCyURp2N2Q7cM:-MtMktv-CNpvkh9gCMTR:b5pz515) ([raw file](https://github.com/memkind/memkind/blob/d3ba83cdc2df2d37089c7ebc8a6410884b38568b/utils/memtier/memtier.c#L78)):*
<details><summary><i>Previously, maciekpac wrote…</i></summary><blockquote>

What version exactly? Why?
</blockquote></details>

Whatever Centos 7 on our CI uses.


<!-- Sent from Reviewable.io -->

2022-01-14 13:31 UTC, bratpiorka requested changes
> Reviewed 3 of 3 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/718)* status: all files reviewed, 10 unresolved discussions (waiting on @kilobyte, @maciekpac, and @PatKamin)

___
*[utils/memtier/fakecap.c, line 1 at r7](https://reviewable.io/reviews/memkind/memkind/718#-MtDdHqH6pncYn1KjufQ:-MtNlp3v62RRn-kPOToy:by4zqzx) ([raw file](https://github.com/memkind/memkind/blob/17d4d23888380c0b710dc68cdefa25febb2e599c/utils/memtier/fakecap.c#L1)):*
<details><summary><i>Previously, kilobyte (Adam Borowski) wrote…</i></summary><blockquote>

`fprintf()`
</blockquote></details>

I still don't know where... please give me a reference to the exact point in the code
___
*[utils/memtier/memtier.c, line 84 at r4](https://reviewable.io/reviews/memkind/memkind/718#-MrWfzwK2iKmfU1XvWkA:-MtNlK4o27XQ3tIDFp5q:bfn91u4) ([raw file](https://github.com/memkind/memkind/blob/5a91d0752390c8622582f7d785f23268d1ae9ea0/utils/memtier/memtier.c#L84)):*
<details><summary><i>Previously, kilobyte (Adam Borowski) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

relative portion could mean e.g. "1,1.5"? What if user passes here floating-point number? Could you add info that you expect here only integer numbers and validate this?


<!-- Sent from Reviewable.io -->

2022-01-18 11:05 UTC, PatKamin requested changes
> Reviewed 1 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/718)* status: all files reviewed, 14 unresolved discussions (waiting on @kilobyte, @maciekpac, and @PatKamin)

___
*[utils/memtier/fakecap.c, line 23 at r8](https://reviewable.io/reviews/memkind/memkind/718#-MtgI7oK52RI6y_K2hva:-MtgI7oL9H0OnlWHLZ7T:bwuc4yf) ([raw file](https://github.com/memkind/memkind/blob/fbd64e977cdc4d7dd6795d3eae87a2ba0890e88f/utils/memtier/fakecap.c#L23)):*
> ```C
>     // memory amounts are unsigned
>     char *err;
>     size_t cap = strtoul(var, &err, 0);
> ```

Wrong value when var is a negative number.
___
*[utils/memtier/memtier.c, line 107 at r6](https://reviewable.io/reviews/memkind/memkind/718#-Mt25XFX1e-NzcilNm1t:-Mt25XFX1e-NzcilNm1u:b-ohs27t) ([raw file](https://github.com/memkind/memkind/blob/d3ba83cdc2df2d37089c7ebc8a6410884b38568b/utils/memtier/memtier.c#L107)):*
> ```C
>                 exit(0);
>             default:
>                 die(PN ": unknown option ｢%s｣\n", argv[optind]);
> ```

Add info from `--help`.
___
*[utils/memtier/memtier.c, line 66 at r8](https://reviewable.io/reviews/memkind/memkind/718#-MtgXf5yCn9ndZlNm6CO:-MtgXf5yCn9ndZlNm6CP:b-wq8m8w) ([raw file](https://github.com/memkind/memkind/blob/fbd64e977cdc4d7dd6795d3eae87a2ba0890e88f/utils/memtier/memtier.c#L66)):*
> ```C
> {
>     unsigned long ratio[2];
>     bool noratio = true;
> ```

nit: `default_ratio` sounds much better.
___
*[utils/memtier/memtier.c, line 110 at r8](https://reviewable.io/reviews/memkind/memkind/718#-Mtga1UIE-fUjN7p8NwM:-Mtga1UIE-fUjN7p8NwN:b-5djcmh) ([raw file](https://github.com/memkind/memkind/blob/fbd64e977cdc4d7dd6795d3eae87a2ba0890e88f/utils/memtier/memtier.c#L110)):*
> ```C
>                 exit(0);
>             default:
>                 die(PN ": unknown option ｢%s｣\n", argv[optind]);
> ```

Print wrong arg name rather than it's value.
___
*[utils/memtier/memtier.c, line 116 at r8](https://reviewable.io/reviews/memkind/memkind/718#-MtgpwTq6peSxoKKEo3X:-MtgpwTq6peSxoKKEo3Y:bqfb066) ([raw file](https://github.com/memkind/memkind/blob/fbd64e977cdc4d7dd6795d3eae87a2ba0890e88f/utils/memtier/memtier.c#L116)):*
> ```C
> 
>     if (noratio) {
>         ssize_t dram = memkind_get_capacity(MEMKIND_REGULAR);
> ```

This kind will be initialized only after making an initial malloc(). Otherwise you'll get `dram = -1` here.
___
*[utils/memtier/memtier.c, line 126 at r8](https://reviewable.io/reviews/memkind/memkind/718#-MtgaacJ0v9cpuJ4PTa3:-MtgaacJ0v9cpuJ4PTa4:bbmnx5u) ([raw file](https://github.com/memkind/memkind/blob/fbd64e977cdc4d7dd6795d3eae87a2ba0890e88f/utils/memtier/memtier.c#L126)):*
> ```C
>         ratio[0] = dram / d;
>         ratio[1] = pmem / d;
>         vmsg("Using ratio %zu:%zu\n", ratio[0], ratio[1]);
> ```

Include the names of tiers.
___
*[utils/memtier/memtier.c, line 136 at r8](https://reviewable.io/reviews/memkind/memkind/718#-MtgLTsRBl77fhUJTmac:-MtgLTsRBl77fhUJTmad:b-4p6285) ([raw file](https://github.com/memkind/memkind/blob/fbd64e977cdc4d7dd6795d3eae87a2ba0890e88f/utils/memtier/memtier.c#L136)):*
> ```C
> 
>     if (optind >= argc)
>         die("Usage: " PN " [options] command [args]\n");
> ```

It's still not much of a help. With such a statement I still don't know how to run this. Please, print help message here.


<!-- Sent from Reviewable.io -->

2022-01-21 10:26 UTC, kilobyte reviewed
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/718)* status: 3 of 7 files reviewed, 13 unresolved discussions (waiting on @bratpiorka, @kilobyte, @maciekpac, and @PatKamin)

___
*[utils/memtier/fakecap.c, line 1 at r7](https://reviewable.io/reviews/memkind/memkind/718#-MtDdHqH6pncYn1KjufQ:-Mtw6RSVEpyclF573A8L:bhyl5g7) ([raw file](https://github.com/memkind/memkind/blob/17d4d23888380c0b710dc68cdefa25febb2e599c/utils/memtier/fakecap.c#L1)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

I still don't know where... please give me a reference to the exact point in the code
</blockquote></details>

`--help` for example.
___
*[utils/memtier/fakecap.c, line 23 at r8](https://reviewable.io/reviews/memkind/memkind/718#-MtgI7oK52RI6y_K2hva:-Mtw6fwt1jL7Zw58OXGE:b-rcijzn) ([raw file](https://github.com/memkind/memkind/blob/fbd64e977cdc4d7dd6795d3eae87a2ba0890e88f/utils/memtier/fakecap.c#L23)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Wrong value when var is a negative number.
</blockquote></details>

No argument to `memtier` is ever supposed to be negative.  But I added a sanity check for ≥ 1PB.
___
*[utils/memtier/memtier.c, line 97 at r1](https://reviewable.io/reviews/memkind/memkind/718#-MrSXOxx-Y6_5rOiyi0q:-Mtw9M253X9mD5-WuZ-Q:b-m5gxmg) ([raw file](https://github.com/memkind/memkind/blob/9d35d22d356172a9078997d9fae98c2fc09e7a01/utils/memtier/memtier.c#L97)):*
<details><summary><i>Previously, maciekpac wrote…</i></summary><blockquote>

Maybe some short comment in code? E.g.:

// if path starts with "/usr" (memkind is properly installed), return "libmemtier.so" which Just Works™
// else assume libmemtier.so is in the same directory as argv[0]

I can see the previous comment, but it does not say what it means to be "properly installed" and that, in such case, a bare "libmemtier.so" is taken.
</blockquote></details>

I've rewritten the comment.
___
*[utils/memtier/memtier.c, line 107 at r6](https://reviewable.io/reviews/memkind/memkind/718#-Mt25XFX1e-NzcilNm1t:-Mtw8Jjl-LX0xP1cSnjy:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/d3ba83cdc2df2d37089c7ebc8a6410884b38568b/utils/memtier/memtier.c#L107)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Add info from `--help`.
</blockquote></details>

Done.
___
*[utils/memtier/memtier.c, line 66 at r8](https://reviewable.io/reviews/memkind/memkind/718#-MtgXf5yCn9ndZlNm6CO:-Mtw7lKqEOWLUPOe0I70:b-arf445) ([raw file](https://github.com/memkind/memkind/blob/fbd64e977cdc4d7dd6795d3eae87a2ba0890e88f/utils/memtier/memtier.c#L66)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

nit: `default_ratio` sounds much better.
</blockquote></details>

It's `guess_ratio now`.
___
*[utils/memtier/memtier.c, line 110 at r8](https://reviewable.io/reviews/memkind/memkind/718#-Mtga1UIE-fUjN7p8NwM:-Mtw8b0M2FUBGkq75zdf:bft6y4w) ([raw file](https://github.com/memkind/memkind/blob/fbd64e977cdc4d7dd6795d3eae87a2ba0890e88f/utils/memtier/memtier.c#L110)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Print wrong arg name rather than it's value.
</blockquote></details>

Actually, stdopt already gives an error message.
___
*[utils/memtier/memtier.c, line 116 at r8](https://reviewable.io/reviews/memkind/memkind/718#-MtgpwTq6peSxoKKEo3X:-Mtw8vg67XlscyFMFurp:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/fbd64e977cdc4d7dd6795d3eae87a2ba0890e88f/utils/memtier/memtier.c#L116)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

This kind will be initialized only after making an initial malloc(). Otherwise you'll get `dram = -1` here.
</blockquote></details>

Done.
___
*[utils/memtier/memtier.c, line 126 at r8](https://reviewable.io/reviews/memkind/memkind/718#-MtgaacJ0v9cpuJ4PTa3:-Mtw91vE2V0YcGCldh-t:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/fbd64e977cdc4d7dd6795d3eae87a2ba0890e88f/utils/memtier/memtier.c#L126)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Include the names of tiers.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-01-21 10:58 UTC, maciekpac requested changes
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/718)* status: 3 of 7 files reviewed, 14 unresolved discussions (waiting on @bratpiorka, @kilobyte, @maciekpac, and @PatKamin)

___
*[utils/memtier/memtier.c, line 97 at r1](https://reviewable.io/reviews/memkind/memkind/718#-MrSXOxx-Y6_5rOiyi0q:-MtwGPrz4o8xRnl_zW4b:b-wfoefh) ([raw file](https://github.com/memkind/memkind/blob/9d35d22d356172a9078997d9fae98c2fc09e7a01/utils/memtier/memtier.c#L97)):*
<details><summary><i>Previously, kilobyte (Adam Borowski) wrote…</i></summary><blockquote>

I've rewritten the comment.
</blockquote></details>

Thank you :)

It would be best to do at least manual QA tests of this code with some dev that does not know the source code, to make sure it behaves the expected way and does not cause too much confusion, as a side note for future
___
*[utils/memtier/memtier.c, line 78 at r6](https://reviewable.io/reviews/memkind/memkind/718#-MtE3SRxCyURp2N2Q7cM:-MtwFeN4AKnsKsHZFpSq:bazx4m6) ([raw file](https://github.com/memkind/memkind/blob/d3ba83cdc2df2d37089c7ebc8a6410884b38568b/utils/memtier/memtier.c#L78)):*
<details><summary><i>Previously, kilobyte (Adam Borowski) wrote…</i></summary><blockquote>

Whatever Centos 7 on our CI uses.
</blockquote></details>

would be perfect to add it in a comment, e.g.

            case 'r':; // gcc <<version>> on centof 7 requires an empty statement here

This way we would be able to easily get rid of this statement once we drop support for that system
___
*[utils/memtier/memtier.c, line 136 at r8](https://reviewable.io/reviews/memkind/memkind/718#-MtgLTsRBl77fhUJTmac:-MtwH63Y2VbZSv5akpG-:b32wyo) ([raw file](https://github.com/memkind/memkind/blob/fbd64e977cdc4d7dd6795d3eae87a2ba0890e88f/utils/memtier/memtier.c#L136)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

It's still not much of a help. With such a statement I still don't know how to run this. Please, print help message here.
</blockquote></details>

up
___
*[utils/memtier/memtier.c, line 24 at r9](https://reviewable.io/reviews/memkind/memkind/718#-MtwF9la7L2svKacazyr:-MtwF9la7L2svKacazys:b2ztv0u) ([raw file](https://github.com/memkind/memkind/blob/84df562e5cbfe677329c688378b557a7d74ed693/utils/memtier/memtier.c#L24)):*
> ```C
>     int len = vsnprintf(buf, sizeof(buf), fmt, args);
>     va_end(args);
>     if (write(STDERR_FILENO, buf, len))
> ```

? Why is it inside "if" ? Is it a way of not ignoring the return value?



_Code quote:_
```C
    if (write(STDERR_FILENO, buf, len))
        ;
```


<!-- Sent from Reviewable.io -->

2022-01-31 12:25 UTC, bratpiorka requested changes
> Reviewed 1 of 4 files at r9, 2 of 3 files at r11, 2 of 3 files at r12.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/718)* status: 5 of 8 files reviewed, 16 unresolved discussions (waiting on @bratpiorka, @kilobyte, @maciekpac, and @PatKamin)

___
*[utils/memtier/fakecap.c, line 1 at r7](https://reviewable.io/reviews/memkind/memkind/718#-MtDdHqH6pncYn1KjufQ:-Muk4W989nkW8xhFDhGJ:b-7xqh20) ([raw file](https://github.com/memkind/memkind/blob/17d4d23888380c0b710dc68cdefa25febb2e599c/utils/memtier/fakecap.c#L1)):*
<details><summary><i>Previously, kilobyte (Adam Borowski) wrote…</i></summary><blockquote>

`--help` for example.
</blockquote></details>

I still don't get it - where help() call memkind_get_capacity() from this file?
___
*[utils/memtier/memtier.c, line 36 at r11](https://reviewable.io/reviews/memkind/memkind/718#-Muk2jjhEMFJ15x7c9ME:-Muk2jjhEMFJ15x7c9MF:b-c6zsw2) ([raw file](https://github.com/memkind/memkind/blob/087ca49136d2f1cde5a06e81419793e751234f82/utils/memtier/memtier.c#L36)):*
> ```C
>         "    memtier [options] program [args]\n"
>         "Options:\n"
>         "    -r/--ratio      colon-separated relative portions of memory tiers to use,\n"
> ```

relative portion could mean e.g. "1,1.5"? What if user passes here floating-point number? Could you add info that you expect here only integer numbers and validate this?
___
*[utils/memtier/memtier.c, line 40 at r11](https://reviewable.io/reviews/memkind/memkind/718#-Muk3SCY4O_JmFZpdAbC:-Muk3SCY4O_JmFZpdAbD:b-4ndgb1) ([raw file](https://github.com/memkind/memkind/blob/087ca49136d2f1cde5a06e81419793e751234f82/utils/memtier/memtier.c#L40)):*
> ```C
>         "                    1:3 means 1 byte of DRAM will be used per 3 bytes of PMEM.\n"
>         "    -t/--threshold  alloc size threshold configurations, see the man page\n"
>         "    -v/--verbose    display generated configuration\n");
> ```

add -h to list of options
___
*[utils/memtier/memtier.c, line 105 at r11](https://reviewable.io/reviews/memkind/memkind/718#-Muk4jMf3dXNAfKgVv_y:-Muk4jMf3dXNAfKgVv_z:bvttbo7) ([raw file](https://github.com/memkind/memkind/blob/087ca49136d2f1cde5a06e81419793e751234f82/utils/memtier/memtier.c#L105)):*
> ```C
>                 if (ratio[0] > PETA || ratio[1] > PETA) // overflow somewhere?
>                     die(PN
>                         ": the number to --ratio doesn't seem to be sane.\n");
> ```

could you refrain from using judging words in error messages?


<!-- Sent from Reviewable.io -->

2022-01-31 12:26 UTC, bratpiorka reviewed
> Reviewed 1 of 3 files at r11, 1 of 3 files at r12, 2 of 2 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/718)* status: all files reviewed, 16 unresolved discussions (waiting on @kilobyte, @maciekpac, and @PatKamin)



<!-- Sent from Reviewable.io -->

2022-02-02 10:26 UTC, PatKamin requested changes
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/718)* status: all files reviewed, 13 unresolved discussions (waiting on @kilobyte, @maciekpac, and @PatKamin)

___
*[utils/memtier/memtier.c, line 66 at r8](https://reviewable.io/reviews/memkind/memkind/718#-MtgXf5yCn9ndZlNm6CO:-MutglnzEsZN33mIS7pE:bfk5qud) ([raw file](https://github.com/memkind/memkind/blob/fbd64e977cdc4d7dd6795d3eae87a2ba0890e88f/utils/memtier/memtier.c#L66)):*
<details><summary><i>Previously, kilobyte (Adam Borowski) wrote…</i></summary><blockquote>

It's `guess_ratio now`.
</blockquote></details>

nit: It's not a guess, rather a calculation :)
___
*[utils/memtier/memtier.c, line 116 at r8](https://reviewable.io/reviews/memkind/memkind/718#-MtgpwTq6peSxoKKEo3X:-MutxC2h4rtL0_pJMdM7:b930b8i) ([raw file](https://github.com/memkind/memkind/blob/fbd64e977cdc4d7dd6795d3eae87a2ba0890e88f/utils/memtier/memtier.c#L116)):*
<details><summary><i>Previously, kilobyte (Adam Borowski) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

You have to explicitly call a malloc with this kind: memkind_malloc(MEMKIND_REGULAR, size). Sorry for a misleading comment.
___
*[utils/memtier/memtier.c, line 126 at r8](https://reviewable.io/reviews/memkind/memkind/718#-MtgaacJ0v9cpuJ4PTa3:-Muty2CFAr5A3OHeC4vP:b-9zua1g) ([raw file](https://github.com/memkind/memkind/blob/fbd64e977cdc4d7dd6795d3eae87a2ba0890e88f/utils/memtier/memtier.c#L126)):*
<details><summary><i>Previously, kilobyte (Adam Borowski) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

nit: DRAM:KMEM_DAX


<!-- Sent from Reviewable.io -->

2022-02-04 07:37 UTC, bratpiorka reviewed
> Reviewed 5 of 5 files at r15, 3 of 3 files at r16, 2 of 2 files at r17, 1 of 1 files at r18, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/718)* status: all files reviewed, 12 unresolved discussions (waiting on @kilobyte, @maciekpac, and @PatKamin)



<!-- Sent from Reviewable.io -->

2022-02-04 09:31 UTC, kilobyte reviewed
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/718)* status: 3 of 9 files reviewed, 12 unresolved discussions (waiting on @bratpiorka, @kilobyte, @maciekpac, and @PatKamin)

___
*[utils/memtier/fakecap.c, line 1 at r7](https://reviewable.io/reviews/memkind/memkind/718#-MtDdHqH6pncYn1KjufQ:-Mv32jaS4ONU5VZk8sq9:bgun02t) ([raw file](https://github.com/memkind/memkind/blob/17d4d23888380c0b710dc68cdefa25febb2e599c/utils/memtier/fakecap.c#L1)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

I still don't get it - where help() call memkind_get_capacity() from this file?
</blockquote></details>

Seems like Reviewable is confused about context and moved the discussion to another file.
___
*[utils/memtier/memtier.c, line 97 at r1](https://reviewable.io/reviews/memkind/memkind/718#-MrSXOxx-Y6_5rOiyi0q:-Mv33RSAEOEhKPv7-kT1:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/9d35d22d356172a9078997d9fae98c2fc09e7a01/utils/memtier/memtier.c#L97)):*
<details><summary><i>Previously, maciekpac wrote…</i></summary><blockquote>

Thank you :)

It would be best to do at least manual QA tests of this code with some dev that does not know the source code, to make sure it behaves the expected way and does not cause too much confusion, as a side note for future
</blockquote></details>

Done.
___
*[utils/memtier/memtier.c, line 129 at r1](https://reviewable.io/reviews/memkind/memkind/718#-MrS3dpN86OIxCjnoiOz:-Mv33RxdE-uoK4lAp7H-:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/9d35d22d356172a9078997d9fae98c2fc09e7a01/utils/memtier/memtier.c#L129)):*
<details><summary><i>Previously, maciekpac wrote…</i></summary><blockquote>

Up
</blockquote></details>

Done.
___
*[utils/memtier/memtier.c, line 78 at r6](https://reviewable.io/reviews/memkind/memkind/718#-MtE3SRxCyURp2N2Q7cM:-MuysJbc5Vaz4j-25_Kl:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/d3ba83cdc2df2d37089c7ebc8a6410884b38568b/utils/memtier/memtier.c#L78)):*
<details><summary><i>Previously, maciekpac wrote…</i></summary><blockquote>

would be perfect to add it in a comment, e.g.

            case 'r':; // gcc <<version>> on centof 7 requires an empty statement here

This way we would be able to easily get rid of this statement once we drop support for that system
</blockquote></details>

Done.
___
*[utils/memtier/memtier.c, line 116 at r8](https://reviewable.io/reviews/memkind/memkind/718#-MtgpwTq6peSxoKKEo3X:-Muysjh193U04pJnMkBu:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/fbd64e977cdc4d7dd6795d3eae87a2ba0890e88f/utils/memtier/memtier.c#L116)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

You have to explicitly call a malloc with this kind: memkind_malloc(MEMKIND_REGULAR, size). Sorry for a misleading comment.
</blockquote></details>

Done.
___
*[utils/memtier/memtier.c, line 126 at r8](https://reviewable.io/reviews/memkind/memkind/718#-MtgaacJ0v9cpuJ4PTa3:-MuysnJ14EAXkFXhkwSV:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/fbd64e977cdc4d7dd6795d3eae87a2ba0890e88f/utils/memtier/memtier.c#L126)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

nit: DRAM:KMEM_DAX
</blockquote></details>

Done.
___
*[utils/memtier/memtier.c, line 136 at r8](https://reviewable.io/reviews/memkind/memkind/718#-MtgLTsRBl77fhUJTmac:-Muyt-6Q-8Xq1xOWHUZt:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/fbd64e977cdc4d7dd6795d3eae87a2ba0890e88f/utils/memtier/memtier.c#L136)):*
<details><summary><i>Previously, maciekpac wrote…</i></summary><blockquote>

up
</blockquote></details>

Done.
___
*[utils/memtier/memtier.c, line 24 at r9](https://reviewable.io/reviews/memkind/memkind/718#-MtwF9la7L2svKacazyr:-Muyr8_c8JXfplGdPb-B:b3wihz3) ([raw file](https://github.com/memkind/memkind/blob/84df562e5cbfe677329c688378b557a7d74ed693/utils/memtier/memtier.c#L24)):*
<details><summary><i>Previously, maciekpac wrote…</i></summary><blockquote>

? Why is it inside "if" ? Is it a way of not ignoring the return value?
</blockquote></details>

The usual way to block bogus unused-result warnings is currently [broken](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=66425), the `if` is an unsightly but working workaround.
___
*[utils/memtier/memtier.c, line 40 at r11](https://reviewable.io/reviews/memkind/memkind/718#-Muk3SCY4O_JmFZpdAbC:-MuyryPbEp8wi_ySfoau:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/ab3096a58d4b8f9ac6c568f9d1eb8d03afa43566/utils/memtier/memtier.c#L40)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

add -h to list of options
</blockquote></details>

Done.
___
*[utils/memtier/memtier.c, line 105 at r11](https://reviewable.io/reviews/memkind/memkind/718#-Muk4jMf3dXNAfKgVv_y:-Mv33Ize3XssPyH6p8cR:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/ab3096a58d4b8f9ac6c568f9d1eb8d03afa43566/utils/memtier/memtier.c#L105)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

could you refrain from using judging words in error messages?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-02-04 09:39 UTC, kilobyte reviewed
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/718)* status: 3 of 9 files reviewed, 12 unresolved discussions (waiting on @bratpiorka, @maciekpac, and @PatKamin)

___
*[utils/memtier/memtier.c, line 90 at r6](https://reviewable.io/reviews/memkind/memkind/718#-MtE5Aif7xd5EYboGoCe:-Mv344vJBk4t0J4X58pe:b-uu7jm4) ([raw file](https://github.com/memkind/memkind/blob/d3ba83cdc2df2d37089c7ebc8a6410884b38568b/utils/memtier/memtier.c#L90)):*
<details><summary><i>Previously, maciekpac wrote…</i></summary><blockquote>

TODO
</blockquote></details>

It works well enough when passed as-is, at least for the first stab.  The tiering library itself will parse the string and complain if it's wrong.  Reporting issues without an abort() would be nicer, but I'm leaving this TODO for the future.
___
*[utils/memtier/memtier.c, line 36 at r11](https://reviewable.io/reviews/memkind/memkind/718#-Muk2jjhEMFJ15x7c9ME:-Mv35Qmv5Jj29tYG2-OE:b-fz71l) ([raw file](https://github.com/memkind/memkind/blob/ab3096a58d4b8f9ac6c568f9d1eb8d03afa43566/utils/memtier/memtier.c#L36)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

relative portion could mean e.g. "1,1.5"? What if user passes here floating-point number? Could you add info that you expect here only integer numbers and validate this?
</blockquote></details>

Which way would you prefer — int only or floats?


<!-- Sent from Reviewable.io -->

2022-02-04 10:40 UTC, PatKamin requested changes
> Reviewed 1 of 4 files at r9, 6 of 6 files at r19, 2 of 2 files at r21, 1 of 1 files at r22, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/718)* status: 6 of 9 files reviewed, 9 unresolved discussions (waiting on @bratpiorka, @kilobyte, @maciekpac, and @PatKamin)

___
*[utils/memtier/tests, line 27 at r22](https://reviewable.io/reviews/memkind/memkind/718#-Mv3AfiWDE9HZ4xcHqxt:-Mv3AfiWDE9HZ4xcHqxu:bnox8pl) ([raw file](https://github.com/memkind/memkind/blob/2aecb33969046a73d82790b09595da642dbc69e1/utils/memtier/tests#L27)):*
> ```
> calc_ratio 512G 4T 1:8
> calc_ratio 1000017 3000000 1:3
> calc_ratio 20G 50G 2:5
> ```

Add a test with the opposite ratio, ie. 3:2


<!-- Sent from Reviewable.io -->

2022-02-04 11:10 UTC, bratpiorka requested changes
> Reviewed 4 of 6 files at r19, 3 of 3 files at r20, 2 of 2 files at r21, 1 of 1 files at r22, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/718)* status: all files reviewed, 8 unresolved discussions (waiting on @kilobyte, @maciekpac, and @PatKamin)

___
*[utils/memtier/Makefile.mk, line 2 at r19](https://reviewable.io/reviews/memkind/memkind/718#-Mv3OqhB46QOoMeDDeGs:-Mv3OqhB46QOoMeDDeGt:b11178e) ([raw file](https://github.com/memkind/memkind/blob/67a16ac89740f3c288bae45f9c2d9dce45531d66/utils/memtier/Makefile.mk#L2)):*
> ```Makefile
> # SPDX-License-Identifier: BSD-2-Clause
> # Copyright (C) 2021 Intel Corporation.
> ```

21 or 22?
___
*[utils/memtier/memtier.c, line 36 at r11](https://reviewable.io/reviews/memkind/memkind/718#-Muk2jjhEMFJ15x7c9ME:-Mv3OxOv7Y3Su-urtG0c:bf3ivba) ([raw file](https://github.com/memkind/memkind/blob/ab3096a58d4b8f9ac6c568f9d1eb8d03afa43566/utils/memtier/memtier.c#L36)):*
<details><summary><i>Previously, kilobyte (Adam Borowski) wrote…</i></summary><blockquote>

Which way would you prefer — int only or floats?
</blockquote></details>

only ints - please add an info to this messages that you expects only ints and validate values passed by user
___
*[utils/memtier/memtier.c, line 105 at r11](https://reviewable.io/reviews/memkind/memkind/718#-Muk4jMf3dXNAfKgVv_y:-Mv3PCH-9aha9uQalwmx:b-7rl0iw) ([raw file](https://github.com/memkind/memkind/blob/ab3096a58d4b8f9ac6c568f9d1eb8d03afa43566/utils/memtier/memtier.c#L105)):*
<details><summary><i>Previously, kilobyte (Adam Borowski) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

done?
___
*[utils/memtier/tests, line 27 at r22](https://reviewable.io/reviews/memkind/memkind/718#-Mv3AfiWDE9HZ4xcHqxt:-Mv3PMLV7hgKqM3h-JrB:b-o999k7) ([raw file](https://github.com/memkind/memkind/blob/2aecb33969046a73d82790b09595da642dbc69e1/utils/memtier/tests#L27)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Add a test with the opposite ratio, ie. 3:2
</blockquote></details>

Add negative test with floating point values


<!-- Sent from Reviewable.io -->

2022-02-04 13:29 UTC, kilobyte reviewed
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/718)* status: all files reviewed, 8 unresolved discussions (waiting on @bratpiorka, @maciekpac, and @PatKamin)

___
*[utils/memtier/Makefile.mk, line 2 at r19](https://reviewable.io/reviews/memkind/memkind/718#-Mv3OqhB46QOoMeDDeGs:-Mv3RCr_CNNkOhr0ixNT:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/67a16ac89740f3c288bae45f9c2d9dce45531d66/utils/memtier/Makefile.mk#L2)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

21 or 22?
</blockquote></details>

Done.
___
*[utils/memtier/memtier.c, line 36 at r11](https://reviewable.io/reviews/memkind/memkind/718#-Muk2jjhEMFJ15x7c9ME:-Mv3ThHH29zCeBs6mgX3:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/ab3096a58d4b8f9ac6c568f9d1eb8d03afa43566/utils/memtier/memtier.c#L36)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

only ints - please add an info to this messages that you expects only ints and validate values passed by user
</blockquote></details>

Done.
___
*[utils/memtier/memtier.c, line 105 at r11](https://reviewable.io/reviews/memkind/memkind/718#-Muk4jMf3dXNAfKgVv_y:-Mv3Tok-CU_8kEmDyU6F:bhst7oq) ([raw file](https://github.com/memkind/memkind/blob/ab3096a58d4b8f9ac6c568f9d1eb8d03afa43566/utils/memtier/memtier.c#L105)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

done?
</blockquote></details>

"plausible"
___
*[utils/memtier/tests, line 27 at r22](https://reviewable.io/reviews/memkind/memkind/718#-Mv3AfiWDE9HZ4xcHqxt:-Mv3v12nBZMVAaf5zvdr:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/2aecb33969046a73d82790b09595da642dbc69e1/utils/memtier/tests#L27)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

Add negative test with floating point values
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-02-04 13:41 UTC, bratpiorka reviewed
> Reviewed 3 of 6 files at r23, 3 of 3 files at r24, 2 of 2 files at r25, 2 of 2 files at r26, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/718)* status: all files reviewed, 6 unresolved discussions (waiting on @maciekpac and @PatKamin)



<!-- Sent from Reviewable.io -->

2022-02-04 14:41 UTC, bratpiorka approved these changes
> Reviewed 6 of 6 files at r27, 3 of 3 files at r28, 2 of 2 files at r29, 2 of 2 files at r30, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/718)* status: all files reviewed, 6 unresolved discussions (waiting on @maciekpac and @PatKamin)



<!-- Sent from Reviewable.io -->

2022-02-04 18:35 UTC, maciekpac reviewed
> Reviewed 1 of 6 files at r27.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/718)* status: all files reviewed, 3 unresolved discussions (waiting on @kilobyte, @maciekpac, and @PatKamin)

___
*[utils/memtier/memtier.c, line 24 at r9](https://reviewable.io/reviews/memkind/memkind/718#-MtwF9la7L2svKacazyr:-Mv4y_muAeV4eDRh4SH-:bfbxxf7) ([raw file](https://github.com/memkind/memkind/blob/84df562e5cbfe677329c688378b557a7d74ed693/utils/memtier/memtier.c#L24)):*
<details><summary><i>Previously, kilobyte (Adam Borowski) wrote…</i></summary><blockquote>

The usual way to block bogus unused-result warnings is currently [broken](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=66425), the `if` is an unsightly but working workaround.
</blockquote></details>

Could you write a short comment about that in code?


<!-- Sent from Reviewable.io -->

2022-02-04 21:44 UTC, kilobyte reviewed
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/718)* status: 3 of 9 files reviewed, 3 unresolved discussions (waiting on @bratpiorka, @maciekpac, and @PatKamin)

___
*[utils/memtier/memtier.c, line 24 at r9](https://reviewable.io/reviews/memkind/memkind/718#-MtwF9la7L2svKacazyr:-Mv5gWAv7CrdgEDk-ynS:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/84df562e5cbfe677329c688378b557a7d74ed693/utils/memtier/memtier.c#L24)):*
<details><summary><i>Previously, maciekpac wrote…</i></summary><blockquote>

Could you write a short comment about that in code?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-02-07 07:41 UTC, PatKamin approved these changes
> Reviewed 2 of 3 files at r32, 2 of 2 files at r33, 2 of 2 files at r34, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/718)* status: all files reviewed, 2 unresolved discussions (waiting on @maciekpac)



<!-- Sent from Reviewable.io -->

2022-02-09 11:59 UTC, maciekpac approved these changes
> Reviewed 1 of 4 files at r9, 6 of 6 files at r31.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/718)* status: all files reviewed, 2 unresolved discussions (waiting on @maciekpac)



<!-- Sent from Reviewable.io -->

2022-02-10 10:46 UTC, PatKamin commented
Please, add a note for this binary in manual.

2022-02-15 17:18 UTC, maciekpac approved these changes
> Reviewed 3 of 3 files at r32.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/718)* status: all files reviewed, 2 unresolved discussions (waiting on @maciekpac)



<!-- Sent from Reviewable.io -->

2022-02-28 08:16 UTC, kilobyte reviewed
Added.

> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/718#-:-MwzOdot3HV1gATmP-Dx:bqmjwcz)* status: 7 of 14 files reviewed, 2 unresolved discussions (waiting on @bratpiorka, @maciekpac, and @PatKamin)



<!-- Sent from Reviewable.io -->

2022-02-28 10:13 UTC, bratpiorka reviewed
> Reviewed 6 of 6 files at r31, 3 of 3 files at r32, 2 of 2 files at r33, 2 of 2 files at r34, 5 of 6 files at r35.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/718)* status: 9 of 14 files reviewed, 2 unresolved discussions (waiting on @bratpiorka, @maciekpac, and @PatKamin)



<!-- Sent from Reviewable.io -->

2022-02-28 10:14 UTC, bratpiorka reviewed
> Reviewed 5 of 5 files at r36, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/718)* status: all files reviewed, 2 unresolved discussions (waiting on @maciekpac)



<!-- Sent from Reviewable.io -->

2022-03-03 07:10 UTC, PatKamin approved these changes
> Reviewed 11 of 11 files at r38, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/718)* status: all files reviewed, 3 unresolved discussions (waiting on @kilobyte and @maciekpac)



<!-- Sent from Reviewable.io -->

2022-03-03 07:12 UTC, merged