Fix klocwork issues
memkind/memkind pull request #728
Opened 2022-01-18 12:01 UTC by jacekgrzybek

2022-01-18 13:58 UTC, bratpiorka requested changes
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/728)* status: all files reviewed, 8 unresolved discussions (waiting on @jacekgrzybek)

___
*[tiering/ctl.c, line 291 at r1](https://reviewable.io/reviews/memkind/memkind/728#-MthTsYG8p_KBtBWxLSN:-MthTsYG8p_KBtBWxLSO:bdfygbj) ([raw file](https://github.com/memkind/memkind/blob/0446e97af91af1d61c60e30f44dcf71280a751e4/tiering/ctl.c#L291)):*
> ```C
>         size_t fsdax_max_size = 0;
>         if (fsdax_size_set &&
>             (fsdax_max_size == 0 || fsdax_max_size > MEMKIND_PMEM_MIN_SIZE)) {
> ```

two lines above there is an initialization of fsdax_max_size to 0, please remove this check


<!-- Sent from Reviewable.io -->

2022-01-18 14:16 UTC, PatKamin requested changes
> Reviewed 1 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/728)* status: all files reviewed, 15 unresolved discussions (waiting on @jacekgrzybek)

___
*[src/memkind_memtier.c, line 426 at r1](https://reviewable.io/reviews/memkind/memkind/728#-MthMCn-948pvObK-fyd:-MthMCn-948pvObK-fye:bowciwr) ([raw file](https://github.com/memkind/memkind/blob/0446e97af91af1d61c60e30f44dcf71280a751e4/src/memkind_memtier.c#L426)):*
> ```C
>     char name_substr[256] = {0};
>     int chr_read = 0;
>     const int chr_read_max = 256;
> ```

Make it uppercase. Use this const  to get numbers 255 or 256.
___
*[src/memkind_memtier.c, line 440 at r1](https://reviewable.io/reviews/memkind/memkind/728#-MthPbTl1d-nA4qHKg-D:-MthPbTl1d-nA4qHKg-E:b-2x5bun) ([raw file](https://github.com/memkind/memkind/blob/0446e97af91af1d61c60e30f44dcf71280a751e4/src/memkind_memtier.c#L440)):*
> ```C
>             ret = sscanf(query, "[%d]%n", &th_indx, &chr_read);
>             if (th_indx >= 0 && chr_read < chr_read_max && chr_read > 0) {
>                 if (th_indx + 1 >= (int)builder->cfg_size) {
> ```

Cast int to unsigned.
___
*[tiering/ctl.c, line 215 at r1](https://reviewable.io/reviews/memkind/memkind/728#-MthR8xP7bjM1JeKpT5f:-MthR8xP7bjM1JeKpT5g:bos5ire) ([raw file](https://github.com/memkind/memkind/blob/0446e97af91af1d61c60e30f44dcf71280a751e4/tiering/ctl.c#L215)):*
> ```C
>             }
>             char *kind_name = strtok_r(NULL, CTL_PARAM_SEPARATOR, &sptr);
>             if (kind_name) {
> ```

If kind_name is NULL then log an error and return -1.
___
*[tiering/ctl.c, line 241 at r1](https://reviewable.io/reviews/memkind/memkind/728#-MthRjr6-TotZp6t6QGA:-MthRjr6-TotZp6t6QGB:bdct2t3) ([raw file](https://github.com/memkind/memkind/blob/0446e97af91af1d61c60e30f44dcf71280a751e4/tiering/ctl.c#L241)):*
> ```C
>                 return -1;
>             }
>             fsdax_path = strtok_r(NULL, CTL_PARAM_SEPARATOR, &sptr);
> ```

Check here if it's an empty string. If yes, log an error and return -1;
___
*[tiering/ctl.c, line 291 at r1](https://reviewable.io/reviews/memkind/memkind/728#-MthSEEP-o9HW1u3XqyP:-MthSEEP-o9HW1u3XqyQ:b32vlw) ([raw file](https://github.com/memkind/memkind/blob/0446e97af91af1d61c60e30f44dcf71280a751e4/tiering/ctl.c#L291)):*
>=
___
*[tiering/ctl.c, line 299 at r1](https://reviewable.io/reviews/memkind/memkind/728#-MthUENRDM5NDA5Njegg:-MthUENRDM5NDA5Njegh:b32vlw) ([raw file](https://github.com/memkind/memkind/blob/0446e97af91af1d61c60e30f44dcf71280a751e4/tiering/ctl.c#L299)):*
>=
___
*[utils/memtier_counter_bench/memtier_counter_bench.cpp, line 100 at r1](https://reviewable.io/reviews/memkind/memkind/728#-MthWzYG4J8JCYO0WjqY:-MthWzYG4J8JCYO0WjqZ:b4kwwbg) ([raw file](https://github.com/memkind/memkind/blob/0446e97af91af1d61c60e30f44dcf71280a751e4/utils/memtier_counter_bench/memtier_counter_bench.cpp#L100)):*
> ```cpp
>     memtier_bench_alloc()
>     {
>         m_tier_builder = memtier_builder_new(MEMTIER_POLICY_STATIC_RATIO);
> ```

Check what was returned here. In case of a NULL, fail the test.


<!-- Sent from Reviewable.io -->

2022-01-19 13:16 UTC, bratpiorka requested changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/728)* status: all files reviewed, 16 unresolved discussions (waiting on @jacekgrzybek)

___
*[src/memkind_memtier.c, line 440 at r1](https://reviewable.io/reviews/memkind/memkind/728#-MthSHgY5RQPOQGGoRXr:-MtmQoKR8EEQbw5RXkoy:b-e0x77b) ([raw file](https://github.com/memkind/memkind/blob/0446e97af91af1d61c60e30f44dcf71280a751e4/src/memkind_memtier.c#L440)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

if we know here that th_indx is >=0 then it would be better to cast it to (unsigned)
</blockquote></details>

builder->cfg_size is already unsigned val. I though rather of "(unsigned)th_indx + 1 >=builder->cfg_size"



_Code quote:_
```C
lder->cfg_size
```
___
*[src/memkind_memtier.c, line 425 at r2](https://reviewable.io/reviews/memkind/memkind/728#-MtmR2gk49hKuVTGO-PH:-MtmR2gk49hKuVTGO-PI:biztepf) ([raw file](https://github.com/memkind/memkind/blob/4d99a30f1d1659c4e4477ab6dc365840a8865ab2/src/memkind_memtier.c#L425)):*
> ```C
>     const int chr_read_max = 256;
>     const char *query = name;
>     char name_substr[chr_read_max] = {0};
> ```

upper case


<!-- Sent from Reviewable.io -->

2022-01-19 13:40 UTC, PatKamin requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/728)* status: all files reviewed, 17 unresolved discussions (waiting on @jacekgrzybek)

___
*[src/memkind_memtier.c, line 440 at r2](https://reviewable.io/reviews/memkind/memkind/728#-MtmYesEBSdyE_6h3sU4:-MtmYesEBSdyE_6h3sU5:b-5l9z7p) ([raw file](https://github.com/memkind/memkind/blob/4d99a30f1d1659c4e4477ab6dc365840a8865ab2/src/memkind_memtier.c#L440)):*
> ```C
>             ret = sscanf(query, "[%d]%n", &th_indx, &chr_read);
>             if (th_indx >= 0 && chr_read < chr_read_max && chr_read > 0) {
>                 if (th_indx + 1 >= (unsigned)builder->cfg_size) {
> ```

Casting unsigned to unsigned doesn't make sense. What I meant is that you should cast an int var to unsigned (given that an int var is greater than or equal to zero), not the other way around.
___
*[tiering/ctl.c, line 299 at r1](https://reviewable.io/reviews/memkind/memkind/728#-MthUENRDM5NDA5Njegg:-MtmZA-wAjFhbv4CtUkU:bytec2y) ([raw file](https://github.com/memkind/memkind/blob/0446e97af91af1d61c60e30f44dcf71280a751e4/tiering/ctl.c#L299)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

>=
</blockquote></details>

fsdax_min_size can be equal to MEMKIND_PMEM_MIN_SIZE


<!-- Sent from Reviewable.io -->

2022-01-20 11:29 UTC, bratpiorka reviewed
> Reviewed 1 of 2 files at r3, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/728)* status: all files reviewed, 16 unresolved discussions (waiting on @jacekgrzybek)



<!-- Sent from Reviewable.io -->

2022-01-21 09:08 UTC, bratpiorka requested changes
> Reviewed 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/728)* status: all files reviewed, 13 unresolved discussions (waiting on @jacekgrzybek)

___
*[tiering/ctl.c, line 234 at r1](https://reviewable.io/reviews/memkind/memkind/728#-MthQ3oL9DzlI8Ilu9MX:-MtvsG_JDn5TnCeAGuy4:brwmequ) ([raw file](https://github.com/memkind/memkind/blob/0446e97af91af1d61c60e30f44dcf71280a751e4/tiering/ctl.c#L234)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

add else with error kind_name == NULL
</blockquote></details>

please add error with info that kind_name == NULL
___
*[tiering/ctl.c, line 288 at r6](https://reviewable.io/reviews/memkind/memkind/728#-MtvsUrC-VG8-sfOcCE7:-MtvsUrC-VG8-sfOcCE8:bygmngp) ([raw file](https://github.com/memkind/memkind/blob/6bb90d8fd2545be4d791b12c0d72c50e1284eadd/tiering/ctl.c#L288)):*
> ```C
>         }
> 
>         if (fsdax_path) {
> ```

you don't need to check it once again, it should be != NULL here
___
*[utils/memtier_counter_bench/memtier_counter_bench.cpp, line 104 at r6](https://reviewable.io/reviews/memkind/memkind/728#-Mtvt5ob75ae8NDd_ZtS:-Mtvt5ob75ae8NDd_ZtT:b-uhykgq) ([raw file](https://github.com/memkind/memkind/blob/6bb90d8fd2545be4d791b12c0d72c50e1284eadd/utils/memtier_counter_bench/memtier_counter_bench.cpp#L104)):*
> ```cpp
>             assert(0);
>         memtier_builder_add_tier(m_tier_builder, MEMKIND_DEFAULT, 1);
>         if (m_tier_builder) {
> ```

you don't have to check it



_Code quote:_
```cpp
if (m_tier_builder) {
```


<!-- Sent from Reviewable.io -->

2022-01-21 12:29 UTC, jacekgrzybek reviewed
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/728)* status: 2 of 3 files reviewed, 13 unresolved discussions (waiting on @bratpiorka, @jacekgrzybek, and @PatKamin)

___
*[src/memkind_memtier.c, line 440 at r1](https://reviewable.io/reviews/memkind/memkind/728#-MthPbTl1d-nA4qHKg-D:-MtwbAdOBaCnKwyBeXLg:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/0446e97af91af1d61c60e30f44dcf71280a751e4/src/memkind_memtier.c#L440)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Cast int to unsigned.
</blockquote></details>

Done.
___
*[src/memkind_memtier.c, line 440 at r2](https://reviewable.io/reviews/memkind/memkind/728#-MtmYesEBSdyE_6h3sU4:-MtwbERuETKuUQrpRdBh:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/4d99a30f1d1659c4e4477ab6dc365840a8865ab2/src/memkind_memtier.c#L440)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Casting unsigned to unsigned doesn't make sense. What I meant is that you should cast an int var to unsigned (given that an int var is greater than or equal to zero), not the other way around.
</blockquote></details>

Done.
___
*[tiering/ctl.c, line 288 at r6](https://reviewable.io/reviews/memkind/memkind/728#-MtvsUrC-VG8-sfOcCE7:-Mtw_l8PEMKmTKKUA0yj:b-fyjqx9) ([raw file](https://github.com/memkind/memkind/blob/6bb90d8fd2545be4d791b12c0d72c50e1284eadd/tiering/ctl.c#L288)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

you don't need to check it once again, it should be != NULL here
</blockquote></details>

klocwork marks this place as issue
___
*[utils/memtier_counter_bench/memtier_counter_bench.cpp, line 100 at r1](https://reviewable.io/reviews/memkind/memkind/728#-MthWzYG4J8JCYO0WjqY:-Mtwb3GY-yIm-Yh7KdGE:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/0446e97af91af1d61c60e30f44dcf71280a751e4/utils/memtier_counter_bench/memtier_counter_bench.cpp#L100)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Check what was returned here. In case of a NULL, fail the test.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-01-21 12:58 UTC, bratpiorka requested changes
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/728)* status: all files reviewed, 12 unresolved discussions (waiting on @jacekgrzybek and @PatKamin)

___
*[tiering/ctl.c, line 234 at r1](https://reviewable.io/reviews/memkind/memkind/728#-MthQ3oL9DzlI8Ilu9MX:-MtwhGsP1H7VhSvA1Mwl:b5xjyf) ([raw file](https://github.com/memkind/memkind/blob/0446e97af91af1d61c60e30f44dcf71280a751e4/tiering/ctl.c#L234)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

please add error with info that kind_name == NULL
</blockquote></details>

you are testing if (kind_name) above, so here just simple "else" will be enough
___
*[tiering/ctl.c, line 288 at r6](https://reviewable.io/reviews/memkind/memkind/728#-MtvsUrC-VG8-sfOcCE7:-MtwheIU6UQC-LKKFgwy:b32wtd) ([raw file](https://github.com/memkind/memkind/blob/6bb90d8fd2545be4d791b12c0d72c50e1284eadd/tiering/ctl.c#L288)):*
<details><summary><i>Previously, jacekgrzybek (Jacek Grzybek) wrote…</i></summary><blockquote>

klocwork marks this place as issue
</blockquote></details>

ok


<!-- Sent from Reviewable.io -->

2022-01-24 21:23 UTC, jacekgrzybek reviewed
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/728)* status: all files reviewed, 12 unresolved discussions (waiting on @bratpiorka, @jacekgrzybek, and @PatKamin)

___
*[src/memkind_memtier.c, line 426 at r1](https://reviewable.io/reviews/memkind/memkind/728#-MthMCn-948pvObK-fyd:-MuCwxZo0itnym8UB9HC:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/0446e97af91af1d61c60e30f44dcf71280a751e4/src/memkind_memtier.c#L426)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Make it uppercase. Use this const  to get numbers 255 or 256.
</blockquote></details>

Done.
___
*[src/memkind_memtier.c, line 432 at r1](https://reviewable.io/reviews/memkind/memkind/728#-MthS1DtCfUrTE4YVq7l:-MuCx2uQ9_Xl4OKG66Kt:b-nbma99) ([raw file](https://github.com/memkind/memkind/blob/0446e97af91af1d61c60e30f44dcf71280a751e4/src/memkind_memtier.c#L432)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

why 255?
</blockquote></details>

to stay in array size limit, should i change it to 256?


<!-- Sent from Reviewable.io -->

2022-01-24 22:19 UTC, jacekgrzybek reviewed
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/728)* status: 2 of 3 files reviewed, 12 unresolved discussions (waiting on @bratpiorka, @jacekgrzybek, and @PatKamin)

___
*[src/memkind_memtier.c, line 424 at r1](https://reviewable.io/reviews/memkind/memkind/728#-MthRDur3ieMmtM6289i:-MuDA2sHASQ-mrwp-qIx:bb7f2mf) ([raw file](https://github.com/memkind/memkind/blob/0446e97af91af1d61c60e30f44dcf71280a751e4/src/memkind_memtier.c#L424)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

set size of this array using chr_read_max
</blockquote></details>

done
___
*[src/memkind_memtier.c, line 439 at r1](https://reviewable.io/reviews/memkind/memkind/728#-MthRShg-MSznwIILzNx:-MuD8ALfDi4dimjSp2OG:b-8f5pjy) ([raw file](https://github.com/memkind/memkind/blob/0446e97af91af1d61c60e30f44dcf71280a751e4/src/memkind_memtier.c#L439)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

this second check is needed?
</blockquote></details>

you are right, klocwork doesn't mark this after delete 
___
*[src/memkind_memtier.c, line 440 at r1](https://reviewable.io/reviews/memkind/memkind/728#-MthSHgY5RQPOQGGoRXr:-MuD7wPL4GdzebFbyNYD:b-7rl0kd) ([raw file](https://github.com/memkind/memkind/blob/0446e97af91af1d61c60e30f44dcf71280a751e4/src/memkind_memtier.c#L440)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

builder->cfg_size is already unsigned val. I though rather of "(unsigned)th_indx + 1 >=builder->cfg_size"
</blockquote></details>

done


<!-- Sent from Reviewable.io -->

2022-01-24 22:36 UTC, jacekgrzybek reviewed
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/728)* status: 1 of 3 files reviewed, 12 unresolved discussions (waiting on @bratpiorka, @jacekgrzybek, and @PatKamin)

___
*[tiering/ctl.c, line 215 at r1](https://reviewable.io/reviews/memkind/memkind/728#-MthR8xP7bjM1JeKpT5f:-MuDCEbm3JUSSWEwhc6q:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/0446e97af91af1d61c60e30f44dcf71280a751e4/tiering/ctl.c#L215)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

If kind_name is NULL then log an error and return -1.
</blockquote></details>

Done.
___
*[tiering/ctl.c, line 234 at r1](https://reviewable.io/reviews/memkind/memkind/728#-MthQ3oL9DzlI8Ilu9MX:-MuDCm8N3j2PKcwuMcTD:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/0446e97af91af1d61c60e30f44dcf71280a751e4/tiering/ctl.c#L234)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

you are testing if (kind_name) above, so here just simple "else" will be enough
</blockquote></details>

Done.
___
*[tiering/ctl.c, line 241 at r1](https://reviewable.io/reviews/memkind/memkind/728#-MthRjr6-TotZp6t6QGA:-MuDCohO1SCcwvXL-jI9:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/0446e97af91af1d61c60e30f44dcf71280a751e4/tiering/ctl.c#L241)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Check here if it's an empty string. If yes, log an error and return -1;
</blockquote></details>

Done.
___
*[tiering/ctl.c, line 283 at r1](https://reviewable.io/reviews/memkind/memkind/728#-MthQV0BE6qLQXeoyyMG:-MuDD5gtATA0zI0cICNm:b-ti31aw) ([raw file](https://github.com/memkind/memkind/blob/0446e97af91af1d61c60e30f44dcf71280a751e4/tiering/ctl.c#L283)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

maybe you could add validation of "fsdax_path" and error after "fsdax_path = strtok_r(NULL, CTL_PARAM_SEPARATOR, &sptr)"
</blockquote></details>

error message is done
___
*[tiering/ctl.c, line 291 at r1](https://reviewable.io/reviews/memkind/memkind/728#-MthTsYG8p_KBtBWxLSN:-MuDDK857aREjfkmuQx-:bb7f2mf) ([raw file](https://github.com/memkind/memkind/blob/0446e97af91af1d61c60e30f44dcf71280a751e4/tiering/ctl.c#L291)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

two lines above there is an initialization of fsdax_max_size to 0, please remove this check
</blockquote></details>

done
___
*[tiering/ctl.c, line 356 at r1](https://reviewable.io/reviews/memkind/memkind/728#-MthQk_09l27zsUlBsX3:-MuDDhrW7DeDCz6u_qdJ:b-lsmxdu) ([raw file](https://github.com/memkind/memkind/blob/0446e97af91af1d61c60e30f44dcf71280a751e4/tiering/ctl.c#L356)):*
> fsdax_max_size 
___
*[utils/memtier_counter_bench/memtier_counter_bench.cpp, line 104 at r6](https://reviewable.io/reviews/memkind/memkind/728#-Mtvt5ob75ae8NDd_ZtS:-MuDDkte42hEhol0tias:b-ra4nr9) ([raw file](https://github.com/memkind/memkind/blob/6bb90d8fd2545be4d791b12c0d72c50e1284eadd/utils/memtier_counter_bench/memtier_counter_bench.cpp#L104)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

you don't have to check it
</blockquote></details>

no in this place is still issue 


<!-- Sent from Reviewable.io -->

2022-01-25 08:11 UTC, bratpiorka requested changes
> Reviewed 1 of 1 files at r8, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/728)* status: all files reviewed, 10 unresolved discussions (waiting on @jacekgrzybek and @PatKamin)

___
*[src/memkind_memtier.c, line 432 at r1](https://reviewable.io/reviews/memkind/memkind/728#-MthS1DtCfUrTE4YVq7l:-MuFHXDz0P3nT-nnG-5p:b8c8qr2) ([raw file](https://github.com/memkind/memkind/blob/0446e97af91af1d61c60e30f44dcf71280a751e4/src/memkind_memtier.c#L432)):*
<details><summary><i>Previously, jacekgrzybek (Jacek Grzybek) wrote…</i></summary><blockquote>

to stay in array size limit, should i change it to 256?
</blockquote></details>

hm 255 is ok
___
*[src/memkind_memtier.c, line 439 at r1](https://reviewable.io/reviews/memkind/memkind/728#-MthRShg-MSznwIILzNx:-MuFFKr30a9YOnMLVstA:bi6hmm0) ([raw file](https://github.com/memkind/memkind/blob/0446e97af91af1d61c60e30f44dcf71280a751e4/src/memkind_memtier.c#L439)):*
<details><summary><i>Previously, jacekgrzybek (Jacek Grzybek) wrote…</i></summary><blockquote>

you are right, klocwork doesn't mark this after delete 
</blockquote></details>

by "second check" I meant check of chr_read val, so both min and max tests. Please note that you already tested also " chr_read < CHR_READ_MAX" few lines above 



_Code quote:_
```C
 chr_read < CHR_READ_MAX
```


<!-- Sent from Reviewable.io -->

2022-01-25 10:30 UTC, PatKamin requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/728)* status: all files reviewed, 10 unresolved discussions (waiting on @jacekgrzybek and @PatKamin)

___
*[src/memkind_memtier.c, line 433 at r9](https://reviewable.io/reviews/memkind/memkind/728#-MuFK1rY5G9t4imGALmu:-MuFK1rY5G9t4imGALmv:b-4nk6xa) ([raw file](https://github.com/memkind/memkind/blob/c2c5e3f2fa8606e370ded6001aa16f5332de1fa3/src/memkind_memtier.c#L433)):*
> ```C
>         query += chr_read;
> 
>         int ret = sscanf(query, "%255[^\[]%n", name_substr, &chr_read);
> ```

Use `CHR_READ_MAX -1` instead of 255.
___
*[tiering/ctl.c, line 235 at r9](https://reviewable.io/reviews/memkind/memkind/728#-MuFKiGA9fkw0q5UfLBM:-MuFKiGA9fkw0q5UfLBN:b-72sn6d) ([raw file](https://github.com/memkind/memkind/blob/c2c5e3f2fa8606e370ded6001aa16f5332de1fa3/tiering/ctl.c#L235)):*
> ```C
>                 }
>             } else {
>                 log_err("Kind name is NULL");
> ```

Please, be a bit more precise in the log message. See other messages in this file.
___
*[tiering/ctl.c, line 246 at r9](https://reviewable.io/reviews/memkind/memkind/728#-MuFMPmF8ifCy-jI4Grp:-MuFMPmF8ifCy-jI4Grq:b3kqx) ([raw file](https://github.com/memkind/memkind/blob/c2c5e3f2fa8606e370ded6001aa16f5332de1fa3/tiering/ctl.c#L246)):*
> ```C
>             fsdax_path = strtok_r(NULL, CTL_PARAM_SEPARATOR, &sptr);
>             if (fsdax_path == NULL) {
>                 log_err("PATH is empty");
> ```

.
___
*[tiering/ctl.c, line 290 at r9](https://reviewable.io/reviews/memkind/memkind/728#-MuFRGT46scnqPfN-2tA:-MuFNAnG4w9ff_1Qyx2x:b8i1fhn) ([raw file](https://github.com/memkind/memkind/blob/c2c5e3f2fa8606e370ded6001aa16f5332de1fa3/tiering/ctl.c#L290)):*
> ```C
>         }
> 
>         if (fsdax_path) {
> ```

Probably not needed. You already return in case fsdax_path is NULL.
___
*[utils/memtier_counter_bench/memtier_counter_bench.cpp, line 102 at r9](https://reviewable.io/reviews/memkind/memkind/728#-MuFSZtP6x0m2yRBrv0K:-MuFSZtP6x0m2yRBrv0L:baeqsv3) ([raw file](https://github.com/memkind/memkind/blob/c2c5e3f2fa8606e370ded6001aa16f5332de1fa3/utils/memtier_counter_bench/memtier_counter_bench.cpp#L102)):*
> ```cpp
>         m_tier_builder = memtier_builder_new(MEMTIER_POLICY_STATIC_RATIO);
>         if (m_tier_builder == NULL)
>             assert(0);
> ```

The if-clause is not needed. Use an assert and add a log message.
___
*[utils/memtier_counter_bench/memtier_counter_bench.cpp, line 104 at r9](https://reviewable.io/reviews/memkind/memkind/728#-MuFSsV5DrSc2_FHftL2:-MuFSsV5DrSc2_FHftL3:bub8p3a) ([raw file](https://github.com/memkind/memkind/blob/c2c5e3f2fa8606e370ded6001aa16f5332de1fa3/utils/memtier_counter_bench/memtier_counter_bench.cpp#L104)):*
> ```cpp
>             assert(0);
>         memtier_builder_add_tier(m_tier_builder, MEMKIND_DEFAULT, 1);
>         if (m_tier_builder) {
> ```

Fail the test if NULL.
___
*[utils/memtier_counter_bench/memtier_counter_bench.cpp, line 146 at r9](https://reviewable.io/reviews/memkind/memkind/728#-MuFm9ACBkNKi3zwTyIg:-MuFm9AD2Z6JSTa0m7WK:b-xmy213) ([raw file](https://github.com/memkind/memkind/blob/c2c5e3f2fa8606e370ded6001aa16f5332de1fa3/utils/memtier_counter_bench/memtier_counter_bench.cpp#L146)):*
> ```cpp
>                 memtier_builder_construct_memtier_memory(m_tier_builder);
>         } else {
>             m_tier_memory = NULL;
> ```

Fail the tests.


<!-- Sent from Reviewable.io -->

2022-01-25 11:14 UTC, bratpiorka approved these changes
> Reviewed 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/728)* status: all files reviewed, 8 unresolved discussions (waiting on @jacekgrzybek and @PatKamin)



<!-- Sent from Reviewable.io -->

2022-01-26 07:46 UTC, bratpiorka approved these changes
> Reviewed 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/728)* status: all files reviewed, 8 unresolved discussions (waiting on @jacekgrzybek and @PatKamin)



<!-- Sent from Reviewable.io -->

2022-01-27 08:06 UTC, bratpiorka approved these changes
> Reviewed 1 of 1 files at r12, 3 of 3 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/728)* status: all files reviewed, 8 unresolved discussions (waiting on @jacekgrzybek and @PatKamin)



<!-- Sent from Reviewable.io -->

2022-01-27 09:27 UTC, bratpiorka reviewed
> Reviewed 1 of 1 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/728)* status: all files reviewed, 8 unresolved discussions (waiting on @jacekgrzybek and @PatKamin)



<!-- Sent from Reviewable.io -->

2022-01-27 09:29 UTC, jacekgrzybek reviewed
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/728)* status: 2 of 3 files reviewed, 8 unresolved discussions (waiting on @bratpiorka, @jacekgrzybek, and @PatKamin)

___
*[tiering/ctl.c, line 235 at r9](https://reviewable.io/reviews/memkind/memkind/728#-MuFKiGA9fkw0q5UfLBM:-MuPrFGc6WRT3tCgB5q6:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/c2c5e3f2fa8606e370ded6001aa16f5332de1fa3/tiering/ctl.c#L235)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Please, be a bit more precise in the log message. See other messages in this file.
</blockquote></details>

Done.
___
*[utils/memtier_counter_bench/memtier_counter_bench.cpp, line 102 at r9](https://reviewable.io/reviews/memkind/memkind/728#-MuFSZtP6x0m2yRBrv0K:-MuPrUIiEYNV50x2jMjS:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/c2c5e3f2fa8606e370ded6001aa16f5332de1fa3/utils/memtier_counter_bench/memtier_counter_bench.cpp#L102)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

The if-clause is not needed. Use an assert and add a log message.
</blockquote></details>

Done.
___
*[utils/memtier_counter_bench/memtier_counter_bench.cpp, line 104 at r9](https://reviewable.io/reviews/memkind/memkind/728#-MuFSsV5DrSc2_FHftL2:-MuPrWCw4F3tmbUupHjn:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/c2c5e3f2fa8606e370ded6001aa16f5332de1fa3/utils/memtier_counter_bench/memtier_counter_bench.cpp#L104)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Fail the test if NULL.
</blockquote></details>

Done.
___
*[utils/memtier_counter_bench/memtier_counter_bench.cpp, line 146 at r9](https://reviewable.io/reviews/memkind/memkind/728#-MuFm9ACBkNKi3zwTyIg:-MuPrWem1P9dwSKShJxe:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/c2c5e3f2fa8606e370ded6001aa16f5332de1fa3/utils/memtier_counter_bench/memtier_counter_bench.cpp#L146)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Fail the tests.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-01-27 11:19 UTC, PatKamin requested changes
> Reviewed 1 of 3 files at r13, 1 of 1 files at r16, 1 of 1 files at r17, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/728)* status: all files reviewed, 9 unresolved discussions (waiting on @jacekgrzybek)

___
*[src/memkind_memtier.c, line 426 at r16](https://reviewable.io/reviews/memkind/memkind/728#-MuQC1f2EKcoqVcnwI6B:-MuQC1f2EKcoqVcnwI6C:bdk7ku9) ([raw file](https://github.com/memkind/memkind/blob/9790f3d7942f60ac4323c23829ef2d20519a8938/src/memkind_memtier.c#L426)):*
> ```C
>     const char *query = name;
>     char name_substr[CHR_READ_MAX];
>     memset(name_substr, 0, CHR_READ_MAX * sizeof(char));
> ```

Why is this needed?
___
*[src/memkind_memtier.c, line 450 at r17](https://reviewable.io/reviews/memkind/memkind/728#-MuQDWXv-Cj_efs7oFq4:-MuQDWXv-Cj_efs7oFq5:b-d1e9er) ([raw file](https://github.com/memkind/memkind/blob/256c54f9868e5f56c77df8f56710e1dba833fa94/src/memkind_memtier.c#L450)):*
> ```C
>                 struct memtier_threshold_cfg *thres = &builder->thres[th_indx];
> 
>                 ret = sscanf(query, ".%255s", name_substr);
> ```

Don't introduce a magic number.
___
*[tiering/ctl.c, line 235 at r9](https://reviewable.io/reviews/memkind/memkind/728#-MuFKiGA9fkw0q5UfLBM:-MuQDqRi8afO70pQvDIs:b-pfcyxg) ([raw file](https://github.com/memkind/memkind/blob/c2c5e3f2fa8606e370ded6001aa16f5332de1fa3/tiering/ctl.c#L235)):*
<details><summary><i>Previously, jacekgrzybek (Jacek Grzybek) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Kind_name is not the name of this param.
___
*[utils/memtier_counter_bench/memtier_counter_bench.cpp, line 102 at r9](https://reviewable.io/reviews/memkind/memkind/728#-MuFSZtP6x0m2yRBrv0K:-MuQEyjg47NORWg0zZzu:bq1hnwi) ([raw file](https://github.com/memkind/memkind/blob/c2c5e3f2fa8606e370ded6001aa16f5332de1fa3/utils/memtier_counter_bench/memtier_counter_bench.cpp#L102)):*
> add a log message.
___
*[utils/memtier_counter_bench/memtier_counter_bench.cpp, line 146 at r9](https://reviewable.io/reviews/memkind/memkind/728#-MuFm9ACBkNKi3zwTyIg:-MuQFddKEfCaShplcXkT:byy0gzn) ([raw file](https://github.com/memkind/memkind/blob/c2c5e3f2fa8606e370ded6001aa16f5332de1fa3/utils/memtier_counter_bench/memtier_counter_bench.cpp#L146)):*
<details><summary><i>Previously, jacekgrzybek (Jacek Grzybek) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Fail before trying to add tiers to the m_tier_builder which could be NULL. Print the message.
___
*[utils/memtier_counter_bench/memtier_counter_bench.cpp, line 103 at r17](https://reviewable.io/reviews/memkind/memkind/728#-MuQFR7TBhMNEKqRlkfW:-MuQFR7TBhMNEKqRlkfX:b8l8i0j) ([raw file](https://github.com/memkind/memkind/blob/256c54f9868e5f56c77df8f56710e1dba833fa94/utils/memtier_counter_bench/memtier_counter_bench.cpp#L103)):*
> ```cpp
>         assert(m_tier_builder != NULL);
>         memtier_builder_add_tier(m_tier_builder, MEMKIND_DEFAULT, 1);
>         m_tier_memory =
> ```

Fail the test if NULL. Print a message.



_Code quote:_
```cpp
        m_tier_memory =
            memtier_builder_construct_memtier_memory(m_tier_builder);
```


<!-- Sent from Reviewable.io -->

2022-01-28 08:28 UTC, jacekgrzybek reviewed
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/728)* status: 1 of 3 files reviewed, 9 unresolved discussions (waiting on @bratpiorka, @jacekgrzybek, and @PatKamin)

___
*[src/memkind_memtier.c, line 433 at r9](https://reviewable.io/reviews/memkind/memkind/728#-MuFK1rY5G9t4imGALmu:-MuUmAowBSqMRD3j1v6m:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/c2c5e3f2fa8606e370ded6001aa16f5332de1fa3/src/memkind_memtier.c#L433)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Use `CHR_READ_MAX -1` instead of 255.
</blockquote></details>

Done.
___
*[src/memkind_memtier.c, line 426 at r16](https://reviewable.io/reviews/memkind/memkind/728#-MuQC1f2EKcoqVcnwI6B:-MuUn-HmCKZjOcbg4JeK:bp84gjq) ([raw file](https://github.com/memkind/memkind/blob/9790f3d7942f60ac4323c23829ef2d20519a8938/src/memkind_memtier.c#L426)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Why is this needed?
</blockquote></details>

there was fails without it
___
*[src/memkind_memtier.c, line 450 at r17](https://reviewable.io/reviews/memkind/memkind/728#-MuQDWXv-Cj_efs7oFq4:-MuUmKbc1X1MyoZl5cEx:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/256c54f9868e5f56c77df8f56710e1dba833fa94/src/memkind_memtier.c#L450)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Don't introduce a magic number.
</blockquote></details>

Done.
___
*[tiering/ctl.c, line 299 at r1](https://reviewable.io/reviews/memkind/memkind/728#-MthUENRDM5NDA5Njegg:-MuUmrt-2v8oskDzTl6c:bb7f2mf) ([raw file](https://github.com/memkind/memkind/blob/0446e97af91af1d61c60e30f44dcf71280a751e4/tiering/ctl.c#L299)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

fsdax_min_size can be equal to MEMKIND_PMEM_MIN_SIZE
</blockquote></details>

done
___
*[utils/memtier_counter_bench/memtier_counter_bench.cpp, line 102 at r9](https://reviewable.io/reviews/memkind/memkind/728#-MuFSZtP6x0m2yRBrv0K:-MuUmupm6yQBUPvtE7sb:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/c2c5e3f2fa8606e370ded6001aa16f5332de1fa3/utils/memtier_counter_bench/memtier_counter_bench.cpp#L102)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

> add a log message.
</blockquote></details>

Done.
___
*[utils/memtier_counter_bench/memtier_counter_bench.cpp, line 146 at r9](https://reviewable.io/reviews/memkind/memkind/728#-MuFm9ACBkNKi3zwTyIg:-MuUmxgX0ZWlEJESn-fB:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/c2c5e3f2fa8606e370ded6001aa16f5332de1fa3/utils/memtier_counter_bench/memtier_counter_bench.cpp#L146)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Fail before trying to add tiers to the m_tier_builder which could be NULL. Print the message.
</blockquote></details>

Done.
___
*[utils/memtier_counter_bench/memtier_counter_bench.cpp, line 103 at r17](https://reviewable.io/reviews/memkind/memkind/728#-MuQFR7TBhMNEKqRlkfW:-MuUmwDb0SyD9QWiLLLL:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/256c54f9868e5f56c77df8f56710e1dba833fa94/utils/memtier_counter_bench/memtier_counter_bench.cpp#L103)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Fail the test if NULL. Print a message.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-01-28 08:31 UTC, bratpiorka reviewed
> Reviewed 2 of 2 files at r18, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/728)* status: all files reviewed, 9 unresolved discussions (waiting on @jacekgrzybek and @PatKamin)



<!-- Sent from Reviewable.io -->

2022-01-28 09:18 UTC, jacekgrzybek reviewed
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/728)* status: 1 of 3 files reviewed, 9 unresolved discussions (waiting on @bratpiorka, @jacekgrzybek, and @PatKamin)

___
*[tiering/ctl.c, line 235 at r9](https://reviewable.io/reviews/memkind/memkind/728#-MuFKiGA9fkw0q5UfLBM:-MuUx98c-mmeHH8xgFjc:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/c2c5e3f2fa8606e370ded6001aa16f5332de1fa3/tiering/ctl.c#L235)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Kind_name is not the name of this param.
</blockquote></details>

Done.
___
*[tiering/ctl.c, line 246 at r9](https://reviewable.io/reviews/memkind/memkind/728#-MuFMPmF8ifCy-jI4Grp:-MuUxAgw2Q-KjYcF8gNU:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/c2c5e3f2fa8606e370ded6001aa16f5332de1fa3/tiering/ctl.c#L246)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-01-28 09:20 UTC, bratpiorka approved these changes
> Reviewed 2 of 2 files at r19, 1 of 1 files at r20, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/728)* status: all files reviewed, 9 unresolved discussions (waiting on @jacekgrzybek and @PatKamin)



<!-- Sent from Reviewable.io -->

2022-01-28 09:30 UTC, PatKamin requested changes
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/728)* status: 1 of 3 files reviewed, 14 unresolved discussions (waiting on @bratpiorka, @jacekgrzybek, and @PatKamin)

___
*[src/memkind_memtier.c, line 426 at r16](https://reviewable.io/reviews/memkind/memkind/728#-MuQC1f2EKcoqVcnwI6B:-MuUxJ5527f99v5f4H6W:bxfky8l) ([raw file](https://github.com/memkind/memkind/blob/9790f3d7942f60ac4323c23829ef2d20519a8938/src/memkind_memtier.c#L426)):*
<details><summary><i>Previously, jacekgrzybek (Jacek Grzybek) wrote…</i></summary><blockquote>

there was fails without it
</blockquote></details>

Remove the comment.
___
*[src/memkind_memtier.c, line 450 at r18](https://reviewable.io/reviews/memkind/memkind/728#-MuUyJqN6tRbfOmvavGZ:-MuUyJqOCmvzZ90b7ACr:b9ask29) ([raw file](https://github.com/memkind/memkind/blob/7ebad1dde1b40a3511cdf424c3f9fabf2117327a/src/memkind_memtier.c#L450)):*
> ```C
>                 struct memtier_threshold_cfg *thres = &builder->thres[th_indx];
> 
>                 sprintf(buffer, "%s%d%s", ".%", CHR_READ_MAX - 1, "s");
> ```

This buffer is not used.
___
*[utils/memtier_counter_bench/memtier_counter_bench.cpp, line 102 at r9](https://reviewable.io/reviews/memkind/memkind/728#-MuFSZtP6x0m2yRBrv0K:-MuUz7gy4kho76zxUPKr:b-tg04er) ([raw file](https://github.com/memkind/memkind/blob/c2c5e3f2fa8606e370ded6001aa16f5332de1fa3/utils/memtier_counter_bench/memtier_counter_bench.cpp#L102)):*
<details><summary><i>Previously, jacekgrzybek (Jacek Grzybek) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

nit: nullptr
___
*[utils/memtier_counter_bench/memtier_counter_bench.cpp, line 102 at r18](https://reviewable.io/reviews/memkind/memkind/728#-MuUzWXv7deDIGbRWmOc:-MuUzWXv7deDIGbRWmOd:b-obghpc) ([raw file](https://github.com/memkind/memkind/blob/7ebad1dde1b40a3511cdf424c3f9fabf2117327a/utils/memtier_counter_bench/memtier_counter_bench.cpp#L102)):*
> ```cpp
>         m_tier_builder = memtier_builder_new(MEMTIER_POLICY_STATIC_RATIO);
>         assert(m_tier_builder != NULL &&
>                "m_tier_builder parameter is not defined");
> ```

"failed to create memtier builder" or sth similar
___
*[utils/memtier_counter_bench/memtier_counter_bench.cpp, line 106 at r18](https://reviewable.io/reviews/memkind/memkind/728#-MuUzo3c2z7ilz-kdP5O:-MuUzo3c2z7ilz-kdP5P:b-tg04er) ([raw file](https://github.com/memkind/memkind/blob/7ebad1dde1b40a3511cdf424c3f9fabf2117327a/utils/memtier_counter_bench/memtier_counter_bench.cpp#L106)):*
> ```cpp
>         m_tier_memory =
>             memtier_builder_construct_memtier_memory(m_tier_builder);
>         assert(m_tier_memory != NULL &&
> ```

nit: nullptr
___
*[utils/memtier_counter_bench/memtier_counter_bench.cpp, line 107 at r18](https://reviewable.io/reviews/memkind/memkind/728#-MuUzu5YE-rzQmPK0m0m:-MuUzu5YE-rzQmPK0m0n:b-nzywpq) ([raw file](https://github.com/memkind/memkind/blob/7ebad1dde1b40a3511cdf424c3f9fabf2117327a/utils/memtier_counter_bench/memtier_counter_bench.cpp#L107)):*
> ```cpp
>             memtier_builder_construct_memtier_memory(m_tier_builder);
>         assert(m_tier_memory != NULL &&
>                "m_tier_memory parameter is not defined");
> ```

"failed to create memtier memory" or sth similar
___
*[utils/memtier_counter_bench/memtier_counter_bench.cpp, line 138 at r18](https://reviewable.io/reviews/memkind/memkind/728#-MuV-GN41ReK4KQwpTFx:-MuV-GN41ReK4KQwpTFy:b-tg04er) ([raw file](https://github.com/memkind/memkind/blob/7ebad1dde1b40a3511cdf424c3f9fabf2117327a/utils/memtier_counter_bench/memtier_counter_bench.cpp#L138)):*
> ```cpp
>     {
>         m_tier_builder = memtier_builder_new(policy);
>         assert(m_tier_builder != NULL &&
> ```

nit: nullptr
___
*[utils/memtier_counter_bench/memtier_counter_bench.cpp, line 139 at r18](https://reviewable.io/reviews/memkind/memkind/728#-MuV-Mu_39Rt6hHaAG5l:-MuV-Mu_39Rt6hHaAG5m:b3kqx) ([raw file](https://github.com/memkind/memkind/blob/7ebad1dde1b40a3511cdf424c3f9fabf2117327a/utils/memtier_counter_bench/memtier_counter_bench.cpp#L139)):*
> ```cpp
>         m_tier_builder = memtier_builder_new(policy);
>         assert(m_tier_builder != NULL &&
>                "m_tier_builder parameter is not defined");
> ```

.
___
*[utils/memtier_counter_bench/memtier_counter_bench.cpp, line 142 at r18](https://reviewable.io/reviews/memkind/memkind/728#-MuV-jg25mqPfCZSYMrR:-MuV-jg25mqPfCZSYMrS:bzfn9yn) ([raw file](https://github.com/memkind/memkind/blob/7ebad1dde1b40a3511cdf424c3f9fabf2117327a/utils/memtier_counter_bench/memtier_counter_bench.cpp#L142)):*
> ```cpp
>         memtier_builder_add_tier(m_tier_builder, MEMKIND_DEFAULT, 1);
>         memtier_builder_add_tier(m_tier_builder, MEMKIND_REGULAR, 1);
>         if (m_tier_builder) {
> ```

Check not needed.
___
*[utils/memtier_counter_bench/memtier_counter_bench.cpp, line 143 at r18](https://reviewable.io/reviews/memkind/memkind/728#-MuV-prd6Ub6pFZjfpZI:-MuV-prd6Ub6pFZjfpZJ:bw16xr9) ([raw file](https://github.com/memkind/memkind/blob/7ebad1dde1b40a3511cdf424c3f9fabf2117327a/utils/memtier_counter_bench/memtier_counter_bench.cpp#L143)):*
> ```cpp
>         memtier_builder_add_tier(m_tier_builder, MEMKIND_REGULAR, 1);
>         if (m_tier_builder) {
>             m_tier_memory =
> ```

Check the result.
___
*[utils/memtier_counter_bench/memtier_counter_bench.cpp, line 146 at r18](https://reviewable.io/reviews/memkind/memkind/728#-MuV-Hp592QbV0VEODNA:-MuV-Hp592QbV0VEODNB:b-tg04er) ([raw file](https://github.com/memkind/memkind/blob/7ebad1dde1b40a3511cdf424c3f9fabf2117327a/utils/memtier_counter_bench/memtier_counter_bench.cpp#L146)):*
> ```cpp
>                 memtier_builder_construct_memtier_memory(m_tier_builder);
>         } else {
>             m_tier_memory = NULL;
> ```

nit: nullptr


<!-- Sent from Reviewable.io -->

2022-01-28 09:32 UTC, jacekgrzybek reviewed
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/728)* status: 1 of 3 files reviewed, 14 unresolved discussions (waiting on @bratpiorka, @jacekgrzybek, and @PatKamin)

___
*[src/memkind_memtier.c, line 439 at r1](https://reviewable.io/reviews/memkind/memkind/728#-MthRShg-MSznwIILzNx:-MuV0ff06qNRdQvU1ZFT:buy5q6p) ([raw file](https://github.com/memkind/memkind/blob/0446e97af91af1d61c60e30f44dcf71280a751e4/src/memkind_memtier.c#L439)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

by "second check" I meant check of chr_read val, so both min and max tests. Please note that you already tested also " chr_read < CHR_READ_MAX" few lines above 
</blockquote></details>

it makes an issue



_Code quote:_
```C
if (th_indx >= 0
```


<!-- Sent from Reviewable.io -->

2022-01-28 12:00 UTC, bratpiorka approved these changes
> Reviewed 2 of 2 files at r22, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/728)* status: all files reviewed, 14 unresolved discussions (waiting on @jacekgrzybek and @PatKamin)

___
*[src/memkind_memtier.c, line 439 at r1](https://reviewable.io/reviews/memkind/memkind/728#-MthRShg-MSznwIILzNx:-MuVYiTu1h4qPTrncHR2:b2ni9ah) ([raw file](https://github.com/memkind/memkind/blob/0446e97af91af1d61c60e30f44dcf71280a751e4/src/memkind_memtier.c#L439)):*
<details><summary><i>Previously, jacekgrzybek (Jacek Grzybek) wrote…</i></summary><blockquote>

it makes an issue
</blockquote></details>

ok


<!-- Sent from Reviewable.io -->

2022-01-28 13:11 UTC, jacekgrzybek reviewed
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/728)* status: 2 of 3 files reviewed, 11 unresolved discussions (waiting on @bratpiorka, @jacekgrzybek, and @PatKamin)

___
*[src/memkind_memtier.c, line 450 at r18](https://reviewable.io/reviews/memkind/memkind/728#-MuUyJqN6tRbfOmvavGZ:-MuVm5VW18pcydqTY6gQ:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/7ebad1dde1b40a3511cdf424c3f9fabf2117327a/src/memkind_memtier.c#L450)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

This buffer is not used.
</blockquote></details>

Done.
___
*[tiering/ctl.c, line 291 at r1](https://reviewable.io/reviews/memkind/memkind/728#-MthSEEP-o9HW1u3XqyP:-MuVaTXF6BmdmlnRGdPG:bb7f2mf) ([raw file](https://github.com/memkind/memkind/blob/0446e97af91af1d61c60e30f44dcf71280a751e4/tiering/ctl.c#L291)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

>=
</blockquote></details>

done
___
*[tiering/ctl.c, line 290 at r9](https://reviewable.io/reviews/memkind/memkind/728#-MuFRGT46scnqPfN-2tA:-MuVaRllBDipd-ROMPOr:bt6ze4b) ([raw file](https://github.com/memkind/memkind/blob/c2c5e3f2fa8606e370ded6001aa16f5332de1fa3/tiering/ctl.c#L290)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Probably not needed. You already return in case fsdax_path is NULL.
</blockquote></details>

it is needed
___
*[utils/memtier_counter_bench/memtier_counter_bench.cpp, line 102 at r9](https://reviewable.io/reviews/memkind/memkind/728#-MuFSZtP6x0m2yRBrv0K:-MuViaXB2h3bUNno55Kx:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/c2c5e3f2fa8606e370ded6001aa16f5332de1fa3/utils/memtier_counter_bench/memtier_counter_bench.cpp#L102)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

nit: nullptr
</blockquote></details>

Done.
___
*[utils/memtier_counter_bench/memtier_counter_bench.cpp, line 102 at r18](https://reviewable.io/reviews/memkind/memkind/728#-MuUzWXv7deDIGbRWmOc:-MuVibZ97unICyp2bZDG:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/7ebad1dde1b40a3511cdf424c3f9fabf2117327a/utils/memtier_counter_bench/memtier_counter_bench.cpp#L102)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

"failed to create memtier builder" or sth similar
</blockquote></details>

Done.
___
*[utils/memtier_counter_bench/memtier_counter_bench.cpp, line 106 at r18](https://reviewable.io/reviews/memkind/memkind/728#-MuUzo3c2z7ilz-kdP5O:-MuVi_XT64h_yaV1ZdCe:bb7f2mf) ([raw file](https://github.com/memkind/memkind/blob/7ebad1dde1b40a3511cdf424c3f9fabf2117327a/utils/memtier_counter_bench/memtier_counter_bench.cpp#L106)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

nit: nullptr
</blockquote></details>

done
___
*[utils/memtier_counter_bench/memtier_counter_bench.cpp, line 107 at r18](https://reviewable.io/reviews/memkind/memkind/728#-MuUzu5YE-rzQmPK0m0m:-MuVieFD2jIe0A4W5KN4:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/7ebad1dde1b40a3511cdf424c3f9fabf2117327a/utils/memtier_counter_bench/memtier_counter_bench.cpp#L107)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

"failed to create memtier memory" or sth similar
</blockquote></details>

Done.
___
*[utils/memtier_counter_bench/memtier_counter_bench.cpp, line 139 at r18](https://reviewable.io/reviews/memkind/memkind/728#-MuV-Mu_39Rt6hHaAG5l:-MuViZ9E9RcOuSEK1QQh:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/7ebad1dde1b40a3511cdf424c3f9fabf2117327a/utils/memtier_counter_bench/memtier_counter_bench.cpp#L139)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[utils/memtier_counter_bench/memtier_counter_bench.cpp, line 142 at r18](https://reviewable.io/reviews/memkind/memkind/728#-MuV-jg25mqPfCZSYMrR:-MuVm_me8Pvd_hdtTvhr:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/7ebad1dde1b40a3511cdf424c3f9fabf2117327a/utils/memtier_counter_bench/memtier_counter_bench.cpp#L142)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Check not needed.
</blockquote></details>

Done.
___
*[utils/memtier_counter_bench/memtier_counter_bench.cpp, line 143 at r18](https://reviewable.io/reviews/memkind/memkind/728#-MuV-prd6Ub6pFZjfpZI:-MuVnfkG4KBnAQkh0F1W:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/7ebad1dde1b40a3511cdf424c3f9fabf2117327a/utils/memtier_counter_bench/memtier_counter_bench.cpp#L143)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Check the result.
</blockquote></details>

Done.
___
*[utils/memtier_counter_bench/memtier_counter_bench.cpp, line 146 at r18](https://reviewable.io/reviews/memkind/memkind/728#-MuV-Hp592QbV0VEODNA:-MuViXl15mX0nXnwVzMt:b-a4017v) ([raw file](https://github.com/memkind/memkind/blob/7ebad1dde1b40a3511cdf424c3f9fabf2117327a/utils/memtier_counter_bench/memtier_counter_bench.cpp#L146)):*
> failed to create memtier builder
done


<!-- Sent from Reviewable.io -->

2022-01-28 13:42 UTC, bratpiorka approved these changes
> Reviewed 1 of 1 files at r23, 1 of 1 files at r24, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/728)* status: all files reviewed, 6 unresolved discussions (waiting on @jacekgrzybek and @PatKamin)



<!-- Sent from Reviewable.io -->

2022-01-28 13:47 UTC, PatKamin approved these changes
> Reviewed 2 of 2 files at r22, 1 of 1 files at r24, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/728)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jacekgrzybek)



<!-- Sent from Reviewable.io -->

2022-01-31 12:27 UTC, bratpiorka requested changes
> Reviewed 1 of 1 files at r25, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/728)* status: all files reviewed, 1 unresolved discussion (waiting on @jacekgrzybek)

___
*[tiering/ctl.c, line 302 at r25](https://reviewable.io/reviews/memkind/memkind/728#-Muk5g2cDdqGmePRmfim:-Muk5g2cDdqGmePRmfin:b6bukv0) ([raw file](https://github.com/memkind/memkind/blob/0f6e599724da9413e1bdb176f4e1496d6bfd1399/tiering/ctl.c#L302)):*
> ```C
>             if (ret != 0) {
>                 return -1;
>         }
> ```

coding style - tab this bracket 


<!-- Sent from Reviewable.io -->

2022-01-31 12:31 UTC, jacekgrzybek reviewed
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/728)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @bratpiorka)

___
*[src/memkind_memtier.c, line 426 at r16](https://reviewable.io/reviews/memkind/memkind/728#-MuQC1f2EKcoqVcnwI6B:-Muk6Yvg6mdnUG7Yg9jK:bb7f2mf) ([raw file](https://github.com/memkind/memkind/blob/9790f3d7942f60ac4323c23829ef2d20519a8938/src/memkind_memtier.c#L426)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Remove the comment.
</blockquote></details>

done
___
*[tiering/ctl.c, line 302 at r25](https://reviewable.io/reviews/memkind/memkind/728#-Muk5g2cDdqGmePRmfim:-Muk6anFCzRYwcPZHC1q:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/0f6e599724da9413e1bdb176f4e1496d6bfd1399/tiering/ctl.c#L302)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

coding style - tab this bracket 
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-01-31 12:44 UTC, PatKamin approved these changes
> Reviewed 1 of 1 files at r26, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/728)* status: all files reviewed, 1 unresolved discussion (waiting on @bratpiorka)



<!-- Sent from Reviewable.io -->

2022-01-31 14:57 UTC, bratpiorka approved these changes
> Reviewed 1 of 1 files at r27, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/728)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jacekgrzybek)



<!-- Sent from Reviewable.io -->

2022-02-01 13:40 UTC, merged