Add initial version of bigary & slab_allocator + tests
memkind/memkind pull request #731
Opened 2022-01-31 12:32 UTC by maciekpac

### Description

### Types of changes

- [ ] Bugfix (non-breaking change which fixes issue linked in Description above)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation (correction or otherwise)
- [ ] Cosmetics (whitespace, appearance)
- [ ] Other

### Checklist

- [x] Code compiles without errors
- [x] All tests pass locally with my changes (see TESTING section in CONTRIBUTING file)
- [x] Created tests which will fail without the change (if possible)
- [ ] Extended the README/documentation (if necessary)
- [x] All newly added files have proprietary license (if necessary)
- [ ] All newly added files are referenced in MANIFEST files (if necessary)

## Further comments

2022-01-31 14:57 UTC, bratpiorka approved these changes
> Reviewed 6 of 6 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/731)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @PatKamin)



<!-- Sent from Reviewable.io -->

2022-02-01 08:00 UTC, PatKamin requested changes
> Reviewed 3 of 6 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/731)* status: all files reviewed, 9 unresolved discussions (waiting on @maciekpac)

___
*[src/bigary.c, line 13 at r3](https://reviewable.io/reviews/memkind/memkind/731#-Muo0Acp9iK37hW4iEJI:-Muo0Acq7m2GYgd7rSKj:b-c467ki) ([raw file](https://github.com/memkind/memkind/blob/9d5852bc57f6dfd5b49c09ea8e8967c37f3734a5/src/bigary.c#L13)):*
> ```C
> 
> #include "memkind/internal/bigary.h"
> // default max: 16 GB
> ```

Remove or edit this comment as it's misleading. The default is 4 GB.
___
*[src/bigary.c, line 18 at r3](https://reviewable.io/reviews/memkind/memkind/731#-MuoExNWEIKaJ2RsV9Lo:-MuoExNXE_jTQYUDb6O5:bpra467) ([raw file](https://github.com/memkind/memkind/blob/9d5852bc57f6dfd5b49c09ea8e8967c37f3734a5/src/bigary.c#L18)):*
> ```C
> #define BIGARY_PAGESIZE    2097152
> 
> static void die(const char *fmt, ...)
> ```

Why not using log_fatal() + abort()?
___
*[src/bigary.c, line 79 at r3](https://reviewable.io/reviews/memkind/memkind/731#-Muo2aPB0uYFuhI2LVdY:-Muo2aPB0uYFuhI2LVdZ:bsuwfo1) ([raw file](https://github.com/memkind/memkind/blob/9d5852bc57f6dfd5b49c09ea8e8967c37f3734a5/src/bigary.c#L79)):*
> ```C
>         goto done;
>     top = (top + BIGARY_PAGESIZE - 1) & ~(BIGARY_PAGESIZE - 1); // align up
>     // printf("extending to %zd\n", top);
> ```

nit: Remove comment.
___
*[src/slab_allocator.c, line 25 at r3](https://reviewable.io/reviews/memkind/memkind/731#-Muo4Ee36Br6dtxYS8O0:-Muo4Ee36Br6dtxYS8O1:b-coeavw) ([raw file](https://github.com/memkind/memkind/blob/9d5852bc57f6dfd5b49c09ea8e8967c37f3734a5/src/slab_allocator.c#L25)):*
> ```C
> static freelist_node_meta_t *slab_alloc_addr_to_node_meta_(void *addr)
> {
>     assert(addr);
> ```

Please, add a log message.
___
*[src/slab_allocator.c, line 32 at r3](https://reviewable.io/reviews/memkind/memkind/731#-Muo4JARC7dGuXKYU6y3:-Muo4JARC7dGuXKYU6y4:b-coeavw) ([raw file](https://github.com/memkind/memkind/blob/9d5852bc57f6dfd5b49c09ea8e8967c37f3734a5/src/slab_allocator.c#L32)):*
> ```C
> static void *slab_alloc_node_meta_to_addr_(freelist_node_meta_t *meta)
> {
>     assert(meta);
> ```

Please, add a log message.
___
*[src/slab_allocator.c, line 134 at r3](https://reviewable.io/reviews/memkind/memkind/731#-MuoGYXW425YM207ObzS:-MuoGYXW425YM207ObzT:bvvhrb4) ([raw file](https://github.com/memkind/memkind/blob/9d5852bc57f6dfd5b49c09ea8e8967c37f3734a5/src/slab_allocator.c#L134)):*
> ```C
>     int ret = pthread_mutex_init(&alloc->globFreelist.mutex, NULL);
>     alloc->globFreelist.freelist = NULL;
>     if (ret != 0)
> ```

It doesn't matter. The flow goes straight to the return statement anyway.
___
*[src/slab_allocator.c, line 160 at r3](https://reviewable.io/reviews/memkind/memkind/731#-MuoHkp_2EncKNVYT5U6:-MuoHkp_2EncKNVYT5U7:b-coeavw) ([raw file](https://github.com/memkind/memkind/blob/9d5852bc57f6dfd5b49c09ea8e8967c37f3734a5/src/slab_allocator.c#L160)):*
> ```C
> MEMKIND_EXPORT void slab_alloc_free(void *addr)
> {
>     assert(addr);
> ```

Please, add a log message.
___
*[test/memkind_memtier_data_movement_test.cpp, line 71 at r3](https://reviewable.io/reviews/memkind/memkind/731#-Muo9NoC9qFJtcO6iLPS:-Muo9NoC9qFJtcO6iLPT:b-5c7hqh) ([raw file](https://github.com/memkind/memkind/blob/9d5852bc57f6dfd5b49c09ea8e8967c37f3734a5/test/memkind_memtier_data_movement_test.cpp#L71)):*
> ```cpp
> struct_bar(7);
> 
> #define test_slab_alloc(size, nof_elements)                                    \
> ```

Add a TODO to refactor this test to use gtest.
___
*[test/memkind_memtier_data_movement_test.cpp, line 220 at r3](https://reviewable.io/reviews/memkind/memkind/731#-MuoH-C8AgW0NpMy7VE1:-MuoH-C8AgW0NpMy7VE2:bluhjjw) ([raw file](https://github.com/memkind/memkind/blob/9d5852bc57f6dfd5b49c09ea8e8967c37f3734a5/test/memkind_memtier_data_movement_test.cpp#L220)):*
> ```cpp
> }
> 
> TEST(SlabAlloc, Alignment)
> ```

Add a test trying to allocate more than initialized with slab_alloc_init().


<!-- Sent from Reviewable.io -->

2022-02-01 14:07 UTC, maciekpac reviewed
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/731)* status: 1 of 6 files reviewed, 8 unresolved discussions (waiting on @bratpiorka and @PatKamin)

___
*[src/bigary.c, line 13 at r3](https://reviewable.io/reviews/memkind/memkind/731#-Muo0Acp9iK37hW4iEJI:-MupVOiW3jJMlxUoWLYW:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/9d5852bc57f6dfd5b49c09ea8e8967c37f3734a5/src/bigary.c#L13)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Remove or edit this comment as it's misleading. The default is 4 GB.
</blockquote></details>

Done.
___
*[src/bigary.c, line 18 at r3](https://reviewable.io/reviews/memkind/memkind/731#-MuoExNWEIKaJ2RsV9Lo:-MupWOQn3k17LvCTd5pd:b7pttqz) ([raw file](https://github.com/memkind/memkind/blob/9d5852bc57f6dfd5b49c09ea8e8967c37f3734a5/src/bigary.c#L18)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Why not using log_fatal() + abort()?
</blockquote></details>

Actually, a good idea. Done
___
*[src/slab_allocator.c, line 25 at r3](https://reviewable.io/reviews/memkind/memkind/731#-Muo4Ee36Br6dtxYS8O0:-MupWvPh0YhNxiq7Hlv4:bhied4h) ([raw file](https://github.com/memkind/memkind/blob/9d5852bc57f6dfd5b49c09ea8e8967c37f3734a5/src/slab_allocator.c#L25)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Please, add a log message.
</blockquote></details>

added && "comment" instead of log message; this is internal function and, by design, nullptr should never be passed here; also, asserts can be turned off and provide 0 runtime cost

With the new version, a program that fails would display show the failed line with the comment
___
*[src/slab_allocator.c, line 32 at r3](https://reviewable.io/reviews/memkind/memkind/731#-Muo4JARC7dGuXKYU6y3:-MupXMT3BDllNj2rYEis:b-9chp70) ([raw file](https://github.com/memkind/memkind/blob/9d5852bc57f6dfd5b49c09ea8e8967c37f3734a5/src/slab_allocator.c#L32)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Please, add a log message.
</blockquote></details>

as above
___
*[src/slab_allocator.c, line 134 at r3](https://reviewable.io/reviews/memkind/memkind/731#-MuoGYXW425YM207ObzS:-MupX_bZCDru74fhZQ9J:b2eh0w9) ([raw file](https://github.com/memkind/memkind/blob/9d5852bc57f6dfd5b49c09ea8e8967c37f3734a5/src/slab_allocator.c#L134)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

It doesn't matter. The flow goes straight to the return statement anyway.
</blockquote></details>

true, done
___
*[src/slab_allocator.c, line 160 at r3](https://reviewable.io/reviews/memkind/memkind/731#-MuoHkp_2EncKNVYT5U6:-MupXhsi9WvywppaZ6Wz:busos3b) ([raw file](https://github.com/memkind/memkind/blob/9d5852bc57f6dfd5b49c09ea8e8967c37f3734a5/src/slab_allocator.c#L160)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Please, add a log message.
</blockquote></details>

modified the function; right now, NULL is handled
___
*[test/memkind_memtier_data_movement_test.cpp, line 71 at r3](https://reviewable.io/reviews/memkind/memkind/731#-Muo9NoC9qFJtcO6iLPS:-MupY62t8aQrTjGs2X13:b146gxk) ([raw file](https://github.com/memkind/memkind/blob/9d5852bc57f6dfd5b49c09ea8e8967c37f3734a5/test/memkind_memtier_data_movement_test.cpp#L71)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Add a TODO to refactor this test to use gtest.
</blockquote></details>

I'm not sure if exact porting would be possible, but I've added the comment
___
*[test/memkind_memtier_data_movement_test.cpp, line 220 at r3](https://reviewable.io/reviews/memkind/memkind/731#-MuoH-C8AgW0NpMy7VE1:-MupYDOz1q2pf6zHwMEA:b27nre2) ([raw file](https://github.com/memkind/memkind/blob/9d5852bc57f6dfd5b49c09ea8e8967c37f3734a5/test/memkind_memtier_data_movement_test.cpp#L220)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Add a test trying to allocate more than initialized with slab_alloc_init().
</blockquote></details>

Currently, we should fail with SIGABORT.

If POC is successful, we will write code that handles such cases and I think it's not the perfect moment to write tests that will have to be rewritten, in the best case ...


<!-- Sent from Reviewable.io -->

2022-02-01 14:11 UTC, bratpiorka approved these changes
> Reviewed 5 of 5 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/731)* status: all files reviewed, 8 unresolved discussions (waiting on @PatKamin)

___
*[test/memkind_memtier_data_movement_test.cpp, line 71 at r3](https://reviewable.io/reviews/memkind/memkind/731#-Muo9NoC9qFJtcO6iLPS:-MupbpxKBgMEpVdZ8VzM:bbat0ds) ([raw file](https://github.com/memkind/memkind/blob/9d5852bc57f6dfd5b49c09ea8e8967c37f3734a5/test/memkind_memtier_data_movement_test.cpp#L71)):*
<details><summary><i>Previously, maciekpac wrote…</i></summary><blockquote>

I'm not sure if exact porting would be possible, but I've added the comment
</blockquote></details>

c++ has template functions :) but for POC this is ok


<!-- Sent from Reviewable.io -->

2022-02-01 14:13 UTC, PatKamin approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/731)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @maciekpac)



<!-- Sent from Reviewable.io -->

2022-02-01 14:40 UTC, maciekpac reviewed
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/731)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @maciekpac)

___
*[test/memkind_memtier_data_movement_test.cpp, line 71 at r3](https://reviewable.io/reviews/memkind/memkind/731#-Muo9NoC9qFJtcO6iLPS:-MupiZrD4AavRQYBQr9Q:b-k19hpp) ([raw file](https://github.com/memkind/memkind/blob/9d5852bc57f6dfd5b49c09ea8e8967c37f3734a5/test/memkind_memtier_data_movement_test.cpp#L71)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

c++ has template functions :) but for POC this is ok
</blockquote></details>

true..


<!-- Sent from Reviewable.io -->

2022-02-02 16:35 UTC, merged