Add iterface for tracking page allocations
memkind/memkind pull request #750
Opened 2022-02-15 11:19 UTC by maciekpac

### Description

### Types of changes

- [ ] Bugfix (non-breaking change which fixes issue linked in Description above)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation (correction or otherwise)
- [ ] Cosmetics (whitespace, appearance)
- [ ] Other

### Checklist

- [x] Code compiles without errors
- [x] All tests pass locally with my changes (see TESTING section in CONTRIBUTING file)
- [ ] Created tests which will fail without the change (if possible)
- [ ] Extended the README/documentation (if necessary)
- [ ] All newly added files have proprietary license (if necessary)
- [ ] All newly added files are referenced in MANIFEST files (if necessary)

## Further comments

2022-02-15 12:53 UTC, bratpiorka requested changes
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/750)* status: all files reviewed, 3 unresolved discussions (waiting on @maciekpac and @PatKamin)

___
*[src/bigary.c, line 91 at r1](https://reviewable.io/reviews/memkind/memkind/750#-MvxQ_BDEZjMJaei0tMv:-MvxQ_BDEZjMJaei0tMw:b-gn80nu) ([raw file](https://github.com/memkind/memkind/blob/60bddb27653dffccdc601f136b47c21f62e223ad/src/bigary.c#L91)):*
> ```C
> }
> 
> extern void bigary_alloc_pages(bigary *restrict m_bigary, size_t top,
> ```

why do you need this extra declaration?
___
*[src/pool_allocator.c, line 96 at r1](https://reviewable.io/reviews/memkind/memkind/750#-MvxR89A35pSjV7d02Gq:-MvxR89A35pSjV7d02Gr:bkkzynh) ([raw file](https://github.com/memkind/memkind/blob/60bddb27653dffccdc601f136b47c21f62e223ad/src/pool_allocator.c#L96)):*
> ```C
> // -------- public functions --------------------------------------------------
> 
> MEMKIND_EXPORT void *pool_allocator_malloc(PoolAllocator *pool, size_t size)
> ```

could you call pool_allocator_malloc_pages() here as this is a more generic case of simple malloc?
___
*[src/slab_allocator.c, line 175 at r1](https://reviewable.io/reviews/memkind/memkind/750#-MvxRVXI10I9nQn7lLkg:-MvxRVXI10I9nQn7lLkh:bqmmct5) ([raw file](https://github.com/memkind/memkind/blob/60bddb27653dffccdc601f136b47c21f62e223ad/src/slab_allocator.c#L175)):*
> ```C
> 
> MEMKIND_EXPORT void *slab_allocator_malloc(SlabAllocator *alloc)
> {
> ```

could you call slab_allocator_malloc_pages() here?


<!-- Sent from Reviewable.io -->

2022-02-15 14:35 UTC, maciekpac reviewed
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/750)* status: all files reviewed, 3 unresolved discussions (waiting on @bratpiorka and @PatKamin)

___
*[src/bigary.c, line 91 at r1](https://reviewable.io/reviews/memkind/memkind/750#-MvxQ_BDEZjMJaei0tMv:-MvxgO7JArXkoT3IvYXh:be0yh86) ([raw file](https://github.com/memkind/memkind/blob/60bddb27653dffccdc601f136b47c21f62e223ad/src/bigary.c#L91)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

why do you need this extra declaration?
</blockquote></details>

This function has 2 additional arguments.

Another issue is code duplication, but I really do not want to interact in any way with performance of the original function by adding new conditional statements...
___
*[src/pool_allocator.c, line 96 at r1](https://reviewable.io/reviews/memkind/memkind/750#-MvxR89A35pSjV7d02Gq:-MvxmPa43BIxl7QzBIak:brnvl21) ([raw file](https://github.com/memkind/memkind/blob/60bddb27653dffccdc601f136b47c21f62e223ad/src/pool_allocator.c#L96)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

could you call pool_allocator_malloc_pages() here as this is a more generic case of simple malloc?
</blockquote></details>

I could, but I did not want to get rid of the old implementation, just to be sure no new overhead goes unnoticed - this is critical path for all mallocs and it might need to be optimized up to branch hints (https://arcb.csc.ncsu.edu/~mueller/cluster/ps3/SDK3.0/docs/accessibility/sdkpt/cbet_3reducbrmis.html), as other malloc implementations are.
___
*[src/slab_allocator.c, line 175 at r1](https://reviewable.io/reviews/memkind/memkind/750#-MvxRVXI10I9nQn7lLkg:-MvxndKTEKYazICFT1_4:b-d22wbz) ([raw file](https://github.com/memkind/memkind/blob/60bddb27653dffccdc601f136b47c21f62e223ad/src/slab_allocator.c#L175)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

could you call slab_allocator_malloc_pages() here?
</blockquote></details>

Same response as above


<!-- Sent from Reviewable.io -->

2022-02-15 15:55 UTC, bratpiorka approved these changes
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/750)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @PatKamin)



<!-- Sent from Reviewable.io -->

2022-02-16 09:09 UTC, bratpiorka approved these changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/750)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @PatKamin)



<!-- Sent from Reviewable.io -->

2022-02-16 14:35 UTC, bratpiorka approved these changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/750)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @PatKamin)



<!-- Sent from Reviewable.io -->

2022-02-16 17:55 UTC, maciekpac commented
dax_kmem and hbw tests passed on https://github.com/memkind/memkind/pull/753, which is based on this commit; I am merging these commits to POC branch to avoid holdups related to too many pending PRs

2022-02-16 17:55 UTC, merged