Always initialize memory used by kind
memkind/memkind pull request #754
Opened 2022-02-16 17:24 UTC by bratpiorka

### Description

### Types of changes

- [ ] Bugfix (non-breaking change which fixes issue linked in Description above)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation (correction or otherwise)
- [ ] Cosmetics (whitespace, appearance)
- [ ] Other

### Checklist

- [ ] Code compiles without errors
- [ ] All tests pass locally with my changes (see TESTING section in CONTRIBUTING file)
- [ ] Created tests which will fail without the change (if possible)
- [ ] Extended the README/documentation (if necessary)
- [ ] All newly added files have proprietary license (if necessary)
- [ ] All newly added files are referenced in MANIFEST files (if necessary)

## Further comments

2022-02-17 09:35 UTC, maciekpac requested changes
I'm not sure about the intent of this commit and the code looks dubious

2022-02-17 09:35 UTC, maciekpac commented on src/memkind.c
> +    void *t = memkind_malloc(kind, 8);
What if it fails? E.g. DAX_KMEM returns null if no pmem is detected in the system, in such case, we would get segfault

2022-02-17 10:45 UTC, bratpiorka reviewed
I updated commit info and added a comment

> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/754#-:-Mw6HLWl6NM2EN0xSQl1:b-ekrsib)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @kilobyte, @maciekpac, and @PatKamin)

___
*[src/memkind.c, line 585 at r1](https://reviewable.io/reviews/memkind/memkind/754#-Mw2Z5bLcSKKw51pPJT2-r1-585:-Mw6HIt711RLJUq4GfeS:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/7048da5df4a7b04a8b754ae75a6d5a069c0d20c6/src/memkind.c#L585)):*
<details><summary><i>Previously, maciekpac wrote…</i></summary><blockquote>

What if it fails? E.g. DAX_KMEM returns null if no pmem is detected in the system, in such case, we would get segfault
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-02-18 09:40 UTC, maciekpac requested changes
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/754)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @bratpiorka, @kilobyte, and @PatKamin)

___
*[src/memkind.c, line 585 at r1](https://reviewable.io/reviews/memkind/memkind/754#-Mw2Z5bLcSKKw51pPJT2-r1-585:-MwBBbCo5dOBEBoYG1n4:b-y6ers3) ([raw file](https://github.com/memkind/memkind/blob/7048da5df4a7b04a8b754ae75a6d5a069c0d20c6/src/memkind.c#L585)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

The use case for this is really obscure - I would describe it in more detail - visibility in numactl, statistics, etc.


<!-- Sent from Reviewable.io -->

2022-02-22 07:42 UTC, closed without merging