Integrate background thread
memkind/memkind pull request #756
Opened 2022-02-18 17:17 UTC by maciekpac

### Description

### Types of changes

- [ ] Bugfix (non-breaking change which fixes issue linked in Description above)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation (correction or otherwise)
- [ ] Cosmetics (whitespace, appearance)
- [ ] Other

### Checklist

- [x] Code compiles without errors
- [x] All tests pass locally with my changes (see TESTING section in CONTRIBUTING file)
- [ ] Created tests which will fail without the change (if possible)
- [ ] Extended the README/documentation (if necessary)
- [ ] All newly added files have proprietary license (if necessary)
- [ ] All newly added files are referenced in MANIFEST files (if necessary)

## Further comments

2022-02-21 10:05 UTC, PatKamin requested changes
> Reviewed 13 of 13 files at r1, 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/756)* status: all files reviewed, 7 unresolved discussions (waiting on @maciekpac)

___
*[include/memkind/internal/traced_pagesize_defs.h, line 4 at r1](https://reviewable.io/reviews/memkind/memkind/756#-MwQL7SnEwmIwb1O4OL-:-MwQL7So4MaM6Q6DzZ5W:b-8qf8yd) ([raw file](https://github.com/memkind/memkind/blob/0835123389fe7a6a31957822d38e1467614db9d1/include/memkind/internal/traced_pagesize_defs.h#L4)):*
> ```objc
> /* Copyright (C) 2022 Intel Corporation. */
> 
> #define TRACED_PAGESIZE (4 * 1024u)
> ```

Can it be retrieved from the OS?
___
*[src/mtt_allocator.c, line 100 at r1](https://reviewable.io/reviews/memkind/memkind/756#-MwQRZQI0CnJHgqvw-RI:-MwQRZQI0CnJHgqvw-RJ:b14xb3t) ([raw file](https://github.com/memkind/memkind/blob/0835123389fe7a6a31957822d38e1467614db9d1/src/mtt_allocator.c#L100)):*
> ```C
> {
>     pthread_mutex_lock(&allocatorsMutex);
>     if (root) {
> ```

`root` is a static var in this file. Consider inserting new MTTAllocator at the beginning of this list to decrease the time complexity. It seems that it's the only usage of this list that wouldn't require searching for a specific element and can be optimised. However, as there will be not many mtt allocators created, I understand that it might be left as-is.
___
*[src/mtt_allocator.c, line 123 at r1](https://reviewable.io/reviews/memkind/memkind/756#-MwQSnWeEI2z7_TRvB_T:-MwQSnWeEI2z7_TRvB_U:bsfo2wu) ([raw file](https://github.com/memkind/memkind/blob/0835123389fe7a6a31957822d38e1467614db9d1/src/mtt_allocator.c#L123)):*
> ```C
>     MTTAllocatorNode *cnode = root;
>     MTTAllocatorNode *prev_node = root;
>     bool multiple_allocators_registered = (bool)root->next;
> ```

nit: single_allocator_registered would be easier to understand (there would be no need for a negation later).
___
*[src/mtt_internals.c, line 11 at r1](https://reviewable.io/reviews/memkind/memkind/756#-MwQeU-gAQ3XYke-oDzz:-MwQeU-gAQ3XYke-oE--:b-ksya7) ([raw file](https://github.com/memkind/memkind/blob/0835123389fe7a6a31957822d38e1467614db9d1/src/mtt_internals.c#L11)):*
> ```C
> MEMKIND_EXPORT int mtt_internals_create(MttInternals *internals,
>                                         uint64_t timestamp,
>                                         MTTInternalsLimits *limits)
> ```

Perhaps these limits could be passed as NULL and then some defaults used? Might be added as a TODO.
___
*[src/mtt_internals.c, line 16 at r1](https://reviewable.io/reviews/memkind/memkind/756#-MwQUL4i1gauhBEss1Dz:-MwQUL4i1gauhBEss1E-:b-5m1j3r) ([raw file](https://github.com/memkind/memkind/blob/0835123389fe7a6a31957822d38e1467614db9d1/src/mtt_internals.c#L16)):*
> ```C
>     assert(limits->lowLimit <= limits->softLimit &&
>            "low limit (movement PMEM -> DRAM occurs below) "
>            " has to be lower than "
> ```

lower than or equal to
___
*[src/mtt_internals.c, line 20 at r1](https://reviewable.io/reviews/memkind/memkind/756#-MwQUOBa-8gjpIAUJR-D:-MwQUOBa-8gjpIAUJR-E:b-5m1j3r) ([raw file](https://github.com/memkind/memkind/blob/0835123389fe7a6a31957822d38e1467614db9d1/src/mtt_internals.c#L20)):*
> ```C
>     assert(limits->softLimit <= limits->hardLimit &&
>            "soft limit (movement DRAM -> PMEM occurs above) "
>            " has to be lower than "
> ```

lower than or equal to
___
*[test/memkind_memtier_data_movement_test.cpp, line 388 at r1](https://reviewable.io/reviews/memkind/memkind/756#-MwQegdsBc1YAGEwP5dt:-MwQegdsBc1YAGEwP5du:b-l0hck2) ([raw file](https://github.com/memkind/memkind/blob/0835123389fe7a6a31957822d38e1467614db9d1/test/memkind_memtier_data_movement_test.cpp#L388)):*
> ```cpp
> }
> 
> #if 0
> ```

Please, try fixing this test as it's not a good idea to disable the only PEBS test.


<!-- Sent from Reviewable.io -->

2022-02-21 12:28 UTC, bratpiorka requested changes
> Reviewed 13 of 13 files at r1, 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/756)* status: all files reviewed, 8 unresolved discussions (waiting on @maciekpac and @PatKamin)

___
*[src/mtt_internals.c, line 15 at r1](https://reviewable.io/reviews/memkind/memkind/756#-MwREcoj5e006yFYvJlH:-MwREcoj5e006yFYvJlI:b-ywalhc) ([raw file](https://github.com/memkind/memkind/blob/0835123389fe7a6a31957822d38e1467614db9d1/src/mtt_internals.c#L15)):*
> ```C
>     internals->lastTimestamp = timestamp;
>     assert(limits->lowLimit <= limits->softLimit &&
>            "low limit (movement PMEM -> DRAM occurs below) "
> ```

could you move this comments to limits definition? they are really helpful
___
*[test/memkind_memtier_data_movement_test.cpp, line 388 at r1](https://reviewable.io/reviews/memkind/memkind/756#-MwQegdsBc1YAGEwP5dt:-MwREOsP3IkSAxJmtbbO:b32v57) ([raw file](https://github.com/memkind/memkind/blob/0835123389fe7a6a31957822d38e1467614db9d1/test/memkind_memtier_data_movement_test.cpp#L388)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Please, try fixing this test as it's not a good idea to disable the only PEBS test.
</blockquote></details>

+1


<!-- Sent from Reviewable.io -->

2022-02-21 17:04 UTC, maciekpac reviewed
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/756)* status: 3 of 16 files reviewed, 7 unresolved discussions (waiting on @bratpiorka and @PatKamin)

___
*[src/mtt_allocator.c, line 100 at r1](https://reviewable.io/reviews/memkind/memkind/756#-MwQRZQI0CnJHgqvw-RI:-MwRlluA7uIa-0-br4mX:b-timqfv) ([raw file](https://github.com/memkind/memkind/blob/0835123389fe7a6a31957822d38e1467614db9d1/src/mtt_allocator.c#L100)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

`root` is a static var in this file. Consider inserting new MTTAllocator at the beginning of this list to decrease the time complexity. It seems that it's the only usage of this list that wouldn't require searching for a specific element and can be optimised. However, as there will be not many mtt allocators created, I understand that it might be left as-is.
</blockquote></details>

You're right, it's better to insert on the front. Not only is this code more efficient, but also more readable. The performance of this function is not relevant for our benchmarks, but I've applied your comment
___
*[src/mtt_allocator.c, line 123 at r1](https://reviewable.io/reviews/memkind/memkind/756#-MwQSnWeEI2z7_TRvB_T:-MwRmM_9DJtE472GMHPq:bb6un1j) ([raw file](https://github.com/memkind/memkind/blob/0835123389fe7a6a31957822d38e1467614db9d1/src/mtt_allocator.c#L123)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

nit: single_allocator_registered would be easier to understand (there would be no need for a negation later).
</blockquote></details>

Done
___
*[src/mtt_internals.c, line 11 at r1](https://reviewable.io/reviews/memkind/memkind/756#-MwQeU-gAQ3XYke-oDzz:-MwRm_IU3WGDa_bBq0R0:b-7fwzoz) ([raw file](https://github.com/memkind/memkind/blob/0835123389fe7a6a31957822d38e1467614db9d1/src/mtt_internals.c#L11)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Perhaps these limits could be passed as NULL and then some defaults used? Might be added as a TODO.
</blockquote></details>

Handling default values would be more straightforward in the case of kernel memory tiering... We don't know how many programs will use PMEM and how much of it they will need.
___
*[src/mtt_internals.c, line 15 at r1](https://reviewable.io/reviews/memkind/memkind/756#-MwREcoj5e006yFYvJlH:-MwRnd5LCQKJPb9yNgzh:b-uo7u2e) ([raw file](https://github.com/memkind/memkind/blob/0835123389fe7a6a31957822d38e1467614db9d1/src/mtt_internals.c#L15)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

could you move this comments to limits definition? they are really helpful
</blockquote></details>

Actually, these comments are already them; I updated the comments and added more info to make them look nicer
___
*[src/mtt_internals.c, line 16 at r1](https://reviewable.io/reviews/memkind/memkind/756#-MwQUL4i1gauhBEss1Dz:-MwRoXPh2_e9gC9_Hurs:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/0835123389fe7a6a31957822d38e1467614db9d1/src/mtt_internals.c#L16)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

lower than or equal to
</blockquote></details>

Done.
___
*[src/mtt_internals.c, line 20 at r1](https://reviewable.io/reviews/memkind/memkind/756#-MwQUOBa-8gjpIAUJR-D:-MwRo_kH4M3cstBCL0A_:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/0835123389fe7a6a31957822d38e1467614db9d1/src/mtt_internals.c#L20)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

lower than or equal to
</blockquote></details>

Done.
___
*[test/memkind_memtier_data_movement_test.cpp, line 388 at r1](https://reviewable.io/reviews/memkind/memkind/756#-MwQegdsBc1YAGEwP5dt:-MwSDDFxCSaz2NTmMKZy:b9fa18e) ([raw file](https://github.com/memkind/memkind/blob/0835123389fe7a6a31957822d38e1467614db9d1/test/memkind_memtier_data_movement_test.cpp#L388)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

+1
</blockquote></details>

Done.

The test looks a little bit differently right now
___
*[include/memkind/internal/traced_pagesize_defs.h, line 4 at r1](https://reviewable.io/reviews/memkind/memkind/756#-MwQL7SnEwmIwb1O4OL-:-MwR6s8C1wIXmuydtrGu:b6wcsuz) ([raw file](https://github.com/memkind/memkind/blob/0835123389fe7a6a31957822d38e1467614db9d1/include/memkind/internal/traced_pagesize_defs.h#L4)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Can it be retrieved from the OS?
</blockquote></details>

Pagesize can be retrieved from the OS, but I would like it to be more customizable.

I have renamed the whole file to pagesizes.h and modified it, you can check the new version


<!-- Sent from Reviewable.io -->

2022-02-22 06:41 UTC, PatKamin reviewed
> Reviewed 13 of 13 files at r3, 6 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/756)* status: all files reviewed, 5 unresolved discussions (waiting on @bratpiorka, @maciekpac, and @PatKamin)

___
*[test/memkind_memtier_data_movement_test.cpp, line 423 at r3](https://reviewable.io/reviews/memkind/memkind/756#-MwV8sgc5UPKIficMDH-:-MwV8sgd3ipYuy2tmJXD:beta009) ([raw file](https://github.com/memkind/memkind/blob/d3be09737cdf8bcb377a8636dbba0d07b799cb72/test/memkind_memtier_data_movement_test.cpp#L423)):*
> ```cpp
>     }
> 
>     ASSERT_TRUE(success);
> ```

nit: Move these asserts right below the get_highest_hotness call.


<!-- Sent from Reviewable.io -->

2022-02-22 07:41 UTC, bratpiorka requested changes
> Reviewed 13 of 13 files at r3, 6 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/756)* status: all files reviewed, 7 unresolved discussions (waiting on @maciekpac and @PatKamin)

___
*[include/memkind/internal/pebs.h, line 49 at r4](https://reviewable.io/reviews/memkind/memkind/756#-MwVMztF5J0DY8G8NISj:-MwVMztF5J0DY8G8NISk:b-580i82) ([raw file](https://github.com/memkind/memkind/blob/c664d3e4c86107dab2746ed9a7e0529e68304332/include/memkind/internal/pebs.h#L49)):*
> ```objc
> } PebsMetadata;
> 
> void pebs_create(PebsMetadata *pebs, touch_cb cb);
> ```

I think we should make a class here but for POC this is ok
___
*[src/pebs.c, line 16 at r4](https://reviewable.io/reviews/memkind/memkind/756#-MwVMntnAnzVTVgoXVmx:-MwVMntnAnzVTVgoXVmy:b4vjnl4) ([raw file](https://github.com/memkind/memkind/blob/c664d3e4c86107dab2746ed9a7e0529e68304332/src/pebs.c#L16)):*
> ```C
> #define HOTNESS_PEBS_THREAD_FREQUENCY 10.0
> 
> MEMKIND_EXPORT int pebs_debug_num_samples = 0;
> ```

this could be also removed
___
*[test/memkind_memtier_data_movement_test.cpp, line 422 at r1](https://reviewable.io/reviews/memkind/memkind/756#-MwVMJnP4_ho6hdN55_c:-MwVMJnP4_ho6hdN55_d:bxgsj87) ([raw file](https://github.com/memkind/memkind/blob/0835123389fe7a6a31957822d38e1467614db9d1/test/memkind_memtier_data_movement_test.cpp#L422)):*
> ```cpp
> 
>     // check debug value defined in pebs.c
>     ASSERT_GT(pebs_debug_num_samples, 0);
> ```

if there is no need to use "pebs_debug_num_samples" - could you remove them in separate commit?


<!-- Sent from Reviewable.io -->

2022-02-22 13:58 UTC, maciekpac reviewed
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/756)* status: 10 of 16 files reviewed, 6 unresolved discussions (waiting on @bratpiorka and @PatKamin)

___
*[include/memkind/internal/pebs.h, line 49 at r4](https://reviewable.io/reviews/memkind/memkind/756#-MwVMztF5J0DY8G8NISj:-MwWTgU509Bc3A3qb6mk:b1x0n2q) ([raw file](https://github.com/memkind/memkind/blob/c664d3e4c86107dab2746ed9a7e0529e68304332/include/memkind/internal/pebs.h#L49)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

I think we should make a class here but for POC this is ok
</blockquote></details>

this is written in C, not in C++ ...

But yes, this part might need refactoring in the future
___
*[src/pebs.c, line 16 at r4](https://reviewable.io/reviews/memkind/memkind/756#-MwVMntnAnzVTVgoXVmx:-MwWU8jb-CFskNhOacd2:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/c664d3e4c86107dab2746ed9a7e0529e68304332/src/pebs.c#L16)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

this could be also removed
</blockquote></details>

Done.
___
*[test/memkind_memtier_data_movement_test.cpp, line 422 at r1](https://reviewable.io/reviews/memkind/memkind/756#-MwVMJnP4_ho6hdN55_c:-MwWUcZx31RA0lAGnbo_:bz6ufss) ([raw file](https://github.com/memkind/memkind/blob/0835123389fe7a6a31957822d38e1467614db9d1/test/memkind_memtier_data_movement_test.cpp#L422)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

if there is no need to use "pebs_debug_num_samples" - could you remove them in separate commit?
</blockquote></details>

Done, but rebased on an old commit
___
*[test/memkind_memtier_data_movement_test.cpp, line 423 at r3](https://reviewable.io/reviews/memkind/memkind/756#-MwV8sgc5UPKIficMDH-:-MwWUWOyB5S0HFUyDPRD:bb6un1j) ([raw file](https://github.com/memkind/memkind/blob/d3be09737cdf8bcb377a8636dbba0d07b799cb72/test/memkind_memtier_data_movement_test.cpp#L423)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

nit: Move these asserts right below the get_highest_hotness call.
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2022-02-22 14:15 UTC, PatKamin reviewed
> Reviewed 6 of 6 files at r5.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/756)* status: 11 of 16 files reviewed, 5 unresolved discussions (waiting on @bratpiorka and @PatKamin)



<!-- Sent from Reviewable.io -->

2022-02-22 14:17 UTC, PatKamin approved these changes
> Reviewed 5 of 5 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/756)* status: all files reviewed, 3 unresolved discussions (waiting on @bratpiorka)



<!-- Sent from Reviewable.io -->

2022-02-22 14:37 UTC, bratpiorka approved these changes
> Reviewed 6 of 6 files at r5, 5 of 5 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/756)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @maciekpac)



<!-- Sent from Reviewable.io -->

2022-02-22 15:04 UTC, merged