Add python script to gather extensive zipf data
memkind/memkind pull request #778
Opened 2022-03-22 10:13 UTC by maciekpac

### Description

### Types of changes

- [ ] Bugfix (non-breaking change which fixes issue linked in Description above)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation (correction or otherwise)
- [ ] Cosmetics (whitespace, appearance)
- [ ] Other

### Checklist

- [x] Code compiles without errors
- [x] All tests pass locally with my changes (see TESTING section in CONTRIBUTING file)
- [ ] Created tests which will fail without the change (if possible)
- [ ] Extended the README/documentation (if necessary)
- [x] All newly added files have proprietary license (if necessary)
- [ ] All newly added files are referenced in MANIFEST files (if necessary)

## Further comments

2022-03-22 12:24 UTC, PatKamin requested changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/778)* status: all files reviewed, 7 unresolved discussions (waiting on @bratpiorka and @maciekpac)

___
*[utils/memtier_zipf_bench/swipe_testcase.py, line 57 at r2](https://reviewable.io/reviews/memkind/memkind/778#-MylT7ogBtZt_YaR7-zo:-MylT7ogBtZt_YaR7-zp:b-gwux3j) ([raw file](https://github.com/memkind/memkind/blob/f249b85f56cb32117460101bbcfb9e5853a5fd06/utils/memtier_zipf_bench/swipe_testcase.py#L57)):*
> ```Python
> 
> 
> def check_mem_usage_by_node(pid, dram_nodes, pmem_nodes):
> ```

Please, use type hints: https://docs.python.org/3/library/typing.html
___
*[utils/memtier_zipf_bench/swipe_testcase.py, line 63 at r2](https://reviewable.io/reviews/memkind/memkind/778#-MylOqWzD9M2mKvYUqei:-MylOqWzD9M2mKvYUqej:b5vcfpl) ([raw file](https://github.com/memkind/memkind/blob/f249b85f56cb32117460101bbcfb9e5853a5fd06/utils/memtier_zipf_bench/swipe_testcase.py#L63)):*
> ```Python
>     out = result.stdout.decode()
>     usage_data = re.findall("MemUsed(.*?)\n", out)[
>         0
> ```

Move the comment to other line. Selecting the first element of the table in three lines is a bit too much. Readability suffers. 
___
*[utils/memtier_zipf_bench/swipe_testcase.py, line 86 at r2](https://reviewable.io/reviews/memkind/memkind/778#-MylTOY67ARC6JqmOF0f:-MylTOY67ARC6JqmOF0g:b-as7icr) ([raw file](https://github.com/memkind/memkind/blob/f249b85f56cb32117460101bbcfb9e5853a5fd06/utils/memtier_zipf_bench/swipe_testcase.py#L86)):*
> ```Python
> def check_mem_usage(pid):
>     DRAM_NODES = [0, 1]
>     PMEM_NODES = [2, 3]
> ```

nit: Good enough for POC, should be parameterized or read from the system for production quality.
___
*[utils/memtier_zipf_bench/swipe_testcase.py, line 101 at r2](https://reviewable.io/reviews/memkind/memkind/778#-MylTdqQDGkIvYne_a-P:-MylTdqR9bSjeB2LPbjg:b-gth9li) ([raw file](https://github.com/memkind/memkind/blob/f249b85f56cb32117460101bbcfb9e5853a5fd06/utils/memtier_zipf_bench/swipe_testcase.py#L101)):*
> ```Python
>     proportions = [int(val) for val in ratio.split(":")]
>     if len(proportions) != 2:
>         raise ValueError("invalid ratio format")
> ```

Add info what is the correct format and what format have been read.
___
*[utils/memtier_zipf_bench/swipe_testcase.py, line 114 at r2](https://reviewable.io/reviews/memkind/memkind/778#-MylUTW93LFdL6tBgrQh:-MylUTW93LFdL6tBgrQi:b7j93xe) ([raw file](https://github.com/memkind/memkind/blob/f249b85f56cb32117460101bbcfb9e5853a5fd06/utils/memtier_zipf_bench/swipe_testcase.py#L114)):*
> ```Python
>         f"{dram_soft_limit}",
>         "--low-limit",
>         "512000",
> ```

nit: Please, place in one line argument and it's value.
___
*[utils/memtier_zipf_bench/swipe_testcase.py, line 118 at r2](https://reviewable.io/reviews/memkind/memkind/778#-MylUoytCmkwRAoE5RUN:-MylUoytCmkwRAoE5RUO:b6wtfw) ([raw file](https://github.com/memkind/memkind/blob/f249b85f56cb32117460101bbcfb9e5853a5fd06/utils/memtier_zipf_bench/swipe_testcase.py#L118)):*
> ```Python
>         "-a",
>         f"{nof_accesses}",
>         "-i",
> ```

For the sake of readability use long argument names where possible.
___
*[utils/memtier_zipf_bench/swipe_testcase.py, line 137 at r2](https://reviewable.io/reviews/memkind/memkind/778#-MylXfW27cfv-gqzK1jh:-MylXfW27cfv-gqzK1ji:b-5n3lyf) ([raw file](https://github.com/memkind/memkind/blob/f249b85f56cb32117460101bbcfb9e5853a5fd06/utils/memtier_zipf_bench/swipe_testcase.py#L137)):*
> ```Python
>     output = output.decode()
>     if errs is not None:
>         raise ValueError("Incorrect process execution!")
> ```

Print stderr (errs)


<!-- Sent from Reviewable.io -->

2022-03-22 13:06 UTC, maciekpac reviewed
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/778)* status: 0 of 1 files reviewed, 7 unresolved discussions (waiting on @bratpiorka and @PatKamin)

___
*[utils/memtier_zipf_bench/swipe_testcase.py, line 57 at r2](https://reviewable.io/reviews/memkind/memkind/778#-MylT7ogBtZt_YaR7-zo:-Mylg7riA0aXVwNPNO_E:ba1j86p) ([raw file](https://github.com/memkind/memkind/blob/f249b85f56cb32117460101bbcfb9e5853a5fd06/utils/memtier_zipf_bench/swipe_testcase.py#L57)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Please, use type hints: https://docs.python.org/3/library/typing.html
</blockquote></details>

I already had type annotations in some places, I added them to all functions and named tuples
___
*[utils/memtier_zipf_bench/swipe_testcase.py, line 63 at r2](https://reviewable.io/reviews/memkind/memkind/778#-MylOqWzD9M2mKvYUqei:-MylgbnCDSI8r4XPTncu:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/f249b85f56cb32117460101bbcfb9e5853a5fd06/utils/memtier_zipf_bench/swipe_testcase.py#L63)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Move the comment to other line. Selecting the first element of the table in three lines is a bit too much. Readability suffers. 
</blockquote></details>

Done.
___
*[utils/memtier_zipf_bench/swipe_testcase.py, line 86 at r2](https://reviewable.io/reviews/memkind/memkind/778#-MylTOY67ARC6JqmOF0f:-Mylge7H-RlUYORimkwQ:bqrtief) ([raw file](https://github.com/memkind/memkind/blob/f249b85f56cb32117460101bbcfb9e5853a5fd06/utils/memtier_zipf_bench/swipe_testcase.py#L86)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

nit: Good enough for POC, should be parameterized or read from the system for production quality.
</blockquote></details>

Completely understood; I had the same thoughts, but finding our which numa node is dram and which pmem is probably an overkill for now.

I added a comment
___
*[utils/memtier_zipf_bench/swipe_testcase.py, line 101 at r2](https://reviewable.io/reviews/memkind/memkind/778#-MylTdqQDGkIvYne_a-P:-MylhMXlEXppoUpf6_Mp:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/f249b85f56cb32117460101bbcfb9e5853a5fd06/utils/memtier_zipf_bench/swipe_testcase.py#L101)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Add info what is the correct format and what format have been read.
</blockquote></details>

Done.
___
*[utils/memtier_zipf_bench/swipe_testcase.py, line 114 at r2](https://reviewable.io/reviews/memkind/memkind/778#-MylUTW93LFdL6tBgrQh:-MylhphC61HTKliEzSYq:b-eiwgz4) ([raw file](https://github.com/memkind/memkind/blob/f249b85f56cb32117460101bbcfb9e5853a5fd06/utils/memtier_zipf_bench/swipe_testcase.py#L114)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

nit: Please, place in one line argument and it's value.
</blockquote></details>

These lines were automatically formatted by  [black](https://pypi.org/project/black/).
___
*[utils/memtier_zipf_bench/swipe_testcase.py, line 118 at r2](https://reviewable.io/reviews/memkind/memkind/778#-MylUoytCmkwRAoE5RUN:-MylihjxBmUX0vw4Cn3H:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/f249b85f56cb32117460101bbcfb9e5853a5fd06/utils/memtier_zipf_bench/swipe_testcase.py#L118)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

For the sake of readability use long argument names where possible.
</blockquote></details>

Done.
___
*[utils/memtier_zipf_bench/swipe_testcase.py, line 137 at r2](https://reviewable.io/reviews/memkind/memkind/778#-MylXfW27cfv-gqzK1jh:-MyljB3r20Q9LIIemo1t:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/f249b85f56cb32117460101bbcfb9e5853a5fd06/utils/memtier_zipf_bench/swipe_testcase.py#L137)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Print stderr (errs)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-03-22 14:17 UTC, PatKamin requested changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/778)* status: all files reviewed, 1 unresolved discussion (waiting on @bratpiorka and @maciekpac)

___
*[utils/memtier_zipf_bench/swipe_testcase.py, line 73 at r3](https://reviewable.io/reviews/memkind/memkind/778#-MylwkG00PaeXxxiuGj6:-MylwkG00PaeXxxiuGj7:b-iso2nc) ([raw file](https://github.com/memkind/memkind/blob/3a7bf7c114db3eb96b1fbbe3c5ab758c965d6157/utils/memtier_zipf_bench/swipe_testcase.py#L73)):*
> ```Python
> def check_mem_usage_by_node(
>     pid: int, dram_nodes: list[int], pmem_nodes: list[int]
> ):
> ```

Add a type annotation for the return value as well (in all functions returning sth).


<!-- Sent from Reviewable.io -->

2022-03-23 12:00 UTC, bratpiorka approved these changes
> Reviewed 1 of 1 files at r2, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/778)* status: all files reviewed, 1 unresolved discussion (waiting on @maciekpac)



<!-- Sent from Reviewable.io -->

2022-03-25 08:03 UTC, maciekpac reviewed
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/778)* status: all files reviewed, 1 unresolved discussion (waiting on @PatKamin)

___
*[utils/memtier_zipf_bench/swipe_testcase.py, line 73 at r3](https://reviewable.io/reviews/memkind/memkind/778#-MylwkG00PaeXxxiuGj6:-MymOmacBVOsl2i7ThfE:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/3a7bf7c114db3eb96b1fbbe3c5ab758c965d6157/utils/memtier_zipf_bench/swipe_testcase.py#L73)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Add a type annotation for the return value as well (in all functions returning sth).
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-03-25 08:07 UTC, PatKamin approved these changes
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/778)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @maciekpac)



<!-- Sent from Reviewable.io -->

2022-03-25 12:29 UTC, bratpiorka approved these changes
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/778)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @maciekpac)



<!-- Sent from Reviewable.io -->

2022-03-25 12:46 UTC, PatKamin approved these changes
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/778)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @maciekpac)



<!-- Sent from Reviewable.io -->

2022-03-25 18:44 UTC, merged