handle fork()
memkind/memkind pull request #784
Opened 2022-03-28 10:19 UTC by kilobyte

(depends on #780)

2022-03-29 08:50 UTC, bratpiorka requested changes
> Reviewed 6 of 6 files at r1, 2 of 2 files at r2, 1 of 1 files at r3, 6 of 6 files at r4, 5 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/784)* status: all files reviewed, 2 unresolved discussions (waiting on @kilobyte, @maciekpac, and @PatKamin)

___
*[src/mtt_allocator.c, line 37 at r5](https://reviewable.io/reviews/memkind/memkind/784#-MzJr4097CCFNszPDj2Y:-MzJr4097CCFNszPDj2Z:behxngw) ([raw file](https://github.com/memkind/memkind/blob/784cedb4c5c1803fe5dce685bc2a73ac89392fff/src/mtt_allocator.c#L37)):*
> ```C
> static void register_mtt_allocator(MTTAllocator *mtt_allocator);
> static void unregister_mtt_allocator(MTTAllocator *mtt_allocator);
> static void background_thread_start(BackgroundThread *bg_thread);
> ```

if we declare all static functions here, please add others also (thread_stop, prefork, postfork)
___
*[src/pebs.c, line 201 at r5](https://reviewable.io/reviews/memkind/memkind/784#-MzJrVXo0wTUR6iMN2UU:-MzJrVXo0wTUR6iMN2UV:b2dtg9w) ([raw file](https://github.com/memkind/memkind/blob/784cedb4c5c1803fe5dce685bc2a73ac89392fff/src/pebs.c#L201)):*
> ```C
>     mtt_allocator_free(mtt_allocator, pebs->pebs_fd);
>     mtt_allocator_free(mtt_allocator, pebs->pebs_mmap);
>     mtt_allocator_free(mtt_allocator, pebs->last_head);
> ```

because we log "... created", please add here log_info("PEBS destroyed");


<!-- Sent from Reviewable.io -->

2022-03-29 09:10 UTC, maciekpac commented on src/mtt_allocator.c
> +static void mtt_atfork_init(void)
nit: mtt_atfork_register_handlers ? Current name sounds a little bit like some initialization function that is performed during ```fork```, not a registration of *atfork* handlers, but maybe it's just my opinion...

2022-03-29 09:10 UTC, maciekpac reviewed
> Reviewed 1 of 2 files at r2, 5 of 6 files at r4.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/784)* status: all files reviewed, 3 unresolved discussions (waiting on @bratpiorka, @kilobyte, and @PatKamin)

___
*[src/mtt_allocator.c, line 37 at r5](https://reviewable.io/reviews/memkind/memkind/784#-MzJr4097CCFNszPDj2Y:-MzJtXZI7AJ3aq4p6zbf:b32w74) ([raw file](https://github.com/memkind/memkind/blob/784cedb4c5c1803fe5dce685bc2a73ac89392fff/src/mtt_allocator.c#L37)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

if we declare all static functions here, please add others also (thread_stop, prefork, postfork)
</blockquote></details>

Up


<!-- Sent from Reviewable.io -->

2022-03-29 10:17 UTC, PatKamin approved these changes
> Reviewed 1 of 2 files at r2, 6 of 6 files at r4, 5 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/784)* status: all files reviewed, 3 unresolved discussions (waiting on @bratpiorka and @kilobyte)



<!-- Sent from Reviewable.io -->

2022-03-31 10:12 UTC, bratpiorka approved these changes
> Reviewed 2 of 2 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/784)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @kilobyte)

___
*[src/mtt_allocator.c, line 37 at r5](https://reviewable.io/reviews/memkind/memkind/784#-MzJr4097CCFNszPDj2Y:-MzUSJfR3yfKnh4ujVyn:blm39kk) ([raw file](https://github.com/memkind/memkind/blob/784cedb4c5c1803fe5dce685bc2a73ac89392fff/src/mtt_allocator.c#L37)):*
<details><summary><i>Previously, kilobyte (Adam Borowski) wrote…</i></summary><blockquote>

Do we?  I think that should be done only when it's a forward declaration; in this case it allows writing the functions in natural order.
</blockquote></details>

ok but can we stick to one code style?


<!-- Sent from Reviewable.io -->

2022-03-31 12:47 UTC, PatKamin approved these changes
> Reviewed 2 of 2 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/784)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @kilobyte)



<!-- Sent from Reviewable.io -->

2022-04-04 11:16 UTC, bratpiorka approved these changes
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/784)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @kilobyte)



<!-- Sent from Reviewable.io -->

2022-04-11 10:53 UTC, PatKamin approved these changes
> Reviewed 1 of 2 files at r9, 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/784)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @kilobyte)



<!-- Sent from Reviewable.io -->

2022-04-11 12:01 UTC, merged