Add mtt calloc() implementation
memkind/memkind pull request #803
Opened 2022-04-15 08:57 UTC by PatKamin

### Description

### Types of changes

- [ ] Bugfix (non-breaking change which fixes issue linked in Description above)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation (correction or otherwise)
- [ ] Cosmetics (whitespace, appearance)
- [ ] Other

### Checklist

- [ ] Code compiles without errors
- [ ] All tests pass locally with my changes (see TESTING section in CONTRIBUTING file)
- [ ] Created tests which will fail without the change (if possible)
- [ ] Extended the README/documentation (if necessary)
- [ ] All newly added files have proprietary license (if necessary)
- [ ] All newly added files are referenced in MANIFEST files (if necessary)

## Further comments

2022-04-19 10:30 UTC, bratpiorka approved these changes
> Reviewed 3 of 3 files at r1, 1 of 1 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/803)* status: all files reviewed, 1 unresolved discussion (waiting on @maciekpac and @PatKamin)

___
*[-- commits, line 5 at r3](https://reviewable.io/reviews/memkind/memkind/803#-N00MgYr0pFOX1Y8awrB):*
nit: ok but could you change this commit info to "mtt calloc parellel test" or similar?


<!-- Sent from Reviewable.io -->

2022-04-19 13:18 UTC, maciekpac requested changes
> Reviewed 1 of 1 files at r2, 4 of 4 files at r5, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/803)* status: all files reviewed, 1 unresolved discussion (waiting on @PatKamin)

___
*[test/memkind_memtier_data_movement_test.cpp, line 1834 at r6](https://reviewable.io/reviews/memkind/memkind/803#-N00y6GdD93gpODYZEm-:-N00y6GdD93gpODYZEm0:b-bgeuez) ([raw file](https://github.com/memkind/memkind/blob/1bfbeec1a6ca76a847813b6d8f281558e24df2f6/test/memkind_memtier_data_movement_test.cpp#L1834)):*
> ```cpp
>     MTTAllocator mtt_allocator;
> 
>     mtt_allocator_create(&mtt_allocator, &limits);
> ```

is mtt_allocator_destroy called?


<!-- Sent from Reviewable.io -->

2022-04-20 06:36 UTC, PatKamin reviewed
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/803)* status: 2 of 5 files reviewed, 1 unresolved discussion (waiting on @maciekpac)

___
*[test/memkind_memtier_data_movement_test.cpp, line 1834 at r6](https://reviewable.io/reviews/memkind/memkind/803#-N00y6GdD93gpODYZEm-:-N04foHhDPp83LM52rUr:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/1bfbeec1a6ca76a847813b6d8f281558e24df2f6/test/memkind_memtier_data_movement_test.cpp#L1834)):*
<details><summary><i>Previously, maciekpac wrote…</i></summary><blockquote>

is mtt_allocator_destroy called?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-04-20 09:52 UTC, bratpiorka approved these changes
> Reviewed 1 of 4 files at r5, 3 of 3 files at r7, 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/803)* status: all files reviewed, 1 unresolved discussion (waiting on @maciekpac)



<!-- Sent from Reviewable.io -->

2022-04-20 13:01 UTC, maciekpac commented on src/mtt_allocator.c
> +        abort();
I'm not sure if we should abort here - if mtt_allocator_malloc did not abort, why should we ? We can just propagate the null value, I wouldn't even add additional logs here.

2022-04-20 13:04 UTC, PatKamin reviewed
> Reviewed 1 of 3 files at r9.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/803)* status: 3 of 5 files reviewed, 2 unresolved discussions (waiting on @bratpiorka and @maciekpac)

___
*[src/mtt_allocator.c, line 394 at r8](https://reviewable.io/reviews/memkind/memkind/803#-N-gREKtYWbfdOjoJGD3-r8-394:-N063mCdEONdHGy70zXL:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/229f2aa081563a8868dd548e3339a39fc5774d38/src/mtt_allocator.c#L394)):*
<details><summary><i>Previously, maciekpac wrote…</i></summary><blockquote>

I'm not sure if we should abort here - if mtt_allocator_malloc did not abort, why should we ? We can just propagate the null value, I wouldn't even add additional logs here. 
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-04-20 13:20 UTC, maciekpac approved these changes
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/803)* status: 3 of 5 files reviewed, 1 unresolved discussion (waiting on @bratpiorka and @maciekpac)



<!-- Sent from Reviewable.io -->

2022-04-20 13:40 UTC, bratpiorka approved these changes
> Reviewed 3 of 3 files at r9, 2 of 2 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/803)* status: all files reviewed, 1 unresolved discussion (waiting on @maciekpac)



<!-- Sent from Reviewable.io -->

2022-04-21 01:51 UTC, maciekpac approved these changes
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/803)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @PatKamin)



<!-- Sent from Reviewable.io -->

2022-04-21 08:26 UTC, merged