add md2man script and change Makefile
memkind/memkind pull request #839
Opened 2022-07-19 19:05 UTC by szadam

### Description

### Types of changes

- [ ] Bugfix (non-breaking change which fixes issue linked in Description above)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation (correction or otherwise)
- [ ] Cosmetics (whitespace, appearance)
- [ ] Other

### Checklist

- [ ] Code compiles without errors
- [ ] All tests pass locally with my changes (see TESTING section in CONTRIBUTING file)
- [ ] Created tests which will fail without the change (if possible)
- [ ] Extended the README/documentation (if necessary)
- [ ] All newly added files have proprietary license (if necessary)
- [ ] All newly added files are referenced in MANIFEST files (if necessary)

## Further comments

2022-07-19 19:06 UTC, szadam commented
I have attached an example of the generated man file

2022-07-22 09:53 UTC, maciekpac requested changes

2022-07-22 09:53 UTC, maciekpac commented on .github/workflows/gha.yml
> +      run: sudo apt install autoconf ccache libnuma-dev pandoc
I think this is not the job that is failing.

The one that's failing has `name: Docker build [xxx]`

2022-07-29 08:56 UTC, lukaszstolarczuk reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/839)* status: 0 of 9 files reviewed, 4 unresolved discussions (waiting on @bratpiorka, @PatKamin, and @szadam)

___
*[`-- commits` line 5 at r4](https://reviewable.io/reviews/memkind/memkind/839#-N889ht806NenCNntqPi):*
I think these 2 changes do not make sense without each other; alternatively, add pandoc first, then add a script using it :wink: 
___
*[`utils/docker/Dockerfile.centos-7` line 2 at r4](https://reviewable.io/reviews/memkind/memkind/839#-N882lN60kt2lsdvYqae:-N882lN60kt2lsdvYqaf:b-sj0xsx) ([raw file](https://github.com/memkind/memkind/blob/de3ce345704f57ccf900af4087ed831bb3718dcd/utils/docker/Dockerfile.centos-7#L2)):*
> ```
> # SPDX-License-Identifier: BSD-2-Clause
> # Copyright (C) 2020 - 2021 Intel Corporation.
> ```

pls updates dates: `- 2022` (everywhere)
___
*[`utils/docker/Dockerfile.fedora-34` line 48 at r4](https://reviewable.io/reviews/memkind/memkind/839#-N883TFCAJvosQc0DHK2:-N883TFCAJvosQc0DHK3:b8xg78o) ([raw file](https://github.com/memkind/memkind/blob/de3ce345704f57ccf900af4087ed831bb3718dcd/utils/docker/Dockerfile.fedora-34#L48)):*
> ```
>     which \
>     whois \
>     pandoc \
> ```

sort A-Z pls


<!-- Sent from Reviewable.io -->

2022-08-02 10:29 UTC, PatKamin requested changes
> Reviewed 5 of 5 files at r1, 1 of 1 files at r2, 3 of 3 files at r3, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/839)* status: all files reviewed, 14 unresolved discussions (waiting on @bratpiorka, @lukaszstolarczuk, and @szadam)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/memkind/memkind/839#-N8SwqU_24VTTAzoYp_f):*
Please, start with a capital letter to align with commits that are already in the repo.
___
*[`-- commits` line 5 at r4](https://reviewable.io/reviews/memkind/memkind/839#-N889ht806NenCNntqPi):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

I think these 2 changes do not make sense without each other; alternatively, add pandoc first, then add a script using it :wink: 
</blockquote></details>

+1
___
*[`Makefile.am` line 653 at r1](https://reviewable.io/reviews/memkind/memkind/839#-N8Sx3IM7Nh3Uxzr9_DZ:-N8Sx3IM7Nh3Uxzr9_D_:bhw4dbj) ([raw file](https://github.com/memkind/memkind/blob/92ed60fd3e4853d49f384d6704dffdeb051c5eed/Makefile.am#L653)):*
> ```Makefile
> 			utils/md2man/default.man \
> 			doc/memkindallocator.3 \
> 			$(VERSION)
> ```

Shift left tabulation.



_Code quote:_
```Makefile
		utils/md2man/md2man.sh \
			doc/memkindallocator.3.md \
			utils/md2man/default.man \
			doc/memkindallocator.3 \
			$(VERSION)
```
___
*[`doc/memkindallocator.3` line 1 at r1](https://reviewable.io/reviews/memkind/memkind/839#-N8SxeAA3Vmk94fKnT7k:-N8SxeAA3Vmk94fKnT7l:bokz2uz) ([raw file](https://github.com/memkind/memkind/blob/92ed60fd3e4853d49f384d6704dffdeb051c5eed/doc/memkindallocator.3#L1)):*
> ```Roff
> .\" Automatically generated by Pandoc 2.5
> ```

If this file is generated with `make`, then why including it in the repo?
___
*[`doc/memkindallocator.3` line 1 at r1](https://reviewable.io/reviews/memkind/memkind/839#-N8T0aJu4zpuHczEU5o3:-N8T0aJu4zpuHczEU5o4:bp7vwgh) ([raw file](https://github.com/memkind/memkind/blob/92ed60fd3e4853d49f384d6704dffdeb051c5eed/doc/memkindallocator.3#L1)):*
> ```Roff
> .\" Automatically generated by Pandoc 2.5
> ```

Remove the old manual from man/ directory.
___
*[`doc/memkindallocator.3.md` line 10 at r1](https://reviewable.io/reviews/memkind/memkind/839#-N8T0yqOD8LfL1xFuygz:-N8T0yqP8XyMagf1QNEH:b9t3qeg) ([raw file](https://github.com/memkind/memkind/blob/92ed60fd3e4853d49f384d6704dffdeb051c5eed/doc/memkindallocator.3.md#L10)):*
> ```Markdown
> title: MEMKINDALLOCATOR
> section: 3
> ---
> ```

This whole table looks strange in a readme. Remove this, please.



_Code quote:_
```Markdown
---
draft: false
layout: "library"
slider_enable: true
description: ""
disclaimer: "The contents of this web site and the associated <a href=\"https://github.com/memkind\">GitHub repositories</a> are BSD-licensed open source."
aliases: ["memkindallocator.3.html"]
title: MEMKINDALLOCATOR
section: 3
---
```
___
*[`doc/memkindallocator.3.md` line 70 at r1](https://reviewable.io/reviews/memkind/memkind/839#-N8T1fJLBR_y63hEq8Hg:-N8T1fJLBR_y63hEq8Hh:b9gvec) ([raw file](https://github.com/memkind/memkind/blob/92ed60fd3e4853d49f384d6704dffdeb051c5eed/doc/memkindallocator.3.md#L70)):*
> ```Markdown
> >`libmemkind::static_kind::allocator<T>::deallocate(T *p, std::size_t n)` deallocates memory >associated with pointer returned by `allocate()` using `memkind_free()`.
> 
> `libmemkind::kinds` 
> ```

Nit: Too much of the following text is grey and as such is hard to read in a github's dark mode.
___
*[`utils/md2man/default.man` line 21 at r1](https://reviewable.io/reviews/memkind/memkind/839#-N8T4bLR413O8048-TLD:-N8T4bLR413O8048-TLE:b-o1atl5) ([raw file](https://github.com/memkind/memkind/blob/92ed60fd3e4853d49f384d6704dffdeb051c5eed/utils/md2man/default.man#L21)):*
> ```Roff
> $endfor$
> .\" SPDX-License-Identifier: BSD-2-Clause
> .\" Copyright 2022-$year$, Intel Corporation
> ```

Just $year$ would suffice, I think.
___
*[`utils/md2man/md2man.sh` line 2 at r1](https://reviewable.io/reviews/memkind/memkind/839#-N8T5-TEBb-m5S7pYB3E:-N8T5-TEBb-m5S7pYB3F:bweyv5i) ([raw file](https://github.com/memkind/memkind/blob/92ed60fd3e4853d49f384d6704dffdeb051c5eed/utils/md2man/md2man.sh#L2)):*
> ```Shell
> #!/usr/bin/env bash
> # SPDX-License-Identifier: BSD-3-Clause
> ```

BSD-2 if it's created by Intel.
___
*[`utils/md2man/md2man.sh` line 3 at r1](https://reviewable.io/reviews/memkind/memkind/839#-N8T4oz4Eg0_epudecpU:-N8T4oz4Eg0_epudecpV:b-zc3v1p) ([raw file](https://github.com/memkind/memkind/blob/92ed60fd3e4853d49f384d6704dffdeb051c5eed/utils/md2man/md2man.sh#L3)):*
> ```Shell
> #!/usr/bin/env bash
> # SPDX-License-Identifier: BSD-3-Clause
> # Copyright 2016-2021, Intel Corporation
> ```

It's a brand new file - why 2016? Is it some kind of a template?
___
*[`utils/md2man/md2man.sh` line 13 at r5](https://reviewable.io/reviews/memkind/memkind/839#-N8T5J0T2Gox-0UgG_xY:-N8T5J0U5Pumb3olk14z:btcev82) ([raw file](https://github.com/memkind/memkind/blob/cd4375cba14f499543d052ada7d1370e0431aeb0/utils/md2man/md2man.sh#L13)):*
> ```Shell
> 
> set -x
> # set -e
> ```

Either remove this line or leave it. Don't just comment out.


<!-- Sent from Reviewable.io -->

2022-08-02 13:31 UTC, maciekpac reviewed
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/839)* status: all files reviewed, 13 unresolved discussions (waiting on @lukaszstolarczuk, @PatKamin, and @szadam)

___
*[`utils/md2man/default.man` line 21 at r1](https://reviewable.io/reviews/memkind/memkind/839#-N8T4bLR413O8048-TLD:-N8Tk0fH3AnF_jK0RwSz:b55ysum) ([raw file](https://github.com/memkind/memkind/blob/92ed60fd3e4853d49f384d6704dffdeb051c5eed/utils/md2man/default.man#L21)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Just $year$ would suffice, I think.
</blockquote></details>

I think we put ranges everywhere, don't we ?


<!-- Sent from Reviewable.io -->

2022-08-03 07:56 UTC, PatKamin requested changes
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/839)* status: all files reviewed, 13 unresolved discussions (waiting on @lukaszstolarczuk, @maciekpac, and @szadam)

___
*[`utils/md2man/default.man` line 21 at r1](https://reviewable.io/reviews/memkind/memkind/839#-N8T4bLR413O8048-TLD:-N8XgQ8S0wBvd0z00k_H:b-87s4f0) ([raw file](https://github.com/memkind/memkind/blob/92ed60fd3e4853d49f384d6704dffdeb051c5eed/utils/md2man/default.man#L21)):*
<details><summary><i>Previously, maciekpac wrote…</i></summary><blockquote>

I think we put ranges everywhere, don't we ?
</blockquote></details>

As I understand this file is a template for generating manpages with the `make` command. If that's true, then generating manuals with ie. 2022-2022 (in such a case range is redundant) or 2022-2023 makes no sense at all as manuals could be written prior to 2022. They could be written after 2022 as well.


<!-- Sent from Reviewable.io -->

2022-08-03 08:24 UTC, lukaszstolarczuk reviewed
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/839)* status: all files reviewed, 13 unresolved discussions (waiting on @PatKamin and @szadam)

___
*[`doc/memkindallocator.3.md` line 10 at r1](https://reviewable.io/reviews/memkind/memkind/839#-N8T0yqOD8LfL1xFuygz:-N8XieiIAG5t0rN_jlnj:bqrcr) ([raw file](https://github.com/memkind/memkind/blob/92ed60fd3e4853d49f384d6704dffdeb051c5eed/doc/memkindallocator.3.md#L10)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

This whole table looks strange in a readme. Remove this, please.
</blockquote></details>

Actually, you need this metadata for the website.

I'd say you generally should either point your users to the website or to the generated manpages. I'm guessing if someone really wants to read it on the GH repo then they can just skip over that weird table :wink: (but that's just my opinion, perhaps there's better way to approach this metadata :wink: )
___
*[`utils/md2man/default.man` line 21 at r1](https://reviewable.io/reviews/memkind/memkind/839#-N8T4bLR413O8048-TLD:-N8Xn-wj4VG6PdU0qwN-:byqvwo0) ([raw file](https://github.com/memkind/memkind/blob/92ed60fd3e4853d49f384d6704dffdeb051c5eed/utils/md2man/default.man#L21)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

As I understand this file is a template for generating manpages with the `make` command. If that's true, then generating manuals with ie. 2022-2022 (in such a case range is redundant) or 2022-2023 makes no sense at all as manuals could be written prior to 2022. They could be written after 2022 as well.
</blockquote></details>

maybe it should be just `<original_date_of_man_creation>-$year$` instead of the current `2022-$year$`
___
*[`utils/md2man/md2man.sh` line 15 at r1](https://reviewable.io/reviews/memkind/memkind/839#-N8XnJWLBhsZ7Uha0st8:-N8XnJWLBhsZ7Uha0st9:b-ppnq0z) ([raw file](https://github.com/memkind/memkind/blob/92ed60fd3e4853d49f384d6704dffdeb051c5eed/utils/md2man/md2man.sh#L15)):*
> ```Shell
> set -o pipefail
> 
> # read input params (usually passed from doc/CMakeLists.txt)
> ```

heh, CMake :smile: 


<!-- Sent from Reviewable.io -->

2022-08-03 08:32 UTC, szadam reviewed
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/839)* status: all files reviewed, 13 unresolved discussions (waiting on @maciekpac, @PatKamin, and @szadam)

___
*[`.github/workflows/gha.yml` line 118 at r2](https://reviewable.io/reviews/memkind/memkind/839#-N7_GZbnGIXU9D4r5eOn-r2-118:-N8XpMBt4dDr8Rz1FB90:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/0b0d7c3cc76922bbea816db986e80159337df91f/.github/workflows/gha.yml#L118)):*
<details><summary><i>Previously, maciekpac wrote…</i></summary><blockquote>

I think this is not the job that is failing.

The one that's failing has `name: Docker build [xxx]`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-08-03 08:35 UTC, PatKamin requested changes
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/839)* status: all files reviewed, 11 unresolved discussions (waiting on @lukaszstolarczuk, @maciekpac, and @szadam)

___
*[`doc/memkindallocator.3.md` line 10 at r1](https://reviewable.io/reviews/memkind/memkind/839#-N8T0yqOD8LfL1xFuygz:-N8XpVgn4wocm7ov8Yv4:b-tn5q9y) ([raw file](https://github.com/memkind/memkind/blob/92ed60fd3e4853d49f384d6704dffdeb051c5eed/doc/memkindallocator.3.md#L10)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

Actually, you need this metadata for the website.

I'd say you generally should either point your users to the website or to the generated manpages. I'm guessing if someone really wants to read it on the GH repo then they can just skip over that weird table :wink: (but that's just my opinion, perhaps there's better way to approach this metadata :wink: )
</blockquote></details>

OK, that's fair enough.
___
*[`utils/md2man/default.man` line 21 at r1](https://reviewable.io/reviews/memkind/memkind/839#-N8T4bLR413O8048-TLD:-N8XpfVI7zEoPdP52MXu:b480gph) ([raw file](https://github.com/memkind/memkind/blob/92ed60fd3e4853d49f384d6704dffdeb051c5eed/utils/md2man/default.man#L21)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

maybe it should be just `<original_date_of_man_creation>-$year$` instead of the current `2022-$year$`
</blockquote></details>

That would be great (except the situation when both are the same, but that's a minor issue).


<!-- Sent from Reviewable.io -->

2022-08-03 08:57 UTC, lukaszstolarczuk reviewed
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/839)* status: all files reviewed, 12 unresolved discussions (waiting on @lukaszstolarczuk, @maciekpac, and @szadam)

___
*[`.github/workflows/gha.yml` line 118 at r2](https://reviewable.io/reviews/memkind/memkind/839#-N7_GZbnGIXU9D4r5eOn-r2-118:-N8XuoQb-L2TLTeptHxR:bmpfatm) ([raw file](https://github.com/memkind/memkind/blob/0b0d7c3cc76922bbea816db986e80159337df91f/.github/workflows/gha.yml#L118)):*
<details><summary><i>Previously, szadam wrote…</i></summary><blockquote>

Done.
</blockquote></details>

are you sure you need this `pandoc` here? it seems you only require it inside dockers, or maybe in some jobs (I may not be aware of) which run `make all`/`make man-local`


<!-- Sent from Reviewable.io -->

2022-08-03 09:12 UTC, bratpiorka commented
*[`utils/md2man/md2man.sh` line 39 at r5](https://reviewable.io/reviews/memkind/memkind/839#-N8XyKhBCAQWzlOiVovx:-N8XyKhBCAQWzlOiVovy:b63q5ar) ([raw file](https://github.com/memkind/memkind/blob/cd4375cba14f499543d052ada7d1370e0431aeb0/utils/md2man/md2man.sh#L39)):*
> ```Shell
> # 3. unindent code blocks
> cat $filename | sed -n -e '/# NAME #/,$p' |\
> 	pandoc -s -t man -o $outfile --template=$template \
> ```

please check if the pandoc is present in the system and DO NOT FAIL make if not



_Code quote:_
```Shell
pandoc 
```


<!-- Sent from Reviewable.io -->

2022-08-03 09:15 UTC, bratpiorka requested changes
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/839)* status: all files reviewed, 14 unresolved discussions (waiting on @lukaszstolarczuk, @maciekpac, and @szadam)

___
*[`utils/md2man/md2man.sh` line 48 at r5](https://reviewable.io/reviews/memkind/memkind/839#-N8XzD_JCEsKmetc3Wzd:-N8XzD_JCEsKmetc3Wze:b-5boz0j) ([raw file](https://github.com/memkind/memkind/blob/cd4375cba14f499543d052ada7d1370e0431aeb0/utils/md2man/md2man.sh#L48)):*
> ```Shell
> 	s/IP/PP/
>     }
> }'
> ```

please add info to README that a pandoc is required depedency for generating documentation



_Code quote:_
```Shell
}'
```


<!-- Sent from Reviewable.io -->

2022-08-03 09:30 UTC, szadam reviewed
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/839)* status: all files reviewed, 14 unresolved discussions (waiting on @lukaszstolarczuk, @maciekpac, @PatKamin, and @szadam)

___
*[`.github/workflows/gha.yml` line 118 at r2](https://reviewable.io/reviews/memkind/memkind/839#-N7_GZbnGIXU9D4r5eOn-r2-118:-N8Y0T2349VPfbKa5y2M:bk2aywb) ([raw file](https://github.com/memkind/memkind/blob/0b0d7c3cc76922bbea816db986e80159337df91f/.github/workflows/gha.yml#L118)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

are you sure you need this `pandoc` here? it seems you only require it inside dockers, or maybe in some jobs (I may not be aware of) which run `make all`/`make man-local`
</blockquote></details>

yes, I`m sure. In other case I have more issue.
___
*[`doc/memkindallocator.3` line 1 at r1](https://reviewable.io/reviews/memkind/memkind/839#-N8SxeAA3Vmk94fKnT7k:-N8Y0fEH4nCjBGKjbTz0:b-xuxlza) ([raw file](https://github.com/memkind/memkind/blob/92ed60fd3e4853d49f384d6704dffdeb051c5eed/doc/memkindallocator.3#L1)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

If this file is generated with `make`, then why including it in the repo?
</blockquote></details>

solved (discussion
___
*[`doc/memkindallocator.3` line 1 at r1](https://reviewable.io/reviews/memkind/memkind/839#-N8T0aJu4zpuHczEU5o3:-N8Y0o9c9rYtSOhDGW9d:bftqwa7) ([raw file](https://github.com/memkind/memkind/blob/92ed60fd3e4853d49f384d6704dffdeb051c5eed/doc/memkindallocator.3#L1)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Remove the old manual from man/ directory.
</blockquote></details>

solved (discussion)


<!-- Sent from Reviewable.io -->

2022-08-03 10:01 UTC, PatKamin requested changes
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/839)* status: all files reviewed, 14 unresolved discussions (waiting on @lukaszstolarczuk, @maciekpac, @PatKamin, and @szadam)

___
*[`doc/memkindallocator.3` line 1 at r1](https://reviewable.io/reviews/memkind/memkind/839#-N8T0aJu4zpuHczEU5o3:-N8Y86Au3iGBduH5IuR6:bz2g830) ([raw file](https://github.com/memkind/memkind/blob/92ed60fd3e4853d49f384d6704dffdeb051c5eed/doc/memkindallocator.3#L1)):*
<details><summary><i>Previously, szadam wrote…</i></summary><blockquote>

solved (discussion)
</blockquote></details>

I don't see a reason why two versions of manuals should be kept - one in doc/ and the other in man/.


<!-- Sent from Reviewable.io -->

2022-08-03 10:14 UTC, bratpiorka requested changes
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/839)* status: all files reviewed, 16 unresolved discussions (waiting on @lukaszstolarczuk, @maciekpac, @PatKamin, and @szadam)

___
*[`Makefile.am` line 652 at r1](https://reviewable.io/reviews/memkind/memkind/839#-N8YA8f_ES2nT0X8p9cO:-N8YA8f_ES2nT0X8p9cP:b1irqj1) ([raw file](https://github.com/memkind/memkind/blob/92ed60fd3e4853d49f384d6704dffdeb051c5eed/Makefile.am#L652)):*
> ```Makefile
> 			doc/memkindallocator.3.md \
> 			utils/md2man/default.man \
> 			doc/memkindallocator.3 \
> ```

I think that "md" files should be placed in "doc" folder, but "man" files should be placed in "man" dir. All - what do you think?



_Code quote:_
```Makefile
doc/
```
___
*[`Makefile.am` line 652 at r1](https://reviewable.io/reviews/memkind/memkind/839#-N8YAS4Q8onq-sSYjuOv:-N8YAS4Q8onq-sSYjuOw:b9pmjky) ([raw file](https://github.com/memkind/memkind/blob/92ed60fd3e4853d49f384d6704dffdeb051c5eed/Makefile.am#L652)):*
> ```Makefile
> 			doc/memkindallocator.3.md \
> 			utils/md2man/default.man \
> 			doc/memkindallocator.3 \
> ```

what about other files?



_Code quote:_
```Makefile
doc/memkindallocator.3
```


<!-- Sent from Reviewable.io -->

2022-08-03 10:16 UTC, PatKamin reviewed
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/839)* status: all files reviewed, 16 unresolved discussions (waiting on @bratpiorka, @lukaszstolarczuk, @maciekpac, @PatKamin, and @szadam)

___
*[`Makefile.am` line 652 at r1](https://reviewable.io/reviews/memkind/memkind/839#-N8YA8f_ES2nT0X8p9cO:-N8YC4cFAnAIHaib9BYd:btd51a6) ([raw file](https://github.com/memkind/memkind/blob/92ed60fd3e4853d49f384d6704dffdeb051c5eed/Makefile.am#L652)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

I think that "md" files should be placed in "doc" folder, but "man" files should be placed in "man" dir. All - what do you think?
</blockquote></details>

I agree.


<!-- Sent from Reviewable.io -->

2022-08-03 20:16 UTC, szadam reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/839)* status: 6 of 9 files reviewed, 16 unresolved discussions (waiting on @bratpiorka, @lukaszstolarczuk, @maciekpac, @PatKamin, and @szadam)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/memkind/memkind/839#-N8SwqU_24VTTAzoYp_f):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Please, start with a capital letter to align with commits that are already in the repo.
</blockquote></details>

Done.
___
*[`-- commits` line 5 at r4](https://reviewable.io/reviews/memkind/memkind/839#-N889ht806NenCNntqPi):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

+1
</blockquote></details>

Done.
___
*[`Makefile.am` line 653 at r1](https://reviewable.io/reviews/memkind/memkind/839#-N8Sx3IM7Nh3Uxzr9_DZ:-N8_L8Yt4w-O1xvxcwMY:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/92ed60fd3e4853d49f384d6704dffdeb051c5eed/Makefile.am#L653)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Shift left tabulation.
</blockquote></details>

Done.
___
*[`utils/md2man/md2man.sh` line 15 at r1](https://reviewable.io/reviews/memkind/memkind/839#-N8XnJWLBhsZ7Uha0st8:-N8_LOkW6d3Uo05TVfgX:b32vji) ([raw file](https://github.com/memkind/memkind/blob/92ed60fd3e4853d49f384d6704dffdeb051c5eed/utils/md2man/md2man.sh#L15)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

heh, CMake :smile: 
</blockquote></details>

;D
___
*[`utils/md2man/md2man.sh` line 13 at r5](https://reviewable.io/reviews/memkind/memkind/839#-N8T5J0T2Gox-0UgG_xY:-N8_LO7V52Y5UYnvdkbh:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/cd4375cba14f499543d052ada7d1370e0431aeb0/utils/md2man/md2man.sh#L13)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Either remove this line or leave it. Don't just comment out.
</blockquote></details>

Done.
___
*[`utils/md2man/md2man.sh` line 39 at r5](https://reviewable.io/reviews/memkind/memkind/839#-N8XyKhBCAQWzlOiVovx:-N8_LSeTEaETCLfYhwgK:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/cd4375cba14f499543d052ada7d1370e0431aeb0/utils/md2man/md2man.sh#L39)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

please check if the pandoc is present in the system and DO NOT FAIL make if not
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-08-04 06:52 UTC, PatKamin reviewed
> Reviewed 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/839)* status: all files reviewed, 12 unresolved discussions (waiting on @bratpiorka, @lukaszstolarczuk, @maciekpac, and @szadam)



<!-- Sent from Reviewable.io -->

2022-08-04 12:09 UTC, szadam reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/839)* status: 8 of 9 files reviewed, 12 unresolved discussions (waiting on @bratpiorka, @lukaszstolarczuk, @maciekpac, @PatKamin, and @szadam)



<!-- Sent from Reviewable.io -->

2022-08-05 10:03 UTC, szadam reviewed
> Reviewed 1 of 3 files at r6, 6 of 8 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/839)* status: 8 of 11 files reviewed, 12 unresolved discussions (waiting on @bratpiorka, @lukaszstolarczuk, @maciekpac, @PatKamin, and @szadam)

___
*[`doc/memkindallocator.3.md` line 70 at r1](https://reviewable.io/reviews/memkind/memkind/839#-N8T1fJLBR_y63hEq8Hg:-N8gx1tgArwmv3OpjIBJ:bevr85q) ([raw file](https://github.com/memkind/memkind/blob/92ed60fd3e4853d49f384d6704dffdeb051c5eed/doc/memkindallocator.3.md#L70)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Nit: Too much of the following text is grey and as such is hard to read in a github's dark mode.
</blockquote></details>

Is it really such a big problem? What do you suggest?
___
*[`utils/docker/Dockerfile.centos-7` line 2 at r4](https://reviewable.io/reviews/memkind/memkind/839#-N882lN60kt2lsdvYqae:-N8hSEpH7YqtSvdw3jif:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/de3ce345704f57ccf900af4087ed831bb3718dcd/utils/docker/Dockerfile.centos-7#L2)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

pls updates dates: `- 2022` (everywhere)
</blockquote></details>

Done.
___
*[`utils/docker/Dockerfile.fedora-34` line 48 at r4](https://reviewable.io/reviews/memkind/memkind/839#-N883TFCAJvosQc0DHK2:-N8hSGf3C0oi3PkWpLRv:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/de3ce345704f57ccf900af4087ed831bb3718dcd/utils/docker/Dockerfile.fedora-34#L48)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

sort A-Z pls
</blockquote></details>

Done.
___
*[`utils/md2man/default.man` line 21 at r1](https://reviewable.io/reviews/memkind/memkind/839#-N8T4bLR413O8048-TLD:-N8hSIpLDqbvrSoSz9Ek:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/92ed60fd3e4853d49f384d6704dffdeb051c5eed/utils/md2man/default.man#L21)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

That would be great (except the situation when both are the same, but that's a minor issue).
</blockquote></details>

Done.
___
*[`utils/md2man/md2man.sh` line 48 at r5](https://reviewable.io/reviews/memkind/memkind/839#-N8XzD_JCEsKmetc3Wzd:-N8hSMvy6thh_mkNw6h2:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/cd4375cba14f499543d052ada7d1370e0431aeb0/utils/md2man/md2man.sh#L48)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

please add info to README that a pandoc is required depedency for generating documentation
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-08-05 10:27 UTC, maciekpac reviewed
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/839)* status: 8 of 11 files reviewed, 12 unresolved discussions (waiting on @bratpiorka, @lukaszstolarczuk, @maciekpac, @PatKamin, and @szadam)

___
*[`doc/memkindallocator.3.md` line 70 at r1](https://reviewable.io/reviews/memkind/memkind/839#-N8T1fJLBR_y63hEq8Hg:-N8hTeOJCtHyqrW8mQ34:bxrysr6) ([raw file](https://github.com/memkind/memkind/blob/92ed60fd3e4853d49f384d6704dffdeb051c5eed/doc/memkindallocator.3.md#L70)):*
The whole section looks like a kind of comment...

Dark mode is widely used, especially among programmers.

https://nighteye.app/dark-mode/

Maybe you could try using definition list instead of block quotes? Or sth else ? It's strange to keep everything as a blockquote...

```md
> block quote

Item
: definition first line
definition second line
```

renders to

> block quote

Item
: definition first line
definition second line

edit: the second one does not render as expected in reviewable.io, you can check it e.g. here https://stackedit.io/app#


<!-- Sent from Reviewable.io -->

2022-08-08 06:03 UTC, lukaszstolarczuk reviewed
> Reviewed 1 of 1 files at r2, 3 of 8 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/839)* status: 9 of 11 files reviewed, 9 unresolved discussions (waiting on @bratpiorka, @maciekpac, @PatKamin, and @szadam)

___
*[`utils/md2man/md2man.sh` line 15 at r1](https://reviewable.io/reviews/memkind/memkind/839#-N8XnJWLBhsZ7Uha0st8:-N8w1kFF9D3a3dtbvtYF:bcphazp) ([raw file](https://github.com/memkind/memkind/blob/92ed60fd3e4853d49f384d6704dffdeb051c5eed/utils/md2man/md2man.sh#L15)):*
<details><summary><i>Previously, szadam wrote…</i></summary><blockquote>

;D
</blockquote></details>

you can update that comment :stuck_out_tongue_winking_eye: 
___
*[`utils/md2man/md2man.sh` line 39 at r5](https://reviewable.io/reviews/memkind/memkind/839#-N8XyKhBCAQWzlOiVovx:-N8w1s2w44KJXXaI9Lk4:b-hndcz9) ([raw file](https://github.com/memkind/memkind/blob/cd4375cba14f499543d052ada7d1370e0431aeb0/utils/md2man/md2man.sh#L39)):*
<details><summary><i>Previously, szadam wrote…</i></summary><blockquote>

Done.
</blockquote></details>

not done?


<!-- Sent from Reviewable.io -->

2022-08-08 06:37 UTC, PatKamin requested changes
> Reviewed 1 of 1 files at r8, 8 of 8 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/839)* status: all files reviewed, 12 unresolved discussions (waiting on @bratpiorka, @lukaszstolarczuk, @maciekpac, @PatKamin, and @szadam)

___
*[`doc/memkindallocator.3` line 1 at r1](https://reviewable.io/reviews/memkind/memkind/839#-N8T0aJu4zpuHczEU5o3:-N8w9qX13OohF_ip7n0l:bz6z3ha) ([raw file](https://github.com/memkind/memkind/blob/92ed60fd3e4853d49f384d6704dffdeb051c5eed/doc/memkindallocator.3#L1)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

I don't see a reason why two versions of manuals should be kept - one in doc/ and the other in man/.
</blockquote></details>

Add this file to the man/ directory.
___
*[`utils/docker/docker_run_build.sh` line 3 at r9](https://reviewable.io/reviews/memkind/memkind/839#-N8w7BUv0u-dn_m2x-M7:-N8w7BUv0u-dn_m2x-M8:b8ok3wi) ([raw file](https://github.com/memkind/memkind/blob/9250810a064a12679dbee744b387f4333c67dec1/utils/docker/docker_run_build.sh#L3)):*
> ```Shell
> #!/bin/bash
> # SPDX-License-Identifier: BSD-2-Clause
> # Copyright (C) 2019 - 2022 Intel Corporation.
> ```

There are no changes introduced in this file. Revert this year change.
___
*[`utils/docker/README.md` line 68 at r9](https://reviewable.io/reviews/memkind/memkind/839#-N8w7_Yy-Q_lO0xdgG4Y:-N8w7_Yy-Q_lO0xdgG4Z:b-qcfeof) ([raw file](https://github.com/memkind/memkind/blob/9250810a064a12679dbee744b387f4333c67dec1/utils/docker/README.md#L68)):*
> ```Markdown
> Others class group must have write permission to MEMKIND_HOST_WORKDIR to use the run_local script.
> 
> Pandoc is required dependency for generating man documentation.
> ```

This comment should be rather in the main README file for memkind. This pandoc dependency will be installed in containers anyway. It's not required to have it on a host server in order to run docker scripts. 
___
*[`utils/md2man/default.man` line 21 at r1](https://reviewable.io/reviews/memkind/memkind/839#-N8T4bLR413O8048-TLD:-N8w8V945LLEkSKRDVJv:bojt7eh) ([raw file](https://github.com/memkind/memkind/blob/92ed60fd3e4853d49f384d6704dffdeb051c5eed/utils/md2man/default.man#L21)):*
<details><summary><i>Previously, szadam wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not all man pages were created in 2014. If it's not possible to have a variable like $original_date_of_man_creation$, then leave just a $year$ var here.
___
*[`utils/md2man/md2man.sh` line 2 at r9](https://reviewable.io/reviews/memkind/memkind/839#-N8w9BjZ2BzlQf64Bq83:-N8w9BjZ2BzlQf64Bq84:b-yumzr1) ([raw file](https://github.com/memkind/memkind/blob/9250810a064a12679dbee744b387f4333c67dec1/utils/md2man/md2man.sh#L2)):*
> ```Shell
> #!/usr/bin/env bash
> # SPDX-License-Identifier: BSD-2-Clause
> ```

If this file is copied from some other pmdk repo, then don't change it's license.


<!-- Sent from Reviewable.io -->

2022-08-08 07:33 UTC, szadam commented
*[`utils/md2man/md2man.sh` line 39 at r5](https://reviewable.io/reviews/memkind/memkind/839#-N8XyKhBCAQWzlOiVovx:-N8wMcSX5Gm8TK7QIQvd:b-eb9a63) ([raw file](https://github.com/memkind/memkind/blob/cd4375cba14f499543d052ada7d1370e0431aeb0/utils/md2man/md2man.sh#L39)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

not done?
</blockquote></details>

please explain me, what should I check?


<!-- Sent from Reviewable.io -->

2022-08-08 07:43 UTC, szadam reviewed
> Reviewed 4 of 7 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/839)* status: 9 of 12 files reviewed, 11 unresolved discussions (waiting on @bratpiorka, @lukaszstolarczuk, @maciekpac, @PatKamin, and @szadam)

___
*[`utils/docker/docker_run_build.sh` line 3 at r9](https://reviewable.io/reviews/memkind/memkind/839#-N8w7BUv0u-dn_m2x-M7:-N8wOtYOEU3RGlxSpfHE:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/9250810a064a12679dbee744b387f4333c67dec1/utils/docker/docker_run_build.sh#L3)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

There are no changes introduced in this file. Revert this year change.
</blockquote></details>

Done.
___
*[`utils/docker/README.md` line 68 at r9](https://reviewable.io/reviews/memkind/memkind/839#-N8w7_Yy-Q_lO0xdgG4Y:-N8wOuexACdOajbnrIuE:bh95ke4) ([raw file](https://github.com/memkind/memkind/blob/9250810a064a12679dbee744b387f4333c67dec1/utils/docker/README.md#L68)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

This comment should be rather in the main README file for memkind. This pandoc dependency will be installed in containers anyway. It's not required to have it on a host server in order to run docker scripts. 
</blockquote></details>

You're right
___
*[`utils/md2man/md2man.sh` line 2 at r9](https://reviewable.io/reviews/memkind/memkind/839#-N8w9BjZ2BzlQf64Bq83:-N8wP3a-Bx3O8PtQt-_W:bb7m0b9) ([raw file](https://github.com/memkind/memkind/blob/9250810a064a12679dbee744b387f4333c67dec1/utils/md2man/md2man.sh#L2)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

If this file is copied from some other pmdk repo, then don't change it's license.
</blockquote></details>

okey


<!-- Sent from Reviewable.io -->

2022-08-08 07:47 UTC, lukaszstolarczuk reviewed
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/839)* status: 9 of 12 files reviewed, 11 unresolved discussions (waiting on @bratpiorka, @lukaszstolarczuk, @maciekpac, @PatKamin, and @szadam)

___
*[`utils/md2man/md2man.sh` line 39 at r5](https://reviewable.io/reviews/memkind/memkind/839#-N8XyKhBCAQWzlOiVovx:-N8wPHUcAg4alMy5Zapc:b-o5s7uc) ([raw file](https://github.com/memkind/memkind/blob/cd4375cba14f499543d052ada7d1370e0431aeb0/utils/md2man/md2man.sh#L39)):*
<details><summary><i>Previously, szadam (Adam Szopiński) wrote…</i></summary><blockquote>

please explain me, what should I check?
</blockquote></details>

as Rafał stated - it'd be nice to check if `pandoc` command is available in the system. You can either check here, using some bash `if` (e.g. something a bit similar to this: https://github.com/pmem/pmemstream/blob/master/utils/docker/prepare-for-build.sh#L36-L37 - but you only need to check if the pandoc command is working); if it isn't then you can just end up this script (with no error) and print some information

or you could potentially do the check in makefile (but here is more safe, because someone could use this script "by hand", not using make)


<!-- Sent from Reviewable.io -->

2022-08-08 11:24 UTC, bratpiorka requested changes
> Reviewed 1 of 1 files at r2, 4 of 8 files at r9, 2 of 7 files at r10, 2 of 2 files at r11, 6 of 7 files at r12, 6 of 6 files at r13.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/839)* status: 11 of 25 files reviewed, 7 unresolved discussions (waiting on @bratpiorka, @lukaszstolarczuk, @maciekpac, @PatKamin, and @szadam)

___
*[`.github/workflows/gha.yml` line 118 at r2](https://reviewable.io/reviews/memkind/memkind/839#-N7_GZbnGIXU9D4r5eOn-r2-118:-N8xA1JY79VkI-zNzf-E:b3unn3y) ([raw file](https://github.com/memkind/memkind/blob/0b0d7c3cc76922bbea816db986e80159337df91f/.github/workflows/gha.yml#L118)):*
<details><summary><i>Previously, szadam (Adam Szopiński) wrote…</i></summary><blockquote>

yes, I`m sure. In other case I have more issue.
</blockquote></details>

pandoc is not needed here in "building job". Instead of this please create a separate job that will run man-local Makefile target and check if man files that are included into the repository are up-to-date
___
*[`utils/md2man/md2man.sh` line 39 at r5](https://reviewable.io/reviews/memkind/memkind/839#-N8XyKhBCAQWzlOiVovx:-N8xAsT0DDqa7CbQCU1S:b-py02ke) ([raw file](https://github.com/memkind/memkind/blob/cd4375cba14f499543d052ada7d1370e0431aeb0/utils/md2man/md2man.sh#L39)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

as Rafał stated - it'd be nice to check if `pandoc` command is available in the system. You can either check here, using some bash `if` (e.g. something a bit similar to this: https://github.com/pmem/pmemstream/blob/master/utils/docker/prepare-for-build.sh#L36-L37 - but you only need to check if the pandoc command is working); if it isn't then you can just end up this script (with no error) and print some information

or you could potentially do the check in makefile (but here is more safe, because someone could use this script "by hand", not using make)
</blockquote></details>

yes, please print an error if pandoc is not installed. If you removed the man-local target from the default make then this target shouldn't fail anyway, but this is expected to fail man-local if there are no pandoc in the system.


<!-- Sent from Reviewable.io -->

2022-08-08 11:25 UTC, bratpiorka reviewed
> Reviewed 6 of 14 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/839)* status: 17 of 25 files reviewed, 7 unresolved discussions (waiting on @bratpiorka, @lukaszstolarczuk, @maciekpac, @PatKamin, and @szadam)



<!-- Sent from Reviewable.io -->

2022-08-09 16:43 UTC, szadam reviewed
> Reviewed 1 of 2 files at r16.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/839)* status: 52 of 53 files reviewed, 7 unresolved discussions (waiting on @bratpiorka, @lukaszstolarczuk, @maciekpac, and @PatKamin)

___
*[`utils/md2man/default.man` line 21 at r1](https://reviewable.io/reviews/memkind/memkind/839#-N8T4bLR413O8048-TLD:-N92UAO3545z_1EmFxHj:bdl5bcx) ([raw file](https://github.com/memkind/memkind/blob/92ed60fd3e4853d49f384d6704dffdeb051c5eed/utils/md2man/default.man#L21)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Not all man pages were created in 2014. If it's not possible to have a variable like $original_date_of_man_creation$, then leave just a $year$ var here.
</blockquote></details>

okey, I will just leave like that
___
*[`utils/md2man/md2man.sh` line 15 at r1](https://reviewable.io/reviews/memkind/memkind/839#-N8XnJWLBhsZ7Uha0st8:-N92UFhJB5H3FyjrqMmv:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/92ed60fd3e4853d49f384d6704dffdeb051c5eed/utils/md2man/md2man.sh#L15)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

you can update that comment :stuck_out_tongue_winking_eye: 
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-08-10 08:26 UTC, szadam reviewed
> Reviewed 1 of 2 files at r17, 23 of 24 files at r18, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/839)* status: 52 of 53 files reviewed, 7 unresolved discussions (waiting on @bratpiorka, @lukaszstolarczuk, @maciekpac, and @PatKamin)

___
*[`utils/md2man/md2man.sh` line 39 at r5](https://reviewable.io/reviews/memkind/memkind/839#-N8XyKhBCAQWzlOiVovx:-N95qs9UDM4gaj8LTila:b-iqxofb) ([raw file](https://github.com/memkind/memkind/blob/cd4375cba14f499543d052ada7d1370e0431aeb0/utils/md2man/md2man.sh#L39)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

yes, please print an error if pandoc is not installed. If you removed the man-local target from the default make then this target shouldn't fail anyway, but this is expected to fail man-local if there are no pandoc in the system.
</blockquote></details>

I have hope that I understand correctly. I propose something like this


<!-- Sent from Reviewable.io -->

2022-08-10 08:33 UTC, PatKamin requested changes
> Reviewed 1 of 7 files at r10, 1 of 2 files at r11, 23 of 43 files at r15, 2 of 2 files at r17.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/839)* status: 52 of 53 files reviewed, 17 unresolved discussions (waiting on @bratpiorka, @lukaszstolarczuk, @maciekpac, @PatKamin, and @szadam)

___
*[`-- commits` line 5 at r17](https://reviewable.io/reviews/memkind/memkind/839#-N95gIkc2Jjut5qgOapX):*
Begin commit messages with a capital letter.
___
*[`README` line 92 at r17](https://reviewable.io/reviews/memkind/memkind/839#-N95j3Be2Q7UDDObg5Sw:-N95j3Bf6JtEneGPYcCj:b-qj1f7i) ([raw file](https://github.com/memkind/memkind/blob/34b1fbf52cd8323c100e5027a3aa9886b6000518/README#L92)):*
> ```
> * **hwloc-devel** (v2.3.0 or later)
> 
> You will need to install **pandoc** for generating man documentation.
> ```

Add an information on how to generate this documentation.
___
*[`doc/autohbw.7.md` line 52 at r17](https://reviewable.io/reviews/memkind/memkind/839#-N95kx-qEIrpmwWft-VP:-N95kx-qEIrpmwWft-VQ:b-9fw9f3) ([raw file](https://github.com/memkind/memkind/blob/34b1fbf52cd8323c100e5027a3aa9886b6000518/doc/autohbw.7.md#L52)):*
> ```Markdown
> 
> `AUTO_HBW_SIZE=x:[y]`
> :   Indicates that any allocation larger than x and smaller than y should be allocated in HBW memory.  x and y can be followed by a K, M, or G to indicate the size in Kilo/Memga/Giga bytes (e.g., 4K, 3M, 2G).
> ```

Parameters `x`and `y` in text in italics, please. This way it will be much easier to spot them.
___
*[`doc/autohbw.7.md` line 63 at r17](https://reviewable.io/reviews/memkind/memkind/839#-N95lbAS9GMmoS7elH7c:-N95lbAS9GMmoS7elH7d:b-gxkwzz) ([raw file](https://github.com/memkind/memkind/blob/34b1fbf52cd8323c100e5027a3aa9886b6000518/doc/autohbw.7.md#L63)):*
> ```Markdown
> 
> `AUTO_HBW_LOG=level`
> :   Sets the value of logging (printing) level.  If level is:
> ```

`level` in italics



_Code quote:_
```Markdown
If level is
```
___
*[`doc/autohbw.7.md` line 66 at r17](https://reviewable.io/reviews/memkind/memkind/839#-N95liIs8nSBAOJ5vvU6:-N95liIs8nSBAOJ5vvU7:bniv9jv) ([raw file](https://github.com/memkind/memkind/blob/34b1fbf52cd8323c100e5027a3aa9886b6000518/doc/autohbw.7.md#L66)):*
> ```Markdown
> 
> + -1 no messages are printed
> + 0 no allocations messages are printed but INFO messages are printe
> ```

are printed



_Code quote:_
```Markdown
are printe
```
___
*[`doc/memkind.3.md` line 259 at r17](https://reviewable.io/reviews/memkind/memkind/839#-N95mtU87R4F_UrtYoKG:-N95mtU87R4F_UrtYoKH:bdur5mc) ([raw file](https://github.com/memkind/memkind/blob/34b1fbf52cd8323c100e5027a3aa9886b6000518/doc/memkind.3.md#L259)):*
> ```Markdown
> **The available kinds of memory:**
> 
> MEMKIND_DEFAULT
> ```

All kind names in bold. Same for all other constants. See the current formatting of man pages.
___
*[`doc/memkind_arena.3.md` line 124 at r17](https://reviewable.io/reviews/memkind/memkind/839#-N95nKfL8CHhwIzVR3Vc:-N95nKfL8CHhwIzVR3Vd:b-c0o4bw) ([raw file](https://github.com/memkind/memkind/blob/34b1fbf52cd8323c100e5027a3aa9886b6000518/doc/memkind_arena.3.md#L124)):*
> ```Markdown
> The available options for printing statistics:
> 
> MEMKIND_STAT_PRINT_ALL
> ```

All options in bold.
___
*[`doc/memkind_pmem.3.md` line 61 at r17](https://reviewable.io/reviews/memkind/memkind/839#-N95nyFn-khUNBhfsten:-N95nyFn-khUNBhfsteo:bgla070) ([raw file](https://github.com/memkind/memkind/blob/34b1fbf52cd8323c100e5027a3aa9886b6000518/doc/memkind_pmem.3.md#L61)):*
> ```Markdown
> `memkind_pmem_validate_dir()` returns zero if file created in specified *pmem_dir* supports DAX (direct mapping of persistent memory) or an error code from the **ERRORS** if not.
> 
> MEMKIND_PMEM_CHUNK_SIZE
> ```

. bold
___
*[`doc/memtier.1.md` line 40 at r17](https://reviewable.io/reviews/memkind/memkind/839#-N95pMLn8M9vVfwwElp7:-N95pMLn8M9vVfwwElp8:bw4n5ik) ([raw file](https://github.com/memkind/memkind/blob/34b1fbf52cd8323c100e5027a3aa9886b6000518/doc/memtier.1.md#L40)):*
> ```Markdown
> # DESCRIPTION #
> 
> memtier
> ```

Missing backticks, also in other places.
___
*[`doc/memtier.1.md` line 50 at r17](https://reviewable.io/reviews/memkind/memkind/839#-N95q7yGAo1YVZBCMQnZ:-N95q7yGAo1YVZBCMQn_:b-mex2we) ([raw file](https://github.com/memkind/memkind/blob/34b1fbf52cd8323c100e5027a3aa9886b6000518/doc/memtier.1.md#L50)):*
> ```Markdown
>     If the ratio is not given, it defaults to the relative share of physically installed memory.
> 
>     This version of memtier recognizes only two tiers (DRAM and KMEM_DAX).
> ```

This should be formatted as a normal text. Perhaps even without the empty line in between.



_Code quote:_
```Markdown
    If the ratio is not given, it defaults to the relative share of physically installed memory.

    This version of memtier recognizes only two tiers (DRAM and KMEM_DAX).
```
___
*[`man/libmemtier.7` line 32 at r17](https://reviewable.io/reviews/memkind/memkind/839#-N95sQeZ2sttTFW9jqtq:-N95sQeZ2sttTFW9jqtr:bx7fgtg) ([raw file](https://github.com/memkind/memkind/blob/34b1fbf52cd8323c100e5027a3aa9886b6000518/man/libmemtier.7#L32)):*
> ```Roff
> Both \f[B]LD_PRELOAD\f[R] and \f[B]MEMKIND_MEM_TIERS\f[R] environment
> variables are mandatory for enabling the memkind memory tiering.
> .SS ENVIRONMENT
> ```

Not formatted as a section (.SH formatting). Please, verify that sections in all man pages are correctly formatted.


<!-- Sent from Reviewable.io -->

2022-08-10 09:59 UTC, maciekpac reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/839)* status: 52 of 53 files reviewed, 17 unresolved discussions (waiting on @bratpiorka, @lukaszstolarczuk, @maciekpac, @PatKamin, and @szadam)



<!-- Sent from Reviewable.io -->

2022-08-11 06:58 UTC, bratpiorka requested changes
@szadam - if you change md files in this review, please update files in memkind webpage also

> Reviewed 2 of 7 files at r10, 1 of 14 files at r14, 14 of 43 files at r15, 1 of 2 files at r17, 1 of 24 files at r18, 5 of 25 files at r19, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/839#-:-N9AgWKt8uZXTbRMx3Fh:b-jn1z8r)* status: 33 of 53 files reviewed, 20 unresolved discussions (waiting on @lukaszstolarczuk, @maciekpac, @PatKamin, and @szadam)

___
*[`.github/workflows/gha.yml` line 161 at r19](https://reviewable.io/reviews/memkind/memkind/839#-N9AeiUe8IvkGkx-VR6_:-N9AeiUe8IvkGkx-VR6a:ble9na8) ([raw file](https://github.com/memkind/memkind/blob/f35c2e6a7ed73a772f020adea1fe3dfb6fb0deb1/.github/workflows/gha.yml#L161)):*
> ```YAML
>         make man-local
>         if [[ $(git diff man/) ]]; then
>           echo "man and md file are not synced"
> ```

file*s*
___
*[`doc/autohbw.7.md` line 52 at r19](https://reviewable.io/reviews/memkind/memkind/839#-N9AesTP5rhUquuIDWKE:-N9AesTP5rhUquuIDWKF:b-r0q3x8) ([raw file](https://github.com/memkind/memkind/blob/f35c2e6a7ed73a772f020adea1fe3dfb6fb0deb1/doc/autohbw.7.md#L52)):*
> ```Markdown
> 
> `AUTO_HBW_SIZE=x:[y]`
> :   Indicates that any allocation larger than x and smaller than y should be allocated in HBW memory.  x and y can be followed by a K, M, or G to indicate the size in Kilo/Memga/Giga bytes (e.g., 4K, 3M, 2G).
> ```

double whitespace- there are many occurrences of this - could you find & replace them with single whitespace?



_Code quote:_
```Markdown
.  x
```
___
*[`doc/memtier.7.md` line 30 at r19](https://reviewable.io/reviews/memkind/memkind/839#-N9AgOisDei4GeYITsRT:-N9AgOisDei4GeYITsRU:b-7ev9qo) ([raw file](https://github.com/memkind/memkind/blob/f35c2e6a7ed73a772f020adea1fe3dfb6fb0deb1/doc/memtier.7.md#L30)):*
> ```Markdown
> # NAME #
> 
> .so libmemtier.7
> ```

add newline
___
*[`utils/md2man/md2man.sh` line 34 at r19](https://reviewable.io/reviews/memkind/memkind/839#-N9Ag5Pp86zhvOuiXmxI:-N9Ag5Pp86zhvOuiXmxJ:b-iljhlp) ([raw file](https://github.com/memkind/memkind/blob/f35c2e6a7ed73a772f020adea1fe3dfb6fb0deb1/utils/md2man/md2man.sh#L34)):*
> ```Shell
> mkdir -p $(dirname $outfile)
> 
> #Check if the pandoc is present in the system
> ```

please format this comment the same way as others in this file


<!-- Sent from Reviewable.io -->

2022-08-11 07:34 UTC, lukaszstolarczuk reviewed
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/839)* status: 33 of 53 files reviewed, 25 unresolved discussions (waiting on @maciekpac, @PatKamin, and @szadam)

___
*[`-- commits` line 9 at r19](https://reviewable.io/reviews/memkind/memkind/839#-N9AjpTD7CAXHRHqHyPC):*
if you don't want the version variable, just don't add in the first commit - adding something in one commit and removing it in another one (within the same PR) makes no sense, IMHO :smile: 
___
*[`.github/workflows/gha.yml` line 161 at r19](https://reviewable.io/reviews/memkind/memkind/839#-N9Al3Eo5X_Mp7Ja93Jg:-N9Al3Eo5X_Mp7Ja93Jh:bmf0on5) ([raw file](https://github.com/memkind/memkind/blob/f35c2e6a7ed73a772f020adea1fe3dfb6fb0deb1/.github/workflows/gha.yml#L161)):*
> ```YAML
>         make man-local
>         if [[ $(git diff man/) ]]; then
>           echo "man and md file are not synced"
> ```

I'm not sure if I understand correctly, but are you guys planning on keeping generated 'man' files within the repo? May I know what is the reason for that?
It seems to me like a bad idea, i.a., because of that extra CI job you need now :stuck_out_tongue_winking_eye: 
___
*[`doc/autohbw.7.md` line 42 at r19](https://reviewable.io/reviews/memkind/memkind/839#-N9Ao5zBBRtqCjEbKHKQ:-N9Ao5zBBRtqCjEbKHKR:b-h5yybf) ([raw file](https://github.com/memkind/memkind/blob/f35c2e6a7ed73a772f020adea1fe3dfb6fb0deb1/doc/autohbw.7.md#L42)):*
> ```Markdown
> 
> **AutoHBW**  library  (`libautohbw.so`)
> :   is an interposer library for redirecting heap allocations (malloc, calloc, realloc, valloc, posix_memalign, memlign) to high-bandwidth (**HBW**) memory. Consequently, **AutoHBW** library can be used to automatically allocate high-bandwidth memory without any modification to source code of an application.
> ```

long lines are still not broken down (in all md files)
___
*[`doc/memtier.1.md` line 15 at r19](https://reviewable.io/reviews/memkind/memkind/839#-N9AnhVQD27RnZOdd3f7:-N9AnhVQD27RnZOdd3f8:bqwjfke) ([raw file](https://github.com/memkind/memkind/blob/f35c2e6a7ed73a772f020adea1fe3dfb6fb0deb1/doc/memtier.1.md#L15)):*
> ```Markdown
> [comment]: <> (Copyright 2022, Intel Corporation)
> 
> [comment]: <> (memtier.1 -- man page for memkimemtiernd_pmem)
> ```

for what? :wink: 
___
*[`doc/memtier.7.md` line 1 at r19](https://reviewable.io/reviews/memkind/memkind/839#-N9AmIgBB4MqMRqzkEwV:-N9AmIgBB4MqMRqzkEwW:behyfy4) ([raw file](https://github.com/memkind/memkind/blob/f35c2e6a7ed73a772f020adea1fe3dfb6fb0deb1/doc/memtier.7.md#L1)):*
> ```Markdown
> ---
> ```

is this md file properly generated on the web page?
___
*[`doc/memtier.7.md` line 9 at r19](https://reviewable.io/reviews/memkind/memkind/839#-N9AmGag8T-yKhfrnZ6l:-N9AmGag8T-yKhfrnZ6m:b-7urw24) ([raw file](https://github.com/memkind/memkind/blob/f35c2e6a7ed73a772f020adea1fe3dfb6fb0deb1/doc/memtier.7.md#L9)):*
> ```Markdown
> aliases: ["memtier.7.html"]
> title: MEMTIER
> section: 7q
> ```

`7q`?


<!-- Sent from Reviewable.io -->

2022-08-11 07:39 UTC, bratpiorka commented
*[`.github/workflows/gha.yml` line 161 at r19](https://reviewable.io/reviews/memkind/memkind/839#-N9Al3Eo5X_Mp7Ja93Jg:-N9ApYAP8_B7KKLnSGk4:b-bqy7u1) ([raw file](https://github.com/memkind/memkind/blob/f35c2e6a7ed73a772f020adea1fe3dfb6fb0deb1/.github/workflows/gha.yml#L161)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

I'm not sure if I understand correctly, but are you guys planning on keeping generated 'man' files within the repo? May I know what is the reason for that?
It seems to me like a bad idea, i.a., because of that extra CI job you need now :stuck_out_tongue_winking_eye: 
</blockquote></details>

We want to allow user to run make && make install with access to man files without installing extra dependencies like pandoc


<!-- Sent from Reviewable.io -->

2022-08-11 07:57 UTC, szadam reviewed
okey, I will make it after closing this PR.

> Reviewed 19 of 25 files at r19.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/839#-:-N9AsEHx54tMXK1Ggswb:b-xpaija)* status: 52 of 53 files reviewed, 24 unresolved discussions (waiting on @maciekpac, @PatKamin, and @szadam)

___
*[`.github/workflows/gha.yml` line 118 at r2](https://reviewable.io/reviews/memkind/memkind/839#-N7_GZbnGIXU9D4r5eOn-r2-118:-N9Atrv40FMDoNO45G8C:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/0b0d7c3cc76922bbea816db986e80159337df91f/.github/workflows/gha.yml#L118)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

pandoc is not needed here in "building job". Instead of this please create a separate job that will run man-local Makefile target and check if man files that are included into the repository are up-to-date
</blockquote></details>

Done.
___
*[`doc/memkind.3.md` line 259 at r17](https://reviewable.io/reviews/memkind/memkind/839#-N95mtU87R4F_UrtYoKG:-N9AtmQg9fnC0A7fDqWv:b-a95xh1) ([raw file](https://github.com/memkind/memkind/blob/34b1fbf52cd8323c100e5027a3aa9886b6000518/doc/memkind.3.md#L259)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

All kind names in bold. Same for all other constants. See the current formatting of man pages.
</blockquote></details>

line before ":" is bold
___
*[`doc/memkind_arena.3.md` line 124 at r17](https://reviewable.io/reviews/memkind/memkind/839#-N95nKfL8CHhwIzVR3Vc:-N9AsiEmCNtDcf4N-oPH:b-a95xh1) ([raw file](https://github.com/memkind/memkind/blob/34b1fbf52cd8323c100e5027a3aa9886b6000518/doc/memkind_arena.3.md#L124)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

All options in bold.
</blockquote></details>

line before ":" is bold
___
*[`doc/memkind_pmem.3.md` line 61 at r17](https://reviewable.io/reviews/memkind/memkind/839#-N95nyFn-khUNBhfsten:-N9AstUY8zOPPiKsx3Fp:b-a95xh1) ([raw file](https://github.com/memkind/memkind/blob/34b1fbf52cd8323c100e5027a3aa9886b6000518/doc/memkind_pmem.3.md#L61)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

. bold
</blockquote></details>

line before ":" is bold


<!-- Sent from Reviewable.io -->

2022-08-11 08:20 UTC, PatKamin reviewed
> Reviewed 2 of 7 files at r10, 1 of 25 files at r19.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/839)* status: 52 of 53 files reviewed, 18 unresolved discussions (waiting on @maciekpac and @szadam)

___
*[`doc/memkind.3.md` line 259 at r17](https://reviewable.io/reviews/memkind/memkind/839#-N95mtU87R4F_UrtYoKG:-N9AxxeH66Y4S0Ij4dSP:bhksqac) ([raw file](https://github.com/memkind/memkind/blob/34b1fbf52cd8323c100e5027a3aa9886b6000518/doc/memkind.3.md#L259)):*
<details><summary><i>Previously, szadam (Adam Szopiński) wrote…</i></summary><blockquote>

line before ":" is bold
</blockquote></details>

OK. I see that on the webpage it's in bold. It's not bold when viewing this file on repo's github page. It can stay this way, I suppose.


<!-- Sent from Reviewable.io -->

2022-08-11 09:23 UTC, PatKamin requested changes
> Reviewed 1 of 24 files at r18, 2 of 25 files at r19.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/839)* status: 31 of 53 files reviewed, 21 unresolved discussions (waiting on @bratpiorka, @maciekpac, @PatKamin, and @szadam)

___
*[`.github/workflows/gha.yml` line 149 at r20](https://reviewable.io/reviews/memkind/memkind/839#-N9B3B02EDnrSvXtxWaU:-N9B3B02EDnrSvXtxWaV:b-mh6x1t) ([raw file](https://github.com/memkind/memkind/blob/69a54751827b64815a62ec5665d2be8c4e12fad8/.github/workflows/gha.yml#L149)):*
> ```YAML
>     - name: Install basic dependencies
>       run: sudo apt install pandoc autoconf clang-format-11 libnuma-dev
>     
> ```

Remove whitespaces.
___
*[`.github/workflows/gha.yml` line 154 at r20](https://reviewable.io/reviews/memkind/memkind/839#-N9B3D1G73FSduQDDa5g:-N9B3D1G73FSduQDDa5h:b3kqx) ([raw file](https://github.com/memkind/memkind/blob/69a54751827b64815a62ec5665d2be8c4e12fad8/.github/workflows/gha.yml#L154)):*
> ```YAML
>       with:
>         fetch-depth: 0
>     
> ```

.
___
*[`man/autohbw.7` line 6 at r20](https://reviewable.io/reviews/memkind/memkind/839#-N9BCPSj3HWX25K-bQnk:-N9BCPSj3HWX25K-bQnl:b-568joj) ([raw file](https://github.com/memkind/memkind/blob/69a54751827b64815a62ec5665d2be8c4e12fad8/man/autohbw.7#L6)):*
> ```Roff
> .hy
> .\" SPDX-License-Identifier: BSD-2-Clause
> .\" Copyright 2022, Intel Corporation
> ```

I think that original dates should be preserved in all man pages. They just change their form, they are not created by scratch.


<!-- Sent from Reviewable.io -->

2022-08-11 09:53 UTC, szadam reviewed
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/839)* status: 31 of 53 files reviewed, 21 unresolved discussions (waiting on @bratpiorka, @maciekpac, @PatKamin, and @szadam)

___
*[`man/libmemtier.7` line 32 at r17](https://reviewable.io/reviews/memkind/memkind/839#-N95sQeZ2sttTFW9jqtq:-N9BIaTvCF2epqXgP1JI:bn7rxfd) ([raw file](https://github.com/memkind/memkind/blob/34b1fbf52cd8323c100e5027a3aa9886b6000518/man/libmemtier.7#L32)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Not formatted as a section (.SH formatting). Please, verify that sections in all man pages are correctly formatted.
</blockquote></details>

It is formatted as a subsection. It depends on how many "#" the header has


<!-- Sent from Reviewable.io -->

2022-08-11 10:27 UTC, szadam reviewed
> Reviewed 17 of 22 files at r21, 15 of 15 files at r22, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/839)* status: all files reviewed, 21 unresolved discussions (waiting on @bratpiorka, @lukaszstolarczuk, @maciekpac, @PatKamin, and @szadam)

___
*[`-- commits` line 5 at r17](https://reviewable.io/reviews/memkind/memkind/839#-N95gIkc2Jjut5qgOapX):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Begin commit messages with a capital letter.
</blockquote></details>

Done.
___
*[`-- commits` line 9 at r19](https://reviewable.io/reviews/memkind/memkind/839#-N9AjpTD7CAXHRHqHyPC):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

if you don't want the version variable, just don't add in the first commit - adding something in one commit and removing it in another one (within the same PR) makes no sense, IMHO :smile: 
</blockquote></details>

Done.
___
*[`doc/autohbw.7.md` line 52 at r17](https://reviewable.io/reviews/memkind/memkind/839#-N95kx-qEIrpmwWft-VP:-N9BQntR1emlkuTYrHqV:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/34b1fbf52cd8323c100e5027a3aa9886b6000518/doc/autohbw.7.md#L52)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Parameters `x`and `y` in text in italics, please. This way it will be much easier to spot them.
</blockquote></details>

Done.
___
*[`doc/autohbw.7.md` line 63 at r17](https://reviewable.io/reviews/memkind/memkind/839#-N95lbAS9GMmoS7elH7c:-N9BQpX_EiZbz55gTkMc:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/34b1fbf52cd8323c100e5027a3aa9886b6000518/doc/autohbw.7.md#L63)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

`level` in italics
</blockquote></details>

Done.
___
*[`doc/autohbw.7.md` line 66 at r17](https://reviewable.io/reviews/memkind/memkind/839#-N95liIs8nSBAOJ5vvU6:-N9BQq181_9IbmG-VctI:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/34b1fbf52cd8323c100e5027a3aa9886b6000518/doc/autohbw.7.md#L66)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

are printed
</blockquote></details>

Done.
___
*[`doc/autohbw.7.md` line 42 at r19](https://reviewable.io/reviews/memkind/memkind/839#-N9Ao5zBBRtqCjEbKHKQ:-N9BQmaj8dxtS2XPkqnB:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/f35c2e6a7ed73a772f020adea1fe3dfb6fb0deb1/doc/autohbw.7.md#L42)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

long lines are still not broken down (in all md files)
</blockquote></details>

Done.
___
*[`doc/autohbw.7.md` line 52 at r19](https://reviewable.io/reviews/memkind/memkind/839#-N9AesTP5rhUquuIDWKE:-N9BQp-n1Iw_eWsjpR8S:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/f35c2e6a7ed73a772f020adea1fe3dfb6fb0deb1/doc/autohbw.7.md#L52)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

double whitespace- there are many occurrences of this - could you find & replace them with single whitespace?
</blockquote></details>

Done.
___
*[`doc/memtier.1.md` line 40 at r17](https://reviewable.io/reviews/memkind/memkind/839#-N95pMLn8M9vVfwwElp7:-N9BQwN871LSt8iiwhAm:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/34b1fbf52cd8323c100e5027a3aa9886b6000518/doc/memtier.1.md#L40)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Missing backticks, also in other places.
</blockquote></details>

Done.
___
*[`doc/memtier.1.md` line 50 at r17](https://reviewable.io/reviews/memkind/memkind/839#-N95q7yGAo1YVZBCMQnZ:-N9BQxUz3JzLuH4ISoAJ:b-x9bg4s) ([raw file](https://github.com/memkind/memkind/blob/34b1fbf52cd8323c100e5027a3aa9886b6000518/doc/memtier.1.md#L50)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

This should be formatted as a normal text. Perhaps even without the empty line in between.
</blockquote></details>

Like that?
___
*[`doc/memtier.1.md` line 15 at r19](https://reviewable.io/reviews/memkind/memkind/839#-N9AnhVQD27RnZOdd3f7:-N9BQtbcD2an1ZuApalx:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/f35c2e6a7ed73a772f020adea1fe3dfb6fb0deb1/doc/memtier.1.md#L15)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

for what? :wink: 
</blockquote></details>

Done.
___
*[`doc/memtier.7.md` line 1 at r19](https://reviewable.io/reviews/memkind/memkind/839#-N9AmIgBB4MqMRqzkEwV:-N9BR0Vq7v0BPMigr3AG:b-cu5w1j) ([raw file](https://github.com/memkind/memkind/blob/f35c2e6a7ed73a772f020adea1fe3dfb6fb0deb1/doc/memtier.7.md#L1)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

is this md file properly generated on the web page?
</blockquote></details>

I will change it
___
*[`doc/memtier.7.md` line 9 at r19](https://reviewable.io/reviews/memkind/memkind/839#-N9AmGag8T-yKhfrnZ6l:-N9BR-zsA7HAYh-8bs11:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/f35c2e6a7ed73a772f020adea1fe3dfb6fb0deb1/doc/memtier.7.md#L9)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`7q`?
</blockquote></details>

Done.
___
*[`doc/memtier.7.md` line 30 at r19](https://reviewable.io/reviews/memkind/memkind/839#-N9AgOisDei4GeYITsRT:-N9BR4Hu4y3GMBnvWeiw:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/f35c2e6a7ed73a772f020adea1fe3dfb6fb0deb1/doc/memtier.7.md#L30)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

add newline
</blockquote></details>

Done.
___
*[`utils/md2man/md2man.sh` line 34 at r19](https://reviewable.io/reviews/memkind/memkind/839#-N9Ag5Pp86zhvOuiXmxI:-N9BRK-WDPbmZx0tJOr8:b-cnvbez) ([raw file](https://github.com/memkind/memkind/blob/f35c2e6a7ed73a772f020adea1fe3dfb6fb0deb1/utils/md2man/md2man.sh#L34)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

please format this comment the same way as others in this file
</blockquote></details>

Is it okey now?


<!-- Sent from Reviewable.io -->

2022-08-11 10:46 UTC, szadam reviewed
> Reviewed 1 of 1 files at r23, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/839)* status: all files reviewed, 21 unresolved discussions (waiting on @bratpiorka, @lukaszstolarczuk, @maciekpac, @PatKamin, and @szadam)

___
*[`.github/workflows/gha.yml` line 161 at r19](https://reviewable.io/reviews/memkind/memkind/839#-N9AeiUe8IvkGkx-VR6_:-N9BVjR08n0t2HJB1h6g:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/f35c2e6a7ed73a772f020adea1fe3dfb6fb0deb1/.github/workflows/gha.yml#L161)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

file*s*
</blockquote></details>

Done.
___
*[`.github/workflows/gha.yml` line 149 at r20](https://reviewable.io/reviews/memkind/memkind/839#-N9B3B02EDnrSvXtxWaU:-N9BVio-4Zo4YIqe5XWU:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/69a54751827b64815a62ec5665d2be8c4e12fad8/.github/workflows/gha.yml#L149)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Remove whitespaces.
</blockquote></details>

Done.
___
*[`.github/workflows/gha.yml` line 154 at r20](https://reviewable.io/reviews/memkind/memkind/839#-N9B3D1G73FSduQDDa5g:-N9BVjB7-ecsznb17Vuo:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/69a54751827b64815a62ec5665d2be8c4e12fad8/.github/workflows/gha.yml#L154)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-08-11 10:54 UTC, szadam reviewed
> Reviewed 1 of 1 files at r24, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/839)* status: all files reviewed, 21 unresolved discussions (waiting on @bratpiorka, @lukaszstolarczuk, @maciekpac, @PatKamin, and @szadam)

___
*[`README` line 92 at r17](https://reviewable.io/reviews/memkind/memkind/839#-N95j3Be2Q7UDDObg5Sw:-N9BXXy81R5FpQO5bs01:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/34b1fbf52cd8323c100e5027a3aa9886b6000518/README#L92)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Add an information on how to generate this documentation.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-08-11 13:19 UTC, bratpiorka reviewed
> Reviewed 1 of 22 files at r21, 2 of 15 files at r22, 1 of 1 files at r23, 1 of 1 files at r24.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/839)* status: all files reviewed, 17 unresolved discussions (waiting on @lukaszstolarczuk, @maciekpac, @PatKamin, and @szadam)



<!-- Sent from Reviewable.io -->

2022-08-11 13:49 UTC, szadam reviewed
> Reviewed 2 of 2 files at r25, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/839)* status: all files reviewed, 17 unresolved discussions (waiting on @lukaszstolarczuk, @maciekpac, @PatKamin, and @szadam)



<!-- Sent from Reviewable.io -->

2022-08-11 13:49 UTC, szadam reviewed
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/839)* status: all files reviewed, 17 unresolved discussions (waiting on @lukaszstolarczuk, @maciekpac, and @PatKamin)

___
*[`man/autohbw.7` line 6 at r20](https://reviewable.io/reviews/memkind/memkind/839#-N9BCPSj3HWX25K-bQnk:-N9C9hqZ0hj2ffgAGdgs:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/69a54751827b64815a62ec5665d2be8c4e12fad8/man/autohbw.7#L6)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

I think that original dates should be preserved in all man pages. They just change their form, they are not created by scratch.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-08-12 09:43 UTC, bratpiorka requested changes
> Reviewed 5 of 15 files at r22, 1 of 2 files at r25, 1 of 21 files at r26, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/839)* status: 33 of 53 files reviewed, 18 unresolved discussions (waiting on @lukaszstolarczuk, @maciekpac, @PatKamin, and @szadam)

___
*[`utils/md2man/md2man.sh` line 46 at r26](https://reviewable.io/reviews/memkind/memkind/839#-N9GQnVw1bf-X3rFQq8o:-N9GQnVw1bf-X3rFQq8p:brhq1gi) ([raw file](https://github.com/memkind/memkind/blob/5152a4e40f8671adce97cb4c1860f9a199cc06d2/utils/md2man/md2man.sh#L46)):*
> ```Shell
> 	-V title=$title -V section=$section \
> 	-V date="$dt" -V copyright=$copyright \
> 	-V year="$year" -V secondary_title="$secondary_title" |
> ```

you could remove "year" arg if it is not used in the template


<!-- Sent from Reviewable.io -->

2022-08-16 06:28 UTC, PatKamin requested changes
> Reviewed 1 of 25 files at r19, 10 of 15 files at r22, 1 of 1 files at r23, 1 of 1 files at r24, 2 of 2 files at r25, 21 of 21 files at r26, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/839)* status: all files reviewed, 9 unresolved discussions (waiting on @lukaszstolarczuk, @maciekpac, and @szadam)

___
*[`README` line 94 at r26](https://reviewable.io/reviews/memkind/memkind/839#-N9_Guk31Ah0AbxTyLSq:-N9_Guk31Ah0AbxTyLSr:b-x6hqqh) ([raw file](https://github.com/memkind/memkind/blob/5152a4e40f8671adce97cb4c1860f9a199cc06d2/README#L94)):*
> ```
> You will need to install **pandoc** for generating man documentation.
> 
> `make man-local` will generate man files.
> ```

in the man/ directory.
___
*[`man/libmemtier.7` line 32 at r17](https://reviewable.io/reviews/memkind/memkind/839#-N95sQeZ2sttTFW9jqtq:-N9_IjIR85SzTUoj82m9:b-maqo9o) ([raw file](https://github.com/memkind/memkind/blob/34b1fbf52cd8323c100e5027a3aa9886b6000518/man/libmemtier.7#L32)):*
<details><summary><i>Previously, szadam (Adam Szopiński) wrote…</i></summary><blockquote>

It is formatted as a subsection. It depends on how many "#" the header has
</blockquote></details>

Should be sections - see the original man page. Check also other man pages for original formatting of sections/subsections.
___
*[`man/memkind_hugetlb.3` line 6 at r26](https://reviewable.io/reviews/memkind/memkind/839#-N9_JnRgB8fYxvH2tsLj:-N9_JnRgB8fYxvH2tsLk:b-kcgnwb) ([raw file](https://github.com/memkind/memkind/blob/5152a4e40f8671adce97cb4c1860f9a199cc06d2/man/memkind_hugetlb.3#L6)):*
> ```Roff
> .hy
> .\" SPDX-License-Identifier: BSD-2-Clause
> .\" Copyright "2021-2022", Intel Corporation
> ```

2014-2022


<!-- Sent from Reviewable.io -->

2022-08-16 13:42 UTC, bratpiorka requested changes
> Reviewed 1 of 2 files at r25.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/839)* status: all files reviewed, 10 unresolved discussions (waiting on @lukaszstolarczuk, @maciekpac, and @szadam)

___
*[`man/memkind_pmem.3` line 6 at r26](https://reviewable.io/reviews/memkind/memkind/839#-N9assXt6kUVKjYDMnJN:-N9assXu1auPKhudbIdr:b-kcgnwb) ([raw file](https://github.com/memkind/memkind/blob/5152a4e40f8671adce97cb4c1860f9a199cc06d2/man/memkind_pmem.3#L6)):*
> ```Roff
> .hy
> .\" SPDX-License-Identifier: BSD-2-Clause
> .\" Copyright "2015-2022", Intel Corporation
> ```

2014-2022


<!-- Sent from Reviewable.io -->

2022-08-17 10:09 UTC, szadam reviewed
> Reviewed 5 of 21 files at r26, 41 of 42 files at r27, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/839)* status: 52 of 53 files reviewed, 10 unresolved discussions (waiting on @bratpiorka, @lukaszstolarczuk, @maciekpac, @PatKamin, and @szadam)

___
*[`README` line 94 at r26](https://reviewable.io/reviews/memkind/memkind/839#-N9_Guk31Ah0AbxTyLSq:-N9fGKVM6kmchUeFZkBX:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/5152a4e40f8671adce97cb4c1860f9a199cc06d2/README#L94)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

in the man/ directory.
</blockquote></details>

Done.
___
*[`man/memkind_hugetlb.3` line 6 at r26](https://reviewable.io/reviews/memkind/memkind/839#-N9_JnRgB8fYxvH2tsLj:-N9fGgeL8rCNh43ZCW1d:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/5152a4e40f8671adce97cb4c1860f9a199cc06d2/man/memkind_hugetlb.3#L6)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

2014-2022
</blockquote></details>

Done.
___
*[`man/memkind_pmem.3` line 6 at r26](https://reviewable.io/reviews/memkind/memkind/839#-N9assXt6kUVKjYDMnJN:-N9fGhsoC8PAZPmq5Zh6:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/5152a4e40f8671adce97cb4c1860f9a199cc06d2/man/memkind_pmem.3#L6)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

2014-2022
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-08-17 10:25 UTC, PatKamin reviewed
> Reviewed 4 of 42 files at r27, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/839)* status: 52 of 53 files reviewed, 8 unresolved discussions (waiting on @bratpiorka, @lukaszstolarczuk, @maciekpac, @PatKamin, and @szadam)



<!-- Sent from Reviewable.io -->

2022-08-17 10:26 UTC, PatKamin approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/839#-:-N9fKdrX8enyrOrgeVkP:bnfp4nl)* status: 52 of 53 files reviewed, 8 unresolved discussions (waiting on @bratpiorka, @lukaszstolarczuk, @maciekpac, @PatKamin, and @szadam)



<!-- Sent from Reviewable.io -->

2022-08-17 11:58 UTC, szadam commented
*[`doc/autohbw.7.md` line 42 at r19](https://reviewable.io/reviews/memkind/memkind/839#-N9Ao5zBBRtqCjEbKHKQ:-N9femoi1SLBi8Taogsp:b4450x7) ([raw file](https://github.com/memkind/memkind/blob/f35c2e6a7ed73a772f020adea1fe3dfb6fb0deb1/doc/autohbw.7.md#L42)):*
<details><summary><i>Previously, szadam (Adam Szopiński) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I have hope that now is okey


<!-- Sent from Reviewable.io -->

2022-08-17 12:01 UTC, szadam reviewed
> Reviewed 42 of 42 files at r28, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/839)* status: all files reviewed, 8 unresolved discussions (waiting on @bratpiorka, @lukaszstolarczuk, and @maciekpac)

___
*[`man/libmemtier.7` line 32 at r17](https://reviewable.io/reviews/memkind/memkind/839#-N95sQeZ2sttTFW9jqtq:-N9ff5-O59pd6uTdJSKh:bt4pf81) ([raw file](https://github.com/memkind/memkind/blob/34b1fbf52cd8323c100e5027a3aa9886b6000518/man/libmemtier.7#L32)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Should be sections - see the original man page. Check also other man pages for original formatting of sections/subsections.
</blockquote></details>

I have corrected this
___
*[`utils/md2man/md2man.sh` line 46 at r26](https://reviewable.io/reviews/memkind/memkind/839#-N9GQnVw1bf-X3rFQq8o:-N9ffHNJCYu-U7xTEE5l:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/5152a4e40f8671adce97cb4c1860f9a199cc06d2/utils/md2man/md2man.sh#L46)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

you could remove "year" arg if it is not used in the template
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-08-17 12:04 UTC, PatKamin reviewed
> Reviewed 1 of 42 files at r28.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/839)* status: all files reviewed, 8 unresolved discussions (waiting on @bratpiorka, @lukaszstolarczuk, and @maciekpac)



<!-- Sent from Reviewable.io -->

2022-08-17 12:07 UTC, bratpiorka approved these changes
> Reviewed 3 of 42 files at r27, 42 of 42 files at r28, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/839)* status: all files reviewed, 6 unresolved discussions (waiting on @lukaszstolarczuk and @maciekpac)



<!-- Sent from Reviewable.io -->

2022-08-17 12:46 UTC, szadam reviewed
> Reviewed 9 of 9 files at r29, 2 of 2 files at r30, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/839)* status: all files reviewed, 6 unresolved discussions (waiting on @lukaszstolarczuk and @maciekpac)



<!-- Sent from Reviewable.io -->

2022-08-17 12:48 UTC, bratpiorka approved these changes
> Reviewed 8 of 9 files at r29, 2 of 2 files at r30, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/839)* status: all files reviewed, 6 unresolved discussions (waiting on @lukaszstolarczuk and @maciekpac)



<!-- Sent from Reviewable.io -->

2022-08-18 11:19 UTC, maciekpac reviewed
There are some cases of bad formatting under reviewable; I have commented them. I suppose this is a problem with reviewable, not with the scripts - can you check it ?

> Reviewed 3 of 8 files at r9, 2 of 7 files at r10, 1 of 2 files at r11, 1 of 1 files at r23, 1 of 2 files at r25, 3 of 42 files at r27, 33 of 42 files at r28, 7 of 9 files at r29, 2 of 2 files at r30, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/839#-:-N9kf7scEuwuy242oUjc:b-bm2uu3)* status: all files reviewed, 10 unresolved discussions (waiting on @lukaszstolarczuk and @szadam)

___
*[`doc/hbwmalloc.3.md` line 52 at r30](https://reviewable.io/reviews/memkind/memkind/839#-N9kcyybDznfzG6qbQgC:-N9kcyybDznfzG6qbQgD:b-6ev4g2) ([raw file](https://github.com/memkind/memkind/blob/c5697440459d82ff76189457ddcd8c63aa69736b/doc/hbwmalloc.3.md#L52)):*
> ```Markdown
> void hbw_free(void *ptr);
> size_t hbw_malloc_usable_size(void *ptr);
> int hbw_posix_memalign(void **memptr, size_t alignment, size_t size);
> ```

I think this line messed up formatting in reviewable; it it possible to escape the "**" in a code block, or it it a bug in reviewable ? I'm not sure if reviewable detected the code block, this might be another reason for bad formatting....
___
*[`doc/libmemtier.3.md` line 60 at r30](https://reviewable.io/reviews/memkind/memkind/839#-N9kdPA5AcI2tdW8bE_D:-N9kdPA5AcI2tdW8bE_E:b7ty2m7) ([raw file](https://github.com/memkind/memkind/blob/c5697440459d82ff76189457ddcd8c63aa69736b/doc/libmemtier.3.md#L60)):*
> ```Markdown
> void *memtier_realloc(struct memtier_memory *memory, void *ptr, size_t size);
> void *memtier_kind_realloc(memkind_t kind, void *ptr, size_t size);
> int memtier_posix_memalign(struct memtier_memory *memory, void **memptr, size_t alignment, size_t size);
> ```

same as before - incorrect formatting under reviewable
___
*[`doc/memkind_arena.3.md` line 41 at r30](https://reviewable.io/reviews/memkind/memkind/839#-N9kd_PF-Cikif8YhSOd:-N9kd_PF-Cikif8YhSOe:b-lnxgd9) ([raw file](https://github.com/memkind/memkind/blob/c5697440459d82ff76189457ddcd8c63aa69736b/doc/memkind_arena.3.md#L41)):*
> ```Markdown
> void *memkind_arena_malloc(struct memkind *kind, size_t size);
> void *memkind_arena_calloc(struct memkind *kind, size_t num, size_t size);
> int memkind_arena_posix_memalign(struct memkind *kind, void **memptr, size_t alignment, size_t size);
> ```

again, bad formatting under reviewable...
___
*[`doc/memkind_default.3.md` line 107 at r30](https://reviewable.io/reviews/memkind/memkind/839#-N9ke4vr13fDL08k676o:-N9ke4vr13fDL08k676p:bj9pi50) ([raw file](https://github.com/memkind/memkind/blob/c5697440459d82ff76189457ddcd8c63aa69736b/doc/memkind_default.3.md#L107)):*
> ```Markdown
> 
> `memkind_default_get_mbind_mode()`
> :   sets *mode* to **MPOL_BIND**. See **mbind**(2) for more information about this flag.
> ```

messed up formatting under reviewable



_Code quote:_
```Markdown
:   sets *mode* to **MPOL_BIND**. See **mbind**(2) for more information about this flag.

`memkind_default_malloc_usable_size()`
```
___
*[`doc/pmemallocator.3.md` line 59 at r30](https://reviewable.io/reviews/memkind/memkind/839#-N9keKed4KhP7UK7CTPo:-N9keKee9W1tCcjcmcO5:b8ec8wh) ([raw file](https://github.com/memkind/memkind/blob/c5697440459d82ff76189457ddcd8c63aa69736b/doc/pmemallocator.3.md#L59)):*
> ```Markdown
> :   is intended to be used with STL containers to allocate persistent memory.
>   Memory management is based on memkind_pmem (memkind library). Refer to
>   the **memkind_pmem**(3) and the [**memkind**](/memkind/manpages/memkind.3.html)(3)
> ```

bad formatting under reviewable; besides, is `**memkind**` link formatting consistent with others ? 


<!-- Sent from Reviewable.io -->

2022-08-18 11:43 UTC, lukaszstolarczuk reviewed
> Reviewed 1 of 1 files at r23, 1 of 42 files at r28, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/839)* status: all files reviewed, 9 unresolved discussions (waiting on @maciekpac and @szadam)

___
*[`Makefile.am` line 652 at r30](https://reviewable.io/reviews/memkind/memkind/839#-N9kh2QLEGaUurlEg48I:-N9kh2QLEGaUurlEg48J:by7npbk) ([raw file](https://github.com/memkind/memkind/blob/c5697440459d82ff76189457ddcd8c63aa69736b/Makefile.am#L652)):*
> ```Makefile
> 		utils/md2man/default.man \
> 		man/autohbw.7
> ```

couldn't all of these be done with a single list and a `foreach` function...? instead of calling the same script over and over :wink: 
___
*[`.github/workflows/gha.yml` line 160 at r30](https://reviewable.io/reviews/memkind/memkind/839#-N9khzr89jehdL-tiPYp:-N9khzr89jehdL-tiPYq:bvchuca) ([raw file](https://github.com/memkind/memkind/blob/c5697440459d82ff76189457ddcd8c63aa69736b/.github/workflows/gha.yml#L160)):*
> ```YAML
>         ./configure
>         make man-local
>         if [[ $(git diff man/) ]]; then
> ```

did you test this? I'm not sure if `git diff` return anything (by default) when there are differences
___
*[`doc/autohbw.7.md` line 42 at r19](https://reviewable.io/reviews/memkind/memkind/839#-N9Ao5zBBRtqCjEbKHKQ:-N9kiJ_E5jg0z-aoH_WC:b-nqmo3i) ([raw file](https://github.com/memkind/memkind/blob/f35c2e6a7ed73a772f020adea1fe3dfb6fb0deb1/doc/autohbw.7.md#L42)):*
<details><summary><i>Previously, szadam (Adam Szopiński) wrote…</i></summary><blockquote>

I have hope that now is okey
</blockquote></details>

If I'm being honest... this looks like it's too short now :smile: what limit did you put? I think there should be at least 80 chars (or more!)

pls discuss with your teammates if that's ok with you
___
*[`doc/hbwmalloc.3.md` line 52 at r30](https://reviewable.io/reviews/memkind/memkind/839#-N9kcyybDznfzG6qbQgC:-N9kjNCl3wU3qLOmGDKj:b-tgcb21) ([raw file](https://github.com/memkind/memkind/blob/c5697440459d82ff76189457ddcd8c63aa69736b/doc/hbwmalloc.3.md#L52)):*
<details><summary><i>Previously, maciekpac wrote…</i></summary><blockquote>

I think this line messed up formatting in reviewable; it it possible to escape the "**" in a code block, or it it a bug in reviewable ? I'm not sure if reviewable detected the code block, this might be another reason for bad formatting....
</blockquote></details>

I believe it's just an issue on reviewable, they try to do some parsing; a similar situation is after `_` sign - see the italics.

I wouldn't worry too much, the code looks ok

// for comparison, see GHA review board: https://github.com/memkind/memkind/pull/839/files#diff-f27deb80503d8a73c50aa954dc376b8b4098325a89d19df4cc6d6daa11731f40
___
*[`utils/md2man/md2man.sh` line 9 at r30](https://reviewable.io/reviews/memkind/memkind/839#-N9kk_LI-7lAG0b0fQbr:-N9kk_LI-7lAG0b0fQbs:basgkdc) ([raw file](https://github.com/memkind/memkind/blob/c5697440459d82ff76189457ddcd8c63aa69736b/utils/md2man/md2man.sh#L9)):*
> ```Shell
> #	It performs some pre- and post-processing for cleaner man page.
> #
> # usage: md2man.sh md_input_file man_template outfile API_version
> ```

you're not passing VERSION as 4th argument anymore
___
*[`utils/md2man/md2man.sh` line 45 at r30](https://reviewable.io/reviews/memkind/memkind/839#-N9kkejtA7Ni5nyhgDqs:-N9kkejtA7Ni5nyhgDqt:b-hhfw7z) ([raw file](https://github.com/memkind/memkind/blob/c5697440459d82ff76189457ddcd8c63aa69736b/utils/md2man/md2man.sh#L45)):*
> ```Shell
> 	-V title=$title -V section=$section \
> 	-V date="$dt" -V copyright=$copyright \
> 	-V secondary_title="$secondary_title" |
> ```

secondary_title is not used here, I believe


<!-- Sent from Reviewable.io -->

2022-08-18 12:46 UTC, szadam reviewed
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/839)* status: all files reviewed, 9 unresolved discussions (waiting on @lukaszstolarczuk, @maciekpac, and @szadam)

___
*[`.github/workflows/gha.yml` line 160 at r30](https://reviewable.io/reviews/memkind/memkind/839#-N9khzr89jehdL-tiPYp:-N9kuLRjDqNHnSn-jVei:b-yhdig9) ([raw file](https://github.com/memkind/memkind/blob/c5697440459d82ff76189457ddcd8c63aa69736b/.github/workflows/gha.yml#L160)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

did you test this? I'm not sure if `git diff` return anything (by default) when there are differences
</blockquote></details>

I tested it and it always return something when there are differences
___
*[`doc/autohbw.7.md` line 42 at r19](https://reviewable.io/reviews/memkind/memkind/839#-N9Ao5zBBRtqCjEbKHKQ:-N9kuXMPEWGaqWP9n04H:bmy21nx) ([raw file](https://github.com/memkind/memkind/blob/f35c2e6a7ed73a772f020adea1fe3dfb6fb0deb1/doc/autohbw.7.md#L42)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

If I'm being honest... this looks like it's too short now :smile: what limit did you put? I think there should be at least 80 chars (or more!)

pls discuss with your teammates if that's ok with you
</blockquote></details>

I make it to look good on laptop monitor
___
*[`doc/hbwmalloc.3.md` line 52 at r30](https://reviewable.io/reviews/memkind/memkind/839#-N9kcyybDznfzG6qbQgC:-N9kuyUw-HaK_STpXeP4:b286ni3) ([raw file](https://github.com/memkind/memkind/blob/c5697440459d82ff76189457ddcd8c63aa69736b/doc/hbwmalloc.3.md#L52)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

I believe it's just an issue on reviewable, they try to do some parsing; a similar situation is after `_` sign - see the italics.

I wouldn't worry too much, the code looks ok

// for comparison, see GHA review board: https://github.com/memkind/memkind/pull/839/files#diff-f27deb80503d8a73c50aa954dc376b8b4098325a89d19df4cc6d6daa11731f40
</blockquote></details>

I think the same as Lukasz.


<!-- Sent from Reviewable.io -->

2022-08-22 11:16 UTC, PatKamin requested changes
> Reviewed 2 of 42 files at r28, 3 of 27 files at r31, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/839)* status: 29 of 53 files reviewed, 11 unresolved discussions (waiting on @bratpiorka, @lukaszstolarczuk, @maciekpac, @PatKamin, and @szadam)

___
*[`Makefile.am` line 619 at r31](https://reviewable.io/reviews/memkind/memkind/839#-NA4Feir0CWi4bUEdG_Y:-NA4Feir0CWi4bUEdG_Z:bxr809h) ([raw file](https://github.com/memkind/memkind/blob/95cdb6ffc1b3e7dbf25a5ff822d40c4041369298/Makefile.am#L619)):*
> ```Makefile
>                  # end
> 
> dist_doc_DOC = autohbw.7 \
> ```

nit: DOCS
___
*[`Makefile.am` line 674 at r31](https://reviewable.io/reviews/memkind/memkind/839#-NA4Fjty8KPF7cqu3SOs:-NA4Fjty8KPF7cqu3SOt:bqk5vgq) ([raw file](https://github.com/memkind/memkind/blob/95cdb6ffc1b3e7dbf25a5ff822d40c4041369298/Makefile.am#L674)):*
> ```Makefile
> 			doc/$$doc_name.md \
> 			utils/md2man/default.man \
> 			man/$$doc_name ; \
> ```

Semi-colon probably not needed.


<!-- Sent from Reviewable.io -->

2022-08-22 11:27 UTC, szadam reviewed
> Reviewed 24 of 27 files at r31.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/839)* status: 52 of 53 files reviewed, 10 unresolved discussions (waiting on @lukaszstolarczuk, @maciekpac, @PatKamin, and @szadam)

___
*[`Makefile.am` line 674 at r31](https://reviewable.io/reviews/memkind/memkind/839#-NA4Fjty8KPF7cqu3SOs:-NA4IHqM8_OwL_GfnvbD:b-tue6mv) ([raw file](https://github.com/memkind/memkind/blob/95cdb6ffc1b3e7dbf25a5ff822d40c4041369298/Makefile.am#L674)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Semi-colon probably not needed.
</blockquote></details>

It is necessary
___
*[`doc/libmemtier.3.md` line 60 at r30](https://reviewable.io/reviews/memkind/memkind/839#-N9kdPA5AcI2tdW8bE_D:-N9kvOqy-e5qIro5U-jF:b-97gcr3) ([raw file](https://github.com/memkind/memkind/blob/c5697440459d82ff76189457ddcd8c63aa69736b/doc/libmemtier.3.md#L60)):*
<details><summary><i>Previously, maciekpac wrote…</i></summary><blockquote>

same as before - incorrect formatting under reviewable
</blockquote></details>

explained
___
*[`utils/md2man/md2man.sh` line 9 at r30](https://reviewable.io/reviews/memkind/memkind/839#-N9kk_LI-7lAG0b0fQbr:-NA4Gshc2WCbd8cvJHSj:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/c5697440459d82ff76189457ddcd8c63aa69736b/utils/md2man/md2man.sh#L9)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

you're not passing VERSION as 4th argument anymore
</blockquote></details>

Done.
___
*[`utils/md2man/md2man.sh` line 45 at r30](https://reviewable.io/reviews/memkind/memkind/839#-N9kkejtA7Ni5nyhgDqs:-NA4Gr9j2A8Sv8Cdwkmg:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/c5697440459d82ff76189457ddcd8c63aa69736b/utils/md2man/md2man.sh#L45)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

secondary_title is not used here, I believe
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-08-22 11:28 UTC, szadam reviewed
> Reviewed 1 of 1 files at r32, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/839)* status: all files reviewed, 9 unresolved discussions (waiting on @lukaszstolarczuk, @maciekpac, @PatKamin, and @szadam)

___
*[`doc/memkind_arena.3.md` line 41 at r30](https://reviewable.io/reviews/memkind/memkind/839#-N9kd_PF-Cikif8YhSOd:-NA4Ii9O22AK27R907Og:brxxhlb) ([raw file](https://github.com/memkind/memkind/blob/c5697440459d82ff76189457ddcd8c63aa69736b/doc/memkind_arena.3.md#L41)):*
> explained
___
*[`doc/memkind_default.3.md` line 107 at r30](https://reviewable.io/reviews/memkind/memkind/839#-N9ke4vr13fDL08k676o:-NA4IjqgBs72xu4Xa2Ni:b-97gcr3) ([raw file](https://github.com/memkind/memkind/blob/c5697440459d82ff76189457ddcd8c63aa69736b/doc/memkind_default.3.md#L107)):*
<details><summary><i>Previously, maciekpac wrote…</i></summary><blockquote>

messed up formatting under reviewable
</blockquote></details>

explained


<!-- Sent from Reviewable.io -->

2022-08-22 11:59 UTC, szadam reviewed
> Reviewed 1 of 1 files at r33, 3 of 3 files at r34, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/839)* status: all files reviewed, 9 unresolved discussions (waiting on @lukaszstolarczuk, @maciekpac, and @PatKamin)

___
*[`doc/pmemallocator.3.md` line 59 at r30](https://reviewable.io/reviews/memkind/memkind/839#-N9keKed4KhP7UK7CTPo:-NA4JLUO5P8V-Tm4qQPH:bjh8hxb) ([raw file](https://github.com/memkind/memkind/blob/c5697440459d82ff76189457ddcd8c63aa69736b/doc/pmemallocator.3.md#L59)):*
<details><summary><i>Previously, maciekpac wrote…</i></summary><blockquote>

bad formatting under reviewable; besides, is `**memkind**` link formatting consistent with others ? 
</blockquote></details>

Done. It should be good now


<!-- Sent from Reviewable.io -->

2022-08-22 13:08 UTC, PatKamin reviewed
> Reviewed 1 of 3 files at r34, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/839)* status: all files reviewed, 8 unresolved discussions (waiting on @lukaszstolarczuk and @maciekpac)



<!-- Sent from Reviewable.io -->

2022-08-22 13:16 UTC, lukaszstolarczuk reviewed
:+1: 

> Reviewed 1 of 8 files at r9, 1 of 2 files at r25, 1 of 42 files at r27, 2 of 27 files at r31, 1 of 3 files at r34, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/839#-:-NA4gV7r3Y1yhod2fnFL:b-8fx2u7)* status: all files reviewed, 5 unresolved discussions (waiting on @maciekpac)

___
*[`doc/autohbw.7.md` line 42 at r19](https://reviewable.io/reviews/memkind/memkind/839#-N9Ao5zBBRtqCjEbKHKQ:-NA4gXTv52_MEqUX4n06:beaiaro) ([raw file](https://github.com/memkind/memkind/blob/f35c2e6a7ed73a772f020adea1fe3dfb6fb0deb1/doc/autohbw.7.md#L42)):*
<details><summary><i>Previously, szadam (Adam Szopiński) wrote…</i></summary><blockquote>

I make it to look good on laptop monitor
</blockquote></details>

if you say so :smile: 


<!-- Sent from Reviewable.io -->

2022-08-22 13:23 UTC, maciekpac requested changes
> Reviewed 25 of 27 files at r31, 3 of 3 files at r34, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/839)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @szadam)

___
*[`Makefile.am` line 674 at r31](https://reviewable.io/reviews/memkind/memkind/839#-NA4Fjty8KPF7cqu3SOs:-NA4eAIX9DAhxwd05eB9:bq01vvb) ([raw file](https://github.com/memkind/memkind/blob/95cdb6ffc1b3e7dbf25a5ff822d40c4041369298/Makefile.am#L674)):*
<details><summary><i>Previously, szadam (Adam Szopiński) wrote…</i></summary><blockquote>

It is necessary
</blockquote></details>

It's not possible to just write the for loop in separate lines instead of adding semicolon and a backslash ? Just making sure
___
*[`doc/autohbw.7.md` line 42 at r19](https://reviewable.io/reviews/memkind/memkind/839#-N9Ao5zBBRtqCjEbKHKQ:-NA4esNI-bK6GH9RQBpx:b-5vcl4m) ([raw file](https://github.com/memkind/memkind/blob/f35c2e6a7ed73a772f020adea1fe3dfb6fb0deb1/doc/autohbw.7.md#L42)):*
<details><summary><i>Previously, szadam (Adam Szopiński) wrote…</i></summary><blockquote>

I make it to look good on laptop monitor
</blockquote></details>

I think 80 is the standard, but personally I think it's ok.
___
*[`doc/pmemallocator.3.md` line 59 at r30](https://reviewable.io/reviews/memkind/memkind/839#-N9keKed4KhP7UK7CTPo:-NA4hFVJ2THwY1t7aCvc:b-ns4pw9) ([raw file](https://github.com/memkind/memkind/blob/c5697440459d82ff76189457ddcd8c63aa69736b/doc/pmemallocator.3.md#L59)):*
<details><summary><i>Previously, szadam (Adam Szopiński) wrote…</i></summary><blockquote>

Done. It should be good now
</blockquote></details>

The *.html* part disappeared, but is present elsewhere, e.g. 

```markdown
`memtier_malloc()`
:   allocates *size* bytes of memory on one of the memory tiers defined by the
    *memory* parameter. See [**libmemtier**(7)](/memkind/manpages/libmemtier.7.html)
    for further details on memory tiers. `memkind_malloc()` is used for allocations.
    For further details on it’s behavior see
    [**memkind**(3)](/memkind/manpages/memkind.3.html).

`memtier_kind_malloc()`
:   is a wrapper to the `memkind_malloc()` function. See
    [**memkind**(3)](/memkind/manpages/memkind.3.html) for further details.

`memtier_calloc()`
:   allocates *num* times *size* bytes of memory on one of the memory tiers
    defined by the *memory* argument. `memkind_calloc()` is used for allocations.
    For further details on it’s behavior see [**memkind**(3)](/memkind/manpages/memkind.3.html).
```
(doc/libmemtier.3.md)

Which version is correct ?


<!-- Sent from Reviewable.io -->

2022-08-22 14:20 UTC, szadam reviewed
> Reviewed 2 of 27 files at r31.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/839)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @szadam)

___
*[`Makefile.am` line 674 at r31](https://reviewable.io/reviews/memkind/memkind/839#-NA4Fjty8KPF7cqu3SOs:-NA4sc443kaEJ-Tr1ZE2:b-unfzex) ([raw file](https://github.com/memkind/memkind/blob/95cdb6ffc1b3e7dbf25a5ff822d40c4041369298/Makefile.am#L674)):*
<details><summary><i>Previously, maciekpac wrote…</i></summary><blockquote>

It's not possible to just write the for loop in separate lines instead of adding semicolon and a backslash ? Just making sure
</blockquote></details>

I this case no. In other case: /bin/bash: -c: line 2: syntax error: unexpected end of file
___
*[`doc/pmemallocator.3.md` line 59 at r30](https://reviewable.io/reviews/memkind/memkind/839#-N9keKed4KhP7UK7CTPo:-NA4v1Un9IeAuGoBlu4j:b-7fi2g9) ([raw file](https://github.com/memkind/memkind/blob/c5697440459d82ff76189457ddcd8c63aa69736b/doc/pmemallocator.3.md#L59)):*
<details><summary><i>Previously, maciekpac wrote…</i></summary><blockquote>

The *.html* part disappeared, but is present elsewhere, e.g. 

```markdown
`memtier_malloc()`
:   allocates *size* bytes of memory on one of the memory tiers defined by the
    *memory* parameter. See [**libmemtier**(7)](/memkind/manpages/libmemtier.7.html)
    for further details on memory tiers. `memkind_malloc()` is used for allocations.
    For further details on it’s behavior see
    [**memkind**(3)](/memkind/manpages/memkind.3.html).

`memtier_kind_malloc()`
:   is a wrapper to the `memkind_malloc()` function. See
    [**memkind**(3)](/memkind/manpages/memkind.3.html) for further details.

`memtier_calloc()`
:   allocates *num* times *size* bytes of memory on one of the memory tiers
    defined by the *memory* argument. `memkind_calloc()` is used for allocations.
    For further details on it’s behavior see [**memkind**(3)](/memkind/manpages/memkind.3.html).
```
(doc/libmemtier.3.md)

Which version is correct ?
</blockquote></details>

both versions are correct :D


<!-- Sent from Reviewable.io -->

2022-08-22 14:23 UTC, maciekpac approved these changes
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/839)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @szadam)

___
*[`Makefile.am` line 674 at r31](https://reviewable.io/reviews/memkind/memkind/839#-NA4Fjty8KPF7cqu3SOs:-NA4vhPy8m7h5APO2DPZ:br1ul0n) ([raw file](https://github.com/memkind/memkind/blob/95cdb6ffc1b3e7dbf25a5ff822d40c4041369298/Makefile.am#L674)):*
<details><summary><i>Previously, szadam (Adam Szopiński) wrote…</i></summary><blockquote>

I this case no. In other case: /bin/bash: -c: line 2: syntax error: unexpected end of file
</blockquote></details>

Checked and it should be possible with .ONESHELL, but I think it's better to leave this code as is.


<!-- Sent from Reviewable.io -->

2022-08-22 14:26 UTC, maciekpac approved these changes
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/839)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @szadam)



<!-- Sent from Reviewable.io -->

2022-08-22 14:49 UTC, lukaszstolarczuk reviewed
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/839)* status: all files reviewed, 1 unresolved discussion (waiting on @szadam)

___
*[`man/autohbw.7` line 88 at r34](https://reviewable.io/reviews/memkind/memkind/839#-NA50lYlDgYoMVYuVgTN:-NA50lYlDgYoMVYuVgTO:bmsx4tv) ([raw file](https://github.com/memkind/memkind/blob/479ae2cf2376b47d46485ca5821f357ab4a805f0/man/autohbw.7#L88)):*
> ```Roff
> \f[B]MEMKIND_DEFAULT\f[R].
> The names of memory types are defined in
> \f[B]memkind\f[R](3) (/memkind/manpages/memkind.3.html) man page.
> ```

hmm - does this link look good in manpage format?


<!-- Sent from Reviewable.io -->

2022-08-22 19:12 UTC, szadam commented
*[`man/autohbw.7` line 88 at r34](https://reviewable.io/reviews/memkind/memkind/839#-NA50lYlDgYoMVYuVgTN:-NA5xYlv-rmBGBzLPMW9:bte469c) ([raw file](https://github.com/memkind/memkind/blob/479ae2cf2376b47d46485ca5821f357ab4a805f0/man/autohbw.7#L88)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

hmm - does this link look good in manpage format?
</blockquote></details>

It looks just fine (memkind(3) and link in bracket)


<!-- Sent from Reviewable.io -->

2022-08-22 19:13 UTC, szadam commented
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>





<!-- Sent from Reviewable.io -->

2022-08-23 06:09 UTC, PatKamin approved these changes
> Reviewed 2 of 42 files at r27, 9 of 42 files at r28, 4 of 9 files at r29, 23 of 27 files at r31, 2 of 3 files at r34.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/839)* status: all files reviewed, 1 unresolved discussion (waiting on @lukaszstolarczuk)



<!-- Sent from Reviewable.io -->

2022-08-23 06:10 UTC, PatKamin approved these changes
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/839)* status: all files reviewed, 1 unresolved discussion (waiting on @lukaszstolarczuk)



<!-- Sent from Reviewable.io -->

2022-08-23 06:11 UTC, merged