Add Release Steps guide
memkind/memkind pull request #862
Opened 2022-12-23 10:44 UTC by lukaszstolarczuk

to have all steps and tips on doing releases written down in the repository.

Co-authored-by: Patryk Kaminski <patryk.kaminski@intel.com>
Co-authored-by: michalbiesek <michal.biesek@intel.com>

### Types of changes

- [ ] Bugfix (non-breaking change which fixes issue linked in Description above)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Documentation (correction or otherwise)
- [ ] Cosmetics (whitespace, appearance)
- [ ] Other

### Checklist

- [ ] Code compiles without errors
- [ ] All tests pass locally with my changes (see TESTING section in CONTRIBUTING file)
- [ ] Created tests which will fail without the change (if possible)
- [x] Extended the README/documentation (if necessary)
- [ ] All newly added files have proprietary license (if necessary)
- [ ] All newly added files are referenced in MANIFEST files (if necessary)

2022-12-28 09:21 UTC, szadam requested changes
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/862)* status: all files reviewed, 3 unresolved discussions (waiting on @lukaszstolarczuk)

___
*[`doc/RELEASE_STEPS.md` line 16 at r1](https://reviewable.io/reviews/memkind/memkind/862#-NKN0K90Bu6AZbZfX8rf:-NKN0K90Bu6AZbZfX8rg:b-shcayv) ([raw file](https://github.com/memkind/memkind/blob/0dd329e6c51f850cb895774cccee3e58f16e9981/doc/RELEASE_STEPS.md#L16)):*
> ```Markdown
> - add `VERSION` file with memkind version to-be-released
> - update `MEMKIND_VERSION_*` defines in [src/memkind.c](../src/memkind.c#L4-L6)
> - add annotated tag for commit and push tag to the upstream
> ```

push THIS tag
___
*[`doc/RELEASE_STEPS.md` line 18 at r1](https://reviewable.io/reviews/memkind/memkind/862#-NKN-wSTBjl2i6K-liPd:-NKN-wSTBjl2i6K-liPe:b-racfr8) ([raw file](https://github.com/memkind/memkind/blob/0dd329e6c51f850cb895774cccee3e58f16e9981/doc/RELEASE_STEPS.md#L18)):*
> ```Markdown
> - add annotated tag for commit and push tag to the upstream
> 
> To see example how this change should be done, look at one of the previous releases:
> ```

an example
___
*[`doc/RELEASE_STEPS.md` line 29 at r1](https://reviewable.io/reviews/memkind/memkind/862#-NKN-qsO2jDNqTkHP5xi:-NKN-qsP3J3vCrgV0b4N:b-racfr8) ([raw file](https://github.com/memkind/memkind/blob/0dd329e6c51f850cb895774cccee3e58f16e9981/doc/RELEASE_STEPS.md#L29)):*
> ```Markdown
> 
> Remove VERSION file after making a release.
> To see example how this change should be done, look at
> ```

an example


<!-- Sent from Reviewable.io -->

2022-12-28 11:32 UTC, lukaszstolarczuk reviewed
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/862)* status: all files reviewed, 3 unresolved discussions (waiting on @szadam)

___
*[`doc/RELEASE_STEPS.md` line 16 at r1](https://reviewable.io/reviews/memkind/memkind/862#-NKN0K90Bu6AZbZfX8rf:-NKNUdNIE7khh_swZ_iQ:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/0dd329e6c51f850cb895774cccee3e58f16e9981/doc/RELEASE_STEPS.md#L16)):*
<details><summary><i>Previously, szadam (Adam Szopiński) wrote…</i></summary><blockquote>

push THIS tag
</blockquote></details>

Done.
___
*[`doc/RELEASE_STEPS.md` line 18 at r1](https://reviewable.io/reviews/memkind/memkind/862#-NKN-wSTBjl2i6K-liPd:-NKNUdeS3XvWA_lXqlf6:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/0dd329e6c51f850cb895774cccee3e58f16e9981/doc/RELEASE_STEPS.md#L18)):*
<details><summary><i>Previously, szadam (Adam Szopiński) wrote…</i></summary><blockquote>

an example
</blockquote></details>

Done.
___
*[`doc/RELEASE_STEPS.md` line 29 at r1](https://reviewable.io/reviews/memkind/memkind/862#-NKN-qsO2jDNqTkHP5xi:-NKNUe4a-rH8l9S0QkQh:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/0dd329e6c51f850cb895774cccee3e58f16e9981/doc/RELEASE_STEPS.md#L29)):*
<details><summary><i>Previously, szadam (Adam Szopiński) wrote…</i></summary><blockquote>

an example
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-01-02 08:01 UTC, PatKamin approved these changes

2023-01-04 08:59 UTC, szadam approved these changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/862)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @lukaszstolarczuk)



<!-- Sent from Reviewable.io -->

2023-01-05 10:43 UTC, merged